-- İngilis yeni dövr(lər): en-c7-, en-c8-
begin;

delete from tasks where lesson_id in ('en-gr-l7', 'en-gr-l8');
delete from lessons where id in ('en-gr-l7', 'en-gr-l8');
delete from units where id in ('en-grammar');

insert into units (id, subject_id, title, description, sort_order) values
  ('en-c1-grammar', 'ingilis-dili', 'Qayda: Present Simple', 'İndiki sadə zaman — hər gün təkrarlanan işlər. Qaydanı oxu, sonra məşq et.', 0),
  ('en-c1-vocab', 'ingilis-dili', 'Lüğət: Gündəlik fellər', '8 yeni fel — eyni sözləri müxtəlif cümlələrdə təkrar-təkrar işlət.', 1),
  ('en-c1-listening', 'ingilis-dili', 'Dinləmə: Present Simple', 'Present Simple cümlələrini qulaqla tanı — dinlə və düzgün mənanı seç.', 2),
  ('en-c1-reading', 'ingilis-dili', 'Oxu: Mənim günüm', 'Qısa mətni oxu və suallara cavab ver (Present Simple).', 3),
  ('en-c1-writing', 'ingilis-dili', 'Yazı: Present Simple', 'Sözlərdən düzgün Present Simple cümləsi qur.', 4),
  ('en-c2-grammar', 'ingilis-dili', 'Qayda: Present Continuous', 'İndi, danışıq anında baş verən işlər. Qaydanı oxu, sonra məşq et.', 5),
  ('en-c2-vocab', 'ingilis-dili', 'Lüğət: İndi görülən işlər', '8 yeni fel — run, write, sleep, cook, sing, dance, swim, sit.', 6),
  ('en-c2-listening', 'ingilis-dili', 'Dinləmə: Present Continuous', 'İndi baş verən işlərin cümlələrini dinlə və düzgün mənanı seç.', 7),
  ('en-c2-reading', 'ingilis-dili', 'Oxu: In the park', 'Qısa mətni oxu və suallara cavab ver (Present Continuous).', 8),
  ('en-c2-writing', 'ingilis-dili', 'Yazı: Present Continuous', 'Sözlərdən düzgün Present Continuous cümləsi qur.', 9),
  ('en-c3-grammar', 'ingilis-dili', 'Qayda: Past Simple', 'Keçmişdə bitmiş işlər. Qaydalı (-ed) və qaydasız fellər.', 10),
  ('en-c3-vocab', 'ingilis-dili', 'Lüğət: Keçmiş işlər', '8 yeni fel — visit, help, clean, wash, walk, talk, want, call.', 11),
  ('en-c3-listening', 'ingilis-dili', 'Dinləmə: Past Simple', 'Keçmiş işlərin cümlələrini dinlə və düzgün mənanı seç.', 12),
  ('en-c3-reading', 'ingilis-dili', 'Oxu: My weekend', 'Keçmiş haqqında qısa mətni oxu və suallara cavab ver (Past Simple).', 13),
  ('en-c3-writing', 'ingilis-dili', 'Yazı: Past Simple', 'Sözlərdən düzgün Past Simple cümləsi qur.', 14),
  ('en-c4-grammar', 'ingilis-dili', 'Qayda: Sual və inkar', 'Sual (do/does/did) və inkar (don''t/doesn''t/didn''t) cümlələri.', 15),
  ('en-c4-vocab', 'ingilis-dili', 'Lüğət: Sual sözləri', '6 sual sözü: what, where, when, who, why, how.', 16),
  ('en-c4-listening', 'ingilis-dili', 'Dinləmə: Sual və inkar', 'Sual və inkar cümlələrini dinlə və düzgün mənanı seç.', 17),
  ('en-c4-reading', 'ingilis-dili', 'Oxu: An interview', 'Qısa müsahibəni oxu və suallara cavab ver (sual-cavab).', 18),
  ('en-c4-writing', 'ingilis-dili', 'Yazı: Sual və inkar', 'Sözlərdən düzgün sual və inkar cümləsi qur.', 19),
  ('en-c5-grammar', 'ingilis-dili', 'Qayda: Əvəzliklər', 'Şəxs (I, you, he...) və yiyəlik (my, your, his...) əvəzlikləri.', 20),
  ('en-c5-vocab', 'ingilis-dili', 'Lüğət: Əvəzliklər', 'Şəxs və yiyəlik əvəzlikləri: I/he/she/we/they, my/your/her...', 21),
  ('en-c5-listening', 'ingilis-dili', 'Dinləmə: Əvəzliklər', 'Əvəzlikli cümlələri dinlə və düzgün mənanı seç.', 22),
  ('en-c5-reading', 'ingilis-dili', 'Oxu: My family', 'Ailə haqqında mətni oxu və suallara cavab ver (əvəzliklər).', 23),
  ('en-c5-writing', 'ingilis-dili', 'Yazı: Əvəzliklər', 'Sözlərdən əvəzlikli cümlə qur.', 24),
  ('en-c6-grammar', 'ingilis-dili', 'Qayda: Artikllar (a / an / the)', 'Qeyri-müəyyən (a/an) və müəyyən (the) artikllar.', 25),
  ('en-c6-vocab', 'ingilis-dili', 'Lüğət: Əşyalar', '8 yeni isim: orange, egg, umbrella, elephant, banana, pen, car, box.', 26),
  ('en-c6-listening', 'ingilis-dili', 'Dinləmə: Artikllar', 'Artikllı cümlələri dinlə və düzgün mənanı seç.', 27),
  ('en-c6-reading', 'ingilis-dili', 'Oxu: A day at the zoo', 'Heyvanxana haqqında mətni oxu və suallara cavab ver (artikllar).', 28),
  ('en-c6-writing', 'ingilis-dili', 'Yazı: Artikllar', 'Sözlərdən artikllı cümlə qur.', 29),
  ('en-c7-grammar', 'ingilis-dili', 'Qayda: Sifət dərəcələri', 'Müqayisə (-er / more) və üstünlük (-est / most) dərəcələri.', 30),
  ('en-c7-vocab', 'ingilis-dili', 'Lüğət: Sifətlər', '8 yeni sifət: tall, short, fast, slow, strong, young, clever, heavy.', 31),
  ('en-c7-listening', 'ingilis-dili', 'Dinləmə: Sifət dərəcələri', 'Müqayisə cümlələrini dinlə və düzgün mənanı seç.', 32),
  ('en-c7-reading', 'ingilis-dili', 'Oxu: Animals', 'Heyvanlar haqqında mətni oxu və suallara cavab ver (müqayisə).', 33),
  ('en-c7-writing', 'ingilis-dili', 'Yazı: Sifət dərəcələri', 'Sözlərdən müqayisə cümləsi qur.', 34),
  ('en-c8-grammar', 'ingilis-dili', 'Qayda: Modal fellər', 'can (bacarıq), must (məcburiyyət), should (məsləhət).', 35),
  ('en-c8-vocab', 'ingilis-dili', 'Lüğət: Bacarıq felləri', '8 yeni fel: jump, climb, fly, draw, drive, fix, ride, count.', 36),
  ('en-c8-listening', 'ingilis-dili', 'Dinləmə: Modal fellər', 'Modal cümlələri dinlə və düzgün mənanı seç.', 37),
  ('en-c8-reading', 'ingilis-dili', 'Oxu: School rules', 'Məktəb qaydaları haqqında mətni oxu və suallara cavab ver (modallar).', 38),
  ('en-c8-writing', 'ingilis-dili', 'Yazı: Modal fellər', 'Sözlərdən modal fellə cümlə qur.', 39),
  ('en-nouns', 'ingilis-dili', 'İsimlər (Nouns)', 'İsim nədir, cəm forması, sayıla bilən və sayıla bilməyən isimlər.', 40),
  ('en-vocab', 'ingilis-dili', 'Söz ehtiyatı (Vocabulary)', 'Gündəlik həyatla bağlı mövzular: ailə, məktəb, təbiət, qida, şəhər və hobbilər.', 41)
on conflict (id) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order;

insert into lessons (id, unit_id, title, intro, visual, sections, sort_order) values
  ('comp-rule', 'en-c7-grammar', 'Sifət dərəcələri qaydası', 'İki və ya daha çox şeyi müqayisə edək. Gəl öyrənək!', null, '[{"heading":"Müqayisə dərəcəsi (-er / more)","body":"İki şeyi müqayisə edərkən: tall → taller, big → bigger. Uzun sözlərdə ''more'': beautiful → more beautiful. ''than'' ilə: Tom is taller than Sam."},{"heading":"Üstünlük dərəcəsi (-est / most)","body":"Ən yüksək dərəcə: tall → the tallest, big → the biggest. Uzun sözlərdə ''the most'': the most beautiful."},{"heading":"Qeyri-qaydalı","body":"good → better → the best. bad → worse → the worst."}]'::jsonb, 0),
  ('comp-vocab', 'en-c7-vocab', 'Sifətlər (8 söz)', 'Müqayisə üçün 8 yeni sifət öyrənək.', null, '[{"heading":"Yeni sözlər (8 sifət)","body":"tall — hündür · short — qısa/alçaq · fast — sürətli · slow — yavaş · strong — güclü · young — gənc/cavan · clever — ağıllı · heavy — ağır"},{"heading":"Məsləhət","body":"Bu sifətlərin müqayisə formasını da yadda saxla: taller, faster, stronger, heavier..."}]'::jsonb, 0),
  ('comp-listen', 'en-c7-listening', 'Dinlə və seç: müqayisə', 'Cümləni dinlə və düzgün cavabı seç.', null, '[{"heading":"Necə işləyir?","body":"«Dinlə» düyməsinə bas, cümləni eşit və düzgün variantı seç. İstədiyin qədər təkrar dinlə."}]'::jsonb, 0),
  ('comp-read', 'en-c7-reading', 'Reading: Animals', 'Qısa mətni oxu və suallara cavab ver.', null, '[{"heading":"Read the text (Mətni oxu)","body":"Animals are different. The cheetah is the fastest animal. It can run very fast. The elephant is the biggest animal on land. It is very heavy. The giraffe is the tallest animal. Its neck is very long. A mouse is smaller than a cat, but a cat is smaller than a dog. The blue whale is the biggest animal in the world."},{"heading":"İpucu","body":"Sualı oxu, cavabı mətndə tap. Lazım olsa mətnə yenidən bax."}]'::jsonb, 0),
  ('comp-write', 'en-c7-writing', 'Cümlə qur: müqayisə', 'Sözləri düzgün sıraya düz və müqayisə cümləsi qur.', null, '[{"heading":"Necə işləyir?","body":"Sözlərə sıra ilə bas. Müqayisə: X is + sifət-er + than + Y. Üstünlük: the + sifət-est."}]'::jsonb, 0),
  ('modal-rule', 'en-c8-grammar', 'Modal fellər qaydası', 'can, must, should — modal fellər. Nə vaxt hansını işlətməli?', null, '[{"heading":"can — bacarıq / icazə","body":"Bir işi bacarmaq və ya icazə: I can swim. Can I go? Modaldan sonra fel əsas formadadır (can swim, NOT can swims)."},{"heading":"must — məcburiyyət","body":"Vacib, məcburi iş: You must stop. İnkar mustn''t = qadağan: You mustn''t run here."},{"heading":"should — məsləhət","body":"Tövsiyə/məsləhət: You should sleep early. İnkar shouldn''t: You shouldn''t eat too much."}]'::jsonb, 0),
  ('modal-vocab', 'en-c8-vocab', 'Bacarıq felləri (8 söz)', '''can'' ilə işlədəcəyimiz 8 yeni fel öyrənək.', null, '[{"heading":"Yeni sözlər (8 fel)","body":"jump — tullanmaq · climb — dırmaşmaq · fly — uçmaq · draw — rəsm çəkmək · drive — sürmək · fix — təmir etmək · ride — minmək · count — saymaq"},{"heading":"Məsləhət","body":"Bu felləri ''can'' ilə işlət: I can jump. She can draw. A bird can fly."}]'::jsonb, 0),
  ('modal-listen', 'en-c8-listening', 'Dinlə və seç: can / must / should', 'Cümləni dinlə və düzgün cavabı seç.', null, '[{"heading":"Necə işləyir?","body":"«Dinlə» düyməsinə bas, cümləni eşit və düzgün variantı seç. İstədiyin qədər təkrar dinlə."}]'::jsonb, 0),
  ('modal-read', 'en-c8-reading', 'Reading: School rules', 'Qısa mətni oxu və suallara cavab ver.', null, '[{"heading":"Read the text (Mətni oxu)","body":"At our school there are some rules. You must come to school on time. You must listen to the teacher. You should do your homework every day. You can play in the yard at break time. You mustn''t run in the classroom. You shouldn''t shout. Good students always follow the rules."},{"heading":"İpucu","body":"Sualı oxu, cavabı mətndə tap. Lazım olsa mətnə yenidən bax."}]'::jsonb, 0),
  ('modal-write', 'en-c8-writing', 'Cümlə qur: can / must / should', 'Sözləri düzgün sıraya düz və modal cümlə qur.', null, '[{"heading":"Necə işləyir?","body":"Sözlərə sıra ilə bas. Quruluş: kim + modal (can/must/should) + fel (əsas forma)."}]'::jsonb, 0)
on conflict (id) do update set unit_id = excluded.unit_id, title = excluded.title, intro = excluded.intro, visual = excluded.visual, sections = excluded.sections, sort_order = excluded.sort_order;

insert into tasks (id, lesson_id, type, prompt, data, xp, sort_order) values
  ('comp-rule-t1', 'comp-rule', 'multiple_choice', '''Tom is ___ than Sam.'' (tall)', '{"speakOptions":true,"options":["tall","taller","tallest","more tall"],"correctIndex":1}'::jsonb, 10, 0),
  ('comp-rule-t2', 'comp-rule', 'multiple_choice', '''This box is ___ than that one.'' (big)', '{"speakOptions":true,"options":["big","bigger","biggest","more big"],"correctIndex":1}'::jsonb, 10, 1),
  ('comp-rule-t3', 'comp-rule', 'multiple_choice', '''She is the ___ girl in the class.'' (tall)', '{"speakOptions":true,"options":["tall","taller","tallest","more tall"],"correctIndex":2}'::jsonb, 10, 2),
  ('comp-rule-t4', 'comp-rule', 'multiple_choice', '''A car is ___ than a bike.'' (fast)', '{"speakOptions":true,"options":["fast","faster","fastest","more fast"],"correctIndex":1}'::jsonb, 10, 3),
  ('comp-rule-t5', 'comp-rule', 'multiple_choice', '''good'' müqayisə forması?', '{"speakOptions":true,"options":["gooder","better","more good","best"],"correctIndex":1}'::jsonb, 10, 4),
  ('comp-rule-t6', 'comp-rule', 'fill_blank', '''small'' sözünün müqayisə forması (-er)?', '{"accepted":["smaller"]}'::jsonb, 10, 5),
  ('comp-rule-t7', 'comp-rule', 'multiple_choice', '''Everest is the ___ mountain.'' (high)', '{"speakOptions":true,"options":["high","higher","highest","more high"],"correctIndex":2}'::jsonb, 10, 6),
  ('comp-rule-t8', 'comp-rule', 'multiple_choice', '''This book is ___ than that one.'' (interesting)', '{"speakOptions":true,"options":["interestinger","more interesting","most interesting","interesting"],"correctIndex":1}'::jsonb, 10, 7),
  ('comp-rule-t9', 'comp-rule', 'multiple_choice', 'Müqayisə üçün hansı söz işlənir?', '{"speakOptions":true,"options":["than","then","that","the"],"correctIndex":0}'::jsonb, 10, 8),
  ('comp-rule-t10', 'comp-rule', 'fill_blank', '''old'' sözünün üstünlük forması (the ___)?', '{"accepted":["oldest"]}'::jsonb, 15, 9),
  ('comp-rule-b1', 'comp-rule', 'multiple_choice', '''bad'' üstünlük forması?', '{"bonus":true,"speakOptions":true,"options":["baddest","worst","more bad","worse"],"correctIndex":1}'::jsonb, 15, 10),
  ('comp-rule-b2', 'comp-rule', 'multiple_choice', '''An elephant is ___ than a cat.'' (big)', '{"bonus":true,"speakOptions":true,"options":["big","bigger","biggest","more big"],"correctIndex":1}'::jsonb, 15, 11),
  ('comp-rule-b3', 'comp-rule', 'fill_blank', '''fast'' sözünün üstünlük forması (the ___)?', '{"bonus":true,"accepted":["fastest"]}'::jsonb, 15, 12),
  ('comp-vocab-t1', 'comp-vocab', 'multiple_choice', '''tall'' sözünün mənası?', '{"options":["hündür","alçaq","sürətli","yavaş"],"correctIndex":0}'::jsonb, 10, 0),
  ('comp-vocab-t2', 'comp-vocab', 'multiple_choice', '''fast'' sözünün mənası?', '{"options":["sürətli","yavaş","güclü","ağır"],"correctIndex":0}'::jsonb, 10, 1),
  ('comp-vocab-t3', 'comp-vocab', 'multiple_choice', '''slow'' sözünün mənası?', '{"options":["yavaş","sürətli","hündür","gənc"],"correctIndex":0}'::jsonb, 10, 2),
  ('comp-vocab-t4', 'comp-vocab', 'multiple_choice', '''strong'' sözünün mənası?', '{"options":["güclü","zəif","ağıllı","gənc"],"correctIndex":0}'::jsonb, 10, 3),
  ('comp-vocab-t5', 'comp-vocab', 'multiple_choice', '''young'' sözünün mənası?', '{"options":["gənc / cavan","qoca","hündür","ağır"],"correctIndex":0}'::jsonb, 10, 4),
  ('comp-vocab-t6', 'comp-vocab', 'multiple_choice', '''clever'' sözünün mənası?', '{"options":["ağıllı","güclü","sürətli","hündür"],"correctIndex":0}'::jsonb, 10, 5),
  ('comp-vocab-t7', 'comp-vocab', 'fill_blank', '''ağır'' ingiliscə necə yazılır?', '{"accepted":["heavy"]}'::jsonb, 10, 6),
  ('comp-vocab-t8', 'comp-vocab', 'fill_blank', '''qısa / alçaq'' ingiliscə necə yazılır?', '{"accepted":["short"]}'::jsonb, 10, 7),
  ('comp-vocab-t9', 'comp-vocab', 'multiple_choice', '''A giraffe is very ___.'' (hündür)', '{"speakOptions":true,"options":["tall","short","slow","heavy"],"correctIndex":0}'::jsonb, 10, 8),
  ('comp-vocab-t10', 'comp-vocab', 'multiple_choice', '''A turtle is ___.'' (yavaş)', '{"speakOptions":true,"options":["slow","fast","tall","strong"],"correctIndex":0}'::jsonb, 15, 9),
  ('comp-vocab-b1', 'comp-vocab', 'multiple_choice', '''heavy'' sözünün mənası?', '{"bonus":true,"options":["ağır","yüngül","sürətli","ağıllı"],"correctIndex":0}'::jsonb, 15, 10),
  ('comp-vocab-b2', 'comp-vocab', 'multiple_choice', '''short'' sözünün mənası?', '{"bonus":true,"options":["qısa / alçaq","hündür","güclü","gənc"],"correctIndex":0}'::jsonb, 15, 11),
  ('comp-vocab-b3', 'comp-vocab', 'multiple_choice', '''A lion is ___.'' (güclü)', '{"bonus":true,"speakOptions":true,"options":["strong","weak","slow","short"],"correctIndex":0}'::jsonb, 15, 12),
  ('comp-listen-t1', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"Tom is taller than Sam.","options":["Tom Samdan hündürdür.","Tom Samdan alçaqdır.","Sam Tomdan hündürdür.","Tom və Sam eyni boydadır."],"correctIndex":0}'::jsonb, 10, 0),
  ('comp-listen-t2', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"A car is faster than a bike.","options":["Maşın velosipeddən sürətlidir.","Velosiped maşından sürətlidir.","Maşın velosipeddən yavaşdır.","Maşın və velosiped eynidir."],"correctIndex":0}'::jsonb, 10, 1),
  ('comp-listen-t3', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"This box is bigger.","options":["Bu qutu daha böyükdür.","Bu qutu daha kiçikdir.","Bu qutu ağırdır.","Bu qutu yüngüldür."],"correctIndex":0}'::jsonb, 10, 2),
  ('comp-listen-t4', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"She is the best student.","options":["O ən yaxşı şagirddir.","O ən pis şagirddir.","O yaxşı şagirddir.","O yeni şagirddir."],"correctIndex":0}'::jsonb, 10, 3),
  ('comp-listen-t5', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"An elephant is heavy.","options":["Fil ağırdır.","Fil yüngüldür.","Pişik ağırdır.","Fil sürətlidir."],"correctIndex":0}'::jsonb, 10, 4),
  ('comp-listen-t6', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"A turtle is slow.","options":["Tısbağa yavaşdır.","Tısbağa sürətlidir.","Dovşan yavaşdır.","Tısbağa güclüdür."],"correctIndex":0}'::jsonb, 10, 5),
  ('comp-listen-t7', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"He is stronger than me.","options":["O məndən güclüdür.","O məndən zəifdir.","Mən ondan güclüyəm.","Biz eyni güclüyük."],"correctIndex":0}'::jsonb, 10, 6),
  ('comp-listen-t8', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"This is the tallest tree.","options":["Bu ən hündür ağacdır.","Bu ən alçaq ağacdır.","Bu hündür ağacdır.","Bu qısa ağacdır."],"correctIndex":0}'::jsonb, 15, 7),
  ('comp-listen-b1', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"bonus":true,"audioText":"A plane is faster than a car.","options":["Təyyarə maşından sürətlidir.","Maşın təyyarədən sürətlidir.","Təyyarə maşından yavaşdır.","Təyyarə və maşın eynidir."],"correctIndex":0}'::jsonb, 15, 8),
  ('comp-listen-b2', 'comp-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"bonus":true,"audioText":"She is younger than her brother.","options":["O qardaşından cavandır.","O qardaşından böyükdür.","O qardaşı ilə eyni yaşdadır.","Qardaşı ondan cavandır."],"correctIndex":0}'::jsonb, 15, 9),
  ('comp-read-t1', 'comp-read', 'multiple_choice', 'Which is the fastest animal?', '{"speakOptions":true,"options":["the elephant","the cheetah","the giraffe","the mouse"],"correctIndex":1}'::jsonb, 10, 0),
  ('comp-read-t2', 'comp-read', 'multiple_choice', 'Which is the biggest animal on land?', '{"speakOptions":true,"options":["the giraffe","the elephant","the cheetah","the mouse"],"correctIndex":1}'::jsonb, 10, 1),
  ('comp-read-t3', 'comp-read', 'multiple_choice', 'Which is the tallest animal?', '{"speakOptions":true,"options":["the elephant","the giraffe","the cheetah","the whale"],"correctIndex":1}'::jsonb, 10, 2),
  ('comp-read-t4', 'comp-read', 'multiple_choice', 'Is a mouse bigger than a cat?', '{"speakOptions":true,"options":["Yes.","No, it is smaller.","They are the same.","We don''t know."],"correctIndex":1}'::jsonb, 10, 3),
  ('comp-read-t5', 'comp-read', 'multiple_choice', 'What is the biggest animal in the world?', '{"speakOptions":true,"options":["the elephant","the blue whale","the giraffe","the cheetah"],"correctIndex":1}'::jsonb, 10, 4),
  ('comp-read-t6', 'comp-read', 'fill_blank', '''The giraffe is the ___ animal.'' (ən hündür — mətndən)', '{"accepted":["tallest"]}'::jsonb, 10, 5),
  ('comp-read-t7', 'comp-read', 'multiple_choice', '''The elephant is very ___.''', '{"speakOptions":true,"options":["heavy","light","small","fast"],"correctIndex":0}'::jsonb, 10, 6),
  ('comp-read-t8', 'comp-read', 'multiple_choice', 'A cat is smaller than a ___.', '{"speakOptions":true,"options":["mouse","dog","elephant","giraffe"],"correctIndex":1}'::jsonb, 15, 7),
  ('comp-read-b1', 'comp-read', 'multiple_choice', '''neck'' nə deməkdir?', '{"bonus":true,"options":["boyun","ayaq","qol","quyruq"],"correctIndex":0}'::jsonb, 15, 8),
  ('comp-read-b2', 'comp-read', 'fill_blank', '''The cheetah is the ___ animal.'' (ən sürətli — mətndən)', '{"bonus":true,"accepted":["fastest"]}'::jsonb, 15, 9),
  ('comp-write-t1', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["Tom","is","taller","than","Sam"],"answer":"Tom is taller than Sam","translation":"Tom Samdan hündürdür."}'::jsonb, 10, 0),
  ('comp-write-t2', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["A","car","is","faster"],"answer":"A car is faster","translation":"Maşın daha sürətlidir."}'::jsonb, 10, 1),
  ('comp-write-t3', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["This","box","is","bigger"],"answer":"This box is bigger","translation":"Bu qutu daha böyükdür."}'::jsonb, 10, 2),
  ('comp-write-t4', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["She","is","the","best"],"answer":"She is the best","translation":"O ən yaxşıdır."}'::jsonb, 10, 3),
  ('comp-write-t5', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["An","elephant","is","heavy"],"answer":"An elephant is heavy","translation":"Fil ağırdır."}'::jsonb, 10, 4),
  ('comp-write-t6', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["A","turtle","is","slow"],"answer":"A turtle is slow","translation":"Tısbağa yavaşdır."}'::jsonb, 10, 5),
  ('comp-write-t7', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["He","is","stronger","than","me"],"answer":"He is stronger than me","translation":"O məndən güclüdür."}'::jsonb, 10, 6),
  ('comp-write-t8', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["This","tree","is","the","tallest"],"answer":"This tree is the tallest","translation":"Bu ağac ən hündürdür."}'::jsonb, 15, 7),
  ('comp-write-b1', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["A","plane","is","fast"],"answer":"A plane is fast","translation":"Təyyarə sürətlidir."}'::jsonb, 15, 8),
  ('comp-write-b2', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["She","is","younger","than","me"],"answer":"She is younger than me","translation":"O məndən cavandır."}'::jsonb, 15, 9),
  ('comp-write-b3', 'comp-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["This","is","the","biggest","box"],"answer":"This is the biggest box","translation":"Bu ən böyük qutudur."}'::jsonb, 15, 10),
  ('modal-rule-t1', 'modal-rule', 'multiple_choice', '''I ___ swim very well.'' (bacarıq)', '{"speakOptions":true,"options":["can","must","should","am"],"correctIndex":0}'::jsonb, 10, 0),
  ('modal-rule-t2', 'modal-rule', 'multiple_choice', '''You ___ stop at a red light.'' (məcburi)', '{"speakOptions":true,"options":["can","must","should","may"],"correctIndex":1}'::jsonb, 10, 1),
  ('modal-rule-t3', 'modal-rule', 'multiple_choice', '''You ___ sleep early.'' (məsləhət)', '{"speakOptions":true,"options":["can","must","should","do"],"correctIndex":2}'::jsonb, 10, 2),
  ('modal-rule-t4', 'modal-rule', 'multiple_choice', 'Modaldan sonra fel hansı formada olur?', '{"options":["əsas forma","-s","-ing","-ed"],"correctIndex":0}'::jsonb, 10, 3),
  ('modal-rule-t5', 'modal-rule', 'multiple_choice', '''Birds ___ fly.''', '{"speakOptions":true,"options":["can","must","should","are"],"correctIndex":0}'::jsonb, 10, 4),
  ('modal-rule-t6', 'modal-rule', 'multiple_choice', '''___ I open the window?'' (icazə)', '{"speakOptions":true,"options":["Can","Must","Should","Do"],"correctIndex":0}'::jsonb, 10, 5),
  ('modal-rule-t7', 'modal-rule', 'multiple_choice', '''You ___ run in the hospital.'' (qadağa)', '{"speakOptions":true,"options":["can","mustn''t","should","may"],"correctIndex":1}'::jsonb, 10, 6),
  ('modal-rule-t8', 'modal-rule', 'multiple_choice', '''She ___ drive a car.'' (bacarır)', '{"speakOptions":true,"options":["can","must","should","is"],"correctIndex":0}'::jsonb, 10, 7),
  ('modal-rule-t9', 'modal-rule', 'multiple_choice', '''You ___ eat too much sugar.'' (məsləhət — inkar)', '{"speakOptions":true,"options":["shouldn''t","can","must","do"],"correctIndex":0}'::jsonb, 10, 8),
  ('modal-rule-t10', 'modal-rule', 'fill_blank', '''bacarmaq'' mənasını verən modal fel?', '{"accepted":["can"]}'::jsonb, 15, 9),
  ('modal-rule-b1', 'modal-rule', 'multiple_choice', '''Fish ___ swim.''', '{"bonus":true,"speakOptions":true,"options":["can","must","should","are"],"correctIndex":0}'::jsonb, 15, 10),
  ('modal-rule-b2', 'modal-rule', 'multiple_choice', '''We ___ help our friends.'' (məsləhət)', '{"bonus":true,"speakOptions":true,"options":["should","mustn''t","can''t","do"],"correctIndex":0}'::jsonb, 15, 11),
  ('modal-rule-b3', 'modal-rule', 'fill_blank', '''məcburiyyət'' bildirən modal fel?', '{"bonus":true,"accepted":["must"]}'::jsonb, 15, 12),
  ('modal-vocab-t1', 'modal-vocab', 'multiple_choice', '''jump'' sözünün mənası?', '{"options":["tullanmaq","dırmaşmaq","uçmaq","sürmək"],"correctIndex":0}'::jsonb, 10, 0),
  ('modal-vocab-t2', 'modal-vocab', 'multiple_choice', '''climb'' sözünün mənası?', '{"options":["dırmaşmaq","tullanmaq","minmək","saymaq"],"correctIndex":0}'::jsonb, 10, 1),
  ('modal-vocab-t3', 'modal-vocab', 'multiple_choice', '''fly'' sözünün mənası?', '{"options":["uçmaq","üzmək","qaçmaq","tullanmaq"],"correctIndex":0}'::jsonb, 10, 2),
  ('modal-vocab-t4', 'modal-vocab', 'multiple_choice', '''draw'' sözünün mənası?', '{"options":["rəsm çəkmək","yazmaq","oxumaq","sürmək"],"correctIndex":0}'::jsonb, 10, 3),
  ('modal-vocab-t5', 'modal-vocab', 'multiple_choice', '''drive'' sözünün mənası?', '{"options":["sürmək","minmək","uçmaq","təmir etmək"],"correctIndex":0}'::jsonb, 10, 4),
  ('modal-vocab-t6', 'modal-vocab', 'multiple_choice', '''fix'' sözünün mənası?', '{"options":["təmir etmək","sürmək","saymaq","dırmaşmaq"],"correctIndex":0}'::jsonb, 10, 5),
  ('modal-vocab-t7', 'modal-vocab', 'fill_blank', '''minmək'' ingiliscə necə yazılır?', '{"accepted":["ride"]}'::jsonb, 10, 6),
  ('modal-vocab-t8', 'modal-vocab', 'fill_blank', '''saymaq'' ingiliscə necə yazılır?', '{"accepted":["count"]}'::jsonb, 10, 7),
  ('modal-vocab-t9', 'modal-vocab', 'multiple_choice', '''A bird can ___.'' (uçmaq)', '{"speakOptions":true,"options":["fly","swim","drive","count"],"correctIndex":0}'::jsonb, 10, 8),
  ('modal-vocab-t10', 'modal-vocab', 'multiple_choice', '''I can ___ a bike.'' (minmək)', '{"speakOptions":true,"options":["ride","fly","draw","fix"],"correctIndex":0}'::jsonb, 15, 9),
  ('modal-vocab-b1', 'modal-vocab', 'multiple_choice', '''count'' sözünün mənası?', '{"bonus":true,"options":["saymaq","çəkmək","sürmək","uçmaq"],"correctIndex":0}'::jsonb, 15, 10),
  ('modal-vocab-b2', 'modal-vocab', 'multiple_choice', '''ride'' sözünün mənası?', '{"bonus":true,"options":["minmək","tullanmaq","uçmaq","saymaq"],"correctIndex":0}'::jsonb, 15, 11),
  ('modal-vocab-b3', 'modal-vocab', 'multiple_choice', '''She can ___ a picture.'' (rəsm çəkmək)', '{"bonus":true,"speakOptions":true,"options":["draw","drive","count","climb"],"correctIndex":0}'::jsonb, 15, 12),
  ('modal-listen-t1', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"I can swim.","options":["Mən üzə bilirəm.","Mən üzmürəm.","Mən üzmək istəyirəm.","Mən üzürəm."],"correctIndex":0}'::jsonb, 10, 0),
  ('modal-listen-t2', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"You must stop.","options":["Sən dayanmalısan.","Sən getməlisən.","Sən dayanma.","Sən dayana bilərsən."],"correctIndex":0}'::jsonb, 10, 1),
  ('modal-listen-t3', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"You should sleep early.","options":["Sən erkən yatmalısan.","Sən gec yatmalısan.","Sən yatmamalısan.","Sən erkən durmalısan."],"correctIndex":0}'::jsonb, 10, 2),
  ('modal-listen-t4', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"Birds can fly.","options":["Quşlar uça bilər.","Quşlar uça bilməz.","Balıqlar uça bilər.","Quşlar üzə bilər."],"correctIndex":0}'::jsonb, 10, 3),
  ('modal-listen-t5', 'modal-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"audioText":"Can I open the window?","options":["Pəncərəni aça bilərəm?","Pəncərəni bağlaya bilərəm?","Qapını aça bilərəm?","Pəncərəni açmalıyam?"],"correctIndex":0}'::jsonb, 10, 4),
  ('modal-listen-t6', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"You mustn''t run here.","options":["Sən burada qaçmamalısan.","Sən burada qaça bilərsən.","Sən burada gəzməlisən.","Sən burada qaçmalısan."],"correctIndex":0}'::jsonb, 10, 5),
  ('modal-listen-t7', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"She can drive a car.","options":["O maşın sürə bilir.","O maşın sürə bilmir.","O velosiped sürə bilir.","O maşın sürməlidir."],"correctIndex":0}'::jsonb, 10, 6),
  ('modal-listen-t8', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"We should help others.","options":["Biz başqalarına kömək etməliyik.","Biz kömək etməməliyik.","Biz özümüzə kömək etməliyik.","Biz kömək edə bilərik."],"correctIndex":0}'::jsonb, 15, 7),
  ('modal-listen-b1', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"bonus":true,"audioText":"I can ride a bike.","options":["Mən velosiped sürə bilirəm.","Mən velosiped sürə bilmirəm.","Mən maşın sürə bilirəm.","Mən velosiped sürməliyəm."],"correctIndex":0}'::jsonb, 15, 8),
  ('modal-listen-b2', 'modal-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"bonus":true,"audioText":"You shouldn''t eat too much.","options":["Sən çox yeməməlisən.","Sən çox yeməlisən.","Sən az yeməməlisən.","Sən çox yeyə bilərsən."],"correctIndex":0}'::jsonb, 15, 9),
  ('modal-read-t1', 'modal-read', 'multiple_choice', 'What must you do on time?', '{"speakOptions":true,"options":["play","come to school","run","shout"],"correctIndex":1}'::jsonb, 10, 0),
  ('modal-read-t2', 'modal-read', 'multiple_choice', 'What should you do every day?', '{"speakOptions":true,"options":["play football","do your homework","shout","run"],"correctIndex":1}'::jsonb, 10, 1),
  ('modal-read-t3', 'modal-read', 'multiple_choice', 'Where can you play?', '{"speakOptions":true,"options":["in the classroom","in the yard","on the road","at home"],"correctIndex":1}'::jsonb, 10, 2),
  ('modal-read-t4', 'modal-read', 'multiple_choice', 'What mustn''t you do in the classroom?', '{"speakOptions":true,"options":["listen","run","sit","write"],"correctIndex":1}'::jsonb, 10, 3),
  ('modal-read-t5', 'modal-read', 'multiple_choice', 'What shouldn''t you do?', '{"speakOptions":true,"options":["shout","study","listen","read"],"correctIndex":0}'::jsonb, 10, 4),
  ('modal-read-t6', 'modal-read', 'fill_blank', '''You ___ listen to the teacher.'' (məcburi — mətndən)', '{"accepted":["must"]}'::jsonb, 10, 5),
  ('modal-read-t7', 'modal-read', 'multiple_choice', 'Can you play at break time?', '{"speakOptions":true,"options":["Yes, in the yard.","No.","Only at home.","We don''t know."],"correctIndex":0}'::jsonb, 10, 6),
  ('modal-read-t8', 'modal-read', 'multiple_choice', '''Good students follow the ___.''', '{"speakOptions":true,"options":["rules","cars","birds","boxes"],"correctIndex":0}'::jsonb, 15, 7),
  ('modal-read-b1', 'modal-read', 'multiple_choice', '''on time'' nə deməkdir?', '{"bonus":true,"options":["vaxtında","gec","tez","heç vaxt"],"correctIndex":0}'::jsonb, 15, 8),
  ('modal-read-b2', 'modal-read', 'fill_blank', '''You ___ run in the classroom.'' (qadağa — mətndən)', '{"bonus":true,"accepted":["mustn''t"]}'::jsonb, 15, 9),
  ('modal-write-t1', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["I","can","swim"],"answer":"I can swim","translation":"Mən üzə bilirəm."}'::jsonb, 10, 0),
  ('modal-write-t2', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["You","must","stop"],"answer":"You must stop","translation":"Sən dayanmalısan."}'::jsonb, 10, 1),
  ('modal-write-t3', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["You","should","sleep","early"],"answer":"You should sleep early","translation":"Sən erkən yatmalısan."}'::jsonb, 10, 2),
  ('modal-write-t4', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["Birds","can","fly"],"answer":"Birds can fly","translation":"Quşlar uça bilər."}'::jsonb, 10, 3),
  ('modal-write-t5', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["Can","I","open","the","window"],"answer":"Can I open the window","translation":"Pəncərəni aça bilərəm?"}'::jsonb, 10, 4),
  ('modal-write-t6', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["She","can","drive","a","car"],"answer":"She can drive a car","translation":"O maşın sürə bilir."}'::jsonb, 10, 5),
  ('modal-write-t7', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["We","should","help","others"],"answer":"We should help others","translation":"Biz başqalarına kömək etməliyik."}'::jsonb, 10, 6),
  ('modal-write-t8', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["I","can","ride","a","bike"],"answer":"I can ride a bike","translation":"Mən velosiped sürə bilirəm."}'::jsonb, 15, 7),
  ('modal-write-b1', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["You","mustn''t","run","here"],"answer":"You mustn''t run here","translation":"Sən burada qaçmamalısan."}'::jsonb, 15, 8),
  ('modal-write-b2', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["He","can","draw"],"answer":"He can draw","translation":"O rəsm çəkə bilir."}'::jsonb, 15, 9),
  ('modal-write-b3', 'modal-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["You","should","listen"],"answer":"You should listen","translation":"Sən qulaq asmalısan."}'::jsonb, 15, 10)
on conflict (id) do update set lesson_id = excluded.lesson_id, type = excluded.type, prompt = excluded.prompt, data = excluded.data, xp = excluded.xp, sort_order = excluded.sort_order;

commit;
