-- İngilis yeni dövr(lər): en-c3-, en-c4-
-- Bölmələr yenidən sıralanır; köhnə təkrar dərslər silinir; yeni dərslər əlavə olunur.
begin;

-- Köhnə təkrar dərsləri sil.
delete from tasks where lesson_id in ('en-gr-l3', 'en-gr-l4');
delete from lessons where id in ('en-gr-l3', 'en-gr-l4');

insert into units (id, subject_id, title, description, sort_order) values
  ('en-c1-grammar', 'ingilis-dili', 'Qayda: Present Simple', 'İndiki sadə zaman — hər gün təkrarlanan işlər. Qaydanı oxu, sonra məşq et.', 0),
  ('en-c1-vocab', 'ingilis-dili', 'Lüğət: Gündəlik fellər', '8 yeni fel — eyni sözləri müxtəlif cümlələrdə təkrar-təkrar işlət.', 1),
  ('en-c1-listening', 'ingilis-dili', 'Dinləmə: Present Simple', 'Present Simple cümlələrini qulaqla tanı — dinlə və düzgün mənanı seç.', 2),
  ('en-c1-reading', 'ingilis-dili', 'Oxu: Mənim günüm', 'Qısa mətni oxu və suallara cavab ver (Present Simple).', 3),
  ('en-c1-writing', 'ingilis-dili', 'Yazı: Present Simple', 'Sözlərdən düzgün Present Simple cümləsi qur.', 4),
  ('en-c2-grammar', 'ingilis-dili', 'Qayda: Present Continuous', 'İndi, danışıq anında baş verən işlər. Qaydanı oxu, sonra məşq et.', 5),
  ('en-c2-vocab', 'ingilis-dili', 'Lüğət: İndi görülən işlər', '8 yeni fel — run, write, sleep, cook, sing, dance, swim, sit.', 6),
  ('en-c2-listening', 'ingilis-dili', 'Dinləmə: Present Continuous', 'İndi baş verən işlərin cümlələrini dinlə və düzgün mənanı seç.', 7),
  ('en-c2-reading', 'ingilis-dili', 'Oxu: In the park', 'Qısa mətni oxu və suallara cavab ver (Present Continuous).', 8),
  ('en-c2-writing', 'ingilis-dili', 'Yazı: Present Continuous', 'Sözlərdən düzgün Present Continuous cümləsi qur.', 9),
  ('en-c3-grammar', 'ingilis-dili', 'Qayda: Past Simple', 'Keçmişdə bitmiş işlər. Qaydalı (-ed) və qaydasız fellər.', 10),
  ('en-c3-vocab', 'ingilis-dili', 'Lüğət: Keçmiş işlər', '8 yeni fel — visit, help, clean, wash, walk, talk, want, call.', 11),
  ('en-c3-listening', 'ingilis-dili', 'Dinləmə: Past Simple', 'Keçmiş işlərin cümlələrini dinlə və düzgün mənanı seç.', 12),
  ('en-c3-reading', 'ingilis-dili', 'Oxu: My weekend', 'Keçmiş haqqında qısa mətni oxu və suallara cavab ver (Past Simple).', 13),
  ('en-c3-writing', 'ingilis-dili', 'Yazı: Past Simple', 'Sözlərdən düzgün Past Simple cümləsi qur.', 14),
  ('en-c4-grammar', 'ingilis-dili', 'Qayda: Sual və inkar', 'Sual (do/does/did) və inkar (don''t/doesn''t/didn''t) cümlələri.', 15),
  ('en-c4-vocab', 'ingilis-dili', 'Lüğət: Sual sözləri', '6 sual sözü: what, where, when, who, why, how.', 16),
  ('en-c4-listening', 'ingilis-dili', 'Dinləmə: Sual və inkar', 'Sual və inkar cümlələrini dinlə və düzgün mənanı seç.', 17),
  ('en-c4-reading', 'ingilis-dili', 'Oxu: An interview', 'Qısa müsahibəni oxu və suallara cavab ver (sual-cavab).', 18),
  ('en-c4-writing', 'ingilis-dili', 'Yazı: Sual və inkar', 'Sözlərdən düzgün sual və inkar cümləsi qur.', 19),
  ('en-grammar', 'ingilis-dili', 'Qrammatika — Zamanlar və cümlə', 'Present Simple, Present Continuous, Past Simple, sual/inkar cümlələr, əvəzliklər, artikllar, sifət dərəcələri və modal fellər.', 20),
  ('en-nouns', 'ingilis-dili', 'İsimlər (Nouns)', 'İsim nədir, cəm forması, sayıla bilən və sayıla bilməyən isimlər.', 21),
  ('en-vocab', 'ingilis-dili', 'Söz ehtiyatı (Vocabulary)', 'Gündəlik həyatla bağlı mövzular: ailə, məktəb, təbiət, qida, şəhər və hobbilər.', 22)
on conflict (id) do update set title = excluded.title, description = excluded.description, sort_order = excluded.sort_order;

insert into lessons (id, unit_id, title, intro, visual, sections, sort_order) values
  ('past-rule', 'en-c3-grammar', 'Past Simple qaydası', 'Past Simple keçmişdə bitmiş işi bildirir. Gəl qaydanı öyrənək!', null, '[{"heading":"Past Simple nədir?","body":"Keçmişdə bitmiş işi bildirir: I played yesterday. Çox vaxt ''yesterday'', ''last week'', ''ago'' sözləri ilə işlənir."},{"heading":"Qaydalı fellər: -ed","body":"Əksər fellərə -ed əlavə olunur: play → played, visit → visited, help → helped. Bütün şəxslərdə eynidir (I/he/we played)."},{"heading":"Qaydasız fellər","body":"Bəzi fellər dəyişir: go → went, see → saw, eat → ate, have → had. Bunları əzbərləmək lazımdır."}]'::jsonb, 0),
  ('past-vocab', 'en-c3-vocab', 'Gündəlik fellər II (8 söz)', 'Keçmişdə görülən işləri bildirən 8 yeni fel öyrənək.', null, '[{"heading":"Yeni sözlər (8 fel)","body":"visit — ziyarət etmək · help — kömək etmək · clean — təmizləmək · wash — yumaq · walk — gəzmək · talk — danışmaq · want — istəmək · call — zəng etmək"},{"heading":"Məsləhət","body":"Bu fellər qaydalıdır — keçmişdə -ed alır: visited, helped, cleaned... Bir cümlədə xatırla: I helped my mother."}]'::jsonb, 0),
  ('past-listen', 'en-c3-listening', 'Dinlə və seç: keçmiş iş', 'Cümləni dinlə və düzgün cavabı seç.', null, '[{"heading":"Necə işləyir?","body":"«Dinlə» düyməsinə bas, cümləni eşit və düzgün variantı seç. İstədiyin qədər təkrar dinlə."}]'::jsonb, 0),
  ('past-read', 'en-c3-reading', 'Reading: My weekend', 'Qısa mətni oxu və suallara cavab ver.', null, '[{"heading":"Read the text (Mətni oxu)","body":"Last Saturday was a great day. In the morning I cleaned my room and helped my mother. Then we visited my grandmother. She cooked a nice dinner. In the afternoon I played football with my friends. In the evening I watched a film and went to bed early. It was a happy day."},{"heading":"İpucu","body":"Sualı oxu, cavabı mətndə tap. Lazım olsa mətnə yenidən bax."}]'::jsonb, 0),
  ('past-write', 'en-c3-writing', 'Cümlə qur: Past Simple', 'Sözləri düzgün sıraya düz və Past Simple cümləsi qur.', null, '[{"heading":"Necə işləyir?","body":"Sözlərə sıra ilə bas — cümlə yuxarıda düzələcək. Keçmişdə fel -ed alır və ya qaydasız dəyişir (played, went, ate)."}]'::jsonb, 0),
  ('q-rule', 'en-c4-grammar', 'Sual və inkar qaydası', 'İngiliscə sual və inkar necə qurulur? Gəl öyrənək!', null, '[{"heading":"Sual necə qurulur?","body":"do/does/did + kim + fel: Do you like tea? Does she play? Did they go? Sual sözü əvvələ gəlir: What do you want?"},{"heading":"İnkar (negatives)","body":"don''t/doesn''t/didn''t + fel: I don''t like. She doesn''t play. We didn''t go."},{"heading":"Sual sözləri","body":"what (nə), where (harada), when (nə vaxt), who (kim), why (niyə), how (necə)."}]'::jsonb, 0),
  ('q-vocab', 'en-c4-vocab', 'Sual sözləri (wh- sözlər)', 'İngiliscə sual verməyə kömək edən 6 sözü öyrənək.', null, '[{"heading":"Yeni sözlər (sual sözləri)","body":"what — nə · where — harada · when — nə vaxt · who — kim · why — niyə · how — necə"},{"heading":"Məsləhət","body":"Bu sözlər cümlənin əvvəlində gəlir: What is your name? Where do you live?"}]'::jsonb, 0),
  ('q-listen', 'en-c4-listening', 'Dinlə və seç: sual-cavab', 'Cümləni dinlə və düzgün cavabı seç.', null, '[{"heading":"Necə işləyir?","body":"«Dinlə» düyməsinə bas, cümləni eşit və düzgün variantı seç. İstədiyin qədər təkrar dinlə."}]'::jsonb, 0),
  ('q-read', 'en-c4-reading', 'Reading: An interview', 'Qısa müsahibəni oxu və suallara cavab ver.', null, '[{"heading":"Read the text (Mətni oxu)","body":"This is an interview with Nigar. — What is your name? — My name is Nigar. — Where are you from? — I am from Ganja. — How old are you? — I am eleven. — Do you like school? — Yes, I do. I like English very much. — What is your favourite sport? — I like basketball. — Do you play every day? — No, I don''t. I play on Sundays."},{"heading":"İpucu","body":"Sualı oxu, cavabı mətndə tap. Lazım olsa mətnə yenidən bax."}]'::jsonb, 0),
  ('q-write', 'en-c4-writing', 'Cümlə qur: sual və inkar', 'Sözləri düzgün sıraya düz və sual/inkar cümləsi qur.', null, '[{"heading":"Necə işləyir?","body":"Sözlərə sıra ilə bas. Sual: (sual sözü) + do/does/did + kim + fel. İnkar: kim + do/does not + fel."}]'::jsonb, 0)
on conflict (id) do update set unit_id = excluded.unit_id, title = excluded.title, intro = excluded.intro, visual = excluded.visual, sections = excluded.sections, sort_order = excluded.sort_order;

insert into tasks (id, lesson_id, type, prompt, data, xp, sort_order) values
  ('past-rule-t1', 'past-rule', 'multiple_choice', '''I ___ football yesterday.''', '{"speakOptions":true,"options":["play","plays","played","playing"],"correctIndex":2}'::jsonb, 10, 0),
  ('past-rule-t2', 'past-rule', 'multiple_choice', '''She ___ her homework.'' (do)', '{"speakOptions":true,"options":["do","does","did","done"],"correctIndex":2}'::jsonb, 10, 1),
  ('past-rule-t3', 'past-rule', 'multiple_choice', '''We ___ to the park.'' (go)', '{"speakOptions":true,"options":["go","goes","went","gone"],"correctIndex":2}'::jsonb, 10, 2),
  ('past-rule-t4', 'past-rule', 'multiple_choice', '''He ___ a film.'' (watch)', '{"speakOptions":true,"options":["watch","watched","watching","watches"],"correctIndex":1}'::jsonb, 10, 3),
  ('past-rule-t5', 'past-rule', 'fill_blank', '''visit'' felinin keçmiş formasını yaz.', '{"accepted":["visited"]}'::jsonb, 10, 4),
  ('past-rule-t6', 'past-rule', 'multiple_choice', 'Past Simple hansı vaxt üçündür?', '{"options":["indi","keçmiş","gələcək","həmişə"],"correctIndex":1}'::jsonb, 10, 5),
  ('past-rule-t7', 'past-rule', 'multiple_choice', '''They ___ pizza.'' (eat)', '{"speakOptions":true,"options":["eat","ate","eaten","eats"],"correctIndex":1}'::jsonb, 10, 6),
  ('past-rule-t8', 'past-rule', 'multiple_choice', 'İnkar: ''I ___ not play.''', '{"speakOptions":true,"options":["do","did","does","am"],"correctIndex":1}'::jsonb, 10, 7),
  ('past-rule-t9', 'past-rule', 'multiple_choice', 'Sual: ''___ you see the film?''', '{"speakOptions":true,"options":["Do","Did","Does","Are"],"correctIndex":1}'::jsonb, 10, 8),
  ('past-rule-t10', 'past-rule', 'fill_blank', '''help'' felinin keçmiş formasını yaz.', '{"accepted":["helped"]}'::jsonb, 15, 9),
  ('past-rule-b1', 'past-rule', 'multiple_choice', '''She ___ a letter.'' (write)', '{"bonus":true,"speakOptions":true,"options":["write","wrote","written","writes"],"correctIndex":1}'::jsonb, 15, 10),
  ('past-rule-b2', 'past-rule', 'fill_blank', '''clean'' felinin keçmiş formasını yaz.', '{"bonus":true,"accepted":["cleaned"]}'::jsonb, 15, 11),
  ('past-rule-b3', 'past-rule', 'multiple_choice', '''I ___ happy yesterday.'' (be)', '{"bonus":true,"speakOptions":true,"options":["am","was","were","is"],"correctIndex":1}'::jsonb, 15, 12),
  ('past-vocab-t1', 'past-vocab', 'multiple_choice', '''visit'' sözünün mənası?', '{"options":["ziyarət etmək","təmizləmək","yumaq","gəzmək"],"correctIndex":0}'::jsonb, 10, 0),
  ('past-vocab-t2', 'past-vocab', 'multiple_choice', '''help'' sözünün mənası?', '{"options":["kömək etmək","danışmaq","istəmək","zəng etmək"],"correctIndex":0}'::jsonb, 10, 1),
  ('past-vocab-t3', 'past-vocab', 'multiple_choice', '''clean'' sözünün mənası?', '{"options":["təmizləmək","yumaq","gəzmək","ziyarət etmək"],"correctIndex":0}'::jsonb, 10, 2),
  ('past-vocab-t4', 'past-vocab', 'multiple_choice', '''wash'' sözünün mənası?', '{"options":["yumaq","təmizləmək","danışmaq","istəmək"],"correctIndex":0}'::jsonb, 10, 3),
  ('past-vocab-t5', 'past-vocab', 'multiple_choice', '''walk'' sözünün mənası?', '{"options":["gəzmək / yerimək","qaçmaq","üzmək","oturmaq"],"correctIndex":0}'::jsonb, 10, 4),
  ('past-vocab-t6', 'past-vocab', 'multiple_choice', '''talk'' sözünün mənası?', '{"options":["danışmaq","dinləmək","oxumaq","yazmaq"],"correctIndex":0}'::jsonb, 10, 5),
  ('past-vocab-t7', 'past-vocab', 'fill_blank', '''istəmək'' ingiliscə necə yazılır?', '{"accepted":["want"]}'::jsonb, 10, 6),
  ('past-vocab-t8', 'past-vocab', 'fill_blank', '''zəng etmək'' ingiliscə necə yazılır?', '{"accepted":["call"]}'::jsonb, 10, 7),
  ('past-vocab-t9', 'past-vocab', 'multiple_choice', '''Yesterday I ___ my grandma.'' (ziyarət etdim)', '{"speakOptions":true,"options":["visited","cleaned","walked","wanted"],"correctIndex":0}'::jsonb, 10, 8),
  ('past-vocab-t10', 'past-vocab', 'multiple_choice', '''She ___ the dishes.'' (yudu)', '{"speakOptions":true,"options":["washed","helped","talked","called"],"correctIndex":0}'::jsonb, 15, 9),
  ('past-vocab-b1', 'past-vocab', 'multiple_choice', '''want'' sözünün mənası?', '{"bonus":true,"options":["istəmək","sevmək","bilmək","görmək"],"correctIndex":0}'::jsonb, 15, 10),
  ('past-vocab-b2', 'past-vocab', 'multiple_choice', '''call'' sözünün mənası?', '{"bonus":true,"options":["zəng etmək","gəzmək","yumaq","oxumaq"],"correctIndex":0}'::jsonb, 15, 11),
  ('past-vocab-b3', 'past-vocab', 'multiple_choice', '''We ___ in the park.'' (gəzdik)', '{"bonus":true,"speakOptions":true,"options":["walked","washed","wanted","called"],"correctIndex":0}'::jsonb, 15, 12),
  ('past-listen-t1', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"I played football yesterday.","options":["Mən dünən futbol oynadım.","Mən indi futbol oynayıram.","Mən sabah oynayacağam.","Mən futbola baxdım."],"correctIndex":0}'::jsonb, 10, 0),
  ('past-listen-t2', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"She visited her grandmother.","options":["O nənəsini ziyarət etdi.","O nənəsinə zəng etdi.","O anasını ziyarət etdi.","O nənəsinə kömək etdi."],"correctIndex":0}'::jsonb, 10, 1),
  ('past-listen-t3', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"We went to school.","options":["Biz məktəbə getdik.","Biz evə getdik.","Biz məktəbdəyik.","Biz məktəbə gedirik."],"correctIndex":0}'::jsonb, 10, 2),
  ('past-listen-t4', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"He watched a film.","options":["O film izlədi.","O kitab oxudu.","O film çəkdi.","O televizora baxır."],"correctIndex":0}'::jsonb, 10, 3),
  ('past-listen-t5', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"They ate pizza.","options":["Onlar pizza yedi.","Onlar pizza bişirdi.","Onlar pizza istədi.","Onlar yemək yeyir."],"correctIndex":0}'::jsonb, 10, 4),
  ('past-listen-t6', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"I cleaned my room.","options":["Mən otağımı təmizlədim.","Mən otağıma getdim.","Mən otağımı yudum.","Mən otağı gördüm."],"correctIndex":0}'::jsonb, 10, 5),
  ('past-listen-t7', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"She washed the dishes.","options":["O qabları yudu.","O qabları yığdı.","O əllərini yudu.","O paltar yudu."],"correctIndex":0}'::jsonb, 10, 6),
  ('past-listen-t8', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"We walked in the park.","options":["Biz parkda gəzdik.","Biz parkda qaçdıq.","Biz parka getdik.","Biz bağda gəzdik."],"correctIndex":0}'::jsonb, 15, 7),
  ('past-listen-b1', 'past-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"bonus":true,"audioText":"Did you see the film?","options":["Sən filmi gördün?","Sən film çəkdin?","Sən film izləyirsən?","Sən filmi bəyəndin?"],"correctIndex":0}'::jsonb, 15, 8),
  ('past-listen-b2', 'past-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"bonus":true,"audioText":"He helped his mother.","options":["O anasına kömək etdi.","O anasına zəng etdi.","O atasına kömək etdi.","O anası ilə danışdı."],"correctIndex":0}'::jsonb, 15, 9),
  ('past-read-t1', 'past-read', 'multiple_choice', 'When was the great day?', '{"speakOptions":true,"options":["last Sunday","last Saturday","yesterday","last Monday"],"correctIndex":1}'::jsonb, 10, 0),
  ('past-read-t2', 'past-read', 'multiple_choice', 'What did the boy do in the morning?', '{"speakOptions":true,"options":["played football","cleaned his room","watched a film","slept"],"correctIndex":1}'::jsonb, 10, 1),
  ('past-read-t3', 'past-read', 'multiple_choice', 'Who did they visit?', '{"speakOptions":true,"options":["his teacher","his grandmother","his friend","his uncle"],"correctIndex":1}'::jsonb, 10, 2),
  ('past-read-t4', 'past-read', 'multiple_choice', 'Who cooked dinner?', '{"speakOptions":true,"options":["his mother","his grandmother","the boy","his father"],"correctIndex":1}'::jsonb, 10, 3),
  ('past-read-t5', 'past-read', 'multiple_choice', 'What did he do in the afternoon?', '{"speakOptions":true,"options":["watched TV","played football","cleaned","slept"],"correctIndex":1}'::jsonb, 10, 4),
  ('past-read-t6', 'past-read', 'multiple_choice', 'What did he do in the evening?', '{"speakOptions":true,"options":["watched a film","played football","cooked","cleaned"],"correctIndex":0}'::jsonb, 10, 5),
  ('past-read-t7', 'past-read', 'fill_blank', '''I ___ my mother.'' (kömək etdim — mətndən)', '{"accepted":["helped"]}'::jsonb, 10, 6),
  ('past-read-t8', 'past-read', 'multiple_choice', 'Was it a happy day?', '{"speakOptions":true,"options":["Yes, it was.","No, it wasn''t.","We don''t know.","It was sad."],"correctIndex":0}'::jsonb, 15, 7),
  ('past-read-b1', 'past-read', 'multiple_choice', '''went to bed'' nə deməkdir?', '{"bonus":true,"options":["yatmağa getdi","oyandı","yeməyə getdi","çölə çıxdı"],"correctIndex":0}'::jsonb, 15, 8),
  ('past-read-b2', 'past-read', 'fill_blank', '''We ___ my grandmother.'' (ziyarət etdik — mətndən)', '{"bonus":true,"accepted":["visited"]}'::jsonb, 15, 9),
  ('past-write-t1', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["I","played","football"],"answer":"I played football","translation":"Mən futbol oynadım."}'::jsonb, 10, 0),
  ('past-write-t2', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["She","visited","her","grandmother"],"answer":"She visited her grandmother","translation":"O nənəsini ziyarət etdi."}'::jsonb, 10, 1),
  ('past-write-t3', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["We","went","to","school"],"answer":"We went to school","translation":"Biz məktəbə getdik."}'::jsonb, 10, 2),
  ('past-write-t4', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["He","watched","a","film"],"answer":"He watched a film","translation":"O film izlədi."}'::jsonb, 10, 3),
  ('past-write-t5', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["They","ate","pizza"],"answer":"They ate pizza","translation":"Onlar pizza yedi."}'::jsonb, 10, 4),
  ('past-write-t6', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["I","cleaned","my","room"],"answer":"I cleaned my room","translation":"Mən otağımı təmizlədim."}'::jsonb, 10, 5),
  ('past-write-t7', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["She","washed","the","dishes"],"answer":"She washed the dishes","translation":"O qabları yudu."}'::jsonb, 10, 6),
  ('past-write-t8', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["We","walked","in","the","park"],"answer":"We walked in the park","translation":"Biz parkda gəzdik."}'::jsonb, 15, 7),
  ('past-write-b1', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["I","helped","my","mother"],"answer":"I helped my mother","translation":"Mən anama kömək etdim."}'::jsonb, 15, 8),
  ('past-write-b2', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["Did","you","see","the","film"],"answer":"Did you see the film","translation":"Sən filmi gördün?"}'::jsonb, 15, 9),
  ('past-write-b3', 'past-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["He","did","not","play"],"answer":"He did not play","translation":"O oynamadı."}'::jsonb, 15, 10),
  ('q-rule-t1', 'q-rule', 'multiple_choice', 'Sual: ''___ you like music?''', '{"speakOptions":true,"options":["Do","Does","Did","Are"],"correctIndex":0}'::jsonb, 10, 0),
  ('q-rule-t2', 'q-rule', 'multiple_choice', 'Sual: ''___ she play tennis?''', '{"speakOptions":true,"options":["Do","Does","Is","Are"],"correctIndex":1}'::jsonb, 10, 1),
  ('q-rule-t3', 'q-rule', 'multiple_choice', 'İnkar: ''I ___ like coffee.''', '{"speakOptions":true,"options":["don''t","doesn''t","isn''t","not"],"correctIndex":0}'::jsonb, 10, 2),
  ('q-rule-t4', 'q-rule', 'multiple_choice', 'İnkar: ''He ___ eat meat.''', '{"speakOptions":true,"options":["don''t","doesn''t","isn''t","aren''t"],"correctIndex":1}'::jsonb, 10, 3),
  ('q-rule-t5', 'q-rule', 'multiple_choice', '''___ do you live?'' (harada)', '{"speakOptions":true,"options":["What","Where","When","Who"],"correctIndex":1}'::jsonb, 10, 4),
  ('q-rule-t6', 'q-rule', 'multiple_choice', '''___ is your name?'' (nə)', '{"speakOptions":true,"options":["What","Where","When","Why"],"correctIndex":0}'::jsonb, 10, 5),
  ('q-rule-t7', 'q-rule', 'multiple_choice', '''___ are you sad?'' (niyə)', '{"speakOptions":true,"options":["What","Where","Why","Who"],"correctIndex":2}'::jsonb, 10, 6),
  ('q-rule-t8', 'q-rule', 'fill_blank', '''kim'' sual sözü ingiliscə necə yazılır?', '{"accepted":["who"]}'::jsonb, 10, 7),
  ('q-rule-t9', 'q-rule', 'multiple_choice', 'Keçmiş sual: ''___ you see it?''', '{"speakOptions":true,"options":["Do","Does","Did","Are"],"correctIndex":2}'::jsonb, 10, 8),
  ('q-rule-t10', 'q-rule', 'multiple_choice', 'İnkar (keçmiş): ''We ___ go.''', '{"speakOptions":true,"options":["don''t","doesn''t","didn''t","isn''t"],"correctIndex":2}'::jsonb, 15, 9),
  ('q-rule-b1', 'q-rule', 'multiple_choice', '''___ old are you?'' (necə — yaş)', '{"bonus":true,"speakOptions":true,"options":["How","What","Where","Who"],"correctIndex":0}'::jsonb, 15, 10),
  ('q-rule-b2', 'q-rule', 'multiple_choice', '''Does he ___ English?''', '{"bonus":true,"speakOptions":true,"options":["speak","speaks","speaking","spoke"],"correctIndex":0}'::jsonb, 15, 11),
  ('q-rule-b3', 'q-rule', 'fill_blank', '''nə vaxt'' sual sözü ingiliscə necə yazılır?', '{"bonus":true,"accepted":["when"]}'::jsonb, 15, 12),
  ('q-vocab-t1', 'q-vocab', 'multiple_choice', '''what'' sözünün mənası?', '{"options":["nə","harada","nə vaxt","kim"],"correctIndex":0}'::jsonb, 10, 0),
  ('q-vocab-t2', 'q-vocab', 'multiple_choice', '''where'' sözünün mənası?', '{"options":["kim","harada","niyə","necə"],"correctIndex":1}'::jsonb, 10, 1),
  ('q-vocab-t3', 'q-vocab', 'multiple_choice', '''when'' sözünün mənası?', '{"options":["nə vaxt","harada","nə","kim"],"correctIndex":0}'::jsonb, 10, 2),
  ('q-vocab-t4', 'q-vocab', 'multiple_choice', '''who'' sözünün mənası?', '{"options":["kim","nə","harada","niyə"],"correctIndex":0}'::jsonb, 10, 3),
  ('q-vocab-t5', 'q-vocab', 'multiple_choice', '''why'' sözünün mənası?', '{"options":["niyə","necə","nə vaxt","kim"],"correctIndex":0}'::jsonb, 10, 4),
  ('q-vocab-t6', 'q-vocab', 'multiple_choice', '''how'' sözünün mənası?', '{"options":["necə","niyə","harada","nə"],"correctIndex":0}'::jsonb, 10, 5),
  ('q-vocab-t7', 'q-vocab', 'fill_blank', '''harada'' ingiliscə necə yazılır?', '{"accepted":["where"]}'::jsonb, 10, 6),
  ('q-vocab-t8', 'q-vocab', 'fill_blank', '''niyə'' ingiliscə necə yazılır?', '{"accepted":["why"]}'::jsonb, 10, 7),
  ('q-vocab-t9', 'q-vocab', 'multiple_choice', '''___ is your teacher?'' (kim)', '{"speakOptions":true,"options":["Who","What","Where","When"],"correctIndex":0}'::jsonb, 10, 8),
  ('q-vocab-t10', 'q-vocab', 'multiple_choice', '''___ do you go to school?'' (nə vaxt)', '{"speakOptions":true,"options":["When","Who","What","Why"],"correctIndex":0}'::jsonb, 15, 9),
  ('q-vocab-b1', 'q-vocab', 'multiple_choice', '''how'' sözünün mənası?', '{"bonus":true,"options":["necə","nə","kim","harada"],"correctIndex":0}'::jsonb, 15, 10),
  ('q-vocab-b2', 'q-vocab', 'fill_blank', '''nə'' ingiliscə necə yazılır?', '{"bonus":true,"accepted":["what"]}'::jsonb, 15, 11),
  ('q-vocab-b3', 'q-vocab', 'multiple_choice', '''___ are you? — I am fine.'' (necə)', '{"bonus":true,"speakOptions":true,"options":["How","What","Who","Why"],"correctIndex":0}'::jsonb, 15, 12),
  ('q-listen-t1', 'q-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"audioText":"What is your name?","options":["Adın nədir?","Neçə yaşın var?","Haralısan?","Necəsən?"],"correctIndex":0}'::jsonb, 10, 0),
  ('q-listen-t2', 'q-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"audioText":"Where do you live?","options":["Harada yaşayırsan?","Nə vaxt gəlirsən?","Kimsən?","Niyə gəldin?"],"correctIndex":0}'::jsonb, 10, 1),
  ('q-listen-t3', 'q-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"audioText":"How old are you?","options":["Neçə yaşın var?","Adın nədir?","Necəsən?","Haradasan?"],"correctIndex":0}'::jsonb, 10, 2),
  ('q-listen-t4', 'q-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"audioText":"Do you like football?","options":["Futbolu sevirsən?","Futbol oynayırsan?","Futbola baxırsan?","Futbol bilirsən?"],"correctIndex":0}'::jsonb, 10, 3),
  ('q-listen-t5', 'q-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"audioText":"Why are you late?","options":["Niyə gecikirsən?","Harada idin?","Kiminlə gəldin?","Nə vaxt gəldin?"],"correctIndex":0}'::jsonb, 10, 4),
  ('q-listen-t6', 'q-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"I don''t like coffee.","options":["Mən qəhvə sevmirəm.","Mən qəhvə sevirəm.","Mən çay sevmirəm.","Mən qəhvə içirəm."],"correctIndex":0}'::jsonb, 10, 5),
  ('q-listen-t7', 'q-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"audioText":"She doesn''t play tennis.","options":["O tennis oynamır.","O tennis oynayır.","O futbol oynamır.","O tennisə baxmır."],"correctIndex":0}'::jsonb, 10, 6),
  ('q-listen-t8', 'q-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"audioText":"When do you get up?","options":["Nə vaxt durursan?","Harada durursan?","Niyə durursan?","Necə durursan?"],"correctIndex":0}'::jsonb, 15, 7),
  ('q-listen-b1', 'q-listen', 'listening', 'Dinlə və sualın mənasını seç.', '{"bonus":true,"audioText":"Who is your best friend?","options":["Ən yaxşı dostun kimdir?","Dostun haradadır?","Dostun neçə yaşındadır?","Dostun necədir?"],"correctIndex":0}'::jsonb, 15, 8),
  ('q-listen-b2', 'q-listen', 'listening', 'Dinlə və cümlənin mənasını seç.', '{"bonus":true,"audioText":"We didn''t watch the film.","options":["Biz filmi izləmədik.","Biz filmi izlədik.","Biz filmə baxırıq.","Biz filmi bəyənmədik."],"correctIndex":0}'::jsonb, 15, 9),
  ('q-read-t1', 'q-read', 'multiple_choice', 'What is her name?', '{"speakOptions":true,"options":["Leyla","Nigar","Anna","Sara"],"correctIndex":1}'::jsonb, 10, 0),
  ('q-read-t2', 'q-read', 'multiple_choice', 'Where is she from?', '{"speakOptions":true,"options":["Baku","Ganja","Sheki","London"],"correctIndex":1}'::jsonb, 10, 1),
  ('q-read-t3', 'q-read', 'multiple_choice', 'How old is she?', '{"speakOptions":true,"options":["ten","eleven","twelve","nine"],"correctIndex":1}'::jsonb, 10, 2),
  ('q-read-t4', 'q-read', 'multiple_choice', 'Does she like school?', '{"speakOptions":true,"options":["Yes, she does.","No, she doesn''t.","We don''t know.","She likes maths."],"correctIndex":0}'::jsonb, 10, 3),
  ('q-read-t5', 'q-read', 'multiple_choice', 'What is her favourite sport?', '{"speakOptions":true,"options":["football","basketball","tennis","swimming"],"correctIndex":1}'::jsonb, 10, 4),
  ('q-read-t6', 'q-read', 'multiple_choice', 'Does she play every day?', '{"speakOptions":true,"options":["Yes, every day.","No, she plays on Sundays.","Yes, on Mondays.","She doesn''t play."],"correctIndex":1}'::jsonb, 10, 5),
  ('q-read-t7', 'q-read', 'fill_blank', '''What is your ___? — My name is Nigar.''', '{"accepted":["name"]}'::jsonb, 10, 6),
  ('q-read-t8', 'q-read', 'multiple_choice', 'Which subject does she like?', '{"speakOptions":true,"options":["maths","English","science","art"],"correctIndex":1}'::jsonb, 15, 7),
  ('q-read-b1', 'q-read', 'multiple_choice', '''favourite'' nə deməkdir?', '{"bonus":true,"options":["ən sevimli","ən pis","ən böyük","ən kiçik"],"correctIndex":0}'::jsonb, 15, 8),
  ('q-read-b2', 'q-read', 'fill_blank', '''Where are you ___? — I am from Ganja.''', '{"bonus":true,"accepted":["from"]}'::jsonb, 15, 9),
  ('q-write-t1', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["What","is","your","name"],"answer":"What is your name","translation":"Adın nədir?"}'::jsonb, 10, 0),
  ('q-write-t2', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["Where","do","you","live"],"answer":"Where do you live","translation":"Harada yaşayırsan?"}'::jsonb, 10, 1),
  ('q-write-t3', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["Do","you","like","music"],"answer":"Do you like music","translation":"Musiqini sevirsən?"}'::jsonb, 10, 2),
  ('q-write-t4', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["I","do","not","like","tea"],"answer":"I do not like tea","translation":"Mən çay sevmirəm."}'::jsonb, 10, 3),
  ('q-write-t5', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["When","do","you","get","up"],"answer":"When do you get up","translation":"Nə vaxt durursan?"}'::jsonb, 10, 4),
  ('q-write-t6', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["Why","are","you","sad"],"answer":"Why are you sad","translation":"Niyə kədərlisən?"}'::jsonb, 10, 5),
  ('q-write-t7', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["She","does","not","play"],"answer":"She does not play","translation":"O oynamır."}'::jsonb, 10, 6),
  ('q-write-t8', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"words":["How","old","are","you"],"answer":"How old are you","translation":"Neçə yaşın var?"}'::jsonb, 15, 7),
  ('q-write-b1', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["Who","is","your","teacher"],"answer":"Who is your teacher","translation":"Müəllimin kimdir?"}'::jsonb, 15, 8),
  ('q-write-b2', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["Did","you","see","it"],"answer":"Did you see it","translation":"Onu gördün?"}'::jsonb, 15, 9),
  ('q-write-b3', 'q-write', 'word_order', 'Sözləri düzgün sıraya düz.', '{"bonus":true,"words":["We","did","not","go"],"answer":"We did not go","translation":"Biz getmədik."}'::jsonb, 15, 10)
on conflict (id) do update set lesson_id = excluded.lesson_id, type = excluded.type, prompt = excluded.prompt, data = excluded.data, xp = excluded.xp, sort_order = excluded.sort_order;

commit;
