// Azərbaycan dili — 6-cı sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Fonetika  2) Leksika  3) Sözün tərkibi və söz yaradıcılığı
// 4) Nitq hissələri I (isim, sifət, say, əvəzlik)  5) Nitq hissələri II (feil, zərf)
// 6) Orfoqrafiya, durğu işarələri və mətn.
// Hər dərs: 15 əsas + 5 bonus. Mərhələli doldurulur. id prefiksi az6-*.

import type { Subject } from "../types";

export const azerbaijani6: Subject = {
  slug: "azerbaycan-dili-6",
  name: "Azərbaycan dili",
  grade: 6,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. Fonetika ═══════════════
    {
      id: "az6-fonetika",
      title: "Fonetika",
      description:
        "Səs və hərf, saitlər və samitlər, ahəng qanunu, heca, vurğu və fonetik təhlil.",
      lessons: [
        {
          id: "az6-fon-l1",
          title: "Səs və hərf. Saitlər və samitlər",
          intro: "Səs və hərfin fərqi, saitlərin və samitlərin təsnifatı.",
          sections: [
            { heading: "Səs və hərf", body: "Tələffüz etdiyimiz — səs, yazıda onu göstərən işarə — hərfdir. Azərbaycan əlifbasında 32 hərf var." },
            { heading: "Saitlər (9)", body: "a, ı, o, u — qalın saitlər; e, ə, i, ö, ü — incə saitlər. Dodaqlanan: o, u, ö, ü; dodaqlanmayan: a, ı, e, ə, i." },
            { heading: "Samitlər", body: "Kar samitlər: p, f, t, s, ş, ç, k, x, h. Cingiltili samitlər: b, v, d, z, j, c, q, g, ğ və s. Kar-cingiltili cütlər: p-b, t-d, k-q." },
          ],
          tasks: [
            { id: "az6-fon-l1-t1", type: "multiple_choice", prompt: "Azərbaycan əlifbasında neçə hərf var?", options: ["29", "32", "33", "26"], correctIndex: 1, xp: 10 },
            { id: "az6-fon-l1-t2", type: "numeric", prompt: "Azərbaycan dilində neçə sait var?", answer: 9, xp: 10 },
            { id: "az6-fon-l1-t3", type: "multiple_choice", prompt: "Hansı qalın saitdir?", options: ["ə", "e", "o", "i"], correctIndex: 2, xp: 10 },
            { id: "az6-fon-l1-t4", type: "multiple_choice", prompt: "Hansı incə saitdir?", options: ["a", "ı", "ü", "u"], correctIndex: 2, xp: 10 },
            { id: "az6-fon-l1-t5", type: "multiple_choice", prompt: "Hansı dodaqlanan saitdir?", options: ["a", "ö", "e", "ı"], correctIndex: 1, xp: 10 },
            { id: "az6-fon-l1-t6", type: "multiple_choice", prompt: "'p' səsi necə samitdir?", options: ["kar", "cingiltili", "sait", "qoşa"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l1-t7", type: "multiple_choice", prompt: "'b' səsi necə samitdir?", options: ["cingiltili", "kar", "sait", "yarımsait"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l1-t8", type: "multiple_choice", prompt: "'t' samitinin cingiltili cütü hansıdır?", options: ["d", "s", "k", "p"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l1-t9", type: "multiple_choice", prompt: "'k' samitinin cingiltili cütü hansıdır?", options: ["q", "g", "x", "h"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l1-t10", type: "fill_blank", prompt: "Yazıda səsi göstərən işarə necə adlanır?", accepted: ["hərf", "herf"], xp: 10 },
            { id: "az6-fon-l1-t11", type: "multiple_choice", prompt: "Hansı dodaqlanmayan saitdir?", options: ["o", "u", "a", "ö"], correctIndex: 2, xp: 10 },
            { id: "az6-fon-l1-t12", type: "multiple_choice", prompt: "'s' səsi necə samitdir?", options: ["kar", "cingiltili", "sait", "qoşa"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l1-t13", type: "numeric", prompt: "'a, ı, o, u' — neçə qalın saitdir?", answer: 4, xp: 10 },
            { id: "az6-fon-l1-t14", type: "numeric", prompt: "'e, ə, i, ö, ü' — neçə incə saitdir?", answer: 5, xp: 10 },
            { id: "az6-fon-l1-t15", type: "multiple_choice", prompt: "'q' səsi necə samitdir?", options: ["cingiltili", "kar", "sait", "yarımsait"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az6-fon-l1-b1", type: "multiple_choice", prompt: "Hansı sırada yalnız qalın saitlər var?", options: ["a, ı, o, u", "e, ə, i", "a, e, o", "ü, ö, u"], correctIndex: 0, xp: 15 },
            { id: "az6-fon-l1-b2", type: "multiple_choice", prompt: "'ç' samitinin kar/cingiltili qarşılığı 'c'-dir. 'ç' necədir?", options: ["kar", "cingiltili", "sait", "qoşa"], correctIndex: 0, xp: 15 },
            { id: "az6-fon-l1-b3", type: "multiple_choice", prompt: "Hansı sırada yalnız incə saitlər var?", options: ["e, ə, i, ö, ü", "a, ı, o, u", "a, e, i", "o, u, ü"], correctIndex: 0, xp: 15 },
            { id: "az6-fon-l1-b4", type: "multiple_choice", prompt: "'z' səsi necə samitdir?", options: ["cingiltili", "kar", "sait", "yarımsait"], correctIndex: 0, xp: 15 },
            { id: "az6-fon-l1-b5", type: "fill_blank", prompt: "Tələffüz etdiyimiz — ___-dir (hərfin qarşılığı).", accepted: ["səs", "ses"], xp: 15 },
          ],
        },
        {
          id: "az6-fon-l2",
          title: "Ahəng qanunu",
          intro: "Sözdə saitlərin bir-birinə uyğunlaşması qanunu.",
          sections: [
            { heading: "Ahəng qanunu nədir?", body: "Sözdə saitlərin qalınlıq-incəliyə görə bir-birinə uyğunlaşmasına ahəng qanunu deyilir: kitablar (a-a-a — qalın), evlər (e-ə — incə)." },
            { heading: "Damaq ahəngi", body: "Qalın saitdən sonra qalın, incə saitdən sonra incə sait gəlir: yollar (qalın), gəlirlər (incə)." },
            { heading: "Pozulma", body: "Bəzi sözlərdə (alınma sözlər) ahəng qanunu pozulur: kitab, məktəb, tələbə. Şəkilçilər son saitə uyğunlaşır." },
          ],
          tasks: [
            { id: "az6-fon-l2-t1", type: "multiple_choice", prompt: "Sözdə saitlərin bir-birinə uyğunlaşmasına nə deyilir?", options: ["ahəng qanunu", "vurğu", "heca", "səsartımı"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t2", type: "multiple_choice", prompt: "'yollar' sözündə saitlər necədir?", options: ["qalın", "incə", "qarışıq", "yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t3", type: "multiple_choice", prompt: "'evlər' sözündə saitlər necədir?", options: ["incə", "qalın", "qarışıq", "yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t4", type: "multiple_choice", prompt: "Qalın saitdən sonra hansı şəkilçi gəlir?", options: ["qalın saitli", "incə saitli", "samitli", "fərqi yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t5", type: "multiple_choice", prompt: "Hansı sözdə ahəng qanunu var (qalın)?", options: ["qapılar", "evlər", "gəmilər", "üzüklər"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t6", type: "multiple_choice", prompt: "Hansı sözdə ahəng qanunu pozulub (alınma söz)?", options: ["kitab", "yollar", "daşlar", "qollar"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t7", type: "multiple_choice", prompt: "'kitab' sözünə cəm şəkilçisi hansı formada gələr?", options: ["-lar", "-lər", "hər ikisi", "gəlməz"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t8", type: "multiple_choice", prompt: "'ev' sözünə cəm şəkilçisi hansı formada gələr?", options: ["-lər", "-lar", "hər ikisi", "gəlməz"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t9", type: "multiple_choice", prompt: "Hansı söz incə saitlidir?", options: ["üzüm", "qapı", "yol", "daş"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t10", type: "multiple_choice", prompt: "Hansı söz qalın saitlidir?", options: ["armud", "gəl", "ev", "il"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t11", type: "fill_blank", prompt: "'qız' sözünə cəm şəkilçisi: qız___", accepted: ["lar"], xp: 10 },
            { id: "az6-fon-l2-t12", type: "fill_blank", prompt: "'gül' sözünə cəm şəkilçisi: gül___", accepted: ["lər"], xp: 10 },
            { id: "az6-fon-l2-t13", type: "multiple_choice", prompt: "Ahəng qanununa görə şəkilçi nəyə uyğunlaşır?", options: ["son saitə", "ilk saitə", "samitə", "vurğuya"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t14", type: "multiple_choice", prompt: "Hansı sözdə ahəng qanunu pozulub?", options: ["tələbə", "sular", "quşlar", "yollar"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l2-t15", type: "fill_blank", prompt: "'at' sözünə cəm şəkilçisi: at___", accepted: ["lar"], xp: 15 },
          ],
          bonusTasks: [
            { id: "az6-fon-l2-b1", type: "multiple_choice", prompt: "'məktəb' sözündə ahəng qanunu:", options: ["pozulub (alınma)", "qalın", "incə", "yoxdur"], correctIndex: 0, xp: 15 },
            { id: "az6-fon-l2-b2", type: "fill_blank", prompt: "'kitab' sözünə yer şəkilçisi: kitab___ (da/də)", accepted: ["da"], xp: 15 },
            { id: "az6-fon-l2-b3", type: "multiple_choice", prompt: "Hansı söz tam incə saitlidir?", options: ["sevgi", "qapı", "ata", "yol"], correctIndex: 0, xp: 15 },
            { id: "az6-fon-l2-b4", type: "fill_blank", prompt: "'ürək' sözünə cəm şəkilçisi: ürək___", accepted: ["lər"], xp: 15 },
            { id: "az6-fon-l2-b5", type: "multiple_choice", prompt: "Ahəng qanunu əsasən nəyə əsaslanır?", options: ["saitlərin qalın-incəliyinə", "samitlərə", "vurğuya", "heca sayına"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az6-fon-l3",
          title: "Heca, vurğu və böyük hərf",
          intro: "Sözü hecalara bölmək, vurğunu təyin etmək və böyük hərf qaydaları.",
          sections: [
            { heading: "Heca", body: "Söz saitlərin sayı qədər hecaya bölünür: ki-tab (2 heca), mə-ni-si (3 heca). Hecasız söz olmur." },
            { heading: "Vurğu", body: "Sözdə bir hecanın digərlərindən qüvvətli deyilməsi vurğudur. Azərbaycan dilində vurğu adətən son hecaya düşür: kitáb, evlér." },
            { heading: "Böyük hərf", body: "Cümlənin əvvəli, xüsusi isimlər (adlar, şəhərlər, ölkələr) böyük hərflə yazılır: Bakı, Azərbaycan, Nizami." },
          ],
          tasks: [
            { id: "az6-fon-l3-t1", type: "numeric", prompt: "'kitab' sözündə neçə heca var?", answer: 2, xp: 10 },
            { id: "az6-fon-l3-t2", type: "numeric", prompt: "'məktəb' sözündə neçə heca var?", answer: 2, xp: 10 },
            { id: "az6-fon-l3-t3", type: "numeric", prompt: "'Azərbaycan' sözündə neçə heca var?", answer: 4, xp: 10 },
            { id: "az6-fon-l3-t4", type: "multiple_choice", prompt: "Söz neçə hecaya bölünür?", options: ["saitlərin sayı qədər", "samitlərin sayı qədər", "hərflərin sayı qədər", "həmişə 2"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l3-t5", type: "multiple_choice", prompt: "Azərbaycan dilində vurğu adətən hansı hecaya düşür?", options: ["son", "ilk", "orta", "heç birinə"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l3-t6", type: "numeric", prompt: "'alma' sözündə neçə heca var?", answer: 2, xp: 10 },
            { id: "az6-fon-l3-t7", type: "numeric", prompt: "'ev' sözündə neçə heca var?", answer: 1, xp: 10 },
            { id: "az6-fon-l3-t8", type: "multiple_choice", prompt: "Hansı böyük hərflə yazılmalıdır?", options: ["bakı", "kitab", "alma", "su"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l3-t9", type: "multiple_choice", prompt: "Hansı xüsusi isimdir (böyük hərflə)?", options: ["Nizami", "şagird", "müəllim", "dağ"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l3-t10", type: "numeric", prompt: "'müəllim' sözündə neçə heca var?", answer: 3, xp: 10 },
            { id: "az6-fon-l3-t11", type: "multiple_choice", prompt: "Cümlənin əvvəlində söz necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "fərqi yoxdur", "hamısı böyük"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l3-t12", type: "numeric", prompt: "'gül' sözündə neçə heca var?", answer: 1, xp: 10 },
            { id: "az6-fon-l3-t13", type: "multiple_choice", prompt: "Hansı ölkə adıdır (böyük hərflə)?", options: ["Azərbaycan", "şəhər", "ölkə", "dəniz"], correctIndex: 0, xp: 10 },
            { id: "az6-fon-l3-t14", type: "numeric", prompt: "'dəftər' sözündə neçə heca var?", answer: 2, xp: 10 },
            { id: "az6-fon-l3-t15", type: "numeric", prompt: "'qələmdanlıq' sözündə neçə heca var?", answer: 4, xp: 15 },
          ],
          bonusTasks: [
            { id: "az6-fon-l3-b1", type: "numeric", prompt: "'təbiət' sözündə neçə heca var?", answer: 3, xp: 15 },
            { id: "az6-fon-l3-b2", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Bakı şəhəri", "bakı şəhəri", "BAKI şəhəri", "Bakı Şəhəri"], correctIndex: 0, xp: 15 },
            { id: "az6-fon-l3-b3", type: "numeric", prompt: "'kompüter' sözündə neçə heca var?", answer: 3, xp: 15 },
            { id: "az6-fon-l3-b4", type: "multiple_choice", prompt: "İnsan adları necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "fərqi yoxdur", "dırnaqda"], correctIndex: 0, xp: 15 },
            { id: "az6-fon-l3-b5", type: "numeric", prompt: "'yaz-mı-şam' — 'yazmışam' sözündə neçə heca var?", answer: 3, xp: 15 },
          ],
        },
      ],
    },

    // ═══════════════ 2. Leksika ═══════════════
    {
      id: "az6-leksika",
      title: "Leksika",
      description:
        "Sözün həqiqi və məcazi mənası, sinonim, antonim, omonim və çoxmənalı sözlər.",
      lessons: [
        {
          id: "az6-lek-l1",
          title: "Sözün həqiqi və məcazi mənası",
          intro: "Sözün ilkin (həqiqi) və köçürülmüş (məcazi) mənasını ayırd etmək.",
          sections: [
            { heading: "Həqiqi məna", body: "Sözün ilk, əsas mənasına həqiqi məna deyilir: 'dəmir qapı' — dəmirdən düzəlmiş qapı." },
            { heading: "Məcazi məna", body: "Sözün başqa əşyaya köçürülmüş, obrazlı mənasına məcazi məna deyilir: 'dəmir iradə' — möhkəm iradə. Burada 'dəmir' həqiqi deyil." },
            { heading: "Necə ayıraq?", body: "Söz doğrudan həmin əşyanı bildirirsə — həqiqi; oxşatma, obraz üçün işlənirsə — məcazidir: 'şirin çay' (həqiqi), 'şirin söz' (məcazi)." },
          ],
          tasks: [
            { id: "az6-lek-l1-t1", type: "multiple_choice", prompt: "Sözün ilk, əsas mənasına nə deyilir?", options: ["həqiqi məna", "məcazi məna", "sinonim", "antonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t2", type: "multiple_choice", prompt: "Sözün obrazlı, köçürülmüş mənasına nə deyilir?", options: ["məcazi məna", "həqiqi məna", "omonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t3", type: "multiple_choice", prompt: "'dəmir qapı' — 'dəmir' necə mənadadır?", options: ["həqiqi", "məcazi", "sinonim", "antonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t4", type: "multiple_choice", prompt: "'dəmir iradə' — 'dəmir' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t5", type: "multiple_choice", prompt: "'şirin alma' — 'şirin' necə mənadadır?", options: ["həqiqi", "məcazi", "antonim", "sinonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t6", type: "multiple_choice", prompt: "'şirin söz' — 'şirin' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t7", type: "multiple_choice", prompt: "'soyuq hava' — 'soyuq' necə mənadadır?", options: ["həqiqi", "məcazi", "sinonim", "antonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t8", type: "multiple_choice", prompt: "'soyuq baxış' — 'soyuq' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t9", type: "multiple_choice", prompt: "'qızıl üzük' — 'qızıl' necə mənadadır?", options: ["həqiqi", "məcazi", "antonim", "sinonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t10", type: "multiple_choice", prompt: "'qızıl əllər' — 'qızıl' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t11", type: "multiple_choice", prompt: "'ağır yük' — 'ağır' necə mənadadır?", options: ["həqiqi", "məcazi", "sinonim", "antonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t12", type: "multiple_choice", prompt: "'ağır söz' — 'ağır' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t13", type: "multiple_choice", prompt: "'isti çörək' — necə mənadadır?", options: ["həqiqi", "məcazi", "antonim", "omonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t14", type: "multiple_choice", prompt: "'isti münasibət' — necə mənadadır?", options: ["məcazi", "həqiqi", "sinonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l1-t15", type: "multiple_choice", prompt: "'daş ürək' ifadəsi necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "sinonim"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az6-lek-l1-b1", type: "multiple_choice", prompt: "'Günəş doğdu' — 'doğdu' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l1-b2", type: "multiple_choice", prompt: "'açıq qapı' — 'açıq' necə mənadadır?", options: ["həqiqi", "məcazi", "antonim", "sinonim"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l1-b3", type: "multiple_choice", prompt: "'açıq ürəkli' — 'açıq' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "heca"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l1-b4", type: "multiple_choice", prompt: "Məcazi məna nə üçün işlənir?", options: ["obraz, oxşatma", "həqiqəti demək", "saymaq", "heca ayırmaq"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l1-b5", type: "multiple_choice", prompt: "'dağın ətəyi' — 'ətək' necə mənadadır?", options: ["məcazi", "həqiqi", "omonim", "sinonim"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az6-lek-l2",
          title: "Sinonim və antonim",
          intro: "Mənaca yaxın (sinonim) və əks (antonim) sözlər.",
          sections: [
            { heading: "Sinonim", body: "Formaca müxtəlif, mənaca yaxın sözlərə sinonim deyilir: gözəl — qəşəng — göyçək; böyük — iri; cəsur — igid." },
            { heading: "Antonim", body: "Mənaca bir-birinin əksi olan sözlərə antonim deyilir: böyük — kiçik; isti — soyuq; ağ — qara; gündüz — gecə." },
            { heading: "Fayda", body: "Sinonimlər nitqi zənginləşdirir, təkrarın qarşısını alır. Antonimlər fikri qarşılaşdırmaqla gücləndirir." },
          ],
          tasks: [
            { id: "az6-lek-l2-t1", type: "multiple_choice", prompt: "Mənaca yaxın sözlərə nə deyilir?", options: ["sinonim", "antonim", "omonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t2", type: "multiple_choice", prompt: "Mənaca əks sözlərə nə deyilir?", options: ["antonim", "sinonim", "omonim", "vurğu"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t3", type: "multiple_choice", prompt: "'gözəl' sözünün sinonimi hansıdır?", options: ["qəşəng", "çirkin", "böyük", "soyuq"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t4", type: "multiple_choice", prompt: "'böyük' sözünün antonimi hansıdır?", options: ["kiçik", "iri", "nəhəng", "geniş"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t5", type: "multiple_choice", prompt: "'isti' sözünün antonimi hansıdır?", options: ["soyuq", "qaynar", "ilıq", "yandırıcı"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t6", type: "multiple_choice", prompt: "'cəsur' sözünün sinonimi hansıdır?", options: ["igid", "qorxaq", "zəif", "kiçik"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t7", type: "fill_blank", prompt: "'ağ' sözünün antonimini yaz.", accepted: ["qara"], xp: 10 },
            { id: "az6-lek-l2-t8", type: "fill_blank", prompt: "'gündüz' sözünün antonimini yaz.", accepted: ["gecə", "gece"], xp: 10 },
            { id: "az6-lek-l2-t9", type: "multiple_choice", prompt: "'sevinc' sözünün antonimi hansıdır?", options: ["kədər", "şadlıq", "gülüş", "fərəh"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t10", type: "multiple_choice", prompt: "'iri' sözünün sinonimi hansıdır?", options: ["böyük", "kiçik", "dar", "alçaq"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t11", type: "fill_blank", prompt: "'uzun' sözünün antonimini yaz.", accepted: ["qısa", "qisa"], xp: 10 },
            { id: "az6-lek-l2-t12", type: "fill_blank", prompt: "'açıq' sözünün antonimini yaz.", accepted: ["bağlı", "bagli"], xp: 10 },
            { id: "az6-lek-l2-t13", type: "multiple_choice", prompt: "'sürətli' sözünün antonimi hansıdır?", options: ["yavaş", "cəld", "iti", "tez"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t14", type: "multiple_choice", prompt: "'xoşbəxt' sözünün sinonimi hansıdır?", options: ["bəxtiyar", "bədbəxt", "kədərli", "yorğun"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l2-t15", type: "fill_blank", prompt: "'dost' sözünün antonimini yaz.", accepted: ["düşmən", "düsmən", "dusmen"], xp: 15 },
          ],
          bonusTasks: [
            { id: "az6-lek-l2-b1", type: "fill_blank", prompt: "'yaxşı' sözünün antonimini yaz.", accepted: ["pis"], xp: 15 },
            { id: "az6-lek-l2-b2", type: "multiple_choice", prompt: "'zəngin' sözünün antonimi hansıdır?", options: ["kasıb", "varlı", "dövlətli", "böyük"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l2-b3", type: "multiple_choice", prompt: "'gülmək' sözünün antonimi hansıdır?", options: ["ağlamaq", "sevinmək", "danışmaq", "baxmaq"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l2-b4", type: "fill_blank", prompt: "'əvvəl' sözünün antonimini yaz.", accepted: ["sonra", "son"], xp: 15 },
            { id: "az6-lek-l2-b5", type: "multiple_choice", prompt: "'hündür' sözünün sinonimi hansıdır?", options: ["uca", "alçaq", "gödək", "enli"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az6-lek-l3",
          title: "Omonim və çoxmənalı sözlər",
          intro: "Eyni yazılıb müxtəlif məna verən (omonim) və bir neçə mənalı sözlər.",
          sections: [
            { heading: "Omonim", body: "Eyni cür yazılıb-deyilən, lakin mənaca tamamilə fərqli sözlərə omonim deyilir: 'üz' (sifət) və 'üz' (üzmək əmri); 'yaz' (fəsil) və 'yaz' (yazmaq əmri)." },
            { heading: "Çoxmənalı söz", body: "Bir sözün bir-biri ilə əlaqəli bir neçə mənası ola bilər: 'baş' (insanın başı, dağın başı, işin başı). Mənalar arasında əlaqə var." },
            { heading: "Fərq", body: "Omonimlərin mənaları arasında əlaqə YOXDUR (təsadüfən eyni yazılır); çoxmənalı sözün mənaları arasında əlaqə VAR." },
          ],
          tasks: [
            { id: "az6-lek-l3-t1", type: "multiple_choice", prompt: "Eyni yazılıb fərqli məna verən sözlərə nə deyilir?", options: ["omonim", "sinonim", "antonim", "heca"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t2", type: "multiple_choice", prompt: "'yaz' (fəsil) və 'yaz' (yazmaq) sözləri necədir?", options: ["omonim", "sinonim", "antonim", "çoxmənalı"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t3", type: "multiple_choice", prompt: "Omonimlərin mənaları arasında əlaqə...?", options: ["yoxdur", "var", "həmişə var", "sinonimdir"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t4", type: "multiple_choice", prompt: "Çoxmənalı sözün mənaları arasında əlaqə...?", options: ["var", "yoxdur", "təsadüfidir", "əksdir"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t5", type: "multiple_choice", prompt: "'baş' (insan başı, dağ başı) — necə sözdür?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t6", type: "multiple_choice", prompt: "'üz' (sifət) və 'üz' (üzmək) — necədir?", options: ["omonim", "çoxmənalı", "sinonim", "antonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t7", type: "multiple_choice", prompt: "'ağız' (insanın ağzı, çayın ağzı) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t8", type: "multiple_choice", prompt: "'at' (heyvan) və 'at' (atmaq əmri) — necədir?", options: ["omonim", "sinonim", "antonim", "çoxmənalı"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t9", type: "multiple_choice", prompt: "'göz' (insanın gözü, iynənin gözü) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t10", type: "multiple_choice", prompt: "'sağ' (istiqamət) və 'sağ' (diri) — necədir?", options: ["omonim", "çoxmənalı", "sinonim", "antonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t11", type: "multiple_choice", prompt: "'qol' (insanın qolu, çayın qolu) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t12", type: "multiple_choice", prompt: "'diş' (insanın dişi, daraq dişi) — necədir?", options: ["çoxmənalı", "omonim", "sinonim", "antonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t13", type: "multiple_choice", prompt: "'gül' (çiçək) və 'gül' (gülmək əmri) — necədir?", options: ["omonim", "çoxmənalı", "sinonim", "antonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t14", type: "multiple_choice", prompt: "'ayaq' (insanın ayağı, stolun ayağı) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 10 },
            { id: "az6-lek-l3-t15", type: "multiple_choice", prompt: "'daş' (daşımaq əmri) və 'daş' (qaya) — necədir?", options: ["omonim", "çoxmənalı", "sinonim", "antonim"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az6-lek-l3-b1", type: "multiple_choice", prompt: "'burun' (insanın burnu, gəminin burnu) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l3-b2", type: "multiple_choice", prompt: "'ət' (yemək) və 'et' (etmək) omonimə oxşasa da nə fərqi var?", options: ["fərqli yazılır", "eynidir", "sinonimdir", "antonimdir"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l3-b3", type: "multiple_choice", prompt: "'dil' (orqan, danışıq dili) — necədir?", options: ["çoxmənalı", "omonim", "antonim", "sinonim"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l3-b4", type: "multiple_choice", prompt: "Omonim ilə çoxmənalını nə ayırır?", options: ["mənalar arası əlaqə", "yazılış", "heca sayı", "vurğu"], correctIndex: 0, xp: 15 },
            { id: "az6-lek-l3-b5", type: "multiple_choice", prompt: "'yol' (cığır, həyat yolu) — necədir?", options: ["çoxmənalı", "omonim", "sinonim", "antonim"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
  ],
};
