// Azərbaycan dili — "Nitq hissələri" treki. Hər dərs bir layihədir (project).
// Qaydalar (sections) holberton3 üslubunda şəkil altında göstərilir.
// Hər layihə: 15 əsas tapşırıq + 5 bonus (İngilis treki ilə eyni standart).

import type { Subject } from "../types";

export const azerbaijani: Subject = {
  slug: "azerbaycan-dili",
  name: "Azərbaycan dili",
  grade: 5,
  icon: "📖",
  color: "rose",
  units: [
    {
      id: "az-parts-of-speech",
      title: "Nitq hissələri",
      description: "İsim, sifət və feil — sözlərin növləri.",
      lessons: [
        {
          id: "az-u1-l1",
          title: "İsim",
          intro: "İsim əşyaların adıdır.",
          visual: "noun-cards",
          sections: [
            { heading: "İsim nədir?", body: "İsim əşyaların, insanların, canlıların və yerlərin adını bildirən nitq hissəsidir." },
            { heading: "kim? / nə?", body: "Canlılar 'kim?' sualına cavab verir (uşaq, quş). Cansız əşyalar 'nə?' sualına cavab verir (alma, kitab)." },
            { heading: "Ümumi və xüsusi isim", body: "Ümumi isim ortaq adı bildirir (şəhər, çay). Xüsusi isim konkret addır və həmişə böyük hərflə yazılır (Bakı, Nigar)." },
          ],
          tasks: [
            { id: "az-u1-l1-t1", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı isimdir?", options: ["gözəl", "oxumaq", "pəncərə", "tez"], correctIndex: 2, xp: 10 },
            { id: "az-u1-l1-t2", type: "multiple_choice", prompt: "Hansı söz 'kim?' sualına cavab verir?", options: ["daş", "müəllim", "yaşıl", "qaçmaq"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l1-t3", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı xüsusi isimdir?", options: ["şəhər", "Gəncə", "çay", "dağ"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l1-t4", type: "fill_blank", prompt: "'Kitablar' sözündəki cəm şəkilçisini yaz.", accepted: ["-lar", "lar"], xp: 10 },
            { id: "az-u1-l1-t5", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı 'nə?' sualına cavab verir?", options: ["dost", "sərçə", "alma", "bacı"], correctIndex: 2, xp: 10 },
            { id: "az-u1-l1-t6", type: "fill_blank", prompt: "Xüsusi isimlər həmişə ___ hərflə yazılır.", accepted: ["böyük", "boyuk"], xp: 10 },
            { id: "az-u1-l1-t7", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı isimdir?", options: ["qırmızı", "dəniz", "sürətli", "oxumaq"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l1-t8", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı xüsusi isimdir?", options: ["ölkə", "Azərbaycan", "şəhər", "kənd"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l1-t9", type: "fill_blank", prompt: "İsim 'kim?' və '___?' suallarına cavab verir.", accepted: ["nə", "ne"], xp: 10 },
            { id: "az-u1-l1-t10", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı 'kim?' sualına cavab verir?", options: ["ana", "daş", "qapı", "su"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l1-t11", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı ümumi isimdir?", options: ["Nigar", "dağ", "Gəncə", "Xəzər"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l1-t12", type: "fill_blank", prompt: "'Bakı' sözü ___ isimdir. (ümumi / xüsusi)", accepted: ["xüsusi", "xususi"], xp: 10 },
            { id: "az-u1-l1-t13", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı cansız əşyanın adıdır?", options: ["pişik", "quş", "kitab", "uşaq"], correctIndex: 2, xp: 10 },
            { id: "az-u1-l1-t14", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı cəm haldadır?", options: ["gül", "güllər", "gülü", "gülə"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l1-t15", type: "fill_blank", prompt: "İnsan adları ___ isimlərdir. (ümumi / xüsusi)", accepted: ["xüsusi", "xususi"], xp: 15 },
          ],
          bonusTasks: [
            { id: "az-u1-l1-b1", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı isim deyil?", options: ["pəncərə", "stol", "gözəl", "quş"], correctIndex: 2, xp: 15 },
            { id: "az-u1-l1-b2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün yazılıb?", options: ["bakı", "Bakı", "BAKı", "baKı"], correctIndex: 1, xp: 15 },
            { id: "az-u1-l1-b3", type: "fill_blank", prompt: "'Şagirdlər' sözündəki cəm şəkilçisini yaz.", accepted: ["-lər", "lər"], xp: 15 },
            { id: "az-u1-l1-b4", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı 'nə?' sualına cavab verir?", options: ["müəllim", "dost", "ağac", "bacı"], correctIndex: 2, xp: 15 },
            { id: "az-u1-l1-b5", type: "multiple_choice", prompt: "Hansı qrup yalnız isimlərdən ibarətdir?", options: ["ev, kitab, quş", "gözəl, ev, qaçmaq", "getmək, oxumaq, yazmaq", "ağ, qırmızı, yaşıl"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az-u1-l2",
          title: "Sifət",
          intro: "Sifət əşyanın necə olduğunu bildirir.",
          visual: "adjective-apple",
          sections: [
            { heading: "Sifət nədir?", body: "Sifət əşyanın əlamətini, keyfiyyətini və ya rəngini bildirən nitq hissəsidir." },
            { heading: "Suallar", body: "Sifət 'necə?' və 'hansı?' suallarına cavab verir və çox zaman ismin yanında işlənir (qırmızı alma)." },
            { heading: "Nümunələr", body: "Sifət rəngi (ağ), ölçünü (böyük), dadı (şirin) və formanı (yumru) bildirə bilər." },
          ],
          tasks: [
            { id: "az-u1-l2-t1", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı sifətdir?", options: ["qələm", "şirin", "getmək", "şagird"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l2-t2", type: "multiple_choice", prompt: "'Hündür ağac' birləşməsində sifət hansıdır?", options: ["hündür", "ağac", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l2-t3", type: "multiple_choice", prompt: "Sifət aşağıdakı suallardan hansına cavab verir?", options: ["kim?", "nə?", "necə?", "harada?"], correctIndex: 2, xp: 10 },
            { id: "az-u1-l2-t4", type: "fill_blank", prompt: "'Böyük ev' birləşməsində əşyanın əlamətini bildirən sözü yaz.", accepted: ["böyük", "boyuk"], xp: 10 },
            { id: "az-u1-l2-t5", type: "multiple_choice", prompt: "Aşağıdakılardan hansı rəng bildirən sifətdir?", options: ["yumru", "yaşıl", "acı", "kiçik"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l2-t6", type: "multiple_choice", prompt: "Hansı söz birləşməsində sifət var?", options: ["isti çay", "su içmək", "evə getmək", "kitab oxumaq"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l2-t7", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı sifətdir?", options: ["qırmızı", "qaçmaq", "ev", "uşaq"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l2-t8", type: "multiple_choice", prompt: "'İsti çörək' birləşməsində sifət hansıdır?", options: ["isti", "çörək", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l2-t9", type: "fill_blank", prompt: "Sifət 'necə?' və '___?' suallarına cavab verir.", accepted: ["hansı", "hansi"], xp: 10 },
            { id: "az-u1-l2-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı ölçü bildirən sifətdir?", options: ["kiçik", "alma", "getmək", "tez"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l2-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı dad bildirən sifətdir?", options: ["şirin", "mavi", "uzun", "yumru"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l2-t12", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı sifət deyil?", options: ["gözəl", "hündür", "kitab", "ağ"], correctIndex: 2, xp: 10 },
            { id: "az-u1-l2-t13", type: "fill_blank", prompt: "'Yaşıl yarpaq' birləşməsində əlaməti bildirən sözü yaz.", accepted: ["yaşıl", "yasil"], xp: 10 },
            { id: "az-u1-l2-t14", type: "multiple_choice", prompt: "'Böyük' sözünün əksi olan sifət hansıdır?", options: ["kiçik", "geniş", "uzun", "hündür"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l2-t15", type: "multiple_choice", prompt: "Hansı söz birləşməsində sifət var?", options: ["soyuq su", "su içmək", "kitab oxumaq", "evə getmək"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az-u1-l2-b1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı rəng bildirən sifətdir?", options: ["sürətli", "qara", "acı", "yumşaq"], correctIndex: 1, xp: 15 },
            { id: "az-u1-l2-b2", type: "fill_blank", prompt: "Sifət çox zaman ___ yanında işlənir. (nitq hissəsi)", accepted: ["isim", "ismin", "isimin"], xp: 15 },
            { id: "az-u1-l2-b3", type: "multiple_choice", prompt: "Hansı qrup yalnız sifətlərdən ibarətdir?", options: ["ağ, şirin, böyük", "ev, ağ, qaçmaq", "getmək, gözəl, dost", "kitab, alma, quş"], correctIndex: 0, xp: 15 },
            { id: "az-u1-l2-b4", type: "multiple_choice", prompt: "'Hündür' sözü nəyi bildirir?", options: ["rəngi", "ölçünü", "dadı", "hərəkəti"], correctIndex: 1, xp: 15 },
            { id: "az-u1-l2-b5", type: "fill_blank", prompt: "'Acı' sözü ___ bildirən sifətdir. (rəng / dad / ölçü)", accepted: ["dad", "dadı", "dadi"], xp: 15 },
          ],
        },
        {
          id: "az-u1-l3",
          title: "Feil",
          intro: "Feil hərəkəti bildirir.",
          visual: "verb-timeline",
          sections: [
            { heading: "Feil nədir?", body: "Feil əşyanın hərəkətini və ya iş prosesini bildirən nitq hissəsidir (qaçmaq, yazmaq, gülmək)." },
            { heading: "Suallar", body: "Feil 'nə etdi?', 'nə edir?', 'nə edəcək?' kimi suallara cavab verir." },
            { heading: "Zaman", body: "Feillər zamana görə dəyişir: yazdı (keçmiş), yazır (indiki), yazacaq (gələcək)." },
          ],
          tasks: [
            { id: "az-u1-l3-t1", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı feildir?", options: ["gözəl", "qaçmaq", "kitab", "yaşıl"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l3-t2", type: "multiple_choice", prompt: "Hansı söz 'nə etdi?' sualına cavab verir?", options: ["gəldi", "şagird", "ağ", "stol"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l3-t3", type: "multiple_choice", prompt: "'Uşaq oxuyur' cümləsində feil hansıdır?", options: ["uşaq", "oxuyur", "hər ikisi", "heç biri"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l3-t4", type: "fill_blank", prompt: "'Yazdı' feili hansı zamandadır? (keçmiş / indiki / gələcək)", accepted: ["keçmiş", "kecmis", "keçmiş zaman"], xp: 10 },
            { id: "az-u1-l3-t5", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı gələcək zamanı bildirir?", options: ["gəldi", "gəlir", "gələcək", "gəlmək"], correctIndex: 2, xp: 10 },
            { id: "az-u1-l3-t6", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı hərəkət bildirir?", options: ["sevinc", "gülmək", "şən", "dost"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l3-t7", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı feildir?", options: ["yazmaq", "kitab", "gözəl", "dost"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l3-t8", type: "multiple_choice", prompt: "'Quş uçur' cümləsində feil hansıdır?", options: ["quş", "uçur", "hər ikisi", "heç biri"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l3-t9", type: "fill_blank", prompt: "'Gələcək' feili hansı zamandadır? (keçmiş / indiki / gələcək)", accepted: ["gələcək", "gelecek", "gələcək zaman"], xp: 10 },
            { id: "az-u1-l3-t10", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı keçmiş zamanı bildirir?", options: ["oxudu", "oxuyur", "oxuyacaq", "oxumaq"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l3-t11", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı indiki zamanı bildirir?", options: ["gəldi", "gəlir", "gələcək", "gəlmək"], correctIndex: 1, xp: 10 },
            { id: "az-u1-l3-t12", type: "fill_blank", prompt: "Feil əşyanın ___ bildirir.", accepted: ["hərəkət", "hereket", "hərəkətini", "hereketini"], xp: 10 },
            { id: "az-u1-l3-t13", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı hərəkət bildirir?", options: ["qaçmaq", "sevinc", "şən", "dost"], correctIndex: 0, xp: 10 },
            { id: "az-u1-l3-t14", type: "multiple_choice", prompt: "'Yazacaq' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 2, xp: 10 },
            { id: "az-u1-l3-t15", type: "multiple_choice", prompt: "'Uşaqlar oynayır' cümləsində feil hansıdır?", options: ["uşaqlar", "oynayır", "hər ikisi", "heç biri"], correctIndex: 1, xp: 15 },
          ],
          bonusTasks: [
            { id: "az-u1-l3-b1", type: "multiple_choice", prompt: "Hansı qrup yalnız feillərdən ibarətdir?", options: ["yazmaq, qaçmaq, gülmək", "ev, kitab, quş", "gözəl, ağ, şirin", "dost, bacı, ana"], correctIndex: 0, xp: 15 },
            { id: "az-u1-l3-b2", type: "fill_blank", prompt: "Feillər ___ görə dəyişir. (nəyə görə)", accepted: ["zamana", "zaman"], xp: 15 },
            { id: "az-u1-l3-b3", type: "multiple_choice", prompt: "'Getdi' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "az-u1-l3-b4", type: "multiple_choice", prompt: "Aşağıdakı sözlərdən hansı feil deyil?", options: ["oxumaq", "yazmaq", "qələm", "gülmək"], correctIndex: 2, xp: 15 },
            { id: "az-u1-l3-b5", type: "fill_blank", prompt: "'Nə edir?' sualına cavab verən söz hansı nitq hissəsidir?", accepted: ["feil", "feildir"], xp: 15 },
          ],
        },
      ],
    },
  ],
};
