// Azərbaycan dili — 4-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) İsim və halları  2) Əvəzlik  3) Zərf  4) Cümlə üzvləri
// 5) Söz yaradıcılığı və orfoqrafiya  6) Mətn və nitq.
// 4-cü sinif üçün. id prefiksi az4-*.

import type { Subject } from "../types";

export const azerbaijani4: Subject = {
  slug: "azerbaycan-dili-4",
  name: "Azərbaycan dili",
  grade: 4,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. İsim və halları ═══════════════
    {
      id: "az4-isim",
      title: "İsim və halları",
      description: "İsmin təkrarı, tək/cəm, xüsusi/ümumi və halları ilə ilkin tanışlıq.",
      lessons: [
        {
          id: "az4-isim-l1",
          title: "İsim və halları",
          intro: "İsim əşyanın adıdır; suala görə hallanır.",
          sections: [
            { heading: "İsim", body: "Əşyanın adını bildirən söz isimdir: 'kim?' (insan/heyvan), 'nə?' (əşya). Tək/cəm, xüsusi/ümumi olur." },
            { heading: "Hallar", body: "İsim suala görə dəyişir (hallanır): adlıq (kim? nə?), yiyəlik (kimin? nəyin?), yönlük (kimə? nəyə?), təsirlik (kimi? nəyi?), yerlik (kimdə? nədə?), çıxışlıq (kimdən? nədən?)." },
          ],
          tasks: [
            { id: "az4-isim-l1-t1", type: "multiple_choice", prompt: "İsim hansı suallara cavab verir?", options: ["kim? nə?", "necə?", "nə edir?", "neçə?"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t2", type: "multiple_choice", prompt: "Adlıq hal hansı suala cavab verir?", options: ["kim? nə?", "kimin?", "kimə?", "kimdən?"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t3", type: "multiple_choice", prompt: "'kimin? nəyin?' hansı haldır?", options: ["yiyəlik", "adlıq", "yönlük", "təsirlik"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t4", type: "multiple_choice", prompt: "'kimə? nəyə?' hansı haldır?", options: ["yönlük", "yiyəlik", "təsirlik", "yerlik"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t5", type: "multiple_choice", prompt: "'kimi? nəyi?' hansı haldır?", options: ["təsirlik", "yönlük", "yerlik", "çıxışlıq"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t6", type: "multiple_choice", prompt: "'kimdə? nədə?' hansı haldır?", options: ["yerlik", "çıxışlıq", "yönlük", "adlıq"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t7", type: "multiple_choice", prompt: "'kimdən? nədən?' hansı haldır?", options: ["çıxışlıq", "yerlik", "yönlük", "təsirlik"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t8", type: "numeric", prompt: "İsmin neçə halı var?", answer: 6, xp: 10 },
            { id: "az4-isim-l1-t9", type: "multiple_choice", prompt: "'kitabı' sözü hansı haldadır?", options: ["təsirlik (nəyi?)", "adlıq", "yiyəlik", "yerlik"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t10", type: "multiple_choice", prompt: "'evdə' sözü hansı haldadır?", options: ["yerlik (nədə?)", "yönlük", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t11", type: "multiple_choice", prompt: "'evə' sözü hansı haldadır?", options: ["yönlük (nəyə?)", "yerlik", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t12", type: "multiple_choice", prompt: "'evdən' sözü hansı haldadır?", options: ["çıxışlıq (nədən?)", "yerlik", "yönlük", "adlıq"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t13", type: "multiple_choice", prompt: "Xüsusi isimlər necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "cəmdə", "rəqəmlə"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t14", type: "multiple_choice", prompt: "'uşaqlar' sözü hansı formadadır?", options: ["cəm", "tək", "xüsusi", "feil"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l1-t15", type: "multiple_choice", prompt: "'uşağın' sözü hansı haldadır?", options: ["yiyəlik (kimin?)", "adlıq", "təsirlik", "yerlik"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az4-isim-l1-b1", type: "multiple_choice", prompt: "'məktəbə' sözü hansı haldadır?", options: ["yönlük", "yerlik", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 15 },
            { id: "az4-isim-l1-b2", type: "multiple_choice", prompt: "'dostumdan' sözü hansı haldadır?", options: ["çıxışlıq", "yönlük", "yerlik", "təsirlik"], correctIndex: 0, xp: 15 },
            { id: "az4-isim-l1-b3", type: "multiple_choice", prompt: "Adlıq hal ismin hansı formasıdır?", options: ["ilkin/əsas forma", "cəm forma", "kiçildilmiş forma", "feil forma"], correctIndex: 0, xp: 15 },
            { id: "az4-isim-l1-b4", type: "multiple_choice", prompt: "'kitabda' sözü hansı haldadır?", options: ["yerlik", "yönlük", "çıxışlıq", "təsirlik"], correctIndex: 0, xp: 15 },
            { id: "az4-isim-l1-b5", type: "multiple_choice", prompt: "'Bakıya' sözü hansı haldadır?", options: ["yönlük", "yerlik", "çıxışlıq", "adlıq"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-isim-l2",
          title: "Mənsubiyyət və kəmiyyət",
          intro: "İsim kimə aiddir və neçədir?",
          sections: [
            { heading: "Mənsubiyyət", body: "İsim kimə aid olduğunu bildirir: kitab-ım, kitab-ın, kitab-ı, kitab-ımız, kitab-ınız, kitab-ları." },
            { heading: "Kəmiyyət", body: "Tək: kitab. Cəm: kitablar. Cəm şəkilçisi -lar/-lər həmişə mənsubiyyətdən ƏVVƏL gəlir: kitab-lar-ım." },
          ],
          tasks: [
            { id: "az4-isim-l2-t1", type: "multiple_choice", prompt: "'kitabım' sözü kimə aiddir?", options: ["Mənə", "Sənə", "Ona", "Bizə"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l2-t2", type: "multiple_choice", prompt: "'kitabın' sözü kimə aiddir?", options: ["Sənə", "Mənə", "Ona", "Onlara"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l2-t3", type: "multiple_choice", prompt: "'kitabımız' sözü kimə aiddir?", options: ["Bizə", "Mənə", "Sizə", "Onlara"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l2-t4", type: "multiple_choice", prompt: "'kitablarım' sözündə şəkilçilərin sırası necədir?", options: ["Əvvəl cəm, sonra mənsubiyyət", "Əvvəl mənsubiyyət, sonra cəm", "Fərqi yoxdur", "Şəkilçi yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l2-t5", type: "multiple_choice", prompt: "Hansı söz cəmdə və mənsubiyyətdədir?", options: ["dostlarım", "dostum", "dostlar", "dost"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l2-t6", type: "multiple_choice", prompt: "'evimiz' sözünün kökü hansıdır?", options: ["ev", "evim", "imiz", "evi"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l2-t7", type: "fill_blank", prompt: "'qələm' sözünə 'mənim' mənsubiyyəti əlavə et: ______", accepted: ["qələmim", "Qələmim"], xp: 10 },
            { id: "az4-isim-l2-t8", type: "multiple_choice", prompt: "'onların kitabı' necə yazılır?", options: ["kitabları", "kitabım", "kitabın", "kitabımız"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l2-t9", type: "multiple_choice", prompt: "Mənsubiyyət şəkilçisi nəyi bildirir?", options: ["Sahibliyi", "Zamanı", "Yeri", "Sayı"], correctIndex: 0, xp: 10 },
            { id: "az4-isim-l2-t10", type: "multiple_choice", prompt: "'anam' sözündə mənsubiyyət şəkilçisi hansıdır?", options: ["-m", "ana", "-am", "an"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az4-isim-l2-b1", type: "multiple_choice", prompt: "'sinif yoldaşlarımız' ifadəsində neçə şəkilçi var?", options: ["İki: cəm və mənsubiyyət", "Bir", "Üç", "Heç biri"], correctIndex: 0, xp: 15 },
            { id: "az4-isim-l2-b2", type: "multiple_choice", prompt: "Hansı sırada həm cəm, həm mənsubiyyət var?", options: ["dəftərlərin", "dəftər", "dəftərlər", "dəftərə"], correctIndex: 0, xp: 15 },
            { id: "az4-isim-l2-b3", type: "multiple_choice", prompt: "'Bizim şəhərimiz' ifadəsində mənsubiyyət hansı sözdədir?", options: ["şəhərimiz", "bizim", "hər ikisində", "heç birində"], correctIndex: 0, xp: 15 },
            { id: "az4-isim-l2-b4", type: "multiple_choice", prompt: "İsmin kəmiyyət kateqoriyası nəyi bildirir?", options: ["Tək və ya cəm olduğunu", "Sahibini", "Yerini", "Zamanını"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-isim-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-isim-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Əvəzlik ═══════════════
    {
      id: "az4-evezlik",
      title: "Əvəzlik",
      description: "İsim, sifət və sayın yerində işlənən sözlər: mən, sən, o, bu.",
      lessons: [
        {
          id: "az4-evezlik-l1",
          title: "Əvəzlik",
          intro: "Adların yerində işlənən sözlər.",
          sections: [
            { heading: "Şəxs əvəzlikləri", body: "İnsanları əvəz edir: mən, sən, o, biz, siz, onlar." },
            { heading: "İşarə əvəzlikləri", body: "Əşyaya işarə edir: bu, o, elə, belə." },
          ],
          tasks: [
            { id: "az4-evezlik-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı şəxs əvəzliyidir?", options: ["mən", "kitab", "gözəl", "oxumaq"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı şəxs əvəzliyidir?", options: ["sən", "ev", "böyük", "getmək"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t3", type: "multiple_choice", prompt: "Neçə şəxs əvəzliyi var?", options: ["6 (mən, sən, o, biz, siz, onlar)", "3", "4", "5"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t4", type: "multiple_choice", prompt: "'o' hansı əvəzlikdir?", options: ["şəxs (III tək)", "işarə yalnız", "sual", "sifət"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t5", type: "multiple_choice", prompt: "'biz' neçənci şəxsdir?", options: ["I şəxs cəm", "II şəxs tək", "III şəxs cəm", "I şəxs tək"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t6", type: "multiple_choice", prompt: "'onlar' neçənci şəxsdir?", options: ["III şəxs cəm", "I şəxs cəm", "II şəxs cəm", "III şəxs tək"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı işarə əvəzliyidir?", options: ["bu", "mən", "gözəl", "beş"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t8", type: "multiple_choice", prompt: "Əvəzlik nəyin yerində işlənir?", options: ["ismin, sifətin, sayın", "yalnız feilin", "yalnız zərfin", "heç birinin"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t9", type: "multiple_choice", prompt: "'Mən kitab oxuyuram.' — əvəzlik hansıdır?", options: ["mən", "kitab", "oxuyuram", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t10", type: "multiple_choice", prompt: "'siz' neçənci şəxsdir?", options: ["II şəxs cəm", "I şəxs cəm", "III şəxs cəm", "II şəxs tək"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t11", type: "multiple_choice", prompt: "'Ayşə' əvəzinə hansı əvəzlik işlənə bilər?", options: ["o", "mən", "biz", "siz"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t12", type: "multiple_choice", prompt: "'Uşaqlar' əvəzinə hansı əvəzlik işlənə bilər?", options: ["onlar", "o", "mən", "sən"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t13", type: "multiple_choice", prompt: "Aşağıdakılardan hansı əvəzlik DEYİL?", options: ["kitab", "mən", "o", "bu"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t14", type: "multiple_choice", prompt: "'sən' neçənci şəxsdir?", options: ["II şəxs tək", "I şəxs tək", "III şəxs tək", "II şəxs cəm"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l1-t15", type: "multiple_choice", prompt: "'mən' neçənci şəxsdir?", options: ["I şəxs tək", "II şəxs tək", "III şəxs tək", "I şəxs cəm"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az4-evezlik-l1-b1", type: "multiple_choice", prompt: "'Bu mənim kitabımdır.' — əvəzliklər hansılardır?", options: ["bu, mənim", "kitab", "kitabımdır", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "az4-evezlik-l1-b2", type: "multiple_choice", prompt: "'kim?', 'nə?' hansı əvəzlik növüdür?", options: ["sual əvəzliyi", "şəxs əvəzliyi", "işarə əvəzliyi", "sifət"], correctIndex: 0, xp: 15 },
            { id: "az4-evezlik-l1-b3", type: "multiple_choice", prompt: "'Elçin və Ayşə' əvəzinə hansı əvəzlik işlənər?", options: ["onlar", "o", "biz", "siz"], correctIndex: 0, xp: 15 },
            { id: "az4-evezlik-l1-b4", type: "multiple_choice", prompt: "Əvəzlik cümlədə hansı üzv ola bilər?", options: ["mübtəda (kim? — o gəldi)", "yalnız xəbər", "heç bir", "yalnız təyin"], correctIndex: 0, xp: 15 },
            { id: "az4-evezlik-l1-b5", type: "multiple_choice", prompt: "'sən və mən' əvəzinə hansı əvəzlik işlənər?", options: ["biz", "siz", "onlar", "o"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-evezlik-l2",
          title: "Əvəzliyin növləri",
          intro: "Əvəzlik ismin, sifətin və ya sayın yerində işlənir.",
          sections: [
            { heading: "Şəxs əvəzlikləri", body: "mən, sən, o, biz, siz, onlar — insanı və ya əşyanı əvəz edir." },
            { heading: "Digər növlər", body: "İŞARƏ: bu, o, elə, belə. SUAL: kim, nə, hansı, neçə. QEYRİ-MÜƏYYƏN: bəzi, hər, heç kim." },
          ],
          tasks: [
            { id: "az4-evezlik-l2-t1", type: "multiple_choice", prompt: "'mən' hansı əvəzlikdir?", options: ["Şəxs", "İşarə", "Sual", "Qeyri-müəyyən"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l2-t2", type: "multiple_choice", prompt: "'bu' hansı əvəzlikdir?", options: ["İşarə", "Şəxs", "Sual", "Qeyri-müəyyən"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l2-t3", type: "multiple_choice", prompt: "'kim' hansı əvəzlikdir?", options: ["Sual", "Şəxs", "İşarə", "Qeyri-müəyyən"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l2-t4", type: "multiple_choice", prompt: "'hər kəs' hansı əvəzlikdir?", options: ["Qeyri-müəyyən", "Şəxs", "İşarə", "Sual"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l2-t5", type: "multiple_choice", prompt: "Şəxs əvəzlikləri hansılardır?", options: ["mən, sən, o, biz, siz, onlar", "bu, o, elə", "kim, nə, hansı", "bəzi, hər"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l2-t6", type: "multiple_choice", prompt: "Əvəzlik nəyin yerində işlənir?", options: ["İsim, sifət və sayın", "Yalnız feilin", "Yalnız zərfin", "Heç nəyin"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l2-t7", type: "multiple_choice", prompt: "'Onlar gəldilər.' — 'onlar' hansı əvəzlikdir?", options: ["Şəxs", "İşarə", "Sual", "Qeyri-müəyyən"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l2-t8", type: "fill_blank", prompt: "III şəxs tək şəxs əvəzliyi ______-dur. (bir söz)", accepted: ["o", "O"], xp: 10 },
            { id: "az4-evezlik-l2-t9", type: "multiple_choice", prompt: "'Bu kitab mənimdir.' — burada işarə əvəzliyi hansıdır?", options: ["Bu", "kitab", "mənim", "dir"], correctIndex: 0, xp: 10 },
            { id: "az4-evezlik-l2-t10", type: "multiple_choice", prompt: "'neçə' hansı əvəzlikdir?", options: ["Sual", "Şəxs", "İşarə", "Qeyri-müəyyən"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az4-evezlik-l2-b1", type: "multiple_choice", prompt: "Niyə əvəzlik işlədirik?", options: ["Sözü təkrar etməmək üçün", "Cümləni uzatmaq üçün", "Qrammatika üçün", "Səbəbi yoxdur"], correctIndex: 0, xp: 15 },
            { id: "az4-evezlik-l2-b2", type: "multiple_choice", prompt: "'Aysel gəldi. O, çox şaddır.' — 'o' nəyi əvəz edir?", options: ["Aysel", "gəldi", "şad", "heç nəyi"], correctIndex: 0, xp: 15 },
            { id: "az4-evezlik-l2-b3", type: "multiple_choice", prompt: "Hansı sırada hamısı sual əvəzliyidir?", options: ["kim, nə, hansı", "mən, sən, o", "bu, o, belə", "bəzi, hər, heç"], correctIndex: 0, xp: 15 },
            { id: "az4-evezlik-l2-b4", type: "multiple_choice", prompt: "Şəxs əvəzlikləri neçə şəxsə görə dəyişir?", options: ["Üç: I, II, III", "İki", "Dörd", "Dəyişmir"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-evezlik-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-evezlik-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Zərf ═══════════════
    {
      id: "az4-zerf",
      title: "Zərf",
      description: "İşin tərzini, zamanını, yerini bildirən sözlər.",
      lessons: [
        {
          id: "az4-zerf-l1",
          title: "Zərf",
          intro: "Hərəkətin necə, nə vaxt, harada olduğunu bildirir.",
          sections: [
            { heading: "Zərf", body: "İşin əlamətini bildirir: tərz (necə? — tez, yavaş), zaman (nə vaxt? — dünən, sabah), yer (harada? — irəli, geri)." },
          ],
          tasks: [
            { id: "az4-zerf-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı zərfdir?", options: ["tez", "kitab", "gözəl", "beş"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t2", type: "multiple_choice", prompt: "'dünən' hansı zərf növüdür?", options: ["zaman", "tərz", "yer", "kəmiyyət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t3", type: "multiple_choice", prompt: "'tez' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "kəmiyyət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t4", type: "multiple_choice", prompt: "'irəli' hansı zərf növüdür?", options: ["yer", "zaman", "tərz", "kəmiyyət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t5", type: "multiple_choice", prompt: "Tərz zərfi hansı suala cavab verir?", options: ["necə?", "nə vaxt?", "harada?", "neçə?"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t6", type: "multiple_choice", prompt: "Zaman zərfi hansı suala cavab verir?", options: ["nə vaxt?", "necə?", "harada?", "neçə?"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t7", type: "multiple_choice", prompt: "Yer zərfi hansı suala cavab verir?", options: ["harada?", "necə?", "nə vaxt?", "neçə?"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t8", type: "multiple_choice", prompt: "'Uşaq gözəl oxuyur.' — zərf hansıdır?", options: ["gözəl", "uşaq", "oxuyur", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t9", type: "multiple_choice", prompt: "'sabah' hansı zərf növüdür?", options: ["zaman", "yer", "tərz", "kəmiyyət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t10", type: "multiple_choice", prompt: "'yavaş' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "kəmiyyət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t11", type: "multiple_choice", prompt: "'Dünən gəldim.' — zərf hansıdır?", options: ["dünən", "gəldim", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t12", type: "multiple_choice", prompt: "Zərf əsasən hansı sözü izah edir?", options: ["feili", "ismi", "sayı", "qoşmanı"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t13", type: "multiple_choice", prompt: "'geri' hansı zərf növüdür?", options: ["yer", "zaman", "tərz", "kəmiyyət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t14", type: "multiple_choice", prompt: "'həmişə' hansı zərf növüdür?", options: ["zaman", "yer", "tərz", "kəmiyyət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l1-t15", type: "multiple_choice", prompt: "Aşağıdakılardan hansı zərf DEYİL?", options: ["kitab", "tez", "dünən", "yavaş"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az4-zerf-l1-b1", type: "multiple_choice", prompt: "'Səhər tez durdum.' — neçə zərf var? (səhər/tez)", options: ["2", "1", "3", "0"], correctIndex: 0, xp: 15 },
            { id: "az4-zerf-l1-b2", type: "multiple_choice", prompt: "Zərflə sifətin fərqi nədir?", options: ["zərf feili, sifət ismi izah edir", "heç fərq yox", "zərf ismi izah edir", "sifət feili izah edir"], correctIndex: 0, xp: 15 },
            { id: "az4-zerf-l1-b3", type: "multiple_choice", prompt: "'çox' hansı zərf növüdür?", options: ["kəmiyyət", "yer", "zaman", "tərz"], correctIndex: 0, xp: 15 },
            { id: "az4-zerf-l1-b4", type: "multiple_choice", prompt: "'Uşaqlar bağçada oynayır.' — zərf hansıdır?", options: ["bağçada", "uşaqlar", "oynayır", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "az4-zerf-l1-b5", type: "multiple_choice", prompt: "'birlikdə' hansı zərf növüdür?", options: ["tərz", "zaman", "yer", "kəmiyyət"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-zerf-l2",
          title: "Zərfin növləri",
          intro: "Zərf hərəkətin necə, nə vaxt və harada olduğunu bildirir.",
          sections: [
            { heading: "Növlər", body: "TƏRZİ-HƏRƏKƏT: necə? (tez, yavaş, gözəl). ZAMAN: nə vaxt? (dünən, sabah, indi). YER: harada? (burada, orada, irəli). MİQDAR: nə qədər? (çox, az)." },
            { heading: "Fərq", body: "Sifət İSMİ, zərf isə FEİLİ izah edir: 'gözəl mahnı' (sifət) — 'gözəl oxuyur' (zərf)." },
          ],
          tasks: [
            { id: "az4-zerf-l2-t1", type: "multiple_choice", prompt: "'tez qaçdı' — 'tez' hansı zərfdir?", options: ["Tərzi-hərəkət", "Zaman", "Yer", "Miqdar"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l2-t2", type: "multiple_choice", prompt: "'dünən gəldi' — 'dünən' hansı zərfdir?", options: ["Zaman", "Yer", "Tərzi-hərəkət", "Miqdar"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l2-t3", type: "multiple_choice", prompt: "'burada dayandı' — 'burada' hansı zərfdir?", options: ["Yer", "Zaman", "Miqdar", "Tərzi-hərəkət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l2-t4", type: "multiple_choice", prompt: "'çox oxudu' — 'çox' hansı zərfdir?", options: ["Miqdar", "Zaman", "Yer", "Tərzi-hərəkət"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l2-t5", type: "multiple_choice", prompt: "Zərf nəyi izah edir?", options: ["Feili", "İsmi", "Sayı", "Bağlayıcını"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l2-t6", type: "multiple_choice", prompt: "'gözəl mahnı' ifadəsində 'gözəl' nədir?", options: ["Sifət", "Zərf", "Feil", "İsim"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l2-t7", type: "multiple_choice", prompt: "'gözəl oxuyur' ifadəsində 'gözəl' nədir?", options: ["Zərf", "Sifət", "İsim", "Say"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l2-t8", type: "fill_blank", prompt: "Zaman zərfi ______ sualına cavab verir. (məs. nə vaxt)", accepted: ["nə vaxt", "Nə vaxt", "nevaxt"], xp: 10 },
            { id: "az4-zerf-l2-t9", type: "multiple_choice", prompt: "Hansı söz YER zərfidir?", options: ["irəli", "yavaş", "sabah", "az"], correctIndex: 0, xp: 10 },
            { id: "az4-zerf-l2-t10", type: "multiple_choice", prompt: "Hansı söz ZAMAN zərfidir?", options: ["indi", "orada", "tez", "çox"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az4-zerf-l2-b1", type: "multiple_choice", prompt: "'Sürətlə qaçdı' ifadəsində zərf hansıdır?", options: ["Sürətlə", "qaçdı", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "az4-zerf-l2-b2", type: "multiple_choice", prompt: "Eyni söz həm sifət, həm zərf ola bilərmi?", options: ["Bəli, cümlədəki roluna görə", "Xeyr", "Yalnız şeirdə", "Yalnız yazıda"], correctIndex: 0, xp: 15 },
            { id: "az4-zerf-l2-b3", type: "multiple_choice", prompt: "'Az danışdı, çox işlədi' cümləsində neçə zərf var?", options: ["2", "1", "3", "0"], correctIndex: 0, xp: 15 },
            { id: "az4-zerf-l2-b4", type: "multiple_choice", prompt: "Zərflər dəyişirmi (hallanır, cəmlənir)?", options: ["Xeyr, dəyişməzdir", "Bəli, hallanır", "Bəli, cəmlənir", "Yalnız cəmlənir"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-zerf-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-zerf-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Cümlə üzvləri ═══════════════
    {
      id: "az4-uzvler",
      title: "Cümlə üzvləri",
      description: "Baş üzvlər (mübtəda, xəbər) və ikinci dərəcəli üzvlər.",
      lessons: [
        {
          id: "az4-uzvler-l1",
          title: "Cümlə üzvləri",
          intro: "Cümlədə hər sözün vəzifəsi var.",
          sections: [
            { heading: "Baş üzvlər", body: "Mübtəda — iş görəni bildirir (kim? nə?). Xəbər — işi bildirir (nə edir?). 'Uşaq oxuyur.' — uşaq (mübtəda), oxuyur (xəbər)." },
            { heading: "İkinci dərəcəli üzvlər", body: "Tamamlıq (nəyi? kimə?), təyin (necə? hansı?), zərflik (harada? nə vaxt?) baş üzvləri izah edir." },
          ],
          tasks: [
            { id: "az4-uzvler-l1-t1", type: "multiple_choice", prompt: "İş görəni bildirən üzv necə adlanır?", options: ["mübtəda", "xəbər", "təyin", "tamamlıq"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t2", type: "multiple_choice", prompt: "İşi bildirən üzv necə adlanır?", options: ["xəbər", "mübtəda", "təyin", "zərflik"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t3", type: "multiple_choice", prompt: "'Uşaq oxuyur.' — mübtəda hansıdır?", options: ["uşaq", "oxuyur", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t4", type: "multiple_choice", prompt: "'Uşaq oxuyur.' — xəbər hansıdır?", options: ["oxuyur", "uşaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t5", type: "multiple_choice", prompt: "Baş üzvlər hansılardır?", options: ["mübtəda və xəbər", "təyin və tamamlıq", "zərflik", "hamısı"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t6", type: "multiple_choice", prompt: "'Gözəl gül açdı.' — təyin hansıdır?", options: ["gözəl", "gül", "açdı", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t7", type: "multiple_choice", prompt: "'Kitabı oxudum.' — tamamlıq hansıdır?", options: ["kitabı", "oxudum", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t8", type: "multiple_choice", prompt: "'Səhər durdum.' — zərflik hansıdır?", options: ["səhər", "durdum", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t9", type: "multiple_choice", prompt: "'Quşlar uçur.' — mübtəda hansıdır?", options: ["quşlar", "uçur", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t10", type: "multiple_choice", prompt: "Təyin hansı suala cavab verir?", options: ["necə? hansı?", "nə edir?", "kim?", "harada?"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t11", type: "multiple_choice", prompt: "Tamamlıq hansı suala cavab verir?", options: ["nəyi? kimə?", "necə?", "harada?", "nə vaxt?"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t12", type: "multiple_choice", prompt: "'Bahar gəldi.' — xəbər hansıdır?", options: ["gəldi", "bahar", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t13", type: "multiple_choice", prompt: "İkinci dərəcəli üzvlər hansılardır?", options: ["tamamlıq, təyin, zərflik", "mübtəda, xəbər", "isim, feil", "qoşma, bağlayıcı"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t14", type: "multiple_choice", prompt: "'Mən kitab oxuyuram.' — mübtəda hansıdır?", options: ["mən", "kitab", "oxuyuram", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l1-t15", type: "multiple_choice", prompt: "'Balaca uşaq şən oynayır.' — xəbər hansıdır?", options: ["oynayır", "balaca", "uşaq", "şən"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az4-uzvler-l1-b1", type: "multiple_choice", prompt: "'Balaca uşaq şən oynayır.' — təyin hansıdır?", options: ["balaca", "uşaq", "şən", "oynayır"], correctIndex: 0, xp: 15 },
            { id: "az4-uzvler-l1-b2", type: "multiple_choice", prompt: "'Balaca uşaq şən oynayır.' — zərflik hansıdır?", options: ["şən", "balaca", "uşaq", "oynayır"], correctIndex: 0, xp: 15 },
            { id: "az4-uzvler-l1-b3", type: "multiple_choice", prompt: "Cümlədə mütləq olan üzv hansıdır?", options: ["xəbər", "təyin", "tamamlıq", "zərflik"], correctIndex: 0, xp: 15 },
            { id: "az4-uzvler-l1-b4", type: "multiple_choice", prompt: "'Dostuma məktub yazdım.' — tamamlıq hansıdır (nəyi?)?", options: ["məktub", "dostuma", "yazdım", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "az4-uzvler-l1-b5", type: "multiple_choice", prompt: "Cümləni üzvlərinə görə təhlil etmək necə adlanır?", options: ["sintaktik təhlil", "fonetik təhlil", "leksik təhlil", "heç biri"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-uzvler-l2",
          title: "İkinci dərəcəli üzvlər",
          intro: "Mübtəda və xəbərdən başqa üzvlər.",
          sections: [
            { heading: "Tamamlıq", body: "Feilin təsir etdiyi əşyanı bildirir, 'nəyi? kimi?' suallarına cavab verir: 'Kitabı oxudum' — kitabı tamamlıqdır." },
            { heading: "Təyin və zərflik", body: "TƏYİN ismi izah edir ('gözəl gül'). ZƏRFLİK hərəkətin yerini/zamanını bildirir ('səhər gəldi')." },
          ],
          tasks: [
            { id: "az4-uzvler-l2-t1", type: "multiple_choice", prompt: "'Kitabı oxudum' cümləsində tamamlıq hansıdır?", options: ["Kitabı", "oxudum", "mən", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l2-t2", type: "multiple_choice", prompt: "Tamamlıq hansı suala cavab verir?", options: ["Nəyi? Kimi?", "Kim? Nə?", "Necə?", "Nə vaxt?"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l2-t3", type: "multiple_choice", prompt: "'Gözəl gül açdı' cümləsində təyin hansıdır?", options: ["Gözəl", "gül", "açdı", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l2-t4", type: "multiple_choice", prompt: "'Səhər məktəbə getdim' cümləsində zərflik hansıdır?", options: ["Səhər", "məktəbə", "getdim", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l2-t5", type: "multiple_choice", prompt: "Təyin nəyi izah edir?", options: ["İsmi", "Feili", "Sayı", "Bağlayıcını"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l2-t6", type: "multiple_choice", prompt: "Cümlənin baş üzvləri hansılardır?", options: ["Mübtəda və xəbər", "Tamamlıq və təyin", "Zərflik və təyin", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l2-t7", type: "multiple_choice", prompt: "'Aysel məktubu yazdı' cümləsində mübtəda hansıdır?", options: ["Aysel", "məktubu", "yazdı", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l2-t8", type: "fill_blank", prompt: "Cümlədə iş görəni bildirən üzv ______ adlanır. (bir söz)", accepted: ["mübtəda", "Mübtəda"], xp: 10 },
            { id: "az4-uzvler-l2-t9", type: "multiple_choice", prompt: "'Uşaqlar həyətdə oynayır' cümləsində zərflik hansıdır?", options: ["həyətdə", "Uşaqlar", "oynayır", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az4-uzvler-l2-t10", type: "multiple_choice", prompt: "Xəbər hansı suala cavab verir?", options: ["Nə edir? Nədir?", "Kim?", "Necə?", "Harada?"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az4-uzvler-l2-b1", type: "multiple_choice", prompt: "'Kiçik qardaşım dünən yeni kitab aldı' cümləsində neçə ikinci dərəcəli üzv var?", options: ["Üç: kiçik, dünən, yeni kitab", "Bir", "İki", "Heç biri"], correctIndex: 0, xp: 15 },
            { id: "az4-uzvler-l2-b2", type: "multiple_choice", prompt: "Cümlə ən azı hansı üzvlərdən ibarət olmalıdır?", options: ["Mübtəda və xəbər", "Yalnız xəbər", "Tamamlıq və təyin", "Zərflik"], correctIndex: 0, xp: 15 },
            { id: "az4-uzvler-l2-b3", type: "multiple_choice", prompt: "'Anam mənə hədiyyə verdi' cümləsində tamamlıq hansıdır?", options: ["hədiyyə", "Anam", "verdi", "mənə hədiyyə verdi"], correctIndex: 0, xp: 15 },
            { id: "az4-uzvler-l2-b4", type: "multiple_choice", prompt: "İkinci dərəcəli üzvlər cümlədə nə edir?", options: ["Baş üzvləri izah edir", "Cümləni bitirir", "Sual verir", "Heç nə"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-uzvler-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-uzvler-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Söz yaradıcılığı və orfoqrafiya ═══════════════
    {
      id: "az4-soz",
      title: "Söz yaradıcılığı və orfoqrafiya",
      description: "Düzəltmə sözlər, kök və şəkilçi, düzgün yazılış.",
      lessons: [
        {
          id: "az4-soz-l1",
          title: "Düzəltmə sözlər və orfoqrafiya",
          intro: "Şəkilçilərlə yeni sözlər düzəltmək.",
          sections: [
            { heading: "Düzəltmə söz", body: "Kökə sözdüzəldici şəkilçi əlavə edərək yeni söz düzəldirik: iş → işçi, su → sulu, kitab → kitabça." },
            { heading: "Orfoqrafiya", body: "Cümlə böyük hərflə başlayır, nöqtə ilə bitir. Xüsusi isimlər böyük hərflə yazılır." },
          ],
          tasks: [
            { id: "az4-soz-l1-t1", type: "multiple_choice", prompt: "'iş' sözündən hansı düzəltmə söz yaranır?", options: ["işçi", "kitab", "gözəl", "tez"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t2", type: "multiple_choice", prompt: "'su' sözündən hansı düzəltmə söz yaranır?", options: ["sulu", "kitab", "ev", "dağ"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t3", type: "multiple_choice", prompt: "'işçi' sözünün kökü hansıdır?", options: ["iş", "çi", "işç", "i"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t4", type: "multiple_choice", prompt: "'duzlu' sözünün kökü hansıdır?", options: ["duz", "lu", "duzl", "u"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t5", type: "multiple_choice", prompt: "'-çı/-çi' şəkilçisi nə düzəldir?", options: ["peşə/məşğuliyyət bildirən söz", "cəm", "hal", "feil"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t6", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t7", type: "multiple_choice", prompt: "Nəqli cümlə hansı işarə ilə bitir?", options: ["nöqtə", "sual işarəsi", "nida işarəsi", "vergül"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t8", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Bakı", "bakı", "BAKı", "baKı"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t9", type: "multiple_choice", prompt: "'kitabça' sözünün kökü hansıdır?", options: ["kitab", "ça", "kitabç", "a"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t10", type: "multiple_choice", prompt: "'meşəçi' sözü hansı sözdən düzəlib?", options: ["meşə", "çi", "meşəç", "iş"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t11", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Nərmin məktəbə getdi.", "nərmin məktəbə getdi.", "Nərmin Məktəbə getdi.", "nərmin Məktəbə Getdi."], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t12", type: "multiple_choice", prompt: "'daşlı' sözünün kökü hansıdır?", options: ["daş", "lı", "daşl", "ı"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t13", type: "multiple_choice", prompt: "Xüsusi isimlər (ad, şəhər) necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t14", type: "multiple_choice", prompt: "'balıqçı' sözü hansı sözdən düzəlib?", options: ["balıq", "çı", "balıqç", "iş"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l1-t15", type: "multiple_choice", prompt: "Sual cümləsi hansı işarə ilə bitir?", options: ["sual işarəsi (?)", "nöqtə", "nida işarəsi", "vergül"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az4-soz-l1-b1", type: "multiple_choice", prompt: "'-lı/-li/-lu/-lü' şəkilçisi nə bildirir?", options: ["nəyəsə malik olmaq (sulu, daşlı)", "peşə", "cəm", "hal"], correctIndex: 0, xp: 15 },
            { id: "az4-soz-l1-b2", type: "multiple_choice", prompt: "'gözlük' sözü hansı sözdən düzəlib?", options: ["göz", "lük", "gözl", "ük"], correctIndex: 0, xp: 15 },
            { id: "az4-soz-l1-b3", type: "multiple_choice", prompt: "Ay, çay, dağ adları necə yazılır?", options: ["böyük hərflə (xüsusi isim)", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 15 },
            { id: "az4-soz-l1-b4", type: "multiple_choice", prompt: "Nida cümləsi hansı işarə ilə bitir?", options: ["nida işarəsi (!)", "nöqtə", "sual", "vergül"], correctIndex: 0, xp: 15 },
            { id: "az4-soz-l1-b5", type: "multiple_choice", prompt: "'yağışlı' sözünün kökü hansıdır?", options: ["yağış", "lı", "yağışl", "ı"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-soz-l2",
          title: "Böyük hərf və durğu işarələri",
          intro: "Yazıda əsas orfoqrafiya qaydaları.",
          sections: [
            { heading: "Böyük hərf", body: "Cümlənin əvvəlində, insan/şəhər/ölkə adlarında, kitab və qəzet adlarında böyük hərf yazılır." },
            { heading: "Vergül", body: "Sadalanan sözlər arasında vergül qoyulur: 'Çantada kitab, dəftər, qələm var.'" },
          ],
          tasks: [
            { id: "az4-soz-l2-t1", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["Böyük", "Kiçik", "Fərqi yoxdur", "Rəqəmlə"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l2-t2", type: "multiple_choice", prompt: "Hansı cümlə düzgün yazılıb?", options: ["Mən Bakıda yaşayıram.", "mən bakıda yaşayıram.", "Mən bakıda yaşayıram.", "mən Bakıda yaşayıram."], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l2-t3", type: "multiple_choice", prompt: "Sadalanan sözlər arasında hansı işarə qoyulur?", options: ["Vergül", "Nöqtə", "Sual işarəsi", "Heç bir"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l2-t4", type: "multiple_choice", prompt: "'Çantada kitab dəftər qələm var' — nə çatışmır?", options: ["Vergüllər", "Nöqtə", "Böyük hərf", "Heç nə"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l2-t5", type: "multiple_choice", prompt: "Ölkə adları necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Dırnaqda", "Fərqi yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l2-t6", type: "multiple_choice", prompt: "Kitab adları necə yazılır?", options: ["Böyük hərf və dırnaqda", "Kiçik hərflə", "Yalnız böyük hərflə", "Mötərizədə"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l2-t7", type: "multiple_choice", prompt: "Nəqli cümlənin sonunda hansı işarə qoyulur?", options: [".", "?", "!", ","], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l2-t8", type: "multiple_choice", prompt: "Müraciət sözündən sonra hansı işarə qoyulur?", options: ["Vergül", "Nöqtə", "Defis", "Heç bir"], correctIndex: 0, xp: 10 },
            { id: "az4-soz-l2-t9", type: "fill_blank", prompt: "Cümlənin sonunda ______ qoyulur (nəqli cümlədə, işarəni yaz).", accepted: [".", "nöqtə", "Nöqtə"], xp: 10 },
            { id: "az4-soz-l2-t10", type: "multiple_choice", prompt: "'aysel və nihad gəldilər.' — burada neçə səhv var?", options: ["İki böyük hərf səhvi", "Bir", "Üç", "Səhv yoxdur"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az4-soz-l2-b1", type: "multiple_choice", prompt: "Hansı cümlə tam düzgündür?", options: ["Bakı, Gəncə və Şəki gözəl şəhərlərdir.", "bakı, gəncə və şəki gözəl şəhərlərdir.", "Bakı Gəncə və Şəki gözəl şəhərlərdir", "Bakı, gəncə və Şəki gözəl şəhərlərdir."], correctIndex: 0, xp: 15 },
            { id: "az4-soz-l2-b2", type: "multiple_choice", prompt: "Dialoqda replikanın əvvəlində hansı işarə qoyulur?", options: ["Tire (—)", "Vergül", "Nöqtə", "Sual işarəsi"], correctIndex: 0, xp: 15 },
            { id: "az4-soz-l2-b3", type: "multiple_choice", prompt: "'Salam, Aysel!' cümləsində vergül niyə qoyulub?", options: ["Müraciəti ayırmaq üçün", "Sadalama üçün", "Səhvdir", "Uzun olduğu üçün"], correctIndex: 0, xp: 15 },
            { id: "az4-soz-l2-b4", type: "multiple_choice", prompt: "Bayram adları (məs. Novruz) necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Dırnaqda", "Fərqi yoxdur"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-soz-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-soz-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Mətn və nitq ═══════════════
    {
      id: "az4-metn",
      title: "Mətn və nitq",
      description: "Mətn, başlıq, abzas və nitq mədəniyyəti.",
      lessons: [
        {
          id: "az4-metn-l1",
          title: "Mətn və nitq mədəniyyəti",
          intro: "Mətn cümlələrdən ibarətdir; nəzakətli danışıq.",
          sections: [
            { heading: "Mətn", body: "Bir-biri ilə bağlı cümlələrin toplusu mətndir. Mətnin başlığı və abzasları olur. Başlıq mətnin adıdır." },
            { heading: "Nitq mədəniyyəti", body: "Nəzakətli sözlər: sağ ol, zəhmət olmasa, buyurun, üzr istəyirəm. Böyüklərlə 'Siz' deyə danışmaq nəzakətlidir." },
          ],
          tasks: [
            { id: "az4-metn-l1-t1", type: "multiple_choice", prompt: "Mətn nədən ibarətdir?", options: ["bağlı cümlələrdən", "yalnız sözlərdən", "hərflərdən", "hecalardan"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t2", type: "multiple_choice", prompt: "Mətnin adı necə adlanır?", options: ["başlıq", "abzas", "cümlə", "söz"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t3", type: "multiple_choice", prompt: "Mətnin hissələri (paraqrafları) necə adlanır?", options: ["abzas", "başlıq", "cümlə", "heca"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t4", type: "multiple_choice", prompt: "Kimsə sənə kömək etdi. Nə deyərsən?", options: ["Sağ olun / təşəkkür", "Get", "Yox", "Dur"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t5", type: "multiple_choice", prompt: "Nəsə xahiş edəndə hansı nəzakət sözünü deyirik?", options: ["zəhmət olmasa", "yox", "get", "dur"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t6", type: "multiple_choice", prompt: "Böyüklərlə necə danışmaq nəzakətlidir?", options: ["'Siz' deyə", "'sən' deyə qışqıraraq", "gülərək", "susaraq"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t7", type: "multiple_choice", prompt: "Səhvə görə nə deyirik?", options: ["üzr istəyirəm", "sağ ol", "buyurun", "salam"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t8", type: "multiple_choice", prompt: "Mətndə cümlələr necə olmalıdır?", options: ["bir-biri ilə bağlı", "təsadüfi", "bağsız", "eyni"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t9", type: "multiple_choice", prompt: "Başlıq mətnin nəyini bildirir?", options: ["mövzusunu/adını", "sonunu", "səhvini", "uzunluğunu"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t10", type: "multiple_choice", prompt: "Kiməsə nəyisə verəndə nə deyirik?", options: ["buyurun", "yox", "get", "dur"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t11", type: "multiple_choice", prompt: "Görüşəndə nə deyirik?", options: ["salam", "əlvida", "yox", "get"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t12", type: "multiple_choice", prompt: "Ayrılanda nə deyirik?", options: ["sağ ol / əlvida", "salam", "buyurun", "üzr istəyirəm"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t13", type: "multiple_choice", prompt: "Mətn neçə cümlədən ibarət ola bilər?", options: ["bir neçə (çox)", "yalnız bir", "yalnız iki", "heç"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t14", type: "multiple_choice", prompt: "Nəzakətli danışıq nədir?", options: ["hörmətlə, nəzakət sözləri ilə", "qışqıraraq", "kobud", "susaraq"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l1-t15", type: "multiple_choice", prompt: "Aşağıdakılardan hansı nəzakət sözüdür?", options: ["təşəkkür edirəm", "get", "sus", "yox"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az4-metn-l1-b1", type: "multiple_choice", prompt: "Mətnin əvvəlində nə olur?", options: ["başlıq", "nöqtə", "abzas boşluğu yalnız", "imza"], correctIndex: 0, xp: 15 },
            { id: "az4-metn-l1-b2", type: "multiple_choice", prompt: "Yeni fikrə keçəndə mətndə nə edirik?", options: ["yeni abzasa başlayırıq", "böyük hərf yazmırıq", "nöqtə qoymuruq", "heç nə"], correctIndex: 0, xp: 15 },
            { id: "az4-metn-l1-b3", type: "multiple_choice", prompt: "Telefonda danışanda əvvəlcə nə deyirik?", options: ["salam / alo", "get", "yox", "dur"], correctIndex: 0, xp: 15 },
            { id: "az4-metn-l1-b4", type: "multiple_choice", prompt: "Mətnin növləri hansılardır (ümumi)?", options: ["nağıl, hekayə, şeir və s.", "yalnız şeir", "yalnız cümlə", "yalnız söz"], correctIndex: 0, xp: 15 },
            { id: "az4-metn-l1-b5", type: "multiple_choice", prompt: "Müəllimə müraciət edəndə necə danışırıq?", options: ["nəzakətlə, 'Siz' deyə", "kobud", "qışqıraraq", "susaraq"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-metn-l2",
          title: "Mətnin hissələri və planı",
          intro: "Hər mətnin başlanğıcı, əsas hissəsi və sonu var.",
          sections: [
            { heading: "Üç hissə", body: "GİRİŞ mövzunu açır, ƏSAS HİSSƏ hadisəni danışır, NƏTİCƏ yekun fikri verir." },
            { heading: "Plan", body: "Mətni yazmadan əvvəl plan qurmaq faydalıdır: hər hissəyə bir cümlə ilə ad ver." },
          ],
          tasks: [
            { id: "az4-metn-l2-t1", type: "multiple_choice", prompt: "Mətn neçə əsas hissədən ibarətdir?", options: ["Üç", "İki", "Dörd", "Bir"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l2-t2", type: "multiple_choice", prompt: "Mətnin birinci hissəsi necə adlanır?", options: ["Giriş", "Nəticə", "Əsas hissə", "Başlıq"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l2-t3", type: "multiple_choice", prompt: "Mətnin son hissəsi necə adlanır?", options: ["Nəticə", "Giriş", "Əsas hissə", "Plan"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l2-t4", type: "multiple_choice", prompt: "Başlıq nə üçündür?", options: ["Mətnin mövzusunu bildirmək üçün", "Yer doldurmaq üçün", "Uzunluq üçün", "Səbəbi yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l2-t5", type: "multiple_choice", prompt: "Plan nə vaxt qurulur?", options: ["Yazmadan əvvəl", "Yazandan sonra", "Heç vaxt", "Yazı zamanı"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l2-t6", type: "multiple_choice", prompt: "Abzas nədir?", options: ["Mətnin yeni sətirdən başlayan hissəsi", "Bir cümlə", "Bir söz", "Durğu işarəsi"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l2-t7", type: "multiple_choice", prompt: "Mətn nədir?", options: ["Mənaca bağlı cümlələr", "Bir cümlə", "Bir söz", "Sözlər siyahısı"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l2-t8", type: "fill_blank", prompt: "Mətnin ilk hissəsi ______ adlanır. (bir söz)", accepted: ["giriş", "Giriş"], xp: 10 },
            { id: "az4-metn-l2-t9", type: "multiple_choice", prompt: "Nəqli mətn nəyi danışır?", options: ["Hadisəni", "Əşyanın görünüşünü", "Fikri sübut edir", "Heç nəyi"], correctIndex: 0, xp: 10 },
            { id: "az4-metn-l2-t10", type: "multiple_choice", prompt: "Təsviri mətn nəyi göstərir?", options: ["Əşyanın və ya təbiətin görünüşünü", "Hadisəni", "Sübutu", "Sualı"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az4-metn-l2-b1", type: "multiple_choice", prompt: "Yaxşı başlıq necə olmalıdır?", options: ["Qısa və mövzunu əks etdirən", "Uzun və çətin", "Mətnin surəti", "Sual olmalı"], correctIndex: 0, xp: 15 },
            { id: "az4-metn-l2-b2", type: "multiple_choice", prompt: "Mühakimə mətni nə edir?", options: ["Fikri əsaslandırır", "Hadisə danışır", "Görünüşü təsvir edir", "Sual verir"], correctIndex: 0, xp: 15 },
            { id: "az4-metn-l2-b3", type: "multiple_choice", prompt: "Mətnin əsas fikri harada olur?", options: ["Adətən nəticədə və ya başlıqda", "Yalnız birinci sözdə", "Yalnız sonuncu sözdə", "Heç yerdə"], correctIndex: 0, xp: 15 },
            { id: "az4-metn-l2-b4", type: "multiple_choice", prompt: "Niyə abzaslara bölürük?", options: ["Oxunuşu asanlaşdırmaq üçün", "Yer doldurmaq üçün", "Qayda tələb edir deyə", "Səbəbi yoxdur"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az4-metn-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az4-metn-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
