// Azərbaycan dili — 3-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Nitq səsləri və heca  2) Sözün quruluşu (kök və şəkilçi)  3) İsim
// 4) Sifət və say  5) Feil  6) Cümlə və mətn.
// 3-cü sinif üçün sadə. id prefiksi az3-*.

import type { Subject } from "../types";

export const azerbaijani3: Subject = {
  slug: "azerbaycan-dili-3",
  name: "Azərbaycan dili",
  grade: 3,
  icon: "A",
  color: "rose",
  units: [
    // ═══════════════ 1. Nitq səsləri və heca ═══════════════
    {
      id: "az3-fonetika",
      title: "Nitq səsləri və heca",
      description: "Sait və samitlərin təkrarı, heca və vurğu.",
      lessons: [
        {
          id: "az3-fonetika-l1",
          title: "Səslər, heca və vurğu",
          intro: "Saitlər, samitlər, heca bölgüsü və vurğu.",
          sections: [
            { heading: "Səslər", body: "9 sait (a, e, ə, ı, i, o, ö, u, ü) və 23 samit var. Cəmi 32 hərf." },
            { heading: "Heca və vurğu", body: "Sözdə neçə sait varsa, o qədər heca var. Vurğu sözün bir hecasının daha güclü deyilməsidir. Azərbaycan dilində vurğu adətən son hecaya düşür: kitáb, aná." },
          ],
          tasks: [
            { id: "az3-fonetika-l1-t1", type: "numeric", prompt: "Azərbaycan dilində neçə sait var?", answer: 9, xp: 10 },
            { id: "az3-fonetika-l1-t2", type: "numeric", prompt: "Azərbaycan dilində neçə samit var?", answer: 23, xp: 10 },
            { id: "az3-fonetika-l1-t3", type: "numeric", prompt: "'kitab' sözündə neçə heca var? (ki-tab)", answer: 2, xp: 10 },
            { id: "az3-fonetika-l1-t4", type: "numeric", prompt: "'məktəb' sözündə neçə heca var? (mək-təb)", answer: 2, xp: 10 },
            { id: "az3-fonetika-l1-t5", type: "numeric", prompt: "'kitabxana' sözündə neçə heca var? (ki-tab-xa-na)", answer: 4, xp: 10 },
            { id: "az3-fonetika-l1-t6", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saitdir?", options: ["ə", "k", "s", "t"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı samitdir?", options: ["m", "a", "o", "ü"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l1-t8", type: "multiple_choice", prompt: "Sözdə heca sayını nə göstərir?", options: ["saitlərin sayı", "samitlərin sayı", "hərflərin sayı", "vurğu"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l1-t9", type: "multiple_choice", prompt: "Azərbaycan dilində vurğu adətən hansı hecaya düşür?", options: ["son hecaya", "birinci hecaya", "orta hecaya", "vurğu yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l1-t10", type: "numeric", prompt: "'alma' sözündə neçə heca var?", answer: 2, xp: 10 },
            { id: "az3-fonetika-l1-t11", type: "multiple_choice", prompt: "'a' saiti qalın, yoxsa incədir?", options: ["qalın", "incə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l1-t12", type: "multiple_choice", prompt: "'e' saiti qalın, yoxsa incədir?", options: ["incə", "qalın", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l1-t13", type: "numeric", prompt: "'su' sözündə neçə heca var?", answer: 1, xp: 10 },
            { id: "az3-fonetika-l1-t14", type: "numeric", prompt: "'balaca' sözündə neçə heca var? (ba-la-ca)", answer: 3, xp: 10 },
            { id: "az3-fonetika-l1-t15", type: "numeric", prompt: "Cəmi neçə hərf var? (9 + 23)", answer: 32, xp: 15 },
          ],
          bonusTasks: [
            { id: "az3-fonetika-l1-b1", type: "numeric", prompt: "'ayaqqabı' sözündə neçə heca var? (a-yaq-qa-bı)", answer: 4, xp: 15 },
            { id: "az3-fonetika-l1-b2", type: "multiple_choice", prompt: "Hansı sırada yalnız qalın saitlər var?", options: ["a, ı, o, u", "e, ə, i, ö", "a, e, i, o", "u, ü, ö, ı"], correctIndex: 0, xp: 15 },
            { id: "az3-fonetika-l1-b3", type: "numeric", prompt: "'təbiət' sözündə neçə heca var? (tə-bi-ət)", answer: 3, xp: 15 },
            { id: "az3-fonetika-l1-b4", type: "multiple_choice", prompt: "Hansı sırada yalnız incə saitlər var?", options: ["e, ə, i, ö, ü", "a, ı, o, u", "a, e, o, u", "i, o, u, a"], correctIndex: 0, xp: 15 },
            { id: "az3-fonetika-l1-b5", type: "numeric", prompt: "'gül' sözündə neçə heca var?", answer: 1, xp: 15 },
          ],
        },
        {
          id: "az3-fonetika-l2",
          title: "Sait ahəngi",
          intro: "Azərbaycan dilində saitlər bir-birinə uyğunlaşır.",
          sections: [
            { heading: "Qalın və incə", body: "Qalın saitlər: a, ı, o, u. İncə saitlər: e, ə, i, ö, ü. Bir sözdə adətən ya hamısı qalın, ya hamısı incə olur." },
            { heading: "Şəkilçi seçimi", body: "Söz qalın saitlə bitirsə şəkilçi də qalın olur: kitab-lar. İncə olsa incə: ev-lər." },
          ],
          tasks: [
            { id: "az3-fonetika-l2-t1", type: "multiple_choice", prompt: "Hansı sait QALINDIR?", options: ["a", "e", "i", "ə"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l2-t2", type: "multiple_choice", prompt: "Hansı sait İNCƏDİR?", options: ["ü", "ı", "o", "u"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l2-t3", type: "multiple_choice", prompt: "'kitab' sözündəki saitlər necədir?", options: ["Qalın", "İncə", "Qarışıq", "Sait yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l2-t4", type: "multiple_choice", prompt: "'ev' sözündəki sait necədir?", options: ["İncə", "Qalın", "Qarışıq", "Sait yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l2-t5", type: "multiple_choice", prompt: "Qalın saitlə bitən sözə hansı şəkilçi qoşulur?", options: ["-lar", "-lər", "İkisi də", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l2-t6", type: "multiple_choice", prompt: "'gül' sözünə hansı cəm şəkilçisi uyğundur?", options: ["-lər", "-lar", "-lir", "-lur"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l2-t7", type: "multiple_choice", prompt: "Azərbaycan dilində neçə sait var?", options: ["9", "6", "5", "12"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l2-t8", type: "fill_blank", prompt: "Qalın saitlər: a, ı, o, ______ . (bir hərf)", accepted: ["u", "U"], xp: 10 },
            { id: "az3-fonetika-l2-t9", type: "multiple_choice", prompt: "'uşaq' sözündəki saitlər necədir?", options: ["Qalın", "İncə", "Qarışıq", "Sait yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az3-fonetika-l2-t10", type: "multiple_choice", prompt: "Sait ahəngi nə deməkdir?", options: ["Saitlərin bir-birinə uyğunlaşması", "Sözün uzunluğu", "Hecaların sayı", "Samitlərin sırası"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az3-fonetika-l2-b1", type: "multiple_choice", prompt: "Hansı söz sait ahənginə uyğun DEYİL?", options: ["kitabler", "kitablar", "evlər", "güllər"], correctIndex: 0, xp: 15 },
            { id: "az3-fonetika-l2-b2", type: "multiple_choice", prompt: "'məktəb' sözünə hansı şəkilçi uyğundur?", options: ["-lər", "-lar", "-luq", "-lıq"], correctIndex: 0, xp: 15 },
            { id: "az3-fonetika-l2-b3", type: "multiple_choice", prompt: "İncə saitlər hansılardır?", options: ["e, ə, i, ö, ü", "a, ı, o, u", "a, e, i", "o, ö, u, ü"], correctIndex: 0, xp: 15 },
            { id: "az3-fonetika-l2-b4", type: "multiple_choice", prompt: "Alınma sözlərdə sait ahəngi həmişə gözlənilirmi?", options: ["Xeyr, pozula bilər", "Bəli, həmişə", "Yalnız uzun sözlərdə", "Bilmək olmur"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-fonetika-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-fonetika-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Sözün quruluşu ═══════════════
    {
      id: "az3-qurulus",
      title: "Sözün quruluşu",
      description: "Sözün kökü və şəkilçisi.",
      lessons: [
        {
          id: "az3-qurulus-l1",
          title: "Kök və şəkilçi",
          intro: "Sözün əsas hissəsi kök, ona qoşulan hissə şəkilçidir.",
          sections: [
            { heading: "Kök", body: "Sözün məna daşıyan əsas hissəsi köküdür: 'kitab' sözündə kök 'kitab'-dır." },
            { heading: "Şəkilçi", body: "Kökə qoşulan hissə şəkilçidir: 'kitablar' — kök 'kitab', şəkilçi '-lar' (cəm). 'evdə' — kök 'ev', şəkilçi '-də'." },
          ],
          tasks: [
            { id: "az3-qurulus-l1-t1", type: "multiple_choice", prompt: "'kitablar' sözünün kökü hansıdır?", options: ["kitab", "lar", "kitabl", "ar"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t2", type: "multiple_choice", prompt: "'evlər' sözünün kökü hansıdır?", options: ["ev", "lər", "evl", "ər"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t3", type: "multiple_choice", prompt: "'kitablar' sözündə şəkilçi hansıdır?", options: ["-lar", "kitab", "-ar", "kit"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t4", type: "multiple_choice", prompt: "Sözün əsas, məna daşıyan hissəsi necə adlanır?", options: ["kök", "şəkilçi", "heca", "səs"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t5", type: "multiple_choice", prompt: "Kökə qoşulan hissə necə adlanır?", options: ["şəkilçi", "kök", "heca", "vurğu"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t6", type: "multiple_choice", prompt: "'güllər' sözünün kökü hansıdır?", options: ["gül", "lər", "gül­l", "ər"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t7", type: "multiple_choice", prompt: "'evdə' sözünün kökü hansıdır?", options: ["ev", "də", "evd", "ə"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t8", type: "multiple_choice", prompt: "'-lar/-lər' şəkilçisi nə bildirir?", options: ["cəm (çoxluq)", "yer", "sahiblik", "hərəkət"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t9", type: "multiple_choice", prompt: "'uşaqlar' sözünün kökü hansıdır?", options: ["uşaq", "lar", "uşaql", "ar"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t10", type: "multiple_choice", prompt: "'dağlar' sözünün kökü hansıdır?", options: ["dağ", "lar", "dağl", "ar"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t11", type: "multiple_choice", prompt: "'kitabım' sözündə şəkilçi hansıdır?", options: ["-ım", "kitab", "-m", "kit"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t12", type: "multiple_choice", prompt: "'meşədə' sözünün kökü hansıdır?", options: ["meşə", "də", "meş", "ə"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t13", type: "multiple_choice", prompt: "Hər sözdə mütləq olan hissə hansıdır?", options: ["kök", "şəkilçi", "cəm şəkilçisi", "vurğu"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t14", type: "multiple_choice", prompt: "'quşlar' sözünün kökü hansıdır?", options: ["quş", "lar", "quşl", "ar"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l1-t15", type: "multiple_choice", prompt: "'baxçalar' sözündə şəkilçi hansıdır?", options: ["-lar", "baxça", "-ar", "bax"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az3-qurulus-l1-b1", type: "multiple_choice", prompt: "'kitabxanada' sözünün kökü hansıdır?", options: ["kitabxana", "da", "kitab", "xana"], correctIndex: 0, xp: 15 },
            { id: "az3-qurulus-l1-b2", type: "multiple_choice", prompt: "'evimiz' sözündə şəkilçi hansıdır?", options: ["-imiz", "ev", "-miz", "evi"], correctIndex: 0, xp: 15 },
            { id: "az3-qurulus-l1-b3", type: "multiple_choice", prompt: "Kök tək başına söz ola bilərmi?", options: ["bəli", "xeyr", "yalnız cəmdə", "yalnız feildə"], correctIndex: 0, xp: 15 },
            { id: "az3-qurulus-l1-b4", type: "multiple_choice", prompt: "'ağaclar' sözünün kökü hansıdır?", options: ["ağac", "lar", "ağacl", "ar"], correctIndex: 0, xp: 15 },
            { id: "az3-qurulus-l1-b5", type: "multiple_choice", prompt: "Şəkilçi sözə nə əlavə edir?", options: ["yeni məna/qrammatik məna", "heca", "vurğu", "səs"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-qurulus-l2",
          title: "Düzəltmə sözlər",
          intro: "Şəkilçi kökə yeni məna verir.",
          sections: [
            { heading: "Söz düzəldən şəkilçi", body: "Kökə qoşulub YENİ SÖZ düzəldir: iş → işçi, su → suvarmaq, kitab → kitabça, duz → duzlu." },
            { heading: "Fərq", body: "Söz düzəldən şəkilçi yeni məna yaradır (bal → balıq deyil, bal → ballı). Sözü dəyişən şəkilçi isə yalnız formanı dəyişir (kitab → kitablar)." },
          ],
          tasks: [
            { id: "az3-qurulus-l2-t1", type: "multiple_choice", prompt: "'iş' sözündən hansı düzəltmə söz alınır?", options: ["işçi", "işlər", "işi", "işdə"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l2-t2", type: "multiple_choice", prompt: "'duz' sözündən hansı düzəltmə söz alınır?", options: ["duzlu", "duzlar", "duzu", "duzda"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l2-t3", type: "multiple_choice", prompt: "'kitab' sözünün KÖKÜ hansıdır?", options: ["kitab", "kitablar", "-lar", "kitabça"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l2-t4", type: "multiple_choice", prompt: "'meşəçi' sözündə şəkilçi hansıdır?", options: ["-çi", "meşə", "-lər", "meşəç"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l2-t5", type: "multiple_choice", prompt: "Hansı söz DÜZƏLTMƏdir?", options: ["üzgüçü", "üzgüçülər", "üzür", "üzdü"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l2-t6", type: "multiple_choice", prompt: "Hansı söz SADƏdir (şəkilçisiz)?", options: ["ağac", "ağaclıq", "ağaclar", "ağacda"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l2-t7", type: "fill_blank", prompt: "'süd' sözündən 'südçü' düzəldi. Şəkilçi ______-dür. (məs. -çü)", accepted: ["-çü", "çü", "-cü"], xp: 10 },
            { id: "az3-qurulus-l2-t8", type: "multiple_choice", prompt: "'yaz' kökündən hansı düzəltmə söz alınır?", options: ["yazıçı", "yazdım", "yazır", "yazacaq"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l2-t9", type: "multiple_choice", prompt: "Şəkilçi sözün harasına qoşulur?", options: ["Sonuna", "Əvvəlinə", "Ortasına", "Fərqi yoxdur"], correctIndex: 0, xp: 10 },
            { id: "az3-qurulus-l2-t10", type: "multiple_choice", prompt: "'bağban' sözünün kökü hansıdır?", options: ["bağ", "ban", "bağba", "bağban"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az3-qurulus-l2-b1", type: "multiple_choice", prompt: "Hansı cütlükdə hər ikisi düzəltmə sözdür?", options: ["dəmirçi, çörəkçi", "kitab, qələm", "ev, su", "ağac, dağ"], correctIndex: 0, xp: 15 },
            { id: "az3-qurulus-l2-b2", type: "multiple_choice", prompt: "'-lıq / -lik' şəkilçisi hansı sözü düzəldir?", options: ["dostluq", "dostlar", "dostu", "dosta"], correctIndex: 0, xp: 15 },
            { id: "az3-qurulus-l2-b3", type: "multiple_choice", prompt: "'gözlük' sözünün kökü nədir?", options: ["göz", "lük", "gözlü", "gözlük"], correctIndex: 0, xp: 15 },
            { id: "az3-qurulus-l2-b4", type: "multiple_choice", prompt: "Söz düzəldən və söz dəyişdirən şəkilçi arasındakı fərq nədir?", options: ["Biri yeni söz yaradır, digəri formanı dəyişir", "Fərq yoxdur", "Biri uzundur", "Biri əvvəldə gəlir"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-qurulus-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-qurulus-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. İsim ═══════════════
    {
      id: "az3-isim",
      title: "İsim",
      description: "Əşyanın adını bildirən söz; tək və cəm, xüsusi və ümumi isimlər.",
      lessons: [
        {
          id: "az3-isim-l1",
          title: "İsim: tək və cəm",
          intro: "İsim əşyanın adıdır; təkdə və cəmdə olur.",
          sections: [
            { heading: "İsim", body: "Əşyanın adını bildirən, 'kim?', 'nə?' suallarına cavab verən sözə isim deyilir: kitab, uşaq, dağ." },
            { heading: "Tək və cəm", body: "Tək: bir əşya (kitab). Cəm: çox əşya (kitablar). Cəm '-lar/-lər' şəkilçisi ilə düzəlir." },
            { heading: "Xüsusi və ümumi", body: "Xüsusi isimlər (adlar, şəhərlər) böyük hərflə yazılır: Ayşə, Bakı. Ümumi isimlər kiçik hərflə: qız, şəhər." },
          ],
          tasks: [
            { id: "az3-isim-l1-t1", type: "multiple_choice", prompt: "İsim hansı suallara cavab verir?", options: ["kim? nə?", "necə?", "nə edir?", "neçə?"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı isimdir?", options: ["kitab", "oxumaq", "gözəl", "tez"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t3", type: "multiple_choice", prompt: "'kitab' sözünün cəmi hansıdır?", options: ["kitablar", "kitabı", "kitabda", "kitabın"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t4", type: "multiple_choice", prompt: "'uşaq' sözünün cəmi hansıdır?", options: ["uşaqlar", "uşağı", "uşaqda", "uşağın"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t5", type: "multiple_choice", prompt: "Cəm şəkilçisi hansıdır?", options: ["-lar/-lər", "-da/-də", "-ın/-in", "-ı/-i"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t6", type: "multiple_choice", prompt: "Xüsusi isimlər necə yazılır?", options: ["böyük hərflə", "kiçik hərflə", "cəmdə", "rəqəmlə"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı xüsusi isimdir?", options: ["Bakı", "şəhər", "dağ", "çay"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı ümumi isimdir?", options: ["qız", "Ayşə", "Gəncə", "Kür"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t9", type: "multiple_choice", prompt: "'gül' sözünün cəmi hansıdır?", options: ["güllər", "gülü", "güldə", "gülün"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t10", type: "multiple_choice", prompt: "'dağlar' sözü təkdə, yoxsa cəmdədir?", options: ["cəmdə", "təkdə", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı isim DEYİL?", options: ["qaçmaq", "kitab", "dağ", "quş"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t12", type: "multiple_choice", prompt: "İnsan adları hansı isim növüdür?", options: ["xüsusi", "ümumi", "cəm", "tək deyil"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t13", type: "multiple_choice", prompt: "'Elçin məktəbə getdi.' — isim hansıdır?", options: ["Elçin, məktəb", "getdi", "Elçin getdi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t14", type: "multiple_choice", prompt: "'quş' sözünün cəmi hansıdır?", options: ["quşlar", "quşu", "quşda", "quşun"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l1-t15", type: "multiple_choice", prompt: "Aşağıdakılardan hansı xüsusi isimdir?", options: ["Nərmin", "uşaq", "kitab", "ev"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az3-isim-l1-b1", type: "multiple_choice", prompt: "'ağac' sözünün cəmi hansıdır?", options: ["ağaclar", "ağacı", "ağacda", "ağacın"], correctIndex: 0, xp: 15 },
            { id: "az3-isim-l1-b2", type: "multiple_choice", prompt: "Şəhər, çay, dağ adları hansı isim növüdür?", options: ["xüsusi", "ümumi", "cəm", "tək"], correctIndex: 0, xp: 15 },
            { id: "az3-isim-l1-b3", type: "multiple_choice", prompt: "Hansı düzgün yazılıb?", options: ["Bakı", "bakı", "BAKı", "baKı"], correctIndex: 0, xp: 15 },
            { id: "az3-isim-l1-b4", type: "multiple_choice", prompt: "'pəncərələr' sözü hansı formadadır?", options: ["cəm", "tək", "xüsusi", "feil"], correctIndex: 0, xp: 15 },
            { id: "az3-isim-l1-b5", type: "multiple_choice", prompt: "'Kür' sözü nəyin adıdır?", options: ["çayın (xüsusi isim)", "dağın", "şəhərin", "əşyanın"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-isim-l2",
          title: "Xüsusi və ümumi isimlər",
          intro: "Adlar böyük, ümumi sözlər kiçik hərflə yazılır.",
          sections: [
            { heading: "Xüsusi isim", body: "Konkret bir varlığın adıdır: Aysel, Bakı, Kür, Azərbaycan. Həmişə BÖYÜK hərflə yazılır." },
            { heading: "Ümumi isim", body: "Eyni növdən olan hər şeyin adıdır: şəhər, çay, uşaq, ölkə. Kiçik hərflə yazılır." },
          ],
          tasks: [
            { id: "az3-isim-l2-t1", type: "multiple_choice", prompt: "Hansı XÜSUSİ isimdir?", options: ["Bakı", "şəhər", "küçə", "ev"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l2-t2", type: "multiple_choice", prompt: "Hansı ÜMUMİ isimdir?", options: ["çay", "Kür", "Araz", "Xəzər"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l2-t3", type: "multiple_choice", prompt: "Xüsusi isimlər necə yazılır?", options: ["Böyük hərflə", "Kiçik hərflə", "Fərqi yoxdur", "Dırnaqda"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l2-t4", type: "multiple_choice", prompt: "Hansı XÜSUSİ isimdir?", options: ["Azərbaycan", "ölkə", "dövlət", "xalq"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l2-t5", type: "multiple_choice", prompt: "Hansı ÜMUMİ isimdir?", options: ["müəllim", "Aysel", "Nihad", "Leyla"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l2-t6", type: "multiple_choice", prompt: "'Nizami' sözü hansı isimdir?", options: ["Xüsusi", "Ümumi", "Sifət", "Feil"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l2-t7", type: "fill_blank", prompt: "İnsan adları ______ hərflə yazılır. (bir söz)", accepted: ["böyük", "Böyük"], xp: 10 },
            { id: "az3-isim-l2-t8", type: "multiple_choice", prompt: "Hansı cümlədə xüsusi isim var?", options: ["Aysel məktəbə getdi.", "Uşaq məktəbə getdi.", "O, məktəbə getdi.", "Məktəbə getdilər."], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l2-t9", type: "multiple_choice", prompt: "'dəniz' və 'Xəzər' — hansı xüsusidir?", options: ["Xəzər", "dəniz", "İkisi də", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-isim-l2-t10", type: "multiple_choice", prompt: "Şəhər adları hansı isimdir?", options: ["Xüsusi", "Ümumi", "Sifət", "Say"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az3-isim-l2-b1", type: "multiple_choice", prompt: "Hansı cümlədə səhv var?", options: ["mən bakıda yaşayıram.", "Mən Bakıda yaşayıram.", "Bakı gözəldir.", "Aysel Bakıdandır."], correctIndex: 0, xp: 15 },
            { id: "az3-isim-l2-b2", type: "multiple_choice", prompt: "Kitab adları necə yazılır?", options: ["Böyük hərflə və dırnaqda", "Kiçik hərflə", "Yalnız dırnaqda", "Fərqi yoxdur"], correctIndex: 0, xp: 15 },
            { id: "az3-isim-l2-b3", type: "multiple_choice", prompt: "Hansı sırada hamısı xüsusi isimdir?", options: ["Gəncə, Kür, Nizami", "şəhər, çay, şair", "ev, su, ağac", "dağ, dəniz, göl"], correctIndex: 0, xp: 15 },
            { id: "az3-isim-l2-b4", type: "multiple_choice", prompt: "Heyvan adları (məs. pişiyin adı 'Pambıq') hansı isimdir?", options: ["Xüsusi", "Ümumi", "Sifət", "Feil"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-isim-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-isim-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Sifət və say ═══════════════
    {
      id: "az3-sifetsay",
      title: "Sifət və say",
      description: "Əlamət bildirən sifət və miqdar bildirən say.",
      lessons: [
        {
          id: "az3-sifetsay-l1",
          title: "Sifət və say",
          intro: "Sifət əlaməti, say miqdarı bildirir.",
          sections: [
            { heading: "Sifət", body: "Əşyanın əlamətini bildirən, 'necə?', 'nə cür?' suallarına cavab verən sözə sifət deyilir: gözəl, böyük, qırmızı." },
            { heading: "Say", body: "Əşyanın miqdarını, sayını bildirən, 'neçə?', 'nə qədər?' suallarına cavab verən sözə say deyilir: bir, iki, beş, on." },
          ],
          tasks: [
            { id: "az3-sifetsay-l1-t1", type: "multiple_choice", prompt: "Sifət hansı suala cavab verir?", options: ["necə?", "kim?", "nə edir?", "neçə?"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t2", type: "multiple_choice", prompt: "Say hansı suala cavab verir?", options: ["neçə? nə qədər?", "necə?", "kim?", "nə edir?"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t3", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sifətdir?", options: ["gözəl", "kitab", "beş", "oxumaq"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t4", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saydır?", options: ["üç", "gözəl", "kitab", "qaçmaq"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t5", type: "multiple_choice", prompt: "'qırmızı gül' — hansı söz sifətdir?", options: ["qırmızı", "gül", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t6", type: "multiple_choice", prompt: "'beş kitab' — hansı söz saydır?", options: ["beş", "kitab", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t7", type: "multiple_choice", prompt: "Aşağıdakılardan hansı sifətdir?", options: ["böyük", "iki", "ev", "getmək"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t8", type: "multiple_choice", prompt: "Aşağıdakılardan hansı saydır?", options: ["on", "isti", "su", "içmək"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t9", type: "multiple_choice", prompt: "'üç alma' — hansı söz saydır?", options: ["üç", "alma", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t10", type: "multiple_choice", prompt: "'isti çay' — hansı söz sifətdir?", options: ["isti", "çay", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t11", type: "multiple_choice", prompt: "'yaşıl yarpaq' — sifət hansıdır?", options: ["yaşıl", "yarpaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t12", type: "multiple_choice", prompt: "Sifət əşyanın nəyini bildirir?", options: ["əlamətini", "sayını", "hərəkətini", "adını"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t13", type: "multiple_choice", prompt: "Say əşyanın nəyini bildirir?", options: ["miqdarını/sayını", "əlamətini", "hərəkətini", "adını"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t14", type: "multiple_choice", prompt: "'iki gözəl gül' — say hansıdır?", options: ["iki", "gözəl", "gül", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l1-t15", type: "multiple_choice", prompt: "'böyük' sözünün əksi (antonim) hansıdır?", options: ["kiçik", "gözəl", "isti", "yeni"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az3-sifetsay-l1-b1", type: "multiple_choice", prompt: "'On beş dəftər' — say hansıdır?", options: ["on beş", "dəftər", "on", "beş"], correctIndex: 0, xp: 15 },
            { id: "az3-sifetsay-l1-b2", type: "multiple_choice", prompt: "'təmiz, işıqlı otaq' — neçə sifət var?", options: ["2 (təmiz, işıqlı)", "1", "3", "0"], correctIndex: 0, xp: 15 },
            { id: "az3-sifetsay-l1-b3", type: "multiple_choice", prompt: "'birinci' sözü hansı nitq hissəsidir?", options: ["say (sıra)", "sifət", "isim", "feil"], correctIndex: 0, xp: 15 },
            { id: "az3-sifetsay-l1-b4", type: "multiple_choice", prompt: "'soyuq' sözünün əksi hansıdır?", options: ["isti", "böyük", "təmiz", "yeni"], correctIndex: 0, xp: 15 },
            { id: "az3-sifetsay-l1-b5", type: "multiple_choice", prompt: "'üç böyük ağac' — bu ifadədə isim hansıdır?", options: ["ağac", "üç", "böyük", "heç biri"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-sifetsay-l2",
          title: "Miqdar və sıra sayları",
          intro: "Neçə? və neçənci? — iki fərqli sual.",
          sections: [
            { heading: "Miqdar sayı", body: "'Neçə?' sualına cavab verir: bir, iki, üç, on. Məsələn: beş kitab." },
            { heading: "Sıra sayı", body: "'Neçənci?' sualına cavab verir və -ıncı/-inci şəkilçisi alır: birinci, ikinci, beşinci." },
          ],
          tasks: [
            { id: "az3-sifetsay-l2-t1", type: "multiple_choice", prompt: "'beş kitab' — burada 'beş' hansı saydır?", options: ["Miqdar", "Sıra", "Sifət", "İsim"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l2-t2", type: "multiple_choice", prompt: "'beşinci sinif' — burada 'beşinci' hansı saydır?", options: ["Sıra", "Miqdar", "Sifət", "İsim"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l2-t3", type: "multiple_choice", prompt: "Miqdar sayı hansı suala cavab verir?", options: ["Neçə?", "Neçənci?", "Necə?", "Harada?"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l2-t4", type: "multiple_choice", prompt: "Sıra sayı hansı suala cavab verir?", options: ["Neçənci?", "Neçə?", "Necə?", "Nə vaxt?"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l2-t5", type: "multiple_choice", prompt: "Hansı SIRA sayıdır?", options: ["üçüncü", "üç", "üçlük", "üçdə"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l2-t6", type: "multiple_choice", prompt: "Hansı MİQDAR sayıdır?", options: ["yeddi", "yeddinci", "yeddilik", "yeddidə"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l2-t7", type: "fill_blank", prompt: "Sıra sayının şəkilçisi ______ / -inci-dir. (məs. -ıncı)", accepted: ["-ıncı", "ıncı", "-inci"], xp: 10 },
            { id: "az3-sifetsay-l2-t8", type: "multiple_choice", prompt: "'On beş şagird' ifadəsində say hansıdır?", options: ["on beş", "şagird", "on", "beş şagird"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l2-t9", type: "multiple_choice", prompt: "'Birinci yer' — 'birinci' nəyi bildirir?", options: ["Sıranı", "Miqdarı", "Rəngi", "Ölçünü"], correctIndex: 0, xp: 10 },
            { id: "az3-sifetsay-l2-t10", type: "multiple_choice", prompt: "Hansı cümlədə sıra sayı var?", options: ["İkinci dərs başladı.", "İki dərs var.", "Dərs iki saatdır.", "Dərsə iki nəfər gəldi."], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az3-sifetsay-l2-b1", type: "multiple_choice", prompt: "'Yüz iyirmi beşinci' — bu hansı saydır?", options: ["Sıra", "Miqdar", "Sifət", "İsim"], correctIndex: 0, xp: 15 },
            { id: "az3-sifetsay-l2-b2", type: "multiple_choice", prompt: "Saylar hansı sözlərlə birlikdə işlənir?", options: ["İsimlərlə", "Feillərlə", "Zərflərlə", "Bağlayıcılarla"], correctIndex: 0, xp: 15 },
            { id: "az3-sifetsay-l2-b3", type: "multiple_choice", prompt: "'Üç qat' ifadəsində say nə bildirir?", options: ["Miqdarı", "Sıranı", "Rəngi", "Yeri"], correctIndex: 0, xp: 15 },
            { id: "az3-sifetsay-l2-b4", type: "multiple_choice", prompt: "Sıra sayları rəqəmlə necə yazılır?", options: ["5-ci", "5 ci", "5.ci", "ci-5"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-sifetsay-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-sifetsay-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Feil ═══════════════
    {
      id: "az3-feil",
      title: "Feil",
      description: "Hərəkət bildirən söz və onun zamanları.",
      lessons: [
        {
          id: "az3-feil-l1",
          title: "Feil və zamanları",
          intro: "Feil hərəkət bildirir; keçmiş, indiki, gələcək zamanda olur.",
          sections: [
            { heading: "Feil", body: "İşi, hərəkəti bildirən söz feildir: gəlir, oxudu, yazacaq. 'Nə edir?', 'nə etdi?', 'nə edəcək?' suallarına cavab verir." },
            { heading: "Zamanlar", body: "Keçmiş: gəldi (oldu). İndiki: gəlir (indi olur). Gələcək: gələcək (sonra olacaq)." },
          ],
          tasks: [
            { id: "az3-feil-l1-t1", type: "multiple_choice", prompt: "Feil hansı suala cavab verir?", options: ["nə edir?", "kim?", "necə?", "neçə?"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feildir?", options: ["oxuyur", "kitab", "gözəl", "beş"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t3", type: "multiple_choice", prompt: "'gəldi' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t4", type: "multiple_choice", prompt: "'gəlir' feili hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t5", type: "multiple_choice", prompt: "'gələcək' feili hansı zamandadır?", options: ["gələcək", "keçmiş", "indiki", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t6", type: "multiple_choice", prompt: "'Uşaq oynayır.' — feil hansıdır?", options: ["oynayır", "uşaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t7", type: "multiple_choice", prompt: "'yazdı' feili hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t8", type: "multiple_choice", prompt: "'oxuyacaq' feili hansı zamandadır?", options: ["gələcək", "keçmiş", "indiki", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t9", type: "fill_blank", prompt: "'gəl' feilini keçmiş zamana çevir (3-cü şəxs tək).", accepted: ["gəldi"], xp: 10 },
            { id: "az3-feil-l1-t10", type: "fill_blank", prompt: "'yaz' feilini indiki zamana çevir (3-cü şəxs tək).", accepted: ["yazır"], xp: 10 },
            { id: "az3-feil-l1-t11", type: "multiple_choice", prompt: "Aşağıdakılardan hansı feil DEYİL?", options: ["kitab", "gəlir", "oxudu", "yazacaq"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t12", type: "multiple_choice", prompt: "'Quş uçur.' — feil hansı zamandadır?", options: ["indiki", "keçmiş", "gələcək", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t13", type: "multiple_choice", prompt: "Feil neçə zamanda olur?", options: ["üç (keçmiş, indiki, gələcək)", "iki", "dörd", "bir"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l1-t14", type: "fill_blank", prompt: "'oxu' feilini gələcək zamana çevir (3-cü şəxs tək).", accepted: ["oxuyacaq"], xp: 10 },
            { id: "az3-feil-l1-t15", type: "multiple_choice", prompt: "'Sabah gedəcəyəm.' — feil hansı zamandadır?", options: ["gələcək", "keçmiş", "indiki", "heç biri"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az3-feil-l1-b1", type: "multiple_choice", prompt: "'Dünən oxudum.' — feil hansı zamandadır?", options: ["keçmiş", "indiki", "gələcək", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "az3-feil-l1-b2", type: "fill_blank", prompt: "'get' feilini keçmiş zamana çevir (3-cü şəxs tək).", accepted: ["getdi"], xp: 15 },
            { id: "az3-feil-l1-b3", type: "multiple_choice", prompt: "'Ağ pişik yatır.' — feil hansıdır?", options: ["yatır", "ağ", "pişik", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "az3-feil-l1-b4", type: "multiple_choice", prompt: "İnkar: 'gəl' feilinin inkarı hansıdır?", options: ["gəlmə", "gəldi", "gəlir", "gələcək"], correctIndex: 0, xp: 15 },
            { id: "az3-feil-l1-b5", type: "fill_blank", prompt: "'yaz' feilinin inkar formasını yaz.", accepted: ["yazma"], xp: 15 },
          ],
        },
        {
          id: "az3-feil-l2",
          title: "Feilin şəxsə görə dəyişməsi",
          intro: "Kim edir? — feil buna görə dəyişir.",
          sections: [
            { heading: "Şəxs şəkilçiləri", body: "mən yazıram, sən yazırsan, o yazır, biz yazırıq, siz yazırsınız, onlar yazırlar." },
            { heading: "Təsdiq və inkar", body: "Feilə -ma / -mə əlavə edəndə inkar olur: gəlirəm → gəlmirəm, yazdım → yazmadım." },
          ],
          tasks: [
            { id: "az3-feil-l2-t1", type: "multiple_choice", prompt: "'Mən ______' — hansı forma düzgündür?", options: ["yazıram", "yazırsan", "yazır", "yazırıq"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l2-t2", type: "multiple_choice", prompt: "'Onlar ______' — hansı forma düzgündür?", options: ["gəlirlər", "gəlirəm", "gəlirsən", "gəlir"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l2-t3", type: "multiple_choice", prompt: "'Biz ______' — hansı forma düzgündür?", options: ["oxuyuruq", "oxuyuram", "oxuyur", "oxuyursan"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l2-t4", type: "multiple_choice", prompt: "'gəlirəm' feilinin inkarı hansıdır?", options: ["gəlmirəm", "gəldim", "gələcəyəm", "gəlirsən"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l2-t5", type: "multiple_choice", prompt: "'yazdım' feilinin inkarı hansıdır?", options: ["yazmadım", "yazıram", "yazacağam", "yazdın"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l2-t6", type: "multiple_choice", prompt: "İnkar şəkilçisi hansıdır?", options: ["-ma / -mə", "-lar / -lər", "-dı / -di", "-ır / -ir"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l2-t7", type: "multiple_choice", prompt: "'Sən ______' — hansı forma düzgündür?", options: ["gedirsən", "gedirəm", "gedir", "gedirik"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l2-t8", type: "fill_blank", prompt: "'O ______' (oxumaq, indiki zaman) — düzgün forma nədir?", accepted: ["oxuyur", "Oxuyur"], xp: 10 },
            { id: "az3-feil-l2-t9", type: "multiple_choice", prompt: "Feil nəyə görə dəyişir?", options: ["Şəxsə və zamana", "Rəngə", "Ölçüyə", "Yerə"], correctIndex: 0, xp: 10 },
            { id: "az3-feil-l2-t10", type: "multiple_choice", prompt: "'Siz gəlirsiniz' cümləsində şəxs hansıdır?", options: ["II şəxs cəm", "I şəxs tək", "III şəxs tək", "I şəxs cəm"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az3-feil-l2-b1", type: "multiple_choice", prompt: "'Onlar gəlmədilər' cümləsi necədir?", options: ["İnkar, keçmiş zaman", "Təsdiq, keçmiş zaman", "İnkar, gələcək zaman", "Təsdiq, indiki zaman"], correctIndex: 0, xp: 15 },
            { id: "az3-feil-l2-b2", type: "multiple_choice", prompt: "'Oxumuram' feilində neçə şəkilçi var?", options: ["İki: inkar və şəxs", "Bir", "Üç", "Heç biri"], correctIndex: 0, xp: 15 },
            { id: "az3-feil-l2-b3", type: "multiple_choice", prompt: "Hansı cümlədə feil III şəxs cəmdədir?", options: ["Uşaqlar oynayırlar.", "Uşaq oynayır.", "Mən oynayıram.", "Sən oynayırsan."], correctIndex: 0, xp: 15 },
            { id: "az3-feil-l2-b4", type: "multiple_choice", prompt: "'Gəlməyəcəyəm' feilində zaman hansıdır?", options: ["Gələcək", "Keçmiş", "İndiki", "Zamansız"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-feil-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-feil-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Cümlə və mətn ═══════════════
    {
      id: "az3-cumle",
      title: "Cümlə və mətn",
      description: "Cümlə növləri, mübtəda-xəbər və mətn.",
      lessons: [
        {
          id: "az3-cumle-l1",
          title: "Cümlə",
          intro: "Cümlə növləri və əsas üzvləri.",
          sections: [
            { heading: "Cümlə növləri", body: "Nəqli cümlə məlumat verir (nöqtə). Sual cümləsi sual verir (?). Nida cümləsi hiss bildirir (!)." },
            { heading: "Kim/nə iş görür?", body: "Cümlədə iş görəni bildirən söz mübtəda, işi bildirən söz xəbərdir: 'Uşaq oxuyur.' — uşaq (mübtəda), oxuyur (xəbər)." },
          ],
          tasks: [
            { id: "az3-cumle-l1-t1", type: "multiple_choice", prompt: "Məlumat verən cümlə necə adlanır?", options: ["nəqli", "sual", "nida", "əmr"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t2", type: "multiple_choice", prompt: "Sual cümləsi hansı işarə ilə bitir?", options: ["sual işarəsi (?)", "nöqtə (.)", "nida işarəsi (!)", "vergül"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t3", type: "multiple_choice", prompt: "Nida cümləsi hansı işarə ilə bitir?", options: ["nida işarəsi (!)", "nöqtə", "sual işarəsi", "vergül"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t4", type: "multiple_choice", prompt: "'Yağış yağır.' hansı cümlə növüdür?", options: ["nəqli", "sual", "nida", "əmr"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t5", type: "multiple_choice", prompt: "'Sən hara gedirsən?' hansı cümlə növüdür?", options: ["sual", "nəqli", "nida", "əmr"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t6", type: "multiple_choice", prompt: "'Nə gözəldir!' hansı cümlə növüdür?", options: ["nida", "nəqli", "sual", "əmr"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t7", type: "multiple_choice", prompt: "'Uşaq oxuyur.' — mübtəda hansıdır?", options: ["uşaq", "oxuyur", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t8", type: "multiple_choice", prompt: "'Uşaq oxuyur.' — xəbər hansıdır?", options: ["oxuyur", "uşaq", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t9", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["böyük hərflə", "kiçik hərflə", "rəqəmlə", "fərq etməz"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t10", type: "multiple_choice", prompt: "'Quşlar cənuba uçur.' — mübtəda hansıdır?", options: ["quşlar", "cənuba", "uçur", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t11", type: "multiple_choice", prompt: "Nəqli cümlə hansı işarə ilə bitir?", options: ["nöqtə (.)", "sual işarəsi", "nida işarəsi", "vergül"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t12", type: "multiple_choice", prompt: "'Bahar gəldi.' — xəbər hansıdır?", options: ["gəldi", "bahar", "hər ikisi", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t13", type: "multiple_choice", prompt: "İş görəni bildirən üzv necə adlanır?", options: ["mübtəda", "xəbər", "təyin", "tamamlıq"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t14", type: "multiple_choice", prompt: "İşi bildirən üzv necə adlanır?", options: ["xəbər", "mübtəda", "təyin", "tamamlıq"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l1-t15", type: "multiple_choice", prompt: "'Günəş parlayır.' — xəbər hansıdır?", options: ["parlayır", "günəş", "hər ikisi", "heç biri"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "az3-cumle-l1-b1", type: "multiple_choice", prompt: "'Mən kitab oxuyuram.' — mübtəda hansıdır?", options: ["mən", "kitab", "oxuyuram", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "az3-cumle-l1-b2", type: "multiple_choice", prompt: "Mətn nədən ibarətdir?", options: ["cümlələrdən", "yalnız sözlərdən", "hərflərdən", "hecalardan"], correctIndex: 0, xp: 15 },
            { id: "az3-cumle-l1-b3", type: "multiple_choice", prompt: "'Diqqətli ol!' hansı cümlə növüdür?", options: ["nida/əmr", "nəqli", "sual", "adi"], correctIndex: 0, xp: 15 },
            { id: "az3-cumle-l1-b4", type: "multiple_choice", prompt: "Mətnin adı necə adlanır?", options: ["başlıq", "cümlə", "abzas", "söz"], correctIndex: 0, xp: 15 },
            { id: "az3-cumle-l1-b5", type: "multiple_choice", prompt: "'Uşaqlar bağçada oynayır.' — xəbər hansıdır?", options: ["oynayır", "uşaqlar", "bağçada", "heç biri"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-cumle-l2",
          title: "Cümlənin növləri",
          intro: "Cümlə nə məqsədlə deyilir?",
          sections: [
            { heading: "Növlər", body: "NƏQLİ: məlumat verir (Bu gün hava gözəldir.). SUAL: soruşur (Hava necədir?). ƏMR: göstəriş verir (Qapını bağla!). NİDA: hissi bildirir (Nə gözəl gündür!)." },
            { heading: "Durğu işarəsi", body: "Nəqli cümlə nöqtə ilə, sual cümləsi sual işarəsi ilə, əmr və nida cümləsi nida işarəsi ilə bitir." },
          ],
          tasks: [
            { id: "az3-cumle-l2-t1", type: "multiple_choice", prompt: "'Bu gün hava gözəldir.' — hansı cümlədir?", options: ["Nəqli", "Sual", "Əmr", "Nida"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l2-t2", type: "multiple_choice", prompt: "'Hava necədir?' — hansı cümlədir?", options: ["Sual", "Nəqli", "Əmr", "Nida"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l2-t3", type: "multiple_choice", prompt: "'Qapını bağla!' — hansı cümlədir?", options: ["Əmr", "Sual", "Nəqli", "Nida"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l2-t4", type: "multiple_choice", prompt: "'Nə gözəl gündür!' — hansı cümlədir?", options: ["Nida", "Sual", "Nəqli", "Əmr"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l2-t5", type: "multiple_choice", prompt: "Sual cümləsinin sonunda hansı işarə qoyulur?", options: ["?", "!", ".", ","], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l2-t6", type: "multiple_choice", prompt: "Nəqli cümlənin sonunda hansı işarə qoyulur?", options: [".", "?", "!", ";"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l2-t7", type: "fill_blank", prompt: "Əmr cümləsi ______ işarəsi ilə bitir. (işarəni yaz)", accepted: ["!", "nida"], xp: 10 },
            { id: "az3-cumle-l2-t8", type: "multiple_choice", prompt: "'Kitabı mənə ver.' — hansı cümlədir?", options: ["Əmr", "Sual", "Nida", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l2-t9", type: "multiple_choice", prompt: "Cümlə hansı hərflə başlayır?", options: ["Böyük", "Kiçik", "Fərqi yoxdur", "Rəqəmlə"], correctIndex: 0, xp: 10 },
            { id: "az3-cumle-l2-t10", type: "multiple_choice", prompt: "'Sən hara gedirsən?' cümləsi hansı növdür?", options: ["Sual", "Nəqli", "Əmr", "Nida"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "az3-cumle-l2-b1", type: "multiple_choice", prompt: "Hansı cümlədə durğu işarəsi SƏHVDİR?", options: ["Necəsən.", "Necəsən?", "Yaxşıyam.", "Nə yaxşı!"], correctIndex: 0, xp: 15 },
            { id: "az3-cumle-l2-b2", type: "multiple_choice", prompt: "Bir cümlə həm sual, həm nida ola bilərmi?", options: ["Bəli: 'Doğrudanmı?!'", "Xeyr", "Yalnız yazıda", "Yalnız şeirdə"], correctIndex: 0, xp: 15 },
            { id: "az3-cumle-l2-b3", type: "multiple_choice", prompt: "'Gəl!' cümləsində neçə söz var?", options: ["1", "2", "3", "0"], correctIndex: 0, xp: 15 },
            { id: "az3-cumle-l2-b4", type: "multiple_choice", prompt: "Mətn nədir?", options: ["Mənaca bağlı cümlələr toplusu", "Bir cümlə", "Bir söz", "Bir abzas işarəsi"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "az3-cumle-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "az3-cumle-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
