// İngilis dili — 4-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Present Continuous  2) Past Simple (was/were)  3) Past Simple (-ed)
// 4) There is / there are  5) Comparatives  6) Sual sözləri və lüğət.
// 4-cü sinif üçün: qısa qrammatika + şəkil-söz + dinləmə. id prefiksi en4-*.

import type { Subject } from "../types";

export const english4: Subject = {
  slug: "ingilis-dili-4",
  name: "İngilis dili",
  grade: 4,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Present Continuous ═══════════════
    {
      id: "en4-continuous",
      title: "Present Continuous (indi baş verən)",
      description: "İndi baş verən iş: am/is/are + V-ing.",
      lessons: [
        {
          id: "en4-continuous-rule",
          title: "Qayda: Present Continuous",
          intro: "İndi baş verən iş: I am playing. She is reading.",
          sections: [
            { heading: "Necə düzəlir?", body: "am/is/are + feil-ing. I am playing. You/we/they are playing. He/she/it is playing." },
            { heading: "İndi", body: "Bu, indi (danışıq anında) baş verən işdir: 'Look! The baby is sleeping.'" },
          ],
          tasks: [
            { id: "en4-continuous-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ playing.' (indi)", options: ["am", "is", "are", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ reading.'", options: ["is", "am", "are", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'They ___ running.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "Present Continuous necə düzəlir?", options: ["am/is/are + V-ing", "V + s", "was + V", "will + V"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'He is ___.' (play)", options: ["playing", "plays", "played", "play"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'We ___ eating.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t7", type: "multiple_choice", prompt: "'I am reading.' nə deməkdir?", options: ["Oxuyuram (indi).", "Oxudum.", "Oxuyacağam.", "Oxumağı sevirəm."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'You ___ writing.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t9", type: "fill_blank", prompt: "'run' feilinə -ing əlavə et (samit ikiqat).", accepted: ["running"], xp: 10 },
            { id: "en4-continuous-rule-t10", type: "fill_blank", prompt: "'read' feilinə -ing əlavə et.", accepted: ["reading"], xp: 10 },
            { id: "en4-continuous-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'The cat ___ sleeping.'", options: ["is", "am", "are", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'Look! It ___ raining.'", options: ["is", "am", "are", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t13", type: "multiple_choice", prompt: "'She is cooking.' nə deməkdir?", options: ["O bişirir (indi).", "O bişirdi.", "O bişirəcək.", "O bişirməyi sevir."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'I am ___.' (write)", options: ["writing", "writes", "wrote", "write"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'The children ___ playing.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en4-continuous-rule-b1", type: "fill_blank", prompt: "'swim' feilinə -ing əlavə et (samit ikiqat).", accepted: ["swimming"], xp: 15 },
            { id: "en4-continuous-rule-b2", type: "fill_blank", prompt: "'make' feilinə -ing əlavə et (e düşür).", accepted: ["making"], xp: 15 },
            { id: "en4-continuous-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ playing.' (deyiləm)", options: ["am not", "isn't", "aren't", "not"], correctIndex: 0, xp: 15 },
            { id: "en4-continuous-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "Sual: 'What ___ you doing?'", options: ["are", "is", "am", "do"], correctIndex: 0, xp: 15 },
            { id: "en4-continuous-rule-b5", type: "multiple_choice", prompt: "'They are watching TV.' nə deməkdir?", options: ["Onlar televizora baxır (indi).", "Baxdılar.", "Baxacaqlar.", "Televizoru sevirlər."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en4-continuous-listen",
          title: "Dinləmə: Present Continuous",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en4-continuous-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am playing football.", options: ["Futbol oynayıram (indi).", "Futbol oynadım.", "Futbolu sevirəm.", "Futbol oynayacağam."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "She is reading a book.", options: ["O kitab oxuyur (indi).", "O kitab oxudu.", "O kitab aldı.", "O kitabı sevir."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The baby is sleeping.", options: ["Körpə yatır.", "Körpə yatdı.", "Körpə oyaqdır.", "Körpə ağlayır."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They are running.", options: ["Onlar qaçır.", "Onlar qaçdı.", "Onlar oturur.", "Onlar dayanır."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "It is raining.", options: ["Yağış yağır.", "Yağış yağdı.", "Hava aydındır.", "Qar yağır."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We are eating lunch.", options: ["Nahar edirik (indi).", "Nahar etdik.", "Nahar edəcəyik.", "Ac deyilik."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "He is writing a letter.", options: ["O məktub yazır (indi).", "O məktub yazdı.", "O məktub oxudu.", "O məktub aldı."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The dog is barking.", options: ["İt hürür.", "İt hürdü.", "İt yatır.", "İt qaçır."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am doing my homework.", options: ["Ev tapşırığımı edirəm (indi).", "Ev tapşırığımı etdim.", "Ev tapşırığım var.", "Ev tapşırığı yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "She is singing a song.", options: ["O mahnı oxuyur (indi).", "O mahnı oxudu.", "O rəqs edir.", "O dinləyir."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The children are playing.", options: ["Uşaqlar oynayır (indi).", "Uşaqlar oynadı.", "Uşaqlar yatır.", "Uşaqlar oxuyur."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "My mother is cooking.", options: ["Anam bişirir (indi).", "Anam bişirdi.", "Anam gəldi.", "Anam işləyir."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t13", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "What are you doing?", options: ["Nə edirsən (indi)?", "Nə etdin?", "Nə edəcəksən?", "Necəsən?"], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The birds are flying.", options: ["Quşlar uçur.", "Quşlar uçdu.", "Quşlar oxuyur.", "Quşlar yuvadadır."], correctIndex: 0, xp: 10 },
            { id: "en4-continuous-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am not sleeping.", options: ["Yatmıram.", "Yatıram.", "Yatdım.", "Yorğunam."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en4-continuous-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The sun is shining.", options: ["Günəş parlayır.", "Günəş batdı.", "Hava soyuqdur.", "Yağış yağır."], correctIndex: 0, xp: 15 },
            { id: "en4-continuous-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We are watching a film.", options: ["Film baxırıq (indi).", "Film baxdıq.", "Film baxacağıq.", "Filmi sevirik."], correctIndex: 0, xp: 15 },
            { id: "en4-continuous-listen-b3", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Where are you going?", options: ["Hara gedirsən (indi)?", "Hara getdin?", "Hara gedəcəksən?", "Haradasan?"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 2. Past Simple (was/were) ═══════════════
    {
      id: "en4-was",
      title: "Past Simple: was / were",
      description: "Keçmişdə vəziyyət: was (tək), were (cəm).",
      lessons: [
        {
          id: "en4-was-rule",
          title: "Qayda: was / were",
          intro: "'am/is' → was, 'are' → were. I was happy. They were here.",
          sections: [
            { heading: "was / were", body: "I/he/she/it → was. you/we/they → were. 'I was at home.' — Evdə idim. 'They were happy.' — Onlar xoşbəxt idi." },
            { heading: "İnkar", body: "wasn't / weren't: I wasn't tired. They weren't there." },
          ],
          tasks: [
            { id: "en4-was-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ at home.' (idim)", options: ["was", "were", "am", "is"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'They ___ happy.' (idilər)", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'She ___ tired.' (idi)", options: ["was", "were", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'We ___ at school.' (idik)", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'am/is' keçmişdə nəyə çevrilir?", options: ["was", "were", "will", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'are' keçmişdə nəyə çevrilir?", options: ["were", "was", "will", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t7", type: "multiple_choice", prompt: "'I was happy.' nə deməkdir?", options: ["Xoşbəxt idim.", "Xoşbəxtəm.", "Xoşbəxt olacağam.", "Xoşbəxt deyiləm."], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'He ___ a good boy.'", options: ["was", "were", "are", "am"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'You ___ late.' (gecikmişdin)", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ tired.' (yorğun deyildim)", options: ["wasn't", "weren't", "am not", "isn't"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'They ___ here.' (yox idilər)", options: ["weren't", "wasn't", "aren't", "isn't"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t12", type: "multiple_choice", prompt: "'They were at the park.' nə deməkdir?", options: ["Parkda idilər.", "Parkdadırlar.", "Parka gedəcəklər.", "Parkı sevirlər."], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'It ___ cold yesterday.'", options: ["was", "were", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'The books ___ on the table.'", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 10 },
            { id: "en4-was-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'My friends ___ at the party.'", options: ["were", "was", "are", "am"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en4-was-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you at home?'", options: ["Were", "Was", "Are", "Do"], correctIndex: 0, xp: 15 },
            { id: "en4-was-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ she happy?'", options: ["Was", "Were", "Is", "Did"], correctIndex: 0, xp: 15 },
            { id: "en4-was-rule-b3", type: "multiple_choice", prompt: "'It wasn't easy.' nə deməkdir?", options: ["Asan deyildi.", "Asandır.", "Asan olacaq.", "Çətindir."], correctIndex: 0, xp: 15 },
            { id: "en4-was-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'There ___ many people.' (çoxlu adam var idi)", options: ["were", "was", "are", "is"], correctIndex: 0, xp: 15 },
            { id: "en4-was-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a cat in the garden.' (bir pişik var idi)", options: ["was", "were", "is", "are"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 3. Past Simple (-ed) ═══════════════
    {
      id: "en4-past",
      title: "Past Simple (-ed feillər)",
      description: "Keçmiş sadə zaman: qaydalı feillərə -ed əlavə olunur.",
      lessons: [
        {
          id: "en4-past-rule",
          title: "Qayda: Past Simple",
          intro: "Qaydalı feillər: play → played, watch → watched. Qeyri-qaydalı: go → went.",
          sections: [
            { heading: "Qaydalı feillər", body: "Feilə -ed əlavə olunur: play → played, watch → watched, help → helped. 'I played football yesterday.'" },
            { heading: "Qeyri-qaydalı feillər", body: "Bəziləri dəyişir: go → went, see → saw, eat → ate, have → had." },
          ],
          tasks: [
            { id: "en4-past-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'play' feilinin keçmiş forması?", options: ["played", "playd", "plaied", "playing"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'watch' feilinin keçmiş forması?", options: ["watched", "watchd", "watch", "watching"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'help' feilinin keçmiş forması?", options: ["helped", "helpd", "holp", "helping"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "Qaydalı feillərə keçmişdə hansı şəkilçi əlavə olunur?", options: ["-ed", "-ing", "-s", "-er"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'go' feilinin keçmiş forması?", options: ["went", "goed", "gone", "going"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'see' feilinin keçmiş forması?", options: ["saw", "seed", "seen", "sawing"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'eat' feilinin keçmiş forması?", options: ["ate", "eated", "eaten", "eating"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'have' feilinin keçmiş forması?", options: ["had", "haved", "has", "having"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t9", type: "multiple_choice", prompt: "'I played football.' nə deməkdir?", options: ["Futbol oynadım.", "Futbol oynayıram.", "Futbol oynayacağam.", "Futbolu sevirəm."], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'We ___ TV yesterday.' (baxdıq)", options: ["watched", "watch", "watching", "watches"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'She ___ to school.' (getdi)", options: ["went", "goed", "go", "going"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t12", type: "fill_blank", prompt: "'open' feilinin keçmiş formasını yaz.", accepted: ["opened"], xp: 10 },
            { id: "en4-past-rule-t13", type: "fill_blank", prompt: "'clean' feilinin keçmiş formasını yaz.", accepted: ["cleaned"], xp: 10 },
            { id: "en4-past-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ play.' (oynamadım)", options: ["didn't", "wasn't", "don't", "not"], correctIndex: 0, xp: 10 },
            { id: "en4-past-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'They ___ a film.' (baxdılar)", options: ["watched", "watch", "watching", "watches"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en4-past-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'study' feilinin keçmiş forması?", options: ["studied", "studyed", "studed", "studying"], correctIndex: 0, xp: 15 },
            { id: "en4-past-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'drink' feilinin keçmiş forması?", options: ["drank", "drinked", "drunk", "drinking"], correctIndex: 0, xp: 15 },
            { id: "en4-past-rule-b3", type: "multiple_choice", prompt: "'She didn't come.' nə deməkdir?", options: ["O gəlmədi.", "O gəldi.", "O gəlir.", "O gələcək."], correctIndex: 0, xp: 15 },
            { id: "en4-past-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you play football?' (oynadın?)", options: ["Did", "Do", "Was", "Are"], correctIndex: 0, xp: 15 },
            { id: "en4-past-rule-b5", type: "fill_blank", prompt: "'want' feilinin keçmiş formasını yaz.", accepted: ["wanted"], xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 4. There is / there are ═══════════════
    {
      id: "en4-there",
      title: "There is / there are (var)",
      description: "Bir şeyin mövcudluğunu bildirmək: There is a book. There are books.",
      lessons: [
        {
          id: "en4-there-rule",
          title: "Qayda: there is / there are",
          intro: "There is (tək), There are (cəm).",
          sections: [
            { heading: "there is / are", body: "There is + tək isim: There is a cat. (Bir pişik var.) There are + cəm isim: There are three cats. (Üç pişik var.)" },
            { heading: "İnkar", body: "There isn't / There aren't: There isn't a dog. There aren't any books." },
          ],
          tasks: [
            { id: "en4-there-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a book on the table.' (tək)", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'There ___ three cats.' (cəm)", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "Tək isimlə hansı işlənir?", options: ["there is", "there are", "there am", "there be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "Cəm isimlə hansı işlənir?", options: ["there are", "there is", "there am", "there be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t5", type: "multiple_choice", prompt: "'There is a dog.' nə deməkdir?", options: ["Bir it var.", "İt yoxdur.", "İtlər var.", "İt gəldi."], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t6", type: "multiple_choice", prompt: "'There are five apples.' nə deməkdir?", options: ["Beş alma var.", "Bir alma var.", "Alma yoxdur.", "Alma aldım."], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'There ___ many students.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a pen in my bag.'", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'There ___ a cat.' (yoxdur)", options: ["isn't", "aren't", "am not", "not"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'There ___ any books.' (yoxdur, cəm)", options: ["aren't", "isn't", "am not", "not"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'There ___ two windows.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a school near my house.'", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t13", type: "multiple_choice", prompt: "'There are books on the shelf.' nə deməkdir?", options: ["Rəfdə kitablar var.", "Rəfdə kitab yoxdur.", "Rəf boşdur.", "Kitab aldım."], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a big tree in the garden.'", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 10 },
            { id: "en4-there-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'There ___ four seasons.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en4-there-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ there a park here?'", options: ["Is", "Are", "Am", "Do"], correctIndex: 0, xp: 15 },
            { id: "en4-there-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ there any apples?'", options: ["Are", "Is", "Am", "Do"], correctIndex: 0, xp: 15 },
            { id: "en4-there-rule-b3", type: "multiple_choice", prompt: "'There isn't any milk.' nə deməkdir?", options: ["Heç süd yoxdur.", "Süd var.", "Çoxlu süd var.", "Süd aldım."], correctIndex: 0, xp: 15 },
            { id: "en4-there-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'There ___ some water in the glass.'", options: ["is", "are", "am", "be"], correctIndex: 0, xp: 15 },
            { id: "en4-there-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'There ___ a lot of people.'", options: ["are", "is", "am", "be"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 5. Comparatives ═══════════════
    {
      id: "en4-comp",
      title: "Müqayisə (bigger, taller)",
      description: "Sifətlərin müqayisə dərəcəsi: -er + than.",
      lessons: [
        {
          id: "en4-comp-rule",
          title: "Qayda: comparatives",
          intro: "Qısa sifət + -er + than: taller than, bigger than.",
          sections: [
            { heading: "Qayda", body: "Qısa sifətə -er əlavə olunur: tall → taller, big → bigger, small → smaller. Müqayisədə 'than' işlənir: 'Ali is taller than Tom.'" },
          ],
          tasks: [
            { id: "en4-comp-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'tall' sözünün müqayisə forması?", options: ["taller", "tallest", "more tall", "talest"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'small' sözünün müqayisə forması?", options: ["smaller", "smallest", "more small", "smalest"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'big' sözünün müqayisə forması?", options: ["bigger", "biger", "more big", "biggest"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'old' sözünün müqayisə forması?", options: ["older", "oldest", "more old", "olderer"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "Müqayisədə hansı söz işlənir?", options: ["than", "then", "that", "as"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'Ali is ___ than Tom.' (uca)", options: ["taller", "tall", "tallest", "more tall"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'An elephant is ___ than a cat.' (böyük)", options: ["bigger", "big", "biggest", "more big"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'fast' sözünün müqayisə forması?", options: ["faster", "fastest", "more fast", "fasterer"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t9", type: "multiple_choice", prompt: "'A car is faster than a bike.' nə deməkdir?", options: ["Maşın velosipeddən sürətlidir.", "Velosiped sürətlidir.", "Maşın yavaşdır.", "İkisi eynidir."], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'young' sözünün müqayisə forması?", options: ["younger", "youngest", "more young", "youngerer"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'long' sözünün müqayisə forması?", options: ["longer", "longest", "more long", "longerer"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'short' sözünün müqayisə forması?", options: ["shorter", "shortest", "more short", "shorterer"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t13", type: "multiple_choice", prompt: "'Winter is colder than summer.' nə deməkdir?", options: ["Qış yaydan soyuqdur.", "Yay soyuqdur.", "Qış istidir.", "İkisi eynidir."], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'This box is ___ than that one.' (ağır)", options: ["heavier", "heavy", "heaviest", "more heavy"], correctIndex: 0, xp: 10 },
            { id: "en4-comp-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'My bag is ___ than yours.' (kiçik)", options: ["smaller", "small", "smallest", "more small"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en4-comp-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'good' sözünün müqayisə forması (qeyri-qaydalı)?", options: ["better", "gooder", "more good", "best"], correctIndex: 0, xp: 15 },
            { id: "en4-comp-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'happy' sözünün müqayisə forması?", options: ["happier", "happyer", "more happy", "happiest"], correctIndex: 0, xp: 15 },
            { id: "en4-comp-rule-b3", type: "multiple_choice", prompt: "'A mouse is smaller than a cat.' nə deməkdir?", options: ["Siçan pişikdən kiçikdir.", "Pişik kiçikdir.", "Siçan böyükdür.", "İkisi eynidir."], correctIndex: 0, xp: 15 },
            { id: "en4-comp-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'nice' sözünün müqayisə forması?", options: ["nicer", "niceer", "more nice", "nicest"], correctIndex: 0, xp: 15 },
            { id: "en4-comp-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'hot' sözünün müqayisə forması?", options: ["hotter", "hoter", "more hot", "hottest"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 6. Sual sözləri və lüğət ═══════════════
    {
      id: "en4-questions",
      title: "Sual sözləri və lüğət",
      description: "Sual sözləri (what/where/when/who) və tematik lüğət.",
      lessons: [
        {
          id: "en4-questions-vocab",
          title: "Question words & vocab",
          intro: "Sual sözlərini və yeni sözləri öyrənək.",
          sections: [
            { heading: "Sual sözləri", body: "what — nə, where — harada, when — nə vaxt, who — kim, how — necə, why — niyə, how many — neçə." },
            { heading: "Lüğət", body: "hobby — hobbi, sport — idman, weekend — həftəsonu, holiday — bayram/tətil, friend — dost." },
          ],
          tasks: [
            { id: "en4-questions-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'what' nə deməkdir?", options: ["nə", "harada", "kim", "nə vaxt"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'where' nə deməkdir?", options: ["harada", "nə", "kim", "necə"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'when' nə deməkdir?", options: ["nə vaxt", "harada", "kim", "niyə"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'who' nə deməkdir?", options: ["kim", "nə", "harada", "necə"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'how' nə deməkdir?", options: ["necə", "nə", "kim", "niyə"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'why' nə deməkdir?", options: ["niyə", "necə", "kim", "harada"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'___ is your name?' (nə)", options: ["What", "Where", "Who", "When"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'___ do you live?' (harada)", options: ["Where", "What", "Who", "When"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'___ is your teacher?' (kim)", options: ["Who", "What", "Where", "How"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'how many' nə deməkdir?", options: ["neçə", "necə", "nə vaxt", "niyə"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'hobby' nə deməkdir?", options: ["hobbi/məşğuliyyət", "idman", "bayram", "dost"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'weekend' nə deməkdir?", options: ["həftəsonu", "bayram", "gün", "ay"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'friend' nə deməkdir?", options: ["dost", "müəllim", "qonşu", "qardaş"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'holiday' nə deməkdir?", options: ["bayram/tətil", "iş günü", "səhər", "gecə"], correctIndex: 0, xp: 10 },
            { id: "en4-questions-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'sport' nə deməkdir?", options: ["idman", "hobbi", "oyun", "musiqi"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en4-questions-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'___ are you sad?' (niyə)", options: ["Why", "What", "Who", "Where"], correctIndex: 0, xp: 15 },
            { id: "en4-questions-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'___ many books do you have?' (neçə)", options: ["How", "What", "Who", "When"], correctIndex: 0, xp: 15 },
            { id: "en4-questions-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'What is your favourite ___?' (hobbi)", options: ["hobby", "friend", "weekend", "holiday"], correctIndex: 0, xp: 15 },
            { id: "en4-questions-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'which' nə deməkdir?", options: ["hansı", "kim", "nə vaxt", "niyə"], correctIndex: 0, xp: 15 },
            { id: "en4-questions-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'On the ___ I play with friends.' (həftəsonu)", options: ["weekend", "hobby", "sport", "holiday"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
  ],
};
