// İngilis dili — 1-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Salamlaşma  2) Ədədlər 1-10  3) Rənglər  4) Heyvanlar  5) Ailə  6) Məktəb və bədən.
// 1-ci sinif üçün suallar ÇOX SADƏ: şəkil-söz tanıma (emoji) + dinləmə. Oxu/qrammatika YOX.
// id prefiksi en1-*. speakOptions ilə uşaq İngiliscə sözü eşidir.

import type { Subject } from "../types";

export const english1: Subject = {
  slug: "ingilis-dili-1",
  name: "İngilis dili",
  grade: 1,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Salamlaşma ═══════════════
    {
      id: "en1-hello",
      title: "Salamlaşma və tanışlıq",
      description: "Salam sözləri, dinləmə və məşq.",
      lessons: [
        {
          id: "en1-greetings-vocab",
          title: "Salam sözləri",
          intro: "İngiliscə salamlaşmağı öyrənək.",
          sections: [
            { heading: "Sözlər", body: "hello — salam, goodbye — sağ ol/əlvida, thank you — təşəkkür, please — zəhmət olmasa, yes — bəli, no — xeyr." },
          ],
          tasks: [
            { id: "en1-greetings-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'salam' İngiliscə necədir?", options: ["hello", "goodbye", "thank you", "please"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'sağ ol / əlvida' İngiliscə necədir?", options: ["goodbye", "hello", "yes", "no"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'təşəkkür' İngiliscə necədir?", options: ["thank you", "please", "hello", "no"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'bəli' İngiliscə necədir?", options: ["yes", "no", "hello", "please"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'xeyr' İngiliscə necədir?", options: ["no", "yes", "goodbye", "please"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'zəhmət olmasa' İngiliscə necədir?", options: ["please", "thank you", "hello", "yes"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t7", type: "multiple_choice", prompt: "'hello' nə deməkdir?", options: ["salam", "sağ ol", "təşəkkür", "xeyr"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t8", type: "multiple_choice", prompt: "'thank you' nə deməkdir?", options: ["təşəkkür", "salam", "bəli", "xeyr"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t9", type: "multiple_choice", prompt: "'yes' nə deməkdir?", options: ["bəli", "xeyr", "salam", "sağ ol"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t10", type: "multiple_choice", prompt: "'no' nə deməkdir?", options: ["xeyr", "bəli", "salam", "təşəkkür"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t11", type: "multiple_choice", prompt: "'goodbye' nə deməkdir?", options: ["sağ ol / əlvida", "salam", "bəli", "zəhmət olmasa"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t12", type: "multiple_choice", prompt: "'please' nə deməkdir?", options: ["zəhmət olmasa", "təşəkkür", "salam", "xeyr"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "Kimsə sənə kömək etdi. Nə deyərsən?", options: ["thank you", "goodbye", "no", "hello"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "Səhər dostunu görəndə nə deyərsən?", options: ["hello", "goodbye", "no", "thank you"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "Evə gedəndə nə deyərsən?", options: ["goodbye", "hello", "yes", "please"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en1-greetings-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'good morning' nə deməkdir?", options: ["sabahın xeyir", "gecən xeyrə", "sağ ol", "salam"], correctIndex: 0, xp: 15 },
            { id: "en1-greetings-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'good night' nə deməkdir?", options: ["gecən xeyrə", "sabahın xeyir", "salam", "təşəkkür"], correctIndex: 0, xp: 15 },
            { id: "en1-greetings-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'sorry' nə deməkdir?", options: ["üzr istəyirəm", "təşəkkür", "salam", "bəli"], correctIndex: 0, xp: 15 },
            { id: "en1-greetings-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'What is your name?' nə deməkdir?", options: ["Adın nədir?", "Neçə yaşın var?", "Necəsən?", "Salam"], correctIndex: 0, xp: 15 },
            { id: "en1-greetings-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'How are you?' nə deməkdir?", options: ["Necəsən?", "Adın nədir?", "Sağ ol", "Salam"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-greetings-listen",
          title: "Dinləmə: salamlar",
          intro: "Sözü dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə sözü dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en1-greetings-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Hello", options: ["Salam", "Sağ ol", "Təşəkkür", "Xeyr"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Goodbye", options: ["Sağ ol / əlvida", "Salam", "Bəli", "Zəhmət olmasa"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Thank you", options: ["Təşəkkür", "Salam", "Xeyr", "Bəli"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Yes", options: ["Bəli", "Xeyr", "Salam", "Sağ ol"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "No", options: ["Xeyr", "Bəli", "Salam", "Təşəkkür"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Please", options: ["Zəhmət olmasa", "Təşəkkür", "Salam", "Xeyr"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Good morning", options: ["Sabahın xeyir", "Gecən xeyrə", "Salam", "Sağ ol"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Good night", options: ["Gecən xeyrə", "Sabahın xeyir", "Salam", "Təşəkkür"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Sorry", options: ["Üzr istəyirəm", "Təşəkkür", "Salam", "Bəli"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Welcome", options: ["Xoş gəldin", "Sağ ol", "Salam", "Xeyr"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Hi", options: ["Salam", "Sağ ol", "Bəli", "Xeyr"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "See you", options: ["Görüşərik", "Salam", "Təşəkkür", "Bəli"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "My name is Ali", options: ["Mənim adım Alidir", "Sənin adın nədir", "Salam Ali", "Sağ ol Ali"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "How are you?", options: ["Necəsən?", "Adın nədir?", "Salam", "Sağ ol"], correctIndex: 0, xp: 10 },
            { id: "en1-greetings-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am fine", options: ["Mən yaxşıyam", "Mən pisəm", "Salam", "Sağ ol"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en1-greetings-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Nice to meet you", options: ["Tanış olmağıma şadam", "Sağ ol", "Salam", "Necəsən"], correctIndex: 0, xp: 15 },
            { id: "en1-greetings-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Good afternoon", options: ["Günortan xeyir", "Gecən xeyrə", "Sabahın xeyir", "Salam"], correctIndex: 0, xp: 15 },
            { id: "en1-greetings-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "You are welcome", options: ["Dəyməz / buyur", "Sağ ol", "Salam", "Xeyr"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-hello-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-hello-mesq",
          title: "Məşq",
          intro: "Salam sözlərini birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Hello — Salam · Good morning — Sabahın xeyir · Goodbye — Sağ ol/Əlvida · Thank you — Təşəkkür · My name is... — Mənim adım..." },
          ],
          tasks: [
            { id: "en1-hello-mesq-t1", type: "multiple_choice", prompt: "'Hello' nə deməkdir?", options: ["Salam", "Sağ ol", "Təşəkkür", "Xeyr"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t2", type: "multiple_choice", prompt: "'Goodbye' nə deməkdir?", options: ["Əlvida", "Salam", "Bəli", "Zəhmət olmasa"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t3", type: "multiple_choice", prompt: "'Thank you' nə deməkdir?", options: ["Təşəkkür edirəm", "Salam", "Əlvida", "Bağışlayın"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t4", type: "multiple_choice", speakOptions: true, prompt: "Səhər necə salamlaşırsan?", options: ["Good morning", "Good night", "Goodbye", "Thank you"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t5", type: "multiple_choice", speakOptions: true, prompt: "Gecə yatmağa gedəndə nə deyirsən?", options: ["Good night", "Good morning", "Hello", "Please"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t6", type: "multiple_choice", prompt: "'What is your name?' nə soruşur?", options: ["Adını", "Yaşını", "Rəngini", "Evini"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t7", type: "multiple_choice", speakOptions: true, prompt: "«Mənim adım Ayan» — ingiliscə necə deyilir?", options: ["My name is Ayan", "Your name is Ayan", "I am name Ayan", "Name my Ayan"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Hello, my name is Tom.", options: ["Salam, mənim adım Tomdur.", "Sağ ol, Tom.", "Tom haradadır?", "Salam Tom, necəsən?"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Good morning!", options: ["Sabahın xeyir!", "Gecən xeyrə!", "Sağ ol!", "Salam!"], correctIndex: 0, xp: 10 },
            { id: "en1-hello-mesq-t10", type: "multiple_choice", prompt: "'Please' nə deməkdir?", options: ["Zəhmət olmasa", "Təşəkkür", "Salam", "Bağışla"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "en1-hello-mesq-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "How are you?", options: ["Necəsən?", "Adın nədir?", "Haradasan?", "Neçə yaşın var?"], correctIndex: 0, xp: 15 },
            { id: "en1-hello-mesq-b2", type: "multiple_choice", speakOptions: true, prompt: "«Necəsən?» sualına cavab hansıdır?", options: ["I am fine", "My name is Ali", "Good morning", "Thank you"], correctIndex: 0, xp: 15 },
            { id: "en1-hello-mesq-b3", type: "fill_blank", prompt: "'Salam' — ingiliscə yaz (bir söz).", accepted: ["hello", "Hello", "hi", "Hi"], xp: 15 },
            { id: "en1-hello-mesq-b4", type: "multiple_choice", speakOptions: true, prompt: "Ayrılanda nə deyirsən?", options: ["Goodbye", "Hello", "Good morning", "Please"], correctIndex: 0, xp: 15 },
            { id: "en1-hello-mesq-b5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Thank you very much.", options: ["Çox sağ ol.", "Salam.", "Zəhmət olmasa.", "Görüşərik."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-hello-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "en1-numcolor",
      title: "Ədədlər və rənglər",
      description: "1-10 ədədləri, rənglər və məşq.",
      lessons: [
        {
          id: "en1-numbers-vocab",
          title: "Numbers 1-10",
          intro: "İngiliscə saymağı öyrənək.",
          sections: [
            { heading: "Sözlər", body: "one — 1, two — 2, three — 3, four — 4, five — 5, six — 6, seven — 7, eight — 8, nine — 9, ten — 10." },
          ],
          tasks: [
            { id: "en1-numbers-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'1' İngiliscə necədir?", options: ["one", "two", "three", "ten"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'2' İngiliscə necədir?", options: ["two", "three", "one", "four"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'3' İngiliscə necədir?", options: ["three", "two", "five", "six"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'4' İngiliscə necədir?", options: ["four", "five", "one", "nine"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'5' İngiliscə necədir?", options: ["five", "four", "six", "two"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'6' İngiliscə necədir?", options: ["six", "seven", "five", "eight"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'7' İngiliscə necədir?", options: ["seven", "six", "eight", "nine"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'8' İngiliscə necədir?", options: ["eight", "nine", "seven", "ten"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'9' İngiliscə necədir?", options: ["nine", "eight", "ten", "six"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'10' İngiliscə necədir?", options: ["ten", "nine", "one", "two"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t11", type: "multiple_choice", prompt: "'three' hansı ədəddir?", options: ["3", "2", "4", "5"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t12", type: "multiple_choice", prompt: "'seven' hansı ədəddir?", options: ["7", "6", "8", "9"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t13", type: "multiple_choice", prompt: "'ten' hansı ədəddir?", options: ["10", "1", "9", "2"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t14", type: "multiple_choice", prompt: "🍎🍎 — İngiliscə neçədir?", options: ["two", "one", "three", "four"], correctIndex: 0, xp: 10 },
            { id: "en1-numbers-vocab-t15", type: "multiple_choice", prompt: "⭐⭐⭐⭐⭐ — İngiliscə neçədir?", options: ["five", "four", "six", "three"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en1-numbers-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'one' + 'one' = ?", options: ["two", "one", "three", "four"], correctIndex: 0, xp: 15 },
            { id: "en1-numbers-vocab-b2", type: "multiple_choice", prompt: "🐟🐟🐟 — İngiliscə neçədir?", options: ["three", "two", "four", "five"], correctIndex: 0, xp: 15 },
            { id: "en1-numbers-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'eleven' hansı ədəddir?", options: ["11", "1", "12", "10"], correctIndex: 0, xp: 15 },
            { id: "en1-numbers-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'twelve' hansı ədəddir?", options: ["12", "2", "20", "10"], correctIndex: 0, xp: 15 },
            { id: "en1-numbers-vocab-b5", type: "multiple_choice", prompt: "'nine' hansı ədəddir?", options: ["9", "8", "7", "10"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-colors-vocab",
          title: "Colours",
          intro: "Rəngləri İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "red — qırmızı, blue — mavi, green — yaşıl, yellow — sarı, black — qara, white — ağ, orange — narıncı, pink — çəhrayı." },
          ],
          tasks: [
            { id: "en1-colors-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'qırmızı' İngiliscə necədir?", options: ["red", "blue", "green", "black"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'mavi' İngiliscə necədir?", options: ["blue", "red", "yellow", "white"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'yaşıl' İngiliscə necədir?", options: ["green", "blue", "red", "pink"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'sarı' İngiliscə necədir?", options: ["yellow", "green", "orange", "white"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'qara' İngiliscə necədir?", options: ["black", "white", "blue", "red"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'ağ' İngiliscə necədir?", options: ["white", "black", "green", "yellow"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'narıncı' İngiliscə necədir?", options: ["orange", "pink", "red", "yellow"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'çəhrayı' İngiliscə necədir?", options: ["pink", "orange", "red", "blue"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t9", type: "multiple_choice", prompt: "'red' nə rəngdir?", options: ["qırmızı", "mavi", "yaşıl", "sarı"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t10", type: "multiple_choice", prompt: "'green' nə rəngdir?", options: ["yaşıl", "qırmızı", "qara", "ağ"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t11", type: "multiple_choice", prompt: "'yellow' nə rəngdir?", options: ["sarı", "mavi", "narıncı", "çəhrayı"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t12", type: "multiple_choice", prompt: "🍎 (alma) çox vaxt hansı rəngdədir?", options: ["red", "blue", "black", "white"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t13", type: "multiple_choice", prompt: "🌿 (ot) hansı rəngdədir?", options: ["green", "red", "yellow", "pink"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t14", type: "multiple_choice", prompt: "☀️ (günəş) çox vaxt hansı rəngdədir?", options: ["yellow", "blue", "black", "green"], correctIndex: 0, xp: 10 },
            { id: "en1-colors-vocab-t15", type: "multiple_choice", prompt: "'blue' nə rəngdir?", options: ["mavi", "qırmızı", "sarı", "qara"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en1-colors-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'brown' nə rəngdir?", options: ["qəhvəyi", "mavi", "sarı", "yaşıl"], correctIndex: 0, xp: 15 },
            { id: "en1-colors-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'purple' nə rəngdir?", options: ["bənövşəyi", "narıncı", "qırmızı", "ağ"], correctIndex: 0, xp: 15 },
            { id: "en1-colors-vocab-b3", type: "multiple_choice", prompt: "❄️ (qar) hansı rəngdədir?", options: ["white", "black", "red", "green"], correctIndex: 0, xp: 15 },
            { id: "en1-colors-vocab-b4", type: "multiple_choice", prompt: "🌊 (dəniz) çox vaxt hansı rəngdədir?", options: ["blue", "red", "yellow", "pink"], correctIndex: 0, xp: 15 },
            { id: "en1-colors-vocab-b5", type: "multiple_choice", prompt: "'orange' nə rəngdir?", options: ["narıncı", "yaşıl", "mavi", "qara"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-numcolor-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-numcolor-mesq",
          title: "Məşq",
          intro: "Ədədləri və rəngləri birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "one, two, three, four, five, six, seven, eight, nine, ten · red (qırmızı), blue (mavi), green (yaşıl), yellow (sarı), black (qara), white (ağ)" },
          ],
          tasks: [
            { id: "en1-numcolor-mesq-t1", type: "multiple_choice", speakOptions: true, prompt: "3 — ingiliscə necədir?", options: ["three", "two", "four", "five"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t2", type: "multiple_choice", speakOptions: true, prompt: "7 — ingiliscə necədir?", options: ["seven", "six", "eight", "nine"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t3", type: "multiple_choice", prompt: "'ten' neçədir?", options: ["10", "2", "9", "3"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t4", type: "multiple_choice", prompt: "'red' nə rəngdir?", options: ["qırmızı", "mavi", "yaşıl", "sarı"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t5", type: "multiple_choice", prompt: "'blue' nə rəngdir?", options: ["mavi", "qırmızı", "qara", "ağ"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t6", type: "multiple_choice", speakOptions: true, prompt: "Yarpaq hansı rəngdədir?", options: ["green", "red", "black", "white"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t7", type: "multiple_choice", speakOptions: true, prompt: "Günəş hansı rəngdədir?", options: ["yellow", "blue", "green", "black"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t8", type: "listening", prompt: "Dinlə: neçədir?", audioText: "five", options: ["5", "4", "9", "1"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t9", type: "listening", prompt: "Dinlə və rəngi seç.", audioText: "This is a red apple.", options: ["Qırmızı alma", "Yaşıl alma", "Sarı alma", "Mavi alma"], correctIndex: 0, xp: 10 },
            { id: "en1-numcolor-mesq-t10", type: "fill_blank", prompt: "'iki' — ingiliscə yaz (bir söz).", accepted: ["two", "Two"], xp: 10 },
          ],
          bonusTasks: [
            { id: "en1-numcolor-mesq-b1", type: "multiple_choice", speakOptions: true, prompt: "one + two = ?", options: ["three", "two", "four", "five"], correctIndex: 0, xp: 15 },
            { id: "en1-numcolor-mesq-b2", type: "listening", prompt: "Dinlə: neçə pişik?", audioText: "I have three cats.", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 15 },
            { id: "en1-numcolor-mesq-b3", type: "fill_blank", prompt: "'qara' — ingiliscə yaz (bir söz).", accepted: ["black", "Black"], xp: 15 },
            { id: "en1-numcolor-mesq-b4", type: "multiple_choice", prompt: "Qar hansı rəngdədir?", options: ["white", "black", "red", "green"], correctIndex: 0, xp: 15 },
            { id: "en1-numcolor-mesq-b5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The sky is blue.", options: ["Göy mavidir.", "Göy yaşıldır.", "Dəniz mavidir.", "Göy qaradır."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-numcolor-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "en1-animals",
      title: "Heyvanlar",
      description: "Heyvan adları, dinləmə və məşq.",
      lessons: [
        {
          id: "en1-animals-vocab",
          title: "Animals",
          intro: "Heyvanları İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "cat — pişik, dog — it, fish — balıq, bird — quş, cow — inək, horse — at, sheep — qoyun, lion — şir, bear — ayı, rabbit — dovşan." },
          ],
          tasks: [
            { id: "en1-animals-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "🐱 İngiliscə necədir?", options: ["cat", "dog", "fish", "bird"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "🐶 İngiliscə necədir?", options: ["dog", "cat", "cow", "horse"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "🐟 İngiliscə necədir?", options: ["fish", "bird", "cat", "lion"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "🐦 İngiliscə necədir?", options: ["bird", "fish", "dog", "bear"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "🐮 İngiliscə necədir?", options: ["cow", "horse", "sheep", "cat"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "🐴 İngiliscə necədir?", options: ["horse", "cow", "dog", "lion"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "🦁 İngiliscə necədir?", options: ["lion", "bear", "cat", "dog"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "🐻 İngiliscə necədir?", options: ["bear", "lion", "rabbit", "cow"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "🐰 İngiliscə necədir?", options: ["rabbit", "bear", "cat", "fish"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t10", type: "multiple_choice", prompt: "'cat' nə deməkdir?", options: ["pişik", "it", "quş", "balıq"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t11", type: "multiple_choice", prompt: "'dog' nə deməkdir?", options: ["it", "pişik", "inək", "at"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t12", type: "multiple_choice", prompt: "'fish' nə deməkdir?", options: ["balıq", "quş", "pişik", "şir"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t13", type: "multiple_choice", prompt: "'lion' nə deməkdir?", options: ["şir", "ayı", "it", "at"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t14", type: "multiple_choice", prompt: "'sheep' nə deməkdir?", options: ["qoyun", "inək", "at", "dovşan"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-vocab-t15", type: "multiple_choice", prompt: "'bird' nə deməkdir?", options: ["quş", "balıq", "pişik", "ayı"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en1-animals-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "🐘 İngiliscə necədir?", options: ["elephant", "lion", "bear", "horse"], correctIndex: 0, xp: 15 },
            { id: "en1-animals-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "🐒 İngiliscə necədir?", options: ["monkey", "bear", "cat", "dog"], correctIndex: 0, xp: 15 },
            { id: "en1-animals-vocab-b3", type: "multiple_choice", prompt: "'elephant' nə deməkdir?", options: ["fil", "şir", "ayı", "at"], correctIndex: 0, xp: 15 },
            { id: "en1-animals-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "🐭 İngiliscə necədir?", options: ["mouse", "cat", "rabbit", "bird"], correctIndex: 0, xp: 15 },
            { id: "en1-animals-vocab-b5", type: "multiple_choice", prompt: "'horse' nə deməkdir?", options: ["at", "inək", "qoyun", "it"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-animals-listen",
          title: "Dinləmə: heyvanlar",
          intro: "Sözü dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə heyvan adını dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en1-animals-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "cat", options: ["pişik", "it", "balıq", "quş"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "dog", options: ["it", "pişik", "inək", "at"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "fish", options: ["balıq", "quş", "şir", "ayı"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "bird", options: ["quş", "balıq", "pişik", "at"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "cow", options: ["inək", "at", "qoyun", "it"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "horse", options: ["at", "inək", "şir", "dovşan"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "lion", options: ["şir", "ayı", "pişik", "it"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "bear", options: ["ayı", "şir", "dovşan", "inək"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "rabbit", options: ["dovşan", "ayı", "pişik", "quş"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "sheep", options: ["qoyun", "inək", "at", "it"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "elephant", options: ["fil", "şir", "ayı", "at"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "monkey", options: ["meymun", "ayı", "pişik", "it"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "mouse", options: ["siçan", "pişik", "quş", "balıq"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "duck", options: ["ördək", "quş", "balıq", "toyuq"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The cat is small", options: ["Pişik kiçikdir", "Pişik böyükdür", "İt kiçikdir", "Pişik qaçır"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en1-animals-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The dog is big", options: ["İt böyükdür", "İt kiçikdir", "Pişik böyükdür", "İt qaçır"], correctIndex: 0, xp: 15 },
            { id: "en1-animals-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I have a cat", options: ["Mənim pişiyim var", "Mənim itim var", "Pişik gəldi", "Pişik yoxdur"], correctIndex: 0, xp: 15 },
            { id: "en1-animals-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "chicken", options: ["toyuq", "ördək", "quş", "qaz"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-animals-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-animals-mesq",
          title: "Məşq",
          intro: "Heyvan adlarını məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "cat — pişik · dog — it · bird — quş · fish — balıq · cow — inək · horse — at · sheep — qoyun · rabbit — dovşan" },
          ],
          tasks: [
            { id: "en1-animals-mesq-t1", type: "multiple_choice", prompt: "'cat' nə deməkdir?", options: ["pişik", "it", "quş", "balıq"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t2", type: "multiple_choice", prompt: "'dog' nə deməkdir?", options: ["it", "pişik", "at", "inək"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t3", type: "multiple_choice", prompt: "'bird' nə deməkdir?", options: ["quş", "balıq", "dovşan", "qoyun"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t4", type: "multiple_choice", prompt: "'fish' nə deməkdir?", options: ["balıq", "quş", "pişik", "at"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t5", type: "multiple_choice", speakOptions: true, prompt: "Süd verən heyvan hansıdır?", options: ["cow", "cat", "bird", "fish"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t6", type: "multiple_choice", speakOptions: true, prompt: "Suda yaşayan heyvan hansıdır?", options: ["fish", "horse", "sheep", "dog"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t7", type: "multiple_choice", speakOptions: true, prompt: "Uzun qulaqlı heyvan hansıdır?", options: ["rabbit", "cow", "fish", "bird"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t8", type: "listening", prompt: "Dinlə və heyvanı seç.", audioText: "I have a big dog.", options: ["it", "pişik", "quş", "at"], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The cat is sleeping.", options: ["Pişik yatır.", "İt yatır.", "Pişik oynayır.", "Pişik yeyir."], correctIndex: 0, xp: 10 },
            { id: "en1-animals-mesq-t10", type: "fill_blank", prompt: "'quş' — ingiliscə yaz (bir söz).", accepted: ["bird", "Bird"], xp: 10 },
          ],
          bonusTasks: [
            { id: "en1-animals-mesq-b1", type: "multiple_choice", speakOptions: true, prompt: "Hansı heyvan uça bilir?", options: ["bird", "fish", "cow", "sheep"], correctIndex: 0, xp: 15 },
            { id: "en1-animals-mesq-b2", type: "listening", prompt: "Dinlə: neçə pişik?", audioText: "There are two cats.", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 15 },
            { id: "en1-animals-mesq-b3", type: "fill_blank", prompt: "'balıq' — ingiliscə yaz (bir söz).", accepted: ["fish", "Fish"], xp: 15 },
            { id: "en1-animals-mesq-b4", type: "multiple_choice", prompt: "«I like animals» nə deməkdir?", options: ["Mən heyvanları sevirəm.", "Heyvanlar məni sevir.", "Heyvanım var.", "Heyvanlar böyükdür."], correctIndex: 0, xp: 15 },
            { id: "en1-animals-mesq-b5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The dog is running.", options: ["İt qaçır.", "Pişik qaçır.", "İt yatır.", "İtlər qaçır."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-animals-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "en1-famschool",
      title: "Ailə və məktəb",
      description: "Ailə üzvləri, məktəb əşyaları və məşq.",
      lessons: [
        {
          id: "en1-family-vocab",
          title: "Family",
          intro: "Ailə üzvlərini İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "mother — ana, father — ata, sister — bacı, brother — qardaş, grandmother — nənə, grandfather — baba, baby — körpə, family — ailə." },
          ],
          tasks: [
            { id: "en1-family-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'ana' İngiliscə necədir?", options: ["mother", "father", "sister", "brother"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'ata' İngiliscə necədir?", options: ["father", "mother", "brother", "baby"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'bacı' İngiliscə necədir?", options: ["sister", "brother", "mother", "baby"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'qardaş' İngiliscə necədir?", options: ["brother", "sister", "father", "family"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'nənə' İngiliscə necədir?", options: ["grandmother", "grandfather", "mother", "sister"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'baba' İngiliscə necədir?", options: ["grandfather", "grandmother", "father", "brother"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'körpə' İngiliscə necədir?", options: ["baby", "sister", "brother", "mother"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'ailə' İngiliscə necədir?", options: ["family", "mother", "father", "baby"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t9", type: "multiple_choice", prompt: "'mother' nə deməkdir?", options: ["ana", "ata", "bacı", "qardaş"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t10", type: "multiple_choice", prompt: "'father' nə deməkdir?", options: ["ata", "ana", "baba", "körpə"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t11", type: "multiple_choice", prompt: "'sister' nə deməkdir?", options: ["bacı", "qardaş", "ana", "nənə"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t12", type: "multiple_choice", prompt: "'brother' nə deməkdir?", options: ["qardaş", "bacı", "ata", "baba"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t13", type: "multiple_choice", prompt: "'grandmother' nə deməkdir?", options: ["nənə", "baba", "ana", "bacı"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t14", type: "multiple_choice", prompt: "'family' nə deməkdir?", options: ["ailə", "ana", "körpə", "qardaş"], correctIndex: 0, xp: 10 },
            { id: "en1-family-vocab-t15", type: "multiple_choice", prompt: "'grandfather' nə deməkdir?", options: ["baba", "nənə", "ata", "qardaş"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en1-family-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'This is my mother.' nə deməkdir?", options: ["Bu mənim anamdır.", "Bu mənim atamdır.", "Bu mənim bacımdır.", "Bu ailəmdir."], correctIndex: 0, xp: 15 },
            { id: "en1-family-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'I love my family.' nə deməkdir?", options: ["Ailəmi sevirəm.", "Anamı sevirəm.", "Ailəm böyükdür.", "Bu ailəmdir."], correctIndex: 0, xp: 15 },
            { id: "en1-family-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'aunt' nə deməkdir?", options: ["xala/bibi", "əmi/dayı", "nənə", "baba"], correctIndex: 0, xp: 15 },
            { id: "en1-family-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'uncle' nə deməkdir?", options: ["əmi/dayı", "xala/bibi", "baba", "qardaş"], correctIndex: 0, xp: 15 },
            { id: "en1-family-vocab-b5", type: "multiple_choice", prompt: "'baby' nə deməkdir?", options: ["körpə", "bacı", "ana", "nənə"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-school-vocab",
          title: "School things",
          intro: "Məktəb əşyalarını İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "book — kitab, pen — qələm, pencil — karandaş, bag — çanta, desk — parta, teacher — müəllim, school — məktəb, chair — stul." },
          ],
          tasks: [
            { id: "en1-school-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'kitab' İngiliscə necədir?", options: ["book", "pen", "bag", "desk"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'qələm' İngiliscə necədir?", options: ["pen", "book", "chair", "school"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'karandaş' İngiliscə necədir?", options: ["pencil", "pen", "bag", "book"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'çanta' İngiliscə necədir?", options: ["bag", "book", "desk", "pen"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'müəllim' İngiliscə necədir?", options: ["teacher", "school", "book", "chair"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'məktəb' İngiliscə necədir?", options: ["school", "teacher", "desk", "bag"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'stul' İngiliscə necədir?", options: ["chair", "desk", "book", "pen"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t8", type: "multiple_choice", prompt: "'book' nə deməkdir?", options: ["kitab", "qələm", "çanta", "parta"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t9", type: "multiple_choice", prompt: "'pen' nə deməkdir?", options: ["qələm", "kitab", "stul", "məktəb"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t10", type: "multiple_choice", prompt: "'teacher' nə deməkdir?", options: ["müəllim", "şagird", "kitab", "məktəb"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t11", type: "multiple_choice", prompt: "'bag' nə deməkdir?", options: ["çanta", "kitab", "qələm", "stul"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'baş' (bədən) İngiliscə necədir?", options: ["head", "hand", "eye", "foot"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'əl' İngiliscə necədir?", options: ["hand", "head", "leg", "eye"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'göz' İngiliscə necədir?", options: ["eye", "ear", "nose", "hand"], correctIndex: 0, xp: 10 },
            { id: "en1-school-vocab-t15", type: "multiple_choice", prompt: "'school' nə deməkdir?", options: ["məktəb", "müəllim", "kitab", "çanta"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en1-school-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'ayaq' İngiliscə necədir?", options: ["leg / foot", "hand", "head", "eye"], correctIndex: 0, xp: 15 },
            { id: "en1-school-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'burun' İngiliscə necədir?", options: ["nose", "ear", "eye", "mouth"], correctIndex: 0, xp: 15 },
            { id: "en1-school-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'ağız' İngiliscə necədir?", options: ["mouth", "nose", "ear", "hand"], correctIndex: 0, xp: 15 },
            { id: "en1-school-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'qulaq' İngiliscə necədir?", options: ["ear", "eye", "nose", "head"], correctIndex: 0, xp: 15 },
            { id: "en1-school-vocab-b5", type: "multiple_choice", prompt: "'pencil' nə deməkdir?", options: ["karandaş", "qələm", "kitab", "çanta"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-famschool-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en1-famschool-mesq",
          title: "Məşq",
          intro: "Ailə və məktəb sözlərini məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "mother — ana · father — ata · sister — bacı · brother — qardaş · book — kitab · pen — qələm · bag — çanta · desk — parta" },
          ],
          tasks: [
            { id: "en1-famschool-mesq-t1", type: "multiple_choice", prompt: "'mother' nə deməkdir?", options: ["ana", "ata", "bacı", "qardaş"], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t2", type: "multiple_choice", prompt: "'father' nə deməkdir?", options: ["ata", "ana", "baba", "qardaş"], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t3", type: "multiple_choice", prompt: "'sister' nə deməkdir?", options: ["bacı", "qardaş", "ana", "nənə"], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t4", type: "multiple_choice", prompt: "'book' nə deməkdir?", options: ["kitab", "qələm", "çanta", "parta"], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t5", type: "multiple_choice", prompt: "'pen' nə deməkdir?", options: ["qələm", "kitab", "stul", "çanta"], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t6", type: "multiple_choice", speakOptions: true, prompt: "Məktəbə nə ilə kitab aparırsan?", options: ["bag", "pen", "desk", "book"], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t7", type: "multiple_choice", speakOptions: true, prompt: "Sinifdə hansı əşyanın arxasında oturursan?", options: ["desk", "bag", "pen", "book"], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "This is my mother.", options: ["Bu mənim anamdır.", "Bu mənim atamdır.", "Bu mənim bacımdır.", "Bu anadır."], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t9", type: "listening", prompt: "Dinlə və əşyanı seç.", audioText: "I have a red pen.", options: ["qələm", "kitab", "çanta", "parta"], correctIndex: 0, xp: 10 },
            { id: "en1-famschool-mesq-t10", type: "fill_blank", prompt: "'kitab' — ingiliscə yaz (bir söz).", accepted: ["book", "Book"], xp: 10 },
          ],
          bonusTasks: [
            { id: "en1-famschool-mesq-b1", type: "multiple_choice", speakOptions: true, prompt: "«Bu mənim qardaşımdır» — ingiliscə hansıdır?", options: ["This is my brother", "This is my sister", "This my brother", "My brother is this"], correctIndex: 0, xp: 15 },
            { id: "en1-famschool-mesq-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "My father is a teacher.", options: ["Atam müəllimdir.", "Anam müəllimdir.", "Atam həkimdir.", "Müəllim atamdır."], correctIndex: 0, xp: 15 },
            { id: "en1-famschool-mesq-b3", type: "fill_blank", prompt: "'çanta' — ingiliscə yaz (bir söz).", accepted: ["bag", "Bag"], xp: 15 },
            { id: "en1-famschool-mesq-b4", type: "multiple_choice", prompt: "«I love my family» nə deməkdir?", options: ["Ailəmi sevirəm.", "Ailəm məni sevir.", "Ailəm böyükdür.", "Ailəmlə yaşayıram."], correctIndex: 0, xp: 15 },
            { id: "en1-famschool-mesq-b5", type: "listening", prompt: "Dinlə: neçə kitab?", audioText: "I have four books.", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en1-famschool-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
