// İngilis dili — 3-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Present Simple (I/you/we/they)  2) Have got  3) Can/can't
// 4) Sözönləri (in/on/under)  5) Gündəlik rejim və saat  6) Peşələr və şəhər.
// 3-cü sinif üçün sadə: qısa qrammatika + şəkil-söz + dinləmə. id prefiksi en3-*.

import type { Subject } from "../types";

export const english3: Subject = {
  slug: "ingilis-dili-3",
  name: "İngilis dili",
  grade: 3,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Present Simple ═══════════════
    {
      id: "en3-present",
      title: "Present Simple (I like, you play)",
      description: "İndiki sadə zaman: I/you/we/they + feil.",
      lessons: [
        {
          id: "en3-present-rule",
          title: "Qayda: Present Simple",
          intro: "Adət və gündəlik işlər üçün: I play, you like, we go.",
          sections: [
            { heading: "Necə işləyir?", body: "Hər gün olan işlər üçün: I play football. You like apples. We go to school. Feil dəyişmir (I/you/we/they ilə)." },
            { heading: "İnkar", body: "don't əlavə olunur: I don't like fish. We don't play." },
          ],
          tasks: [
            { id: "en3-present-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'Mən futbol oynayıram.' İngiliscə hansıdır?", options: ["I play football.", "I football play.", "Play I football.", "I playing football."], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'I ___ apples.' (sevirəm)", options: ["like", "likes", "liking", "liked"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'We ___ to school.' (gedirik)", options: ["go", "goes", "going", "went"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'They ___ English.' (öyrənirlər)", options: ["learn", "learns", "learning", "learned"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'You ___ TV.' (baxırsan)", options: ["watch", "watches", "watching", "watched"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ like fish.'", options: ["don't", "doesn't", "not", "no"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'I ___ milk every day.' (içirəm)", options: ["drink", "drinks", "drinking", "drank"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t8", type: "multiple_choice", prompt: "'I like cats.' nə deməkdir?", options: ["Pişikləri sevirəm.", "Pişiyim var.", "Pişik gördüm.", "Pişik istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'We ___ in Baku.' (yaşayırıq)", options: ["live", "lives", "living", "lived"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'They ___ football.' (oynayırlar)", options: ["play", "plays", "playing", "played"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'We ___ watch TV.'", options: ["don't", "doesn't", "not", "isn't"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t12", type: "multiple_choice", prompt: "'You go to school.' nə deməkdir?", options: ["Sən məktəbə gedirsən.", "Məktəbə get.", "Məktəbə getdin.", "Məktəb böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'I ___ books.' (oxuyuram)", options: ["read", "reads", "reading", "readed"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'We ___ music.' (sevirik)", options: ["like", "likes", "liking", "liked"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'I ___ juice.' (içmirəm — inkar)", options: ["don't drink", "doesn't drink", "not drink", "drink not"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-present-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'They don't like fish.' nə deməkdir?", options: ["Balığı sevmirlər.", "Balığı sevirlər.", "Balıq yoxdur.", "Balıq istəyirlər."], correctIndex: 0, xp: 15 },
            { id: "en3-present-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'I ___ my teeth every morning.' (təmizləyirəm)", options: ["brush", "brushes", "brushing", "brushed"], correctIndex: 0, xp: 15 },
            { id: "en3-present-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'We ___ breakfast at 8.' (yeyirik)", options: ["have", "has", "having", "had"], correctIndex: 0, xp: 15 },
            { id: "en3-present-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'Do you like ice cream?' nə deməkdir?", options: ["Dondurmanı sevirsən?", "Dondurma var?", "Dondurma istəyirsən?", "Dondurma yedin?"], correctIndex: 0, xp: 15 },
            { id: "en3-present-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'I ___ football, I like basketball.' (inkar)", options: ["don't play", "doesn't play", "not play", "play not"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-present-listen",
          title: "Dinləmə: Present Simple",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en3-present-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I play football.", options: ["Futbol oynayıram.", "Futbol oynadım.", "Futbolu sevirəm.", "Futbol oynamıram."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I like apples.", options: ["Almaları sevirəm.", "Alma yeyirəm.", "Almam var.", "Alma istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We go to school.", options: ["Məktəbə gedirik.", "Məktəbə getdik.", "Məktəbdəyik.", "Məktəb böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They learn English.", options: ["İngiliscə öyrənirlər.", "İngiliscə bilirlər.", "İngiliscə danışırlar.", "İngiliscə öyrəndilər."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I drink milk.", options: ["Süd içirəm.", "Su içirəm.", "Süd sevirəm.", "Süd aldım."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "You watch TV.", options: ["Televizora baxırsan.", "Televizor aldın.", "Televizora bax.", "Televizor böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We live in Baku.", options: ["Bakıda yaşayırıq.", "Bakıya gedirik.", "Bakı gözəldir.", "Bakıda idik."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I don't like fish.", options: ["Balığı sevmirəm.", "Balığı sevirəm.", "Balıq yeyirəm.", "Balıq yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They play in the park.", options: ["Parkda oynayırlar.", "Parka gedirlər.", "Park böyükdür.", "Parkda idilər."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I read books.", options: ["Kitab oxuyuram.", "Kitab alıram.", "Kitabım var.", "Kitab yazıram."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We like music.", options: ["Musiqini sevirik.", "Musiqi çalırıq.", "Musiqi dinləyirik.", "Musiqi yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "You have breakfast.", options: ["Səhər yeməyi yeyirsən.", "Səhər yeməyi bişirdin.", "Səhər yeməyin var.", "Səhər durursan."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I don't watch TV.", options: ["Televizora baxmıram.", "Televizora baxıram.", "Televizor yoxdur.", "Televizora baxdım."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They go home.", options: ["Evə gedirlər.", "Evdədirlər.", "Evə getdilər.", "Ev böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We like ice cream.", options: ["Dondurmanı sevirik.", "Dondurma yeyirik.", "Dondurma aldıq.", "Dondurma yoxdur."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-present-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I brush my teeth every day.", options: ["Hər gün dişlərimi təmizləyirəm.", "Dişlərim ağrıyır.", "Diş fırçam var.", "Dişimi çəkdirdim."], correctIndex: 0, xp: 15 },
            { id: "en3-present-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Do you like cats?", options: ["Pişikləri sevirsən?", "Pişiyin var?", "Pişik gördün?", "Pişik istəyirsən?"], correctIndex: 0, xp: 15 },
            { id: "en3-present-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We don't eat meat.", options: ["Ət yemirik.", "Ət yeyirik.", "Ət aldıq.", "Ət yoxdur."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-present-he",
          title: "He / She / It — sona -s",
          intro: "Üçüncü şəxs tək formada feilə -s əlavə olunur.",
          sections: [
            { heading: "Qayda", body: "I play — He plays. You read — She reads. We go — It goes. Yalnız he/she/it ilə feilə -s qoşulur." },
            { heading: "İnkar", body: "He doesn't play. — O oynamır. (does not = doesn't)" },
          ],
          tasks: [
            { id: "en3-present-he-t1", type: "multiple_choice", prompt: "'He ______ football.' — düzgün forma hansıdır?", options: ["plays", "play", "playing", "played"], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t2", type: "multiple_choice", prompt: "'She ______ a book.' — düzgün forma hansıdır?", options: ["reads", "read", "reading", "readed"], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t3", type: "multiple_choice", prompt: "'They ______ to school.' — düzgün forma hansıdır?", options: ["go", "goes", "going", "gone"], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t4", type: "multiple_choice", prompt: "'It ______ every day.' (rain)", options: ["rains", "rain", "raining", "rained"], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t5", type: "multiple_choice", prompt: "Feilə -s nə vaxt əlavə olunur?", options: ["he / she / it ilə", "I ilə", "we ilə", "they ilə"], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t6", type: "multiple_choice", prompt: "'He doesn't play.' nə deməkdir?", options: ["O oynamır.", "O oynayır.", "Onlar oynamır.", "Mən oynamıram."], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t7", type: "multiple_choice", prompt: "'I ______ English.' — düzgün forma hansıdır?", options: ["speak", "speaks", "speaking", "spoke"], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t8", type: "multiple_choice", prompt: "'Does he like tea?' sualına inkar cavab hansıdır?", options: ["No, he doesn't.", "No, he don't.", "No, he isn't.", "No, he not."], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t9", type: "multiple_choice", prompt: "'We ______ TV in the evening.' (watch)", options: ["watch", "watches", "watching", "watched"], correctIndex: 0, xp: 10 },
            { id: "en3-present-he-t10", type: "multiple_choice", speakOptions: true, prompt: "'gedir' (he) İngiliscə necədir?", options: ["goes", "go", "going", "went"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "en3-present-he-b1", type: "multiple_choice", prompt: "'She ______ her homework every day.' (do)", options: ["does", "do", "doing", "done"], correctIndex: 0, xp: 15 },
            { id: "en3-present-he-b2", type: "multiple_choice", prompt: "'My brother ______ in Baku.' (live)", options: ["lives", "live", "living", "lived"], correctIndex: 0, xp: 15 },
            { id: "en3-present-he-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "He plays football.", options: ["O, futbol oynayır.", "Onlar futbol oynayır.", "Mən futbol oynayıram.", "O, futbol oynamır."], correctIndex: 0, xp: 15 },
            { id: "en3-present-he-b4", type: "multiple_choice", prompt: "'-es' hansı feillərə əlavə olunur?", options: ["go, do, watch kimi feillərə", "Bütün feillərə", "Heç birinə", "Yalnız 'be' feilinə"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-present-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-present-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Have got ═══════════════
    {
      id: "en3-havegot",
      title: "Have got (məndə var)",
      description: "Sahiblik: I have got, you have got, he/she has got.",
      lessons: [
        {
          id: "en3-havegot-rule",
          title: "Qayda: have got / has got",
          intro: "Nəyəsə sahib olmaq: I have got a dog. She has got a cat.",
          sections: [
            { heading: "have / has got", body: "I/you/we/they → have got. he/she/it → has got. 'I have got a bike.' — Velosipedim var. 'She has got a doll.' — Onun kuklası var." },
            { heading: "İnkar", body: "haven't got / hasn't got: I haven't got a cat." },
          ],
          tasks: [
            { id: "en3-havegot-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ got a dog.' (məndə var)", options: ["have", "has", "am", "is"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ got a cat.' (onda var)", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'He ___ got a ball.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'We ___ got books.'", options: ["have", "has", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'They ___ got a car.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t6", type: "multiple_choice", prompt: "'I have got a bike.' nə deməkdir?", options: ["Velosipedim var.", "Velosiped istəyirəm.", "Velosiped sürürəm.", "Velosiped aldım."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t7", type: "multiple_choice", prompt: "'She has got a doll.' nə deməkdir?", options: ["Onun kuklası var.", "O kukla aldı.", "Kukla istəyir.", "Kukla oynayır."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'it' (pişik) üçün: 'It ___ got blue eyes.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ got a cat.'", options: ["haven't", "hasn't", "don't", "isn't"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'She ___ got a bike.'", options: ["hasn't", "haven't", "don't", "isn't"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'My brother ___ got a red car.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'You ___ got a nice bag.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t13", type: "multiple_choice", prompt: "'We have got two cats.' nə deməkdir?", options: ["İki pişiyimiz var.", "İki pişik gördük.", "Pişik istəyirik.", "Pişiklər gəldi."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'The dog ___ got a long tail.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'My friends ___ got new bikes.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-havegot-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you got a pen?'", options: ["Have", "Has", "Do", "Are"], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ she got a sister?'", options: ["Has", "Have", "Do", "Is"], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-rule-b3", type: "multiple_choice", prompt: "'He hasn't got a phone.' nə deməkdir?", options: ["Onun telefonu yoxdur.", "Onun telefonu var.", "Telefon istəyir.", "Telefon aldı."], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'I have got two ___.' (bacı — cəm)", options: ["sisters", "sister", "sisteres", "sisters's"], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'She has got long ___.' (saç)", options: ["hair", "hairs", "a hair", "hairy"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-havegot-q",
          title: "Have got — sual və inkar",
          intro: "Nəyisə var/yox demək.",
          sections: [
            { heading: "Sual", body: "'Have you got a pen?' — Qələmin var? Cavab: 'Yes, I have.' / 'No, I haven't.'" },
            { heading: "İnkar", body: "'I haven't got a car.' — Maşınım yoxdur. 'He hasn't got a dog.' — Onun iti yoxdur." },
          ],
          tasks: [
            { id: "en3-havegot-q-t1", type: "multiple_choice", prompt: "'Have you got a pen?' nə deməkdir?", options: ["Qələmin var?", "Qələm alırsan?", "Qələm verirsən?", "Qələm haradadır?"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t2", type: "multiple_choice", prompt: "'I haven't got a car.' nə deməkdir?", options: ["Maşınım yoxdur.", "Maşınım var.", "Maşın alıram.", "Maşın sürürəm."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t3", type: "multiple_choice", prompt: "'He ______ got a dog.' — inkar forma hansıdır?", options: ["hasn't", "haven't", "not has", "don't"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t4", type: "multiple_choice", prompt: "'Yes, I have.' nə deməkdir?", options: ["Bəli, var.", "Xeyr, yoxdur.", "Bilmirəm.", "Bəlkə."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t5", type: "multiple_choice", prompt: "'She ______ got two sisters.' — düzgün forma hansıdır?", options: ["has", "have", "haves", "having"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t6", type: "multiple_choice", prompt: "'They ______ got a big house.' — düzgün forma hansıdır?", options: ["have", "has", "haves", "having"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t7", type: "multiple_choice", prompt: "'Has he got a bike?' sualına müsbət cavab hansıdır?", options: ["Yes, he has.", "Yes, he have.", "Yes, he is.", "Yes, he does."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t8", type: "multiple_choice", prompt: "'have got' nə bildirir?", options: ["Sahiblik", "Hərəkət", "Yer", "Zaman"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t9", type: "multiple_choice", prompt: "'I have got a brother.' nə deməkdir?", options: ["Qardaşım var.", "Qardaşım yoxdur.", "Qardaşam.", "Qardaşımı görürəm."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-q-t10", type: "multiple_choice", prompt: "'we' ilə hansı forma işlənir?", options: ["have got", "has got", "haves got", "having got"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "en3-havegot-q-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I have got a cat.", options: ["Pişiyim var.", "Pişiyim yoxdur.", "Pişik görürəm.", "Pişik istəyirəm."], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-q-b2", type: "multiple_choice", prompt: "'Has your sister got a phone?' cümləsində 'has' niyə işlənib?", options: ["Çünki 'sister' — he/she/it kimidir", "Səhvdir", "Çünki sualdır", "Çünki keçmişdir"], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-q-b3", type: "multiple_choice", prompt: "'haven't got' hansı sözlərin qısaldılmasıdır?", options: ["have not got", "has not got", "had not got", "having not got"], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-q-b4", type: "multiple_choice", prompt: "'I have got' əvəzinə danışıqda nə deyilir?", options: ["I've got", "I has got", "I got have", "I am got"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-havegot-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-havegot-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Can / can't ═══════════════
    {
      id: "en3-can",
      title: "Can / can't (bacarıq)",
      description: "Bacarıq bildirmək: I can swim. I can't fly.",
      lessons: [
        {
          id: "en3-can-rule",
          title: "Qayda: can / can't",
          intro: "can — bacarmaq. can + feil (əsas forma).",
          sections: [
            { heading: "can", body: "Bacarıq bildirir: I can swim. She can run. can-dan sonra feil sadə formada gəlir (bütün şəxslərdə eyni)." },
            { heading: "can't", body: "İnkar: cannot / can't. I can't fly. He can't drive." },
          ],
          tasks: [
            { id: "en3-can-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ swim.' (üzə bilirəm)", options: ["can", "cans", "am", "do"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ run fast.'", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "can-dan sonra feil hansı formada gəlir?", options: ["əsas forma (swim)", "V-ing (swimming)", "V2 (swam)", "to + V"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ fly.'", options: ["can't", "don't", "isn't", "not can"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t5", type: "multiple_choice", prompt: "'I can swim.' nə deməkdir?", options: ["Üzə bilirəm.", "Üzürəm.", "Üzdüm.", "Üzmək istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t6", type: "multiple_choice", prompt: "'He can't drive.' nə deməkdir?", options: ["O sürə bilmir.", "O sürür.", "O sürdü.", "O maşın aldı."], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'Birds ___ fly.'", options: ["can", "cans", "are", "do"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'Fish ___ walk.' (bacarmır)", options: ["can't", "don't", "aren't", "not"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'We ___ sing.'", options: ["can", "cans", "are", "do"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'I can ___.' (oxumaq — kitab)", options: ["read", "reads", "reading", "to read"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you swim?'", options: ["Can", "Do", "Are", "Is"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t12", type: "multiple_choice", prompt: "'Can you help me?' nə deməkdir?", options: ["Mənə kömək edə bilərsən?", "Mənə kömək et.", "Kömək etdin?", "Kömək istəyirsən?"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'A cat ___ climb trees.'", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'I ___ speak English.' (bacarıram)", options: ["can", "am", "do", "have"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'She ___ ride a bike.' (bacarır)", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-can-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'Penguins can't ___.' (uçmaq)", options: ["fly", "flies", "flying", "flew"], correctIndex: 0, xp: 15 },
            { id: "en3-can-rule-b2", type: "multiple_choice", prompt: "'I can jump but I can't fly.' nə deməkdir?", options: ["Tullana bilirəm, amma uça bilmirəm.", "Uça bilirəm.", "Tullanmıram.", "Uçuram."], correctIndex: 0, xp: 15 },
            { id: "en3-can-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'Can dogs swim?' — Yes, they ___.", options: ["can", "do", "are", "have"], correctIndex: 0, xp: 15 },
            { id: "en3-can-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'I can ___ a picture.' (çəkmək)", options: ["draw", "draws", "drawing", "drew"], correctIndex: 0, xp: 15 },
            { id: "en3-can-rule-b5", type: "multiple_choice", prompt: "'Can I go out?' nə deməkdir?", options: ["Çölə çıxa bilərəm?", "Çölə çıxdım.", "Çölə çıx.", "Çöldəyəm."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-can-ability",
          title: "Can — bacarıq və icazə",
          intro: "İki mənası var: bacarmaq və icazə istəmək.",
          sections: [
            { heading: "Bacarıq", body: "'I can swim.' — Üzə bilirəm. 'She can't drive.' — O, sürə bilmir." },
            { heading: "İcazə", body: "'Can I go out?' — Çölə çıxa bilərəm? 'Can you help me?' — Mənə kömək edə bilərsən?" },
          ],
          tasks: [
            { id: "en3-can-ability-t1", type: "multiple_choice", prompt: "'Can I go out?' nə deməkdir?", options: ["Çölə çıxa bilərəm?", "Çölə çıxıram.", "Çölə çıxdım.", "Çölə çıxma!"], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t2", type: "multiple_choice", prompt: "'Can you help me?' nə deməkdir?", options: ["Mənə kömək edə bilərsən?", "Mənə kömək etdin.", "Mən sənə kömək edirəm.", "Kömək lazımdır."], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t3", type: "multiple_choice", prompt: "'She can't drive.' nə deməkdir?", options: ["O, sürə bilmir.", "O, sürür.", "O, sürəcək.", "O, sürdü."], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t4", type: "multiple_choice", prompt: "'can' sözündən sonra feil necə olur?", options: ["Sadə forma: can swim", "can swims", "can swimming", "can to swim"], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t5", type: "multiple_choice", prompt: "'can't' hansı sözlərin qısaldılmasıdır?", options: ["cannot", "can not to", "can no", "could not"], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t6", type: "multiple_choice", speakOptions: true, prompt: "'üzmək' İngiliscə necədir?", options: ["swim", "sing", "sit", "see"], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t7", type: "multiple_choice", prompt: "'Can he play the piano?' sualına müsbət cavab hansıdır?", options: ["Yes, he can.", "Yes, he does.", "Yes, he is.", "Yes, he has."], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t8", type: "multiple_choice", prompt: "'can' hansı iki mənanı bildirir?", options: ["Bacarıq və icazə", "Zaman və yer", "Say və rəng", "Ad və hərəkət"], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t9", type: "multiple_choice", prompt: "'We can speak English.' nə deməkdir?", options: ["Biz İngiliscə danışa bilirik.", "Biz İngiliscə danışırıq.", "Biz İngiliscə danışdıq.", "Biz İngiliscə öyrənirik."], correctIndex: 0, xp: 10 },
            { id: "en3-can-ability-t10", type: "multiple_choice", prompt: "'I can't see.' nə deməkdir?", options: ["Görə bilmirəm.", "Görürəm.", "Gördüm.", "Görəcəyəm."], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "en3-can-ability-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Can you swim?", options: ["Üzə bilirsən?", "Üzürsən?", "Üzdün?", "Üzəcəksən?"], correctIndex: 0, xp: 15 },
            { id: "en3-can-ability-b2", type: "multiple_choice", prompt: "'Could' sözü 'can'-in hansı formasıdır?", options: ["Keçmiş / nəzakətli forma", "Gələcək", "Cəm", "İnkar"], correctIndex: 0, xp: 15 },
            { id: "en3-can-ability-b3", type: "multiple_choice", prompt: "'Can I have some water, please?' cümləsi nə bildirir?", options: ["Nəzakətli xahiş", "Əmr", "Şikayət", "Sual-cavab"], correctIndex: 0, xp: 15 },
            { id: "en3-can-ability-b4", type: "multiple_choice", prompt: "'can' feili şəxsə görə dəyişirmi?", options: ["Xeyr: I can, he can", "Bəli: he cans", "Yalnız cəmdə", "Yalnız sualda"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-can-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-can-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Sözönləri ═══════════════
    {
      id: "en3-prep",
      title: "Sözönləri (in / on / under)",
      description: "Yer bildirən sözönləri: in, on, under, next to.",
      lessons: [
        {
          id: "en3-prep-vocab",
          title: "Prepositions of place",
          intro: "Əşyanın harada olduğunu bildirən sözlər.",
          sections: [
            { heading: "Sözönləri", body: "in — içində, on — üstündə, under — altında, next to — yanında, behind — arxasında, in front of — qarşısında." },
          ],
          tasks: [
            { id: "en3-prep-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'in' nə deməkdir?", options: ["içində", "üstündə", "altında", "yanında"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'on' nə deməkdir?", options: ["üstündə", "içində", "altında", "arxasında"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'under' nə deməkdir?", options: ["altında", "üstündə", "içində", "yanında"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'next to' nə deməkdir?", options: ["yanında", "altında", "üstündə", "içində"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'The book is ___ the table.' (üstündə)", options: ["on", "in", "under", "next"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'The cat is ___ the box.' (içində)", options: ["in", "on", "under", "next to"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'The ball is ___ the chair.' (altında)", options: ["under", "on", "in", "next to"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'The pen is ___ the book.' (yanında)", options: ["next to", "in", "under", "on"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t9", type: "multiple_choice", prompt: "'The apple is on the table.' nə deməkdir?", options: ["Alma masanın üstündədir.", "Alma masanın altındadır.", "Alma qutudadır.", "Alma yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t10", type: "multiple_choice", prompt: "'The dog is under the bed.' nə deməkdir?", options: ["İt çarpayının altındadır.", "İt çarpayının üstündədir.", "İt qutudadır.", "İt qaçır."], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'behind' nə deməkdir?", options: ["arxasında", "qarşısında", "içində", "üstündə"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'in front of' nə deməkdir?", options: ["qarşısında", "arxasında", "altında", "içində"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'The keys are ___ my bag.' (içində)", options: ["in", "on", "under", "next to"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'The picture is ___ the wall.' (üstündə/divarda)", options: ["on", "in", "under", "behind"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t15", type: "multiple_choice", prompt: "'The cat is in the box.' nə deməkdir?", options: ["Pişik qutunun içindədir.", "Pişik qutunun üstündədir.", "Pişik qutunun altındadır.", "Pişik yoxdur."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-prep-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'The car is ___ the house.' (qarşısında)", options: ["in front of", "in", "under", "on"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'The boy is ___ the tree.' (arxasında)", options: ["behind", "on", "in", "under"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'between' nə deməkdir?", options: ["arasında", "yanında", "arxasında", "içində"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-vocab-b4", type: "multiple_choice", prompt: "'Where is the ball?' nə deməkdir?", options: ["Top haradadır?", "Top nədir?", "Top kimindir?", "Top böyükdür?"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'The shoes are ___ the bed.' (altında)", options: ["under", "on", "in", "next to"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-prep-where",
          title: "Where is it?",
          intro: "Sözönlərini sualda işlədək.",
          sections: [
            { heading: "Sual", body: "'Where is the ball?' — Top haradadır? 'It is under the table.' — Masanın altındadır." },
            { heading: "Daha çox sözönü", body: "in — içində, on — üstündə, under — altında, next to — yanında, behind — arxasında, in front of — qarşısında." },
          ],
          tasks: [
            { id: "en3-prep-where-t1", type: "multiple_choice", prompt: "'Where is the ball?' nə deməkdir?", options: ["Top haradadır?", "Top nədir?", "Top kimindir?", "Top necədir?"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t2", type: "multiple_choice", prompt: "'The cat is under the chair.' nə deməkdir?", options: ["Pişik stulun altındadır.", "Pişik stulun üstündədir.", "Pişik stulun yanındadır.", "Pişik stuldadır."], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t3", type: "multiple_choice", speakOptions: true, prompt: "'yanında' İngiliscə necədir?", options: ["next to", "under", "behind", "in"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t4", type: "multiple_choice", speakOptions: true, prompt: "'arxasında' İngiliscə necədir?", options: ["behind", "in front of", "next to", "on"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t5", type: "multiple_choice", speakOptions: true, prompt: "'qarşısında' İngiliscə necədir?", options: ["in front of", "behind", "under", "in"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t6", type: "multiple_choice", prompt: "'The book is on the table.' nə deməkdir?", options: ["Kitab masanın üstündədir.", "Kitab masanın altındadır.", "Kitab masadadır.", "Kitab masanın yanındadır."], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t7", type: "multiple_choice", prompt: "'in the box' nə deməkdir?", options: ["qutunun içində", "qutunun üstündə", "qutunun altında", "qutunun yanında"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t8", type: "multiple_choice", prompt: "Sual sözü 'where' nəyi soruşur?", options: ["Yeri", "Vaxtı", "Səbəbi", "Adı"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t9", type: "multiple_choice", speakOptions: true, prompt: "'altında' İngiliscə necədir?", options: ["under", "over", "on", "in"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-where-t10", type: "multiple_choice", prompt: "'It is between the chairs.' nə deməkdir?", options: ["Stulların arasındadır.", "Stulun altındadır.", "Stulun üstündədir.", "Stulun yanındadır."], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "en3-prep-where-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The pen is on the desk.", options: ["Qələm masanın üstündədir.", "Qələm masanın altındadır.", "Qələm çantadadır.", "Qələm yerdədir."], correctIndex: 0, xp: 15 },
            { id: "en3-prep-where-b2", type: "multiple_choice", prompt: "'Where are my shoes?' — 'are' niyə işlənib?", options: ["Çünki 'shoes' cəmdir", "Səhvdir", "Çünki sualdır", "Çünki keçmişdir"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-where-b3", type: "multiple_choice", speakOptions: true, prompt: "'arasında' İngiliscə necədir?", options: ["between", "behind", "beside", "below"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-where-b4", type: "multiple_choice", prompt: "'The dog is in front of the house.' nə deməkdir?", options: ["İt evin qarşısındadır.", "İt evin arxasındadır.", "İt evdədir.", "İt evin altındadır."], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-prep-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-prep-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Gündəlik rejim və saat ═══════════════
    {
      id: "en3-routine",
      title: "Gündəlik rejim və saat",
      description: "Gündəlik işlər və saatın deyilməsi.",
      lessons: [
        {
          id: "en3-routine-vocab",
          title: "Daily routines & time",
          intro: "Gündəlik işlər və saat sözləri.",
          sections: [
            { heading: "Rejim", body: "get up — durmaq, have breakfast — səhər yeməyi yemək, go to school — məktəbə getmək, do homework — ev tapşırığı etmək, go to bed — yatmağa getmək." },
            { heading: "Saat", body: "'What time is it?' — Saat neçədir? 'It is seven o'clock.' — Saat yeddidir." },
          ],
          tasks: [
            { id: "en3-routine-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'get up' nə deməkdir?", options: ["durmaq (yuxudan)", "yatmaq", "yemək", "getmək"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'have breakfast' nə deməkdir?", options: ["səhər yeməyi yemək", "nahar etmək", "yatmaq", "durmaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'go to school' nə deməkdir?", options: ["məktəbə getmək", "evə getmək", "yatmaq", "oynamaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'do homework' nə deməkdir?", options: ["ev tapşırığı etmək", "ev təmizləmək", "oynamaq", "yatmaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'go to bed' nə deməkdir?", options: ["yatmağa getmək", "durmaq", "yemək", "gəzmək"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'What time is it?' nə deməkdir?", options: ["Saat neçədir?", "Nə vaxt gəlirsən?", "Necəsən?", "Harададır?"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'It is seven o'clock.' nə deməkdir?", options: ["Saat yeddidir.", "Saat altıdır.", "Yeddi dəqiqə.", "Yeddinci gün."], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'morning' nə deməkdir?", options: ["səhər", "axşam", "gecə", "günorta"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'evening' nə deməkdir?", options: ["axşam", "səhər", "gecə", "günorta"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'night' nə deməkdir?", options: ["gecə", "səhər", "axşam", "gündüz"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'I get up at 7.' nə deməkdir?", options: ["Saat 7-də dururam.", "Saat 7-də yatıram.", "Saat 7-də yeyirəm.", "Saat 7-də gəlirəm."], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'have lunch' nə deməkdir?", options: ["nahar etmək", "səhər yeməyi", "şam etmək", "yatmaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'have dinner' nə deməkdir?", options: ["şam etmək", "nahar etmək", "səhər yeməyi", "durmaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'It is nine o'clock.' saat neçədir?", options: ["9", "8", "10", "7"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'wash my face' nə deməkdir?", options: ["üzümü yumaq", "dişimi təmizləmək", "saçımı daramaq", "əlimi yumaq"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-routine-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'I go to bed at ten.' nə deməkdir?", options: ["Saat 10-da yatıram.", "Saat 10-da dururam.", "Saat 10-da yeyirəm.", "Saat 10-da oxuyuram."], correctIndex: 0, xp: 15 },
            { id: "en3-routine-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'It is half past six.' nə deməkdir?", options: ["Altının yarısı (6:30)", "Saat altı", "Saat yeddi", "Beşin yarısı"], correctIndex: 0, xp: 15 },
            { id: "en3-routine-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'afternoon' nə deməkdir?", options: ["günorta/nahardan sonra", "səhər", "gecə", "axşam"], correctIndex: 0, xp: 15 },
            { id: "en3-routine-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'I do my homework in the evening.' nə deməkdir?", options: ["Ev tapşırığımı axşam edirəm.", "Səhər ev tapşırığı edirəm.", "Ev tapşırığı yoxdur.", "Ev tapşırığını bitirdim."], correctIndex: 0, xp: 15 },
            { id: "en3-routine-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'get dressed' nə deməkdir?", options: ["geyinmək", "soyunmaq", "yumaq", "yatmaq"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-routine-time",
          title: "What time is it?",
          intro: "Saatı İngiliscə demək.",
          sections: [
            { heading: "Saat", body: "'What time is it?' — Saat neçədir? 'It is seven o'clock.' — Saat yeddidir." },
            { heading: "Yarım və rüb", body: "half past seven — yeddi yarım (7:30), quarter past seven — yeddini on beş keçir (7:15)." },
          ],
          tasks: [
            { id: "en3-routine-time-t1", type: "multiple_choice", prompt: "'What time is it?' nə deməkdir?", options: ["Saat neçədir?", "Hansı gündür?", "Neçə yaşın var?", "Harada?"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t2", type: "multiple_choice", prompt: "'It is seven o'clock.' nə deməkdir?", options: ["Saat yeddidir.", "Saat yeddi yarımdır.", "Yeddi yaşım var.", "Yeddinci gündür."], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t3", type: "multiple_choice", prompt: "'half past seven' saat neçədir?", options: ["7:30", "7:00", "7:15", "6:30"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t4", type: "multiple_choice", prompt: "'quarter past seven' saat neçədir?", options: ["7:15", "7:45", "7:30", "7:00"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t5", type: "multiple_choice", speakOptions: true, prompt: "'səhər' İngiliscə necədir?", options: ["morning", "evening", "night", "afternoon"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t6", type: "multiple_choice", speakOptions: true, prompt: "'axşam' İngiliscə necədir?", options: ["evening", "morning", "noon", "day"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t7", type: "multiple_choice", prompt: "'I get up at seven.' nə deməkdir?", options: ["Saat yeddidə qalxıram.", "Saat yeddidə yatıram.", "Yeddi saat yatıram.", "Yeddi yaşım var."], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t8", type: "multiple_choice", speakOptions: true, prompt: "'yatmaq' İngiliscə necədir?", options: ["sleep", "wake", "eat", "play"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t9", type: "multiple_choice", prompt: "'in the morning' nə deməkdir?", options: ["səhər", "axşam", "gecə", "günorta"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-time-t10", type: "multiple_choice", speakOptions: true, prompt: "'nahar' İngiliscə necədir?", options: ["lunch", "breakfast", "dinner", "supper"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "en3-routine-time-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "It is nine o'clock.", options: ["Saat doqquzdur.", "Saat on birdir.", "Doqquz yaşım var.", "Doqquzuncu gündür."], correctIndex: 0, xp: 15 },
            { id: "en3-routine-time-b2", type: "multiple_choice", prompt: "'I have breakfast at 8.' nə deməkdir?", options: ["Saat 8-də səhər yeməyi yeyirəm.", "Saat 8-də nahar edirəm.", "8 saat yeyirəm.", "8 dəfə yeyirəm."], correctIndex: 0, xp: 15 },
            { id: "en3-routine-time-b3", type: "multiple_choice", speakOptions: true, prompt: "'səhər yeməyi' İngiliscə necədir?", options: ["breakfast", "lunch", "dinner", "snack"], correctIndex: 0, xp: 15 },
            { id: "en3-routine-time-b4", type: "multiple_choice", prompt: "'at night' nə deməkdir?", options: ["gecə", "səhər", "günorta", "axşam"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-routine-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-routine-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Peşələr və şəhər ═══════════════
    {
      id: "en3-jobs",
      title: "Peşələr və şəhər (Jobs & Places)",
      description: "Peşələr və şəhərdəki yerlərin adları.",
      lessons: [
        {
          id: "en3-jobs-vocab",
          title: "Jobs & places",
          intro: "Peşələri və yerləri öyrənək.",
          sections: [
            { heading: "Peşələr", body: "teacher — müəllim, doctor — həkim, driver — sürücü, cook — aşpaz, farmer — fermer, nurse — tibb bacısı, police officer — polis, pilot — pilot." },
            { heading: "Yerlər", body: "school — məktəb, hospital — xəstəxana, shop — mağaza, park — park, zoo — heyvanxana, library — kitabxana." },
          ],
          tasks: [
            { id: "en3-jobs-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'müəllim' İngiliscə necədir?", options: ["teacher", "doctor", "driver", "cook"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'həkim' İngiliscə necədir?", options: ["doctor", "teacher", "nurse", "farmer"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'sürücü' İngiliscə necədir?", options: ["driver", "pilot", "cook", "farmer"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'aşpaz' İngiliscə necədir?", options: ["cook", "driver", "doctor", "nurse"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'fermer' İngiliscə necədir?", options: ["farmer", "cook", "pilot", "teacher"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'pilot' İngiliscə necədir?", options: ["pilot", "driver", "police officer", "cook"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t7", type: "multiple_choice", prompt: "'doctor' nə deməkdir?", options: ["həkim", "müəllim", "sürücü", "aşpaz"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t8", type: "multiple_choice", prompt: "'teacher' nə deməkdir?", options: ["müəllim", "həkim", "polis", "pilot"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'məktəb' İngiliscə necədir?", options: ["school", "hospital", "shop", "park"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'xəstəxana' İngiliscə necədir?", options: ["hospital", "school", "shop", "zoo"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'mağaza' İngiliscə necədir?", options: ["shop", "park", "school", "library"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'kitabxana' İngiliscə necədir?", options: ["library", "shop", "zoo", "park"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'heyvanxana' İngiliscə necədir?", options: ["zoo", "park", "shop", "hospital"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'A ___ works in a hospital.' (həkim)", options: ["doctor", "teacher", "farmer", "cook"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'A ___ teaches children.' (müəllim)", options: ["teacher", "doctor", "driver", "pilot"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-jobs-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'A ___ flies a plane.' (pilot)", options: ["pilot", "driver", "cook", "farmer"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'nurse' nə deməkdir?", options: ["tibb bacısı", "həkim", "müəllim", "aşpaz"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'A ___ cooks food.' (aşpaz)", options: ["cook", "farmer", "driver", "pilot"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'We borrow books from the ___.'", options: ["library", "shop", "zoo", "park"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'police officer' nə deməkdir?", options: ["polis", "əsgər", "sürücü", "pilot"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-jobs-city",
          title: "Places in the city",
          intro: "Şəhərdəki yerlərin adları.",
          sections: [
            { heading: "Yerlər", body: "school — məktəb, hospital — xəstəxana, shop — mağaza, park — park, library — kitabxana, bank — bank." },
            { heading: "Kim harada işləyir?", body: "A teacher works at a school. A doctor works at a hospital." },
          ],
          tasks: [
            { id: "en3-jobs-city-t1", type: "multiple_choice", speakOptions: true, prompt: "'xəstəxana' İngiliscə necədir?", options: ["hospital", "school", "shop", "park"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t2", type: "multiple_choice", speakOptions: true, prompt: "'kitabxana' İngiliscə necədir?", options: ["library", "bookshop", "school", "office"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t3", type: "multiple_choice", speakOptions: true, prompt: "'mağaza' İngiliscə necədir?", options: ["shop", "school", "stop", "ship"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t4", type: "multiple_choice", prompt: "'A doctor works at a ______.' — düzgün söz hansıdır?", options: ["hospital", "school", "shop", "bank"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t5", type: "multiple_choice", prompt: "'A teacher works at a ______.' — düzgün söz hansıdır?", options: ["school", "hospital", "bank", "park"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t6", type: "multiple_choice", speakOptions: true, prompt: "'park' İngiliscə necədir?", options: ["park", "pork", "part", "path"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t7", type: "multiple_choice", prompt: "'Where do you buy bread?' — cavab hansıdır?", options: ["At a shop.", "At a school.", "At a hospital.", "At a park."], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t8", type: "multiple_choice", speakOptions: true, prompt: "'küçə' İngiliscə necədir?", options: ["street", "school", "strong", "spring"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t9", type: "multiple_choice", prompt: "'bank' sözü nə deməkdir?", options: ["bank", "sahil", "skamya", "kitab"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-city-t10", type: "multiple_choice", speakOptions: true, prompt: "'muzey' İngiliscə necədir?", options: ["museum", "music", "mission", "market"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "en3-jobs-city-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "She works at a hospital.", options: ["O, xəstəxanada işləyir.", "O, məktəbdə işləyir.", "O, xəstədir.", "O, xəstəxanaya gedir."], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-city-b2", type: "multiple_choice", prompt: "'A firefighter works at a fire station.' nə deməkdir?", options: ["Yanğınsöndürən yanğın stansiyasında işləyir.", "Həkim xəstəxanada işləyir.", "Müəllim məktəbdə işləyir.", "Polis idarədə işləyir."], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-city-b3", type: "multiple_choice", speakOptions: true, prompt: "'aptek' İngiliscə necədir?", options: ["pharmacy", "factory", "gallery", "bakery"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-city-b4", type: "multiple_choice", prompt: "'What does your father do?' nə soruşur?", options: ["Peşəsini", "Adını", "Yaşını", "Ünvanını"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-jobs-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "en3-jobs-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
