// İngilis dili — 6-cı sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr (qrammatika + tematik): 1) Present Perfect  2) Future (will / going to)
// 3) Countable/Uncountable + quantifiers  4) Adverbs & Prepositions
// 5) Comparatives & Superlatives  6) Tematik lüğət (Technology, Travel).
// Hər dərs 15 əsas + 5 bonus. Mərhələli. id prefiksi en6-*. reading dərsləri -read- ilə
// (praktikadan çıxarılır, passage sections-dədir); listening öz audioText-i ilə tamdır.

import type { Subject } from "../types";

export const english6: Subject = {
  slug: "ingilis-dili-6",
  name: "İngilis dili",
  grade: 6,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Present Perfect ═══════════════
    {
      id: "en6-pp",
      title: "Present Perfect",
      description:
        "have/has + III forma (V3) — keçmişdə baş verib indi ilə bağlı olan işlər.",
      lessons: [
        {
          id: "en6-pp-rule",
          title: "Present Perfect qaydası",
          intro: "have/has + feilin III forması ilə keçmiş-indi əlaqəsini ifadə etmək.",
          sections: [
            { heading: "Present Perfect nədir?", body: "Keçmişdə baş verib nəticəsi indi ilə bağlı olan işi bildirir: I have finished my homework. (Ev tapşırığımı bitirmişəm — indi hazırdır.)" },
            { heading: "have / has + V3", body: "I/you/we/they → have; he/she/it → has. Feil III formada olur: go → gone, do → done, see → seen, write → written." },
            { heading: "just / already / yet", body: "'just' (təzəcə), 'already' (artıq) təsdiqdə; 'yet' (hələ) sual və inkarda: I have just eaten. Have you finished yet?" },
          ],
          tasks: [
            { id: "en6-pp-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ finished my work.'", options: ["have", "has", "am", "did"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ gone home.'", options: ["have", "has", "is", "did"], correctIndex: 1, xp: 10 },
            { id: "en6-pp-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'They ___ seen this film.'", options: ["have", "has", "is", "was"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'go' feilinin III forması hansıdır?", options: ["gone", "went", "going", "goed"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'do' feilinin III forması hansıdır?", options: ["done", "did", "doing", "does"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t6", type: "fill_blank", prompt: "'see' feilinin III formasını yaz.", accepted: ["seen"], xp: 10 },
            { id: "en6-pp-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'He has ___ a letter.' (write)", options: ["written", "wrote", "writing", "write"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'We have ___ our lunch.' (eat)", options: ["eaten", "ate", "eating", "eat"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you finished?'", options: ["Have", "Has", "Did", "Are"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'I have ___ eaten.' (təzəcə)", options: ["just", "yet", "ago", "since"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'Have you finished ___?' (hələ)", options: ["yet", "just", "already", "ago"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'She has ___ done it.' (artıq)", options: ["already", "yet", "ago", "since"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t13", type: "fill_blank", prompt: "'take' feilinin III formasını yaz.", accepted: ["taken"], xp: 10 },
            { id: "en6-pp-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ not seen it.'", options: ["have", "has", "did", "am"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-rule-t15", type: "multiple_choice", prompt: "Present Perfect nəyi bildirir?", options: ["keçmiş iş, indi ilə bağlı", "gələcək iş", "hər gün olan iş", "indi baş verən iş"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-pp-rule-b1", type: "fill_blank", prompt: "'break' feilinin III formasını yaz.", accepted: ["broken"], xp: 15 },
            { id: "en6-pp-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'He has ___ his keys.' (lose)", options: ["lost", "losed", "losing", "lose"], correctIndex: 0, xp: 15 },
            { id: "en6-pp-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "Hansı cümlə Present Perfect-dir?", options: ["I have read it.", "I read it yesterday.", "I am reading.", "I will read."], correctIndex: 0, xp: 15 },
            { id: "en6-pp-rule-b4", type: "fill_blank", prompt: "'give' feilinin III formasını yaz.", accepted: ["given"], xp: 15 },
            { id: "en6-pp-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'___ she arrived?'", options: ["Has", "Have", "Did", "Is"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en6-pp-vocab",
          title: "Lüğət və III formalar",
          intro: "Present Perfect üçün lazım olan qaydasız feillərin III forması.",
          sections: [
            { heading: "Qaydasız III formalar", body: "be → been, have → had, come → come, make → made, take → taken, find → found, buy → bought, bring → brought." },
            { heading: "Faydalı sözlər", body: "already — artıq · yet — hələ · just — təzəcə · ever — heç (soruşanda) · never — heç vaxt · since — -dən bəri · for — müddətlə." },
          ],
          tasks: [
            { id: "en6-pp-vocab-t1", type: "fill_blank", prompt: "'be' feilinin III formasını yaz.", accepted: ["been"], xp: 10 },
            { id: "en6-pp-vocab-t2", type: "fill_blank", prompt: "'make' feilinin III formasını yaz.", accepted: ["made"], xp: 10 },
            { id: "en6-pp-vocab-t3", type: "fill_blank", prompt: "'take' feilinin III formasını yaz.", accepted: ["taken"], xp: 10 },
            { id: "en6-pp-vocab-t4", type: "fill_blank", prompt: "'buy' feilinin III formasını yaz.", accepted: ["bought"], xp: 10 },
            { id: "en6-pp-vocab-t5", type: "multiple_choice", prompt: "'ever' sözünün mənası nədir?", options: ["heç (soruşanda)", "artıq", "təzəcə", "hər gün"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-vocab-t6", type: "multiple_choice", prompt: "'never' sözünün mənası?", options: ["heç vaxt", "həmişə", "artıq", "hələ"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-vocab-t7", type: "multiple_choice", prompt: "'already' sözünün mənası?", options: ["artıq", "hələ", "heç vaxt", "təzəcə"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-vocab-t8", type: "multiple_choice", prompt: "'yet' sözünün mənası?", options: ["hələ", "artıq", "təzəcə", "həmişə"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-vocab-t9", type: "fill_blank", prompt: "'come' feilinin III formasını yaz.", accepted: ["come"], xp: 10 },
            { id: "en6-pp-vocab-t10", type: "fill_blank", prompt: "'find' feilinin III formasını yaz.", accepted: ["found"], xp: 10 },
            { id: "en6-pp-vocab-t11", type: "multiple_choice", prompt: "'since' nə üçün işlənir?", options: ["başlanğıc vaxt (-dən bəri)", "müddət", "gələcək", "təkrar"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-vocab-t12", type: "multiple_choice", prompt: "'for' nə üçün işlənir?", options: ["müddət (2 hours)", "başlanğıc vaxt", "gələcək", "keçmiş dəqiq an"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-vocab-t13", type: "fill_blank", prompt: "'bring' feilinin III formasını yaz.", accepted: ["brought"], xp: 10 },
            { id: "en6-pp-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'I have lived here ___ 2010.'", options: ["since", "for", "yet", "ago"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'I have known him ___ five years.'", options: ["for", "since", "yet", "ago"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-pp-vocab-b1", type: "fill_blank", prompt: "'have' feilinin III formasını yaz.", accepted: ["had"], xp: 15 },
            { id: "en6-pp-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'Have you ___ been to London?' (heç)", options: ["ever", "never", "yet", "just"], correctIndex: 0, xp: 15 },
            { id: "en6-pp-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'I have ___ seen a lion.' (heç vaxt)", options: ["never", "ever", "yet", "already"], correctIndex: 0, xp: 15 },
            { id: "en6-pp-vocab-b4", type: "fill_blank", prompt: "'read' feilinin III formasını yaz.", accepted: ["read"], xp: 15 },
            { id: "en6-pp-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'She has worked here ___ ten years.'", options: ["for", "since", "yet", "ago"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en6-pp-listen",
          title: "Dinləmə: Present Perfect",
          intro: "Present Perfect cümlələrini dinlə və düzgün mənanı seç.",
          sections: [
            { heading: "Necə işləyir?", body: "«Dinlə» düyməsinə bas, cümləni eşit və düzgün variantı seç. İstədiyin qədər təkrar dinlə." },
          ],
          tasks: [
            { id: "en6-pp-listen-t1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I have finished my homework.", options: ["Ev tapşırığımı bitirmişəm.", "Ev tapşırığımı edirəm.", "Ev tapşırığı edəcəyəm.", "Ev tapşırığı etmədim."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She has gone home.", options: ["O evə gedib.", "O evə gedir.", "O evdədir.", "O evə gedəcək."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "They have seen this film.", options: ["Onlar bu filmi görüblər.", "Onlar bu filmə baxır.", "Onlar bu filmi görməyib.", "Onlar film çəkir."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t4", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I have just eaten.", options: ["Təzəcə yemişəm.", "İndi yeyirəm.", "Yeməyəcəyəm.", "Hələ yeməmişəm."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t5", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We have already done it.", options: ["Biz onu artıq etmişik.", "Biz onu edəcəyik.", "Biz onu etmirik.", "Biz onu edirik."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t6", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Have you finished yet?", options: ["Hələ bitirməmisən?", "Nə vaxt bitirdin?", "Bitirəcəksən?", "Bitirirsən?"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t7", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "He has lost his keys.", options: ["O açarlarını itirib.", "O açarlarını tapıb.", "O açar alır.", "O açarları verir."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t8", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Have you ever been to Baku?", options: ["Heç Bakıda olmusan?", "Bakıya gedirsən?", "Bakıya gedəcəksən?", "Bakını sevirsən?"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t9", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I have never seen snow.", options: ["Heç vaxt qar görməmişəm.", "Qar görürəm.", "Qar görmüşəm.", "Qar görəcəyəm."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t10", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She has lived here for ten years.", options: ["O on ildir burada yaşayır.", "O on il burada yaşadı.", "O buraya köçəcək.", "O burada yaşamır."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t11", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We have bought a new car.", options: ["Yeni maşın almışıq.", "Yeni maşın alırıq.", "Yeni maşın alacağıq.", "Maşın satmışıq."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t12", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "He has written a book.", options: ["O kitab yazıb.", "O kitab oxuyub.", "O kitab yazır.", "O kitab alıb."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t13", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I have made a cake.", options: ["Tort bişirmişəm.", "Tort yemişəm.", "Tort alıram.", "Tort bişirirəm."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t14", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "They have come home.", options: ["Onlar evə gəliblər.", "Onlar evə gedir.", "Onlar evdə deyil.", "Onlar gələcək."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-listen-t15", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Has she arrived?", options: ["O çatıb?", "O çatır?", "O çatacaq?", "O gedib?"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-pp-listen-b1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I have known him for years.", options: ["Onu illərdir tanıyıram.", "Onu tanımıram.", "Onu tanıyacağam.", "Onu yeni tanıdım."], correctIndex: 0, xp: 15 },
            { id: "en6-pp-listen-b2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She has broken the window.", options: ["O pəncərəni sındırıb.", "O pəncərəni açıb.", "O pəncərəni bağlayıb.", "O pəncərəni təmizləyib."], correctIndex: 0, xp: 15 },
            { id: "en6-pp-listen-b3", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Have they left?", options: ["Onlar gedib?", "Onlar gəlib?", "Onlar qalıb?", "Onlar gedir?"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en6-pp-read",
          title: "Reading: A trip abroad",
          intro: "Qısa mətni oxu və suallara cavab ver (Present Perfect).",
          sections: [
            { heading: "Read the text (Mətni oxu)", body: "Hi, I am Kamran. I have travelled a lot this year. I have been to Turkey and Georgia. I have visited many museums and I have tried delicious food. I have not been to Europe yet, but I hope to go next year. I have taken hundreds of photos. Travelling has taught me a lot about different cultures." },
            { heading: "İpucu", body: "Sualı oxu, cavabı mətndə tap. Lazım olsa mətnə yenidən bax." },
          ],
          tasks: [
            { id: "en6-pp-read-t1", type: "multiple_choice", speakOptions: true, prompt: "What is the boy's name?", options: ["Kamran", "Tural", "Elvin", "Orxan"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t2", type: "multiple_choice", speakOptions: true, prompt: "Which countries has he been to?", options: ["Turkey and Georgia", "France and Italy", "Russia and Iran", "Spain and Greece"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t3", type: "multiple_choice", speakOptions: true, prompt: "What has he visited?", options: ["many museums", "many shops", "many schools", "many parks"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t4", type: "multiple_choice", speakOptions: true, prompt: "Has he been to Europe?", options: ["No, not yet.", "Yes, he has.", "Yes, last year.", "We don't know."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t5", type: "multiple_choice", speakOptions: true, prompt: "What has he taken?", options: ["hundreds of photos", "many books", "some money", "a few gifts"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t6", type: "fill_blank", prompt: "'I have ___ delicious food.' (dadmaq — mətndən)", accepted: ["tried"], xp: 10 },
            { id: "en6-pp-read-t7", type: "multiple_choice", speakOptions: true, prompt: "When does he hope to go to Europe?", options: ["next year", "this year", "next month", "never"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t8", type: "multiple_choice", prompt: "'travelled a lot' nə deməkdir?", options: ["çox səyahət etmiş", "az səyahət etmiş", "heç səyahət etməmiş", "səyahət edəcək"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t9", type: "multiple_choice", speakOptions: true, prompt: "What has travelling taught him?", options: ["about different cultures", "about maths", "about music", "about sport"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t10", type: "fill_blank", prompt: "'I have ___ to Turkey and Georgia.' (mətndən)", accepted: ["been"], xp: 10 },
            { id: "en6-pp-read-t11", type: "multiple_choice", prompt: "'museum' nə deməkdir?", options: ["muzey", "məktəb", "mağaza", "park"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t12", type: "multiple_choice", speakOptions: true, prompt: "How many photos has he taken?", options: ["hundreds", "ten", "none", "two"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t13", type: "multiple_choice", prompt: "'delicious' nə deməkdir?", options: ["dadlı", "acı", "soyuq", "isti"], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t14", type: "multiple_choice", speakOptions: true, prompt: "Has he travelled this year?", options: ["Yes, a lot.", "No, not at all.", "Only once.", "We don't know."], correctIndex: 0, xp: 10 },
            { id: "en6-pp-read-t15", type: "multiple_choice", prompt: "'culture' nə deməkdir?", options: ["mədəniyyət", "ölkə", "şəhər", "dil"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-pp-read-b1", type: "multiple_choice", prompt: "'abroad' nə deməkdir?", options: ["xaricdə", "evdə", "məktəbdə", "şəhərdə"], correctIndex: 0, xp: 15 },
            { id: "en6-pp-read-b2", type: "fill_blank", prompt: "'I have not been to Europe ___.' (hələ — mətndən)", accepted: ["yet"], xp: 15 },
            { id: "en6-pp-read-b3", type: "multiple_choice", speakOptions: true, prompt: "What does he hope to do next year?", options: ["go to Europe", "stay home", "sell photos", "learn maths"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en6-pp-write",
          title: "Cümlə qur: Present Perfect",
          intro: "Sözləri düzgün sıraya düz və Present Perfect cümləsi qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. Quruluş: kim + have/has + V3 (III forma) + qalan. Məs: I have finished it." },
          ],
          tasks: [
            { id: "en6-pp-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "have", "finished"], answer: "I have finished", translation: "Mən bitirmişəm.", xp: 10 },
            { id: "en6-pp-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "has", "gone", "home"], answer: "She has gone home", translation: "O evə gedib.", xp: 10 },
            { id: "en6-pp-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "have", "seen", "it"], answer: "They have seen it", translation: "Onlar onu görüblər.", xp: 10 },
            { id: "en6-pp-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "have", "just", "eaten"], answer: "I have just eaten", translation: "Təzəcə yemişəm.", xp: 10 },
            { id: "en6-pp-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "has", "lost", "his", "keys"], answer: "He has lost his keys", translation: "O açarlarını itirib.", xp: 10 },
            { id: "en6-pp-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "have", "bought", "a", "car"], answer: "We have bought a car", translation: "Maşın almışıq.", xp: 10 },
            { id: "en6-pp-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Have", "you", "finished"], answer: "Have you finished", translation: "Bitirmisən?", xp: 10 },
            { id: "en6-pp-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "has", "written", "a", "book"], answer: "She has written a book", translation: "O kitab yazıb.", xp: 10 },
            { id: "en6-pp-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "have", "never", "seen", "snow"], answer: "I have never seen snow", translation: "Heç vaxt qar görməmişəm.", xp: 10 },
            { id: "en6-pp-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "have", "come", "home"], answer: "They have come home", translation: "Onlar evə gəliblər.", xp: 10 },
            { id: "en6-pp-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "has", "made", "a", "cake"], answer: "He has made a cake", translation: "O tort bişirib.", xp: 10 },
            { id: "en6-pp-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "have", "already", "done", "it"], answer: "I have already done it", translation: "Artıq etmişəm.", xp: 10 },
            { id: "en6-pp-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Has", "she", "arrived"], answer: "Has she arrived", translation: "O çatıb?", xp: 10 },
            { id: "en6-pp-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "have", "visited", "the", "museum"], answer: "We have visited the museum", translation: "Muzeyi ziyarət etmişik.", xp: 10 },
            { id: "en6-pp-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Have", "you", "ever", "been", "there"], answer: "Have you ever been there", translation: "Heç orada olmusan?", xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-pp-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "have", "lived", "here", "since", "2010"], answer: "I have lived here since 2010", translation: "2010-dan bəri burada yaşayıram.", xp: 15 },
            { id: "en6-pp-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "has", "not", "arrived", "yet"], answer: "She has not arrived yet", translation: "O hələ çatmayıb.", xp: 15 },
            { id: "en6-pp-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "has", "broken", "the", "window"], answer: "He has broken the window", translation: "O pəncərəni sındırıb.", xp: 15 },
          ],
        },
      ],
    },

    // ═══════════════ 2. Future (will / going to) ═══════════════
    {
      id: "en6-future",
      title: "Future: will / going to",
      description:
        "Gələcək zaman — 'will' (qərar, proqnoz) və 'be going to' (plan, niyyət).",
      lessons: [
        {
          id: "en6-fut-rule",
          title: "Future qaydası (will / going to)",
          intro: "'will' və 'be going to' ilə gələcək işi ifadə etmək.",
          sections: [
            { heading: "will", body: "Ani qərar, proqnoz və vəd üçün: I will help you. It will rain tomorrow. 'will' + feilin əsas forması (will go, will do). İnkar: won't (will not)." },
            { heading: "be going to", body: "Əvvəlcədən plan/niyyət üçün: I am going to visit my aunt. am/is/are + going to + feil." },
            { heading: "Fərq", body: "will — danışıq anında qərar/proqnoz; going to — əvvəlcədən qurulmuş plan. Tez-tez 'tomorrow', 'next week' ilə işlənir." },
          ],
          tasks: [
            { id: "en6-fut-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ help you.' (vəd)", options: ["will", "am", "have", "did"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'will' sözündən sonra feil hansı formadadır?", options: ["əsas forma", "-ing", "-ed", "III forma"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'It ___ rain tomorrow.' (proqnoz)", options: ["will", "is", "has", "does"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'will not' qısaldılmış formada necə yazılır?", options: ["won't", "willn't", "wouldn't", "don't"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'I am ___ to visit my aunt.' (plan)", options: ["going", "will", "go", "gone"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'She is going ___ study tonight.'", options: ["to", "for", "at", "in"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'They ___ going to travel.'", options: ["are", "is", "am", "will"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'He ___ going to play football.'", options: ["is", "are", "am", "will"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t9", type: "multiple_choice", prompt: "Əvvəlcədən qurulmuş plan üçün hansı işlənir?", options: ["be going to", "will", "have", "did"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t10", type: "multiple_choice", prompt: "Ani qərar/proqnoz üçün hansı işlənir?", options: ["will", "be going to", "have", "was"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'We ___ win the game.' (proqnoz)", options: ["will", "are", "have", "did"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'I ___ going to buy a book.'", options: ["am", "is", "are", "will"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t13", type: "fill_blank", prompt: "'will not' qısa formasını yaz.", accepted: ["won't", "wont"], xp: 10 },
            { id: "en6-fut-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you help me?'", options: ["Will", "Are", "Have", "Did"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'Look at the clouds! It ___ rain.' (going to plan/işarə)", options: ["is going to", "will", "goes", "went"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-fut-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'I think it ___ be sunny.' (fikir/proqnoz)", options: ["will", "is going to", "goes", "was"], correctIndex: 0, xp: 15 },
            { id: "en6-fut-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'We ___ going to have a party.'", options: ["are", "is", "am", "will"], correctIndex: 0, xp: 15 },
            { id: "en6-fut-rule-b3", type: "multiple_choice", prompt: "'won't' nə deməkdir?", options: ["will not (etməyəcək)", "istəmir", "edir", "etdi"], correctIndex: 0, xp: 15 },
            { id: "en6-fut-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'She will ___ tomorrow.' (gəl)", options: ["come", "comes", "coming", "came"], correctIndex: 0, xp: 15 },
            { id: "en6-fut-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'What are you going ___ do?'", options: ["to", "for", "at", "with"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en6-fut-listen",
          title: "Dinləmə: Future",
          intro: "Gələcək zaman cümlələrini dinlə və düzgün mənanı seç.",
          sections: [
            { heading: "Necə işləyir?", body: "«Dinlə» düyməsinə bas, cümləni eşit və düzgün variantı seç. İstədiyin qədər təkrar dinlə." },
          ],
          tasks: [
            { id: "en6-fut-listen-t1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I will help you.", options: ["Sənə kömək edəcəyəm.", "Sənə kömək edirəm.", "Sənə kömək etdim.", "Sənə kömək etmirəm."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "It will rain tomorrow.", options: ["Sabah yağış yağacaq.", "İndi yağış yağır.", "Dünən yağış yağdı.", "Yağış yağmayacaq."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t3", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I am going to visit my aunt.", options: ["Xalamı ziyarət edəcəyəm.", "Xalamı ziyarət etdim.", "Xalam gəlir.", "Xalamı görmürəm."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t4", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She is going to study tonight.", options: ["O bu gecə oxuyacaq.", "O bu gecə oxudu.", "O indi oxuyur.", "O oxumayacaq."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t5", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We will win the game.", options: ["Biz oyunu udacağıq.", "Biz oyunu uduzduq.", "Biz oyun oynayırıq.", "Biz udmayacağıq."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t6", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "They are going to travel next week.", options: ["Onlar gələn həftə səyahət edəcək.", "Onlar səyahət etdi.", "Onlar səyahət edir.", "Onlar getməyəcək."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t7", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Will you help me?", options: ["Mənə kömək edəcəksən?", "Mənə kömək etdin?", "Mənə kömək edirsən?", "Mənə kömək lazımdır?"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t8", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "He is going to play football.", options: ["O futbol oynayacaq.", "O futbol oynadı.", "O futbol oynayır.", "O futbol sevmir."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t9", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I won't be late.", options: ["Gecikməyəcəyəm.", "Gecikdim.", "Gecikirəm.", "Tez gələcəyəm."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t10", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We are going to have a party.", options: ["Şənlik keçirəcəyik.", "Şənlik keçirdik.", "Şənlik keçiririk.", "Şənlik olmayacaq."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t11", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "The film will start soon.", options: ["Film tezliklə başlayacaq.", "Film başladı.", "Film başlayır.", "Film bitdi."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t12", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I am going to buy a new phone.", options: ["Yeni telefon alacağam.", "Yeni telefon aldım.", "Telefon satıram.", "Telefonum yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t13", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "What are you going to do?", options: ["Nə edəcəksən?", "Nə etdin?", "Nə edirsən?", "Nə istəyirsən?"], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t14", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She will call you later.", options: ["O sonra sənə zəng edəcək.", "O sənə zəng etdi.", "O zəng edir.", "O zəng etməyəcək."], correctIndex: 0, xp: 10 },
            { id: "en6-fut-listen-t15", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "They will arrive at six.", options: ["Onlar altıda çatacaq.", "Onlar altıda çatdı.", "Onlar çatır.", "Onlar gəlməyəcək."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-fut-listen-b1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I think it will be cold.", options: ["Məncə soyuq olacaq.", "Soyuq idi.", "Soyuqdur.", "İsti olacaq."], correctIndex: 0, xp: 15 },
            { id: "en6-fut-listen-b2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We are going to move house.", options: ["Ev dəyişəcəyik.", "Ev dəyişdik.", "Evdəyik.", "Ev almayacağıq."], correctIndex: 0, xp: 15 },
            { id: "en6-fut-listen-b3", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Will it snow tomorrow?", options: ["Sabah qar yağacaq?", "Dünən qar yağdı?", "Qar yağır?", "Qar sevirsən?"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en6-fut-write",
          title: "Cümlə qur: Future",
          intro: "Sözləri düzgün sıraya düz və gələcək zaman cümləsi qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. will: kim + will + feil. going to: kim + am/is/are + going to + feil." },
          ],
          tasks: [
            { id: "en6-fut-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "will", "help", "you"], answer: "I will help you", translation: "Sənə kömək edəcəyəm.", xp: 10 },
            { id: "en6-fut-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["It", "will", "rain", "tomorrow"], answer: "It will rain tomorrow", translation: "Sabah yağış yağacaq.", xp: 10 },
            { id: "en6-fut-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "am", "going", "to", "study"], answer: "I am going to study", translation: "Oxuyacağam.", xp: 10 },
            { id: "en6-fut-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "will", "call", "you"], answer: "She will call you", translation: "O sənə zəng edəcək.", xp: 10 },
            { id: "en6-fut-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "will", "win"], answer: "We will win", translation: "Biz udacağıq.", xp: 10 },
            { id: "en6-fut-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "are", "going", "to", "travel"], answer: "They are going to travel", translation: "Onlar səyahət edəcək.", xp: 10 },
            { id: "en6-fut-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["He", "is", "going", "to", "play"], answer: "He is going to play", translation: "O oynayacaq.", xp: 10 },
            { id: "en6-fut-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Will", "you", "help", "me"], answer: "Will you help me", translation: "Mənə kömək edəcəksən?", xp: 10 },
            { id: "en6-fut-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "won't", "be", "late"], answer: "I won't be late", translation: "Gecikməyəcəyəm.", xp: 10 },
            { id: "en6-fut-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["The", "film", "will", "start", "soon"], answer: "The film will start soon", translation: "Film tezliklə başlayacaq.", xp: 10 },
            { id: "en6-fut-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "are", "going", "to", "cook"], answer: "We are going to cook", translation: "Biz bişirəcəyik.", xp: 10 },
            { id: "en6-fut-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "will", "come", "later"], answer: "She will come later", translation: "O sonra gələcək.", xp: 10 },
            { id: "en6-fut-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["What", "will", "you", "do"], answer: "What will you do", translation: "Nə edəcəksən?", xp: 10 },
            { id: "en6-fut-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "am", "going", "to", "buy", "it"], answer: "I am going to buy it", translation: "Onu alacağam.", xp: 10 },
            { id: "en6-fut-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["They", "will", "arrive", "at", "six"], answer: "They will arrive at six", translation: "Onlar altıda çatacaq.", xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-fut-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "are", "going", "to", "have", "a", "party"], answer: "We are going to have a party", translation: "Şənlik keçirəcəyik.", xp: 15 },
            { id: "en6-fut-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "think", "it", "will", "be", "sunny"], answer: "I think it will be sunny", translation: "Məncə günəşli olacaq.", xp: 15 },
            { id: "en6-fut-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Will", "it", "snow", "tomorrow"], answer: "Will it snow tomorrow", translation: "Sabah qar yağacaq?", xp: 15 },
          ],
        },
      ],
    },
    {
      id: "en6-quant",
      title: "Sayıla bilən/bilməyən + some/any/much/many",
      description: "Countable/uncountable isimlər və miqdar sözləri.",
      lessons: [
        {
          id: "en6-quant-rule",
          title: "Qayda: countable / uncountable",
          intro: "Sayıla bilən isimlərin cəmi olur (apple → apples). Sayıla bilməyən isimlərin cəmi olmur (water, rice, money).",
          sections: [
            { heading: "İki növ isim", body: "Countable (sayıla bilən): a book, two books. Uncountable (sayıla bilməyən): water, milk, rice, money, bread — cəmi YOX, 'a/an' işlənmir." },
            { heading: "some / any", body: "some — təsdiqdə (I have some water). any — inkar və sualda (I don't have any money. Do you have any books?)." },
            { heading: "much / many / a lot of", body: "much — uncountable ilə (much water). many — countable ilə (many books). a lot of — hər ikisi ilə." },
          ],
          tasks: [
            { id: "en6-quant-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "Hansı sayıla BİLMƏYƏN isimdir?", options: ["water", "book", "apple", "car"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "Hansı sayıla BİLƏN isimdir?", options: ["chair", "milk", "rice", "money"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'I have ___ water.' (təsdiq)", options: ["some", "any", "many", "a"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'I don't have ___ money.' (inkar)", options: ["any", "some", "many", "much of"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'Do you have ___ questions?' (sual)", options: ["any", "some", "much", "a"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "'How ___ water do you drink?'", options: ["much", "many", "some", "any"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'How ___ books do you have?'", options: ["many", "much", "some", "a"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'There is ___ milk in the fridge.'", options: ["some", "many", "an", "a few"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'There aren't ___ apples.'", options: ["any", "some", "much", "a"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'She has ___ friends.' (çoxlu, countable)", options: ["many", "much", "a", "some of"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'We don't have ___ time.' (uncountable)", options: ["much", "many", "some", "a"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t12", type: "fill_blank", prompt: "Cümləni tamamla: 'I have a ___ books.' (bir neçə, countable)", accepted: ["few"], xp: 10 },
            { id: "en6-quant-rule-t13", type: "fill_blank", prompt: "Cümləni tamamla: 'I have a ___ water.' (bir az, uncountable)", accepted: ["little"], xp: 10 },
            { id: "en6-quant-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'There are a ___ of people here.'", options: ["lot", "much", "many", "little"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-rule-t15", type: "multiple_choice", prompt: "'much' hansı isimlə işlənir?", options: ["sayıla bilməyən (uncountable)", "sayıla bilən cəm", "yalnız insan", "yalnız heyvan"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-quant-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'How much ___?'", options: ["sugar", "apples", "books", "chairs"], correctIndex: 0, xp: 15 },
            { id: "en6-quant-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'Would you like ___ tea?' (təklif)", options: ["some", "any", "many", "a"], correctIndex: 0, xp: 15 },
            { id: "en6-quant-rule-b3", type: "fill_blank", prompt: "Boşluğu doldur: 'There isn't ___ bread.' (inkar)", accepted: ["any"], xp: 15 },
            { id: "en6-quant-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "Hansı düzgündür?", options: ["a few apples", "a few water", "much apples", "many water"], correctIndex: 0, xp: 15 },
            { id: "en6-quant-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "Hansı düzgündür?", options: ["a little milk", "a little books", "many milk", "much book"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en6-quant-listen",
          title: "Dinləmə: miqdar",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün Azərbaycanca tərcüməni seç." },
          ],
          tasks: [
            { id: "en6-quant-listen-t1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I have some water.", options: ["Bir az suyum var.", "Suyum yoxdur.", "Çoxlu suyum var.", "Su istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I don't have any money.", options: ["Heç pulum yoxdur.", "Bir az pulum var.", "Çoxlu pulum var.", "Pul istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t3", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "How much sugar do you want?", options: ["Nə qədər şəkər istəyirsən?", "Neçə alma istəyirsən?", "Şəkər sevirsən?", "Şəkərin var?"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t4", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "How many books do you have?", options: ["Neçə kitabın var?", "Nə qədər suyun var?", "Kitab sevirsən?", "Kitab oxuyursan?"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t5", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "There is a little milk.", options: ["Bir az süd var.", "Çoxlu süd var.", "Süd yoxdur.", "Süd istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t6", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "There are many people here.", options: ["Burada çoxlu adam var.", "Burada az adam var.", "Burada adam yoxdur.", "Adamlar gedir."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t7", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Do you have any questions?", options: ["Hər hansı sualın var?", "Sualın yoxdur?", "Cavabın var?", "Sual verirsən?"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t8", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We don't have much time.", options: ["Çox vaxtımız yoxdur.", "Çoxlu vaxtımız var.", "Vaxtımız var.", "Gecdir."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t9", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "She has a few friends.", options: ["Onun bir neçə dostu var.", "Onun çoxlu dostu var.", "Onun dostu yoxdur.", "O dost axtarır."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t10", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "There isn't any bread.", options: ["Heç çörək yoxdur.", "Bir az çörək var.", "Çoxlu çörək var.", "Çörək alıram."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t11", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I need some help.", options: ["Bir az köməyə ehtiyacım var.", "Köməyə ehtiyacım yoxdur.", "Kömək edirəm.", "Kömək etmə."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t12", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Would you like some tea?", options: ["Bir az çay istəyirsən?", "Çay sevmirsən?", "Çay içdin?", "Çayın var?"], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t13", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "There are a lot of cars.", options: ["Çoxlu maşın var.", "Az maşın var.", "Maşın yoxdur.", "Maşın gedir."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t14", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "I have a little money.", options: ["Bir az pulum var.", "Çoxlu pulum var.", "Pulum yoxdur.", "Pul lazımdır."], correctIndex: 0, xp: 10 },
            { id: "en6-quant-listen-t15", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "There aren't many apples.", options: ["Çox alma yoxdur.", "Çoxlu alma var.", "Alma yoxdur.", "Alma alıram."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-quant-listen-b1", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "How much does it cost?", options: ["Neçəyədir?", "Neçə dənədir?", "Harададır?", "Nə vaxtdır?"], correctIndex: 0, xp: 15 },
            { id: "en6-quant-listen-b2", type: "listening", prompt: "Dinlə və cümlənin mənasını seç.", audioText: "We have plenty of food.", options: ["Bol yeməyimiz var.", "Yeməyimiz yoxdur.", "Az yeməyimiz var.", "Yemək bişiririk."], correctIndex: 0, xp: 15 },
            { id: "en6-quant-listen-b3", type: "listening", prompt: "Dinlə və sualın mənasını seç.", audioText: "Is there any sugar left?", options: ["Şəkər qalıb?", "Şəkər aldın?", "Şəkər sevirsən?", "Şəkər lazımdır?"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en6-quant-write",
          title: "Cümlə qur: miqdar",
          intro: "Sözləri düzgün sıraya düz və miqdar cümləsi qur.",
          sections: [
            { heading: "Necə işləyir?", body: "Sözlərə sıra ilə bas. some/any + isim; much/many + isim; how much/how many sualda." },
          ],
          tasks: [
            { id: "en6-quant-write-t1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "have", "some", "water"], answer: "I have some water", translation: "Bir az suyum var.", xp: 10 },
            { id: "en6-quant-write-t2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "don't", "have", "any", "money"], answer: "I don't have any money", translation: "Heç pulum yoxdur.", xp: 10 },
            { id: "en6-quant-write-t3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["How", "much", "sugar"], answer: "How much sugar", translation: "Nə qədər şəkər?", xp: 10 },
            { id: "en6-quant-write-t4", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["How", "many", "books"], answer: "How many books", translation: "Neçə kitab?", xp: 10 },
            { id: "en6-quant-write-t5", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["There", "are", "many", "people"], answer: "There are many people", translation: "Çoxlu adam var.", xp: 10 },
            { id: "en6-quant-write-t6", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["There", "is", "some", "milk"], answer: "There is some milk", translation: "Bir az süd var.", xp: 10 },
            { id: "en6-quant-write-t7", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "don't", "have", "much", "time"], answer: "We don't have much time", translation: "Çox vaxtımız yoxdur.", xp: 10 },
            { id: "en6-quant-write-t8", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Do", "you", "have", "any", "questions"], answer: "Do you have any questions", translation: "Sualın var?", xp: 10 },
            { id: "en6-quant-write-t9", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["She", "has", "a", "few", "friends"], answer: "She has a few friends", translation: "Onun bir neçə dostu var.", xp: 10 },
            { id: "en6-quant-write-t10", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "have", "a", "little", "water"], answer: "I have a little water", translation: "Bir az suyum var.", xp: 10 },
            { id: "en6-quant-write-t11", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["There", "are", "a", "lot", "of", "cars"], answer: "There are a lot of cars", translation: "Çoxlu maşın var.", xp: 10 },
            { id: "en6-quant-write-t12", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["There", "isn't", "any", "bread"], answer: "There isn't any bread", translation: "Heç çörək yoxdur.", xp: 10 },
            { id: "en6-quant-write-t13", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Would", "you", "like", "some", "tea"], answer: "Would you like some tea", translation: "Bir az çay istəyirsən?", xp: 10 },
            { id: "en6-quant-write-t14", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["I", "need", "some", "help"], answer: "I need some help", translation: "Bir az köməyə ehtiyacım var.", xp: 10 },
            { id: "en6-quant-write-t15", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["There", "aren't", "many", "apples"], answer: "There aren't many apples", translation: "Çox alma yoxdur.", xp: 15 },
          ],
          bonusTasks: [
            { id: "en6-quant-write-b1", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["How", "much", "does", "it", "cost"], answer: "How much does it cost", translation: "Neçəyədir?", xp: 15 },
            { id: "en6-quant-write-b2", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["We", "have", "a", "lot", "of", "food"], answer: "We have a lot of food", translation: "Çoxlu yeməyimiz var.", xp: 15 },
            { id: "en6-quant-write-b3", type: "word_order", prompt: "Sözləri düzgün sıraya düz.", words: ["Is", "there", "any", "sugar"], answer: "Is there any sugar", translation: "Şəkər var?", xp: 15 },
          ],
        },
      ],
    },
  ],
};
