// İngilis dili — 2-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 1-20 və yaş  2) Günlər və aylar  3) Yemək və içki
// 4) Oyuncaqlar və əşyalar (this/that, cəm)  5) Hərəkətlər (verbs)  6) Bədən, geyim, hava.
// 2-ci sinif üçün sadə: şəkil-söz + dinləmə + speakOptions. id prefiksi en2-*.

import type { Subject } from "../types";

export const english2: Subject = {
  slug: "ingilis-dili-2",
  name: "İngilis dili",
  grade: 2,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Ədədlər 1-20 və yaş ═══════════════
    {
      id: "en2-numbers",
      title: "Ədədlər 1-20 və yaş",
      description: "İngiliscə 1-dən 20-yə qədər ədədlər və yaş.",
      lessons: [
        {
          id: "en2-numbers-vocab",
          title: "Numbers 11-20",
          intro: "On birdən iyirmiyə qədər İngiliscə saymaq.",
          sections: [
            { heading: "Sözlər", body: "eleven — 11, twelve — 12, thirteen — 13, fourteen — 14, fifteen — 15, sixteen — 16, seventeen — 17, eighteen — 18, nineteen — 19, twenty — 20." },
            { heading: "Yaş", body: "'How old are you?' — Neçə yaşın var? 'I am eight.' — Səkkiz yaşım var." },
          ],
          tasks: [
            { id: "en2-numbers-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'11' İngiliscə necədir?", options: ["eleven", "twelve", "ten", "twenty"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'12' İngiliscə necədir?", options: ["twelve", "eleven", "twenty", "two"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'13' İngiliscə necədir?", options: ["thirteen", "thirty", "three", "thirteen"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'15' İngiliscə necədir?", options: ["fifteen", "fifty", "five", "fourteen"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'20' İngiliscə necədir?", options: ["twenty", "twelve", "two", "ten"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'17' İngiliscə necədir?", options: ["seventeen", "seventy", "seven", "sixteen"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'18' İngiliscə necədir?", options: ["eighteen", "eighty", "eight", "nineteen"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t8", type: "multiple_choice", prompt: "'fourteen' hansı ədəddir?", options: ["14", "40", "4", "13"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t9", type: "multiple_choice", prompt: "'sixteen' hansı ədəddir?", options: ["16", "60", "6", "15"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t10", type: "multiple_choice", prompt: "'nineteen' hansı ədəddir?", options: ["19", "90", "9", "18"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t11", type: "multiple_choice", prompt: "'twenty' hansı ədəddir?", options: ["20", "12", "2", "10"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'How old are you?' nə deməkdir?", options: ["Neçə yaşın var?", "Adın nədir?", "Necəsən?", "Haralısan?"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'I am eight.' nə deməkdir?", options: ["Səkkiz yaşım var.", "Adım Aytəkindir.", "Mən yaxşıyam.", "Səkkizinci mərtəbə."], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t14", type: "multiple_choice", prompt: "'thirteen' hansı ədəddir?", options: ["13", "30", "3", "14"], correctIndex: 0, xp: 10 },
            { id: "en2-numbers-vocab-t15", type: "multiple_choice", prompt: "🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎 — İngiliscə neçədir? (11)", options: ["eleven", "twelve", "ten", "nine"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en2-numbers-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'thirty' hansı ədəddir?", options: ["30", "13", "3", "40"], correctIndex: 0, xp: 15 },
            { id: "en2-numbers-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'fifty' hansı ədəddir?", options: ["50", "15", "5", "40"], correctIndex: 0, xp: 15 },
            { id: "en2-numbers-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'one hundred' hansı ədəddir?", options: ["100", "10", "1000", "1"], correctIndex: 0, xp: 15 },
            { id: "en2-numbers-vocab-b4", type: "multiple_choice", prompt: "'thirteen' və 'thirty' fərqi nədir?", options: ["13 və 30", "eynidir", "3 və 13", "30 və 3"], correctIndex: 0, xp: 15 },
            { id: "en2-numbers-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'I am ten years old.' nə deməkdir?", options: ["On yaşım var.", "On dəqiqə qaldı.", "Onuncu sinif.", "Saat on."], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 2. Günlər və aylar ═══════════════
    {
      id: "en2-days",
      title: "Günlər və aylar (Days & Months)",
      description: "Həftənin günləri və fəsillər.",
      lessons: [
        {
          id: "en2-days-vocab",
          title: "Days & seasons",
          intro: "Həftənin günləri və fəsilləri İngiliscə öyrənək.",
          sections: [
            { heading: "Günlər", body: "Monday — bazar ertəsi, Tuesday — çərşənbə axşamı, Wednesday — çərşənbə, Thursday — cümə axşamı, Friday — cümə, Saturday — şənbə, Sunday — bazar." },
            { heading: "Fəsillər", body: "spring — yaz, summer — yay, autumn — payız, winter — qış." },
          ],
          tasks: [
            { id: "en2-days-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'bazar ertəsi' İngiliscə necədir?", options: ["Monday", "Sunday", "Friday", "Tuesday"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'cümə' İngiliscə necədir?", options: ["Friday", "Monday", "Sunday", "Saturday"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'şənbə' İngiliscə necədir?", options: ["Saturday", "Sunday", "Friday", "Monday"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'bazar' İngiliscə necədir?", options: ["Sunday", "Saturday", "Monday", "Friday"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t5", type: "multiple_choice", prompt: "'Monday' nə deməkdir?", options: ["bazar ertəsi", "bazar", "cümə", "şənbə"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t6", type: "multiple_choice", prompt: "'Sunday' nə deməkdir?", options: ["bazar", "şənbə", "cümə", "bazar ertəsi"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'yaz' (fəsil) İngiliscə necədir?", options: ["spring", "summer", "autumn", "winter"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'yay' İngiliscə necədir?", options: ["summer", "spring", "winter", "autumn"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'payız' İngiliscə necədir?", options: ["autumn", "summer", "spring", "winter"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'qış' İngiliscə necədir?", options: ["winter", "autumn", "summer", "spring"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t11", type: "multiple_choice", prompt: "'summer' nə deməkdir?", options: ["yay", "yaz", "qış", "payız"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t12", type: "multiple_choice", prompt: "'winter' nə deməkdir?", options: ["qış", "yay", "yaz", "payız"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'today' nə deməkdir?", options: ["bu gün", "sabah", "dünən", "həftə"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'tomorrow' nə deməkdir?", options: ["sabah", "bu gün", "dünən", "indi"], correctIndex: 0, xp: 10 },
            { id: "en2-days-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'week' nə deməkdir?", options: ["həftə", "gün", "ay", "il"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en2-days-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'yesterday' nə deməkdir?", options: ["dünən", "bu gün", "sabah", "indi"], correctIndex: 0, xp: 15 },
            { id: "en2-days-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'month' nə deməkdir?", options: ["ay", "həftə", "gün", "il"], correctIndex: 0, xp: 15 },
            { id: "en2-days-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'January' hansı aydır?", options: ["yanvar", "iyun", "may", "dekabr"], correctIndex: 0, xp: 15 },
            { id: "en2-days-vocab-b4", type: "multiple_choice", prompt: "'Wednesday' nə deməkdir?", options: ["çərşənbə", "cümə", "şənbə", "bazar"], correctIndex: 0, xp: 15 },
            { id: "en2-days-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'year' nə deməkdir?", options: ["il", "ay", "həftə", "gün"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 3. Yemək və içki ═══════════════
    {
      id: "en2-food",
      title: "Yemək və içki (Food & Drinks)",
      description: "Yemək və içkilərin İngiliscə adları.",
      lessons: [
        {
          id: "en2-food-vocab",
          title: "Food & drinks",
          intro: "Yemək və içkiləri İngiliscə öyrənək.",
          sections: [
            { heading: "Sözlər", body: "bread — çörək, milk — süd, water — su, apple — alma, egg — yumurta, meat — ət, rice — düyü, tea — çay, juice — şirə, cheese — pendir." },
          ],
          tasks: [
            { id: "en2-food-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "🍞 İngiliscə necədir?", options: ["bread", "milk", "water", "egg"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "🥛 İngiliscə necədir?", options: ["milk", "water", "juice", "tea"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "💧 (su) İngiliscə necədir?", options: ["water", "milk", "juice", "tea"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "🍎 İngiliscə necədir?", options: ["apple", "egg", "meat", "rice"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "🥚 İngiliscə necədir?", options: ["egg", "apple", "cheese", "bread"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'ət' İngiliscə necədir?", options: ["meat", "rice", "egg", "milk"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'düyü' İngiliscə necədir?", options: ["rice", "meat", "bread", "egg"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'çay' İngiliscə necədir?", options: ["tea", "juice", "milk", "water"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'şirə' İngiliscə necədir?", options: ["juice", "tea", "milk", "water"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t10", type: "multiple_choice", prompt: "'bread' nə deməkdir?", options: ["çörək", "süd", "su", "alma"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t11", type: "multiple_choice", prompt: "'milk' nə deməkdir?", options: ["süd", "su", "çay", "şirə"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t12", type: "multiple_choice", prompt: "'apple' nə deməkdir?", options: ["alma", "armud", "yumurta", "ət"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t13", type: "multiple_choice", prompt: "'cheese' nə deməkdir?", options: ["pendir", "süd", "çörək", "ət"], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'I like apples.' nə deməkdir?", options: ["Almaları sevirəm.", "Alma yeyirəm.", "Almam var.", "Alma alıram."], correctIndex: 0, xp: 10 },
            { id: "en2-food-vocab-t15", type: "multiple_choice", prompt: "'water' nə deməkdir?", options: ["su", "süd", "çay", "şirə"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en2-food-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "🍌 İngiliscə necədir?", options: ["banana", "apple", "egg", "meat"], correctIndex: 0, xp: 15 },
            { id: "en2-food-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "🍕 İngiliscə necədir?", options: ["pizza", "bread", "cheese", "rice"], correctIndex: 0, xp: 15 },
            { id: "en2-food-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'I am hungry.' nə deməkdir?", options: ["Acmışam.", "Susamışam.", "Yorğunam.", "Toxam."], correctIndex: 0, xp: 15 },
            { id: "en2-food-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'fish' (yemək) nə deməkdir?", options: ["balıq", "ət", "toyuq", "yumurta"], correctIndex: 0, xp: 15 },
            { id: "en2-food-vocab-b5", type: "multiple_choice", prompt: "'egg' nə deməkdir?", options: ["yumurta", "alma", "pendir", "çörək"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en2-food-listen",
          title: "Dinləmə: yemək",
          intro: "Sözü dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, İngiliscə sözü dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en2-food-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "bread", options: ["çörək", "süd", "su", "alma"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "milk", options: ["süd", "su", "çay", "şirə"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "water", options: ["su", "süd", "çay", "şirə"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "apple", options: ["alma", "armud", "yumurta", "ət"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "egg", options: ["yumurta", "alma", "pendir", "çörək"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "meat", options: ["ət", "düyü", "yumurta", "süd"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "rice", options: ["düyü", "ət", "çörək", "yumurta"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "tea", options: ["çay", "şirə", "süd", "su"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "juice", options: ["şirə", "çay", "süd", "su"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "cheese", options: ["pendir", "süd", "çörək", "ət"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "banana", options: ["banan", "alma", "üzüm", "nar"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "fish", options: ["balıq", "ət", "toyuq", "yumurta"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I like milk", options: ["Südü sevirəm", "Su içirəm", "Süd alıram", "Süd yoxdur"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I want water", options: ["Su istəyirəm", "Su içdim", "Su yoxdur", "Süd istəyirəm"], correctIndex: 0, xp: 10 },
            { id: "en2-food-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "The apple is red", options: ["Alma qırmızıdır", "Alma yaşıldır", "Alma böyükdür", "Alma şirindir"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en2-food-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I am hungry", options: ["Acmışam", "Susamışam", "Yorğunam", "Toxam"], correctIndex: 0, xp: 15 },
            { id: "en2-food-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Do you like tea?", options: ["Çayı sevirsən?", "Çay içdin?", "Çay var?", "Süd sevirsən?"], correctIndex: 0, xp: 15 },
            { id: "en2-food-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "chicken", options: ["toyuq", "balıq", "ət", "yumurta"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 4. Oyuncaqlar və əşyalar ═══════════════
    {
      id: "en2-things",
      title: "Oyuncaqlar və əşyalar (Toys & Things)",
      description: "Oyuncaq və əşyaların adları, this/that, cəm (-s).",
      lessons: [
        {
          id: "en2-things-vocab",
          title: "Toys & this/that",
          intro: "Oyuncaqları öyrənək və 'this/that' işlədək.",
          sections: [
            { heading: "Sözlər", body: "ball — top, doll — kukla, car — maşın, kite — uçurtma, teddy bear — pəluş ayı, balloon — şar, bike — velosiped, book — kitab." },
            { heading: "this / that", body: "this — bu (yaxın), that — o (uzaq). 'This is a ball.' — Bu topdur. Cəmdə -s əlavə olunur: ball → balls." },
          ],
          tasks: [
            { id: "en2-things-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "⚽ İngiliscə necədir?", options: ["ball", "doll", "car", "kite"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "🚗 İngiliscə necədir?", options: ["car", "ball", "kite", "doll"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "🎈 İngiliscə necədir?", options: ["balloon", "ball", "kite", "doll"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'kukla' İngiliscə necədir?", options: ["doll", "ball", "car", "bike"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'velosiped' İngiliscə necədir?", options: ["bike", "car", "ball", "kite"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'uçurtma' İngiliscə necədir?", options: ["kite", "ball", "doll", "car"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t7", type: "multiple_choice", prompt: "'ball' nə deməkdir?", options: ["top", "maşın", "kukla", "şar"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t8", type: "multiple_choice", prompt: "'car' nə deməkdir?", options: ["maşın", "top", "velosiped", "şar"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'this' nə deməkdir?", options: ["bu (yaxın)", "o (uzaq)", "onlar", "burada"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'that' nə deməkdir?", options: ["o (uzaq)", "bu (yaxın)", "biz", "orada"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'This is a car.' nə deməkdir?", options: ["Bu maşındır.", "O maşındır.", "Maşınlar.", "Maşın var."], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'ball' sözünün cəmi hansıdır?", options: ["balls", "balles", "ball", "balls's"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'car' sözünün cəmi hansıdır?", options: ["cars", "cares", "car", "carz"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t14", type: "multiple_choice", prompt: "'balloon' nə deməkdir?", options: ["şar", "top", "kukla", "maşın"], correctIndex: 0, xp: 10 },
            { id: "en2-things-vocab-t15", type: "multiple_choice", prompt: "'teddy bear' nə deməkdir?", options: ["pəluş ayı", "kukla", "top", "maşın"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en2-things-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'These are dolls.' nə deməkdir?", options: ["Bunlar kuklalardır.", "Bu kukladır.", "O kukladır.", "Kukla var."], correctIndex: 0, xp: 15 },
            { id: "en2-things-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'doll' sözünün cəmi hansıdır?", options: ["dolls", "dolles", "dollies", "doll"], correctIndex: 0, xp: 15 },
            { id: "en2-things-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'I have a bike.' nə deməkdir?", options: ["Velosipedim var.", "Velosiped sürürəm.", "Velosiped istəyirəm.", "Velosiped yoxdur."], correctIndex: 0, xp: 15 },
            { id: "en2-things-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'What is this?' nə deməkdir?", options: ["Bu nədir?", "O nədir?", "Sən kimsən?", "Bu haradadır?"], correctIndex: 0, xp: 15 },
            { id: "en2-things-vocab-b5", type: "multiple_choice", prompt: "'kite' nə deməkdir?", options: ["uçurtma", "şar", "top", "kukla"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 5. Hərəkətlər ═══════════════
    {
      id: "en2-actions",
      title: "Hərəkətlər (Actions)",
      description: "Feillər: run, jump, eat, read və s.",
      lessons: [
        {
          id: "en2-actions-vocab",
          title: "Action verbs",
          intro: "Hərəkət bildirən sözləri öyrənək.",
          sections: [
            { heading: "Sözlər", body: "run — qaçmaq, jump — tullanmaq, eat — yemək, drink — içmək, read — oxumaq, write — yazmaq, sit — oturmaq, stand — durmaq, play — oynamaq, sleep — yatmaq." },
          ],
          tasks: [
            { id: "en2-actions-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'qaçmaq' İngiliscə necədir?", options: ["run", "jump", "eat", "sit"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'tullanmaq' İngiliscə necədir?", options: ["jump", "run", "read", "sleep"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'yemək' İngiliscə necədir?", options: ["eat", "drink", "run", "write"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'içmək' İngiliscə necədir?", options: ["drink", "eat", "read", "sit"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'oxumaq' İngiliscə necədir?", options: ["read", "write", "run", "play"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'yazmaq' İngiliscə necədir?", options: ["write", "read", "eat", "jump"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'oturmaq' İngiliscə necədir?", options: ["sit", "stand", "run", "sleep"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'durmaq' İngiliscə necədir?", options: ["stand", "sit", "jump", "eat"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'oynamaq' İngiliscə necədir?", options: ["play", "run", "read", "write"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'yatmaq' İngiliscə necədir?", options: ["sleep", "sit", "eat", "run"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t11", type: "multiple_choice", prompt: "'run' nə deməkdir?", options: ["qaçmaq", "tullanmaq", "yemək", "oxumaq"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t12", type: "multiple_choice", prompt: "'eat' nə deməkdir?", options: ["yemək", "içmək", "qaçmaq", "yazmaq"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t13", type: "multiple_choice", prompt: "'read' nə deməkdir?", options: ["oxumaq", "yazmaq", "yatmaq", "oynamaq"], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'I can run.' nə deməkdir?", options: ["Qaça bilirəm.", "Qaçıram.", "Qaçdım.", "Qaçacağam."], correctIndex: 0, xp: 10 },
            { id: "en2-actions-vocab-t15", type: "multiple_choice", prompt: "'sleep' nə deməkdir?", options: ["yatmaq", "oturmaq", "durmaq", "yemək"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en2-actions-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'swim' nə deməkdir?", options: ["üzmək", "qaçmaq", "tullanmaq", "uçmaq"], correctIndex: 0, xp: 15 },
            { id: "en2-actions-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'sing' nə deməkdir?", options: ["oxumaq (mahnı)", "rəqs etmək", "danışmaq", "gülmək"], correctIndex: 0, xp: 15 },
            { id: "en2-actions-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'dance' nə deməkdir?", options: ["rəqs etmək", "oxumaq", "qaçmaq", "tullanmaq"], correctIndex: 0, xp: 15 },
            { id: "en2-actions-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'Stand up!' nə deməkdir?", options: ["Ayağa qalx!", "Otur!", "Qaç!", "Yat!"], correctIndex: 0, xp: 15 },
            { id: "en2-actions-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'Sit down!' nə deməkdir?", options: ["Otur!", "Ayağa qalx!", "Qaç!", "Oxu!"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 6. Bədən, geyim və hava ═══════════════
    {
      id: "en2-body",
      title: "Bədən, geyim və hava (Body, Clothes, Weather)",
      description: "Bədən üzvləri, geyimlər və hava sözləri.",
      lessons: [
        {
          id: "en2-body-vocab",
          title: "Body, clothes & weather",
          intro: "Bədən, geyim və hava sözlərini öyrənək.",
          sections: [
            { heading: "Bədən", body: "head — baş, hand — əl, leg — ayaq, eye — göz, ear — qulaq, nose — burun, mouth — ağız, hair — saç." },
            { heading: "Geyim və hava", body: "shirt — köynək, shoes — ayaqqabı, hat — papaq, coat — palto. Hava: sunny — günəşli, rainy — yağışlı, cold — soyuq, hot — isti." },
          ],
          tasks: [
            { id: "en2-body-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'baş' İngiliscə necədir?", options: ["head", "hand", "leg", "eye"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'əl' İngiliscə necədir?", options: ["hand", "head", "leg", "ear"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'ayaq' İngiliscə necədir?", options: ["leg", "hand", "head", "eye"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'göz' İngiliscə necədir?", options: ["eye", "ear", "nose", "mouth"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'qulaq' İngiliscə necədir?", options: ["ear", "eye", "nose", "hair"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'burun' İngiliscə necədir?", options: ["nose", "mouth", "ear", "eye"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'ağız' İngiliscə necədir?", options: ["mouth", "nose", "ear", "hair"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t8", type: "multiple_choice", prompt: "'head' nə deməkdir?", options: ["baş", "əl", "ayaq", "göz"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t9", type: "multiple_choice", prompt: "'hand' nə deməkdir?", options: ["əl", "baş", "ayaq", "qulaq"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'köynək' İngiliscə necədir?", options: ["shirt", "shoes", "hat", "coat"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'ayaqqabı' İngiliscə necədir?", options: ["shoes", "shirt", "hat", "coat"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'papaq' İngiliscə necədir?", options: ["hat", "coat", "shirt", "shoes"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'günəşli' İngiliscə necədir?", options: ["sunny", "rainy", "cold", "hot"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'yağışlı' İngiliscə necədir?", options: ["rainy", "sunny", "cold", "hot"], correctIndex: 0, xp: 10 },
            { id: "en2-body-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'soyuq' İngiliscə necədir?", options: ["cold", "hot", "sunny", "rainy"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en2-body-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'isti' (hava) İngiliscə necədir?", options: ["hot", "cold", "rainy", "sunny"], correctIndex: 0, xp: 15 },
            { id: "en2-body-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'It is sunny.' nə deməkdir?", options: ["Hava günəşlidir.", "Hava yağışlıdır.", "Soyuqdur.", "İstidir."], correctIndex: 0, xp: 15 },
            { id: "en2-body-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'hair' nə deməkdir?", options: ["saç", "baş", "qulaq", "göz"], correctIndex: 0, xp: 15 },
            { id: "en2-body-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'coat' nə deməkdir?", options: ["palto", "köynək", "papaq", "ayaqqabı"], correctIndex: 0, xp: 15 },
            { id: "en2-body-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'It is cold today.' nə deməkdir?", options: ["Bu gün soyuqdur.", "Bu gün istidir.", "Bu gün günəşlidir.", "Bu gün yağışlıdır."], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
  ],
};
