// İngilis dili — 3-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Present Simple (I/you/we/they)  2) Have got  3) Can/can't
// 4) Sözönləri (in/on/under)  5) Gündəlik rejim və saat  6) Peşələr və şəhər.
// 3-cü sinif üçün sadə: qısa qrammatika + şəkil-söz + dinləmə. id prefiksi en3-*.

import type { Subject } from "../types";

export const english3: Subject = {
  slug: "ingilis-dili-3",
  name: "İngilis dili",
  grade: 3,
  icon: "E",
  color: "violet",
  units: [
    // ═══════════════ 1. Present Simple ═══════════════
    {
      id: "en3-present",
      title: "Present Simple (I like, you play)",
      description: "İndiki sadə zaman: I/you/we/they + feil.",
      lessons: [
        {
          id: "en3-present-rule",
          title: "Qayda: Present Simple",
          intro: "Adət və gündəlik işlər üçün: I play, you like, we go.",
          sections: [
            { heading: "Necə işləyir?", body: "Hər gün olan işlər üçün: I play football. You like apples. We go to school. Feil dəyişmir (I/you/we/they ilə)." },
            { heading: "İnkar", body: "don't əlavə olunur: I don't like fish. We don't play." },
          ],
          tasks: [
            { id: "en3-present-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'Mən futbol oynayıram.' İngiliscə hansıdır?", options: ["I play football.", "I football play.", "Play I football.", "I playing football."], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'I ___ apples.' (sevirəm)", options: ["like", "likes", "liking", "liked"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'We ___ to school.' (gedirik)", options: ["go", "goes", "going", "went"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'They ___ English.' (öyrənirlər)", options: ["learn", "learns", "learning", "learned"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'You ___ TV.' (baxırsan)", options: ["watch", "watches", "watching", "watched"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t6", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ like fish.'", options: ["don't", "doesn't", "not", "no"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'I ___ milk every day.' (içirəm)", options: ["drink", "drinks", "drinking", "drank"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t8", type: "multiple_choice", prompt: "'I like cats.' nə deməkdir?", options: ["Pişikləri sevirəm.", "Pişiyim var.", "Pişik gördüm.", "Pişik istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'We ___ in Baku.' (yaşayırıq)", options: ["live", "lives", "living", "lived"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'They ___ football.' (oynayırlar)", options: ["play", "plays", "playing", "played"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'We ___ watch TV.'", options: ["don't", "doesn't", "not", "isn't"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t12", type: "multiple_choice", prompt: "'You go to school.' nə deməkdir?", options: ["Sən məktəbə gedirsən.", "Məktəbə get.", "Məktəbə getdin.", "Məktəb böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'I ___ books.' (oxuyuram)", options: ["read", "reads", "reading", "readed"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'We ___ music.' (sevirik)", options: ["like", "likes", "liking", "liked"], correctIndex: 0, xp: 10 },
            { id: "en3-present-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'I ___ juice.' (içmirəm — inkar)", options: ["don't drink", "doesn't drink", "not drink", "drink not"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-present-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'They don't like fish.' nə deməkdir?", options: ["Balığı sevmirlər.", "Balığı sevirlər.", "Balıq yoxdur.", "Balıq istəyirlər."], correctIndex: 0, xp: 15 },
            { id: "en3-present-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "'I ___ my teeth every morning.' (təmizləyirəm)", options: ["brush", "brushes", "brushing", "brushed"], correctIndex: 0, xp: 15 },
            { id: "en3-present-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'We ___ breakfast at 8.' (yeyirik)", options: ["have", "has", "having", "had"], correctIndex: 0, xp: 15 },
            { id: "en3-present-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'Do you like ice cream?' nə deməkdir?", options: ["Dondurmanı sevirsən?", "Dondurma var?", "Dondurma istəyirsən?", "Dondurma yedin?"], correctIndex: 0, xp: 15 },
            { id: "en3-present-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'I ___ football, I like basketball.' (inkar)", options: ["don't play", "doesn't play", "not play", "play not"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "en3-present-listen",
          title: "Dinləmə: Present Simple",
          intro: "Cümləni dinlə və mənasını seç.",
          sections: [
            { heading: "Necə işləyir?", body: "Səs düyməsinə bas, cümləni dinlə, düzgün mənasını seç." },
          ],
          tasks: [
            { id: "en3-present-listen-t1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I play football.", options: ["Futbol oynayıram.", "Futbol oynadım.", "Futbolu sevirəm.", "Futbol oynamıram."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I like apples.", options: ["Almaları sevirəm.", "Alma yeyirəm.", "Almam var.", "Alma istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We go to school.", options: ["Məktəbə gedirik.", "Məktəbə getdik.", "Məktəbdəyik.", "Məktəb böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t4", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They learn English.", options: ["İngiliscə öyrənirlər.", "İngiliscə bilirlər.", "İngiliscə danışırlar.", "İngiliscə öyrəndilər."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t5", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I drink milk.", options: ["Süd içirəm.", "Su içirəm.", "Süd sevirəm.", "Süd aldım."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t6", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "You watch TV.", options: ["Televizora baxırsan.", "Televizor aldın.", "Televizora bax.", "Televizor böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t7", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We live in Baku.", options: ["Bakıda yaşayırıq.", "Bakıya gedirik.", "Bakı gözəldir.", "Bakıda idik."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t8", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I don't like fish.", options: ["Balığı sevmirəm.", "Balığı sevirəm.", "Balıq yeyirəm.", "Balıq yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t9", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They play in the park.", options: ["Parkda oynayırlar.", "Parka gedirlər.", "Park böyükdür.", "Parkda idilər."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t10", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I read books.", options: ["Kitab oxuyuram.", "Kitab alıram.", "Kitabım var.", "Kitab yazıram."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t11", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We like music.", options: ["Musiqini sevirik.", "Musiqi çalırıq.", "Musiqi dinləyirik.", "Musiqi yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t12", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "You have breakfast.", options: ["Səhər yeməyi yeyirsən.", "Səhər yeməyi bişirdin.", "Səhər yeməyin var.", "Səhər durursan."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t13", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I don't watch TV.", options: ["Televizora baxmıram.", "Televizora baxıram.", "Televizor yoxdur.", "Televizora baxdım."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t14", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "They go home.", options: ["Evə gedirlər.", "Evdədirlər.", "Evə getdilər.", "Ev böyükdür."], correctIndex: 0, xp: 10 },
            { id: "en3-present-listen-t15", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We like ice cream.", options: ["Dondurmanı sevirik.", "Dondurma yeyirik.", "Dondurma aldıq.", "Dondurma yoxdur."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-present-listen-b1", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "I brush my teeth every day.", options: ["Hər gün dişlərimi təmizləyirəm.", "Dişlərim ağrıyır.", "Diş fırçam var.", "Dişimi çəkdirdim."], correctIndex: 0, xp: 15 },
            { id: "en3-present-listen-b2", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "Do you like cats?", options: ["Pişikləri sevirsən?", "Pişiyin var?", "Pişik gördün?", "Pişik istəyirsən?"], correctIndex: 0, xp: 15 },
            { id: "en3-present-listen-b3", type: "listening", prompt: "Dinlə və mənasını seç.", audioText: "We don't eat meat.", options: ["Ət yemirik.", "Ət yeyirik.", "Ət aldıq.", "Ət yoxdur."], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 2. Have got ═══════════════
    {
      id: "en3-havegot",
      title: "Have got (məndə var)",
      description: "Sahiblik: I have got, you have got, he/she has got.",
      lessons: [
        {
          id: "en3-havegot-rule",
          title: "Qayda: have got / has got",
          intro: "Nəyəsə sahib olmaq: I have got a dog. She has got a cat.",
          sections: [
            { heading: "have / has got", body: "I/you/we/they → have got. he/she/it → has got. 'I have got a bike.' — Velosipedim var. 'She has got a doll.' — Onun kuklası var." },
            { heading: "İnkar", body: "haven't got / hasn't got: I haven't got a cat." },
          ],
          tasks: [
            { id: "en3-havegot-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ got a dog.' (məndə var)", options: ["have", "has", "am", "is"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ got a cat.' (onda var)", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "'He ___ got a ball.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "'We ___ got books.'", options: ["have", "has", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t5", type: "multiple_choice", speakOptions: true, prompt: "'They ___ got a car.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t6", type: "multiple_choice", prompt: "'I have got a bike.' nə deməkdir?", options: ["Velosipedim var.", "Velosiped istəyirəm.", "Velosiped sürürəm.", "Velosiped aldım."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t7", type: "multiple_choice", prompt: "'She has got a doll.' nə deməkdir?", options: ["Onun kuklası var.", "O kukla aldı.", "Kukla istəyir.", "Kukla oynayır."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'it' (pişik) üçün: 'It ___ got blue eyes.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ got a cat.'", options: ["haven't", "hasn't", "don't", "isn't"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'She ___ got a bike.'", options: ["hasn't", "haven't", "don't", "isn't"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "'My brother ___ got a red car.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t12", type: "multiple_choice", speakOptions: true, prompt: "'You ___ got a nice bag.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t13", type: "multiple_choice", prompt: "'We have got two cats.' nə deməkdir?", options: ["İki pişiyimiz var.", "İki pişik gördük.", "Pişik istəyirik.", "Pişiklər gəldi."], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'The dog ___ got a long tail.'", options: ["has", "have", "is", "are"], correctIndex: 0, xp: 10 },
            { id: "en3-havegot-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'My friends ___ got new bikes.'", options: ["have", "has", "is", "am"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-havegot-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you got a pen?'", options: ["Have", "Has", "Do", "Are"], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-rule-b2", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ she got a sister?'", options: ["Has", "Have", "Do", "Is"], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-rule-b3", type: "multiple_choice", prompt: "'He hasn't got a phone.' nə deməkdir?", options: ["Onun telefonu yoxdur.", "Onun telefonu var.", "Telefon istəyir.", "Telefon aldı."], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'I have got two ___.' (bacı — cəm)", options: ["sisters", "sister", "sisteres", "sisters's"], correctIndex: 0, xp: 15 },
            { id: "en3-havegot-rule-b5", type: "multiple_choice", speakOptions: true, prompt: "'She has got long ___.' (saç)", options: ["hair", "hairs", "a hair", "hairy"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 3. Can / can't ═══════════════
    {
      id: "en3-can",
      title: "Can / can't (bacarıq)",
      description: "Bacarıq bildirmək: I can swim. I can't fly.",
      lessons: [
        {
          id: "en3-can-rule",
          title: "Qayda: can / can't",
          intro: "can — bacarmaq. can + feil (əsas forma).",
          sections: [
            { heading: "can", body: "Bacarıq bildirir: I can swim. She can run. can-dan sonra feil sadə formada gəlir (bütün şəxslərdə eyni)." },
            { heading: "can't", body: "İnkar: cannot / can't. I can't fly. He can't drive." },
          ],
          tasks: [
            { id: "en3-can-rule-t1", type: "multiple_choice", speakOptions: true, prompt: "'I ___ swim.' (üzə bilirəm)", options: ["can", "cans", "am", "do"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t2", type: "multiple_choice", speakOptions: true, prompt: "'She ___ run fast.'", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t3", type: "multiple_choice", speakOptions: true, prompt: "can-dan sonra feil hansı formada gəlir?", options: ["əsas forma (swim)", "V-ing (swimming)", "V2 (swam)", "to + V"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t4", type: "multiple_choice", speakOptions: true, prompt: "İnkar: 'I ___ fly.'", options: ["can't", "don't", "isn't", "not can"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t5", type: "multiple_choice", prompt: "'I can swim.' nə deməkdir?", options: ["Üzə bilirəm.", "Üzürəm.", "Üzdüm.", "Üzmək istəyirəm."], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t6", type: "multiple_choice", prompt: "'He can't drive.' nə deməkdir?", options: ["O sürə bilmir.", "O sürür.", "O sürdü.", "O maşın aldı."], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t7", type: "multiple_choice", speakOptions: true, prompt: "'Birds ___ fly.'", options: ["can", "cans", "are", "do"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t8", type: "multiple_choice", speakOptions: true, prompt: "'Fish ___ walk.' (bacarmır)", options: ["can't", "don't", "aren't", "not"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t9", type: "multiple_choice", speakOptions: true, prompt: "'We ___ sing.'", options: ["can", "cans", "are", "do"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t10", type: "multiple_choice", speakOptions: true, prompt: "'I can ___.' (oxumaq — kitab)", options: ["read", "reads", "reading", "to read"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t11", type: "multiple_choice", speakOptions: true, prompt: "Sual: '___ you swim?'", options: ["Can", "Do", "Are", "Is"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t12", type: "multiple_choice", prompt: "'Can you help me?' nə deməkdir?", options: ["Mənə kömək edə bilərsən?", "Mənə kömək et.", "Kömək etdin?", "Kömək istəyirsən?"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t13", type: "multiple_choice", speakOptions: true, prompt: "'A cat ___ climb trees.'", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t14", type: "multiple_choice", speakOptions: true, prompt: "'I ___ speak English.' (bacarıram)", options: ["can", "am", "do", "have"], correctIndex: 0, xp: 10 },
            { id: "en3-can-rule-t15", type: "multiple_choice", speakOptions: true, prompt: "'She ___ ride a bike.' (bacarır)", options: ["can", "cans", "is", "does"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-can-rule-b1", type: "multiple_choice", speakOptions: true, prompt: "'Penguins can't ___.' (uçmaq)", options: ["fly", "flies", "flying", "flew"], correctIndex: 0, xp: 15 },
            { id: "en3-can-rule-b2", type: "multiple_choice", prompt: "'I can jump but I can't fly.' nə deməkdir?", options: ["Tullana bilirəm, amma uça bilmirəm.", "Uça bilirəm.", "Tullanmıram.", "Uçuram."], correctIndex: 0, xp: 15 },
            { id: "en3-can-rule-b3", type: "multiple_choice", speakOptions: true, prompt: "'Can dogs swim?' — Yes, they ___.", options: ["can", "do", "are", "have"], correctIndex: 0, xp: 15 },
            { id: "en3-can-rule-b4", type: "multiple_choice", speakOptions: true, prompt: "'I can ___ a picture.' (çəkmək)", options: ["draw", "draws", "drawing", "drew"], correctIndex: 0, xp: 15 },
            { id: "en3-can-rule-b5", type: "multiple_choice", prompt: "'Can I go out?' nə deməkdir?", options: ["Çölə çıxa bilərəm?", "Çölə çıxdım.", "Çölə çıx.", "Çöldəyəm."], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 4. Sözönləri ═══════════════
    {
      id: "en3-prep",
      title: "Sözönləri (in / on / under)",
      description: "Yer bildirən sözönləri: in, on, under, next to.",
      lessons: [
        {
          id: "en3-prep-vocab",
          title: "Prepositions of place",
          intro: "Əşyanın harada olduğunu bildirən sözlər.",
          sections: [
            { heading: "Sözönləri", body: "in — içində, on — üstündə, under — altında, next to — yanında, behind — arxasında, in front of — qarşısında." },
          ],
          tasks: [
            { id: "en3-prep-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'in' nə deməkdir?", options: ["içində", "üstündə", "altında", "yanında"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'on' nə deməkdir?", options: ["üstündə", "içində", "altında", "arxasında"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'under' nə deməkdir?", options: ["altında", "üstündə", "içində", "yanında"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'next to' nə deməkdir?", options: ["yanında", "altında", "üstündə", "içində"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'The book is ___ the table.' (üstündə)", options: ["on", "in", "under", "next"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'The cat is ___ the box.' (içində)", options: ["in", "on", "under", "next to"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'The ball is ___ the chair.' (altında)", options: ["under", "on", "in", "next to"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'The pen is ___ the book.' (yanında)", options: ["next to", "in", "under", "on"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t9", type: "multiple_choice", prompt: "'The apple is on the table.' nə deməkdir?", options: ["Alma masanın üstündədir.", "Alma masanın altındadır.", "Alma qutudadır.", "Alma yoxdur."], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t10", type: "multiple_choice", prompt: "'The dog is under the bed.' nə deməkdir?", options: ["İt çarpayının altındadır.", "İt çarpayının üstündədir.", "İt qutudadır.", "İt qaçır."], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'behind' nə deməkdir?", options: ["arxasında", "qarşısında", "içində", "üstündə"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'in front of' nə deməkdir?", options: ["qarşısında", "arxasında", "altında", "içində"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'The keys are ___ my bag.' (içində)", options: ["in", "on", "under", "next to"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'The picture is ___ the wall.' (üstündə/divarda)", options: ["on", "in", "under", "behind"], correctIndex: 0, xp: 10 },
            { id: "en3-prep-vocab-t15", type: "multiple_choice", prompt: "'The cat is in the box.' nə deməkdir?", options: ["Pişik qutunun içindədir.", "Pişik qutunun üstündədir.", "Pişik qutunun altındadır.", "Pişik yoxdur."], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-prep-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'The car is ___ the house.' (qarşısında)", options: ["in front of", "in", "under", "on"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'The boy is ___ the tree.' (arxasında)", options: ["behind", "on", "in", "under"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'between' nə deməkdir?", options: ["arasında", "yanında", "arxasında", "içində"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-vocab-b4", type: "multiple_choice", prompt: "'Where is the ball?' nə deməkdir?", options: ["Top haradadır?", "Top nədir?", "Top kimindir?", "Top böyükdür?"], correctIndex: 0, xp: 15 },
            { id: "en3-prep-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'The shoes are ___ the bed.' (altında)", options: ["under", "on", "in", "next to"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 5. Gündəlik rejim və saat ═══════════════
    {
      id: "en3-routine",
      title: "Gündəlik rejim və saat",
      description: "Gündəlik işlər və saatın deyilməsi.",
      lessons: [
        {
          id: "en3-routine-vocab",
          title: "Daily routines & time",
          intro: "Gündəlik işlər və saat sözləri.",
          sections: [
            { heading: "Rejim", body: "get up — durmaq, have breakfast — səhər yeməyi yemək, go to school — məktəbə getmək, do homework — ev tapşırığı etmək, go to bed — yatmağa getmək." },
            { heading: "Saat", body: "'What time is it?' — Saat neçədir? 'It is seven o'clock.' — Saat yeddidir." },
          ],
          tasks: [
            { id: "en3-routine-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'get up' nə deməkdir?", options: ["durmaq (yuxudan)", "yatmaq", "yemək", "getmək"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'have breakfast' nə deməkdir?", options: ["səhər yeməyi yemək", "nahar etmək", "yatmaq", "durmaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'go to school' nə deməkdir?", options: ["məktəbə getmək", "evə getmək", "yatmaq", "oynamaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'do homework' nə deməkdir?", options: ["ev tapşırığı etmək", "ev təmizləmək", "oynamaq", "yatmaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'go to bed' nə deməkdir?", options: ["yatmağa getmək", "durmaq", "yemək", "gəzmək"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'What time is it?' nə deməkdir?", options: ["Saat neçədir?", "Nə vaxt gəlirsən?", "Necəsən?", "Harададır?"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t7", type: "multiple_choice", speakOptions: true, prompt: "'It is seven o'clock.' nə deməkdir?", options: ["Saat yeddidir.", "Saat altıdır.", "Yeddi dəqiqə.", "Yeddinci gün."], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t8", type: "multiple_choice", speakOptions: true, prompt: "'morning' nə deməkdir?", options: ["səhər", "axşam", "gecə", "günorta"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'evening' nə deməkdir?", options: ["axşam", "səhər", "gecə", "günorta"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'night' nə deməkdir?", options: ["gecə", "səhər", "axşam", "gündüz"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'I get up at 7.' nə deməkdir?", options: ["Saat 7-də dururam.", "Saat 7-də yatıram.", "Saat 7-də yeyirəm.", "Saat 7-də gəlirəm."], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'have lunch' nə deməkdir?", options: ["nahar etmək", "səhər yeməyi", "şam etmək", "yatmaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'have dinner' nə deməkdir?", options: ["şam etmək", "nahar etmək", "səhər yeməyi", "durmaq"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'It is nine o'clock.' saat neçədir?", options: ["9", "8", "10", "7"], correctIndex: 0, xp: 10 },
            { id: "en3-routine-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'wash my face' nə deməkdir?", options: ["üzümü yumaq", "dişimi təmizləmək", "saçımı daramaq", "əlimi yumaq"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-routine-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'I go to bed at ten.' nə deməkdir?", options: ["Saat 10-da yatıram.", "Saat 10-da dururam.", "Saat 10-da yeyirəm.", "Saat 10-da oxuyuram."], correctIndex: 0, xp: 15 },
            { id: "en3-routine-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'It is half past six.' nə deməkdir?", options: ["Altının yarısı (6:30)", "Saat altı", "Saat yeddi", "Beşin yarısı"], correctIndex: 0, xp: 15 },
            { id: "en3-routine-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'afternoon' nə deməkdir?", options: ["günorta/nahardan sonra", "səhər", "gecə", "axşam"], correctIndex: 0, xp: 15 },
            { id: "en3-routine-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'I do my homework in the evening.' nə deməkdir?", options: ["Ev tapşırığımı axşam edirəm.", "Səhər ev tapşırığı edirəm.", "Ev tapşırığı yoxdur.", "Ev tapşırığını bitirdim."], correctIndex: 0, xp: 15 },
            { id: "en3-routine-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'get dressed' nə deməkdir?", options: ["geyinmək", "soyunmaq", "yumaq", "yatmaq"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 6. Peşələr və şəhər ═══════════════
    {
      id: "en3-jobs",
      title: "Peşələr və şəhər (Jobs & Places)",
      description: "Peşələr və şəhərdəki yerlərin adları.",
      lessons: [
        {
          id: "en3-jobs-vocab",
          title: "Jobs & places",
          intro: "Peşələri və yerləri öyrənək.",
          sections: [
            { heading: "Peşələr", body: "teacher — müəllim, doctor — həkim, driver — sürücü, cook — aşpaz, farmer — fermer, nurse — tibb bacısı, police officer — polis, pilot — pilot." },
            { heading: "Yerlər", body: "school — məktəb, hospital — xəstəxana, shop — mağaza, park — park, zoo — heyvanxana, library — kitabxana." },
          ],
          tasks: [
            { id: "en3-jobs-vocab-t1", type: "multiple_choice", speakOptions: true, prompt: "'müəllim' İngiliscə necədir?", options: ["teacher", "doctor", "driver", "cook"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t2", type: "multiple_choice", speakOptions: true, prompt: "'həkim' İngiliscə necədir?", options: ["doctor", "teacher", "nurse", "farmer"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t3", type: "multiple_choice", speakOptions: true, prompt: "'sürücü' İngiliscə necədir?", options: ["driver", "pilot", "cook", "farmer"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t4", type: "multiple_choice", speakOptions: true, prompt: "'aşpaz' İngiliscə necədir?", options: ["cook", "driver", "doctor", "nurse"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t5", type: "multiple_choice", speakOptions: true, prompt: "'fermer' İngiliscə necədir?", options: ["farmer", "cook", "pilot", "teacher"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t6", type: "multiple_choice", speakOptions: true, prompt: "'pilot' İngiliscə necədir?", options: ["pilot", "driver", "police officer", "cook"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t7", type: "multiple_choice", prompt: "'doctor' nə deməkdir?", options: ["həkim", "müəllim", "sürücü", "aşpaz"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t8", type: "multiple_choice", prompt: "'teacher' nə deməkdir?", options: ["müəllim", "həkim", "polis", "pilot"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t9", type: "multiple_choice", speakOptions: true, prompt: "'məktəb' İngiliscə necədir?", options: ["school", "hospital", "shop", "park"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t10", type: "multiple_choice", speakOptions: true, prompt: "'xəstəxana' İngiliscə necədir?", options: ["hospital", "school", "shop", "zoo"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t11", type: "multiple_choice", speakOptions: true, prompt: "'mağaza' İngiliscə necədir?", options: ["shop", "park", "school", "library"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t12", type: "multiple_choice", speakOptions: true, prompt: "'kitabxana' İngiliscə necədir?", options: ["library", "shop", "zoo", "park"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t13", type: "multiple_choice", speakOptions: true, prompt: "'heyvanxana' İngiliscə necədir?", options: ["zoo", "park", "shop", "hospital"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t14", type: "multiple_choice", speakOptions: true, prompt: "'A ___ works in a hospital.' (həkim)", options: ["doctor", "teacher", "farmer", "cook"], correctIndex: 0, xp: 10 },
            { id: "en3-jobs-vocab-t15", type: "multiple_choice", speakOptions: true, prompt: "'A ___ teaches children.' (müəllim)", options: ["teacher", "doctor", "driver", "pilot"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "en3-jobs-vocab-b1", type: "multiple_choice", speakOptions: true, prompt: "'A ___ flies a plane.' (pilot)", options: ["pilot", "driver", "cook", "farmer"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-vocab-b2", type: "multiple_choice", speakOptions: true, prompt: "'nurse' nə deməkdir?", options: ["tibb bacısı", "həkim", "müəllim", "aşpaz"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-vocab-b3", type: "multiple_choice", speakOptions: true, prompt: "'A ___ cooks food.' (aşpaz)", options: ["cook", "farmer", "driver", "pilot"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-vocab-b4", type: "multiple_choice", speakOptions: true, prompt: "'We borrow books from the ___.'", options: ["library", "shop", "zoo", "park"], correctIndex: 0, xp: 15 },
            { id: "en3-jobs-vocab-b5", type: "multiple_choice", speakOptions: true, prompt: "'police officer' nə deməkdir?", options: ["polis", "əsgər", "sürücü", "pilot"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
  ],
};
