// Maliyyə Savadlılığı — 5-ci sinif proqramı (pilot, Rəqəmsal Təhlükəsizliyin yanında).
// Bölmələr: 1) Pul nədir və haradan gəlir  2) Xərcləmək və qənaət
// 3) Ağıllı qərarlar və pul təhlükəsizliyi.
// id prefiksi ml5-*. Bütün məbləğlər manat/qəpiklə (1 manat = 100 qəpik).

import type { Subject } from "../types";

export const maliyye5: Subject = {
  slug: "maliyye-savadliligi-5",
  name: "Maliyyə Savadlılığı",
  grade: 5,
  icon: "M",
  color: "amber",
  units: [
    // ═══════════════ 1. Pul nədir və haradan gəlir ═══════════════
    {
      id: "ml5-pul-nedir",
      title: "Pul nədir və haradan gəlir",
      description: "Pulun nə üçün lazım olduğu, manat və qəpik, gəlirin mənbələri.",
      lessons: [
        {
          id: "ml5-pul-nedir-l1",
          title: "Pul və onun dəyəri",
          intro: "Pul mübadilə vasitəsidir — onunla lazım olan şeyləri alırıq.",
          sections: [
            { heading: "Pul nə üçündür?", body: "Çox-çox əvvəllər insanlar mal-mala dəyişirdi: bir qoyuna bir kisə buğda. Bu çətin idi. Pul icad olundu ki, hər şeyin ortaq bir ölçüsü olsun. İndi sən pul verirsən, satıcı sənə mal verir." },
            { heading: "Manat və qəpik", body: "Azərbaycanın pulu MANATDIR, işarəsi ₼. Bir manatın içində 100 QƏPİK var. Yəni 1 manat = 100 qəpik. 50 qəpik yarım manat deməkdir." },
            { heading: "Qiymət", body: "Hər malın QİYMƏTİ var — onu almaq üçün lazım olan pul. İki eyni malın qiyməti fərqli ola bilər: bir mağazada ucuz, başqasında baha." },
          ],
          tasks: [
            { id: "ml5-pul-nedir-l1-t1", type: "multiple_choice", prompt: "Azərbaycanın pul vahidi hansıdır?", options: ["Manat", "Dollar", "Avro", "Rubl"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l1-t2", type: "numeric", prompt: "1 manat neçə qəpikdir?", answer: 100, xp: 10 },
            { id: "ml5-pul-nedir-l1-t3", type: "numeric", prompt: "2 manat neçə qəpikdir?", answer: 200, xp: 10 },
            { id: "ml5-pul-nedir-l1-t4", type: "multiple_choice", prompt: "Pul əsasən nə üçün lazımdır?", options: ["Lazım olan malları almaq üçün", "Yalnız yığmaq üçün", "Oyun oynamaq üçün", "Rəsm çəkmək üçün"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l1-t5", type: "numeric", prompt: "50 qəpik + 50 qəpik neçə manat edir?", answer: 1, xp: 10 },
            { id: "ml5-pul-nedir-l1-t6", type: "multiple_choice", prompt: "Pul icad olunmamışdan əvvəl insanlar necə alış-veriş edirdi?", options: ["Malı mala dəyişirdilər", "Kartla ödəyirdilər", "Heç alış-veriş etmirdilər", "Telefonla ödəyirdilər"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l1-t7", type: "numeric", prompt: "Bir dəftər 80 qəpikdir. 1 manat verirsən. Neçə qəpik qaytarmalıdırlar?", answer: 20, xp: 10 },
            { id: "ml5-pul-nedir-l1-t8", type: "multiple_choice", prompt: "'Qiymət' nə deməkdir?", options: ["Malı almaq üçün lazım olan pul", "Malın rəngi", "Malın ağırlığı", "Malın adı"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l1-t9", type: "fill_blank", prompt: "1 manat = ______ qəpik. (rəqəmlə yaz)", accepted: ["100", "yüz", "Yüz"], xp: 10 },
            { id: "ml5-pul-nedir-l1-t10", type: "numeric", prompt: "3 manat 50 qəpik — hamısı neçə qəpik edir?", answer: 350, xp: 10 },
            { id: "ml5-pul-nedir-l1-t11", type: "multiple_choice", prompt: "Eyni çanta bir mağazada 25 ₼, digərində 30 ₼-dır. Hansı daha sərfəlidir?", options: ["25 ₼ olan", "30 ₼ olan", "Fərqi yoxdur", "Hər ikisi eynidir"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l1-t12", type: "numeric", prompt: "5 manatlıq əskinasla 2 manatlıq çörək alırsan. Neçə manat qalır?", answer: 3, xp: 10 },
          ],
          bonusTasks: [
            { id: "ml5-pul-nedir-l1-b1", type: "numeric", prompt: "1 manat 20 qəpik + 80 qəpik = neçə manat?", answer: 2, xp: 15 },
            { id: "ml5-pul-nedir-l1-b2", type: "multiple_choice", prompt: "Niyə eyni malın qiyməti müxtəlif mağazalarda fərqli olur?", options: ["Mağazanın xərcləri və qazancı fərqlidir", "Pul fərqlidir", "Mal fərqlidir", "Heç bir səbəbi yoxdur"], correctIndex: 0, xp: 15 },
            { id: "ml5-pul-nedir-l1-b3", type: "numeric", prompt: "Bir qələm 45 qəpikdir. 3 qələm neçə qəpik edir?", answer: 135, xp: 15 },
            { id: "ml5-pul-nedir-l1-b4", type: "multiple_choice", prompt: "10 ₼-a 4 ədəd 2 ₼-lıq dəftər alırsan. Nə baş verir?", options: ["2 ₼ qalır", "Pul çatmır", "Tam qurtarır", "5 ₼ qalır"], correctIndex: 0, xp: 15 },
            { id: "ml5-pul-nedir-l1-b5", type: "multiple_choice", prompt: "Pulun ən əsas işi nədir?", options: ["Malların dəyərini ortaq ölçü ilə müqayisə etmək", "Gözəl görünmək", "Ağır olmaq", "Rəngli olmaq"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ml5-pul-nedir-l2",
          title: "Pul haradan gəlir?",
          intro: "Pul göydən düşmür — o, əməyin qarşılığıdır.",
          sections: [
            { heading: "Gəlir", body: "Ailəyə daxil olan pula GƏLİR deyilir. Böyüklər işləyir, əvəzində əmək haqqı (maaş) alırlar. Bu, ailənin əsas gəliridir." },
            { heading: "Sənin gəlirin", body: "Şagirdin gəliri adətən cib xərcliyi və bayram hədiyyəsidir. Bu da puldur — və onu necə xərcləmək sənin qərarındır." },
            { heading: "Vacib qayda", body: "Pul əməklə qazanılır. 'Heç nə etmədən tez pul' vəd edən təkliflər demək olar həmişə fırıldaqdır." },
          ],
          tasks: [
            { id: "ml5-pul-nedir-l2-t1", type: "multiple_choice", prompt: "Böyüklər işlədiklərinə görə aldıqları pula nə deyilir?", options: ["Əmək haqqı (maaş)", "Hədiyyə", "Cərimə", "Borc"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l2-t2", type: "multiple_choice", prompt: "Ailəyə daxil olan pula nə deyilir?", options: ["Gəlir", "Xərc", "Qiymət", "Çeşid"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l2-t3", type: "multiple_choice", prompt: "Aşağıdakılardan hansı şagird üçün gəlir sayıla bilər?", options: ["Cib xərcliyi", "Dərs cədvəli", "Ev tapşırığı", "Zəng səsi"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l2-t4", type: "multiple_choice", prompt: "Kimsə 'heç nə etmə, bir gündə çox pul qazan' deyir. Bu nədir?", options: ["Çox güman fırıldaqdır", "Yaxşı imkandır", "Adi işdir", "Bank təklifidir"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l2-t5", type: "numeric", prompt: "Həftədə 2 ₼ cib xərcliyi alırsan. 4 həftəyə neçə manat olur?", answer: 8, xp: 10 },
            { id: "ml5-pul-nedir-l2-t6", type: "multiple_choice", prompt: "Pul əsasən nə ilə qazanılır?", options: ["Əməklə", "Arzu etməklə", "Gözləməklə", "Yatmaqla"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l2-t7", type: "fill_blank", prompt: "Ailəyə daxil olan pula ______ deyilir. (bir söz)", accepted: ["gəlir", "Gəlir", "gelir"], xp: 10 },
            { id: "ml5-pul-nedir-l2-t8", type: "multiple_choice", prompt: "Gəlirlə xərc arasındakı fərq nədir?", options: ["Gəlir gələn, xərc gedən puldur", "İkisi eynidir", "Gəlir gedən puldur", "Xərc gələn puldur"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l2-t9", type: "numeric", prompt: "Ayda 3 dəfə 5 ₼ hədiyyə aldın. Cəmi neçə manat?", answer: 15, xp: 10 },
            { id: "ml5-pul-nedir-l2-t10", type: "multiple_choice", prompt: "Bayram hədiyyəsi olaraq aldığın pulla nə etmək ən ağıllıdır?", options: ["Bir hissəsini yığmaq, bir hissəsini xərcləmək", "Hamısını bir gündə xərcləmək", "İtirmək", "Heç kimə demədən gizlətmək"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l2-t11", type: "multiple_choice", prompt: "Ailənin gəliri azaldıqda nə etmək lazımdır?", options: ["Xərcləri də azaltmaq", "Xərcləri artırmaq", "Heç nə dəyişməmək", "Daha çox alış-veriş etmək"], correctIndex: 0, xp: 10 },
            { id: "ml5-pul-nedir-l2-t12", type: "numeric", prompt: "Həftəlik 3 ₼ cib xərcliyindən hər həftə 1 ₼ yığırsan. 5 həftəyə neçə manat yığılır?", answer: 5, xp: 10 },
          ],
          bonusTasks: [
            { id: "ml5-pul-nedir-l2-b1", type: "multiple_choice", prompt: "Niyə 'tez və asan pul' təklifləri təhlükəlidir?", options: ["Adətən fırıldaqdır və pulunu itirirsən", "Çünki çox vaxt aparır", "Çünki maraqsızdır", "Çünki bahalıdır"], correctIndex: 0, xp: 15 },
            { id: "ml5-pul-nedir-l2-b2", type: "numeric", prompt: "Ailənin aylıq gəliri 900 ₼, xərci 700 ₼-dır. Ay sonunda neçə manat qalır?", answer: 200, xp: 15 },
            { id: "ml5-pul-nedir-l2-b3", type: "multiple_choice", prompt: "Bir insanın peşəsi ilə gəliri arasında nə əlaqə var?", options: ["Bacarıq və təhsil gəlirə təsir edir", "Heç bir əlaqə yoxdur", "Gəlir yalnız yaşdan asılıdır", "Gəlir təsadüfidir"], correctIndex: 0, xp: 15 },
            { id: "ml5-pul-nedir-l2-b4", type: "multiple_choice", prompt: "Sən qonşuya kömək etdin, o sənə pul verdi. Bu nədir?", options: ["Əməyin qarşılığı", "Oğurluq", "Borc", "Cərimə"], correctIndex: 0, xp: 15 },
            { id: "ml5-pul-nedir-l2-b5", type: "numeric", prompt: "Gəlir 50 ₼, xərc 65 ₼. Neçə manat çatışmır?", answer: 15, xp: 15 },
          ],
        },
        {
          id: "ml5-pul-nedir-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ml5-pul-nedir-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },

    // ═══════════════ 2. Xərcləmək və qənaət ═══════════════
    {
      id: "ml5-xerc-qenaet",
      title: "Xərcləmək və qənaət",
      description: "Ehtiyac və istəyi ayırmaq, məqsəd üçün pul yığmaq.",
      lessons: [
        {
          id: "ml5-xerc-qenaet-l1",
          title: "Ehtiyac və istək",
          intro: "Hər istədiyin şey sənə lazım olan şey deyil.",
          sections: [
            { heading: "Ehtiyac", body: "EHTİYAC — onsuz keçinə bilmədiyin şeydir: yemək, su, geyim, dərslik, dərman, ev. Bunlar birinci gəlir." },
            { heading: "İstək", body: "İSTƏK — olsa yaxşı olar, amma olmasa da yaşaya bilərsən: yeni oyun, şirniyyat, üçüncü futbol topu. Bunlar ikinci gəlir." },
            { heading: "Qayda", body: "Pul məhduddur, istəklər isə sonsuzdur. Ona görə əvvəl ehtiyacları ödə, sonra qalan pulla istəklərə bax." },
          ],
          tasks: [
            { id: "ml5-xerc-qenaet-l1-t1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı EHTİYACDIR?", options: ["Yemək", "Video oyun", "Şirniyyat", "Üçüncü top"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı İSTƏKDİR?", options: ["Yeni oyun konsolu", "Dərslik", "Qış paltarı", "Dərman"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t3", type: "multiple_choice", prompt: "Ehtiyacla istəyin əsas fərqi nədir?", options: ["Ehtiyac olmadan keçinmək olmur", "İstək daha ucuzdur", "Ehtiyac həmişə bahadır", "Fərq yoxdur"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t4", type: "multiple_choice", prompt: "Pulun azdır. Əvvəl nəyi almalısan?", options: ["Ehtiyacı", "İstəyi", "Ən bahalını", "Ən rənglini"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t5", type: "multiple_choice", prompt: "Məktəb çantan cırılıb. Yeni çanta bu halda nədir?", options: ["Ehtiyac", "İstək", "Hədiyyə", "Lüks"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t6", type: "multiple_choice", prompt: "Sağlam çantan var, amma dostunda daha gözəli var. Yeni çanta indi nədir?", options: ["İstək", "Ehtiyac", "Vacib xərc", "Məcburiyyət"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t7", type: "fill_blank", prompt: "Onsuz keçinə bilmədiyin şeyə ______ deyilir. (bir söz)", accepted: ["ehtiyac", "Ehtiyac", "ehtiyacdır"], xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t8", type: "numeric", prompt: "10 ₼-ın var. 6 ₼-a dərslik (ehtiyac) alırsan. İstəklərə neçə manat qalır?", answer: 4, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t9", type: "multiple_choice", prompt: "Niyə hər istəyi almaq mümkün deyil?", options: ["Pul məhduddur, istəklər sonsuzdur", "Mağazalar bağlıdır", "İstəklər qadağandır", "Pul çox asandır"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t10", type: "multiple_choice", prompt: "Su və çörək hansı qrupa aiddir?", options: ["Ehtiyac", "İstək", "Əyləncə", "Hədiyyə"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t11", type: "multiple_choice", prompt: "Alışdan əvvəl özünə hansı sualı verməlisən?", options: ["Bu mənə həqiqətən lazımdırmı?", "Bu rəngli midir?", "Dostumda varmı?", "Reklamda göstərilibmi?"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l1-t12", type: "numeric", prompt: "20 ₼-ın var. Ehtiyaclara 12 ₼, istəklərə 5 ₼ xərclədin. Neçə manat qaldı?", answer: 3, xp: 10 },
          ],
          bonusTasks: [
            { id: "ml5-xerc-qenaet-l1-b1", type: "multiple_choice", prompt: "Eyni şey bir adam üçün ehtiyac, başqası üçün istək ola bilərmi?", options: ["Bəli, vəziyyətdən asılıdır", "Xeyr, heç vaxt", "Yalnız qışda", "Yalnız uşaqlar üçün"], correctIndex: 0, xp: 15 },
            { id: "ml5-xerc-qenaet-l1-b2", type: "multiple_choice", prompt: "İdman ayaqqabın yırtılıb və başqası yoxdur. Yeni ayaqqabı nədir?", options: ["Ehtiyac", "İstək", "Lüks", "Əyləncə"], correctIndex: 0, xp: 15 },
            { id: "ml5-xerc-qenaet-l1-b3", type: "numeric", prompt: "Aylıq 30 ₼-dan ehtiyaclara 18 ₼ gedir. İstək və yığıma neçə manat qalır?", answer: 12, xp: 15 },
            { id: "ml5-xerc-qenaet-l1-b4", type: "multiple_choice", prompt: "'İmpuls alış' nə deməkdir?", options: ["Düşünmədən, ani hisslə alış", "Planlı alış", "Ucuz alış", "Böyük alış"], correctIndex: 0, xp: 15 },
            { id: "ml5-xerc-qenaet-l1-b5", type: "multiple_choice", prompt: "İmpuls alışın qarşısını almaq üçün ən yaxşı üsul hansıdır?", options: ["Bir gün gözlə, sonra qərar ver", "Dərhal al", "Dostundan borc al", "İki dənə al"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ml5-xerc-qenaet-l2",
          title: "Qənaət və məqsəd",
          intro: "Böyük şeyi almaq üçün kiçik-kiçik yığmaq lazımdır.",
          sections: [
            { heading: "Qənaət", body: "QƏNAƏT — pulun bir hissəsini indi xərcləməyib gələcək üçün saxlamaqdır. Az-az yığılan pul böyük məbləğ olur." },
            { heading: "Məqsəd qoy", body: "Yığıma məqsəd lazımdır: 'velosiped üçün 120 ₼'. Məqsəd olanda yığmaq asanlaşır, çünki nə üçün gözlədiyini bilirsən." },
            { heading: "Nə qədər çəkir?", body: "Neçə vaxta yığacağını hesabla: məbləği həftəlik yığdığın pula böl. 120 ₼ ÷ 10 ₼ = 12 həftə." },
          ],
          tasks: [
            { id: "ml5-xerc-qenaet-l2-t1", type: "multiple_choice", prompt: "Qənaət nə deməkdir?", options: ["Pulun bir hissəsini gələcək üçün saxlamaq", "Bütün pulu xərcləmək", "Pulu itirmək", "Borc almaq"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t2", type: "numeric", prompt: "Həftədə 5 ₼ yığırsan. 6 həftəyə neçə manat olur?", answer: 30, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t3", type: "numeric", prompt: "Velosiped 120 ₼-dır. Həftədə 10 ₼ yığırsan. Neçə həftəyə yığılar?", answer: 12, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t4", type: "multiple_choice", prompt: "Niyə yığıma məqsəd qoymaq faydalıdır?", options: ["Nə üçün gözlədiyini bilirsən və asan olur", "Pul artır", "Qiymətlər düşür", "Vaxt tez keçir"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t5", type: "numeric", prompt: "40 ₼ yığmısan, məqsəd 100 ₼-dır. Daha neçə manat lazımdır?", answer: 60, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t6", type: "multiple_choice", prompt: "Cib xərcliyinin nə qədərini yığmaq yaxşı vərdişdir?", options: ["Kiçik də olsa, hər dəfə bir hissəsini", "Heç nəyi", "Yalnız bayramda", "Hamısını"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t7", type: "fill_blank", prompt: "Pulu gələcək üçün saxlamağa ______ deyilir. (bir söz)", accepted: ["qənaət", "Qənaət", "qenaet"], xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t8", type: "multiple_choice", prompt: "Yığdığın pulu harada saxlamaq daha təhlükəsizdir?", options: ["Valideynlə birlikdə bank hesabında və ya qutuda", "Cibində gəzdirmək", "Məktəb partasında", "Həyətdə basdırmaq"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t9", type: "numeric", prompt: "Gündə 50 qəpik yığırsan. 10 günə neçə manat olur?", answer: 5, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t10", type: "multiple_choice", prompt: "Yığım zamanı ən çətin şey nədir?", options: ["Səbir etmək və indi xərcləməmək", "Pulu saymaq", "Qutu tapmaq", "Məqsəd yazmaq"], correctIndex: 0, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t11", type: "numeric", prompt: "Ayda 8 ₼ yığırsan. 3 aya neçə manat olur?", answer: 24, xp: 10 },
            { id: "ml5-xerc-qenaet-l2-t12", type: "multiple_choice", prompt: "Məqsədinə çatmağa az qalıb, amma başqa şey almaq istəyirsən. Ən ağıllı davranış?", options: ["Məqsədə sadiq qal, bir az da gözlə", "Yığımı xərclə", "Məqsədi dəyiş", "Borc al"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "ml5-xerc-qenaet-l2-b1", type: "numeric", prompt: "Həftədə 4 ₼ yığırsan. 60 ₼ üçün neçə həftə lazımdır?", answer: 15, xp: 15 },
            { id: "ml5-xerc-qenaet-l2-b2", type: "multiple_choice", prompt: "Bankda saxlanan pula bəzən əlavə verilir. Buna nə deyilir?", options: ["Faiz", "Cərimə", "Vergi", "Qiymət"], correctIndex: 0, xp: 15 },
            { id: "ml5-xerc-qenaet-l2-b3", type: "numeric", prompt: "100 ₼ yığmısan. Məqsəd 250 ₼. Ayda 30 ₼ yığsan, təxminən neçə ay lazımdır?", answer: 5, xp: 15 },
            { id: "ml5-xerc-qenaet-l2-b4", type: "multiple_choice", prompt: "Niyə 'əvvəl yığ, sonra xərclə' qaydası işləyir?", options: ["Yığım qalıqdan asılı qalmır", "Çünki daha sürətlidir", "Çünki mağazalar bağlıdır", "Çünki pul artır"], correctIndex: 0, xp: 15 },
            { id: "ml5-xerc-qenaet-l2-b5", type: "multiple_choice", prompt: "Qənaət etməyin ən böyük faydası nədir?", options: ["Gözlənilməz xərcə hazır olursan", "Pul rəngini dəyişir", "Qiymətlər ucuzlaşır", "Vaxt qazanırsan"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ml5-xerc-qenaet-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ml5-xerc-qenaet-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },

    // ═══════════════ 3. Ağıllı qərarlar və pul təhlükəsizliyi ═══════════════
    {
      id: "ml5-agilli-qerar",
      title: "Ağıllı qərarlar və pul təhlükəsizliyi",
      description: "Sadə büdcə qurmaq, reklamı tanımaq və pul fırıldaqlarından qorunmaq.",
      lessons: [
        {
          id: "ml5-agilli-qerar-l1",
          title: "Sadə büdcə qur",
          intro: "Büdcə — pulunun hara getdiyini əvvəlcədən yazmaqdır.",
          sections: [
            { heading: "Büdcə nədir?", body: "BÜDCƏ gəlirlərin və xərclərin planıdır. Sadə düsturu belədir: GƏLİR − XƏRC = QALIQ. Qalıq müsbətdirsə, yaxşı; mənfidirsə, xərci azaltmaq lazımdır." },
            { heading: "Üç zərf qaydası", body: "Aldığın pulu üçə böl: bir hissə XƏRC (indi lazım olan), bir hissə YIĞIM (məqsəd üçün), bir hissə PAYLAŞMA (kömək/hədiyyə). Bu, sadə və işləyən üsuldur." },
            { heading: "Yazmaq vacibdir", body: "Xərclərini yaz. Yazmasan, pulun hara getdiyini unudursan — bu, ən çox rast gəlinən səhvdir." },
          ],
          tasks: [
            { id: "ml5-agilli-qerar-l1-t1", type: "multiple_choice", prompt: "Büdcə nədir?", options: ["Gəlir və xərclərin planı", "Bankın adı", "Pul növü", "Mağaza növü"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t2", type: "numeric", prompt: "Gəlir 25 ₼, xərc 18 ₼. Qalıq neçə manatdır?", answer: 7, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t3", type: "multiple_choice", prompt: "Xərc gəlirdən çox olsa nə baş verir?", options: ["Pul çatmır, kəsir yaranır", "Pul artır", "Heç nə olmur", "Qiymət düşür"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t4", type: "numeric", prompt: "Gəlir 40 ₼, xərc 40 ₼. Qalıq neçə manatdır?", answer: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t5", type: "multiple_choice", prompt: "Büdcədə kəsir yarananda ilk addım nədir?", options: ["Ən az vacib xərci azaltmaq", "Daha çox xərcləmək", "Yığımı dayandırmaq və unutmaq", "Heç nə etməmək"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t6", type: "fill_blank", prompt: "Gəlir − xərc = ______ . (bir söz)", accepted: ["qalıq", "Qalıq", "qaliq"], xp: 10 },
            { id: "ml5-agilli-qerar-l1-t7", type: "multiple_choice", prompt: "'Üç zərf' qaydasında hissələr hansılardır?", options: ["Xərc, yığım, paylaşma", "Yemək, oyun, kitab", "Səhər, günorta, axşam", "Manat, qəpik, dollar"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t8", type: "numeric", prompt: "30 ₼-ı üç bərabər hissəyə bölürsən. Hər hissə neçə manatdır?", answer: 10, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t9", type: "multiple_choice", prompt: "Niyə xərcləri yazmaq lazımdır?", options: ["Pulun hara getdiyini görmək üçün", "Dəftər doldurmaq üçün", "Müəllim tələb edir deyə", "Heç bir səbəbi yoxdur"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t10", type: "numeric", prompt: "Həftəlik 12 ₼-dan 4 ₼ yığım, 2 ₼ paylaşma ayırdın. Xərcə neçə manat qalır?", answer: 6, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t11", type: "multiple_choice", prompt: "Aylıq büdcədə ən vacib xərc hansıdır?", options: ["Yemək və dərs ləvazimatı", "Şirniyyat", "Oyun içi alış", "Üçüncü oyuncaq"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l1-t12", type: "numeric", prompt: "Gəlir 50 ₼. Yemək 20 ₼, nəqliyyat 10 ₼, dəftərxana 8 ₼. Qalıq neçə manatdır?", answer: 12, xp: 10 },
          ],
          bonusTasks: [
            { id: "ml5-agilli-qerar-l1-b1", type: "numeric", prompt: "Gəlir 60 ₼, xərclər 25 ₼ + 18 ₼ + 9 ₼. Qalıq neçə manatdır?", answer: 8, xp: 15 },
            { id: "ml5-agilli-qerar-l1-b2", type: "multiple_choice", prompt: "'Gözlənilməz xərc' üçün büdcədə nə saxlamaq lazımdır?", options: ["Kiçik ehtiyat fondu", "Heç nə", "Bütün pulu", "Yalnız qəpiklər"], correctIndex: 0, xp: 15 },
            { id: "ml5-agilli-qerar-l1-b3", type: "numeric", prompt: "24 ₼-ın yarısını yığıma qoydun. Yığıma neçə manat getdi?", answer: 12, xp: 15 },
            { id: "ml5-agilli-qerar-l1-b4", type: "multiple_choice", prompt: "Büdcəni nə vaxt yenidən nəzərdən keçirmək lazımdır?", options: ["Gəlir və ya xərclər dəyişəndə", "Heç vaxt", "Yalnız yeni ildə", "Yalnız kimsə deyəndə"], correctIndex: 0, xp: 15 },
            { id: "ml5-agilli-qerar-l1-b5", type: "multiple_choice", prompt: "Büdcə qurmağın əsas faydası nədir?", options: ["Pulunu sən idarə edirsən, pul səni yox", "Pul çoxalır", "Qiymətlər düşür", "Alış-veriş sürətlənir"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ml5-agilli-qerar-l2",
          title: "Reklam və pul fırıldaqları",
          intro: "Hər parlaq təklif faydalı deyil — bəziləri pulunu almaq üçün qurulub.",
          sections: [
            { heading: "Reklamın məqsədi", body: "Reklam sənə məlumat vermək üçün deyil, ALDIRMAQ üçün hazırlanır. Rənglər, musiqi və 'yalnız bu gün!' sözləri tələsdirmək üçündür." },
            { heading: "Çox yaxşı görünürsə...", body: "'Pulsuz telefon!', 'Bir kliklə 1000 manat!' — belə təkliflər demək olar həmişə fırıldaqdır. Qayda sadədir: həddindən artıq yaxşı görünürsə, doğru deyil." },
            { heading: "Oyun içi alışlar", body: "Oyunlarda 'sandıq', 'əlavə can', 'skin' üçün real pul tələb olunur. Valideyn icazəsi olmadan heç vaxt ödəniş etmə və kart məlumatını heç bir yerə yazma." },
          ],
          tasks: [
            { id: "ml5-agilli-qerar-l2-t1", type: "multiple_choice", prompt: "Reklamın əsas məqsədi nədir?", options: ["Məhsulu sənə aldırmaq", "Səni öyrətmək", "Səni əyləndirmək", "Xəbər vermək"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t2", type: "multiple_choice", prompt: "'Yalnız bu gün! Tez ol!' sözləri nə üçün işlədilir?", options: ["Düşünməyə vaxt verməmək üçün", "Səni məlumatlandırmaq üçün", "Qiyməti azaltmaq üçün", "Malı yaxşılaşdırmaq üçün"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t3", type: "multiple_choice", prompt: "'Bir kliklə 1000 ₼ qazan!' yazısı görürsən. Nə edirsən?", options: ["Klikləmirəm, fırıldaqdır", "Kliklərəm", "Kart nömrəsi yazaram", "Dostlarıma göndərərəm"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t4", type: "multiple_choice", prompt: "Oyunda alış etmək üçün nə lazımdır?", options: ["Valideyn icazəsi", "Yalnız istək", "Dostun icazəsi", "Heç nə"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t5", type: "multiple_choice", prompt: "Bank kartının nömrəsini kimə demək olar?", options: ["Heç kimə — yalnız valideyn bilir", "Onlayn dostuna", "Oyun saytına", "Reklamda yazılan nömrəyə"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t6", type: "multiple_choice", prompt: "Bir təklif həddindən artıq yaxşı görünürsə, bu nə deməkdir?", options: ["Çox güman fırıldaqdır", "Mütləq almalısan", "Etibarlıdır", "Ucuzdur"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t7", type: "fill_blank", prompt: "Reklamın məqsədi məhsulu sənə ______ . (bir söz: nə etdirmək?)", accepted: ["aldırmaq", "Aldırmaq", "satmaq"], xp: 10 },
            { id: "ml5-agilli-qerar-l2-t8", type: "multiple_choice", prompt: "Endirim yazısı görəndə əvvəl nəyi yoxlamaq lazımdır?", options: ["Əvvəlki real qiyməti", "Şəklin rəngini", "Yazının şriftini", "Reklamın uzunluğunu"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t9", type: "numeric", prompt: "20 ₼-lıq oyuncağa 25% endirim var. Neçə manata düşür?", answer: 15, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t10", type: "multiple_choice", prompt: "Naməlum nömrədən 'uddunuz, pul göndərin' mesajı gəlir. Nə edirsən?", options: ["Cavab vermirəm, böyüyə deyirəm", "Pul göndərirəm", "Kart nömrəmi yazıram", "Dostuma ötürürəm"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t11", type: "multiple_choice", prompt: "Alış etməzdən əvvəl ən faydalı vərdiş hansıdır?", options: ["Qiymətləri müqayisə etmək", "İlk gördüyünü almaq", "Ən bahasını almaq", "Reklama inanmaq"], correctIndex: 0, xp: 10 },
            { id: "ml5-agilli-qerar-l2-t12", type: "numeric", prompt: "Eyni ayaqqabı 45 ₼ və 38 ₼-dır. Ucuzunu alsan neçə manat qənaət edirsən?", answer: 7, xp: 10 },
          ],
          bonusTasks: [
            { id: "ml5-agilli-qerar-l2-b1", type: "multiple_choice", prompt: "'Pulsuz' yazan oyun niyə əslində pulsuz olmaya bilər?", options: ["İçində pullu alışlar var", "Yüklənmir", "Yavaş işləyir", "Reklamı yoxdur"], correctIndex: 0, xp: 15 },
            { id: "ml5-agilli-qerar-l2-b2", type: "numeric", prompt: "60 ₼-lıq mala 50% endirim, sonra 5 ₼ daha endirim. Son qiymət neçə manatdır?", answer: 25, xp: 15 },
            { id: "ml5-agilli-qerar-l2-b3", type: "multiple_choice", prompt: "Bir sayt kart məlumatını istəyir, amma ünvanı qəribədir. Nə edirsən?", options: ["Yazmıram, valideynə göstərirəm", "Yazıram", "Dostuma göndərirəm", "Yarısını yazıram"], correctIndex: 0, xp: 15 },
            { id: "ml5-agilli-qerar-l2-b4", type: "multiple_choice", prompt: "Reklamda məşhur adamın olması məhsulun yaxşı olduğunu sübut edirmi?", options: ["Xeyr, ona bunun üçün pul verilir", "Bəli, həmişə", "Bəli, əgər idmançıdırsa", "Yalnız televiziyada"], correctIndex: 0, xp: 15 },
            { id: "ml5-agilli-qerar-l2-b5", type: "multiple_choice", prompt: "Pulunu qorumağın ən yaxşı ümumi qaydası hansıdır?", options: ["Tələsmə, yoxla, valideynlə məsləhətləş", "Tez qərar ver", "Reklama güvən", "Hamısını bir yerdə xərclə"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ml5-agilli-qerar-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ml5-agilli-qerar-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
