// Riyaziyyat — 6-cı sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Bölünmə (əlamətlər, sadə/mürəkkəb, ƏBOB, ƏKOB)  2) Adi kəsrlər
// 3) Onluq kəsrlər  4) Nisbət və tənasüb  5) Faiz  6) Tam ədədlər
// 7) Rasional ədədlər və koordinat  8) Həndəsə.
// Hər dərs: 15 əsas + 5 bonus tapşırıq. Mərhələli doldurulur (İngilis 5-ci sinif kimi).
// id prefiksi ry6-* → 5-ci sinif progress-i ilə toqquşmur.

import type { Subject } from "../types";

export const math6: Subject = {
  slug: "riyaziyyat-6",
  name: "Riyaziyyat",
  grade: 6,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Bölünmə ═══════════════
    {
      id: "ry6-bolunme",
      title: "Bölünmə. ƏBOB və ƏKOB",
      description:
        "Bölünmə əlamətləri (2, 3, 5, 9, 10), sadə və mürəkkəb ədədlər, sadə vuruqlara ayırma, ən böyük ortaq bölən (ƏBOB) və ən kiçik ortaq bölünən (ƏKOB).",
      lessons: [
        {
          id: "ry6-bol-l1",
          title: "2-yə, 5-ə və 10-a bölünmə əlamətləri",
          intro: "Bir ədədin bölünüb-bölünmədiyini bölmə etmədən son rəqəmə baxaraq bilmək.",
          sections: [
            { heading: "2-yə bölünmə", body: "Son rəqəmi cüt (0, 2, 4, 6, 8) olan ədəd 2-yə bölünür. Belə ədədlərə cüt ədədlər deyilir. Məsələn: 54, 130, 728." },
            { heading: "5-ə bölünmə", body: "Son rəqəmi 0 və ya 5 olan ədəd 5-ə bölünür. Məsələn: 85, 340, 205." },
            { heading: "10-a bölünmə", body: "Son rəqəmi 0 olan ədəd 10-a bölünür. Belə ədəd həm də 2-yə və 5-ə bölünür. Məsələn: 90, 350, 1 000." },
          ],
          tasks: [
            { id: "ry6-bol-l1-t1", type: "multiple_choice", prompt: "Ədəd 2-yə bölünürsə, son rəqəmi necə olmalıdır?", options: ["cüt (0, 2, 4, 6, 8)", "tək", "yalnız 5", "yalnız 0"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l1-t2", type: "multiple_choice", prompt: "Aşağıdakılardan hansı 2-yə bölünür?", options: ["37", "54", "81", "19"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l1-t3", type: "multiple_choice", prompt: "5-ə bölünmə əlaməti: son rəqəm ...?", options: ["0 və ya 5", "cüt", "3", "1"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l1-t4", type: "multiple_choice", prompt: "Hansı ədəd 5-ə bölünür?", options: ["42", "73", "85", "24"], correctIndex: 2, xp: 10 },
            { id: "ry6-bol-l1-t5", type: "multiple_choice", prompt: "10-a bölünmə əlaməti: son rəqəm ...?", options: ["0", "5", "cüt", "1"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l1-t6", type: "multiple_choice", prompt: "Hansı ədəd 10-a bölünür?", options: ["205", "350", "128", "64"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l1-t7", type: "numeric", prompt: "630 ədədi 2, 5 və 10-dan neçəsinə bölünür?", answer: 3, xp: 10 },
            { id: "ry6-bol-l1-t8", type: "multiple_choice", prompt: "748 ədədi hansına bölünür?", options: ["yalnız 2", "yalnız 5", "2 və 5", "10"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l1-t9", type: "multiple_choice", prompt: "265 ədədi hansına bölünür?", options: ["2", "5", "10", "2 və 10"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l1-t10", type: "fill_blank", prompt: "Son rəqəmi 0 olan ədəd 2-yə, 5-ə və ___-a bölünür.", accepted: ["10"], xp: 10 },
            { id: "ry6-bol-l1-t11", type: "multiple_choice", prompt: "Hansı ədəd HƏM 2-yə, HƏM də 5-ə bölünür?", options: ["25", "40", "14", "35"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l1-t12", type: "numeric", prompt: "50, 55, 60 ədədlərindən neçəsi 5-ə bölünür?", answer: 3, xp: 10 },
            { id: "ry6-bol-l1-t13", type: "multiple_choice", prompt: "999 ədədi 2-yə bölünürmü?", options: ["Bəli", "Xeyr"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l1-t14", type: "multiple_choice", prompt: "1 000 ədədi hansına bölünür?", options: ["yalnız 10", "2, 5 və 10", "yalnız 2", "heç birinə"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l1-t15", type: "multiple_choice", prompt: "Hansı ədəd nə 2-yə, nə də 5-ə bölünür?", options: ["30", "17", "20", "45"], correctIndex: 1, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-bol-l1-b1", type: "multiple_choice", prompt: "3 620 ədədi hansına bölünür?", options: ["yalnız 2", "2, 5 və 10", "yalnız 5", "heç birinə"], correctIndex: 1, xp: 15 },
            { id: "ry6-bol-l1-b2", type: "multiple_choice", prompt: "Son rəqəmi 5 olan ədəd 2-yə bölünürmü?", options: ["Bəli", "Xeyr"], correctIndex: 1, xp: 15 },
            { id: "ry6-bol-l1-b3", type: "numeric", prompt: "1-dən 100-ə qədər (100 daxil) 10-a bölünən neçə ədəd var?", answer: 10, xp: 15 },
            { id: "ry6-bol-l1-b4", type: "multiple_choice", prompt: "Hansı cüt ədəddir?", options: ["27", "39", "46", "51"], correctIndex: 2, xp: 15 },
            { id: "ry6-bol-l1-b5", type: "fill_blank", prompt: "10-a bölünən ədədin son rəqəmi həmişə ___-dır.", accepted: ["0"], xp: 15 },
          ],
        },
        {
          id: "ry6-bol-l2",
          title: "3-ə və 9-a bölünmə. Sadə və mürəkkəb ədədlər",
          intro: "Rəqəmlərin cəminə görə 3-ə və 9-a bölünmə; sadə və mürəkkəb ədədləri tanımaq.",
          sections: [
            { heading: "3-ə bölünmə", body: "Ədədin rəqəmləri cəmi 3-ə bölünürsə, ədədin özü də 3-ə bölünür. Məsələn: 51 → 5+1=6, 6 üç-ə bölünür, deməli 51 də 3-ə bölünür." },
            { heading: "9-a bölünmə", body: "Ədədin rəqəmləri cəmi 9-a bölünürsə, ədəd 9-a bölünür. Məsələn: 234 → 2+3+4=9 → 9-a bölünür." },
            { heading: "Sadə və mürəkkəb", body: "Yalnız iki böləni (1 və özü) olan ədədə sadə ədəd deyilir: 2, 3, 5, 7, 11... İkidən çox böləni olan ədəd mürəkkəbdir: 4, 6, 8, 9... 1 nə sadə, nə mürəkkəbdir." },
          ],
          tasks: [
            { id: "ry6-bol-l2-t1", type: "multiple_choice", prompt: "3-ə bölünmə əlaməti nədir?", options: ["rəqəmləri cəmi 3-ə bölünür", "son rəqəm 3-dür", "son rəqəm cütdür", "son rəqəm 0-dır"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l2-t2", type: "numeric", prompt: "51 ədədinin rəqəmləri cəmi neçədir?", answer: 6, xp: 10 },
            { id: "ry6-bol-l2-t3", type: "multiple_choice", prompt: "51 ədədi 3-ə bölünürmü? (5+1=6)", options: ["Bəli", "Xeyr"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l2-t4", type: "multiple_choice", prompt: "9-a bölünmə əlaməti nədir?", options: ["rəqəmləri cəmi 9-a bölünür", "son rəqəm 9-dur", "son rəqəm 0-dır", "cütdür"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l2-t5", type: "multiple_choice", prompt: "234 ədədi 9-a bölünürmü? (2+3+4=9)", options: ["Bəli", "Xeyr"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l2-t6", type: "multiple_choice", prompt: "Hansı ədəd 3-ə bölünür?", options: ["25", "42", "17", "28"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l2-t7", type: "numeric", prompt: "126 ədədinin rəqəmləri cəmi neçədir?", answer: 9, xp: 10 },
            { id: "ry6-bol-l2-t8", type: "multiple_choice", prompt: "126 ədədi hansına bölünür?", options: ["yalnız 3", "3 və 9", "yalnız 9", "heç birinə"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l2-t9", type: "multiple_choice", prompt: "Sadə ədəd nədir?", options: ["yalnız 1 və özünə bölünən", "hər cüt ədəd", "3-ə bölünən ədəd", "sıfır"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l2-t10", type: "multiple_choice", prompt: "Hansı sadə ədəddir?", options: ["9", "15", "7", "21"], correctIndex: 2, xp: 10 },
            { id: "ry6-bol-l2-t11", type: "multiple_choice", prompt: "Hansı mürəkkəb ədəddir?", options: ["2", "3", "11", "15"], correctIndex: 3, xp: 10 },
            { id: "ry6-bol-l2-t12", type: "multiple_choice", prompt: "1 ədədi sadədir, yoxsa mürəkkəb?", options: ["sadə", "mürəkkəb", "nə sadə, nə mürəkkəb", "hər ikisi"], correctIndex: 2, xp: 10 },
            { id: "ry6-bol-l2-t13", type: "numeric", prompt: "10-dan kiçik neçə sadə ədəd var? (2, 3, 5, 7)", answer: 4, xp: 10 },
            { id: "ry6-bol-l2-t14", type: "numeric", prompt: "Ən kiçik sadə ədəd neçədir?", answer: 2, xp: 10 },
            { id: "ry6-bol-l2-t15", type: "multiple_choice", prompt: "13 sadə ədəddirmi?", options: ["Bəli", "Xeyr"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-bol-l2-b1", type: "multiple_choice", prompt: "Hansı ədəd həm 3-ə, həm də 9-a bölünür?", options: ["12", "18", "15", "21"], correctIndex: 1, xp: 15 },
            { id: "ry6-bol-l2-b2", type: "numeric", prompt: "20-dən kiçik neçə sadə ədəd var? (2,3,5,7,11,13,17,19)", answer: 8, xp: 15 },
            { id: "ry6-bol-l2-b3", type: "multiple_choice", prompt: "2-dən başqa bütün sadə ədədlər necədir?", options: ["tək", "cüt", "sıfır", "10-a bölünən"], correctIndex: 0, xp: 15 },
            { id: "ry6-bol-l2-b4", type: "fill_blank", prompt: "Yalnız iki böləni (1 və özü) olan ədədə ___ ədəd deyilir.", accepted: ["sadə"], xp: 15 },
            { id: "ry6-bol-l2-b5", type: "multiple_choice", prompt: "Hansı mürəkkəb ədəddir?", options: ["17", "19", "25", "23"], correctIndex: 2, xp: 15 },
          ],
        },
        {
          id: "ry6-bol-l3",
          title: "Sadə vuruqlara ayırma. ƏBOB",
          intro: "Ədədi sadə vuruqların hasili kimi yazmaq və iki ədədin ən böyük ortaq bölənini tapmaq.",
          sections: [
            { heading: "Sadə vuruqlara ayırma", body: "Hər mürəkkəb ədəd sadə ədədlərin hasili kimi yazıla bilər: 12 = 2·2·3, 18 = 2·3·3, 24 = 2·2·2·3." },
            { heading: "ƏBOB nədir?", body: "İki (və ya bir neçə) ədədin hər ikisinə bölünən ən böyük ədədə onların Ən Böyük Ortaq Böləni (ƏBOB) deyilir. Məsələn ƏBOB(8, 12) = 4." },
            { heading: "Qarşılıqlı sadə", body: "Ortaq böləni yalnız 1 olan ədədlərə qarşılıqlı sadə deyilir: ƏBOB(9, 16) = 1." },
          ],
          tasks: [
            { id: "ry6-bol-l3-t1", type: "multiple_choice", prompt: "12 ədədinin sadə vuruqlara ayrılışı hansıdır?", options: ["2·6", "2·2·3", "3·4", "2·3"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l3-t2", type: "multiple_choice", prompt: "18 = ?", options: ["2·9", "2·3·3", "3·6", "2·2·3"], correctIndex: 1, xp: 10 },
            { id: "ry6-bol-l3-t3", type: "numeric", prompt: "8 ədədinin neçə böləni var? (1, 2, 4, 8)", answer: 4, xp: 10 },
            { id: "ry6-bol-l3-t4", type: "multiple_choice", prompt: "ƏBOB nə deməkdir?", options: ["ən böyük ortaq bölən", "ən böyük ortaq bölünən", "ən kiçik bölən", "cəm"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l3-t5", type: "numeric", prompt: "ƏBOB(8, 12) = ?", answer: 4, xp: 10 },
            { id: "ry6-bol-l3-t6", type: "numeric", prompt: "ƏBOB(6, 9) = ?", answer: 3, xp: 10 },
            { id: "ry6-bol-l3-t7", type: "numeric", prompt: "ƏBOB(10, 15) = ?", answer: 5, xp: 10 },
            { id: "ry6-bol-l3-t8", type: "multiple_choice", prompt: "Ortaq böləni yalnız 1 olan ədədlərə ... deyilir.", options: ["qarşılıqlı sadə", "mürəkkəb", "cüt", "bərabər"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l3-t9", type: "numeric", prompt: "ƏBOB(20, 30) = ?", answer: 10, xp: 10 },
            { id: "ry6-bol-l3-t10", type: "multiple_choice", prompt: "24 = 2·2·2·3 yazılışı nədir?", options: ["sadə vuruqlara ayrılış", "cəm", "fərq", "ƏKOB"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l3-t11", type: "numeric", prompt: "ƏBOB(16, 24) = ?", answer: 8, xp: 10 },
            { id: "ry6-bol-l3-t12", type: "numeric", prompt: "ƏBOB(7, 14) = ?", answer: 7, xp: 10 },
            { id: "ry6-bol-l3-t13", type: "numeric", prompt: "ƏBOB(9, 16) = ? (qarşılıqlı sadə)", answer: 1, xp: 10 },
            { id: "ry6-bol-l3-t14", type: "multiple_choice", prompt: "36 ədədinin sadə vuruqları hansılardır?", options: ["2 və 3", "2 və 5", "3 və 5", "yalnız 2"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l3-t15", type: "numeric", prompt: "ƏBOB(12, 18) = ?", answer: 6, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-bol-l3-b1", type: "numeric", prompt: "ƏBOB(15, 25) = ?", answer: 5, xp: 15 },
            { id: "ry6-bol-l3-b2", type: "numeric", prompt: "ƏBOB(48, 36) = ?", answer: 12, xp: 15 },
            { id: "ry6-bol-l3-b3", type: "multiple_choice", prompt: "8 və 9 qarşılıqlı sadədirmi?", options: ["Bəli (ƏBOB=1)", "Xeyr"], correctIndex: 0, xp: 15 },
            { id: "ry6-bol-l3-b4", type: "numeric", prompt: "ƏBOB(14, 21) = ?", answer: 7, xp: 15 },
            { id: "ry6-bol-l3-b5", type: "fill_blank", prompt: "Hər iki ədədə bölünən ən böyük ədədin qısaltması ___-dur.", accepted: ["ƏBOB", "əbob", "ebob"], xp: 15 },
          ],
        },
        {
          id: "ry6-bol-l4",
          title: "Ən kiçik ortaq bölünən (ƏKOB)",
          intro: "İki (və ya bir neçə) ədədin hər ikisinə bölünən ən kiçik ədədi tapmaq.",
          sections: [
            { heading: "ƏKOB nədir?", body: "Hər iki ədədə də bölünən ən kiçik (sıfırdan böyük) ədədə onların Ən Kiçik Ortaq Bölünəni (ƏKOB) deyilir. Məsələn ƏKOB(4, 6) = 12." },
            { heading: "Misli (qatı)", body: "Ədədin misli onu 1, 2, 3, ... ədədlərinə vurmaqla alınır: 4-ün mislləri 4, 8, 12, 16... ƏKOB ortaq misllərin ən kiçiyidir." },
            { heading: "Faydalı qayda", body: "İki ədəddən biri o birinə bölünürsə, ƏKOB böyük ədədin özüdür: ƏKOB(2, 8) = 8. Həmçinin ƏBOB·ƏKOB = a·b." },
          ],
          tasks: [
            { id: "ry6-bol-l4-t1", type: "multiple_choice", prompt: "ƏKOB nə deməkdir?", options: ["ən kiçik ortaq bölünən", "ən böyük ortaq bölən", "ən kiçik bölən", "cəm"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l4-t2", type: "numeric", prompt: "ƏKOB(4, 6) = ?", answer: 12, xp: 10 },
            { id: "ry6-bol-l4-t3", type: "numeric", prompt: "ƏKOB(3, 5) = ?", answer: 15, xp: 10 },
            { id: "ry6-bol-l4-t4", type: "numeric", prompt: "ƏKOB(2, 8) = ?", answer: 8, xp: 10 },
            { id: "ry6-bol-l4-t5", type: "numeric", prompt: "ƏKOB(6, 9) = ?", answer: 18, xp: 10 },
            { id: "ry6-bol-l4-t6", type: "multiple_choice", prompt: "4-ün ilk üç misli hansılardır?", options: ["4, 8, 12", "1, 2, 4", "4, 6, 8", "2, 4, 6"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l4-t7", type: "numeric", prompt: "ƏKOB(5, 10) = ?", answer: 10, xp: 10 },
            { id: "ry6-bol-l4-t8", type: "numeric", prompt: "ƏKOB(3, 4) = ?", answer: 12, xp: 10 },
            { id: "ry6-bol-l4-t9", type: "numeric", prompt: "ƏKOB(6, 8) = ?", answer: 24, xp: 10 },
            { id: "ry6-bol-l4-t10", type: "numeric", prompt: "ƏKOB(2, 3, 4) = ?", answer: 12, xp: 10 },
            { id: "ry6-bol-l4-t11", type: "multiple_choice", prompt: "Bir ədəd o birinə bölünürsə, ƏKOB nədir?", options: ["böyük ədəd", "kiçik ədəd", "1", "cəm"], correctIndex: 0, xp: 10 },
            { id: "ry6-bol-l4-t12", type: "numeric", prompt: "ƏKOB(7, 3) = ?", answer: 21, xp: 10 },
            { id: "ry6-bol-l4-t13", type: "numeric", prompt: "ƏKOB(10, 15) = ?", answer: 30, xp: 10 },
            { id: "ry6-bol-l4-t14", type: "numeric", prompt: "ƏKOB(8, 12) = ?", answer: 24, xp: 10 },
            { id: "ry6-bol-l4-t15", type: "numeric", prompt: "ƏKOB(9, 12) = ?", answer: 36, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-bol-l4-b1", type: "numeric", prompt: "ƏKOB(4, 5) = ?", answer: 20, xp: 15 },
            { id: "ry6-bol-l4-b2", type: "numeric", prompt: "ƏKOB(6, 10) = ?", answer: 30, xp: 15 },
            { id: "ry6-bol-l4-b3", type: "multiple_choice", prompt: "ƏBOB(a, b) · ƏKOB(a, b) nəyə bərabərdir?", options: ["a · b", "a + b", "a − b", "a ÷ b"], correctIndex: 0, xp: 15 },
            { id: "ry6-bol-l4-b4", type: "numeric", prompt: "ƏKOB(12, 16) = ?", answer: 48, xp: 15 },
            { id: "ry6-bol-l4-b5", type: "numeric", prompt: "ƏKOB(5, 6) = ?", answer: 30, xp: 15 },
          ],
        },
      ],
    },

    // ═══════════════ 2. Adi kəsrlər ═══════════════
    {
      id: "ry6-kesrler",
      title: "Adi kəsrlər üzərində əməllər",
      description:
        "Kəsrin əsas xassəsi və ixtisarı, ortaq məxrəcə gətirmə, toplama və çıxma, vurma və bölmə, qarışıq ədədlər, ədədin kəsrini tapma.",
      lessons: [
        {
          id: "ry6-kesr-l1",
          title: "Kəsrin əsas xassəsi və ixtisarı",
          intro: "Bərabər kəsrlər və kəsri ən sadə şəklə (ixtisar) gətirmək.",
          sections: [
            { heading: "Kəsrin əsas xassəsi", body: "Kəsrin surətini və məxrəcini eyni (sıfırdan fərqli) ədədə vursaq və ya bölsək, kəsrin qiyməti dəyişmir. Məsələn: 1/2 = 2/4 = 3/6." },
            { heading: "İxtisar", body: "Surət və məxrəci onların ortaq böləninə (ən yaxşısı ƏBOB-a) bölməklə kəsri kiçildirik: 6/8 = 3/4 (2-yə böldük)." },
            { heading: "Ən sadə forma", body: "Surət və məxrəcin ortaq böləni yalnız 1 olanda kəsr ən sadə formadadır: 3/4, 5/7." },
          ],
          tasks: [
            { id: "ry6-kesr-l1-t1", type: "multiple_choice", prompt: "Kəsrin surəti və məxrəci eyni ədədə vurulsa, kəsr necə olar?", options: ["dəyişməz (bərabər qalar)", "böyüyər", "kiçilər", "0 olar"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l1-t2", type: "fill_blank", prompt: "1/2 kəsrinin surət və məxrəcini 3-ə vur. Nəticə (a/b formatında)?", accepted: ["3/6"], xp: 10 },
            { id: "ry6-kesr-l1-t3", type: "fill_blank", prompt: "6/8 kəsrini ən sadə şəklə gətir (ixtisar et).", accepted: ["3/4"], xp: 10 },
            { id: "ry6-kesr-l1-t4", type: "fill_blank", prompt: "4/12 kəsrini ixtisar et.", accepted: ["1/3"], xp: 10 },
            { id: "ry6-kesr-l1-t5", type: "multiple_choice", prompt: "Hansı kəsr 1/2-yə bərabərdir?", options: ["2/3", "3/6", "2/5", "3/4"], correctIndex: 1, xp: 10 },
            { id: "ry6-kesr-l1-t6", type: "fill_blank", prompt: "10/15 kəsrini ixtisar et.", accepted: ["2/3"], xp: 10 },
            { id: "ry6-kesr-l1-t7", type: "multiple_choice", prompt: "Kəsri ixtisar etmək üçün surət və məxrəci nəyə bölürük?", options: ["ortaq bölənə", "cəminə", "fərqinə", "1-ə"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l1-t8", type: "fill_blank", prompt: "9/12 kəsrini ixtisar et.", accepted: ["3/4"], xp: 10 },
            { id: "ry6-kesr-l1-t9", type: "fill_blank", prompt: "5/10 kəsrini ixtisar et.", accepted: ["1/2"], xp: 10 },
            { id: "ry6-kesr-l1-t10", type: "multiple_choice", prompt: "12/16 kəsrinin ən sadə forması hansıdır?", options: ["6/8", "3/4", "4/5", "2/3"], correctIndex: 1, xp: 10 },
            { id: "ry6-kesr-l1-t11", type: "fill_blank", prompt: "8/20 kəsrini ixtisar et.", accepted: ["2/5"], xp: 10 },
            { id: "ry6-kesr-l1-t12", type: "multiple_choice", prompt: "Hansı kəsr artıq ən sadə formadadır?", options: ["4/6", "3/9", "5/7", "6/8"], correctIndex: 2, xp: 10 },
            { id: "ry6-kesr-l1-t13", type: "fill_blank", prompt: "14/21 kəsrini ixtisar et.", accepted: ["2/3"], xp: 10 },
            { id: "ry6-kesr-l1-t14", type: "fill_blank", prompt: "2/3 kəsrinin surət və məxrəcini 4-ə vur.", accepted: ["8/12"], xp: 10 },
            { id: "ry6-kesr-l1-t15", type: "fill_blank", prompt: "15/25 kəsrini ixtisar et.", accepted: ["3/5"], xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-kesr-l1-b1", type: "fill_blank", prompt: "24/36 kəsrini ixtisar et.", accepted: ["2/3"], xp: 15 },
            { id: "ry6-kesr-l1-b2", type: "multiple_choice", prompt: "3/4 və 6/8 kəsrləri...", options: ["bərabərdir", "3/4 böyükdür", "6/8 böyükdür", "müqayisə olunmur"], correctIndex: 0, xp: 15 },
            { id: "ry6-kesr-l1-b3", type: "fill_blank", prompt: "16/24 kəsrini ixtisar et.", accepted: ["2/3"], xp: 15 },
            { id: "ry6-kesr-l1-b4", type: "fill_blank", prompt: "7/28 kəsrini ixtisar et.", accepted: ["1/4"], xp: 15 },
            { id: "ry6-kesr-l1-b5", type: "multiple_choice", prompt: "18/24 kəsrinin ən sadə forması?", options: ["9/12", "3/4", "6/8", "2/3"], correctIndex: 1, xp: 15 },
          ],
        },
        {
          id: "ry6-kesr-l2",
          title: "Kəsrlərin toplanması və çıxılması",
          intro: "Eyni və müxtəlif məxrəcli kəsrləri toplamaq və çıxmaq.",
          sections: [
            { heading: "Eyni məxrəc", body: "Məxrəclər eynidirsə, surətləri toplayırıq (və ya çıxırıq), məxrəc dəyişmir: 1/5 + 2/5 = 3/5." },
            { heading: "Müxtəlif məxrəc", body: "Əvvəlcə kəsrləri ortaq məxrəcə (məxrəclərin ƏKOB-u) gətiririk, sonra toplayırıq: 1/2 + 1/3 = 3/6 + 2/6 = 5/6." },
            { heading: "Nəticəni ixtisar et", body: "Cavabı mümkünsə ən sadə şəklə gətir: 4/8 = 1/2." },
          ],
          tasks: [
            { id: "ry6-kesr-l2-t1", type: "multiple_choice", prompt: "Eyni məxrəcli kəsrləri toplayanda nə edirik?", options: ["surətləri toplayırıq, məxrəc qalır", "hər ikisini toplayırıq", "məxrəcləri toplayırıq", "vururuq"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l2-t2", type: "fill_blank", prompt: "1/5 + 2/5 = ?", accepted: ["3/5"], xp: 10 },
            { id: "ry6-kesr-l2-t3", type: "fill_blank", prompt: "3/7 + 2/7 = ?", accepted: ["5/7"], xp: 10 },
            { id: "ry6-kesr-l2-t4", type: "fill_blank", prompt: "5/8 − 1/8 = ? (ixtisar oluna bilər)", accepted: ["4/8", "1/2"], xp: 10 },
            { id: "ry6-kesr-l2-t5", type: "multiple_choice", prompt: "1/2 və 1/3 üçün ortaq məxrəc neçədir?", options: ["5", "6", "2", "3"], correctIndex: 1, xp: 10 },
            { id: "ry6-kesr-l2-t6", type: "fill_blank", prompt: "1/2 + 1/3 = ? (məxrəc 6)", accepted: ["5/6"], xp: 10 },
            { id: "ry6-kesr-l2-t7", type: "fill_blank", prompt: "1/2 + 1/4 = ?", accepted: ["3/4"], xp: 10 },
            { id: "ry6-kesr-l2-t8", type: "fill_blank", prompt: "2/3 + 1/6 = ?", accepted: ["5/6"], xp: 10 },
            { id: "ry6-kesr-l2-t9", type: "fill_blank", prompt: "3/4 − 1/2 = ?", accepted: ["1/4"], xp: 10 },
            { id: "ry6-kesr-l2-t10", type: "fill_blank", prompt: "5/6 − 1/3 = ?", accepted: ["1/2", "3/6"], xp: 10 },
            { id: "ry6-kesr-l2-t11", type: "multiple_choice", prompt: "1/4 + 1/4 + 1/4 = ?", options: ["3/4", "3/12", "1/4", "3/8"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l2-t12", type: "fill_blank", prompt: "2/5 + 1/10 = ? (məxrəc 10)", accepted: ["5/10", "1/2"], xp: 10 },
            { id: "ry6-kesr-l2-t13", type: "fill_blank", prompt: "7/8 − 3/8 = ?", accepted: ["4/8", "1/2"], xp: 10 },
            { id: "ry6-kesr-l2-t14", type: "fill_blank", prompt: "1/3 + 1/6 = ?", accepted: ["1/2", "3/6"], xp: 10 },
            { id: "ry6-kesr-l2-t15", type: "fill_blank", prompt: "1 − 1/4 = ?", accepted: ["3/4"], xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-kesr-l2-b1", type: "fill_blank", prompt: "2/3 + 1/4 = ? (məxrəc 12)", accepted: ["11/12"], xp: 15 },
            { id: "ry6-kesr-l2-b2", type: "fill_blank", prompt: "3/4 − 1/3 = ?", accepted: ["5/12"], xp: 15 },
            { id: "ry6-kesr-l2-b3", type: "fill_blank", prompt: "5/6 − 1/2 = ?", accepted: ["1/3", "2/6"], xp: 15 },
            { id: "ry6-kesr-l2-b4", type: "multiple_choice", prompt: "Ortaq məxrəc necə tapılır?", options: ["məxrəclərin ƏKOB-u", "surətlərin cəmi", "məxrəclərin cəmi", "həmişə 1"], correctIndex: 0, xp: 15 },
            { id: "ry6-kesr-l2-b5", type: "fill_blank", prompt: "1/2 + 1/3 + 1/6 = ?", accepted: ["1", "6/6"], xp: 15 },
          ],
        },
        {
          id: "ry6-kesr-l3",
          title: "Kəsrlərin vurulması və bölünməsi",
          intro: "Kəsrləri bir-birinə vurmaq və bölmək (tərs kəsrə vurma).",
          sections: [
            { heading: "Vurma", body: "Surəti surətə, məxrəci məxrəcə vururuq: 2/3 · 3/4 = 6/12 = 1/2. Məxrəclər eyni olmaya bilər." },
            { heading: "Tərs kəsr", body: "Kəsrin surət və məxrəcinin yerini dəyişsək tərs kəsri alınır: 2/3-ün tərsi 3/2. Kəsri öz tərsinə vursaq 1 alınır." },
            { heading: "Bölmə", body: "Bir kəsrə bölmək = onun tərs kəsrinə vurmaq: 1/2 ÷ 1/4 = 1/2 · 4/1 = 4/2 = 2." },
          ],
          tasks: [
            { id: "ry6-kesr-l3-t1", type: "multiple_choice", prompt: "İki kəsri vurmaq üçün nə edirik?", options: ["surəti surətə, məxrəci məxrəcə vururuq", "çarpaz vururuq", "toplayırıq", "məxrəcləri bərabərləşdiririk"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l3-t2", type: "fill_blank", prompt: "1/2 · 1/3 = ?", accepted: ["1/6"], xp: 10 },
            { id: "ry6-kesr-l3-t3", type: "fill_blank", prompt: "2/3 · 3/4 = ? (ixtisar oluna bilər)", accepted: ["6/12", "1/2"], xp: 10 },
            { id: "ry6-kesr-l3-t4", type: "fill_blank", prompt: "2/5 · 1/2 = ?", accepted: ["2/10", "1/5"], xp: 10 },
            { id: "ry6-kesr-l3-t5", type: "fill_blank", prompt: "3/4 · 2/3 = ?", accepted: ["6/12", "1/2"], xp: 10 },
            { id: "ry6-kesr-l3-t6", type: "multiple_choice", prompt: "Kəsri kəsrə bölmək üçün nə edirik?", options: ["ikinci kəsri çevirib vururuq", "toplayırıq", "surətləri bölürük", "məxrəcləri vururuq"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l3-t7", type: "fill_blank", prompt: "1/2 ÷ 1/4 = ?", accepted: ["2", "4/2"], xp: 10 },
            { id: "ry6-kesr-l3-t8", type: "fill_blank", prompt: "3/4 ÷ 1/2 = ?", accepted: ["3/2", "6/4"], xp: 10 },
            { id: "ry6-kesr-l3-t9", type: "fill_blank", prompt: "2/3 · 3 = ?", accepted: ["2", "6/3"], xp: 10 },
            { id: "ry6-kesr-l3-t10", type: "fill_blank", prompt: "1/4 · 4 = ?", accepted: ["1", "4/4"], xp: 10 },
            { id: "ry6-kesr-l3-t11", type: "multiple_choice", prompt: "1/2-nin tərs kəsri hansıdır?", options: ["2/1", "1/2", "2/2", "1/4"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l3-t12", type: "fill_blank", prompt: "5/6 · 2/5 = ?", accepted: ["10/30", "1/3"], xp: 10 },
            { id: "ry6-kesr-l3-t13", type: "fill_blank", prompt: "1/2 ÷ 2 = ?", accepted: ["1/4"], xp: 10 },
            { id: "ry6-kesr-l3-t14", type: "fill_blank", prompt: "3/5 · 5 = ?", accepted: ["3", "15/5"], xp: 10 },
            { id: "ry6-kesr-l3-t15", type: "fill_blank", prompt: "2/3 ÷ 4 = ?", accepted: ["2/12", "1/6"], xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-kesr-l3-b1", type: "fill_blank", prompt: "3/4 · 4/3 = ?", accepted: ["1", "12/12"], xp: 15 },
            { id: "ry6-kesr-l3-b2", type: "fill_blank", prompt: "5/8 ÷ 5/8 = ?", accepted: ["1"], xp: 15 },
            { id: "ry6-kesr-l3-b3", type: "multiple_choice", prompt: "Kəsri öz tərs kəsrinə vursaq nə alınar?", options: ["1", "0", "kəsr", "2"], correctIndex: 0, xp: 15 },
            { id: "ry6-kesr-l3-b4", type: "fill_blank", prompt: "2/7 · 7/2 = ?", accepted: ["1"], xp: 15 },
            { id: "ry6-kesr-l3-b5", type: "fill_blank", prompt: "6/7 ÷ 3/7 = ?", accepted: ["2", "42/21"], xp: 15 },
          ],
        },
        {
          id: "ry6-kesr-l4",
          title: "Qarışıq ədədlər. Ədədin kəsrini tapma",
          intro: "Düzgün olmayan kəsri qarışıq ədədə çevirmək və ədədin verilmiş kəsrini tapmaq.",
          sections: [
            { heading: "Qarışıq ədəd", body: "Surəti məxrəcdən böyük kəsr (düzgün olmayan) qarışıq ədədə çevrilir: 7/3 = 2 1/3 (7-ni 3-ə böl: 2 tam, 1 qalıq)." },
            { heading: "Geri çevirmə", body: "Qarışıq ədədi düzgün olmayan kəsrə çevirmək: 2 1/3 = (2·3+1)/3 = 7/3." },
            { heading: "Ədədin kəsrini tapma", body: "Ədədin kəsrini tapmaq üçün ədədi həmin kəsrə vururuq: 12-nin 1/3-i = 12 · 1/3 = 4. 24-ün 3/4-ü = 18." },
          ],
          tasks: [
            { id: "ry6-kesr-l4-t1", type: "multiple_choice", prompt: "7/3 kəsri qarışıq ədəd kimi necə yazılır?", options: ["2 1/3", "3 1/2", "1 2/3", "2 2/3"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l4-t2", type: "fill_blank", prompt: "9/4 kəsrini qarışıq ədədə çevir (məs. '2 1/4').", accepted: ["2 1/4"], xp: 10 },
            { id: "ry6-kesr-l4-t3", type: "fill_blank", prompt: "11/5 kəsrini qarışıq ədədə çevir.", accepted: ["2 1/5"], xp: 10 },
            { id: "ry6-kesr-l4-t4", type: "multiple_choice", prompt: "2 1/2 düzgün olmayan kəsr kimi necə yazılır?", options: ["5/2", "3/2", "4/2", "2/2"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l4-t5", type: "fill_blank", prompt: "1 3/4 düzgün olmayan kəsr kimi yaz.", accepted: ["7/4"], xp: 10 },
            { id: "ry6-kesr-l4-t6", type: "numeric", prompt: "12-nin 1/3-i neçədir?", answer: 4, xp: 10 },
            { id: "ry6-kesr-l4-t7", type: "numeric", prompt: "20-nin 1/4-i neçədir?", answer: 5, xp: 10 },
            { id: "ry6-kesr-l4-t8", type: "numeric", prompt: "30-un 2/3-i neçədir?", answer: 20, xp: 10 },
            { id: "ry6-kesr-l4-t9", type: "numeric", prompt: "24-ün 3/4-ü neçədir?", answer: 18, xp: 10 },
            { id: "ry6-kesr-l4-t10", type: "numeric", prompt: "50-nin 1/5-i neçədir?", answer: 10, xp: 10 },
            { id: "ry6-kesr-l4-t11", type: "numeric", prompt: "18-in 2/9-u neçədir?", answer: 4, xp: 10 },
            { id: "ry6-kesr-l4-t12", type: "numeric", prompt: "100-ün 3/5-i neçədir?", answer: 60, xp: 10 },
            { id: "ry6-kesr-l4-t13", type: "multiple_choice", prompt: "Ədədin kəsrini tapmaq üçün nə edirik?", options: ["ədədi kəsrə vururuq", "ədədi kəsrə bölürük", "toplayırıq", "çıxırıq"], correctIndex: 0, xp: 10 },
            { id: "ry6-kesr-l4-t14", type: "numeric", prompt: "40-ın 1/8-i neçədir?", answer: 5, xp: 10 },
            { id: "ry6-kesr-l4-t15", type: "numeric", prompt: "36-nın 5/6-sı neçədir?", answer: 30, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-kesr-l4-b1", type: "numeric", prompt: "60-ın 3/4-ü neçədir?", answer: 45, xp: 15 },
            { id: "ry6-kesr-l4-b2", type: "fill_blank", prompt: "13/4 kəsrini qarışıq ədədə çevir.", accepted: ["3 1/4"], xp: 15 },
            { id: "ry6-kesr-l4-b3", type: "numeric", prompt: "45-in 2/9-u neçədir?", answer: 10, xp: 15 },
            { id: "ry6-kesr-l4-b4", type: "fill_blank", prompt: "3 1/3 düzgün olmayan kəsr kimi yaz.", accepted: ["10/3"], xp: 15 },
            { id: "ry6-kesr-l4-b5", type: "numeric", prompt: "80-in 3/8-i neçədir?", answer: 30, xp: 15 },
          ],
        },
      ],
    },

    // ═══════════════ 3. Onluq kəsrlər ═══════════════
    {
      id: "ry6-onluq",
      title: "Onluq kəsrlər üzərində əməllər",
      description:
        "Onluq kəsrlərin oxunuşu və müqayisəsi, toplama və çıxma, vurma, bölmə, yuvarlaqlaşdırma və adi kəsrlə əlaqə.",
      lessons: [
        {
          id: "ry6-onl-l1",
          title: "Onluq kəsrlərin oxunuşu və müqayisəsi",
          intro: "Onluq kəsrləri oxumaq, mərtəbələri tanımaq və müqayisə etmək.",
          sections: [
            { heading: "Onluq kəsr nədir?", body: "Vergüldən sonra mərtəbələri olan ədəd onluq kəsrdir: 3,5 (üç tam beş onda bir). Vergül tam hissəni kəsr hissədən ayırır." },
            { heading: "Mərtəbələr", body: "Vergüldən sonra: birinci — onda bir, ikinci — yüzdə bir, üçüncü — mində bir. 0,25 = 25 yüzdə bir." },
            { heading: "Müqayisə", body: "Əvvəlcə tam hissəni müqayisə edirik; bərabərdirsə vergüldən sonrakı rəqəmləri soldan müqayisə edirik: 3,45 > 3,4 (çünki 3,45 = 3,45; 3,40)." },
          ],
          tasks: [
            { id: "ry6-onl-l1-t1", type: "multiple_choice", prompt: "0,7 onluq kəsri necə oxunur?", options: ["yeddi onda bir", "yeddi yüzdə bir", "yeddi tam", "yetmiş"], correctIndex: 0, xp: 10 },
            { id: "ry6-onl-l1-t2", type: "multiple_choice", prompt: "'Üç tam iki onda bir' necə yazılır?", options: ["3,2", "3,02", "32", "0,32"], correctIndex: 0, xp: 10 },
            { id: "ry6-onl-l1-t3", type: "multiple_choice", prompt: "0,25-də 2 rəqəmi hansı mərtəbədədir?", options: ["onda bir", "yüzdə bir", "təklik", "mində bir"], correctIndex: 0, xp: 10 },
            { id: "ry6-onl-l1-t4", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 3,45 ___ 3,4", accepted: [">"], xp: 10 },
            { id: "ry6-onl-l1-t5", type: "fill_blank", prompt: "Uyğun işarəni yaz: 0,6 ___ 0,60", accepted: ["="], xp: 10 },
            { id: "ry6-onl-l1-t6", type: "multiple_choice", prompt: "Hansı ən böyükdür?", options: ["0,5", "0,45", "0,55", "0,4"], correctIndex: 2, xp: 10 },
            { id: "ry6-onl-l1-t7", type: "fill_blank", prompt: "Uyğun işarəni yaz: 2,3 ___ 2,30", accepted: ["="], xp: 10 },
            { id: "ry6-onl-l1-t8", type: "multiple_choice", prompt: "0,05 necə oxunur?", options: ["beş yüzdə bir", "beş onda bir", "beş tam", "əlli"], correctIndex: 0, xp: 10 },
            { id: "ry6-onl-l1-t9", type: "fill_blank", prompt: "Uyğun işarəni yaz: 1,2 ___ 1,19", accepted: [">"], xp: 10 },
            { id: "ry6-onl-l1-t10", type: "multiple_choice", prompt: "Hansı ən kiçikdir?", options: ["0,8", "0,08", "0,18", "0,1"], correctIndex: 1, xp: 10 },
            { id: "ry6-onl-l1-t11", type: "multiple_choice", prompt: "'Sıfır tam beş yüzdə bir' necə yazılır?", options: ["0,05", "0,5", "5,0", "0,005"], correctIndex: 0, xp: 10 },
            { id: "ry6-onl-l1-t12", type: "fill_blank", prompt: "Uyğun işarəni yaz: 4,7 ___ 4,70", accepted: ["="], xp: 10 },
            { id: "ry6-onl-l1-t13", type: "multiple_choice", prompt: "12,34-də 4 rəqəmi hansı mərtəbədədir?", options: ["yüzdə bir", "onda bir", "təklik", "onluq"], correctIndex: 0, xp: 10 },
            { id: "ry6-onl-l1-t14", type: "fill_blank", prompt: "Uyğun işarəni yaz: 0,9 ___ 1,0", accepted: ["<"], xp: 10 },
            { id: "ry6-onl-l1-t15", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün sıralanıb (kiçikdən böyüyə)?", options: ["0,3; 0,25; 0,4", "0,25; 0,3; 0,4", "0,4; 0,3; 0,25", "0,3; 0,4; 0,25"], correctIndex: 1, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-onl-l1-b1", type: "multiple_choice", prompt: "0,125-də 5 rəqəmi hansı mərtəbədədir?", options: ["mində bir", "yüzdə bir", "onda bir", "təklik"], correctIndex: 0, xp: 15 },
            { id: "ry6-onl-l1-b2", type: "fill_blank", prompt: "Uyğun işarəni yaz: 5,06 ___ 5,6", accepted: ["<"], xp: 15 },
            { id: "ry6-onl-l1-b3", type: "multiple_choice", prompt: "Hansı 0,5-ə bərabərdir?", options: ["0,50", "0,05", "5,0", "0,005"], correctIndex: 0, xp: 15 },
            { id: "ry6-onl-l1-b4", type: "fill_blank", prompt: "Uyğun işarəni yaz: 3,14 ___ 3,041", accepted: [">"], xp: 15 },
            { id: "ry6-onl-l1-b5", type: "multiple_choice", prompt: "10,1 ədədində vergüldən sonrakı rəqəm neçə onda birdir?", options: ["1", "10", "0", "11"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry6-onl-l2",
          title: "Onluq kəsrlərin toplanması və çıxılması",
          intro: "Onluq kəsrləri vergülü vergülün altına yazaraq toplamaq və çıxmaq.",
          sections: [
            { heading: "Qayda", body: "Ədədləri vergül vergülün altında olacaq şəkildə alt-alta yazırıq, sonra adi ədədlər kimi toplayırıq/çıxırıq. Vergül nəticədə də eyni yerdə qalır." },
            { heading: "Mərtəbələri bərabərləşdir", body: "Lazım olsa sonuna sıfır əlavə et: 3,5 − 1,25 → 3,50 − 1,25 = 2,25." },
          ],
          tasks: [
            { id: "ry6-onl-l2-t1", type: "numeric", prompt: "0,3 + 0,4 = ? (onluq)", answer: 0.7, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t2", type: "numeric", prompt: "1,5 + 2,3 = ?", answer: 3.8, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t3", type: "numeric", prompt: "0,7 − 0,2 = ?", answer: 0.5, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t4", type: "numeric", prompt: "2,5 + 1,25 = ?", answer: 3.75, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t5", type: "numeric", prompt: "3,5 − 1,25 = ?", answer: 2.25, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t6", type: "numeric", prompt: "0,25 + 0,75 = ?", answer: 1, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t7", type: "numeric", prompt: "5,6 − 2,4 = ?", answer: 3.2, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t8", type: "numeric", prompt: "1,1 + 2,2 + 3,3 = ?", answer: 6.6, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t9", type: "numeric", prompt: "4 − 1,5 = ?", answer: 2.5, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t10", type: "numeric", prompt: "0,45 + 0,55 = ?", answer: 1, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t11", type: "numeric", prompt: "7,8 − 3,6 = ?", answer: 4.2, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t12", type: "numeric", prompt: "2,05 + 1,95 = ?", answer: 4, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t13", type: "numeric", prompt: "10 − 0,5 = ?", answer: 9.5, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t14", type: "numeric", prompt: "3,14 + 2,86 = ?", answer: 6, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l2-t15", type: "numeric", prompt: "8,25 − 4,75 = ?", answer: 3.5, tolerance: 0.001, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-onl-l2-b1", type: "numeric", prompt: "12,6 + 7,45 = ?", answer: 20.05, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l2-b2", type: "numeric", prompt: "15 − 6,25 = ?", answer: 8.75, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l2-b3", type: "numeric", prompt: "0,125 + 0,875 = ?", answer: 1, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l2-b4", type: "numeric", prompt: "9,9 − 0,99 = ?", answer: 8.91, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l2-b5", type: "numeric", prompt: "100,5 + 0,5 = ?", answer: 101, tolerance: 0.001, xp: 15 },
          ],
        },
        {
          id: "ry6-onl-l3",
          title: "Onluq kəsrlərin vurulması və bölünməsi",
          intro: "Onluq kəsri onluq kəsrə və natural ədədə vurmaq, bölmək.",
          sections: [
            { heading: "10, 100, 1000-ə vurma", body: "Vergülü sağa aparırıq: 3,45 · 10 = 34,5; 3,45 · 100 = 345. Neçə sıfır varsa, o qədər mərtəbə." },
            { heading: "10, 100-ə bölmə", body: "Vergülü sola aparırıq: 34,5 ÷ 10 = 3,45; 345 ÷ 100 = 3,45." },
            { heading: "İki onluğu vurma", body: "Vergülləri saymadan vururuq, sonra hər iki ədəddəki vergüldən sonrakı rəqəmlərin cəmi qədər mərtəbəni nəticədə vergüllə ayırırıq: 0,2 · 0,3 = 0,06." },
          ],
          tasks: [
            { id: "ry6-onl-l3-t1", type: "numeric", prompt: "3,45 · 10 = ?", answer: 34.5, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t2", type: "numeric", prompt: "2,5 · 100 = ?", answer: 250, tolerance: 0.01, xp: 10 },
            { id: "ry6-onl-l3-t3", type: "numeric", prompt: "34,5 ÷ 10 = ?", answer: 3.45, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t4", type: "numeric", prompt: "0,2 · 0,3 = ?", answer: 0.06, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t5", type: "numeric", prompt: "1,5 · 2 = ?", answer: 3, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t6", type: "numeric", prompt: "0,5 · 0,5 = ?", answer: 0.25, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t7", type: "numeric", prompt: "4,2 · 3 = ?", answer: 12.6, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t8", type: "numeric", prompt: "6,4 ÷ 2 = ?", answer: 3.2, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t9", type: "numeric", prompt: "0,36 · 10 = ?", answer: 3.6, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t10", type: "numeric", prompt: "250 ÷ 100 = ?", answer: 2.5, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t11", type: "numeric", prompt: "0,1 · 0,1 = ?", answer: 0.01, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t12", type: "numeric", prompt: "9 ÷ 10 = ?", answer: 0.9, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t13", type: "numeric", prompt: "1,25 · 4 = ?", answer: 5, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t14", type: "numeric", prompt: "0,8 · 5 = ?", answer: 4, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l3-t15", type: "numeric", prompt: "7,5 ÷ 5 = ?", answer: 1.5, tolerance: 0.001, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-onl-l3-b1", type: "numeric", prompt: "1,2 · 1,2 = ?", answer: 1.44, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l3-b2", type: "numeric", prompt: "0,25 · 8 = ?", answer: 2, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l3-b3", type: "numeric", prompt: "4,5 ÷ 100 = ?", answer: 0.045, tolerance: 0.0001, xp: 15 },
            { id: "ry6-onl-l3-b4", type: "numeric", prompt: "0,04 · 0,5 = ?", answer: 0.02, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l3-b5", type: "numeric", prompt: "12,5 · 4 = ?", answer: 50, tolerance: 0.01, xp: 15 },
          ],
        },
        {
          id: "ry6-onl-l4",
          title: "Yuvarlaqlaşdırma. Onluq və adi kəsrin əlaqəsi",
          intro: "Onluq kəsri verilmiş mərtəbəyə qədər yuvarlaqlaşdırmaq və adi kəsrlə çevirmək.",
          sections: [
            { heading: "Yuvarlaqlaşdırma", body: "Atılan mərtəbədəki rəqəm 5 və ya böyükdürsə, saxlanan rəqəmi 1 artırırıq; kiçikdirsə dəyişmirik. 3,47 → onda birə qədər: 3,5 (7≥5). 3,42 → 3,4." },
            { heading: "Onluq → adi kəsr", body: "0,5 = 5/10 = 1/2. 0,25 = 25/100 = 1/4. 0,75 = 3/4. Vergüldən sonra neçə rəqəm varsa, məxrəc o qədər sıfırlı 10-un qüvvətidir." },
            { heading: "Adi → onluq", body: "Bəzi adi kəsrləri onluğa çevirmək olar: 1/2 = 0,5; 1/4 = 0,25; 3/5 = 0,6 (surəti məxrəcə bölürük)." },
          ],
          tasks: [
            { id: "ry6-onl-l4-t1", type: "numeric", prompt: "3,47 ədədini onda birə qədər yuvarlaqlaşdır.", answer: 3.5, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l4-t2", type: "numeric", prompt: "3,42 ədədini onda birə qədər yuvarlaqlaşdır.", answer: 3.4, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l4-t3", type: "numeric", prompt: "5,68 ədədini tama qədər yuvarlaqlaşdır.", answer: 6, tolerance: 0.01, xp: 10 },
            { id: "ry6-onl-l4-t4", type: "numeric", prompt: "2,3 ədədini tama qədər yuvarlaqlaşdır.", answer: 2, tolerance: 0.01, xp: 10 },
            { id: "ry6-onl-l4-t5", type: "fill_blank", prompt: "0,5 onluğunu adi kəsr kimi yaz (ən sadə).", accepted: ["1/2"], xp: 10 },
            { id: "ry6-onl-l4-t6", type: "fill_blank", prompt: "0,25 onluğunu adi kəsr kimi yaz.", accepted: ["1/4"], xp: 10 },
            { id: "ry6-onl-l4-t7", type: "fill_blank", prompt: "0,75 onluğunu adi kəsr kimi yaz.", accepted: ["3/4"], xp: 10 },
            { id: "ry6-onl-l4-t8", type: "numeric", prompt: "1/2 adi kəsrini onluğa çevir.", answer: 0.5, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l4-t9", type: "numeric", prompt: "1/4 adi kəsrini onluğa çevir.", answer: 0.25, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l4-t10", type: "numeric", prompt: "3/5 adi kəsrini onluğa çevir.", answer: 0.6, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l4-t11", type: "numeric", prompt: "7,85 ədədini onda birə qədər yuvarlaqlaşdır.", answer: 7.9, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l4-t12", type: "fill_blank", prompt: "0,2 onluğunu adi kəsr kimi yaz (ən sadə).", accepted: ["1/5"], xp: 10 },
            { id: "ry6-onl-l4-t13", type: "numeric", prompt: "9,49 ədədini tama qədər yuvarlaqlaşdır.", answer: 9, tolerance: 0.01, xp: 10 },
            { id: "ry6-onl-l4-t14", type: "numeric", prompt: "1/5 adi kəsrini onluğa çevir.", answer: 0.2, tolerance: 0.001, xp: 10 },
            { id: "ry6-onl-l4-t15", type: "numeric", prompt: "0,125 ədədini yüzdə birə qədər yuvarlaqlaşdır.", answer: 0.13, tolerance: 0.001, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-onl-l4-b1", type: "fill_blank", prompt: "0,05 onluğunu adi kəsr kimi yaz (ən sadə).", accepted: ["1/20"], xp: 15 },
            { id: "ry6-onl-l4-b2", type: "numeric", prompt: "3/4 adi kəsrini onluğa çevir.", answer: 0.75, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l4-b3", type: "numeric", prompt: "12,55 ədədini onda birə qədər yuvarlaqlaşdır.", answer: 12.6, tolerance: 0.001, xp: 15 },
            { id: "ry6-onl-l4-b4", type: "fill_blank", prompt: "0,4 onluğunu adi kəsr kimi yaz (ən sadə).", accepted: ["2/5"], xp: 15 },
            { id: "ry6-onl-l4-b5", type: "numeric", prompt: "2/5 adi kəsrini onluğa çevir.", answer: 0.4, tolerance: 0.001, xp: 15 },
          ],
        },
      ],
    },

    // ═══════════════ 4. Nisbət və tənasüb ═══════════════
    {
      id: "ry6-nisbet",
      title: "Nisbət və tənasüb",
      description:
        "İki kəmiyyətin nisbəti, tənasüb və onun əsas xassəsi, düz və tərs mütənasib kəmiyyətlər, miqyas.",
      lessons: [
        {
          id: "ry6-nis-l1",
          title: "Nisbət",
          intro: "İki ədədin (kəmiyyətin) nisbətini qurmaq və sadələşdirmək.",
          sections: [
            { heading: "Nisbət nədir?", body: "İki ədədin bölünməsinə onların nisbəti deyilir: a : b (a-nın b-yə nisbəti). 6 : 3 = 2, yəni 6, 3-dən 2 dəfə böyükdür." },
            { heading: "Nisbətin sadələşdirilməsi", body: "Nisbəti kəsr kimi ixtisar edirik: 8 : 12 = 2 : 3. Hər iki hədi ortaq bölənə bölürük." },
            { heading: "Tətbiq", body: "Nisbət hissələri bildirir: bir sinifdə oğlan və qızların nisbəti 3 : 2 deməkdir — hər 3 oğlana 2 qız düşür." },
          ],
          tasks: [
            { id: "ry6-nis-l1-t1", type: "multiple_choice", prompt: "6 : 3 nisbəti neçəyə bərabərdir?", options: ["2", "3", "18", "9"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l1-t2", type: "fill_blank", prompt: "8 : 12 nisbətini sadələşdir (a:b formatı, məs. '2:3').", accepted: ["2:3"], xp: 10 },
            { id: "ry6-nis-l1-t3", type: "fill_blank", prompt: "10 : 15 nisbətini sadələşdir.", accepted: ["2:3"], xp: 10 },
            { id: "ry6-nis-l1-t4", type: "fill_blank", prompt: "4 : 8 nisbətini sadələşdir.", accepted: ["1:2"], xp: 10 },
            { id: "ry6-nis-l1-t5", type: "multiple_choice", prompt: "20 : 5 nisbəti neçəyə bərabərdir?", options: ["4", "5", "15", "25"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l1-t6", type: "fill_blank", prompt: "9 : 12 nisbətini sadələşdir.", accepted: ["3:4"], xp: 10 },
            { id: "ry6-nis-l1-t7", type: "fill_blank", prompt: "15 : 25 nisbətini sadələşdir.", accepted: ["3:5"], xp: 10 },
            { id: "ry6-nis-l1-t8", type: "multiple_choice", prompt: "'3:2 nisbəti' nə deməkdir?", options: ["hər 3-ə 2 düşür", "3 və 2 bərabərdir", "cəmi 5", "fərqi 1"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l1-t9", type: "fill_blank", prompt: "6 : 9 nisbətini sadələşdir.", accepted: ["2:3"], xp: 10 },
            { id: "ry6-nis-l1-t10", type: "fill_blank", prompt: "14 : 21 nisbətini sadələşdir.", accepted: ["2:3"], xp: 10 },
            { id: "ry6-nis-l1-t11", type: "numeric", prompt: "24 : 8 nisbəti neçəyə bərabərdir?", answer: 3, xp: 10 },
            { id: "ry6-nis-l1-t12", type: "fill_blank", prompt: "12 : 16 nisbətini sadələşdir.", accepted: ["3:4"], xp: 10 },
            { id: "ry6-nis-l1-t13", type: "fill_blank", prompt: "5 : 10 nisbətini sadələşdir.", accepted: ["1:2"], xp: 10 },
            { id: "ry6-nis-l1-t14", type: "multiple_choice", prompt: "Bir qutuda 4 qırmızı, 6 mavi kart var. Qırmızıların maviyə nisbəti?", options: ["2:3", "3:2", "4:10", "1:2"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l1-t15", type: "fill_blank", prompt: "18 : 24 nisbətini sadələşdir.", accepted: ["3:4"], xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-nis-l1-b1", type: "fill_blank", prompt: "25 : 100 nisbətini sadələşdir.", accepted: ["1:4"], xp: 15 },
            { id: "ry6-nis-l1-b2", type: "fill_blank", prompt: "0,5 : 1 nisbətini tam ədədlərlə yaz (məs. '1:2').", accepted: ["1:2"], xp: 15 },
            { id: "ry6-nis-l1-b3", type: "numeric", prompt: "100 : 25 nisbəti neçəyə bərabərdir?", answer: 4, xp: 15 },
            { id: "ry6-nis-l1-b4", type: "fill_blank", prompt: "16 : 20 nisbətini sadələşdir.", accepted: ["4:5"], xp: 15 },
            { id: "ry6-nis-l1-b5", type: "multiple_choice", prompt: "2 : 3 və 4 : 6 nisbətləri...", options: ["bərabərdir", "fərqlidir", "müqayisə olunmur", "tərsdir"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry6-nis-l2",
          title: "Tənasüb və onun əsas xassəsi",
          intro: "İki nisbətin bərabərliyi (tənasüb) və naməlum hədin tapılması.",
          sections: [
            { heading: "Tənasüb nədir?", body: "İki nisbətin bərabərliyinə tənasüb deyilir: a : b = c : d. Məsələn 2 : 3 = 4 : 6." },
            { heading: "Əsas xassə", body: "Tənasübdə kənar hədlərin hasili orta hədlərin hasilinə bərabərdir: a·d = b·c. 2·6 = 3·4 = 12." },
            { heading: "Naməlumu tapma", body: "x : 3 = 4 : 6 → 6x = 12 → x = 2. Çarpaz vururuq və tənliyi həll edirik." },
          ],
          tasks: [
            { id: "ry6-nis-l2-t1", type: "multiple_choice", prompt: "İki nisbətin bərabərliyinə nə deyilir?", options: ["tənasüb", "nisbət", "faiz", "fərq"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l2-t2", type: "multiple_choice", prompt: "Tənasübün əsas xassəsi nədir?", options: ["kənar hədlərin hasili = orta hədlərin hasili", "cəmləri bərabərdir", "fərqləri 0-dır", "hamısı bərabərdir"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l2-t3", type: "numeric", prompt: "x : 3 = 4 : 6 tənasübündə x = ?", answer: 2, xp: 10 },
            { id: "ry6-nis-l2-t4", type: "numeric", prompt: "2 : 5 = x : 10 tənasübündə x = ?", answer: 4, xp: 10 },
            { id: "ry6-nis-l2-t5", type: "numeric", prompt: "3 : x = 6 : 8 tənasübündə x = ?", answer: 4, xp: 10 },
            { id: "ry6-nis-l2-t6", type: "multiple_choice", prompt: "2 : 3 = 4 : 6 tənasübdürmü? (2·6 və 3·4)", options: ["Bəli", "Xeyr"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l2-t7", type: "numeric", prompt: "1 : 2 = 5 : x tənasübündə x = ?", answer: 10, xp: 10 },
            { id: "ry6-nis-l2-t8", type: "numeric", prompt: "x : 4 = 3 : 2 tənasübündə x = ?", answer: 6, xp: 10 },
            { id: "ry6-nis-l2-t9", type: "numeric", prompt: "4 : 6 = 6 : x tənasübündə x = ?", answer: 9, xp: 10 },
            { id: "ry6-nis-l2-t10", type: "numeric", prompt: "5 : 10 = x : 4 tənasübündə x = ?", answer: 2, xp: 10 },
            { id: "ry6-nis-l2-t11", type: "multiple_choice", prompt: "3 : 4 = 6 : 8 tənasübündə kənar hədlər hansılardır?", options: ["3 və 8", "4 və 6", "3 və 4", "6 və 8"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l2-t12", type: "numeric", prompt: "2 : 7 = x : 21 tənasübündə x = ?", answer: 6, xp: 10 },
            { id: "ry6-nis-l2-t13", type: "numeric", prompt: "x : 5 = 8 : 10 tənasübündə x = ?", answer: 4, xp: 10 },
            { id: "ry6-nis-l2-t14", type: "numeric", prompt: "9 : x = 3 : 2 tənasübündə x = ?", answer: 6, xp: 10 },
            { id: "ry6-nis-l2-t15", type: "numeric", prompt: "12 : 8 = x : 2 tənasübündə x = ?", answer: 3, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-nis-l2-b1", type: "numeric", prompt: "x : 6 = 10 : 15 tənasübündə x = ?", answer: 4, xp: 15 },
            { id: "ry6-nis-l2-b2", type: "numeric", prompt: "7 : 14 = x : 20 tənasübündə x = ?", answer: 10, xp: 15 },
            { id: "ry6-nis-l2-b3", type: "numeric", prompt: "2,5 : 5 = x : 8 tənasübündə x = ?", answer: 4, xp: 15 },
            { id: "ry6-nis-l2-b4", type: "multiple_choice", prompt: "5 : 6 = 10 : 12 tənasübdürmü?", options: ["Bəli", "Xeyr"], correctIndex: 0, xp: 15 },
            { id: "ry6-nis-l2-b5", type: "numeric", prompt: "100 : x = 4 : 1 tənasübündə x = ?", answer: 25, xp: 15 },
          ],
        },
        {
          id: "ry6-nis-l3",
          title: "Düz və tərs mütənasib kəmiyyətlər",
          intro: "Bir kəmiyyət artdıqda o birinin necə dəyişdiyini müəyyən etmək və məsələ həll etmək.",
          sections: [
            { heading: "Düz mütənasiblik", body: "Bir kəmiyyət neçə dəfə artırsa, digəri də o qədər dəfə artırsa, onlar düz mütənasibdir: 1 kq alma 2 ₼-dirsə, 3 kq 6 ₼-dir." },
            { heading: "Tərs mütənasiblik", body: "Bir kəmiyyət neçə dəfə artırsa, digəri o qədər dəfə azalırsa, onlar tərs mütənasibdir: 2 fəhlə işi 6 gündə görürsə, 4 fəhlə 3 gündə görər." },
            { heading: "Məsələ həlli", body: "Düz mütənasibdə tənasüb qururuq; tərs mütənasibdə hasil sabit qalır (a₁·b₁ = a₂·b₂)." },
          ],
          tasks: [
            { id: "ry6-nis-l3-t1", type: "multiple_choice", prompt: "1 kq alma 2 ₼-dirsə, 3 kq neçə ₼-dir? (düz mütənasib)", options: ["6", "5", "4", "9"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l3-t2", type: "numeric", prompt: "1 dəftər 3 ₼-dirsə, 5 dəftər neçə ₼-dir?", answer: 15, xp: 10 },
            { id: "ry6-nis-l3-t3", type: "multiple_choice", prompt: "Bir kəmiyyət artdıqca digəri də eyni dəfə artırsa, bu ...?", options: ["düz mütənasib", "tərs mütənasib", "bərabər", "əlaqəsiz"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l3-t4", type: "multiple_choice", prompt: "2 fəhlə işi 6 gündə görür. 4 fəhlə neçə gündə görər? (tərs mütənasib)", options: ["3", "12", "6", "8"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l3-t5", type: "numeric", prompt: "3 qələm 12 ₼-dirsə, 1 qələm neçə ₼-dir?", answer: 4, xp: 10 },
            { id: "ry6-nis-l3-t6", type: "numeric", prompt: "2 kq kartof 3 ₼-dirsə, 6 kq neçə ₼-dir?", answer: 9, xp: 10 },
            { id: "ry6-nis-l3-t7", type: "multiple_choice", prompt: "Bir kəmiyyət artdıqca digəri azalırsa, bu ...?", options: ["tərs mütənasib", "düz mütənasib", "bərabər", "sabit"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l3-t8", type: "numeric", prompt: "1 maşın 4 saatda gedir. 2 maşın eyni işi neçə saatda görər? (tərs)", answer: 2, xp: 10 },
            { id: "ry6-nis-l3-t9", type: "numeric", prompt: "5 bilet 25 ₼-dirsə, 3 bilet neçə ₼-dir?", answer: 15, xp: 10 },
            { id: "ry6-nis-l3-t10", type: "numeric", prompt: "4 fəhlə işi 6 saatda görür. 6 fəhlə neçə saatda görər? (tərs, hasil=24)", answer: 4, xp: 10 },
            { id: "ry6-nis-l3-t11", type: "numeric", prompt: "2 m parça 8 ₼-dirsə, 5 m neçə ₼-dir?", answer: 20, xp: 10 },
            { id: "ry6-nis-l3-t12", type: "numeric", prompt: "1 avtomobil 60 km/saatla 2 saatda gedir. 120 km-i neçə saata gedər? (60 km/saat)", answer: 2, xp: 10 },
            { id: "ry6-nis-l3-t13", type: "multiple_choice", prompt: "Sürət və vaxt (sabit məsafədə) hansı əlaqədədir?", options: ["tərs mütənasib", "düz mütənasib", "bərabər", "əlaqəsiz"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l3-t14", type: "numeric", prompt: "6 kq alma 18 ₼-dirsə, 2 kq neçə ₼-dir?", answer: 6, xp: 10 },
            { id: "ry6-nis-l3-t15", type: "numeric", prompt: "3 fəhlə evi 8 gündə tikir. 4 fəhlə neçə gündə tikər? (tərs, hasil=24)", answer: 6, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-nis-l3-b1", type: "numeric", prompt: "5 işçi işi 12 gündə görür. 10 işçi neçə gündə görər?", answer: 6, xp: 15 },
            { id: "ry6-nis-l3-b2", type: "numeric", prompt: "4 kq şəkər 10 ₼-dirsə, 10 kq neçə ₼-dir?", answer: 25, xp: 15 },
            { id: "ry6-nis-l3-b3", type: "numeric", prompt: "2 nasos hovuzu 9 saatda doldurur. 3 nasos neçə saatda? (hasil=18)", answer: 6, xp: 15 },
            { id: "ry6-nis-l3-b4", type: "numeric", prompt: "8 dəftər 24 ₼-dirsə, 5 dəftər neçə ₼-dir?", answer: 15, xp: 15 },
            { id: "ry6-nis-l3-b5", type: "multiple_choice", prompt: "Alınan malın miqdarı və qiyməti (sabit vahid qiymətdə)?", options: ["düz mütənasib", "tərs mütənasib", "əlaqəsiz", "sabit"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry6-nis-l4",
          title: "Miqyas",
          intro: "Xəritə və planlarda miqyas anlayışı və məsafə hesablamaları.",
          sections: [
            { heading: "Miqyas nədir?", body: "Xəritədəki uzunluğun həqiqi uzunluğa nisbətinə miqyas deyilir: 1 : 100 000 (xəritədə 1 sm = həqiqətdə 100 000 sm = 1 km)." },
            { heading: "Həqiqi məsafə", body: "Xəritə uzunluğunu miqyasa vururuq. Miqyas 1 : 100 000, xəritədə 3 sm → həqiqi 300 000 sm = 3 km." },
            { heading: "Xəritə uzunluğu", body: "Həqiqi məsafəni miqyasa bölürük. 5 km = 500 000 sm, miqyas 1:100 000 → xəritədə 5 sm." },
          ],
          tasks: [
            { id: "ry6-nis-l4-t1", type: "multiple_choice", prompt: "Miqyas nədir?", options: ["xəritə uzunluğunun həqiqi uzunluğa nisbəti", "cəm", "fərq", "sürət"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l4-t2", type: "multiple_choice", prompt: "1 : 100 000 miqyasında xəritədə 1 sm həqiqətdə neçə sm-dir?", options: ["100 000", "1 000", "100", "10 000"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l4-t3", type: "numeric", prompt: "100 000 sm neçə km-dir?", answer: 1, xp: 10 },
            { id: "ry6-nis-l4-t4", type: "numeric", prompt: "Miqyas 1:100 000. Xəritədə 3 sm həqiqətdə neçə km-dir?", answer: 3, xp: 10 },
            { id: "ry6-nis-l4-t5", type: "numeric", prompt: "Miqyas 1:100 000. Xəritədə 5 sm həqiqətdə neçə km-dir?", answer: 5, xp: 10 },
            { id: "ry6-nis-l4-t6", type: "numeric", prompt: "1 km neçə sm-dir?", answer: 100000, xp: 10 },
            { id: "ry6-nis-l4-t7", type: "numeric", prompt: "Miqyas 1:100 000. Həqiqi 4 km xəritədə neçə sm-dir?", answer: 4, xp: 10 },
            { id: "ry6-nis-l4-t8", type: "numeric", prompt: "Miqyas 1:1 000. Xəritədə 2 sm həqiqətdə neçə sm-dir?", answer: 2000, xp: 10 },
            { id: "ry6-nis-l4-t9", type: "numeric", prompt: "Miqyas 1:100 000. Xəritədə 10 sm həqiqətdə neçə km-dir?", answer: 10, xp: 10 },
            { id: "ry6-nis-l4-t10", type: "multiple_choice", prompt: "1:200 000 miqyası 1:100 000-dən nə deməkdir?", options: ["daha kiçik (uzaq görünüş)", "daha böyük", "eyni", "əlaqəsiz"], correctIndex: 0, xp: 10 },
            { id: "ry6-nis-l4-t11", type: "numeric", prompt: "Miqyas 1:50 000. Xəritədə 2 sm həqiqətdə neçə sm-dir?", answer: 100000, xp: 10 },
            { id: "ry6-nis-l4-t12", type: "numeric", prompt: "Miqyas 1:100 000. Həqiqi 7 km xəritədə neçə sm-dir?", answer: 7, xp: 10 },
            { id: "ry6-nis-l4-t13", type: "numeric", prompt: "300 000 sm neçə km-dir?", answer: 3, xp: 10 },
            { id: "ry6-nis-l4-t14", type: "numeric", prompt: "Miqyas 1:100 000. Xəritədə 6 sm həqiqətdə neçə km-dir?", answer: 6, xp: 10 },
            { id: "ry6-nis-l4-t15", type: "numeric", prompt: "Miqyas 1:100 000. Həqiqi 12 km xəritədə neçə sm-dir?", answer: 12, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-nis-l4-b1", type: "numeric", prompt: "Miqyas 1:200 000. Xəritədə 3 sm həqiqətdə neçə km-dir?", answer: 6, xp: 15 },
            { id: "ry6-nis-l4-b2", type: "numeric", prompt: "Miqyas 1:100 000. Həqiqi 25 km xəritədə neçə sm-dir?", answer: 25, xp: 15 },
            { id: "ry6-nis-l4-b3", type: "numeric", prompt: "Miqyas 1:500 000. Xəritədə 2 sm həqiqətdə neçə km-dir?", answer: 10, xp: 15 },
            { id: "ry6-nis-l4-b4", type: "numeric", prompt: "5 km neçə sm-dir?", answer: 500000, xp: 15 },
            { id: "ry6-nis-l4-b5", type: "numeric", prompt: "Miqyas 1:100 000. Xəritədə 0,5 sm həqiqətdə neçə km-dir?", answer: 0.5, tolerance: 0.01, xp: 15 },
          ],
        },
      ],
    },

    // ═══════════════ 5. Faiz ═══════════════
    {
      id: "ry6-faiz",
      title: "Faiz",
      description:
        "Faiz anlayışı, ədədin faizini tapma, faizinə görə ədədi tapma, faiz məsələləri (endirim, artım).",
      lessons: [
        {
          id: "ry6-fai-l1",
          title: "Faiz anlayışı",
          intro: "Faizin mənasını başa düşmək və faizi kəsr/onluqla əlaqələndirmək.",
          sections: [
            { heading: "Faiz nədir?", body: "Bütövün yüzdə bir hissəsinə faiz deyilir və % işarəsi ilə göstərilir: 1% = 1/100 = 0,01. 100% bütöv deməkdir." },
            { heading: "Faiz ↔ kəsr", body: "50% = 50/100 = 1/2. 25% = 1/4. 20% = 1/5. 10% = 1/10." },
            { heading: "Faiz ↔ onluq", body: "Faizi 100-ə bölürük: 30% = 0,3. Onluğu faizə: 100-ə vururuq: 0,45 = 45%." },
          ],
          tasks: [
            { id: "ry6-fai-l1-t1", type: "multiple_choice", prompt: "1% neçəyə bərabərdir?", options: ["1/100", "1/10", "1/2", "1"], correctIndex: 0, xp: 10 },
            { id: "ry6-fai-l1-t2", type: "multiple_choice", prompt: "100% nə deməkdir?", options: ["bütöv", "yarısı", "heç nə", "iki dəfə"], correctIndex: 0, xp: 10 },
            { id: "ry6-fai-l1-t3", type: "fill_blank", prompt: "50% adi kəsr kimi (ən sadə)?", accepted: ["1/2"], xp: 10 },
            { id: "ry6-fai-l1-t4", type: "fill_blank", prompt: "25% adi kəsr kimi?", accepted: ["1/4"], xp: 10 },
            { id: "ry6-fai-l1-t5", type: "fill_blank", prompt: "20% adi kəsr kimi?", accepted: ["1/5"], xp: 10 },
            { id: "ry6-fai-l1-t6", type: "numeric", prompt: "30% onluq kəsr kimi neçədir?", answer: 0.3, tolerance: 0.001, xp: 10 },
            { id: "ry6-fai-l1-t7", type: "numeric", prompt: "0,45 neçə faizdir? (%-siz ədəd yaz)", answer: 45, xp: 10 },
            { id: "ry6-fai-l1-t8", type: "fill_blank", prompt: "10% adi kəsr kimi?", accepted: ["1/10"], xp: 10 },
            { id: "ry6-fai-l1-t9", type: "numeric", prompt: "75% onluq kimi neçədir?", answer: 0.75, tolerance: 0.001, xp: 10 },
            { id: "ry6-fai-l1-t10", type: "numeric", prompt: "0,5 neçə faizdir?", answer: 50, xp: 10 },
            { id: "ry6-fai-l1-t11", type: "multiple_choice", prompt: "1/4 neçə faizdir?", options: ["25%", "40%", "14%", "75%"], correctIndex: 0, xp: 10 },
            { id: "ry6-fai-l1-t12", type: "numeric", prompt: "100% onluq kimi neçədir?", answer: 1, tolerance: 0.001, xp: 10 },
            { id: "ry6-fai-l1-t13", type: "numeric", prompt: "1 neçə faizdir?", answer: 100, xp: 10 },
            { id: "ry6-fai-l1-t14", type: "multiple_choice", prompt: "1/2 neçə faizdir?", options: ["50%", "25%", "12%", "20%"], correctIndex: 0, xp: 10 },
            { id: "ry6-fai-l1-t15", type: "numeric", prompt: "5% onluq kimi neçədir?", answer: 0.05, tolerance: 0.001, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-fai-l1-b1", type: "numeric", prompt: "0,08 neçə faizdir?", answer: 8, xp: 15 },
            { id: "ry6-fai-l1-b2", type: "fill_blank", prompt: "40% adi kəsr kimi (ən sadə)?", accepted: ["2/5"], xp: 15 },
            { id: "ry6-fai-l1-b3", type: "numeric", prompt: "125% onluq kimi neçədir?", answer: 1.25, tolerance: 0.001, xp: 15 },
            { id: "ry6-fai-l1-b4", type: "multiple_choice", prompt: "3/4 neçə faizdir?", options: ["75%", "34%", "50%", "60%"], correctIndex: 0, xp: 15 },
            { id: "ry6-fai-l1-b5", type: "numeric", prompt: "1,5 neçə faizdir?", answer: 150, xp: 15 },
          ],
        },
        {
          id: "ry6-fai-l2",
          title: "Ədədin faizini tapma",
          intro: "Verilmiş ədədin müəyyən faizini hesablamaq.",
          sections: [
            { heading: "Qayda", body: "Ədədin faizini tapmaq üçün faizi onluğa çevirib ədədə vururuq: 200-ün 10%-i = 200 · 0,1 = 20." },
            { heading: "Asan yollar", body: "10% = ədədin 1/10-u (bir rəqəm sağa). 50% = yarısı. 25% = dörddə biri. 100-ün 20%-i = 20." },
          ],
          tasks: [
            { id: "ry6-fai-l2-t1", type: "numeric", prompt: "200-ün 10%-i neçədir?", answer: 20, xp: 10 },
            { id: "ry6-fai-l2-t2", type: "numeric", prompt: "100-ün 25%-i neçədir?", answer: 25, xp: 10 },
            { id: "ry6-fai-l2-t3", type: "numeric", prompt: "80-in 50%-i neçədir?", answer: 40, xp: 10 },
            { id: "ry6-fai-l2-t4", type: "numeric", prompt: "50-nin 20%-i neçədir?", answer: 10, xp: 10 },
            { id: "ry6-fai-l2-t5", type: "numeric", prompt: "300-ün 10%-i neçədir?", answer: 30, xp: 10 },
            { id: "ry6-fai-l2-t6", type: "numeric", prompt: "40-ın 25%-i neçədir?", answer: 10, xp: 10 },
            { id: "ry6-fai-l2-t7", type: "numeric", prompt: "60-ın 50%-i neçədir?", answer: 30, xp: 10 },
            { id: "ry6-fai-l2-t8", type: "numeric", prompt: "500-ün 30%-i neçədir?", answer: 150, xp: 10 },
            { id: "ry6-fai-l2-t9", type: "numeric", prompt: "20-nin 100%-i neçədir?", answer: 20, xp: 10 },
            { id: "ry6-fai-l2-t10", type: "numeric", prompt: "150-nin 10%-i neçədir?", answer: 15, xp: 10 },
            { id: "ry6-fai-l2-t11", type: "numeric", prompt: "1000-in 5%-i neçədir?", answer: 50, xp: 10 },
            { id: "ry6-fai-l2-t12", type: "numeric", prompt: "90-ın 20%-i neçədir?", answer: 18, xp: 10 },
            { id: "ry6-fai-l2-t13", type: "numeric", prompt: "250-nin 40%-i neçədir?", answer: 100, xp: 10 },
            { id: "ry6-fai-l2-t14", type: "numeric", prompt: "70-in 10%-i neçədir?", answer: 7, xp: 10 },
            { id: "ry6-fai-l2-t15", type: "numeric", prompt: "120-nin 75%-i neçədir?", answer: 90, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-fai-l2-b1", type: "numeric", prompt: "800-ün 15%-i neçədir?", answer: 120, xp: 15 },
            { id: "ry6-fai-l2-b2", type: "numeric", prompt: "60-ın 5%-i neçədir?", answer: 3, xp: 15 },
            { id: "ry6-fai-l2-b3", type: "numeric", prompt: "40-ın 150%-i neçədir?", answer: 60, xp: 15 },
            { id: "ry6-fai-l2-b4", type: "numeric", prompt: "1200-ün 12%-i neçədir?", answer: 144, xp: 15 },
            { id: "ry6-fai-l2-b5", type: "numeric", prompt: "25-in 8%-i neçədir?", answer: 2, xp: 15 },
          ],
        },
        {
          id: "ry6-fai-l3",
          title: "Faizinə görə ədədi tapma",
          intro: "Ədədin faizi məlum olduqda ədədin özünü tapmaq.",
          sections: [
            { heading: "Qayda", body: "Ədədin 20%-i 40-dırsa, ədəd nədir? 40-ı faizin onluğuna bölürük: 40 ÷ 0,2 = 200. Yəni 100%-i tapırıq." },
            { heading: "Fikirləşmə", body: "10% = 5-dirsə, 100% = 50 (10 dəfə çox). 1% tapıb 100-ə vurmaq da olar." },
          ],
          tasks: [
            { id: "ry6-fai-l3-t1", type: "numeric", prompt: "Ədədin 10%-i 5-dir. Ədəd neçədir?", answer: 50, xp: 10 },
            { id: "ry6-fai-l3-t2", type: "numeric", prompt: "Ədədin 20%-i 40-dır. Ədəd neçədir?", answer: 200, xp: 10 },
            { id: "ry6-fai-l3-t3", type: "numeric", prompt: "Ədədin 50%-i 30-dur. Ədəd neçədir?", answer: 60, xp: 10 },
            { id: "ry6-fai-l3-t4", type: "numeric", prompt: "Ədədin 25%-i 10-dur. Ədəd neçədir?", answer: 40, xp: 10 },
            { id: "ry6-fai-l3-t5", type: "numeric", prompt: "Ədədin 100%-i 75-dir. Ədəd neçədir?", answer: 75, xp: 10 },
            { id: "ry6-fai-l3-t6", type: "numeric", prompt: "Ədədin 10%-i 12-dir. Ədəd neçədir?", answer: 120, xp: 10 },
            { id: "ry6-fai-l3-t7", type: "numeric", prompt: "Ədədin 50%-i 8-dir. Ədəd neçədir?", answer: 16, xp: 10 },
            { id: "ry6-fai-l3-t8", type: "numeric", prompt: "Ədədin 20%-i 15-dir. Ədəd neçədir?", answer: 75, xp: 10 },
            { id: "ry6-fai-l3-t9", type: "numeric", prompt: "Ədədin 5%-i 4-dür. Ədəd neçədir?", answer: 80, xp: 10 },
            { id: "ry6-fai-l3-t10", type: "numeric", prompt: "Ədədin 25%-i 25-dir. Ədəd neçədir?", answer: 100, xp: 10 },
            { id: "ry6-fai-l3-t11", type: "numeric", prompt: "Ədədin 10%-i 9-dur. Ədəd neçədir?", answer: 90, xp: 10 },
            { id: "ry6-fai-l3-t12", type: "numeric", prompt: "Ədədin 40%-i 20-dir. Ədəd neçədir?", answer: 50, xp: 10 },
            { id: "ry6-fai-l3-t13", type: "numeric", prompt: "Ədədin 75%-i 30-dur. Ədəd neçədir?", answer: 40, xp: 10 },
            { id: "ry6-fai-l3-t14", type: "numeric", prompt: "Ədədin 50%-i 50-dir. Ədəd neçədir?", answer: 100, xp: 10 },
            { id: "ry6-fai-l3-t15", type: "numeric", prompt: "Ədədin 30%-i 60-dır. Ədəd neçədir?", answer: 200, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-fai-l3-b1", type: "numeric", prompt: "Ədədin 15%-i 30-dur. Ədəd neçədir?", answer: 200, xp: 15 },
            { id: "ry6-fai-l3-b2", type: "numeric", prompt: "Ədədin 8%-i 16-dır. Ədəd neçədir?", answer: 200, xp: 15 },
            { id: "ry6-fai-l3-b3", type: "numeric", prompt: "Ədədin 2%-i 6-dır. Ədəd neçədir?", answer: 300, xp: 15 },
            { id: "ry6-fai-l3-b4", type: "numeric", prompt: "Ədədin 125%-i 250-dir. Ədəd neçədir?", answer: 200, xp: 15 },
            { id: "ry6-fai-l3-b5", type: "numeric", prompt: "Ədədin 12%-i 24-dür. Ədəd neçədir?", answer: 200, xp: 15 },
          ],
        },
        {
          id: "ry6-fai-l4",
          title: "Faiz məsələləri (endirim və artım)",
          intro: "Real həyat faiz məsələləri: endirim, artım, faizlə hesablama.",
          sections: [
            { heading: "Endirim", body: "100 ₼-lıq mal 20% endirimlə: endirim 100·0,2 = 20 ₼, yeni qiymət 100 − 20 = 80 ₼." },
            { heading: "Artım", body: "200 ₼ maaş 10% artırsa: artım 200·0,1 = 20 ₼, yeni maaş 220 ₼." },
            { heading: "Neçə faiz?", body: "50-dən 60-a artım: fərq 10, nisbət 10/50 = 0,2 = 20% artım." },
          ],
          tasks: [
            { id: "ry6-fai-l4-t1", type: "numeric", prompt: "100 ₼-lıq malın 20% endirimi neçə ₼-dir?", answer: 20, xp: 10 },
            { id: "ry6-fai-l4-t2", type: "numeric", prompt: "100 ₼-lıq mal 20% endirimlə neçə ₼ olur?", answer: 80, xp: 10 },
            { id: "ry6-fai-l4-t3", type: "numeric", prompt: "200 ₼ maaş 10% artsa, artım neçə ₼-dir?", answer: 20, xp: 10 },
            { id: "ry6-fai-l4-t4", type: "numeric", prompt: "200 ₼ maaş 10% artsa, yeni maaş neçə ₼-dir?", answer: 220, xp: 10 },
            { id: "ry6-fai-l4-t5", type: "numeric", prompt: "50 ₼-lıq mal 10% endirimlə neçə ₼ olur?", answer: 45, xp: 10 },
            { id: "ry6-fai-l4-t6", type: "numeric", prompt: "80 ₼-lıq malın 25% endirimi neçə ₼-dir?", answer: 20, xp: 10 },
            { id: "ry6-fai-l4-t7", type: "numeric", prompt: "80 ₼-lıq mal 25% endirimlə neçə ₼ olur?", answer: 60, xp: 10 },
            { id: "ry6-fai-l4-t8", type: "numeric", prompt: "50-dən 60-a artım neçə faizdir?", answer: 20, xp: 10 },
            { id: "ry6-fai-l4-t9", type: "numeric", prompt: "40 nəfərdən 10%-i gəlmədi. Neçə nəfər gəlmədi?", answer: 4, xp: 10 },
            { id: "ry6-fai-l4-t10", type: "numeric", prompt: "150 ₼-lıq mal 20% endirimlə neçə ₼ olur?", answer: 120, xp: 10 },
            { id: "ry6-fai-l4-t11", type: "numeric", prompt: "500 ₼ 10% artsa neçə ₼ olur?", answer: 550, xp: 10 },
            { id: "ry6-fai-l4-t12", type: "numeric", prompt: "200 ₼-lıq malın 50% endirimi neçə ₼-dir?", answer: 100, xp: 10 },
            { id: "ry6-fai-l4-t13", type: "numeric", prompt: "20-dən 25-ə artım neçə faizdir?", answer: 25, xp: 10 },
            { id: "ry6-fai-l4-t14", type: "numeric", prompt: "60 ₼-lıq mal 10% endirimlə neçə ₼ olur?", answer: 54, xp: 10 },
            { id: "ry6-fai-l4-t15", type: "numeric", prompt: "300 ₼-lıq mal 30% endirimlə neçə ₼ olur?", answer: 210, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry6-fai-l4-b1", type: "numeric", prompt: "Sinifdə 25 şagirddən 20%-i əla oxuyur. Neçə nəfər?", answer: 5, xp: 15 },
            { id: "ry6-fai-l4-b2", type: "numeric", prompt: "1000 ₼-lıq mal əvvəl 10%, sonra qalanın 10% endirimlə neçə ₼ olur?", answer: 810, xp: 15 },
            { id: "ry6-fai-l4-b3", type: "numeric", prompt: "40-dan 30-a azalma neçə faizdir?", answer: 25, xp: 15 },
            { id: "ry6-fai-l4-b4", type: "numeric", prompt: "250 ₼ maaş 20% artsa neçə ₼ olur?", answer: 300, xp: 15 },
            { id: "ry6-fai-l4-b5", type: "numeric", prompt: "120 ₼-lıq malın 15% endirimindən sonra qiyməti neçə ₼-dir?", answer: 102, xp: 15 },
          ],
        },
      ],
    },
  ],
};
