// Riyaziyyat — 7-ci sinif proqramı (Azərbaycan kurikuluma uyğun: Cəbr + Həndəsə).
// Bölmələr: 1) Rasional ədədlər üzərində əməllər  2) Cəbri ifadələr
// 3) Birdəyişənli tənliklər  4) Tək və çoxhədlilər  5) Müxtəsər vurma düsturları
// 6) Qüvvət  7) Funksiya və koordinat  8) Həndəsə.
// Hər dərs: 15 əsas + 5 bonus tapşırıq. Mərhələli doldurulur.
// id prefiksi ry7-* → aşağı siniflərin progress-i ilə toqquşmur.

import type { Subject } from "../types";

export const math7: Subject = {
  slug: "riyaziyyat-7",
  name: "Riyaziyyat",
  grade: 7,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Rasional ədədlər üzərində əməllər ═══════════════
    {
      id: "ry7-rasional",
      title: "Rasional ədədlər üzərində əməllər",
      description:
        "Müsbət və mənfi ədədlərin toplanması, çıxılması, vurulması və bölünməsi; işarə qaydaları, modul və qarışıq əməllər.",
      lessons: [
        {
          id: "ry7-ras-l1",
          title: "Rasional ədədlərin toplanması",
          intro: "Müsbət və mənfi ədədləri işarə qaydalarına görə toplamaq.",
          sections: [
            { heading: "Eyni işarəli ədədlər", body: "İşarələri eyni olan iki ədədi toplayarkən modullarını toplayır, ümumi işarəni saxlayırıq. Məsələn: (−3) + (−5) = −8." },
            { heading: "Müxtəlif işarəli ədədlər", body: "İşarələri fərqli olduqda modulu böyük olandan kiçiyi çıxırıq, nəticəyə böyük modullu ədədin işarəsini veririk. Məsələn: (−7) + 4 = −3, çünki 7 − 4 = 3 və böyük modul mənfidir." },
            { heading: "Əks ədədlər", body: "Bir ədədlə onun əks ədədinin cəmi 0-dır: 6 + (−6) = 0." },
          ],
          tasks: [
            { id: "ry7-ras-l1-t1", type: "numeric", prompt: "(−3) + (−5) = ?", answer: -8, xp: 10 },
            { id: "ry7-ras-l1-t2", type: "numeric", prompt: "(−7) + 4 = ?", answer: -3, xp: 10 },
            { id: "ry7-ras-l1-t3", type: "numeric", prompt: "9 + (−12) = ?", answer: -3, xp: 10 },
            { id: "ry7-ras-l1-t4", type: "numeric", prompt: "(−6) + 6 = ?", answer: 0, xp: 10 },
            { id: "ry7-ras-l1-t5", type: "numeric", prompt: "(−8) + (−2) = ?", answer: -10, xp: 10 },
            { id: "ry7-ras-l1-t6", type: "numeric", prompt: "15 + (−7) = ?", answer: 8, xp: 10 },
            { id: "ry7-ras-l1-t7", type: "numeric", prompt: "(−10) + 3 = ?", answer: -7, xp: 10 },
            { id: "ry7-ras-l1-t8", type: "numeric", prompt: "(−4) + (−4) = ?", answer: -8, xp: 10 },
            { id: "ry7-ras-l1-t9", type: "numeric", prompt: "20 + (−25) = ?", answer: -5, xp: 10 },
            { id: "ry7-ras-l1-t10", type: "numeric", prompt: "(−13) + 13 = ?", answer: 0, xp: 10 },
            { id: "ry7-ras-l1-t11", type: "multiple_choice", prompt: "(−9) + (−1) neçədir?", options: ["−10", "−8", "8", "10"], correctIndex: 0, xp: 10 },
            { id: "ry7-ras-l1-t12", type: "multiple_choice", prompt: "Müxtəlif işarəli ədədləri toplayarkən nəticə hansı işarəni alır?", options: ["modulu böyük olanın işarəsini", "həmişə müsbət", "həmişə mənfi", "modulu kiçik olanın işarəsini"], correctIndex: 0, xp: 10 },
            { id: "ry7-ras-l1-t13", type: "numeric", prompt: "(−2) + (−3) + (−5) = ?", answer: -10, xp: 10 },
            { id: "ry7-ras-l1-t14", type: "numeric", prompt: "(−7) + 10 + (−1) = ?", answer: 2, xp: 10 },
            { id: "ry7-ras-l1-t15", type: "numeric", prompt: "0 + (−14) = ?", answer: -14, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-ras-l1-b1", type: "numeric", prompt: "(−1.5) + (−2.5) = ?", answer: -4, xp: 15 },
            { id: "ry7-ras-l1-b2", type: "numeric", prompt: "(−100) + 60 = ?", answer: -40, xp: 15 },
            { id: "ry7-ras-l1-b3", type: "numeric", prompt: "(−8) + (−7) + 15 = ?", answer: 0, xp: 15 },
            { id: "ry7-ras-l1-b4", type: "multiple_choice", prompt: "6 ədədinin əks ədədi hansıdır?", options: ["−6", "6", "0", "1/6"], correctIndex: 0, xp: 15 },
            { id: "ry7-ras-l1-b5", type: "numeric", prompt: "(−3.2) + 3.2 = ?", answer: 0, xp: 15 },
          ],
        },
        {
          id: "ry7-ras-l2",
          title: "Rasional ədədlərin çıxılması",
          intro: "Çıxmanı əks ədədin toplanmasına çevirmək: a − b = a + (−b).",
          sections: [
            { heading: "Çıxma qaydası", body: "Bir ədəddən digərini çıxmaq üçün çıxılanın əks ədədini gələnə toplayırıq: a − b = a + (−b). Məsələn: 5 − 8 = 5 + (−8) = −3." },
            { heading: "Mənfi ədədin çıxılması", body: "Mənfi ədədi çıxmaq onu toplamaq deməkdir: 4 − (−3) = 4 + 3 = 7. İki mənfi yan-yana gələndə (− −) plus olur." },
          ],
          tasks: [
            { id: "ry7-ras-l2-t1", type: "numeric", prompt: "5 − 8 = ?", answer: -3, xp: 10 },
            { id: "ry7-ras-l2-t2", type: "numeric", prompt: "4 − (−3) = ?", answer: 7, xp: 10 },
            { id: "ry7-ras-l2-t3", type: "numeric", prompt: "(−6) − 2 = ?", answer: -8, xp: 10 },
            { id: "ry7-ras-l2-t4", type: "numeric", prompt: "(−5) − (−9) = ?", answer: 4, xp: 10 },
            { id: "ry7-ras-l2-t5", type: "numeric", prompt: "10 − 15 = ?", answer: -5, xp: 10 },
            { id: "ry7-ras-l2-t6", type: "numeric", prompt: "0 − 7 = ?", answer: -7, xp: 10 },
            { id: "ry7-ras-l2-t7", type: "numeric", prompt: "(−3) − (−3) = ?", answer: 0, xp: 10 },
            { id: "ry7-ras-l2-t8", type: "numeric", prompt: "12 − (−8) = ?", answer: 20, xp: 10 },
            { id: "ry7-ras-l2-t9", type: "numeric", prompt: "(−10) − 5 = ?", answer: -15, xp: 10 },
            { id: "ry7-ras-l2-t10", type: "numeric", prompt: "7 − 7 = ?", answer: 0, xp: 10 },
            { id: "ry7-ras-l2-t11", type: "multiple_choice", prompt: "a − b ifadəsi hansına bərabərdir?", options: ["a + (−b)", "a + b", "(−a) + b", "b − a"], correctIndex: 0, xp: 10 },
            { id: "ry7-ras-l2-t12", type: "numeric", prompt: "(−2) − (−10) = ?", answer: 8, xp: 10 },
            { id: "ry7-ras-l2-t13", type: "numeric", prompt: "(−15) − (−5) = ?", answer: -10, xp: 10 },
            { id: "ry7-ras-l2-t14", type: "numeric", prompt: "3 − 9 − 2 = ?", answer: -8, xp: 10 },
            { id: "ry7-ras-l2-t15", type: "numeric", prompt: "(−4) − 6 + 2 = ?", answer: -8, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-ras-l2-b1", type: "numeric", prompt: "(−2.5) − 1.5 = ?", answer: -4, xp: 15 },
            { id: "ry7-ras-l2-b2", type: "numeric", prompt: "100 − (−50) = ?", answer: 150, xp: 15 },
            { id: "ry7-ras-l2-b3", type: "numeric", prompt: "(−7) − (−7) − 7 = ?", answer: -7, xp: 15 },
            { id: "ry7-ras-l2-b4", type: "numeric", prompt: "0 − (−9) = ?", answer: 9, xp: 15 },
            { id: "ry7-ras-l2-b5", type: "numeric", prompt: "(−1) − (−2) − (−3) = ?", answer: 4, xp: 15 },
          ],
        },
        {
          id: "ry7-ras-l3",
          title: "Rasional ədədlərin vurulması və bölünməsi",
          intro: "İşarə qaydası: eyni işarə → müsbət, müxtəlif işarə → mənfi.",
          sections: [
            { heading: "Vurma işarə qaydası", body: "(+)·(+) = +, (−)·(−) = +, (+)·(−) = −, (−)·(+) = −. Yəni eyni işarəli iki ədədin hasili müsbət, müxtəlif işarəli iki ədədin hasili mənfidir." },
            { heading: "Bölmə", body: "Bölmədə də eyni işarə qaydası işləyir: (−12) : (−4) = 3, (−12) : 4 = −3." },
            { heading: "Sıfırla vurma", body: "İstənilən ədədi 0-a vurduqda nəticə 0 olur." },
          ],
          tasks: [
            { id: "ry7-ras-l3-t1", type: "numeric", prompt: "(−3) · (−4) = ?", answer: 12, xp: 10 },
            { id: "ry7-ras-l3-t2", type: "numeric", prompt: "(−5) · 6 = ?", answer: -30, xp: 10 },
            { id: "ry7-ras-l3-t3", type: "numeric", prompt: "7 · (−2) = ?", answer: -14, xp: 10 },
            { id: "ry7-ras-l3-t4", type: "numeric", prompt: "(−8) · (−2) = ?", answer: 16, xp: 10 },
            { id: "ry7-ras-l3-t5", type: "numeric", prompt: "(−12) : (−4) = ?", answer: 3, xp: 10 },
            { id: "ry7-ras-l3-t6", type: "numeric", prompt: "(−20) : 5 = ?", answer: -4, xp: 10 },
            { id: "ry7-ras-l3-t7", type: "numeric", prompt: "18 : (−6) = ?", answer: -3, xp: 10 },
            { id: "ry7-ras-l3-t8", type: "numeric", prompt: "(−9) · 0 = ?", answer: 0, xp: 10 },
            { id: "ry7-ras-l3-t9", type: "multiple_choice", prompt: "(−)·(−) hasilinin işarəsi necədir?", options: ["müsbət", "mənfi", "sıfır", "dəyişmir"], correctIndex: 0, xp: 10 },
            { id: "ry7-ras-l3-t10", type: "multiple_choice", prompt: "Müxtəlif işarəli iki ədədin hasili hansı işarəlidir?", options: ["mənfi", "müsbət", "sıfır", "həmişə 1"], correctIndex: 0, xp: 10 },
            { id: "ry7-ras-l3-t11", type: "numeric", prompt: "(−2) · (−3) · (−1) = ?", answer: -6, xp: 10 },
            { id: "ry7-ras-l3-t12", type: "numeric", prompt: "(−4) · 5 · (−1) = ?", answer: 20, xp: 10 },
            { id: "ry7-ras-l3-t13", type: "numeric", prompt: "(−36) : (−9) = ?", answer: 4, xp: 10 },
            { id: "ry7-ras-l3-t14", type: "numeric", prompt: "(−100) : 25 = ?", answer: -4, xp: 10 },
            { id: "ry7-ras-l3-t15", type: "numeric", prompt: "(−6) · (−6) = ?", answer: 36, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-ras-l3-b1", type: "numeric", prompt: "(−0.5) · 8 = ?", answer: -4, xp: 15 },
            { id: "ry7-ras-l3-b2", type: "numeric", prompt: "(−2) · (−2) · (−2) = ?", answer: -8, xp: 15 },
            { id: "ry7-ras-l3-b3", type: "multiple_choice", prompt: "Mənfi ədədlərin sayı tək olduqda hasilin işarəsi necə olur?", options: ["mənfi", "müsbət", "sıfır", "dəyişmir"], correctIndex: 0, xp: 15 },
            { id: "ry7-ras-l3-b4", type: "numeric", prompt: "(−1) · (−1) · (−1) · (−1) = ?", answer: 1, xp: 15 },
            { id: "ry7-ras-l3-b5", type: "numeric", prompt: "(−48) : (−6) : (−2) = ?", answer: -4, xp: 15 },
          ],
        },
        {
          id: "ry7-ras-l4",
          title: "Modul və qarışıq əməllər",
          intro: "Ədədin modulu (mütləq qiyməti) və əməllərin sırası.",
          sections: [
            { heading: "Modul (mütləq qiymət)", body: "Ədədin modulu onun sıfırdan olan məsafəsidir və heç vaxt mənfi olmur: |−5| = 5, |7| = 7, |0| = 0." },
            { heading: "Əməllərin sırası", body: "Əvvəlcə mötərizə, sonra vurma/bölmə, sonra toplama/çıxma. İşarələrə diqqət et." },
          ],
          tasks: [
            { id: "ry7-ras-l4-t1", type: "numeric", prompt: "|−5| = ?", answer: 5, xp: 10 },
            { id: "ry7-ras-l4-t2", type: "numeric", prompt: "|7| = ?", answer: 7, xp: 10 },
            { id: "ry7-ras-l4-t3", type: "numeric", prompt: "|0| = ?", answer: 0, xp: 10 },
            { id: "ry7-ras-l4-t4", type: "numeric", prompt: "|−12| + |−3| = ?", answer: 15, xp: 10 },
            { id: "ry7-ras-l4-t5", type: "numeric", prompt: "|−10| − |6| = ?", answer: 4, xp: 10 },
            { id: "ry7-ras-l4-t6", type: "numeric", prompt: "2 + 3 · (−4) = ?", answer: -10, xp: 10 },
            { id: "ry7-ras-l4-t7", type: "numeric", prompt: "(2 + 3) · (−4) = ?", answer: -20, xp: 10 },
            { id: "ry7-ras-l4-t8", type: "numeric", prompt: "(−6) + 12 : (−3) = ?", answer: -10, xp: 10 },
            { id: "ry7-ras-l4-t9", type: "numeric", prompt: "10 − 2 · (−3) = ?", answer: 16, xp: 10 },
            { id: "ry7-ras-l4-t10", type: "multiple_choice", prompt: "|−8| ifadəsinin qiyməti hansıdır?", options: ["8", "−8", "0", "1/8"], correctIndex: 0, xp: 10 },
            { id: "ry7-ras-l4-t11", type: "numeric", prompt: "(−3) · (−2) + (−4) = ?", answer: 2, xp: 10 },
            { id: "ry7-ras-l4-t12", type: "numeric", prompt: "|−4| · |−3| = ?", answer: 12, xp: 10 },
            { id: "ry7-ras-l4-t13", type: "numeric", prompt: "(−20) : 4 + 3 = ?", answer: -2, xp: 10 },
            { id: "ry7-ras-l4-t14", type: "numeric", prompt: "5 · (−2) − (−4) = ?", answer: -6, xp: 10 },
            { id: "ry7-ras-l4-t15", type: "numeric", prompt: "(−1) · (3 − 8) = ?", answer: 5, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-ras-l4-b1", type: "numeric", prompt: "|−15| − |−15| = ?", answer: 0, xp: 15 },
            { id: "ry7-ras-l4-b2", type: "numeric", prompt: "(−2) · (−3) · (−1) + 6 = ?", answer: 0, xp: 15 },
            { id: "ry7-ras-l4-b3", type: "numeric", prompt: "|(−7) + 3| = ?", answer: 4, xp: 15 },
            { id: "ry7-ras-l4-b4", type: "numeric", prompt: "(−4)² = ?", answer: 16, xp: 15 },
            { id: "ry7-ras-l4-b5", type: "multiple_choice", prompt: "İstənilən ədədin modulu haqqında hansı doğrudur?", options: ["heç vaxt mənfi olmur", "həmişə müsbətdir", "həmişə tam ədəddir", "ədədin özünə bərabərdir"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 2. Cəbri ifadələr ═══════════════
    {
      id: "ry7-cebri",
      title: "Cəbri ifadələr",
      description:
        "Cəbri ifadənin qiyməti, oxşar hədlər, mötərizələrin açılması və ifadələrin sadələşdirilməsi.",
      lessons: [
        {
          id: "ry7-cebr-l1",
          title: "Cəbri ifadə və onun qiyməti",
          intro: "İfadədəki hərfin yerinə ədəd qoyub qiymətini hesablamaq.",
          sections: [
            { heading: "Cəbri ifadə nədir?", body: "Tərkibində hərf (dəyişən) olan ifadəyə cəbri ifadə deyilir: 2x + 3, a − b, 5n. Hərfin yerinə ədəd qoyduqda ifadənin qiymətini taparıq." },
            { heading: "Qiymətin tapılması", body: "x = 4 olduqda 2x + 3 = 2·4 + 3 = 11. Əvvəlcə vurma, sonra toplama edilir." },
          ],
          tasks: [
            { id: "ry7-cebr-l1-t1", type: "numeric", prompt: "x = 4 olduqda 2x + 3 ifadəsinin qiyməti nədir?", answer: 11, xp: 10 },
            { id: "ry7-cebr-l1-t2", type: "numeric", prompt: "x = 5 olduqda 3x − 2 = ?", answer: 13, xp: 10 },
            { id: "ry7-cebr-l1-t3", type: "numeric", prompt: "a = 6 olduqda a + 7 = ?", answer: 13, xp: 10 },
            { id: "ry7-cebr-l1-t4", type: "numeric", prompt: "n = 3 olduqda 5n = ?", answer: 15, xp: 10 },
            { id: "ry7-cebr-l1-t5", type: "numeric", prompt: "x = 2 olduqda 4x + 1 = ?", answer: 9, xp: 10 },
            { id: "ry7-cebr-l1-t6", type: "numeric", prompt: "x = 10 olduqda x − 6 = ?", answer: 4, xp: 10 },
            { id: "ry7-cebr-l1-t7", type: "numeric", prompt: "x = 3, y = 2 olduqda x + y = ?", answer: 5, xp: 10 },
            { id: "ry7-cebr-l1-t8", type: "numeric", prompt: "x = 4, y = 5 olduqda xy = ?", answer: 20, xp: 10 },
            { id: "ry7-cebr-l1-t9", type: "numeric", prompt: "a = 7 olduqda 2a − 5 = ?", answer: 9, xp: 10 },
            { id: "ry7-cebr-l1-t10", type: "numeric", prompt: "x = −2 olduqda 3x = ?", answer: -6, xp: 10 },
            { id: "ry7-cebr-l1-t11", type: "numeric", prompt: "x = −1 olduqda x + 5 = ?", answer: 4, xp: 10 },
            { id: "ry7-cebr-l1-t12", type: "numeric", prompt: "x = 5 olduqda x² = ?", answer: 25, xp: 10 },
            { id: "ry7-cebr-l1-t13", type: "numeric", prompt: "a = 2, b = 3 olduqda 2a + 3b = ?", answer: 13, xp: 10 },
            { id: "ry7-cebr-l1-t14", type: "multiple_choice", prompt: "Aşağıdakılardan hansı cəbri ifadədir?", options: ["3x + 5", "7 + 2", "10", "4 · 6"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l1-t15", type: "numeric", prompt: "x = 6 olduqda (x − 2) : 2 = ?", answer: 2, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-cebr-l1-b1", type: "numeric", prompt: "x = −3 olduqda x² + 1 = ?", answer: 10, xp: 15 },
            { id: "ry7-cebr-l1-b2", type: "numeric", prompt: "a = 4, b = −2 olduqda a − b = ?", answer: 6, xp: 15 },
            { id: "ry7-cebr-l1-b3", type: "numeric", prompt: "x = 3 olduqda 2x² = ?", answer: 18, xp: 15 },
            { id: "ry7-cebr-l1-b4", type: "numeric", prompt: "x = 10, y = 4 olduqda (x + y) : 2 = ?", answer: 7, xp: 15 },
            { id: "ry7-cebr-l1-b5", type: "numeric", prompt: "x = −5 olduqda −x = ?", answer: 5, xp: 15 },
          ],
        },
        {
          id: "ry7-cebr-l2",
          title: "Oxşar hədlər və onların yığılması",
          intro: "Eyni hərf hissəsi olan hədləri (oxşar hədləri) birləşdirmək.",
          sections: [
            { heading: "Həd və əmsal", body: "3x ifadəsində 3 — əmsal, x — dəyişəndir. 3x, −5x, x hədlərinin hamısı x-lidir." },
            { heading: "Oxşar hədlər", body: "Hərf hissəsi eyni olan hədlərə oxşar hədlər deyilir: 3x və 5x oxşardır, 3x və 3y oxşar deyil. Oxşar hədləri əmsallarını toplayaraq yığırıq: 3x + 5x = 8x." },
          ],
          tasks: [
            { id: "ry7-cebr-l2-t1", type: "multiple_choice", prompt: "3x + 5x = ?", options: ["8x", "15x", "8x²", "8"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t2", type: "multiple_choice", prompt: "7a − 2a = ?", options: ["5a", "9a", "5", "14a"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t3", type: "multiple_choice", prompt: "Hansı hədlər oxşardır?", options: ["4x və 9x", "4x və 4y", "4x və 4x²", "4 və 4x"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t4", type: "multiple_choice", prompt: "2x + 3y + 4x = ?", options: ["6x + 3y", "9xy", "9x", "5x + 3y"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t5", type: "multiple_choice", prompt: "x + x + x = ?", options: ["3x", "x³", "x", "3"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t6", type: "multiple_choice", prompt: "10a − 10a = ?", options: ["0", "20a", "10a", "100a"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t7", type: "multiple_choice", prompt: "6x − x = ?", options: ["5x", "6", "6x", "0"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t8", type: "multiple_choice", prompt: "3a + 4b − a = ?", options: ["2a + 4b", "6ab", "7ab", "2ab"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t9", type: "fill_blank", prompt: "5x + 2x = ? (nəticəni yaz, məs. 7x)", accepted: ["7x"], xp: 10 },
            { id: "ry7-cebr-l2-t10", type: "fill_blank", prompt: "9y − 4y = ? (məs. 5y)", accepted: ["5y"], xp: 10 },
            { id: "ry7-cebr-l2-t11", type: "multiple_choice", prompt: "2x + 3 + 5x = ?", options: ["7x + 3", "10x", "7x³", "8x"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t12", type: "multiple_choice", prompt: "−3x + 8x = ?", options: ["5x", "−5x", "11x", "−11x"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t13", type: "multiple_choice", prompt: "4a + 2b + 3a + b = ?", options: ["7a + 3b", "10ab", "7ab", "6a + 3b"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t14", type: "multiple_choice", prompt: "3x ifadəsində əmsal hansıdır?", options: ["3", "x", "3x", "1"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l2-t15", type: "fill_blank", prompt: "x + 2x + 3x = ? (məs. 6x)", accepted: ["6x"], xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-cebr-l2-b1", type: "multiple_choice", prompt: "5x² + 3x² = ?", options: ["8x²", "8x⁴", "8x", "15x²"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l2-b2", type: "multiple_choice", prompt: "7ab − 3ab = ?", options: ["4ab", "4", "10ab", "4a²b²"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l2-b3", type: "multiple_choice", prompt: "2x + 3y − 2x = ?", options: ["3y", "3xy", "0", "5y"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l2-b4", type: "fill_blank", prompt: "10a − 3a − 2a = ? (məs. 5a)", accepted: ["5a"], xp: 15 },
            { id: "ry7-cebr-l2-b5", type: "multiple_choice", prompt: "−x − x = ?", options: ["−2x", "2x", "0", "−x²"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry7-cebr-l3",
          title: "Mötərizələrin açılması",
          intro: "Mötərizə önündəki işarə və əmsala görə mötərizəni açmaq (paylama qanunu).",
          sections: [
            { heading: "Paylama qanunu", body: "a(b + c) = ab + ac. Məsələn: 3(x + 2) = 3x + 6; 2(a − 4) = 2a − 8." },
            { heading: "Mötərizə önündə işarə", body: "+(x − 3) = x − 3 (dəyişmir). −(x − 3) = −x + 3 (bütün işarələr dəyişir)." },
          ],
          tasks: [
            { id: "ry7-cebr-l3-t1", type: "multiple_choice", prompt: "3(x + 2) = ?", options: ["3x + 6", "3x + 2", "x + 6", "3x + 5"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t2", type: "multiple_choice", prompt: "2(a − 4) = ?", options: ["2a − 8", "2a − 4", "2a + 8", "a − 8"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t3", type: "multiple_choice", prompt: "5(x + 1) = ?", options: ["5x + 5", "5x + 1", "x + 5", "6x"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t4", type: "multiple_choice", prompt: "−(x − 3) = ?", options: ["−x + 3", "−x − 3", "x − 3", "x + 3"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t5", type: "multiple_choice", prompt: "4(2x + 3) = ?", options: ["8x + 12", "8x + 3", "6x + 12", "8x + 7"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t6", type: "multiple_choice", prompt: "x(x + 5) = ?", options: ["x² + 5x", "x² + 5", "2x + 5", "x + 5x"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t7", type: "multiple_choice", prompt: "−2(a + 3) = ?", options: ["−2a − 6", "−2a + 6", "2a − 6", "−2a − 3"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t8", type: "multiple_choice", prompt: "+(2x − 5) = ?", options: ["2x − 5", "−2x + 5", "2x + 5", "−2x − 5"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t9", type: "multiple_choice", prompt: "6(x − 2) = ?", options: ["6x − 12", "6x − 2", "6x + 12", "x − 12"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t10", type: "multiple_choice", prompt: "3(2a − 1) = ?", options: ["6a − 3", "6a − 1", "5a − 3", "6a + 3"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t11", type: "multiple_choice", prompt: "a(b + c) düsturu necə açılır?", options: ["ab + ac", "a + b + c", "abc", "ab + c"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t12", type: "multiple_choice", prompt: "−(a + b) = ?", options: ["−a − b", "−a + b", "a − b", "a + b"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t13", type: "multiple_choice", prompt: "2(x + y) = ?", options: ["2x + 2y", "2x + y", "x + 2y", "2xy"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t14", type: "multiple_choice", prompt: "10(a − 1) = ?", options: ["10a − 10", "10a − 1", "10a + 10", "a − 10"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l3-t15", type: "multiple_choice", prompt: "−3(x − 2) = ?", options: ["−3x + 6", "−3x − 6", "3x − 6", "−3x + 2"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-cebr-l3-b1", type: "multiple_choice", prompt: "2x(x + 3) = ?", options: ["2x² + 6x", "2x² + 3", "2x + 6x", "2x² + 6"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l3-b2", type: "multiple_choice", prompt: "3(x + 2) + 2(x − 1) = ?", options: ["5x + 4", "5x + 8", "6x + 4", "5x + 5"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l3-b3", type: "multiple_choice", prompt: "−(2x − 3y + 1) = ?", options: ["−2x + 3y − 1", "−2x − 3y − 1", "2x − 3y + 1", "−2x + 3y + 1"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l3-b4", type: "multiple_choice", prompt: "5(2a + 3b) = ?", options: ["10a + 15b", "10a + 3b", "7a + 8b", "10ab + 15"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l3-b5", type: "multiple_choice", prompt: "−2(x − y + 4) = ?", options: ["−2x + 2y − 8", "−2x − 2y − 8", "−2x + 2y + 8", "2x − 2y + 8"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry7-cebr-l4",
          title: "İfadələrin sadələşdirilməsi",
          intro: "Mötərizələri açıb oxşar hədləri yığaraq ifadəni sadələşdirmək.",
          sections: [
            { heading: "Addımlar", body: "1) Mötərizələri aç. 2) Oxşar hədləri yığ. Məsələn: 2(x + 3) + x = 2x + 6 + x = 3x + 6." },
          ],
          tasks: [
            { id: "ry7-cebr-l4-t1", type: "multiple_choice", prompt: "2(x + 3) + x = ?", options: ["3x + 6", "3x + 3", "2x + 6", "3x + 9"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t2", type: "multiple_choice", prompt: "3x + 2(x + 1) = ?", options: ["5x + 2", "5x + 1", "6x + 2", "5x + 3"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t3", type: "multiple_choice", prompt: "4(a − 1) + 3 = ?", options: ["4a − 1", "4a + 2", "4a − 4", "4a + 3"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t4", type: "multiple_choice", prompt: "5x − (x + 2) = ?", options: ["4x − 2", "4x + 2", "6x − 2", "4x"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t5", type: "multiple_choice", prompt: "2(x + 1) + 3(x − 1) = ?", options: ["5x − 1", "5x + 1", "5x + 5", "6x − 1"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t6", type: "multiple_choice", prompt: "3a + 4 − a = ?", options: ["2a + 4", "3a + 4", "2a", "4a + 4"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t7", type: "multiple_choice", prompt: "x + 2(x + 3) = ?", options: ["3x + 6", "3x + 3", "2x + 6", "3x + 5"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t8", type: "multiple_choice", prompt: "6x − 2(x − 1) = ?", options: ["4x + 2", "4x − 2", "8x − 2", "4x − 1"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t9", type: "multiple_choice", prompt: "2(2x + 1) + 3 = ?", options: ["4x + 5", "4x + 4", "4x + 2", "5x + 5"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t10", type: "multiple_choice", prompt: "10 − (x − 3) = ?", options: ["13 − x", "7 − x", "13 + x", "7 + x"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t11", type: "multiple_choice", prompt: "3(x + 2) − 2x = ?", options: ["x + 6", "5x + 6", "x + 2", "x + 4"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t12", type: "multiple_choice", prompt: "4x + 3 − 2x − 1 = ?", options: ["2x + 2", "2x + 4", "6x + 2", "2x − 2"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t13", type: "multiple_choice", prompt: "5(a − 2) + 10 = ?", options: ["5a", "5a − 10", "5a + 10", "5a − 2"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t14", type: "multiple_choice", prompt: "2x + 3y − x + y = ?", options: ["x + 4y", "3x + 4y", "x + 2y", "x + 3y"], correctIndex: 0, xp: 10 },
            { id: "ry7-cebr-l4-t15", type: "multiple_choice", prompt: "3(2x − 1) − (x − 4) = ?", options: ["5x + 1", "5x − 1", "7x + 1", "5x − 7"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-cebr-l4-b1", type: "multiple_choice", prompt: "2(x + 3) + 3(2x − 1) = ?", options: ["8x + 3", "8x + 9", "8x − 3", "5x + 3"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l4-b2", type: "multiple_choice", prompt: "x = 2 olduqda 3(x + 1) − x sadələşəndən sonrakı qiyməti?", options: ["7", "9", "5", "6"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l4-b3", type: "multiple_choice", prompt: "4a − 2(a − 3) + a = ?", options: ["3a + 6", "3a − 6", "5a + 6", "3a"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l4-b4", type: "multiple_choice", prompt: "−(2x − 5) + 3x = ?", options: ["x + 5", "5x + 5", "x − 5", "−x + 5"], correctIndex: 0, xp: 15 },
            { id: "ry7-cebr-l4-b5", type: "multiple_choice", prompt: "2(3x + y) − (x + 2y) = ?", options: ["5x", "5x + 4y", "7x", "5x − 4y"], correctIndex: 0, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 3. Birdəyişənli tənliklər ═══════════════
    {
      id: "ry7-tenlik",
      title: "Birdəyişənli tənliklər",
      description:
        "Tənlik və onun kökü, sadə tənliklərin həlli, hədlərin köçürülməsi və mötərizəli tənliklər, mətn məsələləri.",
      lessons: [
        {
          id: "ry7-tenl-l1",
          title: "Tənlik və onun kökü",
          intro: "Tənlik nədir və hansı ədəd onun kökü (həlli) olur.",
          sections: [
            { heading: "Tənlik nədir?", body: "Tərkibində naməlum (dəyişən) olan bərabərliyə tənlik deyilir: x + 3 = 7. Tənliyi ödəyən naməlumun qiymətinə onun kökü (həlli) deyilir." },
            { heading: "Kökün yoxlanması", body: "x = 4 tənliyin köküdürsə, onu yerinə qoyduqda bərabərlik doğru olur: 4 + 3 = 7 ✓." },
          ],
          tasks: [
            { id: "ry7-tenl-l1-t1", type: "numeric", prompt: "x + 3 = 7 tənliyinin kökü nədir?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l1-t2", type: "numeric", prompt: "x − 2 = 5 tənliyinin kökü?", answer: 7, xp: 10 },
            { id: "ry7-tenl-l1-t3", type: "numeric", prompt: "x + 6 = 6 tənliyinin kökü?", answer: 0, xp: 10 },
            { id: "ry7-tenl-l1-t4", type: "numeric", prompt: "2x = 8 tənliyinin kökü?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l1-t5", type: "multiple_choice", prompt: "x = 5 hansı tənliyin köküdür?", options: ["x + 2 = 7", "x + 2 = 8", "x − 5 = 5", "2x = 8"], correctIndex: 0, xp: 10 },
            { id: "ry7-tenl-l1-t6", type: "multiple_choice", prompt: "Tənliyi ödəyən naməlumun qiymətinə nə deyilir?", options: ["kök (həll)", "əmsal", "modul", "dərəcə"], correctIndex: 0, xp: 10 },
            { id: "ry7-tenl-l1-t7", type: "numeric", prompt: "x − 10 = 0 tənliyinin kökü?", answer: 10, xp: 10 },
            { id: "ry7-tenl-l1-t8", type: "numeric", prompt: "3x = 9 tənliyinin kökü?", answer: 3, xp: 10 },
            { id: "ry7-tenl-l1-t9", type: "multiple_choice", prompt: "x = 2, x + 4 = 6 tənliyinin köküdürmü?", options: ["Bəli", "Xeyr", "Bilmək olmur", "Yalnız yoxlamaqla mümkün deyil"], correctIndex: 0, xp: 10 },
            { id: "ry7-tenl-l1-t10", type: "numeric", prompt: "x + 1 = 1 tənliyinin kökü?", answer: 0, xp: 10 },
            { id: "ry7-tenl-l1-t11", type: "numeric", prompt: "5x = 25 tənliyinin kökü?", answer: 5, xp: 10 },
            { id: "ry7-tenl-l1-t12", type: "numeric", prompt: "x − 4 = −4 tənliyinin kökü?", answer: 0, xp: 10 },
            { id: "ry7-tenl-l1-t13", type: "multiple_choice", prompt: "Aşağıdakılardan hansı tənlikdir?", options: ["x + 5 = 9", "3 + 5 = 8", "2x + 1", "x + 5"], correctIndex: 0, xp: 10 },
            { id: "ry7-tenl-l1-t14", type: "numeric", prompt: "x + 8 = 12 tənliyinin kökü?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l1-t15", type: "numeric", prompt: "4x = 0 tənliyinin kökü?", answer: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-tenl-l1-b1", type: "numeric", prompt: "x + 3 = 0 tənliyinin kökü?", answer: -3, xp: 15 },
            { id: "ry7-tenl-l1-b2", type: "numeric", prompt: "2x = −6 tənliyinin kökü?", answer: -3, xp: 15 },
            { id: "ry7-tenl-l1-b3", type: "multiple_choice", prompt: "x = −2, x + 5 = 3 tənliyinin köküdürmü?", options: ["Bəli", "Xeyr", "Yalnız müsbət kök olur", "0-dır"], correctIndex: 0, xp: 15 },
            { id: "ry7-tenl-l1-b4", type: "numeric", prompt: "x − 7 = −10 tənliyinin kökü?", answer: -3, xp: 15 },
            { id: "ry7-tenl-l1-b5", type: "numeric", prompt: "10x = 100 tənliyinin kökü?", answer: 10, xp: 15 },
          ],
        },
        {
          id: "ry7-tenl-l2",
          title: "Sadə tənliklərin həlli",
          intro: "x + a = b, x − a = b və ax = b tipli tənlikləri həll etmək.",
          sections: [
            { heading: "Toplama/çıxma ilə", body: "x + a = b olduqda x = b − a. Məsələn: x + 5 = 12 → x = 12 − 5 = 7." },
            { heading: "Vurma ilə", body: "ax = b olduqda x = b : a. Məsələn: 3x = 15 → x = 15 : 3 = 5." },
          ],
          tasks: [
            { id: "ry7-tenl-l2-t1", type: "numeric", prompt: "x + 5 = 12, x = ?", answer: 7, xp: 10 },
            { id: "ry7-tenl-l2-t2", type: "numeric", prompt: "x − 4 = 9, x = ?", answer: 13, xp: 10 },
            { id: "ry7-tenl-l2-t3", type: "numeric", prompt: "3x = 15, x = ?", answer: 5, xp: 10 },
            { id: "ry7-tenl-l2-t4", type: "numeric", prompt: "x + 10 = 10, x = ?", answer: 0, xp: 10 },
            { id: "ry7-tenl-l2-t5", type: "numeric", prompt: "4x = 20, x = ?", answer: 5, xp: 10 },
            { id: "ry7-tenl-l2-t6", type: "numeric", prompt: "x − 7 = 0, x = ?", answer: 7, xp: 10 },
            { id: "ry7-tenl-l2-t7", type: "numeric", prompt: "6x = 18, x = ?", answer: 3, xp: 10 },
            { id: "ry7-tenl-l2-t8", type: "numeric", prompt: "x + 8 = 20, x = ?", answer: 12, xp: 10 },
            { id: "ry7-tenl-l2-t9", type: "numeric", prompt: "5x = 45, x = ?", answer: 9, xp: 10 },
            { id: "ry7-tenl-l2-t10", type: "numeric", prompt: "x − 12 = 8, x = ?", answer: 20, xp: 10 },
            { id: "ry7-tenl-l2-t11", type: "numeric", prompt: "2x = 7, x = ? (onluq kəsr yaz)", answer: 3.5, tolerance: 0.01, xp: 10 },
            { id: "ry7-tenl-l2-t12", type: "numeric", prompt: "x + 15 = 9, x = ?", answer: -6, xp: 10 },
            { id: "ry7-tenl-l2-t13", type: "numeric", prompt: "7x = 0, x = ?", answer: 0, xp: 10 },
            { id: "ry7-tenl-l2-t14", type: "multiple_choice", prompt: "ax = b tənliyində x necə tapılır?", options: ["x = b : a", "x = b − a", "x = a : b", "x = a + b"], correctIndex: 0, xp: 10 },
            { id: "ry7-tenl-l2-t15", type: "numeric", prompt: "x − 3 = −8, x = ?", answer: -5, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-tenl-l2-b1", type: "numeric", prompt: "10x = 25, x = ? (onluq)", answer: 2.5, tolerance: 0.01, xp: 15 },
            { id: "ry7-tenl-l2-b2", type: "numeric", prompt: "x + 4 = −4, x = ?", answer: -8, xp: 15 },
            { id: "ry7-tenl-l2-b3", type: "numeric", prompt: "−2x = 10, x = ?", answer: -5, xp: 15 },
            { id: "ry7-tenl-l2-b4", type: "numeric", prompt: "x : 3 = 4, x = ?", answer: 12, xp: 15 },
            { id: "ry7-tenl-l2-b5", type: "numeric", prompt: "8x = 4, x = ? (onluq)", answer: 0.5, tolerance: 0.01, xp: 15 },
          ],
        },
        {
          id: "ry7-tenl-l3",
          title: "Hədlərin köçürülməsi",
          intro: "ax + b = c tipli tənlikləri hədləri o biri tərəfə köçürməklə həll etmək.",
          sections: [
            { heading: "Köçürmə qaydası", body: "Hədi bərabərliyin o biri tərəfinə keçirdikdə onun işarəsi dəyişir. Məsələn: 2x + 3 = 11 → 2x = 11 − 3 → 2x = 8 → x = 4." },
            { heading: "Naməlumları bir tərəfə", body: "5x − 2 = 3x + 6 → 5x − 3x = 6 + 2 → 2x = 8 → x = 4." },
          ],
          tasks: [
            { id: "ry7-tenl-l3-t1", type: "numeric", prompt: "2x + 3 = 11, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l3-t2", type: "numeric", prompt: "3x − 5 = 10, x = ?", answer: 5, xp: 10 },
            { id: "ry7-tenl-l3-t3", type: "numeric", prompt: "5x + 2 = 17, x = ?", answer: 3, xp: 10 },
            { id: "ry7-tenl-l3-t4", type: "numeric", prompt: "4x − 1 = 15, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l3-t5", type: "numeric", prompt: "2x + 7 = 7, x = ?", answer: 0, xp: 10 },
            { id: "ry7-tenl-l3-t6", type: "numeric", prompt: "6x − 4 = 20, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l3-t7", type: "numeric", prompt: "3x + 1 = 10, x = ?", answer: 3, xp: 10 },
            { id: "ry7-tenl-l3-t8", type: "numeric", prompt: "5x − 2 = 3x + 6, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l3-t9", type: "numeric", prompt: "4x + 3 = 2x + 11, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l3-t10", type: "numeric", prompt: "7x = 4x + 12, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l3-t11", type: "numeric", prompt: "10 − x = 4, x = ?", answer: 6, xp: 10 },
            { id: "ry7-tenl-l3-t12", type: "numeric", prompt: "2x + 5 = 1, x = ?", answer: -2, xp: 10 },
            { id: "ry7-tenl-l3-t13", type: "multiple_choice", prompt: "Hədi o biri tərəfə köçürdükdə nə baş verir?", options: ["işarəsi dəyişir", "işarəsi dəyişmir", "əmsalı dəyişir", "yox olur"], correctIndex: 0, xp: 10 },
            { id: "ry7-tenl-l3-t14", type: "numeric", prompt: "8x − 3 = 5x + 9, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l3-t15", type: "numeric", prompt: "3x + 4 = x + 10, x = ?", answer: 3, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-tenl-l3-b1", type: "numeric", prompt: "2x + 1 = 8, x = ? (onluq)", answer: 3.5, tolerance: 0.01, xp: 15 },
            { id: "ry7-tenl-l3-b2", type: "numeric", prompt: "6x − 5 = 2x − 1, x = ?", answer: 1, xp: 15 },
            { id: "ry7-tenl-l3-b3", type: "numeric", prompt: "5 − 2x = 11, x = ?", answer: -3, xp: 15 },
            { id: "ry7-tenl-l3-b4", type: "numeric", prompt: "4x + 9 = 9, x = ?", answer: 0, xp: 15 },
            { id: "ry7-tenl-l3-b5", type: "numeric", prompt: "7x − 3 = 4x + 12, x = ?", answer: 5, xp: 15 },
          ],
        },
        {
          id: "ry7-tenl-l4",
          title: "Mötərizəli tənliklər və məsələlər",
          intro: "Mötərizələri açaraq tənlik həll etmək və mətn məsələlərini tənliklə həll etmək.",
          sections: [
            { heading: "Mötərizəli tənlik", body: "Əvvəlcə mötərizəni aç, sonra həll et: 2(x + 3) = 14 → 2x + 6 = 14 → 2x = 8 → x = 4." },
            { heading: "Mətn məsələsi", body: "Naməlumu x ilə işarələ, şərtə görə tənlik qur, həll et. Məs.: 'Bir ədədin 3 misli 21-dir' → 3x = 21 → x = 7." },
          ],
          tasks: [
            { id: "ry7-tenl-l4-t1", type: "numeric", prompt: "2(x + 3) = 14, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l4-t2", type: "numeric", prompt: "3(x − 1) = 12, x = ?", answer: 5, xp: 10 },
            { id: "ry7-tenl-l4-t3", type: "numeric", prompt: "5(x + 2) = 25, x = ?", answer: 3, xp: 10 },
            { id: "ry7-tenl-l4-t4", type: "numeric", prompt: "2(x − 4) = 0, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l4-t5", type: "numeric", prompt: "4(x + 1) = 20, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l4-t6", type: "numeric", prompt: "Bir ədədin 3 misli 21-dir. Bu ədəd nədir?", answer: 7, xp: 10 },
            { id: "ry7-tenl-l4-t7", type: "numeric", prompt: "Bir ədədin üstünə 8 gəlsək 15 alınır. Ədəd nədir?", answer: 7, xp: 10 },
            { id: "ry7-tenl-l4-t8", type: "numeric", prompt: "3(x + 2) = 18, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l4-t9", type: "numeric", prompt: "Bir ədədin 2 mislindən 5 çıxsaq 9 alınır. Ədəd nədir?", answer: 7, xp: 10 },
            { id: "ry7-tenl-l4-t10", type: "numeric", prompt: "2(x + 5) = 16, x = ?", answer: 3, xp: 10 },
            { id: "ry7-tenl-l4-t11", type: "numeric", prompt: "6(x − 2) = 12, x = ?", answer: 4, xp: 10 },
            { id: "ry7-tenl-l4-t12", type: "numeric", prompt: "Ata oğuldan 3 dəfə yaşlıdır. Oğul 8 yaşındadır. Ata neçə yaşındadır?", answer: 24, xp: 10 },
            { id: "ry7-tenl-l4-t13", type: "numeric", prompt: "2(x + 1) + 3 = 9, x = ?", answer: 2, xp: 10 },
            { id: "ry7-tenl-l4-t14", type: "numeric", prompt: "İki ardıcıl ədədin cəmi 15-dir. Kiçiyi nədir? (x + (x+1) = 15)", answer: 7, xp: 10 },
            { id: "ry7-tenl-l4-t15", type: "numeric", prompt: "3(x − 2) = 2(x + 1), x = ?", answer: 8, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry7-tenl-l4-b1", type: "numeric", prompt: "4(x + 3) = 2(x + 9), x = ?", answer: 3, xp: 15 },
            { id: "ry7-tenl-l4-b2", type: "numeric", prompt: "Bir düzbucaqlının eni x, uzunu x+4-dür, perimetri 20-dir. Eni nədir? (2(x+x+4)=20)", answer: 3, xp: 15 },
            { id: "ry7-tenl-l4-b3", type: "numeric", prompt: "5(x − 1) = 3(x + 1), x = ?", answer: 4, xp: 15 },
            { id: "ry7-tenl-l4-b4", type: "numeric", prompt: "2(2x + 1) = 3(x + 4), x = ?", answer: 10, xp: 15 },
            { id: "ry7-tenl-l4-b5", type: "numeric", prompt: "Bir ədədin yarısı 12-dir. Ədəd nədir? (x : 2 = 12)", answer: 24, xp: 15 },
          ],
        },
      ],
    },
  ],
};
