// Riyaziyyat — 2-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 100-ə qədər  2) 100 dairəsində toplama  3) 100 dairəsində çıxma
// 4) Vurma (2,3,4,5)  5) Bölmə  6) Ölçmə, zaman, pul və fiqurlar.
// 2-ci sinif üçün suallar sadədir (rəqəm cavablar). id prefiksi ry2-*.

import type { Subject } from "../types";

export const math2: Subject = {
  slug: "riyaziyyat-2",
  name: "Riyaziyyat",
  grade: 2,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Ədədlər 100-ə qədər ═══════════════
    {
      id: "ry2-yuzluk",
      title: "Ədədlər 100-ə qədər",
      description: "İkirəqəmli ədədləri oxumaq, yazmaq, onluq və təkliklərə ayırmaq, müqayisə etmək.",
      lessons: [
        {
          id: "ry2-yuzluk-l1",
          title: "İkirəqəmli ədədlər",
          intro: "Onluq və təklikləri tanıyaq.",
          sections: [
            { heading: "Onluq və təklik", body: "İkirəqəmli ədəd onluq və təklikdən ibarətdir. 34 = 3 onluq + 4 təklik. 50 = 5 onluq. 7 = 7 təklik." },
            { heading: "Sıra", body: "Ədədlər sıra ilə gedir: 20, 21, 22... Hər ədəddən sonra gələn 1 böyükdür." },
          ],
          tasks: [
            { id: "ry2-yuzluk-l1-t1", type: "numeric", prompt: "34 ədədində neçə onluq var?", answer: 3, xp: 10 },
            { id: "ry2-yuzluk-l1-t2", type: "numeric", prompt: "34 ədədində neçə təklik var?", answer: 4, xp: 10 },
            { id: "ry2-yuzluk-l1-t3", type: "numeric", prompt: "50 ədədində neçə onluq var?", answer: 5, xp: 10 },
            { id: "ry2-yuzluk-l1-t4", type: "numeric", prompt: "3 onluq + 5 təklik = ?", answer: 35, xp: 10 },
            { id: "ry2-yuzluk-l1-t5", type: "numeric", prompt: "4 onluq + 2 təklik = ?", answer: 42, xp: 10 },
            { id: "ry2-yuzluk-l1-t6", type: "numeric", prompt: "6 onluq = ?", answer: 60, xp: 10 },
            { id: "ry2-yuzluk-l1-t7", type: "numeric", prompt: "29-dan sonra hansı ədəd gəlir?", answer: 30, xp: 10 },
            { id: "ry2-yuzluk-l1-t8", type: "numeric", prompt: "50-dən əvvəl gələn ədəd hansıdır?", answer: 49, xp: 10 },
            { id: "ry2-yuzluk-l1-t9", type: "numeric", prompt: "99-dan sonra hansı ədəd gəlir?", answer: 100, xp: 10 },
            { id: "ry2-yuzluk-l1-t10", type: "multiple_choice", prompt: "47 və 74 ədədlərindən böyüyü hansıdır?", options: ["74", "47", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l1-t11", type: "multiple_choice", prompt: "63 və 36 ədədlərindən kiçiyi hansıdır?", options: ["36", "63", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l1-t12", type: "numeric", prompt: "7 onluq + 0 təklik = ?", answer: 70, xp: 10 },
            { id: "ry2-yuzluk-l1-t13", type: "numeric", prompt: "'səksən' ədədi rəqəmlə necə yazılır?", answer: 80, xp: 10 },
            { id: "ry2-yuzluk-l1-t14", type: "numeric", prompt: "'iyirmi beş' ədədi rəqəmlə necə yazılır?", answer: 25, xp: 10 },
            { id: "ry2-yuzluk-l1-t15", type: "numeric", prompt: "90-dan sonra hansı ədəd gəlir?", answer: 91, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-yuzluk-l1-b1", type: "numeric", prompt: "56 və 65 ədədlərindən böyüyü hansıdır?", answer: 65, xp: 15 },
            { id: "ry2-yuzluk-l1-b2", type: "numeric", prompt: "8 onluq + 8 təklik = ?", answer: 88, xp: 15 },
            { id: "ry2-yuzluk-l1-b3", type: "numeric", prompt: "100 ədədində neçə onluq var?", answer: 10, xp: 15 },
            { id: "ry2-yuzluk-l1-b4", type: "numeric", prompt: "'qırx' ədədi rəqəmlə necə yazılır?", answer: 40, xp: 15 },
            { id: "ry2-yuzluk-l1-b5", type: "numeric", prompt: "45, 54, 44 ədədlərindən ən böyüyü hansıdır?", answer: 54, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 2. 100 dairəsində toplama ═══════════════
    {
      id: "ry2-toplama",
      title: "100 dairəsində toplama",
      description: "İkirəqəmli ədədləri toplamaq.",
      lessons: [
        {
          id: "ry2-toplama-l1",
          title: "Toplama",
          intro: "Onluqları onluqlara, təklikləri təkliklərə əlavə edirik.",
          sections: [
            { heading: "Toplama", body: "20 + 30 = 50 (onluqlar). 23 + 14 = 37 (əvvəl təkliklər 3+4=7, sonra onluqlar 20+10=30)." },
          ],
          tasks: [
            { id: "ry2-toplama-l1-t1", type: "numeric", prompt: "20 + 30 = ?", answer: 50, xp: 10 },
            { id: "ry2-toplama-l1-t2", type: "numeric", prompt: "40 + 10 = ?", answer: 50, xp: 10 },
            { id: "ry2-toplama-l1-t3", type: "numeric", prompt: "23 + 14 = ?", answer: 37, xp: 10 },
            { id: "ry2-toplama-l1-t4", type: "numeric", prompt: "31 + 25 = ?", answer: 56, xp: 10 },
            { id: "ry2-toplama-l1-t5", type: "numeric", prompt: "12 + 6 = ?", answer: 18, xp: 10 },
            { id: "ry2-toplama-l1-t6", type: "numeric", prompt: "45 + 4 = ?", answer: 49, xp: 10 },
            { id: "ry2-toplama-l1-t7", type: "numeric", prompt: "50 + 25 = ?", answer: 75, xp: 10 },
            { id: "ry2-toplama-l1-t8", type: "numeric", prompt: "33 + 33 = ?", answer: 66, xp: 10 },
            { id: "ry2-toplama-l1-t9", type: "numeric", prompt: "60 + 40 = ?", answer: 100, xp: 10 },
            { id: "ry2-toplama-l1-t10", type: "numeric", prompt: "17 + 12 = ?", answer: 29, xp: 10 },
            { id: "ry2-toplama-l1-t11", type: "numeric", prompt: "25 + 25 = ?", answer: 50, xp: 10 },
            { id: "ry2-toplama-l1-t12", type: "numeric", prompt: "44 + 15 = ?", answer: 59, xp: 10 },
            { id: "ry2-toplama-l1-t13", type: "numeric", prompt: "70 + 20 = ?", answer: 90, xp: 10 },
            { id: "ry2-toplama-l1-t14", type: "numeric", prompt: "36 + 12 = ?", answer: 48, xp: 10 },
            { id: "ry2-toplama-l1-t15", type: "numeric", prompt: "28 + 30 = ?", answer: 58, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-toplama-l1-b1", type: "numeric", prompt: "27 + 15 = ? (təkliklər 7+5=12, keçidli)", answer: 42, xp: 15 },
            { id: "ry2-toplama-l1-b2", type: "numeric", prompt: "48 + 26 = ?", answer: 74, xp: 15 },
            { id: "ry2-toplama-l1-b3", type: "numeric", prompt: "55 + 45 = ?", answer: 100, xp: 15 },
            { id: "ry2-toplama-l1-b4", type: "numeric", prompt: "19 + 19 = ?", answer: 38, xp: 15 },
            { id: "ry2-toplama-l1-b5", type: "numeric", prompt: "34 + 29 = ?", answer: 63, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 3. 100 dairəsində çıxma ═══════════════
    {
      id: "ry2-cixma",
      title: "100 dairəsində çıxma",
      description: "İkirəqəmli ədədlərdən çıxmaq.",
      lessons: [
        {
          id: "ry2-cixma-l1",
          title: "Çıxma",
          intro: "Onluqlardan onluqları, təkliklərdən təklikləri çıxırıq.",
          sections: [
            { heading: "Çıxma", body: "50 − 20 = 30 (onluqlar). 37 − 14 = 23 (təkliklər 7−4=3, onluqlar 30−10=20)." },
          ],
          tasks: [
            { id: "ry2-cixma-l1-t1", type: "numeric", prompt: "50 − 20 = ?", answer: 30, xp: 10 },
            { id: "ry2-cixma-l1-t2", type: "numeric", prompt: "60 − 40 = ?", answer: 20, xp: 10 },
            { id: "ry2-cixma-l1-t3", type: "numeric", prompt: "37 − 14 = ?", answer: 23, xp: 10 },
            { id: "ry2-cixma-l1-t4", type: "numeric", prompt: "56 − 25 = ?", answer: 31, xp: 10 },
            { id: "ry2-cixma-l1-t5", type: "numeric", prompt: "18 − 6 = ?", answer: 12, xp: 10 },
            { id: "ry2-cixma-l1-t6", type: "numeric", prompt: "49 − 4 = ?", answer: 45, xp: 10 },
            { id: "ry2-cixma-l1-t7", type: "numeric", prompt: "75 − 25 = ?", answer: 50, xp: 10 },
            { id: "ry2-cixma-l1-t8", type: "numeric", prompt: "66 − 33 = ?", answer: 33, xp: 10 },
            { id: "ry2-cixma-l1-t9", type: "numeric", prompt: "100 − 50 = ?", answer: 50, xp: 10 },
            { id: "ry2-cixma-l1-t10", type: "numeric", prompt: "29 − 12 = ?", answer: 17, xp: 10 },
            { id: "ry2-cixma-l1-t11", type: "numeric", prompt: "40 − 15 = ?", answer: 25, xp: 10 },
            { id: "ry2-cixma-l1-t12", type: "numeric", prompt: "59 − 15 = ?", answer: 44, xp: 10 },
            { id: "ry2-cixma-l1-t13", type: "numeric", prompt: "90 − 20 = ?", answer: 70, xp: 10 },
            { id: "ry2-cixma-l1-t14", type: "numeric", prompt: "48 − 12 = ?", answer: 36, xp: 10 },
            { id: "ry2-cixma-l1-t15", type: "numeric", prompt: "58 − 30 = ?", answer: 28, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-cixma-l1-b1", type: "numeric", prompt: "42 − 15 = ? (keçidli)", answer: 27, xp: 15 },
            { id: "ry2-cixma-l1-b2", type: "numeric", prompt: "74 − 26 = ?", answer: 48, xp: 15 },
            { id: "ry2-cixma-l1-b3", type: "numeric", prompt: "100 − 45 = ?", answer: 55, xp: 15 },
            { id: "ry2-cixma-l1-b4", type: "numeric", prompt: "38 − 19 = ?", answer: 19, xp: 15 },
            { id: "ry2-cixma-l1-b5", type: "numeric", prompt: "63 − 29 = ?", answer: 34, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 4. Vurma ═══════════════
    {
      id: "ry2-vurma",
      title: "Vurma (2, 3, 4, 5)",
      description: "Vurma cədvəlinin başlanğıcı: 2, 3, 4, 5 ilə vurma.",
      lessons: [
        {
          id: "ry2-vurma-l1",
          title: "Vurma nədir?",
          intro: "Vurma — eyni ədədin təkrar toplanmasıdır. 3 × 2 = 2 + 2 + 2 = 6.",
          sections: [
            { heading: "Vurma", body: "3 × 2 o deməkdir ki, 2-ni 3 dəfə toplayırıq: 2 + 2 + 2 = 6. Yəni 3 × 2 = 6." },
            { heading: "5 cədvəli", body: "5 × 1 = 5, 5 × 2 = 10, 5 × 3 = 15, 5 × 4 = 20, 5 × 5 = 25." },
          ],
          tasks: [
            { id: "ry2-vurma-l1-t1", type: "numeric", prompt: "2 × 2 = ?", answer: 4, xp: 10 },
            { id: "ry2-vurma-l1-t2", type: "numeric", prompt: "2 × 3 = ?", answer: 6, xp: 10 },
            { id: "ry2-vurma-l1-t3", type: "numeric", prompt: "2 × 5 = ?", answer: 10, xp: 10 },
            { id: "ry2-vurma-l1-t4", type: "numeric", prompt: "3 × 3 = ?", answer: 9, xp: 10 },
            { id: "ry2-vurma-l1-t5", type: "numeric", prompt: "3 × 4 = ?", answer: 12, xp: 10 },
            { id: "ry2-vurma-l1-t6", type: "numeric", prompt: "4 × 2 = ?", answer: 8, xp: 10 },
            { id: "ry2-vurma-l1-t7", type: "numeric", prompt: "4 × 5 = ?", answer: 20, xp: 10 },
            { id: "ry2-vurma-l1-t8", type: "numeric", prompt: "5 × 2 = ?", answer: 10, xp: 10 },
            { id: "ry2-vurma-l1-t9", type: "numeric", prompt: "5 × 5 = ?", answer: 25, xp: 10 },
            { id: "ry2-vurma-l1-t10", type: "numeric", prompt: "5 × 4 = ?", answer: 20, xp: 10 },
            { id: "ry2-vurma-l1-t11", type: "numeric", prompt: "2 + 2 + 2 + 2 neçə edir? (4 × 2)", answer: 8, xp: 10 },
            { id: "ry2-vurma-l1-t12", type: "numeric", prompt: "3 × 5 = ?", answer: 15, xp: 10 },
            { id: "ry2-vurma-l1-t13", type: "numeric", prompt: "4 × 4 = ?", answer: 16, xp: 10 },
            { id: "ry2-vurma-l1-t14", type: "numeric", prompt: "2 × 1 = ?", answer: 2, xp: 10 },
            { id: "ry2-vurma-l1-t15", type: "numeric", prompt: "5 × 3 = ?", answer: 15, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-vurma-l1-b1", type: "numeric", prompt: "5 × 6 = ?", answer: 30, xp: 15 },
            { id: "ry2-vurma-l1-b2", type: "numeric", prompt: "4 × 6 = ?", answer: 24, xp: 15 },
            { id: "ry2-vurma-l1-b3", type: "numeric", prompt: "3 × 6 = ?", answer: 18, xp: 15 },
            { id: "ry2-vurma-l1-b4", type: "numeric", prompt: "2 × 8 = ?", answer: 16, xp: 15 },
            { id: "ry2-vurma-l1-b5", type: "numeric", prompt: "Hər səbətdə 5 alma var. 3 səbətdə neçə alma var?", answer: 15, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 5. Bölmə ═══════════════
    {
      id: "ry2-bolme",
      title: "Bölmə",
      description: "Bölmənin başlanğıcı: bərabər hissələrə bölmək.",
      lessons: [
        {
          id: "ry2-bolme-l1",
          title: "Bölmə nədir?",
          intro: "Bölmə — bərabər hissələrə ayırmaqdır. 6 ÷ 2 = 3.",
          sections: [
            { heading: "Bölmə", body: "6 almanı 2 uşağa bərabər paylasaq, hər biri 3 alma alır: 6 ÷ 2 = 3. Bölmə vurmanın əksidir: 2 × 3 = 6, ona görə 6 ÷ 2 = 3." },
          ],
          tasks: [
            { id: "ry2-bolme-l1-t1", type: "numeric", prompt: "6 ÷ 2 = ?", answer: 3, xp: 10 },
            { id: "ry2-bolme-l1-t2", type: "numeric", prompt: "8 ÷ 2 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l1-t3", type: "numeric", prompt: "10 ÷ 2 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l1-t4", type: "numeric", prompt: "9 ÷ 3 = ?", answer: 3, xp: 10 },
            { id: "ry2-bolme-l1-t5", type: "numeric", prompt: "12 ÷ 3 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l1-t6", type: "numeric", prompt: "12 ÷ 4 = ?", answer: 3, xp: 10 },
            { id: "ry2-bolme-l1-t7", type: "numeric", prompt: "20 ÷ 4 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l1-t8", type: "numeric", prompt: "10 ÷ 5 = ?", answer: 2, xp: 10 },
            { id: "ry2-bolme-l1-t9", type: "numeric", prompt: "25 ÷ 5 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l1-t10", type: "numeric", prompt: "20 ÷ 5 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l1-t11", type: "numeric", prompt: "4 ÷ 2 = ?", answer: 2, xp: 10 },
            { id: "ry2-bolme-l1-t12", type: "numeric", prompt: "15 ÷ 3 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l1-t13", type: "numeric", prompt: "16 ÷ 4 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l1-t14", type: "numeric", prompt: "6 almanı 3 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 2, xp: 10 },
            { id: "ry2-bolme-l1-t15", type: "numeric", prompt: "15 ÷ 5 = ?", answer: 3, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-bolme-l1-b1", type: "numeric", prompt: "30 ÷ 5 = ?", answer: 6, xp: 15 },
            { id: "ry2-bolme-l1-b2", type: "numeric", prompt: "24 ÷ 4 = ?", answer: 6, xp: 15 },
            { id: "ry2-bolme-l1-b3", type: "numeric", prompt: "18 ÷ 3 = ?", answer: 6, xp: 15 },
            { id: "ry2-bolme-l1-b4", type: "numeric", prompt: "10 konfeti 2 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 5, xp: 15 },
            { id: "ry2-bolme-l1-b5", type: "numeric", prompt: "16 ÷ 2 = ?", answer: 8, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 6. Ölçmə, zaman, pul və fiqurlar ═══════════════
    {
      id: "ry2-olcme",
      title: "Ölçmə, zaman, pul və fiqurlar",
      description: "Uzunluq, saat, pul (qəpik/manat) və həndəsi fiqurlar.",
      lessons: [
        {
          id: "ry2-olcme-l1",
          title: "Ölçmə və zaman",
          intro: "Santimetr, saat, pul və fiqurları tanıyaq.",
          sections: [
            { heading: "Uzunluq", body: "Uzunluğu santimetr (sm) və metr (m) ilə ölçürük. 1 metr = 100 santimetr." },
            { heading: "Zaman", body: "Bir saatda 60 dəqiqə var. Bir gündə 24 saat var. Bir həftədə 7 gün var." },
            { heading: "Pul", body: "1 manat = 100 qəpik." },
          ],
          tasks: [
            { id: "ry2-olcme-l1-t1", type: "numeric", prompt: "1 metr neçə santimetrdir?", answer: 100, xp: 10 },
            { id: "ry2-olcme-l1-t2", type: "numeric", prompt: "Bir saatda neçə dəqiqə var?", answer: 60, xp: 10 },
            { id: "ry2-olcme-l1-t3", type: "numeric", prompt: "Bir gündə neçə saat var?", answer: 24, xp: 10 },
            { id: "ry2-olcme-l1-t4", type: "numeric", prompt: "Bir həftədə neçə gün var?", answer: 7, xp: 10 },
            { id: "ry2-olcme-l1-t5", type: "numeric", prompt: "1 manat neçə qəpikdir?", answer: 100, xp: 10 },
            { id: "ry2-olcme-l1-t6", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10 },
            { id: "ry2-olcme-l1-t7", type: "numeric", prompt: "2 metr neçə santimetrdir?", answer: 200, xp: 10 },
            { id: "ry2-olcme-l1-t8", type: "multiple_choice", prompt: "Kvadratın neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l1-t9", type: "multiple_choice", prompt: "Üçbucağın neçə tərəfi var?", options: ["3", "4", "5", "2"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l1-t10", type: "numeric", prompt: "İki həftədə neçə gün var? (7 + 7)", answer: 14, xp: 10 },
            { id: "ry2-olcme-l1-t11", type: "numeric", prompt: "50 qəpik + 50 qəpik neçə manatdır?", answer: 1, xp: 10 },
            { id: "ry2-olcme-l1-t12", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["kvadrat", "düzbucaqlı", "dairə", "xətt"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l1-t13", type: "numeric", prompt: "Kvadratın bir tərəfi 5 sm-dir. Perimetri neçədir? (4 tərəf)", answer: 20, xp: 10 },
            { id: "ry2-olcme-l1-t14", type: "numeric", prompt: "Səhər saat 8-də başladı, 2 saat keçdi. Saat neçədir?", answer: 10, xp: 10 },
            { id: "ry2-olcme-l1-t15", type: "numeric", prompt: "Bir ildə neçə ay var?", answer: 12, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l1-b1", type: "numeric", prompt: "3 metr neçə santimetrdir?", answer: 300, xp: 15 },
            { id: "ry2-olcme-l1-b2", type: "numeric", prompt: "İki saatda neçə dəqiqə var? (60 + 60)", answer: 120, xp: 15 },
            { id: "ry2-olcme-l1-b3", type: "numeric", prompt: "Üçbucağın hər tərəfi 4 sm-dir. Perimetri neçədir? (3 tərəf)", answer: 12, xp: 15 },
            { id: "ry2-olcme-l1-b4", type: "numeric", prompt: "70 qəpik + 30 qəpik neçə manatdır?", answer: 1, xp: 15 },
            { id: "ry2-olcme-l1-b5", type: "numeric", prompt: "Düzbucaqlının tərəfləri 3 sm və 5 sm-dir. Perimetri? (2×(3+5))", answer: 16, xp: 15 },
          ],
        },
        {
          id: "ry2-olcme-l2",
          title: "Sadə məsələlər",
          intro: "Toplama, çıxma və vurma ilə məsələ həll edək.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, hansı əməli işlədəcəyini seç, sonra hesabla." },
          ],
          tasks: [
            { id: "ry2-olcme-l2-t1", type: "numeric", prompt: "Aylının 15 stikeri var, 12 də aldı. Neçə stikeri oldu?", answer: 27, xp: 10 },
            { id: "ry2-olcme-l2-t2", type: "numeric", prompt: "Rəfdə 40 kitab var idi, 15-ni götürdük. Neçə kitab qaldı?", answer: 25, xp: 10 },
            { id: "ry2-olcme-l2-t3", type: "numeric", prompt: "Hər qutuda 5 qələm var. 4 qutuda neçə qələm var?", answer: 20, xp: 10 },
            { id: "ry2-olcme-l2-t4", type: "numeric", prompt: "12 konfeti 3 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 4, xp: 10 },
            { id: "ry2-olcme-l2-t5", type: "numeric", prompt: "Bağçada 30 gül var idi, 25 də açdı. Neçə gül oldu?", answer: 55, xp: 10 },
            { id: "ry2-olcme-l2-t6", type: "numeric", prompt: "Elçinin 50 manatı var idi, 20 manat xərclədi. Neçə manatı qaldı?", answer: 30, xp: 10 },
            { id: "ry2-olcme-l2-t7", type: "numeric", prompt: "Hər masada 2 uşaq oturur. 5 masada neçə uşaq var?", answer: 10, xp: 10 },
            { id: "ry2-olcme-l2-t8", type: "numeric", prompt: "20 alma 5 səbətə bərabər paylandı. Hər səbətdə neçə alma var?", answer: 4, xp: 10 },
            { id: "ry2-olcme-l2-t9", type: "numeric", prompt: "Sinifdə 24 şagird var, 12-si qız. Neçə oğlan var?", answer: 12, xp: 10 },
            { id: "ry2-olcme-l2-t10", type: "numeric", prompt: "Hər gün 3 səhifə oxuyuram. 4 gündə neçə səhifə oxuyuram?", answer: 12, xp: 10 },
            { id: "ry2-olcme-l2-t11", type: "numeric", prompt: "35 + 40 = ? (məsələ: iki qrupun cəmi)", answer: 75, xp: 10 },
            { id: "ry2-olcme-l2-t12", type: "numeric", prompt: "Ağacda 18 quş var idi, 9-u uçdu. Neçə quş qaldı?", answer: 9, xp: 10 },
            { id: "ry2-olcme-l2-t13", type: "numeric", prompt: "Hər paketdə 4 peçenye var. 5 paketdə neçə peçenye var?", answer: 20, xp: 10 },
            { id: "ry2-olcme-l2-t14", type: "numeric", prompt: "16 oyuncaq 4 uşağa bərabər paylandı. Hər biri neçə alır?", answer: 4, xp: 10 },
            { id: "ry2-olcme-l2-t15", type: "numeric", prompt: "60 manatım var idi, 25 manat kitaba, 15 manat da çantaya verdim. Neçə manat qaldı?", answer: 20, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l2-b1", type: "numeric", prompt: "Hər həftədə 7 gün var. 3 həftədə neçə gün var?", answer: 21, xp: 15 },
            { id: "ry2-olcme-l2-b2", type: "numeric", prompt: "45 şəkil 5 albomda bərabər yerləşdi. Hər albomda neçə şəkil var?", answer: 9, xp: 15 },
            { id: "ry2-olcme-l2-b3", type: "numeric", prompt: "İki dostun birində 28, digərində 34 marka var. Cəmi neçə marka var?", answer: 62, xp: 15 },
            { id: "ry2-olcme-l2-b4", type: "numeric", prompt: "Hər qutuda 5 top var. 6 qutuda neçə top var?", answer: 30, xp: 15 },
            { id: "ry2-olcme-l2-b5", type: "numeric", prompt: "100 səhifəlik kitabın 60 səhifəsini oxudum. Neçə səhifə qaldı?", answer: 40, xp: 15 },
          ],
        },
      ],
    },
  ],
};
