// Riyaziyyat — 2-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 100-ə qədər  2) 100 dairəsində toplama  3) 100 dairəsində çıxma
// 4) Vurma (2,3,4,5)  5) Bölmə  6) Ölçmə, zaman, pul və fiqurlar.
// 2-ci sinif üçün suallar sadədir (rəqəm cavablar). id prefiksi ry2-*.

import type { Subject } from "../types";

export const math2: Subject = {
  slug: "riyaziyyat-2",
  name: "Riyaziyyat",
  grade: 2,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Ədədlər 100-ə qədər ═══════════════
    {
      id: "ry2-yuzluk",
      title: "Ədədlər 100-ə qədər",
      description: "İkirəqəmli ədədləri oxumaq, yazmaq, onluq və təkliklərə ayırmaq, müqayisə etmək.",
      lessons: [
        {
          id: "ry2-yuzluk-l1",
          title: "İkirəqəmli ədədlər",
          intro: "Onluq və təklikləri tanıyaq.",
          sections: [
            { heading: "Onluq və təklik", body: "İkirəqəmli ədəd onluq və təklikdən ibarətdir. 34 = 3 onluq + 4 təklik. 50 = 5 onluq. 7 = 7 təklik." },
            { heading: "Sıra", body: "Ədədlər sıra ilə gedir: 20, 21, 22... Hər ədəddən sonra gələn 1 böyükdür." },
          ],
          tasks: [
            { id: "ry2-yuzluk-l1-t1", type: "numeric", prompt: "34 ədədində neçə onluq var?", answer: 3, xp: 10 },
            { id: "ry2-yuzluk-l1-t2", type: "numeric", prompt: "34 ədədində neçə təklik var?", answer: 4, xp: 10 },
            { id: "ry2-yuzluk-l1-t3", type: "numeric", prompt: "50 ədədində neçə onluq var?", answer: 5, xp: 10 },
            { id: "ry2-yuzluk-l1-t4", type: "numeric", prompt: "3 onluq + 5 təklik = ?", answer: 35, xp: 10 },
            { id: "ry2-yuzluk-l1-t5", type: "numeric", prompt: "4 onluq + 2 təklik = ?", answer: 42, xp: 10 },
            { id: "ry2-yuzluk-l1-t6", type: "numeric", prompt: "6 onluq = ?", answer: 60, xp: 10 },
            { id: "ry2-yuzluk-l1-t7", type: "numeric", prompt: "29-dan sonra hansı ədəd gəlir?", answer: 30, xp: 10 },
            { id: "ry2-yuzluk-l1-t8", type: "numeric", prompt: "50-dən əvvəl gələn ədəd hansıdır?", answer: 49, xp: 10 },
            { id: "ry2-yuzluk-l1-t9", type: "numeric", prompt: "99-dan sonra hansı ədəd gəlir?", answer: 100, xp: 10 },
            { id: "ry2-yuzluk-l1-t10", type: "multiple_choice", prompt: "47 və 74 ədədlərindən böyüyü hansıdır?", options: ["74", "47", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l1-t11", type: "multiple_choice", prompt: "63 və 36 ədədlərindən kiçiyi hansıdır?", options: ["36", "63", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l1-t12", type: "numeric", prompt: "7 onluq + 0 təklik = ?", answer: 70, xp: 10 },
            { id: "ry2-yuzluk-l1-t13", type: "numeric", prompt: "'səksən' ədədi rəqəmlə necə yazılır?", answer: 80, xp: 10 },
            { id: "ry2-yuzluk-l1-t14", type: "numeric", prompt: "'iyirmi beş' ədədi rəqəmlə necə yazılır?", answer: 25, xp: 10 },
            { id: "ry2-yuzluk-l1-t15", type: "numeric", prompt: "90-dan sonra hansı ədəd gəlir?", answer: 91, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-yuzluk-l1-b1", type: "numeric", prompt: "56 və 65 ədədlərindən böyüyü hansıdır?", answer: 65, xp: 15 },
            { id: "ry2-yuzluk-l1-b2", type: "numeric", prompt: "8 onluq + 8 təklik = ?", answer: 88, xp: 15 },
            { id: "ry2-yuzluk-l1-b3", type: "numeric", prompt: "100 ədədində neçə onluq var?", answer: 10, xp: 15 },
            { id: "ry2-yuzluk-l1-b4", type: "numeric", prompt: "'qırx' ədədi rəqəmlə necə yazılır?", answer: 40, xp: 15 },
            { id: "ry2-yuzluk-l1-b5", type: "numeric", prompt: "45, 54, 44 ədədlərindən ən böyüyü hansıdır?", answer: 54, xp: 15 },
          ],
        },
        {
          id: "ry2-yuzluk-l2",
          title: "Ədədləri müqayisə et",
          intro: "Hansı böyükdür? Əvvəl onluqlara, sonra təkliklərə bax.",
          sections: [
            { heading: "Qayda", body: "İki ikirəqəmli ədədi müqayisə edərkən ƏVVƏL onluqlara bax. Onluqlar bərabərdirsə, təklikləri müqayisə et. Məsələn 47 və 42: onluqlar eynidir (4), təkliklərdə 7 > 2, deməli 47 > 42." },
            { heading: "İşarələr", body: "> böyükdür, < kiçikdir, = bərabərdir. İşarənin ağzı həmişə BÖYÜK ədədə baxır." },
          ],
          tasks: [
            { id: "ry2-yuzluk-l2-t1", type: "multiple_choice", prompt: "Hansı daha böyükdür: 47 yoxsa 42?", options: ["47", "42", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l2-t2", type: "multiple_choice", prompt: "Hansı daha böyükdür: 38 yoxsa 83?", options: ["83", "38", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l2-t3", type: "multiple_choice", prompt: "Hansı daha kiçikdir: 61 yoxsa 16?", options: ["16", "61", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l2-t4", type: "multiple_choice", prompt: "Müqayisədə ƏVVƏL nəyə baxırıq?", options: ["Onluqlara", "Təkliklərə", "Sonuncu rəqəmə", "Fərqi yoxdur"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l2-t5", type: "numeric", prompt: "25, 52, 35 — ən böyüyünü yaz.", answer: 52, xp: 10 },
            { id: "ry2-yuzluk-l2-t6", type: "numeric", prompt: "74, 47, 44 — ən kiçiyini yaz.", answer: 44, xp: 10 },
            { id: "ry2-yuzluk-l2-t7", type: "multiple_choice", prompt: "60 ... 59 — hansı işarə düzgündür?", options: [">", "<", "=", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l2-t8", type: "multiple_choice", prompt: "33 ... 33 — hansı işarə düzgündür?", options: ["=", ">", "<", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l2-t9", type: "numeric", prompt: "40-dan böyük, 42-dən kiçik ədəd hansıdır?", answer: 41, xp: 10 },
            { id: "ry2-yuzluk-l2-t10", type: "fill_blank", prompt: "İşarənin ağzı həmişə ______ ədədə baxır. (bir söz)", accepted: ["böyük", "Böyük", "boyuk"], xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-yuzluk-l2-b1", type: "numeric", prompt: "İkirəqəmli ən böyük ədəd hansıdır?", answer: 99, xp: 15 },
            { id: "ry2-yuzluk-l2-b2", type: "numeric", prompt: "İkirəqəmli ən kiçik ədəd hansıdır?", answer: 10, xp: 15 },
            { id: "ry2-yuzluk-l2-b3", type: "multiple_choice", prompt: "Onluğu 5, təkliyi 0 olan ədəd hansıdır?", options: ["50", "5", "15", "55"], correctIndex: 0, xp: 15 },
            { id: "ry2-yuzluk-l2-b4", type: "numeric", prompt: "68 və 86 — bunların fərqi neçədir?", answer: 18, xp: 15 },
          ],
        },
        {
          id: "ry2-yuzluk-l3",
          title: "Qonşu ədədlər və sıra",
          intro: "Hər ədədin bir əvvəlki və bir sonrakı qonşusu var.",
          sections: [
            { heading: "Qonşular", body: "Ədədin SOL qonşusu ondan 1 kiçik, SAĞ qonşusu 1 böyükdür. 39-un qonşuları: 38 və 40." },
            { heading: "Onluqla saymaq", body: "10, 20, 30, 40... — hər dəfə 10 artır. Bu, onluqla saymaqdır və toplamağı asanlaşdırır." },
          ],
          tasks: [
            { id: "ry2-yuzluk-l3-t1", type: "numeric", prompt: "39-dan sonra hansı ədəd gəlir?", answer: 40, xp: 10 },
            { id: "ry2-yuzluk-l3-t2", type: "numeric", prompt: "70-dən əvvəl hansı ədəd gəlir?", answer: 69, xp: 10 },
            { id: "ry2-yuzluk-l3-t3", type: "numeric", prompt: "50, 60, 70, ... — növbəti ədəd?", answer: 80, xp: 10 },
            { id: "ry2-yuzluk-l3-t4", type: "numeric", prompt: "99-dan sonra hansı ədəd gəlir?", answer: 100, xp: 10 },
            { id: "ry2-yuzluk-l3-t5", type: "numeric", prompt: "45-in sağ qonşusu hansıdır?", answer: 46, xp: 10 },
            { id: "ry2-yuzluk-l3-t6", type: "numeric", prompt: "20, 30, 40, ... — növbəti ədəd?", answer: 50, xp: 10 },
            { id: "ry2-yuzluk-l3-t7", type: "multiple_choice", prompt: "Ədədin sol qonşusu ondan neçə kiçikdir?", options: ["1", "2", "10", "5"], correctIndex: 0, xp: 10 },
            { id: "ry2-yuzluk-l3-t8", type: "numeric", prompt: "63-ün sol qonşusu hansıdır?", answer: 62, xp: 10 },
            { id: "ry2-yuzluk-l3-t9", type: "numeric", prompt: "2, 4, 6, 8, ... — növbəti ədəd?", answer: 10, xp: 10 },
            { id: "ry2-yuzluk-l3-t10", type: "numeric", prompt: "5, 10, 15, 20, ... — növbəti ədəd?", answer: 25, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-yuzluk-l3-b1", type: "numeric", prompt: "100, 90, 80, ... — növbəti ədəd?", answer: 70, xp: 15 },
            { id: "ry2-yuzluk-l3-b2", type: "numeric", prompt: "3, 6, 9, 12, ... — növbəti ədəd?", answer: 15, xp: 15 },
            { id: "ry2-yuzluk-l3-b3", type: "multiple_choice", prompt: "Hansı sırada ədədlər 10-la artır?", options: ["15, 25, 35", "15, 20, 25", "15, 16, 17", "15, 30, 45"], correctIndex: 0, xp: 15 },
            { id: "ry2-yuzluk-l3-b4", type: "numeric", prompt: "58 və 62 arasında neçə ədəd var?", answer: 3, xp: 15 },
          ],
        },
        {
          id: "ry2-yuzluk-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-yuzluk-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. 100 dairəsində toplama ═══════════════
    {
      id: "ry2-toplama",
      title: "100 dairəsində toplama",
      description: "İkirəqəmli ədədləri toplamaq.",
      lessons: [
        {
          id: "ry2-toplama-l1",
          title: "Toplama",
          intro: "Onluqları onluqlara, təklikləri təkliklərə əlavə edirik.",
          sections: [
            { heading: "Toplama", body: "20 + 30 = 50 (onluqlar). 23 + 14 = 37 (əvvəl təkliklər 3+4=7, sonra onluqlar 20+10=30)." },
          ],
          tasks: [
            { id: "ry2-toplama-l1-t1", type: "numeric", prompt: "20 + 30 = ?", answer: 50, xp: 10 },
            { id: "ry2-toplama-l1-t2", type: "numeric", prompt: "40 + 10 = ?", answer: 50, xp: 10 },
            { id: "ry2-toplama-l1-t3", type: "numeric", prompt: "23 + 14 = ?", answer: 37, xp: 10 },
            { id: "ry2-toplama-l1-t4", type: "numeric", prompt: "31 + 25 = ?", answer: 56, xp: 10 },
            { id: "ry2-toplama-l1-t5", type: "numeric", prompt: "12 + 6 = ?", answer: 18, xp: 10 },
            { id: "ry2-toplama-l1-t6", type: "numeric", prompt: "45 + 4 = ?", answer: 49, xp: 10 },
            { id: "ry2-toplama-l1-t7", type: "numeric", prompt: "50 + 25 = ?", answer: 75, xp: 10 },
            { id: "ry2-toplama-l1-t8", type: "numeric", prompt: "33 + 33 = ?", answer: 66, xp: 10 },
            { id: "ry2-toplama-l1-t9", type: "numeric", prompt: "60 + 40 = ?", answer: 100, xp: 10 },
            { id: "ry2-toplama-l1-t10", type: "numeric", prompt: "17 + 12 = ?", answer: 29, xp: 10 },
            { id: "ry2-toplama-l1-t11", type: "numeric", prompt: "25 + 25 = ?", answer: 50, xp: 10 },
            { id: "ry2-toplama-l1-t12", type: "numeric", prompt: "44 + 15 = ?", answer: 59, xp: 10 },
            { id: "ry2-toplama-l1-t13", type: "numeric", prompt: "70 + 20 = ?", answer: 90, xp: 10 },
            { id: "ry2-toplama-l1-t14", type: "numeric", prompt: "36 + 12 = ?", answer: 48, xp: 10 },
            { id: "ry2-toplama-l1-t15", type: "numeric", prompt: "28 + 30 = ?", answer: 58, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-toplama-l1-b1", type: "numeric", prompt: "27 + 15 = ? (təkliklər 7+5=12, keçidli)", answer: 42, xp: 15 },
            { id: "ry2-toplama-l1-b2", type: "numeric", prompt: "48 + 26 = ?", answer: 74, xp: 15 },
            { id: "ry2-toplama-l1-b3", type: "numeric", prompt: "55 + 45 = ?", answer: 100, xp: 15 },
            { id: "ry2-toplama-l1-b4", type: "numeric", prompt: "19 + 19 = ?", answer: 38, xp: 15 },
            { id: "ry2-toplama-l1-b5", type: "numeric", prompt: "34 + 29 = ?", answer: 63, xp: 15 },
          ],
        },
        {
          id: "ry2-toplama-l2",
          title: "Keçidsiz toplama",
          intro: "Təkliklərin cəmi 10-dan kiçik olanda toplama asandır.",
          sections: [
            { heading: "Addımlar", body: "34 + 25: əvvəl təklikləri topla (4 + 5 = 9), sonra onluqları (30 + 20 = 50). Cavab: 59." },
            { heading: "Yoxlama", body: "Toplama nəticəsini çıxma ilə yoxlaya bilərsən: 59 − 25 = 34. Düz alındısa, toplama doğrudur." },
          ],
          tasks: [
            { id: "ry2-toplama-l2-t1", type: "numeric", prompt: "34 + 25 = ?", answer: 59, xp: 10 },
            { id: "ry2-toplama-l2-t2", type: "numeric", prompt: "42 + 36 = ?", answer: 78, xp: 10 },
            { id: "ry2-toplama-l2-t3", type: "numeric", prompt: "51 + 27 = ?", answer: 78, xp: 10 },
            { id: "ry2-toplama-l2-t4", type: "numeric", prompt: "23 + 45 = ?", answer: 68, xp: 10 },
            { id: "ry2-toplama-l2-t5", type: "numeric", prompt: "60 + 15 = ?", answer: 75, xp: 10 },
            { id: "ry2-toplama-l2-t6", type: "numeric", prompt: "17 + 22 = ?", answer: 39, xp: 10 },
            { id: "ry2-toplama-l2-t7", type: "numeric", prompt: "45 + 33 = ?", answer: 78, xp: 10 },
            { id: "ry2-toplama-l2-t8", type: "multiple_choice", prompt: "Toplamanı hansı əməllə yoxlamaq olar?", options: ["Çıxma", "Vurma", "Bölmə", "Müqayisə"], correctIndex: 0, xp: 10 },
            { id: "ry2-toplama-l2-t9", type: "numeric", prompt: "31 + 8 = ?", answer: 39, xp: 10 },
            { id: "ry2-toplama-l2-t10", type: "numeric", prompt: "26 + 12 = ?", answer: 38, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-toplama-l2-b1", type: "numeric", prompt: "Aysel 23 ₼, Nihad 45 ₼ yığıb. Birlikdə neçə manat?", answer: 68, xp: 15 },
            { id: "ry2-toplama-l2-b2", type: "numeric", prompt: "12 + 23 + 14 = ?", answer: 49, xp: 15 },
            { id: "ry2-toplama-l2-b3", type: "numeric", prompt: "? + 24 = 46 — buraya hansı ədəd gəlir?", answer: 22, xp: 15 },
            { id: "ry2-toplama-l2-b4", type: "numeric", prompt: "35 + 41 = ?", answer: 76, xp: 15 },
          ],
        },
        {
          id: "ry2-toplama-l3",
          title: "Keçidli toplama",
          intro: "Təkliklərin cəmi 10-u keçəndə bir onluq yuxarı keçir.",
          sections: [
            { heading: "Keçid nədir?", body: "27 + 15: təkliklər 7 + 5 = 12. 12-nin içində BİR onluq var — onu onluqlara ötürürük. Onluqlar: 20 + 10 + 10 = 40, təklik 2 qalır. Cavab: 42." },
            { heading: "Asan yol", body: "Əvvəl 10-a tamamla: 27 + 3 = 30, sonra qalan 12-dən 3 çıxıb 12-yə çatdır... yəni 30 + 12 = 42." },
          ],
          tasks: [
            { id: "ry2-toplama-l3-t1", type: "numeric", prompt: "27 + 15 = ?", answer: 42, xp: 10 },
            { id: "ry2-toplama-l3-t2", type: "numeric", prompt: "38 + 24 = ?", answer: 62, xp: 10 },
            { id: "ry2-toplama-l3-t3", type: "numeric", prompt: "46 + 19 = ?", answer: 65, xp: 10 },
            { id: "ry2-toplama-l3-t4", type: "numeric", prompt: "55 + 28 = ?", answer: 83, xp: 10 },
            { id: "ry2-toplama-l3-t5", type: "numeric", prompt: "17 + 18 = ?", answer: 35, xp: 10 },
            { id: "ry2-toplama-l3-t6", type: "numeric", prompt: "29 + 36 = ?", answer: 65, xp: 10 },
            { id: "ry2-toplama-l3-t7", type: "numeric", prompt: "48 + 27 = ?", answer: 75, xp: 10 },
            { id: "ry2-toplama-l3-t8", type: "numeric", prompt: "9 + 8 = ?", answer: 17, xp: 10 },
            { id: "ry2-toplama-l3-t9", type: "multiple_choice", prompt: "Təkliklərin cəmi 10-u keçəndə nə baş verir?", options: ["Bir onluq yuxarı keçir", "Heç nə", "Bir onluq itir", "Cavab sıfır olur"], correctIndex: 0, xp: 10 },
            { id: "ry2-toplama-l3-t10", type: "numeric", prompt: "63 + 29 = ?", answer: 92, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-toplama-l3-b1", type: "numeric", prompt: "Kitabxanada 47 kitab var idi, 38 kitab da gətirdilər. Neçə kitab oldu?", answer: 85, xp: 15 },
            { id: "ry2-toplama-l3-b2", type: "numeric", prompt: "25 + 19 + 16 = ?", answer: 60, xp: 15 },
            { id: "ry2-toplama-l3-b3", type: "numeric", prompt: "34 + ? = 71 — buraya hansı ədəd gəlir?", answer: 37, xp: 15 },
            { id: "ry2-toplama-l3-b4", type: "numeric", prompt: "56 + 37 = ?", answer: 93, xp: 15 },
          ],
        },
        {
          id: "ry2-toplama-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-toplama-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. 100 dairəsində çıxma ═══════════════
    {
      id: "ry2-cixma",
      title: "100 dairəsində çıxma",
      description: "İkirəqəmli ədədlərdən çıxmaq.",
      lessons: [
        {
          id: "ry2-cixma-l1",
          title: "Çıxma",
          intro: "Onluqlardan onluqları, təkliklərdən təklikləri çıxırıq.",
          sections: [
            { heading: "Çıxma", body: "50 − 20 = 30 (onluqlar). 37 − 14 = 23 (təkliklər 7−4=3, onluqlar 30−10=20)." },
          ],
          tasks: [
            { id: "ry2-cixma-l1-t1", type: "numeric", prompt: "50 − 20 = ?", answer: 30, xp: 10 },
            { id: "ry2-cixma-l1-t2", type: "numeric", prompt: "60 − 40 = ?", answer: 20, xp: 10 },
            { id: "ry2-cixma-l1-t3", type: "numeric", prompt: "37 − 14 = ?", answer: 23, xp: 10 },
            { id: "ry2-cixma-l1-t4", type: "numeric", prompt: "56 − 25 = ?", answer: 31, xp: 10 },
            { id: "ry2-cixma-l1-t5", type: "numeric", prompt: "18 − 6 = ?", answer: 12, xp: 10 },
            { id: "ry2-cixma-l1-t6", type: "numeric", prompt: "49 − 4 = ?", answer: 45, xp: 10 },
            { id: "ry2-cixma-l1-t7", type: "numeric", prompt: "75 − 25 = ?", answer: 50, xp: 10 },
            { id: "ry2-cixma-l1-t8", type: "numeric", prompt: "66 − 33 = ?", answer: 33, xp: 10 },
            { id: "ry2-cixma-l1-t9", type: "numeric", prompt: "100 − 50 = ?", answer: 50, xp: 10 },
            { id: "ry2-cixma-l1-t10", type: "numeric", prompt: "29 − 12 = ?", answer: 17, xp: 10 },
            { id: "ry2-cixma-l1-t11", type: "numeric", prompt: "40 − 15 = ?", answer: 25, xp: 10 },
            { id: "ry2-cixma-l1-t12", type: "numeric", prompt: "59 − 15 = ?", answer: 44, xp: 10 },
            { id: "ry2-cixma-l1-t13", type: "numeric", prompt: "90 − 20 = ?", answer: 70, xp: 10 },
            { id: "ry2-cixma-l1-t14", type: "numeric", prompt: "48 − 12 = ?", answer: 36, xp: 10 },
            { id: "ry2-cixma-l1-t15", type: "numeric", prompt: "58 − 30 = ?", answer: 28, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-cixma-l1-b1", type: "numeric", prompt: "42 − 15 = ? (keçidli)", answer: 27, xp: 15 },
            { id: "ry2-cixma-l1-b2", type: "numeric", prompt: "74 − 26 = ?", answer: 48, xp: 15 },
            { id: "ry2-cixma-l1-b3", type: "numeric", prompt: "100 − 45 = ?", answer: 55, xp: 15 },
            { id: "ry2-cixma-l1-b4", type: "numeric", prompt: "38 − 19 = ?", answer: 19, xp: 15 },
            { id: "ry2-cixma-l1-b5", type: "numeric", prompt: "63 − 29 = ?", answer: 34, xp: 15 },
          ],
        },
        {
          id: "ry2-cixma-l2",
          title: "Keçidsiz çıxma",
          intro: "Yuxarıdakı təklik aşağıdakından böyükdürsə, çıxma asandır.",
          sections: [
            { heading: "Addımlar", body: "58 − 23: əvvəl təklikləri çıx (8 − 3 = 5), sonra onluqları (50 − 20 = 30). Cavab: 35." },
            { heading: "Yoxlama", body: "Çıxmanı toplama ilə yoxla: 35 + 23 = 58. Alınırsa, çıxma doğrudur." },
          ],
          tasks: [
            { id: "ry2-cixma-l2-t1", type: "numeric", prompt: "58 − 23 = ?", answer: 35, xp: 10 },
            { id: "ry2-cixma-l2-t2", type: "numeric", prompt: "76 − 41 = ?", answer: 35, xp: 10 },
            { id: "ry2-cixma-l2-t3", type: "numeric", prompt: "89 − 27 = ?", answer: 62, xp: 10 },
            { id: "ry2-cixma-l2-t4", type: "numeric", prompt: "45 − 12 = ?", answer: 33, xp: 10 },
            { id: "ry2-cixma-l2-t5", type: "numeric", prompt: "67 − 34 = ?", answer: 33, xp: 10 },
            { id: "ry2-cixma-l2-t6", type: "numeric", prompt: "90 − 40 = ?", answer: 50, xp: 10 },
            { id: "ry2-cixma-l2-t7", type: "numeric", prompt: "38 − 15 = ?", answer: 23, xp: 10 },
            { id: "ry2-cixma-l2-t8", type: "multiple_choice", prompt: "Çıxmanı hansı əməllə yoxlamaq olar?", options: ["Toplama", "Vurma", "Bölmə", "Müqayisə"], correctIndex: 0, xp: 10 },
            { id: "ry2-cixma-l2-t9", type: "numeric", prompt: "99 − 55 = ?", answer: 44, xp: 10 },
            { id: "ry2-cixma-l2-t10", type: "numeric", prompt: "64 − 21 = ?", answer: 43, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-cixma-l2-b1", type: "numeric", prompt: "Avtobusda 46 sərnişin var idi, 23-ü düşdü. Neçə nəfər qaldı?", answer: 23, xp: 15 },
            { id: "ry2-cixma-l2-b2", type: "numeric", prompt: "87 − 25 − 12 = ?", answer: 50, xp: 15 },
            { id: "ry2-cixma-l2-b3", type: "numeric", prompt: "? − 24 = 35 — buraya hansı ədəd gəlir?", answer: 59, xp: 15 },
            { id: "ry2-cixma-l2-b4", type: "numeric", prompt: "78 − 43 = ?", answer: 35, xp: 15 },
          ],
        },
        {
          id: "ry2-cixma-l3",
          title: "Keçidli çıxma",
          intro: "Təklik çatmayanda bir onluğu sındırıb 10 təklik alırıq.",
          sections: [
            { heading: "Onluğu sındır", body: "52 − 27: təkliklərdə 2-dən 7 çıxmır. Bir onluğu sındırırıq: 52 = 40 + 12. İndi 12 − 7 = 5, onluqlarda 40 − 20 = 20. Cavab: 25." },
            { heading: "Nə vaxt lazımdır?", body: "Yuxarıdakı təklik aşağıdakından KİÇİKDİRSƏ — onda onluq sındırılır." },
          ],
          tasks: [
            { id: "ry2-cixma-l3-t1", type: "numeric", prompt: "52 − 27 = ?", answer: 25, xp: 10 },
            { id: "ry2-cixma-l3-t2", type: "numeric", prompt: "63 − 38 = ?", answer: 25, xp: 10 },
            { id: "ry2-cixma-l3-t3", type: "numeric", prompt: "71 − 46 = ?", answer: 25, xp: 10 },
            { id: "ry2-cixma-l3-t4", type: "numeric", prompt: "40 − 18 = ?", answer: 22, xp: 10 },
            { id: "ry2-cixma-l3-t5", type: "numeric", prompt: "85 − 29 = ?", answer: 56, xp: 10 },
            { id: "ry2-cixma-l3-t6", type: "numeric", prompt: "34 − 17 = ?", answer: 17, xp: 10 },
            { id: "ry2-cixma-l3-t7", type: "numeric", prompt: "100 − 45 = ?", answer: 55, xp: 10 },
            { id: "ry2-cixma-l3-t8", type: "multiple_choice", prompt: "Onluq nə vaxt sındırılır?", options: ["Yuxarıdakı təklik kiçik olanda", "Həmişə", "Heç vaxt", "Cavab böyük olanda"], correctIndex: 0, xp: 10 },
            { id: "ry2-cixma-l3-t9", type: "numeric", prompt: "56 − 19 = ?", answer: 37, xp: 10 },
            { id: "ry2-cixma-l3-t10", type: "numeric", prompt: "92 − 58 = ?", answer: 34, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-cixma-l3-b1", type: "numeric", prompt: "Bağçada 63 ağac var idi, 28-i köçürüldü. Neçə ağac qaldı?", answer: 35, xp: 15 },
            { id: "ry2-cixma-l3-b2", type: "numeric", prompt: "80 − 35 − 16 = ?", answer: 29, xp: 15 },
            { id: "ry2-cixma-l3-b3", type: "numeric", prompt: "74 − ? = 39 — buraya hansı ədəd gəlir?", answer: 35, xp: 15 },
            { id: "ry2-cixma-l3-b4", type: "numeric", prompt: "41 + 29 − 30 = ?", answer: 40, xp: 15 },
          ],
        },
        {
          id: "ry2-cixma-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-cixma-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Vurma ═══════════════
    {
      id: "ry2-vurma",
      title: "Vurma (2, 3, 4, 5)",
      description: "Vurma cədvəlinin başlanğıcı: 2, 3, 4, 5 ilə vurma.",
      lessons: [
        {
          id: "ry2-vurma-l1",
          title: "Vurma nədir?",
          intro: "Vurma — eyni ədədin təkrar toplanmasıdır. 3 × 2 = 2 + 2 + 2 = 6.",
          sections: [
            { heading: "Vurma", body: "3 × 2 o deməkdir ki, 2-ni 3 dəfə toplayırıq: 2 + 2 + 2 = 6. Yəni 3 × 2 = 6." },
            { heading: "5 cədvəli", body: "5 × 1 = 5, 5 × 2 = 10, 5 × 3 = 15, 5 × 4 = 20, 5 × 5 = 25." },
          ],
          tasks: [
            { id: "ry2-vurma-l1-t1", type: "numeric", prompt: "2 × 2 = ?", answer: 4, xp: 10 },
            { id: "ry2-vurma-l1-t2", type: "numeric", prompt: "2 × 3 = ?", answer: 6, xp: 10 },
            { id: "ry2-vurma-l1-t3", type: "numeric", prompt: "2 × 5 = ?", answer: 10, xp: 10 },
            { id: "ry2-vurma-l1-t4", type: "numeric", prompt: "3 × 3 = ?", answer: 9, xp: 10 },
            { id: "ry2-vurma-l1-t5", type: "numeric", prompt: "3 × 4 = ?", answer: 12, xp: 10 },
            { id: "ry2-vurma-l1-t6", type: "numeric", prompt: "4 × 2 = ?", answer: 8, xp: 10 },
            { id: "ry2-vurma-l1-t7", type: "numeric", prompt: "4 × 5 = ?", answer: 20, xp: 10 },
            { id: "ry2-vurma-l1-t8", type: "numeric", prompt: "5 × 2 = ?", answer: 10, xp: 10 },
            { id: "ry2-vurma-l1-t9", type: "numeric", prompt: "5 × 5 = ?", answer: 25, xp: 10 },
            { id: "ry2-vurma-l1-t10", type: "numeric", prompt: "5 × 4 = ?", answer: 20, xp: 10 },
            { id: "ry2-vurma-l1-t11", type: "numeric", prompt: "2 + 2 + 2 + 2 neçə edir? (4 × 2)", answer: 8, xp: 10 },
            { id: "ry2-vurma-l1-t12", type: "numeric", prompt: "3 × 5 = ?", answer: 15, xp: 10 },
            { id: "ry2-vurma-l1-t13", type: "numeric", prompt: "4 × 4 = ?", answer: 16, xp: 10 },
            { id: "ry2-vurma-l1-t14", type: "numeric", prompt: "2 × 1 = ?", answer: 2, xp: 10 },
            { id: "ry2-vurma-l1-t15", type: "numeric", prompt: "5 × 3 = ?", answer: 15, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-vurma-l1-b1", type: "numeric", prompt: "5 × 6 = ?", answer: 30, xp: 15 },
            { id: "ry2-vurma-l1-b2", type: "numeric", prompt: "4 × 6 = ?", answer: 24, xp: 15 },
            { id: "ry2-vurma-l1-b3", type: "numeric", prompt: "3 × 6 = ?", answer: 18, xp: 15 },
            { id: "ry2-vurma-l1-b4", type: "numeric", prompt: "2 × 8 = ?", answer: 16, xp: 15 },
            { id: "ry2-vurma-l1-b5", type: "numeric", prompt: "Hər səbətdə 5 alma var. 3 səbətdə neçə alma var?", answer: 15, xp: 15 },
          ],
        },
        {
          id: "ry2-vurma-l2",
          title: "2 və 5 ilə vurma",
          intro: "Ən asan iki cədvəl: 2-yə vurmaq ikiqat, 5-ə vurmaq beş-beş saymaqdır.",
          sections: [
            { heading: "2 ilə vurma", body: "Bir ədədi 2-yə vurmaq — onu ÖZÜNƏ toplamaqdır. 7 × 2 = 7 + 7 = 14." },
            { heading: "5 ilə vurma", body: "5-ə vurulan ədədin sonu ya 0, ya 5 olur: 5, 10, 15, 20, 25, 30..." },
          ],
          tasks: [
            { id: "ry2-vurma-l2-t1", type: "numeric", prompt: "7 × 2 = ?", answer: 14, xp: 10 },
            { id: "ry2-vurma-l2-t2", type: "numeric", prompt: "9 × 2 = ?", answer: 18, xp: 10 },
            { id: "ry2-vurma-l2-t3", type: "numeric", prompt: "6 × 5 = ?", answer: 30, xp: 10 },
            { id: "ry2-vurma-l2-t4", type: "numeric", prompt: "8 × 5 = ?", answer: 40, xp: 10 },
            { id: "ry2-vurma-l2-t5", type: "numeric", prompt: "4 × 2 = ?", answer: 8, xp: 10 },
            { id: "ry2-vurma-l2-t6", type: "numeric", prompt: "10 × 5 = ?", answer: 50, xp: 10 },
            { id: "ry2-vurma-l2-t7", type: "numeric", prompt: "3 × 5 = ?", answer: 15, xp: 10 },
            { id: "ry2-vurma-l2-t8", type: "multiple_choice", prompt: "5-ə vurulan ədədin sonu necə olur?", options: ["0 və ya 5", "Həmişə 2", "Həmişə 1", "İstənilən rəqəm"], correctIndex: 0, xp: 10 },
            { id: "ry2-vurma-l2-t9", type: "numeric", prompt: "2 × 2 = ?", answer: 4, xp: 10 },
            { id: "ry2-vurma-l2-t10", type: "numeric", prompt: "9 × 5 = ?", answer: 45, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-vurma-l2-b1", type: "numeric", prompt: "Bir qutuda 5 alma var. 7 qutuda neçə alma var?", answer: 35, xp: 15 },
            { id: "ry2-vurma-l2-b2", type: "numeric", prompt: "2 × 8 + 5 = ?", answer: 21, xp: 15 },
            { id: "ry2-vurma-l2-b3", type: "numeric", prompt: "5 × ? = 25 — buraya hansı ədəd gəlir?", answer: 5, xp: 15 },
            { id: "ry2-vurma-l2-b4", type: "multiple_choice", prompt: "7 × 2 ilə 2 × 7 eynidirmi?", options: ["Bəli, nəticə eynidir", "Xeyr", "Yalnız kiçik ədədlərdə", "Bilmək olmur"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry2-vurma-l3",
          title: "3 və 4 ilə vurma",
          intro: "3 və 4 cədvəllərini təkrar toplama ilə öyrənək.",
          sections: [
            { heading: "3 cədvəli", body: "3, 6, 9, 12, 15, 18, 21, 24, 27, 30 — hər dəfə 3 artır." },
            { heading: "4 cədvəli", body: "4-ə vurmaq — 2-yə iki dəfə vurmaqdır. 6 × 4 = 6 × 2 × 2 = 12 × 2 = 24." },
          ],
          tasks: [
            { id: "ry2-vurma-l3-t1", type: "numeric", prompt: "4 × 3 = ?", answer: 12, xp: 10 },
            { id: "ry2-vurma-l3-t2", type: "numeric", prompt: "7 × 3 = ?", answer: 21, xp: 10 },
            { id: "ry2-vurma-l3-t3", type: "numeric", prompt: "6 × 4 = ?", answer: 24, xp: 10 },
            { id: "ry2-vurma-l3-t4", type: "numeric", prompt: "8 × 4 = ?", answer: 32, xp: 10 },
            { id: "ry2-vurma-l3-t5", type: "numeric", prompt: "9 × 3 = ?", answer: 27, xp: 10 },
            { id: "ry2-vurma-l3-t6", type: "numeric", prompt: "5 × 4 = ?", answer: 20, xp: 10 },
            { id: "ry2-vurma-l3-t7", type: "numeric", prompt: "10 × 3 = ?", answer: 30, xp: 10 },
            { id: "ry2-vurma-l3-t8", type: "numeric", prompt: "9 × 4 = ?", answer: 36, xp: 10 },
            { id: "ry2-vurma-l3-t9", type: "multiple_choice", prompt: "4-ə vurmaq nəyə bərabərdir?", options: ["2-yə iki dəfə vurmaq", "2-yə bir dəfə vurmaq", "3-ə vurmaq", "5-ə vurmaq"], correctIndex: 0, xp: 10 },
            { id: "ry2-vurma-l3-t10", type: "numeric", prompt: "3 × 3 = ?", answer: 9, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-vurma-l3-b1", type: "numeric", prompt: "Sinifdə 4 sıra var, hər sırada 6 şagird. Neçə şagird var?", answer: 24, xp: 15 },
            { id: "ry2-vurma-l3-b2", type: "numeric", prompt: "3 × 6 + 4 × 2 = ?", answer: 26, xp: 15 },
            { id: "ry2-vurma-l3-b3", type: "numeric", prompt: "4 × ? = 28 — buraya hansı ədəd gəlir?", answer: 7, xp: 15 },
            { id: "ry2-vurma-l3-b4", type: "numeric", prompt: "3 × 8 = ?", answer: 24, xp: 15 },
          ],
        },
        {
          id: "ry2-vurma-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-vurma-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Bölmə ═══════════════
    {
      id: "ry2-bolme",
      title: "Bölmə",
      description: "Bölmənin başlanğıcı: bərabər hissələrə bölmək.",
      lessons: [
        {
          id: "ry2-bolme-l1",
          title: "Bölmə nədir?",
          intro: "Bölmə — bərabər hissələrə ayırmaqdır. 6 ÷ 2 = 3.",
          sections: [
            { heading: "Bölmə", body: "6 almanı 2 uşağa bərabər paylasaq, hər biri 3 alma alır: 6 ÷ 2 = 3. Bölmə vurmanın əksidir: 2 × 3 = 6, ona görə 6 ÷ 2 = 3." },
          ],
          tasks: [
            { id: "ry2-bolme-l1-t1", type: "numeric", prompt: "6 ÷ 2 = ?", answer: 3, xp: 10 },
            { id: "ry2-bolme-l1-t2", type: "numeric", prompt: "8 ÷ 2 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l1-t3", type: "numeric", prompt: "10 ÷ 2 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l1-t4", type: "numeric", prompt: "9 ÷ 3 = ?", answer: 3, xp: 10 },
            { id: "ry2-bolme-l1-t5", type: "numeric", prompt: "12 ÷ 3 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l1-t6", type: "numeric", prompt: "12 ÷ 4 = ?", answer: 3, xp: 10 },
            { id: "ry2-bolme-l1-t7", type: "numeric", prompt: "20 ÷ 4 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l1-t8", type: "numeric", prompt: "10 ÷ 5 = ?", answer: 2, xp: 10 },
            { id: "ry2-bolme-l1-t9", type: "numeric", prompt: "25 ÷ 5 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l1-t10", type: "numeric", prompt: "20 ÷ 5 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l1-t11", type: "numeric", prompt: "4 ÷ 2 = ?", answer: 2, xp: 10 },
            { id: "ry2-bolme-l1-t12", type: "numeric", prompt: "15 ÷ 3 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l1-t13", type: "numeric", prompt: "16 ÷ 4 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l1-t14", type: "numeric", prompt: "6 almanı 3 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 2, xp: 10 },
            { id: "ry2-bolme-l1-t15", type: "numeric", prompt: "15 ÷ 5 = ?", answer: 3, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-bolme-l1-b1", type: "numeric", prompt: "30 ÷ 5 = ?", answer: 6, xp: 15 },
            { id: "ry2-bolme-l1-b2", type: "numeric", prompt: "24 ÷ 4 = ?", answer: 6, xp: 15 },
            { id: "ry2-bolme-l1-b3", type: "numeric", prompt: "18 ÷ 3 = ?", answer: 6, xp: 15 },
            { id: "ry2-bolme-l1-b4", type: "numeric", prompt: "10 konfeti 2 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 5, xp: 15 },
            { id: "ry2-bolme-l1-b5", type: "numeric", prompt: "16 ÷ 2 = ?", answer: 8, xp: 15 },
          ],
        },
        {
          id: "ry2-bolme-l2",
          title: "2 və 5-ə bölmə",
          intro: "Bərabər paylamağı öyrənək.",
          sections: [
            { heading: "2-yə bölmə", body: "2-yə bölmək — yarıya bölməkdir. 14 ÷ 2 = 7, çünki 7 + 7 = 14." },
            { heading: "5-ə bölmə", body: "20 ÷ 5 = 4, çünki 5 × 4 = 20. Bölməni həmişə vurma ilə yoxlaya bilərsən." },
          ],
          tasks: [
            { id: "ry2-bolme-l2-t1", type: "numeric", prompt: "14 ÷ 2 = ?", answer: 7, xp: 10 },
            { id: "ry2-bolme-l2-t2", type: "numeric", prompt: "18 ÷ 2 = ?", answer: 9, xp: 10 },
            { id: "ry2-bolme-l2-t3", type: "numeric", prompt: "20 ÷ 5 = ?", answer: 4, xp: 10 },
            { id: "ry2-bolme-l2-t4", type: "numeric", prompt: "35 ÷ 5 = ?", answer: 7, xp: 10 },
            { id: "ry2-bolme-l2-t5", type: "numeric", prompt: "10 ÷ 2 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l2-t6", type: "numeric", prompt: "45 ÷ 5 = ?", answer: 9, xp: 10 },
            { id: "ry2-bolme-l2-t7", type: "numeric", prompt: "16 ÷ 2 = ?", answer: 8, xp: 10 },
            { id: "ry2-bolme-l2-t8", type: "multiple_choice", prompt: "2-yə bölmək nə deməkdir?", options: ["Yarıya bölmək", "İkiqat etmək", "2 əlavə etmək", "2 çıxmaq"], correctIndex: 0, xp: 10 },
            { id: "ry2-bolme-l2-t9", type: "numeric", prompt: "25 ÷ 5 = ?", answer: 5, xp: 10 },
            { id: "ry2-bolme-l2-t10", type: "numeric", prompt: "12 ÷ 2 = ?", answer: 6, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-bolme-l2-b1", type: "numeric", prompt: "20 konfeti 5 uşağa bərabər payladıq. Hərəyə neçə düşdü?", answer: 4, xp: 15 },
            { id: "ry2-bolme-l2-b2", type: "numeric", prompt: "30 ÷ 5 + 4 = ?", answer: 10, xp: 15 },
            { id: "ry2-bolme-l2-b3", type: "numeric", prompt: "? ÷ 2 = 8 — buraya hansı ədəd gəlir?", answer: 16, xp: 15 },
            { id: "ry2-bolme-l2-b4", type: "numeric", prompt: "40 ÷ 5 = ?", answer: 8, xp: 15 },
          ],
        },
        {
          id: "ry2-bolme-l3",
          title: "Vurma və bölmə əlaqəsi",
          intro: "Vurma və bölmə bir-birinin əksidir.",
          sections: [
            { heading: "Ailə", body: "3 × 4 = 12 bilirsənsə, 12 ÷ 4 = 3 və 12 ÷ 3 = 4 də bilirsən. Bu üç fakt bir ailədir." },
            { heading: "Yoxlama", body: "Bölmənin cavabını böləni ilə vur — bölünən alınmalıdır. 18 ÷ 3 = 6, yoxlama: 6 × 3 = 18. ✓" },
          ],
          tasks: [
            { id: "ry2-bolme-l3-t1", type: "numeric", prompt: "3 × 4 = 12-dirsə, 12 ÷ 4 = ?", answer: 3, xp: 10 },
            { id: "ry2-bolme-l3-t2", type: "numeric", prompt: "18 ÷ 3 = ?", answer: 6, xp: 10 },
            { id: "ry2-bolme-l3-t3", type: "numeric", prompt: "24 ÷ 4 = ?", answer: 6, xp: 10 },
            { id: "ry2-bolme-l3-t4", type: "numeric", prompt: "27 ÷ 3 = ?", answer: 9, xp: 10 },
            { id: "ry2-bolme-l3-t5", type: "numeric", prompt: "32 ÷ 4 = ?", answer: 8, xp: 10 },
            { id: "ry2-bolme-l3-t6", type: "multiple_choice", prompt: "Bölməni hansı əməllə yoxlayırıq?", options: ["Vurma", "Toplama", "Çıxma", "Müqayisə"], correctIndex: 0, xp: 10 },
            { id: "ry2-bolme-l3-t7", type: "numeric", prompt: "21 ÷ 3 = ?", answer: 7, xp: 10 },
            { id: "ry2-bolme-l3-t8", type: "numeric", prompt: "36 ÷ 4 = ?", answer: 9, xp: 10 },
            { id: "ry2-bolme-l3-t9", type: "numeric", prompt: "9 ÷ 3 = ?", answer: 3, xp: 10 },
            { id: "ry2-bolme-l3-t10", type: "numeric", prompt: "5 × 6 = 30-dursa, 30 ÷ 6 = ?", answer: 5, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-bolme-l3-b1", type: "numeric", prompt: "24 kitabı 3 rəfə bərabər düzdük. Hər rəfdə neçə kitab var?", answer: 8, xp: 15 },
            { id: "ry2-bolme-l3-b2", type: "numeric", prompt: "4 × 5 ÷ 2 = ?", answer: 10, xp: 15 },
            { id: "ry2-bolme-l3-b3", type: "numeric", prompt: "? × 3 = 15 — buraya hansı ədəd gəlir?", answer: 5, xp: 15 },
            { id: "ry2-bolme-l3-b4", type: "multiple_choice", prompt: "0-ı istənilən ədədə bölsək nə alınır?", options: ["0", "1", "Həmin ədəd", "Alınmır"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry2-bolme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-bolme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Ölçmə, zaman, pul və fiqurlar ═══════════════
    {
      id: "ry2-olcme",
      title: "Ölçmə, zaman, pul və fiqurlar",
      description: "Uzunluq, saat, pul (qəpik/manat) və həndəsi fiqurlar.",
      lessons: [
        {
          id: "ry2-olcme-l1",
          title: "Ölçmə və zaman",
          intro: "Santimetr, saat, pul və fiqurları tanıyaq.",
          sections: [
            { heading: "Uzunluq", body: "Uzunluğu santimetr (sm) və metr (m) ilə ölçürük. 1 metr = 100 santimetr." },
            { heading: "Zaman", body: "Bir saatda 60 dəqiqə var. Bir gündə 24 saat var. Bir həftədə 7 gün var." },
            { heading: "Pul", body: "1 manat = 100 qəpik." },
          ],
          tasks: [
            { id: "ry2-olcme-l1-t1", type: "numeric", prompt: "1 metr neçə santimetrdir?", answer: 100, xp: 10 },
            { id: "ry2-olcme-l1-t2", type: "numeric", prompt: "Bir saatda neçə dəqiqə var?", answer: 60, xp: 10 },
            { id: "ry2-olcme-l1-t3", type: "numeric", prompt: "Bir gündə neçə saat var?", answer: 24, xp: 10 },
            { id: "ry2-olcme-l1-t4", type: "numeric", prompt: "Bir həftədə neçə gün var?", answer: 7, xp: 10 },
            { id: "ry2-olcme-l1-t5", type: "numeric", prompt: "1 manat neçə qəpikdir?", answer: 100, xp: 10 },
            { id: "ry2-olcme-l1-t6", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10 },
            { id: "ry2-olcme-l1-t7", type: "numeric", prompt: "2 metr neçə santimetrdir?", answer: 200, xp: 10 },
            { id: "ry2-olcme-l1-t8", type: "multiple_choice", prompt: "Kvadratın neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l1-t9", type: "multiple_choice", prompt: "Üçbucağın neçə tərəfi var?", options: ["3", "4", "5", "2"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l1-t10", type: "numeric", prompt: "İki həftədə neçə gün var? (7 + 7)", answer: 14, xp: 10 },
            { id: "ry2-olcme-l1-t11", type: "numeric", prompt: "50 qəpik + 50 qəpik neçə manatdır?", answer: 1, xp: 10 },
            { id: "ry2-olcme-l1-t12", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["kvadrat", "düzbucaqlı", "dairə", "xətt"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l1-t13", type: "numeric", prompt: "Kvadratın bir tərəfi 5 sm-dir. Perimetri neçədir? (4 tərəf)", answer: 20, xp: 10 },
            { id: "ry2-olcme-l1-t14", type: "numeric", prompt: "Səhər saat 8-də başladı, 2 saat keçdi. Saat neçədir?", answer: 10, xp: 10 },
            { id: "ry2-olcme-l1-t15", type: "numeric", prompt: "Bir ildə neçə ay var?", answer: 12, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l1-b1", type: "numeric", prompt: "3 metr neçə santimetrdir?", answer: 300, xp: 15 },
            { id: "ry2-olcme-l1-b2", type: "numeric", prompt: "İki saatda neçə dəqiqə var? (60 + 60)", answer: 120, xp: 15 },
            { id: "ry2-olcme-l1-b3", type: "numeric", prompt: "Üçbucağın hər tərəfi 4 sm-dir. Perimetri neçədir? (3 tərəf)", answer: 12, xp: 15 },
            { id: "ry2-olcme-l1-b4", type: "numeric", prompt: "70 qəpik + 30 qəpik neçə manatdır?", answer: 1, xp: 15 },
            { id: "ry2-olcme-l1-b5", type: "numeric", prompt: "Düzbucaqlının tərəfləri 3 sm və 5 sm-dir. Perimetri? (2×(3+5))", answer: 16, xp: 15 },
          ],
        },
        {
          id: "ry2-olcme-l2",
          title: "Sadə məsələlər",
          intro: "Toplama, çıxma və vurma ilə məsələ həll edək.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, hansı əməli işlədəcəyini seç, sonra hesabla." },
          ],
          tasks: [
            { id: "ry2-olcme-l2-t1", type: "numeric", prompt: "Aylının 15 stikeri var, 12 də aldı. Neçə stikeri oldu?", answer: 27, xp: 10 },
            { id: "ry2-olcme-l2-t2", type: "numeric", prompt: "Rəfdə 40 kitab var idi, 15-ni götürdük. Neçə kitab qaldı?", answer: 25, xp: 10 },
            { id: "ry2-olcme-l2-t3", type: "numeric", prompt: "Hər qutuda 5 qələm var. 4 qutuda neçə qələm var?", answer: 20, xp: 10 },
            { id: "ry2-olcme-l2-t4", type: "numeric", prompt: "12 konfeti 3 uşağa bərabər paylasaq, hər biri neçə alır?", answer: 4, xp: 10 },
            { id: "ry2-olcme-l2-t5", type: "numeric", prompt: "Bağçada 30 gül var idi, 25 də açdı. Neçə gül oldu?", answer: 55, xp: 10 },
            { id: "ry2-olcme-l2-t6", type: "numeric", prompt: "Elçinin 50 manatı var idi, 20 manat xərclədi. Neçə manatı qaldı?", answer: 30, xp: 10 },
            { id: "ry2-olcme-l2-t7", type: "numeric", prompt: "Hər masada 2 uşaq oturur. 5 masada neçə uşaq var?", answer: 10, xp: 10 },
            { id: "ry2-olcme-l2-t8", type: "numeric", prompt: "20 alma 5 səbətə bərabər paylandı. Hər səbətdə neçə alma var?", answer: 4, xp: 10 },
            { id: "ry2-olcme-l2-t9", type: "numeric", prompt: "Sinifdə 24 şagird var, 12-si qız. Neçə oğlan var?", answer: 12, xp: 10 },
            { id: "ry2-olcme-l2-t10", type: "numeric", prompt: "Hər gün 3 səhifə oxuyuram. 4 gündə neçə səhifə oxuyuram?", answer: 12, xp: 10 },
            { id: "ry2-olcme-l2-t11", type: "numeric", prompt: "35 + 40 = ? (məsələ: iki qrupun cəmi)", answer: 75, xp: 10 },
            { id: "ry2-olcme-l2-t12", type: "numeric", prompt: "Ağacda 18 quş var idi, 9-u uçdu. Neçə quş qaldı?", answer: 9, xp: 10 },
            { id: "ry2-olcme-l2-t13", type: "numeric", prompt: "Hər paketdə 4 peçenye var. 5 paketdə neçə peçenye var?", answer: 20, xp: 10 },
            { id: "ry2-olcme-l2-t14", type: "numeric", prompt: "16 oyuncaq 4 uşağa bərabər paylandı. Hər biri neçə alır?", answer: 4, xp: 10 },
            { id: "ry2-olcme-l2-t15", type: "numeric", prompt: "60 manatım var idi, 25 manat kitaba, 15 manat da çantaya verdim. Neçə manat qaldı?", answer: 20, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l2-b1", type: "numeric", prompt: "Hər həftədə 7 gün var. 3 həftədə neçə gün var?", answer: 21, xp: 15 },
            { id: "ry2-olcme-l2-b2", type: "numeric", prompt: "45 şəkil 5 albomda bərabər yerləşdi. Hər albomda neçə şəkil var?", answer: 9, xp: 15 },
            { id: "ry2-olcme-l2-b3", type: "numeric", prompt: "İki dostun birində 28, digərində 34 marka var. Cəmi neçə marka var?", answer: 62, xp: 15 },
            { id: "ry2-olcme-l2-b4", type: "numeric", prompt: "Hər qutuda 5 top var. 6 qutuda neçə top var?", answer: 30, xp: 15 },
            { id: "ry2-olcme-l2-b5", type: "numeric", prompt: "100 səhifəlik kitabın 60 səhifəsini oxudum. Neçə səhifə qaldı?", answer: 40, xp: 15 },
          ],
        },
        {
          id: "ry2-olcme-l3",
          title: "Saat və zaman",
          intro: "Saatı oxumağı və vaxtı hesablamağı öyrənək.",
          sections: [
            { heading: "Saat", body: "Bir sutkada 24 saat, bir saatda 60 dəqiqə var. Qısa əqrəb saatı, uzun əqrəb dəqiqəni göstərir." },
            { heading: "Yarım və rüb", body: "Yarım saat = 30 dəqiqə. Rüb saat = 15 dəqiqə." },
          ],
          tasks: [
            { id: "ry2-olcme-l3-t1", type: "numeric", prompt: "Bir saatda neçə dəqiqə var?", answer: 60, xp: 10 },
            { id: "ry2-olcme-l3-t2", type: "numeric", prompt: "Bir sutkada neçə saat var?", answer: 24, xp: 10 },
            { id: "ry2-olcme-l3-t3", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10 },
            { id: "ry2-olcme-l3-t4", type: "numeric", prompt: "Rüb saat neçə dəqiqədir?", answer: 15, xp: 10 },
            { id: "ry2-olcme-l3-t5", type: "numeric", prompt: "Dərs 40 dəqiqə çəkir, 15 dəqiqə keçib. Neçə dəqiqə qalıb?", answer: 25, xp: 10 },
            { id: "ry2-olcme-l3-t6", type: "numeric", prompt: "2 saat neçə dəqiqədir?", answer: 120, xp: 10 },
            { id: "ry2-olcme-l3-t7", type: "multiple_choice", prompt: "Saatda hansı əqrəb dəqiqəni göstərir?", options: ["Uzun əqrəb", "Qısa əqrəb", "Hər ikisi", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l3-t8", type: "numeric", prompt: "Bir həftədə neçə gün var?", answer: 7, xp: 10 },
            { id: "ry2-olcme-l3-t9", type: "numeric", prompt: "Bir ildə neçə ay var?", answer: 12, xp: 10 },
            { id: "ry2-olcme-l3-t10", type: "numeric", prompt: "Saat 9-dur. 3 saatdan sonra saat neçə olacaq?", answer: 12, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l3-b1", type: "numeric", prompt: "Film 90 dəqiqə çəkir. Bu, 1 saatdan neçə dəqiqə çoxdur?", answer: 30, xp: 15 },
            { id: "ry2-olcme-l3-b2", type: "numeric", prompt: "3 saat neçə dəqiqədir?", answer: 180, xp: 15 },
            { id: "ry2-olcme-l3-b3", type: "numeric", prompt: "Dərs 45 dəqiqə çəkir, tənəffüs 15 dəqiqə. İkisi birlikdə neçə dəqiqədir?", answer: 60, xp: 15 },
            { id: "ry2-olcme-l3-b4", type: "numeric", prompt: "2 həftədə neçə gün var?", answer: 14, xp: 15 },
          ],
        },
        {
          id: "ry2-olcme-l4",
          title: "Pul və fiqurlar",
          intro: "Manat, qəpik və həndəsi fiqurları tanıyaq.",
          sections: [
            { heading: "Pul", body: "1 manat = 100 qəpik. Alış-verişdə qalıq hesablamaq üçün çıxma işlədilir." },
            { heading: "Fiqurlar", body: "Kvadratın 4 bərabər tərəfi var. Düzbucaqlının qarşı tərəfləri bərabərdir. Üçbucağın 3, dairənin isə heç tərəfi yoxdur." },
          ],
          tasks: [
            { id: "ry2-olcme-l4-t1", type: "numeric", prompt: "1 manat neçə qəpikdir?", answer: 100, xp: 10 },
            { id: "ry2-olcme-l4-t2", type: "numeric", prompt: "Kvadratın neçə tərəfi var?", answer: 4, xp: 10 },
            { id: "ry2-olcme-l4-t3", type: "numeric", prompt: "Üçbucağın neçə tərəfi var?", answer: 3, xp: 10 },
            { id: "ry2-olcme-l4-t4", type: "numeric", prompt: "Çörək 80 qəpikdir. 1 manat verdin, neçə qəpik qalıq?", answer: 20, xp: 10 },
            { id: "ry2-olcme-l4-t5", type: "numeric", prompt: "2 manat neçə qəpikdir?", answer: 200, xp: 10 },
            { id: "ry2-olcme-l4-t6", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["Kvadrat", "Düzbucaqlı", "Üçbucaq", "Dairə"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l4-t7", type: "numeric", prompt: "Tərəfi 5 sm olan kvadratın perimetri neçə sm-dir?", answer: 20, xp: 10 },
            { id: "ry2-olcme-l4-t8", type: "numeric", prompt: "1 metr neçə santimetrdir?", answer: 100, xp: 10 },
            { id: "ry2-olcme-l4-t9", type: "multiple_choice", prompt: "Dairənin neçə tərəfi var?", options: ["Heç biri", "1", "2", "4"], correctIndex: 0, xp: 10 },
            { id: "ry2-olcme-l4-t10", type: "numeric", prompt: "50 qəpik + 50 qəpik neçə manatdır?", answer: 1, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry2-olcme-l4-b1", type: "numeric", prompt: "Tərəfləri 3 sm və 5 sm olan düzbucaqlının perimetri neçə sm-dir?", answer: 16, xp: 15 },
            { id: "ry2-olcme-l4-b2", type: "numeric", prompt: "3 manat 40 qəpik neçə qəpikdir?", answer: 340, xp: 15 },
            { id: "ry2-olcme-l4-b3", type: "numeric", prompt: "5 ₼-la 2 ₼-lıq dəftər aldın. Neçə manat qaldı?", answer: 3, xp: 15 },
            { id: "ry2-olcme-l4-b4", type: "numeric", prompt: "2 metr 50 santimetr neçə santimetrdir?", answer: 250, xp: 15 },
          ],
        },
        {
          id: "ry2-olcme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry2-olcme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
