// Riyaziyyat — 1-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 0-10 və sayma  2) 10 dairəsində toplama  3) 10 dairəsində çıxma
// 4) Ədədlər 11-20  5) 20 dairəsində toplama və çıxma  6) Müqayisə, fiqurlar, məsələlər.
// 1-ci sinif üçün suallar ÇOX SADƏdir (qısa mətn, rəqəm cavablar). id prefiksi ry1-*.

import type { Subject } from "../types";

export const math1: Subject = {
  slug: "riyaziyyat-1",
  name: "Riyaziyyat",
  grade: 1,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Ədədlər 0-10 və sayma ═══════════════
    {
      id: "ry1-eded10",
      title: "Ədədlər 0-10",
      description: "10-a qədər sayma, müqayisə və məşq.",
      lessons: [
        {
          id: "ry1-sayma-l1",
          title: "1-dən 10-a sayma",
          intro: "Ədədləri sıra ilə saymağı öyrənək.",
          sections: [
            { heading: "Sayma", body: "Bir, iki, üç, dörd, beş, altı, yeddi, səkkiz, doqquz, on. Rəqəmlərlə: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10." },
            { heading: "Növbəti ədəd", body: "Hər ədəddən sonra gələn ədəd 1 böyükdür: 3-dən sonra 4 gəlir." },
          ],
          tasks: [
            { id: "ry1-sayma-l1-t1", type: "numeric", prompt: "1-dən sonra hansı ədəd gəlir?", answer: 2, xp: 10 },
            { id: "ry1-sayma-l1-t2", type: "numeric", prompt: "2-dən sonra hansı ədəd gəlir?", answer: 3, xp: 10 },
            { id: "ry1-sayma-l1-t3", type: "numeric", prompt: "3-dən sonra hansı ədəd gəlir?", answer: 4, xp: 10 },
            { id: "ry1-sayma-l1-t4", type: "numeric", prompt: "4-dən sonra hansı ədəd gəlir?", answer: 5, xp: 10 },
            { id: "ry1-sayma-l1-t5", type: "numeric", prompt: "5-dən sonra hansı ədəd gəlir?", answer: 6, xp: 10 },
            { id: "ry1-sayma-l1-t6", type: "numeric", prompt: "6-dan sonra hansı ədəd gəlir?", answer: 7, xp: 10 },
            { id: "ry1-sayma-l1-t7", type: "numeric", prompt: "7-dən sonra hansı ədəd gəlir?", answer: 8, xp: 10 },
            { id: "ry1-sayma-l1-t8", type: "numeric", prompt: "8-dən sonra hansı ədəd gəlir?", answer: 9, xp: 10 },
            { id: "ry1-sayma-l1-t9", type: "numeric", prompt: "9-dan sonra hansı ədəd gəlir?", answer: 10, xp: 10 },
            { id: "ry1-sayma-l1-t10", type: "multiple_choice", prompt: "'beş' ədədi rəqəmlə necə yazılır?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l1-t11", type: "multiple_choice", prompt: "'yeddi' ədədi rəqəmlə necə yazılır?", options: ["7", "8", "6", "9"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l1-t12", type: "multiple_choice", prompt: "🍎🍎🍎 — neçə alma var?", options: ["3", "2", "4", "5"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l1-t13", type: "multiple_choice", prompt: "⭐⭐⭐⭐⭐ — neçə ulduz var?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l1-t14", type: "numeric", prompt: "Ən kiçik birrəqəmli ədəd (0-dan başqa) hansıdır?", answer: 1, xp: 10 },
            { id: "ry1-sayma-l1-t15", type: "numeric", prompt: "Ən böyük birrəqəmli ədəd hansıdır?", answer: 9, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-sayma-l1-b1", type: "multiple_choice", prompt: "🐟🐟🐟🐟 — neçə balıq var?", options: ["4", "3", "5", "6"], correctIndex: 0, xp: 15 },
            { id: "ry1-sayma-l1-b2", type: "numeric", prompt: "10-dan əvvəl gələn ədəd hansıdır?", answer: 9, xp: 15 },
            { id: "ry1-sayma-l1-b3", type: "multiple_choice", prompt: "'on' ədədi rəqəmlə necə yazılır?", options: ["10", "1", "100", "0"], correctIndex: 0, xp: 15 },
            { id: "ry1-sayma-l1-b4", type: "numeric", prompt: "6-dan əvvəl gələn ədəd hansıdır?", answer: 5, xp: 15 },
            { id: "ry1-sayma-l1-b5", type: "multiple_choice", prompt: "🎈🎈 — neçə şar var?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-sayma-l2",
          title: "Ədədləri müqayisə et",
          intro: "Hansı ədəd böyük, hansı kiçikdir?",
          sections: [
            { heading: "Böyük və kiçik", body: "Sayma sırasında sonra gələn ədəd böyükdür: 7 > 3. Əvvəl gələn kiçikdir: 3 < 7." },
          ],
          tasks: [
            { id: "ry1-sayma-l2-t1", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["7", "3", "hər ikisi bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t2", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["9", "5", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t3", type: "multiple_choice", prompt: "Hansı ədəd kiçikdir?", options: ["2", "8", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t4", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["10", "6", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t5", type: "multiple_choice", prompt: "Hansı ədəd kiçikdir?", options: ["1", "4", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t6", type: "multiple_choice", prompt: "4 və 4 — hansı böyükdür?", options: ["bərabərdir", "birinci", "ikinci", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t7", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["8", "7", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t8", type: "numeric", prompt: "3 və 6 ədədlərindən böyüyü hansıdır?", answer: 6, xp: 10 },
            { id: "ry1-sayma-l2-t9", type: "numeric", prompt: "2 və 9 ədədlərindən kiçiyi hansıdır?", answer: 2, xp: 10 },
            { id: "ry1-sayma-l2-t10", type: "numeric", prompt: "5 və 8 ədədlərindən böyüyü hansıdır?", answer: 8, xp: 10 },
            { id: "ry1-sayma-l2-t11", type: "numeric", prompt: "10 və 7 ədədlərindən böyüyü hansıdır?", answer: 10, xp: 10 },
            { id: "ry1-sayma-l2-t12", type: "numeric", prompt: "1 və 4 ədədlərindən kiçiyi hansıdır?", answer: 1, xp: 10 },
            { id: "ry1-sayma-l2-t13", type: "multiple_choice", prompt: "Hansı işarə '7 böyükdür 3' üçün düzgündür?", options: [">", "<", "=", "+"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t14", type: "multiple_choice", prompt: "Hansı işarə '2 kiçikdir 5' üçün düzgündür?", options: ["<", ">", "=", "−"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t15", type: "numeric", prompt: "6 və 9 ədədlərindən böyüyü hansıdır?", answer: 9, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-sayma-l2-b1", type: "numeric", prompt: "1, 5, 3 ədədlərindən ən böyüyü hansıdır?", answer: 5, xp: 15 },
            { id: "ry1-sayma-l2-b2", type: "numeric", prompt: "8, 2, 4 ədədlərindən ən kiçiyi hansıdır?", answer: 2, xp: 15 },
            { id: "ry1-sayma-l2-b3", type: "numeric", prompt: "7, 10, 6 ədədlərindən ən böyüyü hansıdır?", answer: 10, xp: 15 },
            { id: "ry1-sayma-l2-b4", type: "multiple_choice", prompt: "Hansı işarə '5 = 5' üçün düzgündür?", options: ["=", ">", "<", "+"], correctIndex: 0, xp: 15 },
            { id: "ry1-sayma-l2-b5", type: "numeric", prompt: "3, 9, 1, 5 ədədlərindən ən böyüyü hansıdır?", answer: 9, xp: 15 },
          ],
        },
        {
          id: "ry1-eded10-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-eded10-mesq",
          title: "Məşq",
          intro: "10-a qədər ədədləri birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Sayma: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. Böyük ədəd sağda, kiçik ədəd solda olur." },
          ],
          tasks: [
            { id: "ry1-eded10-mesq-t1", type: "numeric", prompt: "5-dən sonra hansı ədəd gəlir?", answer: 6, xp: 10 },
            { id: "ry1-eded10-mesq-t2", type: "numeric", prompt: "8-dən əvvəl hansı ədəd gəlir?", answer: 7, xp: 10 },
            { id: "ry1-eded10-mesq-t3", type: "numeric", prompt: "🐤🐤🐤🐤 — neçə cücə var?", answer: 4, xp: 10 },
            { id: "ry1-eded10-mesq-t4", type: "numeric", prompt: "🌸🌸🌸🌸🌸🌸 — neçə gül var?", answer: 6, xp: 10 },
            { id: "ry1-eded10-mesq-t5", type: "multiple_choice", prompt: "Hansı daha böyükdür?", options: ["9", "4", "2", "0"], correctIndex: 0, xp: 10 },
            { id: "ry1-eded10-mesq-t6", type: "multiple_choice", prompt: "Hansı daha kiçikdir?", options: ["1", "5", "8", "10"], correctIndex: 0, xp: 10 },
            { id: "ry1-eded10-mesq-t7", type: "numeric", prompt: "10-dan əvvəl hansı ədəd gəlir?", answer: 9, xp: 10 },
            { id: "ry1-eded10-mesq-t8", type: "multiple_choice", prompt: "'üç' ədədi rəqəmlə necə yazılır?", options: ["3", "5", "2", "8"], correctIndex: 0, xp: 10 },
            { id: "ry1-eded10-mesq-t9", type: "numeric", prompt: "Ən böyük birrəqəmli ədəd hansıdır?", answer: 9, xp: 10 },
            { id: "ry1-eded10-mesq-t10", type: "multiple_choice", prompt: "6 və 3 — hansı böyükdür?", options: ["6", "3", "bərabərdir", "bilinmir"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-eded10-mesq-b1", type: "numeric", prompt: "2, 4, 6, ... — növbəti ədəd?", answer: 8, xp: 15 },
            { id: "ry1-eded10-mesq-b2", type: "numeric", prompt: "10, 9, 8, ... — növbəti ədəd?", answer: 7, xp: 15 },
            { id: "ry1-eded10-mesq-b3", type: "multiple_choice", prompt: "Hansı sıra düzgündür?", options: ["1, 2, 3, 4", "4, 2, 1, 3", "2, 1, 4, 3", "3, 4, 2, 1"], correctIndex: 0, xp: 15 },
            { id: "ry1-eded10-mesq-b4", type: "numeric", prompt: "🍏🍏🍏 və 🍏🍏 — cəmi neçə alma?", answer: 5, xp: 15 },
            { id: "ry1-eded10-mesq-b5", type: "numeric", prompt: "0-dan 5-ə qədər neçə ədəd var? (0 da daxil)", answer: 6, xp: 15 },
          ],
        },
        {
          id: "ry1-eded10-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-hesab10",
      title: "10 dairəsində toplama və çıxma",
      description: "10-a qədər toplama, çıxma və məşq.",
      lessons: [
        {
          id: "ry1-toplama-l1",
          title: "Kiçik ədədləri topla",
          intro: "Toplama — birləşdirmək deməkdir. 2 + 3 = 5.",
          sections: [
            { heading: "Toplama", body: "İki qrupu birləşdirəndə toplama edirik: 🍎🍎 + 🍎🍎🍎 = 5 alma. Yəni 2 + 3 = 5." },
          ],
          tasks: [
            { id: "ry1-toplama-l1-t1", type: "numeric", prompt: "1 + 1 = ?", answer: 2, xp: 10 },
            { id: "ry1-toplama-l1-t2", type: "numeric", prompt: "2 + 1 = ?", answer: 3, xp: 10 },
            { id: "ry1-toplama-l1-t3", type: "numeric", prompt: "2 + 2 = ?", answer: 4, xp: 10 },
            { id: "ry1-toplama-l1-t4", type: "numeric", prompt: "3 + 1 = ?", answer: 4, xp: 10 },
            { id: "ry1-toplama-l1-t5", type: "numeric", prompt: "2 + 3 = ?", answer: 5, xp: 10 },
            { id: "ry1-toplama-l1-t6", type: "numeric", prompt: "3 + 2 = ?", answer: 5, xp: 10 },
            { id: "ry1-toplama-l1-t7", type: "numeric", prompt: "1 + 4 = ?", answer: 5, xp: 10 },
            { id: "ry1-toplama-l1-t8", type: "numeric", prompt: "3 + 3 = ?", answer: 6, xp: 10 },
            { id: "ry1-toplama-l1-t9", type: "numeric", prompt: "4 + 2 = ?", answer: 6, xp: 10 },
            { id: "ry1-toplama-l1-t10", type: "numeric", prompt: "5 + 1 = ?", answer: 6, xp: 10 },
            { id: "ry1-toplama-l1-t11", type: "numeric", prompt: "0 + 4 = ?", answer: 4, xp: 10 },
            { id: "ry1-toplama-l1-t12", type: "numeric", prompt: "2 + 0 = ?", answer: 2, xp: 10 },
            { id: "ry1-toplama-l1-t13", type: "multiple_choice", prompt: "🍎🍎 + 🍎 = ?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 10 },
            { id: "ry1-toplama-l1-t14", type: "multiple_choice", prompt: "⭐⭐⭐ + ⭐⭐ = ?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10 },
            { id: "ry1-toplama-l1-t15", type: "numeric", prompt: "4 + 1 = ?", answer: 5, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-toplama-l1-b1", type: "numeric", prompt: "3 + 0 = ?", answer: 3, xp: 15 },
            { id: "ry1-toplama-l1-b2", type: "numeric", prompt: "1 + 1 + 1 = ?", answer: 3, xp: 15 },
            { id: "ry1-toplama-l1-b3", type: "numeric", prompt: "2 + 2 + 1 = ?", answer: 5, xp: 15 },
            { id: "ry1-toplama-l1-b4", type: "multiple_choice", prompt: "🐟🐟🐟 + 🐟 = ?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15 },
            { id: "ry1-toplama-l1-b5", type: "numeric", prompt: "0 + 0 = ?", answer: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-toplama-l2",
          title: "10-a qədər topla",
          intro: "Cəmi 10-a qədər olan toplamalar.",
          sections: [
            { heading: "Böyük cəm", body: "Ədədləri topla, cəm 10-a qədər ola bilər: 6 + 4 = 10, 7 + 2 = 9." },
          ],
          tasks: [
            { id: "ry1-toplama-l2-t1", type: "numeric", prompt: "5 + 2 = ?", answer: 7, xp: 10 },
            { id: "ry1-toplama-l2-t2", type: "numeric", prompt: "4 + 3 = ?", answer: 7, xp: 10 },
            { id: "ry1-toplama-l2-t3", type: "numeric", prompt: "6 + 2 = ?", answer: 8, xp: 10 },
            { id: "ry1-toplama-l2-t4", type: "numeric", prompt: "5 + 3 = ?", answer: 8, xp: 10 },
            { id: "ry1-toplama-l2-t5", type: "numeric", prompt: "4 + 4 = ?", answer: 8, xp: 10 },
            { id: "ry1-toplama-l2-t6", type: "numeric", prompt: "7 + 2 = ?", answer: 9, xp: 10 },
            { id: "ry1-toplama-l2-t7", type: "numeric", prompt: "6 + 3 = ?", answer: 9, xp: 10 },
            { id: "ry1-toplama-l2-t8", type: "numeric", prompt: "5 + 4 = ?", answer: 9, xp: 10 },
            { id: "ry1-toplama-l2-t9", type: "numeric", prompt: "5 + 5 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t10", type: "numeric", prompt: "6 + 4 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t11", type: "numeric", prompt: "7 + 3 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t12", type: "numeric", prompt: "8 + 2 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t13", type: "numeric", prompt: "9 + 1 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t14", type: "numeric", prompt: "8 + 1 = ?", answer: 9, xp: 10 },
            { id: "ry1-toplama-l2-t15", type: "numeric", prompt: "7 + 1 = ?", answer: 8, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-toplama-l2-b1", type: "numeric", prompt: "3 + 3 + 4 = ?", answer: 10, xp: 15 },
            { id: "ry1-toplama-l2-b2", type: "numeric", prompt: "2 + 4 + 4 = ?", answer: 10, xp: 15 },
            { id: "ry1-toplama-l2-b3", type: "multiple_choice", prompt: "6-ya nə əlavə etsək 10 alınar?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15 },
            { id: "ry1-toplama-l2-b4", type: "multiple_choice", prompt: "7-yə nə əlavə etsək 10 alınar?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 15 },
            { id: "ry1-toplama-l2-b5", type: "numeric", prompt: "5 + 2 + 3 = ?", answer: 10, xp: 15 },
          ],
        },
        {
          id: "ry1-cixma-l1",
          title: "Kiçik çıxma",
          intro: "Çıxma — azaltmaq deməkdir. 5 − 2 = 3.",
          sections: [
            { heading: "Çıxma", body: "Bir qrupdan bir neçəsini götürəndə çıxma edirik: 🍎🍎🍎🍎🍎 -dən 2 alma götürsək 3 qalır. Yəni 5 − 2 = 3." },
          ],
          tasks: [
            { id: "ry1-cixma-l1-t1", type: "numeric", prompt: "2 − 1 = ?", answer: 1, xp: 10 },
            { id: "ry1-cixma-l1-t2", type: "numeric", prompt: "3 − 1 = ?", answer: 2, xp: 10 },
            { id: "ry1-cixma-l1-t3", type: "numeric", prompt: "3 − 2 = ?", answer: 1, xp: 10 },
            { id: "ry1-cixma-l1-t4", type: "numeric", prompt: "4 − 1 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l1-t5", type: "numeric", prompt: "4 − 2 = ?", answer: 2, xp: 10 },
            { id: "ry1-cixma-l1-t6", type: "numeric", prompt: "5 − 2 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l1-t7", type: "numeric", prompt: "5 − 3 = ?", answer: 2, xp: 10 },
            { id: "ry1-cixma-l1-t8", type: "numeric", prompt: "5 − 1 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l1-t9", type: "numeric", prompt: "6 − 2 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l1-t10", type: "numeric", prompt: "6 − 3 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l1-t11", type: "numeric", prompt: "4 − 4 = ?", answer: 0, xp: 10 },
            { id: "ry1-cixma-l1-t12", type: "numeric", prompt: "3 − 0 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l1-t13", type: "multiple_choice", prompt: "⭐⭐⭐⭐ -dən 1 götürsək neçə qalır?", options: ["3", "4", "2", "5"], correctIndex: 0, xp: 10 },
            { id: "ry1-cixma-l1-t14", type: "multiple_choice", prompt: "🍎🍎🍎🍎🍎 -dən 2 götürsək neçə qalır?", options: ["3", "2", "4", "5"], correctIndex: 0, xp: 10 },
            { id: "ry1-cixma-l1-t15", type: "numeric", prompt: "6 − 1 = ?", answer: 5, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-cixma-l1-b1", type: "numeric", prompt: "5 − 5 = ?", answer: 0, xp: 15 },
            { id: "ry1-cixma-l1-b2", type: "numeric", prompt: "6 − 4 = ?", answer: 2, xp: 15 },
            { id: "ry1-cixma-l1-b3", type: "numeric", prompt: "6 − 5 = ?", answer: 1, xp: 15 },
            { id: "ry1-cixma-l1-b4", type: "numeric", prompt: "4 − 3 = ?", answer: 1, xp: 15 },
            { id: "ry1-cixma-l1-b5", type: "numeric", prompt: "5 − 0 = ?", answer: 5, xp: 15 },
          ],
        },
        {
          id: "ry1-cixma-l2",
          title: "10-dan çıxma",
          intro: "Böyük ədədlərdən çıxma.",
          sections: [
            { heading: "10-dan çıx", body: "10-dan çıxma: 10 − 4 = 6, 10 − 7 = 3. 8, 9-dan da çıx: 9 − 3 = 6." },
          ],
          tasks: [
            { id: "ry1-cixma-l2-t1", type: "numeric", prompt: "7 − 2 = ?", answer: 5, xp: 10 },
            { id: "ry1-cixma-l2-t2", type: "numeric", prompt: "7 − 3 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l2-t3", type: "numeric", prompt: "8 − 2 = ?", answer: 6, xp: 10 },
            { id: "ry1-cixma-l2-t4", type: "numeric", prompt: "8 − 4 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l2-t5", type: "numeric", prompt: "9 − 3 = ?", answer: 6, xp: 10 },
            { id: "ry1-cixma-l2-t6", type: "numeric", prompt: "9 − 5 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l2-t7", type: "numeric", prompt: "10 − 1 = ?", answer: 9, xp: 10 },
            { id: "ry1-cixma-l2-t8", type: "numeric", prompt: "10 − 2 = ?", answer: 8, xp: 10 },
            { id: "ry1-cixma-l2-t9", type: "numeric", prompt: "10 − 5 = ?", answer: 5, xp: 10 },
            { id: "ry1-cixma-l2-t10", type: "numeric", prompt: "10 − 4 = ?", answer: 6, xp: 10 },
            { id: "ry1-cixma-l2-t11", type: "numeric", prompt: "10 − 7 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l2-t12", type: "numeric", prompt: "10 − 10 = ?", answer: 0, xp: 10 },
            { id: "ry1-cixma-l2-t13", type: "numeric", prompt: "8 − 3 = ?", answer: 5, xp: 10 },
            { id: "ry1-cixma-l2-t14", type: "numeric", prompt: "9 − 4 = ?", answer: 5, xp: 10 },
            { id: "ry1-cixma-l2-t15", type: "numeric", prompt: "10 − 6 = ?", answer: 4, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-cixma-l2-b1", type: "numeric", prompt: "10 − 8 = ?", answer: 2, xp: 15 },
            { id: "ry1-cixma-l2-b2", type: "numeric", prompt: "9 − 9 = ?", answer: 0, xp: 15 },
            { id: "ry1-cixma-l2-b3", type: "multiple_choice", prompt: "10-dan nə çıxsaq 3 qalar?", options: ["7", "6", "8", "5"], correctIndex: 0, xp: 15 },
            { id: "ry1-cixma-l2-b4", type: "numeric", prompt: "8 − 6 = ?", answer: 2, xp: 15 },
            { id: "ry1-cixma-l2-b5", type: "numeric", prompt: "10 − 3 = ?", answer: 7, xp: 15 },
          ],
        },
        {
          id: "ry1-hesab10-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-hesab10-mesq",
          title: "Məşq",
          intro: "Toplama və çıxmanı birlikdə məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "Toplama (+) artırır: 3 + 2 = 5. Çıxma (−) azaldır: 5 − 2 = 3." },
          ],
          tasks: [
            { id: "ry1-hesab10-mesq-t1", type: "numeric", prompt: "4 + 3 = ?", answer: 7, xp: 10 },
            { id: "ry1-hesab10-mesq-t2", type: "numeric", prompt: "6 + 2 = ?", answer: 8, xp: 10 },
            { id: "ry1-hesab10-mesq-t3", type: "numeric", prompt: "9 − 4 = ?", answer: 5, xp: 10 },
            { id: "ry1-hesab10-mesq-t4", type: "numeric", prompt: "7 − 3 = ?", answer: 4, xp: 10 },
            { id: "ry1-hesab10-mesq-t5", type: "numeric", prompt: "5 + 5 = ?", answer: 10, xp: 10 },
            { id: "ry1-hesab10-mesq-t6", type: "numeric", prompt: "10 − 6 = ?", answer: 4, xp: 10 },
            { id: "ry1-hesab10-mesq-t7", type: "numeric", prompt: "Nərgizin 3 şarı var idi, 2 şar da aldı. İndi neçə şarı var?", answer: 5, xp: 10 },
            { id: "ry1-hesab10-mesq-t8", type: "numeric", prompt: "Budaqda 8 quş var idi, 3-ü uçdu. Neçə quş qaldı?", answer: 5, xp: 10 },
            { id: "ry1-hesab10-mesq-t9", type: "numeric", prompt: "2 + 2 + 2 = ?", answer: 6, xp: 10 },
            { id: "ry1-hesab10-mesq-t10", type: "numeric", prompt: "10 − 5 = ?", answer: 5, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-hesab10-mesq-b1", type: "numeric", prompt: "3 + ? = 9", answer: 6, xp: 15 },
            { id: "ry1-hesab10-mesq-b2", type: "numeric", prompt: "? − 4 = 3", answer: 7, xp: 15 },
            { id: "ry1-hesab10-mesq-b3", type: "numeric", prompt: "Anar 4 konfet yedi, 4 konfeti də qaldı. Əvvəlcə neçə konfeti var idi?", answer: 8, xp: 15 },
            { id: "ry1-hesab10-mesq-b4", type: "numeric", prompt: "6 + 4 − 2 = ?", answer: 8, xp: 15 },
            { id: "ry1-hesab10-mesq-b5", type: "numeric", prompt: "10 − 3 − 3 = ?", answer: 4, xp: 15 },
          ],
        },
        {
          id: "ry1-hesab10-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-eded20",
      title: "Ədədlər 11-20",
      description: "11-20 arası ədədlər, toplama və çıxma.",
      lessons: [
        {
          id: "ry1-onluq-l1",
          title: "11-dən 20-yə sayma",
          intro: "On birdən iyirmiyə qədər sayaq.",
          sections: [
            { heading: "Sayma", body: "11, 12, 13, 14, 15, 16, 17, 18, 19, 20. Bu ədədlər 'on' və bir rəqəmdən ibarətdir: on bir = 11, on beş = 15." },
          ],
          tasks: [
            { id: "ry1-onluq-l1-t1", type: "numeric", prompt: "11-dən sonra hansı ədəd gəlir?", answer: 12, xp: 10 },
            { id: "ry1-onluq-l1-t2", type: "numeric", prompt: "12-dən sonra hansı ədəd gəlir?", answer: 13, xp: 10 },
            { id: "ry1-onluq-l1-t3", type: "numeric", prompt: "14-dən sonra hansı ədəd gəlir?", answer: 15, xp: 10 },
            { id: "ry1-onluq-l1-t4", type: "numeric", prompt: "15-dən sonra hansı ədəd gəlir?", answer: 16, xp: 10 },
            { id: "ry1-onluq-l1-t5", type: "numeric", prompt: "19-dan sonra hansı ədəd gəlir?", answer: 20, xp: 10 },
            { id: "ry1-onluq-l1-t6", type: "multiple_choice", prompt: "'on bir' ədədi rəqəmlə necə yazılır?", options: ["11", "10", "12", "1"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t7", type: "multiple_choice", prompt: "'on beş' ədədi rəqəmlə necə yazılır?", options: ["15", "50", "14", "16"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t8", type: "multiple_choice", prompt: "'iyirmi' ədədi rəqəmlə necə yazılır?", options: ["20", "12", "2", "200"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t9", type: "numeric", prompt: "13-dən əvvəl gələn ədəd hansıdır?", answer: 12, xp: 10 },
            { id: "ry1-onluq-l1-t10", type: "numeric", prompt: "16-dan əvvəl gələn ədəd hansıdır?", answer: 15, xp: 10 },
            { id: "ry1-onluq-l1-t11", type: "numeric", prompt: "20-dən əvvəl gələn ədəd hansıdır?", answer: 19, xp: 10 },
            { id: "ry1-onluq-l1-t12", type: "multiple_choice", prompt: "13 və 17 ədədlərindən böyüyü hansıdır?", options: ["17", "13", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t13", type: "multiple_choice", prompt: "11 və 15 ədədlərindən kiçiyi hansıdır?", options: ["11", "15", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t14", type: "numeric", prompt: "17-dən sonra hansı ədəd gəlir?", answer: 18, xp: 10 },
            { id: "ry1-onluq-l1-t15", type: "numeric", prompt: "10-dan sonra hansı ədəd gəlir?", answer: 11, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-onluq-l1-b1", type: "numeric", prompt: "14, 18, 12 ədədlərindən ən böyüyü hansıdır?", answer: 18, xp: 15 },
            { id: "ry1-onluq-l1-b2", type: "numeric", prompt: "16, 11, 19 ədədlərindən ən kiçiyi hansıdır?", answer: 11, xp: 15 },
            { id: "ry1-onluq-l1-b3", type: "multiple_choice", prompt: "15 ədədi neçə onluq və neçə təkdən ibarətdir?", options: ["1 onluq 5 tək", "5 onluq 1 tək", "15 tək", "2 onluq"], correctIndex: 0, xp: 15 },
            { id: "ry1-onluq-l1-b4", type: "numeric", prompt: "18-dən əvvəl gələn ədəd hansıdır?", answer: 17, xp: 15 },
            { id: "ry1-onluq-l1-b5", type: "numeric", prompt: "12 və 20 arasında 15-dən 1 böyük ədəd hansıdır?", answer: 16, xp: 15 },
          ],
        },
        {
          id: "ry1-yirmi-l1",
          title: "10-dan yuxarı toplama",
          intro: "10-a bir neçə əlavə edək.",
          sections: [
            { heading: "10 + tək", body: "10 + 3 = 13, 10 + 5 = 15. Onluğa təkləri əlavə edirik." },
          ],
          tasks: [
            { id: "ry1-yirmi-l1-t1", type: "numeric", prompt: "10 + 1 = ?", answer: 11, xp: 10 },
            { id: "ry1-yirmi-l1-t2", type: "numeric", prompt: "10 + 2 = ?", answer: 12, xp: 10 },
            { id: "ry1-yirmi-l1-t3", type: "numeric", prompt: "10 + 3 = ?", answer: 13, xp: 10 },
            { id: "ry1-yirmi-l1-t4", type: "numeric", prompt: "10 + 5 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l1-t5", type: "numeric", prompt: "10 + 7 = ?", answer: 17, xp: 10 },
            { id: "ry1-yirmi-l1-t6", type: "numeric", prompt: "10 + 9 = ?", answer: 19, xp: 10 },
            { id: "ry1-yirmi-l1-t7", type: "numeric", prompt: "11 + 2 = ?", answer: 13, xp: 10 },
            { id: "ry1-yirmi-l1-t8", type: "numeric", prompt: "12 + 3 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l1-t9", type: "numeric", prompt: "13 + 2 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l1-t10", type: "numeric", prompt: "14 + 3 = ?", answer: 17, xp: 10 },
            { id: "ry1-yirmi-l1-t11", type: "numeric", prompt: "15 + 4 = ?", answer: 19, xp: 10 },
            { id: "ry1-yirmi-l1-t12", type: "numeric", prompt: "16 + 2 = ?", answer: 18, xp: 10 },
            { id: "ry1-yirmi-l1-t13", type: "numeric", prompt: "18 + 2 = ?", answer: 20, xp: 10 },
            { id: "ry1-yirmi-l1-t14", type: "numeric", prompt: "10 + 10 = ?", answer: 20, xp: 10 },
            { id: "ry1-yirmi-l1-t15", type: "numeric", prompt: "17 + 2 = ?", answer: 19, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-yirmi-l1-b1", type: "numeric", prompt: "11 + 5 = ?", answer: 16, xp: 15 },
            { id: "ry1-yirmi-l1-b2", type: "numeric", prompt: "13 + 4 = ?", answer: 17, xp: 15 },
            { id: "ry1-yirmi-l1-b3", type: "numeric", prompt: "15 + 5 = ?", answer: 20, xp: 15 },
            { id: "ry1-yirmi-l1-b4", type: "numeric", prompt: "12 + 6 = ?", answer: 18, xp: 15 },
            { id: "ry1-yirmi-l1-b5", type: "numeric", prompt: "16 + 3 = ?", answer: 19, xp: 15 },
          ],
        },
        {
          id: "ry1-yirmi-l2",
          title: "20 dairəsində çıxma",
          intro: "20-yə qədər ədədlərdən çıxaq.",
          sections: [
            { heading: "Çıxma", body: "13 − 3 = 10, 15 − 5 = 10, 20 − 10 = 10. Əvvəlcə təkləri çıxırıq." },
          ],
          tasks: [
            { id: "ry1-yirmi-l2-t1", type: "numeric", prompt: "12 − 2 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t2", type: "numeric", prompt: "13 − 3 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t3", type: "numeric", prompt: "15 − 5 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t4", type: "numeric", prompt: "11 − 1 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t5", type: "numeric", prompt: "14 − 2 = ?", answer: 12, xp: 10 },
            { id: "ry1-yirmi-l2-t6", type: "numeric", prompt: "16 − 3 = ?", answer: 13, xp: 10 },
            { id: "ry1-yirmi-l2-t7", type: "numeric", prompt: "18 − 4 = ?", answer: 14, xp: 10 },
            { id: "ry1-yirmi-l2-t8", type: "numeric", prompt: "19 − 5 = ?", answer: 14, xp: 10 },
            { id: "ry1-yirmi-l2-t9", type: "numeric", prompt: "20 − 10 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t10", type: "numeric", prompt: "17 − 2 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l2-t11", type: "numeric", prompt: "20 − 5 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l2-t12", type: "numeric", prompt: "15 − 3 = ?", answer: 12, xp: 10 },
            { id: "ry1-yirmi-l2-t13", type: "numeric", prompt: "13 − 1 = ?", answer: 12, xp: 10 },
            { id: "ry1-yirmi-l2-t14", type: "numeric", prompt: "20 − 1 = ?", answer: 19, xp: 10 },
            { id: "ry1-yirmi-l2-t15", type: "numeric", prompt: "16 − 6 = ?", answer: 10, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-yirmi-l2-b1", type: "numeric", prompt: "18 − 8 = ?", answer: 10, xp: 15 },
            { id: "ry1-yirmi-l2-b2", type: "numeric", prompt: "20 − 3 = ?", answer: 17, xp: 15 },
            { id: "ry1-yirmi-l2-b3", type: "numeric", prompt: "17 − 4 = ?", answer: 13, xp: 15 },
            { id: "ry1-yirmi-l2-b4", type: "numeric", prompt: "19 − 9 = ?", answer: 10, xp: 15 },
            { id: "ry1-yirmi-l2-b5", type: "numeric", prompt: "14 − 4 = ?", answer: 10, xp: 15 },
          ],
        },
        {
          id: "ry1-eded20-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-eded20-mesq",
          title: "Məşq",
          intro: "20-yə qədər ədədləri məşq edək!",
          sections: [
            { heading: "Yadına salaq", body: "11, 12, 13 ... 20. Onluqdan sonra: 10 + 3 = 13. Ədədin birinci rəqəmi onluğu, ikincisi təkliyi göstərir." },
          ],
          tasks: [
            { id: "ry1-eded20-mesq-t1", type: "numeric", prompt: "13-dən sonra hansı ədəd gəlir?", answer: 14, xp: 10 },
            { id: "ry1-eded20-mesq-t2", type: "numeric", prompt: "17-dən əvvəl hansı ədəd gəlir?", answer: 16, xp: 10 },
            { id: "ry1-eded20-mesq-t3", type: "numeric", prompt: "10 + 5 = ?", answer: 15, xp: 10 },
            { id: "ry1-eded20-mesq-t4", type: "numeric", prompt: "10 + 8 = ?", answer: 18, xp: 10 },
            { id: "ry1-eded20-mesq-t5", type: "numeric", prompt: "12 + 3 = ?", answer: 15, xp: 10 },
            { id: "ry1-eded20-mesq-t6", type: "numeric", prompt: "16 − 4 = ?", answer: 12, xp: 10 },
            { id: "ry1-eded20-mesq-t7", type: "numeric", prompt: "20 − 10 = ?", answer: 10, xp: 10 },
            { id: "ry1-eded20-mesq-t8", type: "multiple_choice", prompt: "Hansı daha böyükdür?", options: ["18", "15", "12", "11"], correctIndex: 0, xp: 10 },
            { id: "ry1-eded20-mesq-t9", type: "numeric", prompt: "19-dan sonra hansı ədəd gəlir?", answer: 20, xp: 10 },
            { id: "ry1-eded20-mesq-t10", type: "numeric", prompt: "14 + 5 = ?", answer: 19, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-eded20-mesq-b1", type: "numeric", prompt: "11, 13, 15, ... — növbəti ədəd?", answer: 17, xp: 15 },
            { id: "ry1-eded20-mesq-b2", type: "numeric", prompt: "10 + ? = 17", answer: 7, xp: 15 },
            { id: "ry1-eded20-mesq-b3", type: "numeric", prompt: "Sinifdə 12 oğlan, 6 qız var. Cəmi neçə şagird var?", answer: 18, xp: 15 },
            { id: "ry1-eded20-mesq-b4", type: "numeric", prompt: "20 − 5 − 5 = ?", answer: 10, xp: 15 },
            { id: "ry1-eded20-mesq-b5", type: "numeric", prompt: "15 ədədində neçə onluq var?", answer: 1, xp: 15 },
          ],
        },
        {
          id: "ry1-eded20-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-fiqur",
      title: "Fiqurlar və məsələlər",
      description: "Həndəsi fiqurlar və sadə mətn məsələləri.",
      lessons: [
        {
          id: "ry1-fiqur-l1",
          title: "Həndəsi fiqurlar",
          intro: "Dairə, kvadrat, üçbucaq, düzbucaqlını tanıyaq.",
          sections: [
            { heading: "Fiqurlar", body: "Dairə — dəyirmi (top kimi). Kvadrat — 4 bərabər tərəf. Üçbucaq — 3 tərəf. Düzbucaqlı — 4 tərəf (2-si uzun)." },
          ],
          tasks: [
            { id: "ry1-fiqur-l1-t1", type: "multiple_choice", prompt: "Üçbucağın neçə tərəfi var?", options: ["3", "4", "2", "5"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t2", type: "multiple_choice", prompt: "Kvadratın neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t3", type: "multiple_choice", prompt: "Dəyirmi (top kimi) fiqur necə adlanır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t4", type: "multiple_choice", prompt: "🔺 hansı fiqurdur?", options: ["üçbucaq", "kvadrat", "dairə", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t5", type: "multiple_choice", prompt: "⬛ hansı fiqurdur?", options: ["kvadrat", "dairə", "üçbucaq", "xətt"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t6", type: "multiple_choice", prompt: "🔵 hansı fiqurdur?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t7", type: "multiple_choice", prompt: "Dairənin neçə küncü var?", options: ["0 (küncü yoxdur)", "3", "4", "1"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t8", type: "multiple_choice", prompt: "Kvadratın neçə küncü var?", options: ["4", "3", "2", "0"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t9", type: "multiple_choice", prompt: "Üçbucağın neçə küncü var?", options: ["3", "4", "2", "0"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t10", type: "multiple_choice", prompt: "Top hansı fiqura oxşayır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t11", type: "multiple_choice", prompt: "Kitab hansı fiqura oxşayır?", options: ["düzbucaqlı", "dairə", "üçbucaq", "top"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t12", type: "multiple_choice", prompt: "Düzbucaqlının neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t13", type: "numeric", prompt: "Kvadratın neçə tərəfi var? (rəqəmlə)", answer: 4, xp: 10 },
            { id: "ry1-fiqur-l1-t14", type: "numeric", prompt: "Üçbucağın neçə küncü var? (rəqəmlə)", answer: 3, xp: 10 },
            { id: "ry1-fiqur-l1-t15", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["kvadrat", "düzbucaqlı", "dairə", "xətt"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-fiqur-l1-b1", type: "numeric", prompt: "Bir üçbucaq və bir kvadratın tərəflərinin cəmi neçədir? (3 + 4)", answer: 7, xp: 15 },
            { id: "ry1-fiqur-l1-b2", type: "multiple_choice", prompt: "Günəş hansı fiqura oxşayır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 15 },
            { id: "ry1-fiqur-l1-b3", type: "numeric", prompt: "İki üçbucağın tərəflərinin cəmi neçədir? (3 + 3)", answer: 6, xp: 15 },
            { id: "ry1-fiqur-l1-b4", type: "multiple_choice", prompt: "Dam (ev üstü) çox vaxt hansı fiqura oxşayır?", options: ["üçbucaq", "dairə", "kvadrat", "düzbucaqlı"], correctIndex: 0, xp: 15 },
            { id: "ry1-fiqur-l1-b5", type: "numeric", prompt: "İki kvadratın tərəflərinin cəmi neçədir? (4 + 4)", answer: 8, xp: 15 },
          ],
        },
        {
          id: "ry1-fiqur-l2",
          title: "Sadə mətn məsələləri",
          intro: "Kiçik məsələləri toplama və çıxma ilə həll edək.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, sonra topla və ya çıx. Məs.: 'Aylının 3 alması var, 2 də aldı. Neçə alması oldu?' → 3 + 2 = 5." },
          ],
          tasks: [
            { id: "ry1-fiqur-l2-t1", type: "numeric", prompt: "Aylının 3 alması var, 2 də aldı. Neçə alması oldu?", answer: 5, xp: 10 },
            { id: "ry1-fiqur-l2-t2", type: "numeric", prompt: "Budaqda 5 quş var idi, 2-si uçdu. Neçə quş qaldı?", answer: 3, xp: 10 },
            { id: "ry1-fiqur-l2-t3", type: "numeric", prompt: "Nərminin 4 şarı var, 1-i partladı. Neçə şar qaldı?", answer: 3, xp: 10 },
            { id: "ry1-fiqur-l2-t4", type: "numeric", prompt: "Səbətdə 2 armud var, 3 də əlavə etdik. Neçə armud oldu?", answer: 5, xp: 10 },
            { id: "ry1-fiqur-l2-t5", type: "numeric", prompt: "Elçinin 6 karandaşı var, 2-sini dostuna verdi. Neçə qaldı?", answer: 4, xp: 10 },
            { id: "ry1-fiqur-l2-t6", type: "numeric", prompt: "Bağçada 4 gül var idi, 4 də açdı. Neçə gül oldu?", answer: 8, xp: 10 },
            { id: "ry1-fiqur-l2-t7", type: "numeric", prompt: "Rəfdə 7 kitab var idi, 3-nü götürdük. Neçə kitab qaldı?", answer: 4, xp: 10 },
            { id: "ry1-fiqur-l2-t8", type: "numeric", prompt: "Leylanın 5 konfeti var, 3 də aldı. Neçə konfeti oldu?", answer: 8, xp: 10 },
            { id: "ry1-fiqur-l2-t9", type: "numeric", prompt: "Hovuzda 6 balıq var idi, 2 də əlavə etdik. Neçə balıq oldu?", answer: 8, xp: 10 },
            { id: "ry1-fiqur-l2-t10", type: "numeric", prompt: "Sinifdə 10 uşaq var idi, 4-ü evə getdi. Neçə uşaq qaldı?", answer: 6, xp: 10 },
            { id: "ry1-fiqur-l2-t11", type: "numeric", prompt: "Anarın 2 maşını var, atası 2 də aldı. Neçə maşını oldu?", answer: 4, xp: 10 },
            { id: "ry1-fiqur-l2-t12", type: "numeric", prompt: "Ağacda 8 alma var idi, 5-i düşdü. Neçə alma qaldı?", answer: 3, xp: 10 },
            { id: "ry1-fiqur-l2-t13", type: "numeric", prompt: "Zərifənin 3 dəftəri var, 4 də aldı. Neçə dəftəri oldu?", answer: 7, xp: 10 },
            { id: "ry1-fiqur-l2-t14", type: "numeric", prompt: "Qutuda 9 top var idi, 3-nü çıxartdıq. Neçə top qaldı?", answer: 6, xp: 10 },
            { id: "ry1-fiqur-l2-t15", type: "numeric", prompt: "Kaminin 5 balonu var, 5 də aldı. Neçə balonu oldu?", answer: 10, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-fiqur-l2-b1", type: "numeric", prompt: "Bağda 10 armud var idi, 6-sını yığdıq. Neçə armud qaldı?", answer: 4, xp: 15 },
            { id: "ry1-fiqur-l2-b2", type: "numeric", prompt: "Tünelin 7 daşı var, 3 də əlavə etdi, sonra 2-sini götürdü. Neçə daş qaldı?", answer: 8, xp: 15 },
            { id: "ry1-fiqur-l2-b3", type: "numeric", prompt: "İki dostun hərəsində 5 stiker var. Cəmi neçə stiker var?", answer: 10, xp: 15 },
            { id: "ry1-fiqur-l2-b4", type: "numeric", prompt: "Nənənin 12 yumurtası var idi, 2-si sındı. Neçə yumurta qaldı?", answer: 10, xp: 15 },
            { id: "ry1-fiqur-l2-b5", type: "numeric", prompt: "Meşədə 8 dovşan var idi, 4 də gəldi. Neçə dovşan oldu?", answer: 12, xp: 15 },
          ],
        },
        {
          id: "ry1-fiqur-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-fiqur-mesq",
          title: "Məşq",
          intro: "Fiqurları tanı və məsələləri həll et!",
          sections: [
            { heading: "Yadına salaq", body: "Kvadrat — 4 bərabər tərəf. Üçbucaq — 3 tərəf. Dairə — tərəfi yoxdur. Düzbucaqlı — 4 tərəf, qarşı tərəflər bərabər." },
          ],
          tasks: [
            { id: "ry1-fiqur-mesq-t1", type: "numeric", prompt: "Üçbucağın neçə tərəfi var?", answer: 3, xp: 10 },
            { id: "ry1-fiqur-mesq-t2", type: "numeric", prompt: "Kvadratın neçə tərəfi var?", answer: 4, xp: 10 },
            { id: "ry1-fiqur-mesq-t3", type: "multiple_choice", prompt: "Hansı fiqurun küncü yoxdur?", options: ["Dairə", "Kvadrat", "Üçbucaq", "Düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-mesq-t4", type: "multiple_choice", prompt: "Top hansı fiqura oxşayır?", options: ["Dairə", "Kvadrat", "Üçbucaq", "Düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-mesq-t5", type: "numeric", prompt: "Leyla 5 kitab oxudu, Aysel 3 kitab. Cəmi neçə kitab oxudular?", answer: 8, xp: 10 },
            { id: "ry1-fiqur-mesq-t6", type: "numeric", prompt: "Ağacda 9 alma var idi, 4-ü düşdü. Neçə alma qaldı?", answer: 5, xp: 10 },
            { id: "ry1-fiqur-mesq-t7", type: "numeric", prompt: "Kvadratın bir tərəfi 2 sm-dir. Bütün tərəflərin cəmi neçə sm-dir?", answer: 8, xp: 10 },
            { id: "ry1-fiqur-mesq-t8", type: "multiple_choice", prompt: "Pəncərə adətən hansı fiqura oxşayır?", options: ["Düzbucaqlı", "Dairə", "Üçbucaq", "Ulduz"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-mesq-t9", type: "numeric", prompt: "Tuncay 7 şəkil çəkdi, 2-ni dostuna verdi. Neçə şəkli qaldı?", answer: 5, xp: 10 },
            { id: "ry1-fiqur-mesq-t10", type: "numeric", prompt: "İki üçbucağın cəmi neçə tərəfi var?", answer: 6, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-fiqur-mesq-b1", type: "numeric", prompt: "Bir kvadrat və bir üçbucağın cəmi neçə tərəfi var?", answer: 7, xp: 15 },
            { id: "ry1-fiqur-mesq-b2", type: "numeric", prompt: "Anarın 6 maşını var idi, 3 maşın da aldı, sonra 2-ni bağışladı. İndi neçə maşını var?", answer: 7, xp: 15 },
            { id: "ry1-fiqur-mesq-b3", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["Kvadrat", "Düzbucaqlı", "Dairə", "Heç biri"], correctIndex: 0, xp: 15 },
            { id: "ry1-fiqur-mesq-b4", type: "numeric", prompt: "Səbətdə 10 armud var idi. Səhər 3, axşam 2 armud yedik. Neçə armud qaldı?", answer: 5, xp: 15 },
            { id: "ry1-fiqur-mesq-b5", type: "numeric", prompt: "Üç dairənin cəmi neçə küncü var?", answer: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-fiqur-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-olcme",
      title: "Ölçmə və müqayisə",
      description: "Uzun-qısa, ağır-yüngül, çox-az — əşyaları müqayisə etmək.",
      lessons: [
        {
          id: "ry1-olcme-l1",
          title: "Uzun və qısa",
          intro: "Hansı uzundur, hansı qısa?",
          sections: [
            { heading: "Müqayisə", body: "İki əşyanı yan-yana qoyub baxırıq: qələm karandaşdan uzundur." },
            { heading: "Sözlər", body: "uzun — qısa, hündür — alçaq, geniş — dar." },
          ],
          tasks: [
            { id: "ry1-olcme-l1-t1", type: "multiple_choice", prompt: "Hansı adətən daha UZUNDUR?", options: ["Qatar", "Avtobus", "Velosiped", "Kitab"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l1-t2", type: "multiple_choice", prompt: "Hansı adətən daha QISADIR?", options: ["Karandaş", "Ağac", "Küçə", "Çay"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l1-t3", type: "multiple_choice", prompt: "'uzun' sözünün əksi hansıdır?", options: ["qısa", "hündür", "geniş", "böyük"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l1-t4", type: "multiple_choice", prompt: "Hansı daha HÜNDÜRDÜR?", options: ["Ağac", "Ot", "Gül", "Daş"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l1-t5", type: "multiple_choice", prompt: "'hündür' sözünün əksi hansıdır?", options: ["alçaq", "uzun", "geniş", "böyük"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l1-t6", type: "numeric", prompt: "3 sm və 7 sm — hansı daha uzundur? (rəqəmi yaz)", answer: 7, xp: 10 },
            { id: "ry1-olcme-l1-t7", type: "multiple_choice", prompt: "Hansı daha GENİŞDİR?", options: ["Yol", "Cığır", "İp", "Tel"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l1-t8", type: "numeric", prompt: "5 sm və 2 sm — hansı daha qısadır? (rəqəmi yaz)", answer: 2, xp: 10 },
            { id: "ry1-olcme-l1-t9", type: "multiple_choice", prompt: "Uzunluğu nə ilə ölçürük?", options: ["Xətkeşlə", "Tərəzi ilə", "Saatla", "Stəkanla"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l1-t10", type: "multiple_choice", prompt: "Hansı daha BÖYÜKDÜR?", options: ["Fil", "Pişik", "Siçan", "Qarışqa"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-olcme-l1-b1", type: "numeric", prompt: "4 sm, 9 sm, 6 sm — ən uzunu neçə sm-dir?", answer: 9, xp: 15 },
            { id: "ry1-olcme-l1-b2", type: "multiple_choice", prompt: "Bir metr neçə santimetrdir?", options: ["100", "10", "50", "1000"], correctIndex: 0, xp: 15 },
            { id: "ry1-olcme-l1-b3", type: "multiple_choice", prompt: "Hansı sıra kiçikdən böyüyə düzülüb?", options: ["qarışqa, pişik, fil", "fil, pişik, qarışqa", "pişik, qarışqa, fil", "fil, qarışqa, pişik"], correctIndex: 0, xp: 15 },
            { id: "ry1-olcme-l1-b4", type: "numeric", prompt: "10 sm-dən 3 sm qısa neçə sm-dir?", answer: 7, xp: 15 },
          ],
        },
        {
          id: "ry1-olcme-l2",
          title: "Ağır və yüngül",
          intro: "Hansı ağırdır?",
          sections: [
            { heading: "Çəki", body: "Ağır əşyanı qaldırmaq çətindir. Daş yüngül deyil, lələk yüngüldür." },
            { heading: "Ölçmək", body: "Çəkini TƏRƏZİ ilə ölçürük. Vahid — qram və kiloqram." },
          ],
          tasks: [
            { id: "ry1-olcme-l2-t1", type: "multiple_choice", prompt: "Hansı daha AĞIRDIR?", options: ["Daş", "Lələk", "Kağız", "Yarpaq"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l2-t2", type: "multiple_choice", prompt: "Hansı daha YÜNGÜLDÜR?", options: ["Lələk", "Kitab", "Kərpic", "Su qabı"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l2-t3", type: "multiple_choice", prompt: "Çəkini nə ilə ölçürük?", options: ["Tərəzi ilə", "Xətkeşlə", "Saatla", "Termometrlə"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l2-t4", type: "numeric", prompt: "1 kiloqram neçə qramdır?", answer: 1000, xp: 10 },
            { id: "ry1-olcme-l2-t5", type: "multiple_choice", prompt: "'ağır' sözünün əksi hansıdır?", options: ["yüngül", "böyük", "uzun", "dolu"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l2-t6", type: "multiple_choice", prompt: "Hansı daha ağırdır: 1 kq pambıq, yoxsa 1 kq dəmir?", options: ["Bərabərdir", "Dəmir", "Pambıq", "Bilmək olmur"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l2-t7", type: "multiple_choice", prompt: "Hansı ən ağırdır?", options: ["Avtomobil", "Velosiped", "Top", "Qələm"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l2-t8", type: "numeric", prompt: "2 kiloqram neçə qramdır?", answer: 2000, xp: 10 },
            { id: "ry1-olcme-l2-t9", type: "multiple_choice", prompt: "Çəki vahidi hansıdır?", options: ["Kiloqram", "Metr", "Saat", "Litr"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l2-t10", type: "multiple_choice", prompt: "Boş çanta ilə dolu çanta — hansı ağırdır?", options: ["Dolu", "Boş", "Bərabər", "Bilmək olmur"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-olcme-l2-b1", type: "numeric", prompt: "500 qram + 500 qram neçə kiloqramdır?", answer: 1, xp: 15 },
            { id: "ry1-olcme-l2-b2", type: "multiple_choice", prompt: "Maye nə ilə ölçülür?", options: ["Litrlə", "Kiloqramla", "Metrlə", "Saatla"], correctIndex: 0, xp: 15 },
            { id: "ry1-olcme-l2-b3", type: "numeric", prompt: "3 kq − 1 kq = ? (kq ilə)", answer: 2, xp: 15 },
            { id: "ry1-olcme-l2-b4", type: "multiple_choice", prompt: "Hansı sıra yüngüldən ağıra düzülüb?", options: ["lələk, kitab, daş", "daş, kitab, lələk", "kitab, lələk, daş", "daş, lələk, kitab"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-olcme-l3",
          title: "Çox və az",
          intro: "Hansı qrupda daha çox var?",
          sections: [
            { heading: "Saymaqla", body: "İki qrupu sayıb müqayisə edirik: 5 alma 3 armuddan çoxdur." },
            { heading: "İşarələr", body: "> böyükdür, < kiçikdir, = bərabərdir." },
          ],
          tasks: [
            { id: "ry1-olcme-l3-t1", type: "numeric", prompt: "5 alma və 3 armud — neçə alma çoxdur?", answer: 2, xp: 10 },
            { id: "ry1-olcme-l3-t2", type: "multiple_choice", prompt: "7 və 4 — hansı çoxdur?", options: ["7", "4", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l3-t3", type: "multiple_choice", prompt: "2 və 9 — hansı azdır?", options: ["2", "9", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l3-t4", type: "numeric", prompt: "6 və 6 — fərq neçədir?", answer: 0, xp: 10 },
            { id: "ry1-olcme-l3-t5", type: "multiple_choice", prompt: "8 ... 5 — hansı işarə düzgündür?", options: [">", "<", "=", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l3-t6", type: "multiple_choice", prompt: "3 ... 3 — hansı işarə düzgündür?", options: ["=", ">", "<", "Heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l3-t7", type: "numeric", prompt: "9 quşdan 4-ü uçdu. Neçə quş qaldı?", answer: 5, xp: 10 },
            { id: "ry1-olcme-l3-t8", type: "numeric", prompt: "4 və 7 — fərq neçədir?", answer: 3, xp: 10 },
            { id: "ry1-olcme-l3-t9", type: "multiple_choice", prompt: "'çox' sözünün əksi hansıdır?", options: ["az", "böyük", "uzun", "ağır"], correctIndex: 0, xp: 10 },
            { id: "ry1-olcme-l3-t10", type: "numeric", prompt: "10 və 3 — hansı böyükdür? (rəqəmi yaz)", answer: 10, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-olcme-l3-b1", type: "numeric", prompt: "Səbətdə 8 alma var idi, 3-ü yeyildi, sonra 2 əlavə olundu. Neçə alma var?", answer: 7, xp: 15 },
            { id: "ry1-olcme-l3-b2", type: "multiple_choice", prompt: "1, 5, 3, 9 — ən böyüyü hansıdır?", options: ["9", "5", "3", "1"], correctIndex: 0, xp: 15 },
            { id: "ry1-olcme-l3-b3", type: "numeric", prompt: "7-dən neçə az 4-dür?", answer: 3, xp: 15 },
            { id: "ry1-olcme-l3-b4", type: "multiple_choice", prompt: "Hansı sıra böyükdən kiçiyə düzülüb?", options: ["9, 6, 3", "3, 6, 9", "6, 3, 9", "3, 9, 6"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-olcme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-olcme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    {
      id: "ry1-zaman",
      title: "Zaman və pul",
      description: "Gün, həftə, saat və qəpik-manatı tanımaq.",
      lessons: [
        {
          id: "ry1-zaman-l1",
          title: "Gün və həftə",
          intro: "Səhər, günorta, axşam, gecə.",
          sections: [
            { heading: "Gün hissələri", body: "Səhər qalxırıq, günorta nahar edirik, axşam evə qayıdırıq, gecə yatırıq." },
            { heading: "Həftə", body: "Həftədə 7 gün var: bazar, bazar ertəsi, çərşənbə axşamı, çərşənbə, cümə axşamı, cümə, şənbə." },
          ],
          tasks: [
            { id: "ry1-zaman-l1-t1", type: "numeric", prompt: "Həftədə neçə gün var?", answer: 7, xp: 10 },
            { id: "ry1-zaman-l1-t2", type: "multiple_choice", prompt: "Nə vaxt yatırıq?", options: ["Gecə", "Səhər", "Günorta", "Həmişə"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l1-t3", type: "multiple_choice", prompt: "Nə vaxt məktəbə gedirik?", options: ["Səhər", "Gecə", "Gecə yarısı", "Heç vaxt"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l1-t4", type: "multiple_choice", prompt: "Bazar ertəsindən sonra hansı gün gəlir?", options: ["Çərşənbə axşamı", "Bazar", "Cümə", "Şənbə"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l1-t5", type: "numeric", prompt: "Bir ildə neçə ay var?", answer: 12, xp: 10 },
            { id: "ry1-zaman-l1-t6", type: "multiple_choice", prompt: "Günün ilk hissəsi hansıdır?", options: ["Səhər", "Axşam", "Gecə", "Günorta"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l1-t7", type: "numeric", prompt: "İki həftədə neçə gün var?", answer: 14, xp: 10 },
            { id: "ry1-zaman-l1-t8", type: "multiple_choice", prompt: "Nahar nə vaxt edilir?", options: ["Günorta", "Gecə", "Səhər tezdən", "Gecə yarısı"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l1-t9", type: "multiple_choice", prompt: "Fəsillər neçədir?", options: ["4", "2", "3", "12"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l1-t10", type: "numeric", prompt: "Bir gündə neçə saat var?", answer: 24, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-zaman-l1-b1", type: "numeric", prompt: "3 həftədə neçə gün var?", answer: 21, xp: 15 },
            { id: "ry1-zaman-l1-b2", type: "multiple_choice", prompt: "Hansı fəsildə qar yağır?", options: ["Qış", "Yay", "Yaz", "Payız"], correctIndex: 0, xp: 15 },
            { id: "ry1-zaman-l1-b3", type: "numeric", prompt: "Həftənin 5 iş günü var. Neçə istirahət günü qalır?", answer: 2, xp: 15 },
            { id: "ry1-zaman-l1-b4", type: "multiple_choice", prompt: "Yaz fəslindən sonra hansı fəsil gəlir?", options: ["Yay", "Qış", "Payız", "Yaz"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-zaman-l2",
          title: "Saatı tanı",
          intro: "Qısa əqrəb saatı göstərir.",
          sections: [
            { heading: "Əqrəblər", body: "Saatda iki əqrəb var: QISA əqrəb saatı, UZUN əqrəb dəqiqəni göstərir." },
            { heading: "Tam saat", body: "Uzun əqrəb 12-nin üstündədirsə, saat tamdır: 3 tamam, 7 tamam." },
          ],
          tasks: [
            { id: "ry1-zaman-l2-t1", type: "multiple_choice", prompt: "Qısa əqrəb nəyi göstərir?", options: ["Saatı", "Dəqiqəni", "Saniyəni", "Günü"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l2-t2", type: "multiple_choice", prompt: "Uzun əqrəb nəyi göstərir?", options: ["Dəqiqəni", "Saatı", "Günü", "Ayı"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l2-t3", type: "numeric", prompt: "Saat 3-dür. 2 saatdan sonra saat neçə olacaq?", answer: 5, xp: 10 },
            { id: "ry1-zaman-l2-t4", type: "numeric", prompt: "Saat 8-dir. 1 saat əvvəl saat neçə idi?", answer: 7, xp: 10 },
            { id: "ry1-zaman-l2-t5", type: "numeric", prompt: "Bir saatda neçə dəqiqə var?", answer: 60, xp: 10 },
            { id: "ry1-zaman-l2-t6", type: "multiple_choice", prompt: "Uzun əqrəb 12-nin üstündədirsə saat necədir?", options: ["Tamdır", "Yarımdır", "Rübdür", "Bilinmir"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l2-t7", type: "numeric", prompt: "Saat 10-dur. 3 saatdan sonra saat neçə olacaq?", answer: 13, xp: 10 },
            { id: "ry1-zaman-l2-t8", type: "numeric", prompt: "Saat 6-dır. 2 saat əvvəl saat neçə idi?", answer: 4, xp: 10 },
            { id: "ry1-zaman-l2-t9", type: "multiple_choice", prompt: "Saatda neçə əqrəb var (əsas)?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l2-t10", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-zaman-l2-b1", type: "numeric", prompt: "Dərs saat 9-da başladı, 1 saat çəkdi. Saat neçədə bitdi?", answer: 10, xp: 15 },
            { id: "ry1-zaman-l2-b2", type: "numeric", prompt: "Səhər 7-dən axşam 7-yə qədər neçə saat keçir?", answer: 12, xp: 15 },
            { id: "ry1-zaman-l2-b3", type: "multiple_choice", prompt: "Gecə yarısı saat neçədir?", options: ["12", "6", "3", "9"], correctIndex: 0, xp: 15 },
            { id: "ry1-zaman-l2-b4", type: "numeric", prompt: "2 saat neçə dəqiqədir?", answer: 120, xp: 15 },
          ],
        },
        {
          id: "ry1-zaman-l3",
          title: "Pulu tanı",
          intro: "Qəpik və manat.",
          sections: [
            { heading: "Pulumuz", body: "Azərbaycanın pulu MANATDIR. Bir manatda 100 qəpik var." },
            { heading: "Alış-veriş", body: "Alanda pul veririk, artıq qalarsa qalıq alırıq." },
          ],
          tasks: [
            { id: "ry1-zaman-l3-t1", type: "numeric", prompt: "1 manat neçə qəpikdir?", answer: 100, xp: 10 },
            { id: "ry1-zaman-l3-t2", type: "multiple_choice", prompt: "Azərbaycanın pulu necə adlanır?", options: ["Manat", "Dollar", "Avro", "Rubl"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l3-t3", type: "numeric", prompt: "50 qəpik + 50 qəpik neçə manatdır?", answer: 1, xp: 10 },
            { id: "ry1-zaman-l3-t4", type: "numeric", prompt: "2 manat neçə qəpikdir?", answer: 200, xp: 10 },
            { id: "ry1-zaman-l3-t5", type: "numeric", prompt: "Çörək 1 manatdır. 2 manat verdin, neçə manat qalıq?", answer: 1, xp: 10 },
            { id: "ry1-zaman-l3-t6", type: "numeric", prompt: "20 qəpik + 30 qəpik neçə qəpikdir?", answer: 50, xp: 10 },
            { id: "ry1-zaman-l3-t7", type: "multiple_choice", prompt: "Hansı daha çoxdur: 1 manat, yoxsa 50 qəpik?", options: ["1 manat", "50 qəpik", "Bərabərdir", "Bilmək olmur"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l3-t8", type: "numeric", prompt: "3 manat + 2 manat = ? (manat)", answer: 5, xp: 10 },
            { id: "ry1-zaman-l3-t9", type: "multiple_choice", prompt: "Pul nə üçün lazımdır?", options: ["Lazım olanı almaq üçün", "Oynamaq üçün", "Rəsm çəkmək üçün", "Heç nə üçün"], correctIndex: 0, xp: 10 },
            { id: "ry1-zaman-l3-t10", type: "numeric", prompt: "5 manatdan 2 manat xərclədin. Neçə manat qaldı?", answer: 3, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry1-zaman-l3-b1", type: "numeric", prompt: "10 qəpiklik 10 ədəd sikkə neçə manat edir?", answer: 1, xp: 15 },
            { id: "ry1-zaman-l3-b2", type: "numeric", prompt: "Şirniyyat 80 qəpikdir. 1 manat verdin, neçə qəpik qalıq?", answer: 20, xp: 15 },
            { id: "ry1-zaman-l3-b3", type: "numeric", prompt: "2 manat 50 qəpik neçə qəpikdir?", answer: 250, xp: 15 },
            { id: "ry1-zaman-l3-b4", type: "multiple_choice", prompt: "Pulu haradan qazanırıq?", options: ["İşləməklə", "Oyundan", "Yuxudan", "Heç yerdən"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-zaman-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry1-zaman-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
