// Riyaziyyat — 3-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 1000-ə qədər  2) Toplama və çıxma  3) Vurma cədvəli
// 4) Bölmə  5) Kəsrlər  6) Həndəsə, ölçmə və məsələlər.
// 3-cü sinif üçün sadə (rəqəm cavablar). id prefiksi ry3-*.

import type { Subject } from "../types";

export const math3: Subject = {
  slug: "riyaziyyat-3",
  name: "Riyaziyyat",
  grade: 3,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Ədədlər 1000-ə qədər ═══════════════
    {
      id: "ry3-min",
      title: "Ədədlər 1000-ə qədər",
      description: "Üçrəqəmli ədədləri oxumaq, yazmaq, mərtəbələrə ayırmaq və müqayisə etmək.",
      lessons: [
        {
          id: "ry3-min-l1",
          title: "Üçrəqəmli ədədlər",
          intro: "Yüzlük, onluq və təkliklər.",
          sections: [
            { heading: "Mərtəbələr", body: "Üçrəqəmli ədəd yüzlük, onluq və təklikdən ibarətdir. 345 = 3 yüzlük + 4 onluq + 5 təklik." },
            { heading: "Sıra", body: "Ən kiçik üçrəqəmli ədəd 100, ən böyüyü 999-dur. 999-dan sonra 1000 gəlir." },
          ],
          tasks: [
            { id: "ry3-min-l1-t1", type: "numeric", prompt: "345 ədədində neçə yüzlük var?", answer: 3, xp: 10 },
            { id: "ry3-min-l1-t2", type: "numeric", prompt: "345 ədədində neçə onluq var?", answer: 4, xp: 10 },
            { id: "ry3-min-l1-t3", type: "numeric", prompt: "345 ədədində neçə təklik var?", answer: 5, xp: 10 },
            { id: "ry3-min-l1-t4", type: "numeric", prompt: "2 yüzlük + 5 onluq + 3 təklik = ?", answer: 253, xp: 10 },
            { id: "ry3-min-l1-t5", type: "numeric", prompt: "5 yüzlük = ?", answer: 500, xp: 10 },
            { id: "ry3-min-l1-t6", type: "numeric", prompt: "Ən kiçik üçrəqəmli ədəd hansıdır?", answer: 100, xp: 10 },
            { id: "ry3-min-l1-t7", type: "numeric", prompt: "Ən böyük üçrəqəmli ədəd hansıdır?", answer: 999, xp: 10 },
            { id: "ry3-min-l1-t8", type: "numeric", prompt: "999-dan sonra hansı ədəd gəlir?", answer: 1000, xp: 10 },
            { id: "ry3-min-l1-t9", type: "numeric", prompt: "300-dən əvvəl gələn ədəd hansıdır?", answer: 299, xp: 10 },
            { id: "ry3-min-l1-t10", type: "multiple_choice", prompt: "456 və 465 ədədlərindən böyüyü hansıdır?", options: ["465", "456", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry3-min-l1-t11", type: "multiple_choice", prompt: "700 və 699 ədədlərindən böyüyü hansıdır?", options: ["700", "699", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry3-min-l1-t12", type: "numeric", prompt: "'beş yüz altmış' ədədi rəqəmlə necə yazılır?", answer: 560, xp: 10 },
            { id: "ry3-min-l1-t13", type: "numeric", prompt: "4 yüzlük + 0 onluq + 7 təklik = ?", answer: 407, xp: 10 },
            { id: "ry3-min-l1-t14", type: "numeric", prompt: "1 yüzlük neçə təklikdir?", answer: 100, xp: 10 },
            { id: "ry3-min-l1-t15", type: "numeric", prompt: "'doqquz yüz' ədədi rəqəmlə necə yazılır?", answer: 900, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry3-min-l1-b1", type: "numeric", prompt: "6 yüzlük + 6 onluq + 6 təklik = ?", answer: 666, xp: 15 },
            { id: "ry3-min-l1-b2", type: "numeric", prompt: "1000 ədədində neçə yüzlük var?", answer: 10, xp: 15 },
            { id: "ry3-min-l1-b3", type: "multiple_choice", prompt: "234, 243, 324 — ən böyüyü hansıdır?", options: ["324", "243", "234", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "ry3-min-l1-b4", type: "numeric", prompt: "'yeddi yüz doqquz' ədədi rəqəmlə necə yazılır?", answer: 709, xp: 15 },
            { id: "ry3-min-l1-b5", type: "numeric", prompt: "500-dən sonra gələn 3-cü ədəd hansıdır?", answer: 503, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 2. Toplama və çıxma ═══════════════
    {
      id: "ry3-toplama",
      title: "1000 dairəsində toplama və çıxma",
      description: "Üçrəqəmli ədədləri toplamaq və çıxmaq.",
      lessons: [
        {
          id: "ry3-toplama-l1",
          title: "Toplama və çıxma",
          intro: "Mərtəbələrə görə toplayıb çıxırıq.",
          sections: [
            { heading: "Toplama", body: "200 + 300 = 500. 234 + 145 = 379 (təkliklər, onluqlar, yüzlüklər)." },
            { heading: "Çıxma", body: "500 − 200 = 300. 379 − 145 = 234." },
          ],
          tasks: [
            { id: "ry3-toplama-l1-t1", type: "numeric", prompt: "200 + 300 = ?", answer: 500, xp: 10 },
            { id: "ry3-toplama-l1-t2", type: "numeric", prompt: "400 + 500 = ?", answer: 900, xp: 10 },
            { id: "ry3-toplama-l1-t3", type: "numeric", prompt: "234 + 145 = ?", answer: 379, xp: 10 },
            { id: "ry3-toplama-l1-t4", type: "numeric", prompt: "312 + 256 = ?", answer: 568, xp: 10 },
            { id: "ry3-toplama-l1-t5", type: "numeric", prompt: "500 − 200 = ?", answer: 300, xp: 10 },
            { id: "ry3-toplama-l1-t6", type: "numeric", prompt: "900 − 400 = ?", answer: 500, xp: 10 },
            { id: "ry3-toplama-l1-t7", type: "numeric", prompt: "379 − 145 = ?", answer: 234, xp: 10 },
            { id: "ry3-toplama-l1-t8", type: "numeric", prompt: "568 − 256 = ?", answer: 312, xp: 10 },
            { id: "ry3-toplama-l1-t9", type: "numeric", prompt: "150 + 150 = ?", answer: 300, xp: 10 },
            { id: "ry3-toplama-l1-t10", type: "numeric", prompt: "600 + 250 = ?", answer: 850, xp: 10 },
            { id: "ry3-toplama-l1-t11", type: "numeric", prompt: "750 − 300 = ?", answer: 450, xp: 10 },
            { id: "ry3-toplama-l1-t12", type: "numeric", prompt: "125 + 125 = ?", answer: 250, xp: 10 },
            { id: "ry3-toplama-l1-t13", type: "numeric", prompt: "1000 − 500 = ?", answer: 500, xp: 10 },
            { id: "ry3-toplama-l1-t14", type: "numeric", prompt: "430 + 270 = ?", answer: 700, xp: 10 },
            { id: "ry3-toplama-l1-t15", type: "numeric", prompt: "820 − 420 = ?", answer: 400, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry3-toplama-l1-b1", type: "numeric", prompt: "345 + 278 = ?", answer: 623, xp: 15 },
            { id: "ry3-toplama-l1-b2", type: "numeric", prompt: "700 − 265 = ?", answer: 435, xp: 15 },
            { id: "ry3-toplama-l1-b3", type: "numeric", prompt: "456 + 544 = ?", answer: 1000, xp: 15 },
            { id: "ry3-toplama-l1-b4", type: "numeric", prompt: "1000 − 375 = ?", answer: 625, xp: 15 },
            { id: "ry3-toplama-l1-b5", type: "numeric", prompt: "289 + 311 = ?", answer: 600, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 3. Vurma cədvəli ═══════════════
    {
      id: "ry3-vurma",
      title: "Vurma cədvəli (1-9)",
      description: "Vurma cədvəlini tam öyrənmək (2-dən 9-a qədər).",
      lessons: [
        {
          id: "ry3-vurma-l1",
          title: "Vurma cədvəli",
          intro: "Bütün vurma cədvəlini məşq edək.",
          sections: [
            { heading: "6, 7, 8, 9 cədvəli", body: "6 × 7 = 42, 7 × 8 = 56, 8 × 9 = 72, 9 × 9 = 81. Cədvəli yadda saxlamaq vacibdir." },
          ],
          tasks: [
            { id: "ry3-vurma-l1-t1", type: "numeric", prompt: "6 × 6 = ?", answer: 36, xp: 10 },
            { id: "ry3-vurma-l1-t2", type: "numeric", prompt: "6 × 7 = ?", answer: 42, xp: 10 },
            { id: "ry3-vurma-l1-t3", type: "numeric", prompt: "7 × 7 = ?", answer: 49, xp: 10 },
            { id: "ry3-vurma-l1-t4", type: "numeric", prompt: "7 × 8 = ?", answer: 56, xp: 10 },
            { id: "ry3-vurma-l1-t5", type: "numeric", prompt: "8 × 8 = ?", answer: 64, xp: 10 },
            { id: "ry3-vurma-l1-t6", type: "numeric", prompt: "8 × 9 = ?", answer: 72, xp: 10 },
            { id: "ry3-vurma-l1-t7", type: "numeric", prompt: "9 × 9 = ?", answer: 81, xp: 10 },
            { id: "ry3-vurma-l1-t8", type: "numeric", prompt: "6 × 8 = ?", answer: 48, xp: 10 },
            { id: "ry3-vurma-l1-t9", type: "numeric", prompt: "7 × 9 = ?", answer: 63, xp: 10 },
            { id: "ry3-vurma-l1-t10", type: "numeric", prompt: "9 × 6 = ?", answer: 54, xp: 10 },
            { id: "ry3-vurma-l1-t11", type: "numeric", prompt: "8 × 7 = ?", answer: 56, xp: 10 },
            { id: "ry3-vurma-l1-t12", type: "numeric", prompt: "5 × 9 = ?", answer: 45, xp: 10 },
            { id: "ry3-vurma-l1-t13", type: "numeric", prompt: "4 × 8 = ?", answer: 32, xp: 10 },
            { id: "ry3-vurma-l1-t14", type: "numeric", prompt: "9 × 3 = ?", answer: 27, xp: 10 },
            { id: "ry3-vurma-l1-t15", type: "numeric", prompt: "6 × 9 = ?", answer: 54, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry3-vurma-l1-b1", type: "numeric", prompt: "10 × 7 = ?", answer: 70, xp: 15 },
            { id: "ry3-vurma-l1-b2", type: "numeric", prompt: "Hər qutuda 8 alma var. 7 qutuda neçə alma var?", answer: 56, xp: 15 },
            { id: "ry3-vurma-l1-b3", type: "numeric", prompt: "9 × 8 = ?", answer: 72, xp: 15 },
            { id: "ry3-vurma-l1-b4", type: "numeric", prompt: "12 × 3 = ?", answer: 36, xp: 15 },
            { id: "ry3-vurma-l1-b5", type: "numeric", prompt: "7 × 6 = ?", answer: 42, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 4. Bölmə ═══════════════
    {
      id: "ry3-bolme",
      title: "Bölmə",
      description: "Vurma cədvəlinə əsaslanan bölmə və qalıqlı bölmə.",
      lessons: [
        {
          id: "ry3-bolme-l1",
          title: "Bölmə",
          intro: "Bölmə vurmanın əksidir: 42 ÷ 6 = 7, çünki 6 × 7 = 42.",
          sections: [
            { heading: "Bölmə", body: "56 ÷ 8 = 7 (çünki 8 × 7 = 56). Vurma cədvəlini bilsək, bölməni asan edərik." },
          ],
          tasks: [
            { id: "ry3-bolme-l1-t1", type: "numeric", prompt: "42 ÷ 6 = ?", answer: 7, xp: 10 },
            { id: "ry3-bolme-l1-t2", type: "numeric", prompt: "56 ÷ 8 = ?", answer: 7, xp: 10 },
            { id: "ry3-bolme-l1-t3", type: "numeric", prompt: "72 ÷ 9 = ?", answer: 8, xp: 10 },
            { id: "ry3-bolme-l1-t4", type: "numeric", prompt: "63 ÷ 7 = ?", answer: 9, xp: 10 },
            { id: "ry3-bolme-l1-t5", type: "numeric", prompt: "81 ÷ 9 = ?", answer: 9, xp: 10 },
            { id: "ry3-bolme-l1-t6", type: "numeric", prompt: "48 ÷ 6 = ?", answer: 8, xp: 10 },
            { id: "ry3-bolme-l1-t7", type: "numeric", prompt: "64 ÷ 8 = ?", answer: 8, xp: 10 },
            { id: "ry3-bolme-l1-t8", type: "numeric", prompt: "45 ÷ 5 = ?", answer: 9, xp: 10 },
            { id: "ry3-bolme-l1-t9", type: "numeric", prompt: "36 ÷ 6 = ?", answer: 6, xp: 10 },
            { id: "ry3-bolme-l1-t10", type: "numeric", prompt: "54 ÷ 9 = ?", answer: 6, xp: 10 },
            { id: "ry3-bolme-l1-t11", type: "numeric", prompt: "49 ÷ 7 = ?", answer: 7, xp: 10 },
            { id: "ry3-bolme-l1-t12", type: "numeric", prompt: "32 ÷ 4 = ?", answer: 8, xp: 10 },
            { id: "ry3-bolme-l1-t13", type: "numeric", prompt: "27 ÷ 3 = ?", answer: 9, xp: 10 },
            { id: "ry3-bolme-l1-t14", type: "numeric", prompt: "56 ÷ 7 = ?", answer: 8, xp: 10 },
            { id: "ry3-bolme-l1-t15", type: "numeric", prompt: "63 ÷ 9 = ?", answer: 7, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry3-bolme-l1-b1", type: "numeric", prompt: "100 ÷ 10 = ?", answer: 10, xp: 15 },
            { id: "ry3-bolme-l1-b2", type: "numeric", prompt: "72 alma 8 səbətə bərabər paylandı. Hər səbətdə neçə alma var?", answer: 9, xp: 15 },
            { id: "ry3-bolme-l1-b3", type: "numeric", prompt: "13 ÷ 4 bölməsində qalıq neçədir? (13 = 4×3 + 1)", answer: 1, xp: 15 },
            { id: "ry3-bolme-l1-b4", type: "numeric", prompt: "90 ÷ 9 = ?", answer: 10, xp: 15 },
            { id: "ry3-bolme-l1-b5", type: "numeric", prompt: "48 ÷ 8 = ?", answer: 6, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 5. Kəsrlər ═══════════════
    {
      id: "ry3-kesr",
      title: "Kəsrlər",
      description: "Bütövün hissələri: 1/2, 1/3, 1/4 kəsrləri.",
      lessons: [
        {
          id: "ry3-kesr-l1",
          title: "Sadə kəsrlər",
          intro: "Bütövü bərabər hissələrə bölmək.",
          sections: [
            { heading: "Kəsr nədir?", body: "Bütövü bərabər hissələrə bölürük. 1/2 — yarı, 1/3 — üçdə bir, 1/4 — dörddə bir. Alt ədəd (məxrəc) neçə hissəyə böldüyümüzü, üst ədəd (sürət) neçə hissə götürdüyümüzü göstərir." },
          ],
          tasks: [
            { id: "ry3-kesr-l1-t1", type: "multiple_choice", prompt: "1/2 kəsri nə deməkdir?", options: ["yarı", "üçdə bir", "dörddə bir", "bütöv"], correctIndex: 0, xp: 10 },
            { id: "ry3-kesr-l1-t2", type: "multiple_choice", prompt: "1/4 kəsri nə deməkdir?", options: ["dörddə bir", "yarı", "üçdə bir", "bütöv"], correctIndex: 0, xp: 10 },
            { id: "ry3-kesr-l1-t3", type: "numeric", prompt: "10 almanın yarısı (1/2) neçə almadır?", answer: 5, xp: 10 },
            { id: "ry3-kesr-l1-t4", type: "numeric", prompt: "12 konfetin yarısı (1/2) neçədir?", answer: 6, xp: 10 },
            { id: "ry3-kesr-l1-t5", type: "numeric", prompt: "9 almanın üçdə biri (1/3) neçə almadır?", answer: 3, xp: 10 },
            { id: "ry3-kesr-l1-t6", type: "numeric", prompt: "8 konfetin dörddə biri (1/4) neçədir?", answer: 2, xp: 10 },
            { id: "ry3-kesr-l1-t7", type: "multiple_choice", prompt: "1/2 kəsrində alt ədəd (məxrəc) neçədir?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 10 },
            { id: "ry3-kesr-l1-t8", type: "numeric", prompt: "6 şarın yarısı neçədir?", answer: 3, xp: 10 },
            { id: "ry3-kesr-l1-t9", type: "numeric", prompt: "12 almanın üçdə biri (1/3) neçədir?", answer: 4, xp: 10 },
            { id: "ry3-kesr-l1-t10", type: "numeric", prompt: "20 konfetin dörddə biri (1/4) neçədir?", answer: 5, xp: 10 },
            { id: "ry3-kesr-l1-t11", type: "multiple_choice", prompt: "Hansı kəsr daha böyükdür?", options: ["1/2", "1/4", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry3-kesr-l1-t12", type: "numeric", prompt: "8 almanın yarısı neçədir?", answer: 4, xp: 10 },
            { id: "ry3-kesr-l1-t13", type: "multiple_choice", prompt: "Bir bütövü 4 bərabər hissəyə bölsək, hər hissə nədir?", options: ["1/4", "1/2", "1/3", "4"], correctIndex: 0, xp: 10 },
            { id: "ry3-kesr-l1-t14", type: "numeric", prompt: "15 almanın üçdə biri (1/3) neçədir?", answer: 5, xp: 10 },
            { id: "ry3-kesr-l1-t15", type: "numeric", prompt: "16 konfetin dörddə biri (1/4) neçədir?", answer: 4, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry3-kesr-l1-b1", type: "numeric", prompt: "20 almanın yarısı neçədir?", answer: 10, xp: 15 },
            { id: "ry3-kesr-l1-b2", type: "multiple_choice", prompt: "1/3 və 1/4 kəsrlərindən böyüyü hansıdır?", options: ["1/3", "1/4", "bərabər", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "ry3-kesr-l1-b3", type: "numeric", prompt: "24 konfetin dörddə biri neçədir?", answer: 6, xp: 15 },
            { id: "ry3-kesr-l1-b4", type: "numeric", prompt: "Tortu 2 bərabər hissəyə böldük, 1 hissəni yedik. Neçə hissə qaldı?", answer: 1, xp: 15 },
            { id: "ry3-kesr-l1-b5", type: "numeric", prompt: "18 almanın üçdə biri neçədir?", answer: 6, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 6. Həndəsə, ölçmə və məsələlər ═══════════════
    {
      id: "ry3-hendese",
      title: "Həndəsə, ölçmə və məsələlər",
      description: "Perimetr, ölçü vahidləri və mətn məsələləri.",
      lessons: [
        {
          id: "ry3-hendese-l1",
          title: "Perimetr və ölçmə",
          intro: "Fiqurun perimetri və ölçü vahidləri.",
          sections: [
            { heading: "Perimetr", body: "Perimetr fiqurun bütün tərəflərinin cəmidir. Kvadratın perimetri: 4 × tərəf. Düzbucaqlının perimetri: 2 × (uzunluq + en)." },
            { heading: "Ölçü vahidləri", body: "1 metr = 100 sm. 1 kq = 1000 qram. 1 litr, 1 saat = 60 dəqiqə." },
          ],
          tasks: [
            { id: "ry3-hendese-l1-t1", type: "numeric", prompt: "Kvadratın tərəfi 6 sm-dir. Perimetri neçədir? (4 × 6)", answer: 24, xp: 10 },
            { id: "ry3-hendese-l1-t2", type: "numeric", prompt: "Kvadratın tərəfi 10 sm-dir. Perimetri neçədir?", answer: 40, xp: 10 },
            { id: "ry3-hendese-l1-t3", type: "numeric", prompt: "Düzbucaqlının tərəfləri 5 və 3 sm-dir. Perimetri? (2×(5+3))", answer: 16, xp: 10 },
            { id: "ry3-hendese-l1-t4", type: "numeric", prompt: "Üçbucağın tərəfləri 4, 5, 6 sm-dir. Perimetri? (4+5+6)", answer: 15, xp: 10 },
            { id: "ry3-hendese-l1-t5", type: "numeric", prompt: "1 metr neçə santimetrdir?", answer: 100, xp: 10 },
            { id: "ry3-hendese-l1-t6", type: "numeric", prompt: "1 kiloqram neçə qramdır?", answer: 1000, xp: 10 },
            { id: "ry3-hendese-l1-t7", type: "numeric", prompt: "1 saat neçə dəqiqədir?", answer: 60, xp: 10 },
            { id: "ry3-hendese-l1-t8", type: "numeric", prompt: "3 metr neçə santimetrdir?", answer: 300, xp: 10 },
            { id: "ry3-hendese-l1-t9", type: "numeric", prompt: "2 kq neçə qramdır?", answer: 2000, xp: 10 },
            { id: "ry3-hendese-l1-t10", type: "numeric", prompt: "Kvadratın tərəfi 8 sm-dir. Perimetri neçədir?", answer: 32, xp: 10 },
            { id: "ry3-hendese-l1-t11", type: "numeric", prompt: "Düzbucaqlının tərəfləri 7 və 3 sm-dir. Perimetri?", answer: 20, xp: 10 },
            { id: "ry3-hendese-l1-t12", type: "numeric", prompt: "Yarım saat neçə dəqiqədir?", answer: 30, xp: 10 },
            { id: "ry3-hendese-l1-t13", type: "numeric", prompt: "Hər tərəfi 5 sm olan üçbucağın perimetri? (3 × 5)", answer: 15, xp: 10 },
            { id: "ry3-hendese-l1-t14", type: "numeric", prompt: "500 qram + 500 qram neçə kiloqramdır?", answer: 1, xp: 10 },
            { id: "ry3-hendese-l1-t15", type: "numeric", prompt: "Kvadratın perimetri 20 sm-dir. Bir tərəfi neçədir? (20 ÷ 4)", answer: 5, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry3-hendese-l1-b1", type: "numeric", prompt: "Düzbucaqlının tərəfləri 8 və 4 sm-dir. Perimetri?", answer: 24, xp: 15 },
            { id: "ry3-hendese-l1-b2", type: "numeric", prompt: "5 metr neçə santimetrdir?", answer: 500, xp: 15 },
            { id: "ry3-hendese-l1-b3", type: "numeric", prompt: "3 saat neçə dəqiqədir? (3 × 60)", answer: 180, xp: 15 },
            { id: "ry3-hendese-l1-b4", type: "numeric", prompt: "Kvadratın perimetri 36 sm-dir. Bir tərəfi neçədir?", answer: 9, xp: 15 },
            { id: "ry3-hendese-l1-b5", type: "numeric", prompt: "Kvadratın sahəsi: tərəf 4 sm-dirsə, sahə neçə kv.sm-dir? (4×4)", answer: 16, xp: 15 },
          ],
        },
        {
          id: "ry3-hendese-l2",
          title: "Mətn məsələləri",
          intro: "Toplama, çıxma, vurma və bölmə ilə məsələ həll edək.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, düzgün əməli seç, hesabla." },
          ],
          tasks: [
            { id: "ry3-hendese-l2-t1", type: "numeric", prompt: "Mağazada 250 kitab var idi, 130 satıldı. Neçə kitab qaldı?", answer: 120, xp: 10 },
            { id: "ry3-hendese-l2-t2", type: "numeric", prompt: "Hər sinifdə 25 şagird var. 4 sinifdə neçə şagird var?", answer: 100, xp: 10 },
            { id: "ry3-hendese-l2-t3", type: "numeric", prompt: "72 alma 8 qutuya bərabər paylandı. Hər qutuda neçə alma var?", answer: 9, xp: 10 },
            { id: "ry3-hendese-l2-t4", type: "numeric", prompt: "Aylının 340 manatı var idi, 150 manat xərclədi. Neçə manatı qaldı?", answer: 190, xp: 10 },
            { id: "ry3-hendese-l2-t5", type: "numeric", prompt: "Kitabxanada 500 kitab var, 250 də əlavə olundu. Neçə kitab oldu?", answer: 750, xp: 10 },
            { id: "ry3-hendese-l2-t6", type: "numeric", prompt: "Hər gün 6 səhifə oxuyuram. 7 gündə neçə səhifə oxuyuram?", answer: 42, xp: 10 },
            { id: "ry3-hendese-l2-t7", type: "numeric", prompt: "48 şəkil 6 albomda bərabər yerləşdi. Hər albomda neçə şəkil var?", answer: 8, xp: 10 },
            { id: "ry3-hendese-l2-t8", type: "numeric", prompt: "Bağçada 200 gül var idi, 85 soldu. Neçə gül qaldı?", answer: 115, xp: 10 },
            { id: "ry3-hendese-l2-t9", type: "numeric", prompt: "Hər kutuda 9 qələm var. 5 kutuda neçə qələm var?", answer: 45, xp: 10 },
            { id: "ry3-hendese-l2-t10", type: "numeric", prompt: "63 konfet 9 uşağa bərabər paylandı. Hər biri neçə alır?", answer: 7, xp: 10 },
            { id: "ry3-hendese-l2-t11", type: "numeric", prompt: "İki qutuda 125 və 175 marka var. Cəmi neçə marka var?", answer: 300, xp: 10 },
            { id: "ry3-hendese-l2-t12", type: "numeric", prompt: "Anarın 8 yaşı var. Atası ondan 4 dəfə böyükdür. Atası neçə yaşındadır?", answer: 32, xp: 10 },
            { id: "ry3-hendese-l2-t13", type: "numeric", prompt: "600 manatlıq velosipedə 250 manat endirim edildi. Yeni qiymət neçədir?", answer: 350, xp: 10 },
            { id: "ry3-hendese-l2-t14", type: "numeric", prompt: "56 şagird 8 komandaya bərabər bölündü. Hər komandada neçə nəfər var?", answer: 7, xp: 10 },
            { id: "ry3-hendese-l2-t15", type: "numeric", prompt: "Hər həftədə 7 gün var. 8 həftədə neçə gün var?", answer: 56, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry3-hendese-l2-b1", type: "numeric", prompt: "Bir avtobusda 45 sərnişin var. 2 avtobusda neçə sərnişin var?", answer: 90, xp: 15 },
            { id: "ry3-hendese-l2-b2", type: "numeric", prompt: "1000 manatım var idi, 350 və 250 manat xərclədim. Neçə manat qaldı?", answer: 400, xp: 15 },
            { id: "ry3-hendese-l2-b3", type: "numeric", prompt: "81 kitab 9 rəfə bərabər yerləşdi. Hər rəfdə neçə kitab var?", answer: 9, xp: 15 },
            { id: "ry3-hendese-l2-b4", type: "numeric", prompt: "Hər qutuda 12 yumurta var. 6 qutuda neçə yumurta var?", answer: 72, xp: 15 },
            { id: "ry3-hendese-l2-b5", type: "numeric", prompt: "240 səhifəlik kitabın 160 səhifəsini oxudum. Neçə səhifə qaldı?", answer: 80, xp: 15 },
          ],
        },
      ],
    },
  ],
};
