// Riyaziyyat — "Adi kəsrlər" treki. Hər dərs bir layihədir (project).
// Qaydalar (sections) holberton3 üslubunda şəkil altında göstərilir.
// Hər layihə: 15 əsas tapşırıq + 5 bonus (İngilis treki ilə eyni standart).

import type { Subject } from "../types";

export const math: Subject = {
  slug: "riyaziyyat",
  name: "Riyaziyyat",
  grade: 5,
  icon: "🔢",
  color: "sky",
  units: [
    {
      id: "ry-fractions",
      title: "Adi kəsrlər",
      description:
        "Kəsr anlayışı, müqayisə, toplama-çıxma və ədədin kəsr hissəsinin tapılması.",
      lessons: [
        {
          id: "ry-u1-l1",
          title: "Kəsr anlayışı",
          intro: "Bir bütövü bərabər hissələrə böləndə kəsr alınır.",
          visual: "fraction-basic",
          sections: [
            { heading: "Kəsr nədir?", body: "Bir bütövü bərabər hissələrə böləndə kəsr alınır. Məsələn, bir şokoladı 4 bərabər hissəyə bölmək olar və hər hissə bütövün 1/4-i olar." },
            { heading: "Surət və məxrəc", body: "Aşağıdakı ədəd — məxrəc — bütövün neçə bərabər hissəyə bölündüyünü göstərir. Yuxarıdakı ədəd — surət — bizim neçə hissə götürdüyümüzü göstərir. 3/4-də 4 məxrəc, 3 surətdir." },
            { heading: "Kəsr xətti = bölmə", body: "Kəsr xətti həm də bölmə deməkdir: 3/4 eyni zamanda 3 : 4 deməkdir." },
          ],
          tasks: [
            { id: "ry-u1-l1-t1", type: "multiple_choice", prompt: "3/8 kəsrində məxrəc hansı ədəddir?", figure: { kind: "fractionBar", parts: 8, filled: 3 }, options: ["3", "8", "11", "5"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l1-t2", type: "multiple_choice", prompt: "Aşağıdakı kəsrlərdən hansında surət məxrəcdən böyükdür?", options: ["2/5", "7/4", "3/8", "1/6"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l1-t3", type: "numeric", prompt: "Bir düzbucaqlı 5 bərabər hissəyə bölünüb və onlardan 2-si rənglənib. Rənglənmiş hissəni göstərən kəsrin surəti neçədir?", figure: { kind: "fractionBar", parts: 5, filled: 2 }, answer: 2, xp: 10 },
            { id: "ry-u1-l1-t4", type: "fill_blank", prompt: "Kəsr xəttinin altında yazılan ədəd ___ adlanır.", accepted: ["məxrəc", "mexrec"], xp: 10 },
            { id: "ry-u1-l1-t5", type: "numeric", prompt: "Bir bütöv 7 bərabər hissəyə bölünüb və hər 7 hissə götürülüb. 7/7 kəsri neçə tam edir?", answer: 1, xp: 10 },
            { id: "ry-u1-l1-t6", type: "multiple_choice", prompt: "3/4 kəsri hansı bölmə əməlini bildirir?", figure: { kind: "fractionBar", parts: 4, filled: 3 }, options: ["4 : 3", "3 : 4", "3 + 4", "3 × 4"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l1-t7", type: "numeric", prompt: "5/6 kəsrində surət hansı ədəddir?", figure: { kind: "fractionBar", parts: 6, filled: 5 }, answer: 5, xp: 10 },
            { id: "ry-u1-l1-t8", type: "numeric", prompt: "Bir pizza 8 bərabər hissəyə bölünüb və 5 hissəsi yeyilib. Yeyilən hissəni göstərən kəsrin surəti neçədir?", figure: { kind: "fractionBar", parts: 8, filled: 5 }, answer: 5, xp: 10 },
            { id: "ry-u1-l1-t9", type: "fill_blank", prompt: "Kəsr xəttinin üstündə yazılan ədəd ___ adlanır.", accepted: ["surət", "suret"], xp: 10 },
            { id: "ry-u1-l1-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün kəsrdir (surəti məxrəcindən kiçikdir)?", options: ["3/2", "5/5", "2/7", "9/4"], correctIndex: 2, xp: 10 },
            { id: "ry-u1-l1-t11", type: "numeric", prompt: "Bir düzbucaqlı 6 bərabər hissəyə bölünüb. Bu kəsrin məxrəci neçədir?", figure: { kind: "fractionBar", parts: 6, filled: 1 }, answer: 6, xp: 10 },
            { id: "ry-u1-l1-t12", type: "multiple_choice", prompt: "4/4 kəsri neçə tam edir?", options: ["0", "1", "4", "1/4"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l1-t13", type: "fill_blank", prompt: "6/10 kəsri 6 : 10 ___ əməlini bildirir.", accepted: ["bölmə", "bolme"], xp: 10 },
            { id: "ry-u1-l1-t14", type: "numeric", prompt: "Bir tortu 10 bərabər hissəyə böldük və 3 hissə götürdük. Götürülən hissəni göstərən kəsrin surəti neçədir?", figure: { kind: "fractionBar", parts: 10, filled: 3 }, answer: 3, xp: 10 },
            { id: "ry-u1-l1-t15", type: "multiple_choice", prompt: "Kəsrdə hansı ədəd bütövün neçə bərabər hissəyə bölündüyünü göstərir?", options: ["surət", "məxrəc", "kəsr xətti", "tam hissə"], correctIndex: 1, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-u1-l1-b1", type: "multiple_choice", prompt: "7/7, 3/3 və 9/9 kəsrlərinin hamısı neçəyə bərabərdir?", options: ["0", "1", "2", "10"], correctIndex: 1, xp: 15 },
            { id: "ry-u1-l1-b2", type: "numeric", prompt: "Bir zolaq 12 bərabər hissəyə bölünüb və 7-si rənglənib. Rənglənmiş hissəni göstərən kəsrin surəti neçədir?", figure: { kind: "fractionBar", parts: 12, filled: 7 }, answer: 7, xp: 15 },
            { id: "ry-u1-l1-b3", type: "fill_blank", prompt: "Surəti məxrəcinə bərabər olan kəsr həmişə ___ tama bərabərdir. (Rəqəmlə yaz)", accepted: ["1", "bir"], xp: 15 },
            { id: "ry-u1-l1-b4", type: "multiple_choice", prompt: "Aşağıdakı kəsrlərdən hansı bütövdən böyükdür?", options: ["3/8", "8/3", "1/2", "5/6"], correctIndex: 1, xp: 15 },
            { id: "ry-u1-l1-b5", type: "numeric", prompt: "Yarım saatı 1/2 kəsri ilə göstəririk. Bu kəsrin məxrəci neçədir?", answer: 2, xp: 15 },
          ],
        },
        {
          id: "ry-u1-l2",
          title: "Kəsrlərin müqayisəsi",
          intro: "İki kəsrdən hansının böyük olduğunu tapaq.",
          visual: "fraction-compare",
          sections: [
            { heading: "Eyni məxrəc", body: "Məxrəclər eynidirsə, surəti böyük olan kəsr daha böyükdür. Məsələn, 5/8 kəsri 3/8-dən böyükdür." },
            { heading: "Eyni surət", body: "Surətlər eynidirsə, məxrəci kiçik olan kəsr daha böyükdür. Məsələn, 1/3 kəsri 1/6-dan böyükdür, çünki hissələr daha iridir." },
            { heading: "İşarələr", body: "Müqayisə üçün üç işarə var: '<' kiçik, '>' böyük, '=' bərabər." },
          ],
          tasks: [
            { id: "ry-u1-l2-t1", type: "multiple_choice", prompt: "Hansı kəsr daha böyükdür: 4/9, yoxsa 7/9?", figure: { kind: "compareBars", a: { parts: 9, filled: 4 }, b: { parts: 9, filled: 7 } }, options: ["4/9", "7/9", "Bərabərdir", "Müqayisə olunmur"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l2-t2", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 3/10 ___ 8/10", accepted: ["<"], xp: 10 },
            { id: "ry-u1-l2-t3", type: "multiple_choice", prompt: "Surətləri eyni olan kəsrlərdən hansı daha böyükdür?", options: ["Məxrəci böyük olan", "Məxrəci kiçik olan", "İkisi bərabərdir", "Müqayisə etmək olmur"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l2-t4", type: "multiple_choice", prompt: "1/4 ilə 1/7 kəsrlərindən hansı daha böyükdür?", figure: { kind: "compareBars", a: { parts: 4, filled: 1 }, b: { parts: 7, filled: 1 } }, options: ["1/4", "1/7", "Bərabərdir", "Bilinmir"], correctIndex: 0, xp: 10 },
            { id: "ry-u1-l2-t5", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 6/6 ___ 1", accepted: ["="], xp: 10 },
            { id: "ry-u1-l2-t6", type: "numeric", prompt: "5/11, 8/11 və 2/11 kəsrlərindən ən böyüyünün surəti neçədir?", answer: 8, xp: 10 },
            { id: "ry-u1-l2-t7", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 5/12 ___ 5/9", accepted: ["<"], xp: 10 },
            { id: "ry-u1-l2-t8", type: "multiple_choice", prompt: "2/3 ilə 2/5 kəsrlərindən hansı daha böyükdür?", figure: { kind: "compareBars", a: { parts: 3, filled: 2 }, b: { parts: 5, filled: 2 } }, options: ["2/3", "2/5", "Bərabərdir", "Bilinmir"], correctIndex: 0, xp: 10 },
            { id: "ry-u1-l2-t9", type: "numeric", prompt: "3/7, 6/7 və 1/7 kəsrlərindən ən kiçiyinin surəti neçədir?", answer: 1, xp: 10 },
            { id: "ry-u1-l2-t10", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 4/8 ___ 4/8", accepted: ["="], xp: 10 },
            { id: "ry-u1-l2-t11", type: "multiple_choice", prompt: "Məxrəcləri eyni olan kəsrlərdən hansı daha böyükdür?", options: ["Surəti kiçik olan", "Surəti böyük olan", "İkisi bərabərdir", "Bilinmir"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l2-t12", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 7/10 ___ 9/10", accepted: ["<"], xp: 10 },
            { id: "ry-u1-l2-t13", type: "multiple_choice", prompt: "1/2 ilə 1/3 kəsrlərindən hansı daha böyükdür?", figure: { kind: "compareBars", a: { parts: 2, filled: 1 }, b: { parts: 3, filled: 1 } }, options: ["1/2", "1/3", "Bərabərdir", "Bilinmir"], correctIndex: 0, xp: 10 },
            { id: "ry-u1-l2-t14", type: "numeric", prompt: "2/5, 4/5 və 3/5 kəsrlərindən ən böyüyünün surəti neçədir?", answer: 4, xp: 10 },
            { id: "ry-u1-l2-t15", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 9/9 ___ 1", accepted: ["="], xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-u1-l2-b1", type: "multiple_choice", prompt: "3/4, 2/4 və 4/4 kəsrlərindən ən böyüyü hansıdır?", options: ["3/4", "2/4", "4/4", "Bərabərdirlər"], correctIndex: 2, xp: 15 },
            { id: "ry-u1-l2-b2", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 1/100 ___ 1/10", accepted: ["<"], xp: 15 },
            { id: "ry-u1-l2-b3", type: "multiple_choice", prompt: "Aşağıdakı kəsrlərdən ən böyüyü hansıdır?", options: ["1/2", "1/4", "1/8", "1/3"], correctIndex: 0, xp: 15 },
            { id: "ry-u1-l2-b4", type: "numeric", prompt: "5/6 ilə 5/8 kəsrlərindən böyük olanın məxrəci neçədir?", answer: 6, xp: 15 },
            { id: "ry-u1-l2-b5", type: "fill_blank", prompt: "Tam ədəd 1-i kəsr kimi göstərsək: 5/5 = ___ (rəqəmlə yaz).", accepted: ["1", "bir"], xp: 15 },
          ],
        },
        {
          id: "ry-u1-l3",
          title: "Kəsrlərin toplanması və çıxılması",
          intro: "Məxrəcləri eyni olan kəsrləri toplamaq və çıxmaq asandır.",
          visual: "fraction-add",
          sections: [
            { heading: "Toplama", body: "Surətləri toplayırıq, məxrəc dəyişmir. Məsələn, 2/7 + 3/7 = 5/7." },
            { heading: "Çıxma", body: "Surətləri çıxırıq, məxrəc olduğu kimi qalır. Məsələn, 6/9 − 4/9 = 2/9." },
            { heading: "Diqqət", body: "Məxrəc heç vaxt toplanmır və ya çıxılmır, çünki hissələrin ölçüsü dəyişmir." },
          ],
          tasks: [
            { id: "ry-u1-l3-t1", type: "numeric", prompt: "Hesabla: 3/10 + 4/10 kəsrinin surəti neçədir?", answer: 7, xp: 10 },
            { id: "ry-u1-l3-t2", type: "multiple_choice", prompt: "2/9 + 5/9 cəmi neçəyə bərabərdir?", figure: { kind: "compareBars", a: { parts: 9, filled: 2 }, b: { parts: 9, filled: 5 } }, options: ["7/18", "7/9", "3/9", "10/9"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l3-t3", type: "numeric", prompt: "Hesabla: 6/13 − 2/13 fərqinin surəti neçədir?", answer: 4, xp: 10 },
            { id: "ry-u1-l3-t4", type: "multiple_choice", prompt: "1/6 + 2/6 + 3/6 cəmi neçəyə bərabərdir?", options: ["6/18", "6/6", "1/2", "6/12"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l3-t5", type: "numeric", prompt: "Bir səbətdəki almaların 4/12-si qırmızı, 5/12-si yaşıldır. Qırmızı və yaşıl almalar birlikdə səbətin neçə on ikidə bir hissəsini təşkil edir? (Yalnız surəti yaz)", figure: { kind: "emoji", items: ["🍎", "🍎", "🍎", "🍎", "🍏", "🍏", "🍏", "🍏", "🍏", "⚪", "⚪", "⚪"] }, answer: 9, xp: 15 },
            { id: "ry-u1-l3-t6", type: "fill_blank", prompt: "Məxrəcləri eyni olan kəsrləri toplayarkən yalnız ___ toplanır.", accepted: ["surətlər", "suretler", "surət", "suret"], xp: 10 },
            { id: "ry-u1-l3-t7", type: "numeric", prompt: "Hesabla: 4/11 + 5/11 kəsrinin surəti neçədir?", answer: 9, xp: 10 },
            { id: "ry-u1-l3-t8", type: "numeric", prompt: "Hesabla: 8/15 − 3/15 fərqinin surəti neçədir?", answer: 5, xp: 10 },
            { id: "ry-u1-l3-t9", type: "multiple_choice", prompt: "3/8 + 3/8 cəmi neçəyə bərabərdir?", options: ["6/16", "6/8", "3/8", "9/8"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l3-t10", type: "numeric", prompt: "Hesabla: 7/20 + 8/20 kəsrinin surəti neçədir?", answer: 15, xp: 10 },
            { id: "ry-u1-l3-t11", type: "fill_blank", prompt: "Eyni məxrəcli kəsrləri toplayarkən məxrəc ___ .", accepted: ["dəyişmir", "deyismir"], xp: 10 },
            { id: "ry-u1-l3-t12", type: "numeric", prompt: "Hesabla: 9/10 − 4/10 fərqinin surəti neçədir?", answer: 5, xp: 10 },
            { id: "ry-u1-l3-t13", type: "multiple_choice", prompt: "1/5 + 1/5 + 1/5 cəmi neçəyə bərabərdir?", options: ["3/15", "3/5", "1/5", "3/10"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l3-t14", type: "numeric", prompt: "Bir kitabın 3/12-si bazar günü, 4/12-si bazar ertəsi oxunub. Cəmi neçə on ikidə bir hissə oxunub? (Yalnız surəti yaz)", answer: 7, xp: 10 },
            { id: "ry-u1-l3-t15", type: "multiple_choice", prompt: "10/13 − 10/13 neçəyə bərabərdir?", options: ["0", "20/13", "10/13", "10/26"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-u1-l3-b1", type: "numeric", prompt: "Hesabla: 2/9 + 3/9 + 4/9 kəsrinin surəti neçədir?", answer: 9, xp: 15 },
            { id: "ry-u1-l3-b2", type: "multiple_choice", prompt: "5/6 − 2/6 − 1/6 neçəyə bərabərdir?", options: ["2/6", "8/6", "2/18", "3/6"], correctIndex: 0, xp: 15 },
            { id: "ry-u1-l3-b3", type: "fill_blank", prompt: "Eyni məxrəcli kəsrləri çıxarkən yalnız ___ çıxılır.", accepted: ["surətlər", "suretler", "surət", "suret"], xp: 15 },
            { id: "ry-u1-l3-b4", type: "numeric", prompt: "Hesabla: 11/25 + 9/25 kəsrinin surəti neçədir?", answer: 20, xp: 15 },
            { id: "ry-u1-l3-b5", type: "numeric", prompt: "Bir bütöv 7/7-dir. 7/7 − 3/7 fərqinin surəti neçədir?", answer: 4, xp: 15 },
          ],
        },
        {
          id: "ry-u1-l4",
          title: "Ədədin kəsr hissəsinin tapılması",
          intro: "Bir ədədin kəsr hissəsini necə tapaq?",
          visual: "fraction-of-number",
          sections: [
            { heading: "Qayda", body: "Əvvəlcə ədədi kəsrin məxrəcinə bölürük, sonra alınan nəticəni surətə vururuq." },
            { heading: "Nümunə", body: "20 ədədinin 3/4 hissəsi: əvvəl 20 : 4 = 5, sonra 5 × 3 = 15. Deməli, cavab 15-dir." },
            { heading: "Surət 1 olanda", body: "Əgər surət 1-dirsə, sadəcə ədədi məxrəcə bölmək kifayətdir. Məsələn, 12-nin 1/3 hissəsi = 12 : 3 = 4." },
          ],
          tasks: [
            { id: "ry-u1-l4-t1", type: "numeric", prompt: "12 ədədinin 1/3 hissəsini tap.", figure: { kind: "dots", total: 12 }, answer: 4, xp: 10 },
            { id: "ry-u1-l4-t2", type: "numeric", prompt: "30 ədədinin 2/5 hissəsini tap.", figure: { kind: "dots", total: 30 }, answer: 12, xp: 10 },
            { id: "ry-u1-l4-t3", type: "numeric", prompt: "24 ədədinin 3/4 hissəsini tap.", answer: 18, xp: 10 },
            { id: "ry-u1-l4-t4", type: "multiple_choice", prompt: "18 ədədinin 1/2 hissəsi neçədir?", options: ["6", "9", "12", "3"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l4-t5", type: "numeric", prompt: "Bir sinifdə 28 şagird var. Şagirdlərin 4/7-si oğlandır. Sinifdə neçə oğlan var?", figure: { kind: "dots", total: 28 }, answer: 16, xp: 15 },
            { id: "ry-u1-l4-t6", type: "numeric", prompt: "50 manatın 1/5 hissəsi neçə manatdır?", answer: 10, xp: 10 },
            { id: "ry-u1-l4-t7", type: "numeric", prompt: "15 ədədinin 1/5 hissəsini tap.", answer: 3, xp: 10 },
            { id: "ry-u1-l4-t8", type: "numeric", prompt: "40 ədədinin 3/8 hissəsini tap.", answer: 15, xp: 10 },
            { id: "ry-u1-l4-t9", type: "numeric", prompt: "21 ədədinin 2/3 hissəsini tap.", answer: 14, xp: 10 },
            { id: "ry-u1-l4-t10", type: "multiple_choice", prompt: "16 ədədinin 1/4 hissəsi neçədir?", options: ["2", "4", "8", "12"], correctIndex: 1, xp: 10 },
            { id: "ry-u1-l4-t11", type: "numeric", prompt: "100 ədədinin 1/10 hissəsini tap.", answer: 10, xp: 10 },
            { id: "ry-u1-l4-t12", type: "numeric", prompt: "27 ədədinin 2/9 hissəsini tap.", answer: 6, xp: 10 },
            { id: "ry-u1-l4-t13", type: "numeric", prompt: "Bir kitab 60 səhifədir. Onun 2/3-ü oxunub. Neçə səhifə oxunub?", answer: 40, xp: 10 },
            { id: "ry-u1-l4-t14", type: "numeric", prompt: "45 ədədinin 1/9 hissəsini tap.", answer: 5, xp: 10 },
            { id: "ry-u1-l4-t15", type: "multiple_choice", prompt: "10 ədədinin 3/5 hissəsi neçədir?", options: ["2", "5", "6", "8"], correctIndex: 2, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-u1-l4-b1", type: "numeric", prompt: "200 ədədinin 3/4 hissəsini tap.", answer: 150, xp: 15 },
            { id: "ry-u1-l4-b2", type: "numeric", prompt: "36 ədədinin 5/6 hissəsini tap.", answer: 30, xp: 15 },
            { id: "ry-u1-l4-b3", type: "numeric", prompt: "Bir sinifdə 32 şagird var. Onların 3/8-i eynək taxır. Neçə şagird eynək taxır?", answer: 12, xp: 15 },
            { id: "ry-u1-l4-b4", type: "numeric", prompt: "90 ədədinin 4/9 hissəsini tap.", answer: 40, xp: 15 },
            { id: "ry-u1-l4-b5", type: "numeric", prompt: "1 saat 60 dəqiqədir. 60 dəqiqənin 1/4 hissəsi neçə dəqiqədir?", answer: 15, xp: 15 },
          ],
        },
      ],
    },
  ],
};
