// Riyaziyyat — 4-cü sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Böyük ədədlər  2) Çoxrəqəmli vurma  3) Çoxrəqəmli bölmə
// 4) Kəsrlər  5) Onluq kəsrlər və ölçmə  6) Sahə, əməllər sırası və məsələlər.
// 4-cü sinif üçün (rəqəm cavablar). id prefiksi ry4-*.

import type { Subject } from "../types";

export const math4: Subject = {
  slug: "riyaziyyat-4",
  name: "Riyaziyyat",
  grade: 4,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Böyük ədədlər ═══════════════
    {
      id: "ry4-boyuk",
      title: "Böyük ədədlər",
      description: "Minlik, on minlik və milyona qədər ədədləri oxumaq, yazmaq, müqayisə etmək.",
      lessons: [
        {
          id: "ry4-boyuk-l1",
          title: "Minliklər və böyük ədədlər",
          intro: "Dördrəqəmli və daha böyük ədədlər.",
          sections: [
            { heading: "Mərtəbələr", body: "Böyük ədədlər minlik, yüzlük, onluq, təklikdən ibarətdir. 3456 = 3 minlik + 4 yüzlük + 5 onluq + 6 təklik." },
            { heading: "Böyük ədədlər", body: "1000 — min, 10 000 — on min, 100 000 — yüz min, 1 000 000 — milyon." },
          ],
          tasks: [
            { id: "ry4-boyuk-l1-t1", type: "numeric", prompt: "3456 ədədində neçə minlik var?", answer: 3, xp: 10 },
            { id: "ry4-boyuk-l1-t2", type: "numeric", prompt: "3456 ədədində neçə yüzlük var?", answer: 4, xp: 10 },
            { id: "ry4-boyuk-l1-t3", type: "numeric", prompt: "2 minlik + 3 yüzlük + 0 onluq + 5 təklik = ?", answer: 2305, xp: 10 },
            { id: "ry4-boyuk-l1-t4", type: "numeric", prompt: "5 minlik = ?", answer: 5000, xp: 10 },
            { id: "ry4-boyuk-l1-t5", type: "numeric", prompt: "'on min' rəqəmlə necə yazılır?", answer: 10000, xp: 10 },
            { id: "ry4-boyuk-l1-t6", type: "numeric", prompt: "'yüz min' rəqəmlə necə yazılır?", answer: 100000, xp: 10 },
            { id: "ry4-boyuk-l1-t7", type: "numeric", prompt: "'bir milyon' rəqəmlə necə yazılır?", answer: 1000000, xp: 10 },
            { id: "ry4-boyuk-l1-t8", type: "numeric", prompt: "9999-dan sonra hansı ədəd gəlir?", answer: 10000, xp: 10 },
            { id: "ry4-boyuk-l1-t9", type: "multiple_choice", prompt: "3456 və 3465 ədədlərindən böyüyü hansıdır?", options: ["3465", "3456", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry4-boyuk-l1-t10", type: "multiple_choice", prompt: "12000 və 9999 ədədlərindən böyüyü hansıdır?", options: ["12000", "9999", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry4-boyuk-l1-t11", type: "numeric", prompt: "'iki min beş yüz' rəqəmlə necə yazılır?", answer: 2500, xp: 10 },
            { id: "ry4-boyuk-l1-t12", type: "numeric", prompt: "1 milyon neçə mindir?", answer: 1000, xp: 10 },
            { id: "ry4-boyuk-l1-t13", type: "numeric", prompt: "7000-dən əvvəl gələn ədəd hansıdır?", answer: 6999, xp: 10 },
            { id: "ry4-boyuk-l1-t14", type: "numeric", prompt: "4 minlik + 0 yüzlük + 0 onluq + 0 təklik = ?", answer: 4000, xp: 10 },
            { id: "ry4-boyuk-l1-t15", type: "numeric", prompt: "'altı min üç yüz' rəqəmlə necə yazılır?", answer: 6300, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry4-boyuk-l1-b1", type: "numeric", prompt: "1 on minlik neçə təklikdir?", answer: 10000, xp: 15 },
            { id: "ry4-boyuk-l1-b2", type: "numeric", prompt: "'səksən beş min' rəqəmlə necə yazılır?", answer: 85000, xp: 15 },
            { id: "ry4-boyuk-l1-b3", type: "multiple_choice", prompt: "45678, 45876, 45687 — ən böyüyü hansıdır?", options: ["45876", "45687", "45678", "heç biri"], correctIndex: 0, xp: 15 },
            { id: "ry4-boyuk-l1-b4", type: "numeric", prompt: "999 999-dan sonra hansı ədəd gəlir?", answer: 1000000, xp: 15 },
            { id: "ry4-boyuk-l1-b5", type: "numeric", prompt: "3 minlik + 3 təklik = ?", answer: 3003, xp: 15 },
          ],
        },
        {
          id: "ry4-boyuk-l2",
          title: "Yuvarlaqlaşdırma",
          intro: "Böyük ədədləri təxmini demək.",
          sections: [
            { heading: "Qayda", body: "Onluğa yuvarlaqlaşdırarkən sonuncu rəqəmə bax: 5 və ya böyükdürsə yuxarı, kiçikdirsə aşağı. 47 → 50, 43 → 40." },
            { heading: "Nə üçün?", body: "Təxmini hesab sürətli qərar verməyə kömək edir: 198 + 302 ≈ 200 + 300 = 500." },
          ],
          tasks: [
            { id: "ry4-boyuk-l2-t1", type: "numeric", prompt: "47 ədədini onluğa yuvarlaqlaşdır.", answer: 50, xp: 10 },
            { id: "ry4-boyuk-l2-t2", type: "numeric", prompt: "43 ədədini onluğa yuvarlaqlaşdır.", answer: 40, xp: 10 },
            { id: "ry4-boyuk-l2-t3", type: "numeric", prompt: "356 ədədini yüzlüyə yuvarlaqlaşdır.", answer: 400, xp: 10 },
            { id: "ry4-boyuk-l2-t4", type: "numeric", prompt: "1240 ədədini yüzlüyə yuvarlaqlaşdır.", answer: 1200, xp: 10 },
            { id: "ry4-boyuk-l2-t5", type: "numeric", prompt: "85 ədədini onluğa yuvarlaqlaşdır.", answer: 90, xp: 10 },
            { id: "ry4-boyuk-l2-t6", type: "numeric", prompt: "2500 ədədini minliyə yuvarlaqlaşdır.", answer: 3000, xp: 10 },
            { id: "ry4-boyuk-l2-t7", type: "multiple_choice", prompt: "Yuvarlaqlaşdırarkən hansı rəqəmə baxırıq?", options: ["Sonrakı mərtəbənin rəqəminə", "Birinci rəqəmə", "Bütün rəqəmlərə", "Heç birinə"], correctIndex: 0, xp: 10 },
            { id: "ry4-boyuk-l2-t8", type: "numeric", prompt: "198 + 302 ifadəsinin təxmini nəticəsi nədir? (yüzlüklə)", answer: 500, xp: 10 },
            { id: "ry4-boyuk-l2-t9", type: "numeric", prompt: "7842 ədədini minliyə yuvarlaqlaşdır.", answer: 8000, xp: 10 },
            { id: "ry4-boyuk-l2-t10", type: "numeric", prompt: "64 ədədini onluğa yuvarlaqlaşdır.", answer: 60, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry4-boyuk-l2-b1", type: "numeric", prompt: "4 999 ədədini minliyə yuvarlaqlaşdır.", answer: 5000, xp: 15 },
            { id: "ry4-boyuk-l2-b2", type: "numeric", prompt: "12 345 ədədini yüzlüyə yuvarlaqlaşdır.", answer: 12300, xp: 15 },
            { id: "ry4-boyuk-l2-b3", type: "multiple_choice", prompt: "Niyə yuvarlaqlaşdırma faydalıdır?", options: ["Tez təxmini hesab üçün", "Cavabı dəqiqləşdirmək üçün", "Yazını uzatmaq üçün", "Faydası yoxdur"], correctIndex: 0, xp: 15 },
            { id: "ry4-boyuk-l2-b4", type: "numeric", prompt: "999 ədədini yüzlüyə yuvarlaqlaşdır.", answer: 1000, xp: 15 },
          ],
        },
        {
          id: "ry4-boyuk-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-boyuk-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 2. Çoxrəqəmli vurma ═══════════════
    {
      id: "ry4-vurma",
      title: "Çoxrəqəmli vurma",
      description: "İkirəqəmli ədədləri birrəqəmli və ikirəqəmli ədədlərə vurmaq.",
      lessons: [
        {
          id: "ry4-vurma-l1",
          title: "Vurma",
          intro: "Böyük ədədləri vururuq.",
          sections: [
            { heading: "Vurma", body: "23 × 3 = 69. 10 × 10 = 100. 12 × 12 = 144. Mərtəbələri ayrı-ayrı vurub toplayırıq." },
          ],
          tasks: [
            { id: "ry4-vurma-l1-t1", type: "numeric", prompt: "12 × 3 = ?", answer: 36, xp: 10 },
            { id: "ry4-vurma-l1-t2", type: "numeric", prompt: "23 × 3 = ?", answer: 69, xp: 10 },
            { id: "ry4-vurma-l1-t3", type: "numeric", prompt: "14 × 2 = ?", answer: 28, xp: 10 },
            { id: "ry4-vurma-l1-t4", type: "numeric", prompt: "25 × 4 = ?", answer: 100, xp: 10 },
            { id: "ry4-vurma-l1-t5", type: "numeric", prompt: "10 × 10 = ?", answer: 100, xp: 10 },
            { id: "ry4-vurma-l1-t6", type: "numeric", prompt: "20 × 5 = ?", answer: 100, xp: 10 },
            { id: "ry4-vurma-l1-t7", type: "numeric", prompt: "11 × 11 = ?", answer: 121, xp: 10 },
            { id: "ry4-vurma-l1-t8", type: "numeric", prompt: "12 × 12 = ?", answer: 144, xp: 10 },
            { id: "ry4-vurma-l1-t9", type: "numeric", prompt: "30 × 3 = ?", answer: 90, xp: 10 },
            { id: "ry4-vurma-l1-t10", type: "numeric", prompt: "15 × 4 = ?", answer: 60, xp: 10 },
            { id: "ry4-vurma-l1-t11", type: "numeric", prompt: "100 × 5 = ?", answer: 500, xp: 10 },
            { id: "ry4-vurma-l1-t12", type: "numeric", prompt: "21 × 4 = ?", answer: 84, xp: 10 },
            { id: "ry4-vurma-l1-t13", type: "numeric", prompt: "13 × 5 = ?", answer: 65, xp: 10 },
            { id: "ry4-vurma-l1-t14", type: "numeric", prompt: "40 × 6 = ?", answer: 240, xp: 10 },
            { id: "ry4-vurma-l1-t15", type: "numeric", prompt: "24 × 3 = ?", answer: 72, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry4-vurma-l1-b1", type: "numeric", prompt: "123 × 2 = ?", answer: 246, xp: 15 },
            { id: "ry4-vurma-l1-b2", type: "numeric", prompt: "15 × 12 = ?", answer: 180, xp: 15 },
            { id: "ry4-vurma-l1-b3", type: "numeric", prompt: "25 × 8 = ?", answer: 200, xp: 15 },
            { id: "ry4-vurma-l1-b4", type: "numeric", prompt: "100 × 100 = ?", answer: 10000, xp: 15 },
            { id: "ry4-vurma-l1-b5", type: "numeric", prompt: "32 × 3 = ?", answer: 96, xp: 15 },
          ],
        },
        {
          id: "ry4-vurma-l2",
          title: "İkirəqəmliyə vurma",
          intro: "Sütun üsulu ilə iki mərtəbəli vurma.",
          sections: [
            { heading: "Addımlar", body: "23 × 14: əvvəl 23 × 4 = 92, sonra 23 × 10 = 230. Cəm: 92 + 230 = 322." },
            { heading: "Yoxlama", body: "Nəticəni təxmin et: 23 ≈ 20, 14 ≈ 10 → təxmini 200. Cavab 322 — məntiqlidir." },
          ],
          tasks: [
            { id: "ry4-vurma-l2-t1", type: "numeric", prompt: "23 × 14 = ?", answer: 322, xp: 10 },
            { id: "ry4-vurma-l2-t2", type: "numeric", prompt: "31 × 12 = ?", answer: 372, xp: 10 },
            { id: "ry4-vurma-l2-t3", type: "numeric", prompt: "45 × 20 = ?", answer: 900, xp: 10 },
            { id: "ry4-vurma-l2-t4", type: "numeric", prompt: "16 × 15 = ?", answer: 240, xp: 10 },
            { id: "ry4-vurma-l2-t5", type: "numeric", prompt: "24 × 11 = ?", answer: 264, xp: 10 },
            { id: "ry4-vurma-l2-t6", type: "numeric", prompt: "52 × 13 = ?", answer: 676, xp: 10 },
            { id: "ry4-vurma-l2-t7", type: "numeric", prompt: "18 × 12 = ?", answer: 216, xp: 10 },
            { id: "ry4-vurma-l2-t8", type: "numeric", prompt: "100 × 25 = ?", answer: 2500, xp: 10 },
            { id: "ry4-vurma-l2-t9", type: "numeric", prompt: "34 × 10 = ?", answer: 340, xp: 10 },
            { id: "ry4-vurma-l2-t10", type: "numeric", prompt: "27 × 21 = ?", answer: 567, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry4-vurma-l2-b1", type: "numeric", prompt: "Kinoteatrda 24 sıra var, hər sırada 18 oturacaq. Neçə oturacaq var?", answer: 432, xp: 15 },
            { id: "ry4-vurma-l2-b2", type: "numeric", prompt: "125 × 8 = ?", answer: 1000, xp: 15 },
            { id: "ry4-vurma-l2-b3", type: "numeric", prompt: "36 × 25 = ?", answer: 900, xp: 15 },
            { id: "ry4-vurma-l2-b4", type: "numeric", prompt: "19 × 19 = ?", answer: 361, xp: 15 },
          ],
        },
        {
          id: "ry4-vurma-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-vurma-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 3. Çoxrəqəmli bölmə ═══════════════
    {
      id: "ry4-bolme",
      title: "Çoxrəqəmli bölmə",
      description: "İkirəqəmli və üçrəqəmli ədədləri bölmək, qalıqlı bölmə.",
      lessons: [
        {
          id: "ry4-bolme-l1",
          title: "Bölmə",
          intro: "Böyük ədədləri bölürük.",
          sections: [
            { heading: "Bölmə", body: "48 ÷ 4 = 12. 100 ÷ 5 = 20. Bölünən ÷ bölən = qismət. Qalıqlı bölmə: 13 ÷ 4 = 3 (qalıq 1)." },
          ],
          tasks: [
            { id: "ry4-bolme-l1-t1", type: "numeric", prompt: "48 ÷ 4 = ?", answer: 12, xp: 10 },
            { id: "ry4-bolme-l1-t2", type: "numeric", prompt: "60 ÷ 5 = ?", answer: 12, xp: 10 },
            { id: "ry4-bolme-l1-t3", type: "numeric", prompt: "100 ÷ 5 = ?", answer: 20, xp: 10 },
            { id: "ry4-bolme-l1-t4", type: "numeric", prompt: "84 ÷ 4 = ?", answer: 21, xp: 10 },
            { id: "ry4-bolme-l1-t5", type: "numeric", prompt: "90 ÷ 3 = ?", answer: 30, xp: 10 },
            { id: "ry4-bolme-l1-t6", type: "numeric", prompt: "72 ÷ 6 = ?", answer: 12, xp: 10 },
            { id: "ry4-bolme-l1-t7", type: "numeric", prompt: "144 ÷ 12 = ?", answer: 12, xp: 10 },
            { id: "ry4-bolme-l1-t8", type: "numeric", prompt: "200 ÷ 4 = ?", answer: 50, xp: 10 },
            { id: "ry4-bolme-l1-t9", type: "numeric", prompt: "55 ÷ 5 = ?", answer: 11, xp: 10 },
            { id: "ry4-bolme-l1-t10", type: "numeric", prompt: "96 ÷ 8 = ?", answer: 12, xp: 10 },
            { id: "ry4-bolme-l1-t11", type: "numeric", prompt: "13 ÷ 4 bölməsində qalıq neçədir?", answer: 1, xp: 10 },
            { id: "ry4-bolme-l1-t12", type: "numeric", prompt: "17 ÷ 5 bölməsində qalıq neçədir?", answer: 2, xp: 10 },
            { id: "ry4-bolme-l1-t13", type: "numeric", prompt: "300 ÷ 3 = ?", answer: 100, xp: 10 },
            { id: "ry4-bolme-l1-t14", type: "numeric", prompt: "63 ÷ 3 = ?", answer: 21, xp: 10 },
            { id: "ry4-bolme-l1-t15", type: "numeric", prompt: "120 ÷ 4 = ?", answer: 30, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry4-bolme-l1-b1", type: "numeric", prompt: "500 ÷ 5 = ?", answer: 100, xp: 15 },
            { id: "ry4-bolme-l1-b2", type: "numeric", prompt: "25 ÷ 4 bölməsində qalıq neçədir?", answer: 1, xp: 15 },
            { id: "ry4-bolme-l1-b3", type: "numeric", prompt: "168 ÷ 8 = ?", answer: 21, xp: 15 },
            { id: "ry4-bolme-l1-b4", type: "numeric", prompt: "1000 ÷ 10 = ?", answer: 100, xp: 15 },
            { id: "ry4-bolme-l1-b5", type: "numeric", prompt: "132 ÷ 11 = ?", answer: 12, xp: 15 },
          ],
        },
        {
          id: "ry4-bolme-l2",
          title: "İkirəqəmliyə bölmə",
          intro: "Böyük ədədləri addım-addım bölmək.",
          sections: [
            { heading: "Üsul", body: "144 ÷ 12: 12 × 10 = 120, qalıq 24. 12 × 2 = 24, qalıq 0. Deməli 144 ÷ 12 = 12." },
            { heading: "Yoxlama", body: "Nəticəni bölənə vur: 12 × 12 = 144. ✓" },
          ],
          tasks: [
            { id: "ry4-bolme-l2-t1", type: "numeric", prompt: "144 ÷ 12 = ?", answer: 12, xp: 10 },
            { id: "ry4-bolme-l2-t2", type: "numeric", prompt: "240 ÷ 20 = ?", answer: 12, xp: 10 },
            { id: "ry4-bolme-l2-t3", type: "numeric", prompt: "198 ÷ 11 = ?", answer: 18, xp: 10 },
            { id: "ry4-bolme-l2-t4", type: "numeric", prompt: "375 ÷ 25 = ?", answer: 15, xp: 10 },
            { id: "ry4-bolme-l2-t5", type: "numeric", prompt: "480 ÷ 16 = ?", answer: 30, xp: 10 },
            { id: "ry4-bolme-l2-t6", type: "numeric", prompt: "169 ÷ 13 = ?", answer: 13, xp: 10 },
            { id: "ry4-bolme-l2-t7", type: "numeric", prompt: "600 ÷ 24 = ?", answer: 25, xp: 10 },
            { id: "ry4-bolme-l2-t8", type: "numeric", prompt: "840 ÷ 40 = ?", answer: 21, xp: 10 },
            { id: "ry4-bolme-l2-t9", type: "multiple_choice", prompt: "Bölmənin nəticəsini necə yoxlayırıq?", options: ["Bölənə vururuq", "Bölənə bölürük", "Toplayırıq", "Çıxırıq"], correctIndex: 0, xp: 10 },
            { id: "ry4-bolme-l2-t10", type: "numeric", prompt: "252 ÷ 14 = ?", answer: 18, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry4-bolme-l2-b1", type: "numeric", prompt: "288 şəkil 24 albomda bərabər yerləşdi. Hər albomda neçə şəkil var?", answer: 12, xp: 15 },
            { id: "ry4-bolme-l2-b2", type: "numeric", prompt: "1000 ÷ 25 = ?", answer: 40, xp: 15 },
            { id: "ry4-bolme-l2-b3", type: "numeric", prompt: "756 ÷ 21 = ?", answer: 36, xp: 15 },
            { id: "ry4-bolme-l2-b4", type: "numeric", prompt: "945 ÷ 35 = ?", answer: 27, xp: 15 },
          ],
        },
        {
          id: "ry4-bolme-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-bolme-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 4. Kəsrlər ═══════════════
    {
      id: "ry4-kesr",
      title: "Kəsrlər",
      description: "Kəsrlərin müqayisəsi və eyni məxrəcli kəsrlərin toplanması-çıxılması.",
      lessons: [
        {
          id: "ry4-kesr-l1",
          title: "Kəsrlərlə əməllər",
          intro: "Kəsrləri müqayisə edək, toplayaq, çıxaq.",
          sections: [
            { heading: "Müqayisə", body: "Eyni məxrəcli kəsrlərdən sürəti böyük olan böyükdür: 3/5 > 2/5. Sürət eynidirsə, məxrəci kiçik olan böyükdür: 1/2 > 1/4." },
            { heading: "Toplama və çıxma", body: "Eyni məxrəcli kəsrlərdə sürətlər toplanır/çıxılır, məxrəc dəyişmir: 1/5 + 2/5 = 3/5. 4/7 − 1/7 = 3/7." },
          ],
          tasks: [
            { id: "ry4-kesr-l1-t1", type: "multiple_choice", prompt: "3/5 və 2/5 kəsrlərindən böyüyü hansıdır?", options: ["3/5", "2/5", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t2", type: "multiple_choice", prompt: "1/2 və 1/4 kəsrlərindən böyüyü hansıdır?", options: ["1/2", "1/4", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t3", type: "multiple_choice", prompt: "1/5 + 2/5 = ?", options: ["3/5", "3/10", "2/5", "3/25"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t4", type: "multiple_choice", prompt: "4/7 − 1/7 = ?", options: ["3/7", "3/14", "5/7", "3/0"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t5", type: "multiple_choice", prompt: "2/6 + 3/6 = ?", options: ["5/6", "5/12", "6/6", "5/36"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t6", type: "multiple_choice", prompt: "5/8 − 2/8 = ?", options: ["3/8", "3/16", "7/8", "3/0"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t7", type: "multiple_choice", prompt: "1/3 + 1/3 = ?", options: ["2/3", "2/6", "1/3", "2/9"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t8", type: "multiple_choice", prompt: "Hansı kəsr daha böyükdür: 1/3 yoxsa 1/6?", options: ["1/3", "1/6", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t9", type: "multiple_choice", prompt: "3/4 və 1/4 kəsrlərindən böyüyü hansıdır?", options: ["3/4", "1/4", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t10", type: "multiple_choice", prompt: "2/9 + 4/9 = ?", options: ["6/9", "6/18", "8/9", "6/81"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t11", type: "multiple_choice", prompt: "7/10 − 3/10 = ?", options: ["4/10", "4/20", "10/10", "4/0"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t12", type: "multiple_choice", prompt: "2/4 + 2/4 = ? (bütöv)", options: ["1 (bütöv)", "4/8", "2/4", "4/16"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t13", type: "multiple_choice", prompt: "Eyni məxrəcli kəsrləri toplayanda nə edirik?", options: ["sürətləri toplayırıq", "məxrəcləri toplayırıq", "hər ikisini toplayırıq", "vururuq"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t14", type: "multiple_choice", prompt: "6/8 − 4/8 = ?", options: ["2/8", "2/16", "10/8", "2/0"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l1-t15", type: "multiple_choice", prompt: "1/6 + 4/6 = ?", options: ["5/6", "5/12", "5/36", "6/6"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry4-kesr-l1-b1", type: "multiple_choice", prompt: "3/10 + 7/10 = ? (bütöv)", options: ["1 (bütöv)", "10/20", "10/100", "3/7"], correctIndex: 0, xp: 15 },
            { id: "ry4-kesr-l1-b2", type: "numeric", prompt: "12 almanın 1/4-i neçədir?", answer: 3, xp: 15 },
            { id: "ry4-kesr-l1-b3", type: "numeric", prompt: "20 konfetin 3/4-ü neçədir? (20:4×3)", answer: 15, xp: 15 },
            { id: "ry4-kesr-l1-b4", type: "multiple_choice", prompt: "1/2 kəsri hansı kəsrə bərabərdir?", options: ["2/4", "1/4", "3/4", "2/3"], correctIndex: 0, xp: 15 },
            { id: "ry4-kesr-l1-b5", type: "multiple_choice", prompt: "5/9 − 5/9 = ?", options: ["0", "1", "5/9", "10/9"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry4-kesr-l2",
          title: "Kəsrləri toplamaq və çıxmaq",
          intro: "Məxrəclər eynidirsə asandır.",
          sections: [
            { heading: "Eyni məxrəc", body: "Yalnız sayları toplayırıq, məxrəc dəyişmir: 2/7 + 3/7 = 5/7." },
            { heading: "Sadələşdirmə", body: "4/8 kəsrini həm sayı, həm məxrəci 4-ə bölsək 1/2 alınır — bu, sadələşdirmədir." },
          ],
          tasks: [
            { id: "ry4-kesr-l2-t1", type: "multiple_choice", prompt: "2/7 + 3/7 = ?", options: ["5/7", "5/14", "6/7", "1/7"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l2-t2", type: "multiple_choice", prompt: "5/9 − 2/9 = ?", options: ["3/9", "3/18", "7/9", "2/9"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l2-t3", type: "multiple_choice", prompt: "4/8 kəsrini sadələşdir.", options: ["1/2", "1/4", "2/4", "4/8"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l2-t4", type: "multiple_choice", prompt: "3/6 kəsrini sadələşdir.", options: ["1/2", "1/3", "2/3", "3/6"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l2-t5", type: "multiple_choice", prompt: "1/5 + 2/5 = ?", options: ["3/5", "3/10", "2/5", "1/10"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l2-t6", type: "multiple_choice", prompt: "Eyni məxrəcli kəsrləri toplayanda məxrəc necə olur?", options: ["Dəyişmir", "Toplanır", "Vurulur", "Bölünür"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l2-t7", type: "multiple_choice", prompt: "6/8 − 2/8 = ?", options: ["4/8", "4/16", "8/8", "2/8"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l2-t8", type: "numeric", prompt: "Bir tortun 3/8-i yeyildi. Neçə səkkizdə bir hissə qaldı? (say ilə)", answer: 5, xp: 10 },
            { id: "ry4-kesr-l2-t9", type: "multiple_choice", prompt: "2/10 kəsrini sadələşdir.", options: ["1/5", "1/10", "2/5", "1/2"], correctIndex: 0, xp: 10 },
            { id: "ry4-kesr-l2-t10", type: "multiple_choice", prompt: "7/7 kəsri neçəyə bərabərdir?", options: ["1", "0", "7", "1/7"], correctIndex: 0, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry4-kesr-l2-b1", type: "multiple_choice", prompt: "1/4 + 1/4 + 1/4 = ?", options: ["3/4", "1/12", "3/12", "1/4"], correctIndex: 0, xp: 15 },
            { id: "ry4-kesr-l2-b2", type: "multiple_choice", prompt: "9/12 kəsrini sadələşdir.", options: ["3/4", "1/3", "2/3", "9/12"], correctIndex: 0, xp: 15 },
            { id: "ry4-kesr-l2-b3", type: "numeric", prompt: "Bir pizzanın 2/6-sını yedim, 3/6-sını qardaşım yedi. Neçə altıda bir hissə qaldı?", answer: 1, xp: 15 },
            { id: "ry4-kesr-l2-b4", type: "multiple_choice", prompt: "5/5 − 2/5 = ?", options: ["3/5", "3/10", "7/5", "2/5"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry4-kesr-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-kesr-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 5. Onluq kəsrlər və ölçmə ═══════════════
    {
      id: "ry4-onluq",
      title: "Onluq kəsrlər və ölçmə",
      description: "Onluq kəsrlərlə tanışlıq və ölçü vahidləri.",
      lessons: [
        {
          id: "ry4-onluq-l1",
          title: "Onluq kəsrlər",
          intro: "Vergüllü ədədlər: 0.5, 1.5, 2.25.",
          sections: [
            { heading: "Onluq kəsr", body: "Vergüldən sonrakı hissə bütövün hissəsidir. 0.5 = yarım = 1/2. 0.25 = dörddə bir = 1/4. 1.5 = bir tam yarım." },
            { heading: "Ölçmə", body: "1 m = 100 sm, 1 km = 1000 m, 1 kq = 1000 q, 1 litr, 1 saat = 60 dəq." },
          ],
          tasks: [
            { id: "ry4-onluq-l1-t1", type: "numeric", prompt: "0.5 + 0.5 = ? (onluq)", answer: 1, xp: 10 },
            { id: "ry4-onluq-l1-t2", type: "numeric", prompt: "1.5 + 0.5 = ? (onluq)", answer: 2, xp: 10 },
            { id: "ry4-onluq-l1-t3", type: "numeric", prompt: "0.25 + 0.25 = ? (onluq)", answer: 0.5, tolerance: 0.001, xp: 10 },
            { id: "ry4-onluq-l1-t4", type: "multiple_choice", prompt: "0.5 hansı kəsrə bərabərdir?", options: ["1/2", "1/4", "1/5", "1/10"], correctIndex: 0, xp: 10 },
            { id: "ry4-onluq-l1-t5", type: "multiple_choice", prompt: "0.25 hansı kəsrə bərabərdir?", options: ["1/4", "1/2", "1/5", "2/5"], correctIndex: 0, xp: 10 },
            { id: "ry4-onluq-l1-t6", type: "numeric", prompt: "2.5 + 2.5 = ? (onluq)", answer: 5, xp: 10 },
            { id: "ry4-onluq-l1-t7", type: "numeric", prompt: "1 m neçə sm-dir?", answer: 100, xp: 10 },
            { id: "ry4-onluq-l1-t8", type: "numeric", prompt: "1 km neçə metrdir?", answer: 1000, xp: 10 },
            { id: "ry4-onluq-l1-t9", type: "numeric", prompt: "1 kq neçə qramdır?", answer: 1000, xp: 10 },
            { id: "ry4-onluq-l1-t10", type: "numeric", prompt: "2 km neçə metrdir?", answer: 2000, xp: 10 },
            { id: "ry4-onluq-l1-t11", type: "numeric", prompt: "1.0 − 0.5 = ? (onluq)", answer: 0.5, tolerance: 0.001, xp: 10 },
            { id: "ry4-onluq-l1-t12", type: "multiple_choice", prompt: "0.5 və 0.25 ədədlərindən böyüyü hansıdır?", options: ["0.5", "0.25", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry4-onluq-l1-t13", type: "numeric", prompt: "3 saat neçə dəqiqədir?", answer: 180, xp: 10 },
            { id: "ry4-onluq-l1-t14", type: "numeric", prompt: "500 q + 500 q neçə kq-dır?", answer: 1, xp: 10 },
            { id: "ry4-onluq-l1-t15", type: "numeric", prompt: "1.5 + 1.5 = ? (onluq)", answer: 3, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry4-onluq-l1-b1", type: "numeric", prompt: "2.75 + 0.25 = ? (onluq)", answer: 3, xp: 15 },
            { id: "ry4-onluq-l1-b2", type: "numeric", prompt: "5 km neçə metrdir?", answer: 5000, xp: 15 },
            { id: "ry4-onluq-l1-b3", type: "multiple_choice", prompt: "0.1 hansı kəsrə bərabərdir?", options: ["1/10", "1/2", "1/4", "1/100"], correctIndex: 0, xp: 15 },
            { id: "ry4-onluq-l1-b4", type: "numeric", prompt: "3.5 − 1.5 = ? (onluq)", answer: 2, xp: 15 },
            { id: "ry4-onluq-l1-b5", type: "numeric", prompt: "2 kq 500 q neçə qramdır?", answer: 2500, xp: 15 },
          ],
        },
        {
          id: "ry4-onluq-l2",
          title: "Onluq kəsrlərlə əməllər",
          intro: "Vergüllər alt-alta düşməlidir.",
          sections: [
            { heading: "Toplama-çıxma", body: "Vergülləri düz alt-alta yaz, sonra adi kimi topla: 2,5 + 1,3 = 3,8." },
            { heading: "Ölçmə ilə əlaqə", body: "1 m = 100 sm, deməli 1,5 m = 150 sm. 1 kq = 1000 q, deməli 2,5 kq = 2500 q." },
          ],
          tasks: [
            { id: "ry4-onluq-l2-t1", type: "numeric", prompt: "2,5 + 1,3 = ? (nəticəni onda bir ilə yaz, məs. 3.8)", answer: 3.8, xp: 10 },
            { id: "ry4-onluq-l2-t2", type: "numeric", prompt: "5,7 − 2,4 = ?", answer: 3.3, xp: 10 },
            { id: "ry4-onluq-l2-t3", type: "numeric", prompt: "0,5 + 0,5 = ?", answer: 1, xp: 10 },
            { id: "ry4-onluq-l2-t4", type: "numeric", prompt: "1,5 metr neçə santimetrdir?", answer: 150, xp: 10 },
            { id: "ry4-onluq-l2-t5", type: "numeric", prompt: "2,5 kiloqram neçə qramdır?", answer: 2500, xp: 10 },
            { id: "ry4-onluq-l2-t6", type: "numeric", prompt: "3,2 + 4,8 = ?", answer: 8, xp: 10 },
            { id: "ry4-onluq-l2-t7", type: "numeric", prompt: "10 − 2,5 = ?", answer: 7.5, xp: 10 },
            { id: "ry4-onluq-l2-t8", type: "multiple_choice", prompt: "Onluq kəsrləri toplayanda nəyə diqqət edirik?", options: ["Vergüllər alt-alta düşməlidir", "Rəqəmlərin sayına", "Böyüklüyünə", "Heç nəyə"], correctIndex: 0, xp: 10 },
            { id: "ry4-onluq-l2-t9", type: "numeric", prompt: "0,25 metr neçə santimetrdir?", answer: 25, xp: 10 },
            { id: "ry4-onluq-l2-t10", type: "numeric", prompt: "1,75 + 0,25 = ?", answer: 2, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry4-onluq-l2-b1", type: "numeric", prompt: "4,6 − 1,85 = ?", answer: 2.75, xp: 15 },
            { id: "ry4-onluq-l2-b2", type: "numeric", prompt: "0,5 kq + 750 q neçə qramdır?", answer: 1250, xp: 15 },
            { id: "ry4-onluq-l2-b3", type: "numeric", prompt: "12,5 ÷ 5 = ?", answer: 2.5, xp: 15 },
            { id: "ry4-onluq-l2-b4", type: "numeric", prompt: "2,5 × 4 = ?", answer: 10, xp: 15 },
          ],
        },
        {
          id: "ry4-onluq-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-onluq-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
    // ═══════════════ 6. Sahə, əməllər sırası və məsələlər ═══════════════
    {
      id: "ry4-sahe",
      title: "Sahə, əməllər sırası və məsələlər",
      description: "Düzbucaqlının sahəsi, əməllərin sırası və mətn məsələləri.",
      lessons: [
        {
          id: "ry4-sahe-l1",
          title: "Sahə və əməllər sırası",
          intro: "Sahə hesablamaq və əməllərin düzgün sırası.",
          sections: [
            { heading: "Sahə", body: "Düzbucaqlının sahəsi = uzunluq × en. Kvadratın sahəsi = tərəf × tərəf. Sahə kvadrat vahidlərlə (kv.sm, kv.m) ölçülür." },
            { heading: "Əməllər sırası", body: "Əvvəlcə mötərizə, sonra vurma və bölmə, sonra toplama və çıxma: 2 + 3 × 4 = 2 + 12 = 14." },
          ],
          tasks: [
            { id: "ry4-sahe-l1-t1", type: "numeric", prompt: "Düzbucaqlının uzunluğu 5, eni 3-dür. Sahəsi? (5×3)", answer: 15, xp: 10 },
            { id: "ry4-sahe-l1-t2", type: "numeric", prompt: "Kvadratın tərəfi 4-dür. Sahəsi? (4×4)", answer: 16, xp: 10 },
            { id: "ry4-sahe-l1-t3", type: "numeric", prompt: "Düzbucaqlının uzunluğu 6, eni 4-dür. Sahəsi?", answer: 24, xp: 10 },
            { id: "ry4-sahe-l1-t4", type: "numeric", prompt: "Kvadratın tərəfi 5-dir. Sahəsi?", answer: 25, xp: 10 },
            { id: "ry4-sahe-l1-t5", type: "numeric", prompt: "2 + 3 × 4 = ?", answer: 14, xp: 10 },
            { id: "ry4-sahe-l1-t6", type: "numeric", prompt: "10 − 2 × 3 = ?", answer: 4, xp: 10 },
            { id: "ry4-sahe-l1-t7", type: "numeric", prompt: "(2 + 3) × 4 = ?", answer: 20, xp: 10 },
            { id: "ry4-sahe-l1-t8", type: "numeric", prompt: "12 ÷ 4 + 5 = ?", answer: 8, xp: 10 },
            { id: "ry4-sahe-l1-t9", type: "numeric", prompt: "6 + 6 ÷ 2 = ?", answer: 9, xp: 10 },
            { id: "ry4-sahe-l1-t10", type: "numeric", prompt: "Düzbucaqlının uzunluğu 10, eni 2-dir. Sahəsi?", answer: 20, xp: 10 },
            { id: "ry4-sahe-l1-t11", type: "numeric", prompt: "3 × 3 + 1 = ?", answer: 10, xp: 10 },
            { id: "ry4-sahe-l1-t12", type: "numeric", prompt: "20 − 4 × 2 = ?", answer: 12, xp: 10 },
            { id: "ry4-sahe-l1-t13", type: "numeric", prompt: "Kvadratın tərəfi 10-dur. Sahəsi?", answer: 100, xp: 10 },
            { id: "ry4-sahe-l1-t14", type: "numeric", prompt: "(10 − 4) × 2 = ?", answer: 12, xp: 10 },
            { id: "ry4-sahe-l1-t15", type: "numeric", prompt: "5 × 2 + 3 × 2 = ?", answer: 16, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry4-sahe-l1-b1", type: "numeric", prompt: "Sahəsi 24, eni 4 olan düzbucaqlının uzunluğu? (24÷4)", answer: 6, xp: 15 },
            { id: "ry4-sahe-l1-b2", type: "numeric", prompt: "2 × (3 + 4) − 5 = ?", answer: 9, xp: 15 },
            { id: "ry4-sahe-l1-b3", type: "numeric", prompt: "100 − 5 × 10 = ?", answer: 50, xp: 15 },
            { id: "ry4-sahe-l1-b4", type: "numeric", prompt: "Kvadratın sahəsi 49-dur. Tərəfi neçədir?", answer: 7, xp: 15 },
            { id: "ry4-sahe-l1-b5", type: "numeric", prompt: "36 ÷ (2 + 4) = ?", answer: 6, xp: 15 },
          ],
        },
        {
          id: "ry4-sahe-l2",
          title: "Mətn məsələləri",
          intro: "Çoxaddımlı məsələlər.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, addımları düşün, hesabla." },
          ],
          tasks: [
            { id: "ry4-sahe-l2-t1", type: "numeric", prompt: "Hər qutuda 12 alma var. 5 qutuda neçə alma var?", answer: 60, xp: 10 },
            { id: "ry4-sahe-l2-t2", type: "numeric", prompt: "144 kitab 12 rəfə bərabər yerləşdi. Hər rəfdə neçə kitab var?", answer: 12, xp: 10 },
            { id: "ry4-sahe-l2-t3", type: "numeric", prompt: "Mağazada 1500 manat var idi, 650 manat xərcləndi. Neçə manat qaldı?", answer: 850, xp: 10 },
            { id: "ry4-sahe-l2-t4", type: "numeric", prompt: "Hər gün 15 səhifə oxuyuram. 6 gündə neçə səhifə oxuyuram?", answer: 90, xp: 10 },
            { id: "ry4-sahe-l2-t5", type: "numeric", prompt: "3 dost hərəsi 25 manat topladı. Cəmi neçə manat var?", answer: 75, xp: 10 },
            { id: "ry4-sahe-l2-t6", type: "numeric", prompt: "200 konfet 8 uşağa bərabər paylandı. Hər biri neçə alır? (200÷8)", answer: 25, xp: 10 },
            { id: "ry4-sahe-l2-t7", type: "numeric", prompt: "Bağda 340 ağac var idi, 160 da əkildi. Neçə ağac oldu?", answer: 500, xp: 10 },
            { id: "ry4-sahe-l2-t8", type: "numeric", prompt: "Hər avtobusda 45 sərnişin var. 3 avtobusda neçə sərnişin var?", answer: 135, xp: 10 },
            { id: "ry4-sahe-l2-t9", type: "numeric", prompt: "Bir qutuda 6 şüşə, hər şüşədə 2 litr su var. Cəmi neçə litr su var?", answer: 12, xp: 10 },
            { id: "ry4-sahe-l2-t10", type: "numeric", prompt: "500 manatlıq telefona 20% (100 manat) endirim edildi. Yeni qiymət?", answer: 400, xp: 10 },
            { id: "ry4-sahe-l2-t11", type: "numeric", prompt: "Sinifdə 32 şagird var, yarısı qızdır. Neçə qız var?", answer: 16, xp: 10 },
            { id: "ry4-sahe-l2-t12", type: "numeric", prompt: "Bir həftədə 7 gün. 12 həftədə neçə gün var? (7×12)", answer: 84, xp: 10 },
            { id: "ry4-sahe-l2-t13", type: "numeric", prompt: "Hər paketdə 25 stiker var. 4 paketdə neçə stiker var?", answer: 100, xp: 10 },
            { id: "ry4-sahe-l2-t14", type: "numeric", prompt: "1000 səhifəlik kitabın 350 səhifəsini oxudum. Neçə səhifə qaldı?", answer: 650, xp: 10 },
            { id: "ry4-sahe-l2-t15", type: "numeric", prompt: "6 kutu, hər kutuda 4 sıra, hər sırada 5 alma. Cəmi neçə alma? (6×4×5)", answer: 120, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry4-sahe-l2-b1", type: "numeric", prompt: "Bağçanın uzunluğu 20 m, eni 10 m-dir. Sahəsi neçə kv.m-dir?", answer: 200, xp: 15 },
            { id: "ry4-sahe-l2-b2", type: "numeric", prompt: "240 manat 4 nəfərə bərabər bölündü, sonra hər biri 10 manat xərclədi. Hər biridə neçə manat qaldı?", answer: 50, xp: 15 },
            { id: "ry4-sahe-l2-b3", type: "numeric", prompt: "Hər gün 20 dəqiqə oxuyuram. 1 həftədə (7 gün) neçə dəqiqə oxuyuram?", answer: 140, xp: 15 },
            { id: "ry4-sahe-l2-b4", type: "numeric", prompt: "3 kutuda hərəsi 24 yumurta var. 2 yumurta sındı. Neçə yumurta qaldı?", answer: 70, xp: 15 },
            { id: "ry4-sahe-l2-b5", type: "numeric", prompt: "Kvadrat meydançanın tərəfi 15 m-dir. Perimetri neçə metrdir? (4×15)", answer: 60, xp: 15 },
          ],
        },
        {
          id: "ry4-sahe-l3",
          title: "Əməllər sırası",
          intro: "Hansı əməl əvvəl gəlir?",
          sections: [
            { heading: "Qayda", body: "Əvvəl mötərizə, sonra vurma və bölmə (soldan sağa), ən sonda toplama və çıxma." },
            { heading: "Nümunə", body: "2 + 3 × 4 = 2 + 12 = 14 (14, 20 deyil!). Amma (2 + 3) × 4 = 5 × 4 = 20." },
          ],
          tasks: [
            { id: "ry4-sahe-l3-t1", type: "numeric", prompt: "2 + 3 × 4 = ?", answer: 14, xp: 10 },
            { id: "ry4-sahe-l3-t2", type: "numeric", prompt: "(2 + 3) × 4 = ?", answer: 20, xp: 10 },
            { id: "ry4-sahe-l3-t3", type: "numeric", prompt: "10 − 2 × 3 = ?", answer: 4, xp: 10 },
            { id: "ry4-sahe-l3-t4", type: "numeric", prompt: "20 ÷ 4 + 3 = ?", answer: 8, xp: 10 },
            { id: "ry4-sahe-l3-t5", type: "numeric", prompt: "6 + 6 ÷ 2 = ?", answer: 9, xp: 10 },
            { id: "ry4-sahe-l3-t6", type: "numeric", prompt: "(10 − 4) ÷ 3 = ?", answer: 2, xp: 10 },
            { id: "ry4-sahe-l3-t7", type: "multiple_choice", prompt: "Hansı əməl birinci yerinə yetirilir?", options: ["Mötərizə", "Toplama", "Çıxma", "Fərqi yoxdur"], correctIndex: 0, xp: 10 },
            { id: "ry4-sahe-l3-t8", type: "numeric", prompt: "5 × 2 + 3 × 3 = ?", answer: 19, xp: 10 },
            { id: "ry4-sahe-l3-t9", type: "numeric", prompt: "100 ÷ 10 ÷ 2 = ?", answer: 5, xp: 10 },
            { id: "ry4-sahe-l3-t10", type: "numeric", prompt: "(8 + 2) × (5 − 3) = ?", answer: 20, xp: 10 },
          ],
          bonusTasks: [
            { id: "ry4-sahe-l3-b1", type: "numeric", prompt: "3 + 4 × 5 − 6 = ?", answer: 17, xp: 15 },
            { id: "ry4-sahe-l3-b2", type: "numeric", prompt: "(12 ÷ 4 + 2) × 3 = ?", answer: 15, xp: 15 },
            { id: "ry4-sahe-l3-b3", type: "multiple_choice", prompt: "2 + 3 × 4 ifadəsində niyə 20 alınmır?", options: ["Çünki vurma toplamadan əvvəl gəlir", "Çünki səhv yazılıb", "Çünki mötərizə var", "20 doğrudur"], correctIndex: 0, xp: 15 },
            { id: "ry4-sahe-l3-b4", type: "numeric", prompt: "50 − (10 + 5) × 2 = ?", answer: 20, xp: 15 },
          ],
        },
        {
          id: "ry4-sahe-chest",
          title: "Sandıq",
          kind: "chest",
          intro: "Buraya çatdın! Sandığı aç və mükafatını al.",
          tasks: [],
        },
        {
          id: "ry4-sahe-test",
          title: "Bölmə sonu test",
          kind: "test",
          intro: "Bu bölmədə öyrəndiklərini yoxla — suallar bütün dərslərdən qarışıq gəlir.",
          tasks: [],
        },
      ],
    },
  ],
};
