// Riyaziyyat — 1-ci sinif proqramı (Azərbaycan kurikuluma uyğun).
// Bölmələr: 1) Ədədlər 0-10 və sayma  2) 10 dairəsində toplama  3) 10 dairəsində çıxma
// 4) Ədədlər 11-20  5) 20 dairəsində toplama və çıxma  6) Müqayisə, fiqurlar, məsələlər.
// 1-ci sinif üçün suallar ÇOX SADƏdir (qısa mətn, rəqəm cavablar). id prefiksi ry1-*.

import type { Subject } from "../types";

export const math1: Subject = {
  slug: "riyaziyyat-1",
  name: "Riyaziyyat",
  grade: 1,
  icon: "R",
  color: "sky",
  units: [
    // ═══════════════ 1. Ədədlər 0-10 və sayma ═══════════════
    {
      id: "ry1-sayma",
      title: "Ədədlər 0-10 və sayma",
      description: "0-dan 10-a qədər ədədləri tanımaq, saymaq və sıralamaq.",
      lessons: [
        {
          id: "ry1-sayma-l1",
          title: "1-dən 10-a sayma",
          intro: "Ədədləri sıra ilə saymağı öyrənək.",
          sections: [
            { heading: "Sayma", body: "Bir, iki, üç, dörd, beş, altı, yeddi, səkkiz, doqquz, on. Rəqəmlərlə: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10." },
            { heading: "Növbəti ədəd", body: "Hər ədəddən sonra gələn ədəd 1 böyükdür: 3-dən sonra 4 gəlir." },
          ],
          tasks: [
            { id: "ry1-sayma-l1-t1", type: "numeric", prompt: "1-dən sonra hansı ədəd gəlir?", answer: 2, xp: 10 },
            { id: "ry1-sayma-l1-t2", type: "numeric", prompt: "2-dən sonra hansı ədəd gəlir?", answer: 3, xp: 10 },
            { id: "ry1-sayma-l1-t3", type: "numeric", prompt: "3-dən sonra hansı ədəd gəlir?", answer: 4, xp: 10 },
            { id: "ry1-sayma-l1-t4", type: "numeric", prompt: "4-dən sonra hansı ədəd gəlir?", answer: 5, xp: 10 },
            { id: "ry1-sayma-l1-t5", type: "numeric", prompt: "5-dən sonra hansı ədəd gəlir?", answer: 6, xp: 10 },
            { id: "ry1-sayma-l1-t6", type: "numeric", prompt: "6-dan sonra hansı ədəd gəlir?", answer: 7, xp: 10 },
            { id: "ry1-sayma-l1-t7", type: "numeric", prompt: "7-dən sonra hansı ədəd gəlir?", answer: 8, xp: 10 },
            { id: "ry1-sayma-l1-t8", type: "numeric", prompt: "8-dən sonra hansı ədəd gəlir?", answer: 9, xp: 10 },
            { id: "ry1-sayma-l1-t9", type: "numeric", prompt: "9-dan sonra hansı ədəd gəlir?", answer: 10, xp: 10 },
            { id: "ry1-sayma-l1-t10", type: "multiple_choice", prompt: "'beş' ədədi rəqəmlə necə yazılır?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l1-t11", type: "multiple_choice", prompt: "'yeddi' ədədi rəqəmlə necə yazılır?", options: ["7", "8", "6", "9"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l1-t12", type: "multiple_choice", prompt: "🍎🍎🍎 — neçə alma var?", options: ["3", "2", "4", "5"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l1-t13", type: "multiple_choice", prompt: "⭐⭐⭐⭐⭐ — neçə ulduz var?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l1-t14", type: "numeric", prompt: "Ən kiçik birrəqəmli ədəd (0-dan başqa) hansıdır?", answer: 1, xp: 10 },
            { id: "ry1-sayma-l1-t15", type: "numeric", prompt: "Ən böyük birrəqəmli ədəd hansıdır?", answer: 9, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-sayma-l1-b1", type: "multiple_choice", prompt: "🐟🐟🐟🐟 — neçə balıq var?", options: ["4", "3", "5", "6"], correctIndex: 0, xp: 15 },
            { id: "ry1-sayma-l1-b2", type: "numeric", prompt: "10-dan əvvəl gələn ədəd hansıdır?", answer: 9, xp: 15 },
            { id: "ry1-sayma-l1-b3", type: "multiple_choice", prompt: "'on' ədədi rəqəmlə necə yazılır?", options: ["10", "1", "100", "0"], correctIndex: 0, xp: 15 },
            { id: "ry1-sayma-l1-b4", type: "numeric", prompt: "6-dan əvvəl gələn ədəd hansıdır?", answer: 5, xp: 15 },
            { id: "ry1-sayma-l1-b5", type: "multiple_choice", prompt: "🎈🎈 — neçə şar var?", options: ["2", "1", "3", "4"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-sayma-l2",
          title: "Ədədləri müqayisə et",
          intro: "Hansı ədəd böyük, hansı kiçikdir?",
          sections: [
            { heading: "Böyük və kiçik", body: "Sayma sırasında sonra gələn ədəd böyükdür: 7 > 3. Əvvəl gələn kiçikdir: 3 < 7." },
          ],
          tasks: [
            { id: "ry1-sayma-l2-t1", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["7", "3", "hər ikisi bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t2", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["9", "5", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t3", type: "multiple_choice", prompt: "Hansı ədəd kiçikdir?", options: ["2", "8", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t4", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["10", "6", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t5", type: "multiple_choice", prompt: "Hansı ədəd kiçikdir?", options: ["1", "4", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t6", type: "multiple_choice", prompt: "4 və 4 — hansı böyükdür?", options: ["bərabərdir", "birinci", "ikinci", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t7", type: "multiple_choice", prompt: "Hansı ədəd böyükdür?", options: ["8", "7", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t8", type: "numeric", prompt: "3 və 6 ədədlərindən böyüyü hansıdır?", answer: 6, xp: 10 },
            { id: "ry1-sayma-l2-t9", type: "numeric", prompt: "2 və 9 ədədlərindən kiçiyi hansıdır?", answer: 2, xp: 10 },
            { id: "ry1-sayma-l2-t10", type: "numeric", prompt: "5 və 8 ədədlərindən böyüyü hansıdır?", answer: 8, xp: 10 },
            { id: "ry1-sayma-l2-t11", type: "numeric", prompt: "10 və 7 ədədlərindən böyüyü hansıdır?", answer: 10, xp: 10 },
            { id: "ry1-sayma-l2-t12", type: "numeric", prompt: "1 və 4 ədədlərindən kiçiyi hansıdır?", answer: 1, xp: 10 },
            { id: "ry1-sayma-l2-t13", type: "multiple_choice", prompt: "Hansı işarə '7 böyükdür 3' üçün düzgündür?", options: [">", "<", "=", "+"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t14", type: "multiple_choice", prompt: "Hansı işarə '2 kiçikdir 5' üçün düzgündür?", options: ["<", ">", "=", "−"], correctIndex: 0, xp: 10 },
            { id: "ry1-sayma-l2-t15", type: "numeric", prompt: "6 və 9 ədədlərindən böyüyü hansıdır?", answer: 9, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-sayma-l2-b1", type: "numeric", prompt: "1, 5, 3 ədədlərindən ən böyüyü hansıdır?", answer: 5, xp: 15 },
            { id: "ry1-sayma-l2-b2", type: "numeric", prompt: "8, 2, 4 ədədlərindən ən kiçiyi hansıdır?", answer: 2, xp: 15 },
            { id: "ry1-sayma-l2-b3", type: "numeric", prompt: "7, 10, 6 ədədlərindən ən böyüyü hansıdır?", answer: 10, xp: 15 },
            { id: "ry1-sayma-l2-b4", type: "multiple_choice", prompt: "Hansı işarə '5 = 5' üçün düzgündür?", options: ["=", ">", "<", "+"], correctIndex: 0, xp: 15 },
            { id: "ry1-sayma-l2-b5", type: "numeric", prompt: "3, 9, 1, 5 ədədlərindən ən böyüyü hansıdır?", answer: 9, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 2. 10 dairəsində toplama ═══════════════
    {
      id: "ry1-toplama",
      title: "10 dairəsində toplama",
      description: "10-a qədər ədədləri toplamağı öyrənək.",
      lessons: [
        {
          id: "ry1-toplama-l1",
          title: "Kiçik ədədləri topla",
          intro: "Toplama — birləşdirmək deməkdir. 2 + 3 = 5.",
          sections: [
            { heading: "Toplama", body: "İki qrupu birləşdirəndə toplama edirik: 🍎🍎 + 🍎🍎🍎 = 5 alma. Yəni 2 + 3 = 5." },
          ],
          tasks: [
            { id: "ry1-toplama-l1-t1", type: "numeric", prompt: "1 + 1 = ?", answer: 2, xp: 10 },
            { id: "ry1-toplama-l1-t2", type: "numeric", prompt: "2 + 1 = ?", answer: 3, xp: 10 },
            { id: "ry1-toplama-l1-t3", type: "numeric", prompt: "2 + 2 = ?", answer: 4, xp: 10 },
            { id: "ry1-toplama-l1-t4", type: "numeric", prompt: "3 + 1 = ?", answer: 4, xp: 10 },
            { id: "ry1-toplama-l1-t5", type: "numeric", prompt: "2 + 3 = ?", answer: 5, xp: 10 },
            { id: "ry1-toplama-l1-t6", type: "numeric", prompt: "3 + 2 = ?", answer: 5, xp: 10 },
            { id: "ry1-toplama-l1-t7", type: "numeric", prompt: "1 + 4 = ?", answer: 5, xp: 10 },
            { id: "ry1-toplama-l1-t8", type: "numeric", prompt: "3 + 3 = ?", answer: 6, xp: 10 },
            { id: "ry1-toplama-l1-t9", type: "numeric", prompt: "4 + 2 = ?", answer: 6, xp: 10 },
            { id: "ry1-toplama-l1-t10", type: "numeric", prompt: "5 + 1 = ?", answer: 6, xp: 10 },
            { id: "ry1-toplama-l1-t11", type: "numeric", prompt: "0 + 4 = ?", answer: 4, xp: 10 },
            { id: "ry1-toplama-l1-t12", type: "numeric", prompt: "2 + 0 = ?", answer: 2, xp: 10 },
            { id: "ry1-toplama-l1-t13", type: "multiple_choice", prompt: "🍎🍎 + 🍎 = ?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 10 },
            { id: "ry1-toplama-l1-t14", type: "multiple_choice", prompt: "⭐⭐⭐ + ⭐⭐ = ?", options: ["5", "4", "6", "3"], correctIndex: 0, xp: 10 },
            { id: "ry1-toplama-l1-t15", type: "numeric", prompt: "4 + 1 = ?", answer: 5, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-toplama-l1-b1", type: "numeric", prompt: "3 + 0 = ?", answer: 3, xp: 15 },
            { id: "ry1-toplama-l1-b2", type: "numeric", prompt: "1 + 1 + 1 = ?", answer: 3, xp: 15 },
            { id: "ry1-toplama-l1-b3", type: "numeric", prompt: "2 + 2 + 1 = ?", answer: 5, xp: 15 },
            { id: "ry1-toplama-l1-b4", type: "multiple_choice", prompt: "🐟🐟🐟 + 🐟 = ?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15 },
            { id: "ry1-toplama-l1-b5", type: "numeric", prompt: "0 + 0 = ?", answer: 0, xp: 15 },
          ],
        },
        {
          id: "ry1-toplama-l2",
          title: "10-a qədər topla",
          intro: "Cəmi 10-a qədər olan toplamalar.",
          sections: [
            { heading: "Böyük cəm", body: "Ədədləri topla, cəm 10-a qədər ola bilər: 6 + 4 = 10, 7 + 2 = 9." },
          ],
          tasks: [
            { id: "ry1-toplama-l2-t1", type: "numeric", prompt: "5 + 2 = ?", answer: 7, xp: 10 },
            { id: "ry1-toplama-l2-t2", type: "numeric", prompt: "4 + 3 = ?", answer: 7, xp: 10 },
            { id: "ry1-toplama-l2-t3", type: "numeric", prompt: "6 + 2 = ?", answer: 8, xp: 10 },
            { id: "ry1-toplama-l2-t4", type: "numeric", prompt: "5 + 3 = ?", answer: 8, xp: 10 },
            { id: "ry1-toplama-l2-t5", type: "numeric", prompt: "4 + 4 = ?", answer: 8, xp: 10 },
            { id: "ry1-toplama-l2-t6", type: "numeric", prompt: "7 + 2 = ?", answer: 9, xp: 10 },
            { id: "ry1-toplama-l2-t7", type: "numeric", prompt: "6 + 3 = ?", answer: 9, xp: 10 },
            { id: "ry1-toplama-l2-t8", type: "numeric", prompt: "5 + 4 = ?", answer: 9, xp: 10 },
            { id: "ry1-toplama-l2-t9", type: "numeric", prompt: "5 + 5 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t10", type: "numeric", prompt: "6 + 4 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t11", type: "numeric", prompt: "7 + 3 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t12", type: "numeric", prompt: "8 + 2 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t13", type: "numeric", prompt: "9 + 1 = ?", answer: 10, xp: 10 },
            { id: "ry1-toplama-l2-t14", type: "numeric", prompt: "8 + 1 = ?", answer: 9, xp: 10 },
            { id: "ry1-toplama-l2-t15", type: "numeric", prompt: "7 + 1 = ?", answer: 8, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-toplama-l2-b1", type: "numeric", prompt: "3 + 3 + 4 = ?", answer: 10, xp: 15 },
            { id: "ry1-toplama-l2-b2", type: "numeric", prompt: "2 + 4 + 4 = ?", answer: 10, xp: 15 },
            { id: "ry1-toplama-l2-b3", type: "multiple_choice", prompt: "6-ya nə əlavə etsək 10 alınar?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 15 },
            { id: "ry1-toplama-l2-b4", type: "multiple_choice", prompt: "7-yə nə əlavə etsək 10 alınar?", options: ["3", "2", "4", "1"], correctIndex: 0, xp: 15 },
            { id: "ry1-toplama-l2-b5", type: "numeric", prompt: "5 + 2 + 3 = ?", answer: 10, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 3. 10 dairəsində çıxma ═══════════════
    {
      id: "ry1-cixma",
      title: "10 dairəsində çıxma",
      description: "10-a qədər ədədlərdən çıxmağı öyrənək.",
      lessons: [
        {
          id: "ry1-cixma-l1",
          title: "Kiçik çıxma",
          intro: "Çıxma — azaltmaq deməkdir. 5 − 2 = 3.",
          sections: [
            { heading: "Çıxma", body: "Bir qrupdan bir neçəsini götürəndə çıxma edirik: 🍎🍎🍎🍎🍎 -dən 2 alma götürsək 3 qalır. Yəni 5 − 2 = 3." },
          ],
          tasks: [
            { id: "ry1-cixma-l1-t1", type: "numeric", prompt: "2 − 1 = ?", answer: 1, xp: 10 },
            { id: "ry1-cixma-l1-t2", type: "numeric", prompt: "3 − 1 = ?", answer: 2, xp: 10 },
            { id: "ry1-cixma-l1-t3", type: "numeric", prompt: "3 − 2 = ?", answer: 1, xp: 10 },
            { id: "ry1-cixma-l1-t4", type: "numeric", prompt: "4 − 1 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l1-t5", type: "numeric", prompt: "4 − 2 = ?", answer: 2, xp: 10 },
            { id: "ry1-cixma-l1-t6", type: "numeric", prompt: "5 − 2 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l1-t7", type: "numeric", prompt: "5 − 3 = ?", answer: 2, xp: 10 },
            { id: "ry1-cixma-l1-t8", type: "numeric", prompt: "5 − 1 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l1-t9", type: "numeric", prompt: "6 − 2 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l1-t10", type: "numeric", prompt: "6 − 3 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l1-t11", type: "numeric", prompt: "4 − 4 = ?", answer: 0, xp: 10 },
            { id: "ry1-cixma-l1-t12", type: "numeric", prompt: "3 − 0 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l1-t13", type: "multiple_choice", prompt: "⭐⭐⭐⭐ -dən 1 götürsək neçə qalır?", options: ["3", "4", "2", "5"], correctIndex: 0, xp: 10 },
            { id: "ry1-cixma-l1-t14", type: "multiple_choice", prompt: "🍎🍎🍎🍎🍎 -dən 2 götürsək neçə qalır?", options: ["3", "2", "4", "5"], correctIndex: 0, xp: 10 },
            { id: "ry1-cixma-l1-t15", type: "numeric", prompt: "6 − 1 = ?", answer: 5, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-cixma-l1-b1", type: "numeric", prompt: "5 − 5 = ?", answer: 0, xp: 15 },
            { id: "ry1-cixma-l1-b2", type: "numeric", prompt: "6 − 4 = ?", answer: 2, xp: 15 },
            { id: "ry1-cixma-l1-b3", type: "numeric", prompt: "6 − 5 = ?", answer: 1, xp: 15 },
            { id: "ry1-cixma-l1-b4", type: "numeric", prompt: "4 − 3 = ?", answer: 1, xp: 15 },
            { id: "ry1-cixma-l1-b5", type: "numeric", prompt: "5 − 0 = ?", answer: 5, xp: 15 },
          ],
        },
        {
          id: "ry1-cixma-l2",
          title: "10-dan çıxma",
          intro: "Böyük ədədlərdən çıxma.",
          sections: [
            { heading: "10-dan çıx", body: "10-dan çıxma: 10 − 4 = 6, 10 − 7 = 3. 8, 9-dan da çıx: 9 − 3 = 6." },
          ],
          tasks: [
            { id: "ry1-cixma-l2-t1", type: "numeric", prompt: "7 − 2 = ?", answer: 5, xp: 10 },
            { id: "ry1-cixma-l2-t2", type: "numeric", prompt: "7 − 3 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l2-t3", type: "numeric", prompt: "8 − 2 = ?", answer: 6, xp: 10 },
            { id: "ry1-cixma-l2-t4", type: "numeric", prompt: "8 − 4 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l2-t5", type: "numeric", prompt: "9 − 3 = ?", answer: 6, xp: 10 },
            { id: "ry1-cixma-l2-t6", type: "numeric", prompt: "9 − 5 = ?", answer: 4, xp: 10 },
            { id: "ry1-cixma-l2-t7", type: "numeric", prompt: "10 − 1 = ?", answer: 9, xp: 10 },
            { id: "ry1-cixma-l2-t8", type: "numeric", prompt: "10 − 2 = ?", answer: 8, xp: 10 },
            { id: "ry1-cixma-l2-t9", type: "numeric", prompt: "10 − 5 = ?", answer: 5, xp: 10 },
            { id: "ry1-cixma-l2-t10", type: "numeric", prompt: "10 − 4 = ?", answer: 6, xp: 10 },
            { id: "ry1-cixma-l2-t11", type: "numeric", prompt: "10 − 7 = ?", answer: 3, xp: 10 },
            { id: "ry1-cixma-l2-t12", type: "numeric", prompt: "10 − 10 = ?", answer: 0, xp: 10 },
            { id: "ry1-cixma-l2-t13", type: "numeric", prompt: "8 − 3 = ?", answer: 5, xp: 10 },
            { id: "ry1-cixma-l2-t14", type: "numeric", prompt: "9 − 4 = ?", answer: 5, xp: 10 },
            { id: "ry1-cixma-l2-t15", type: "numeric", prompt: "10 − 6 = ?", answer: 4, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-cixma-l2-b1", type: "numeric", prompt: "10 − 8 = ?", answer: 2, xp: 15 },
            { id: "ry1-cixma-l2-b2", type: "numeric", prompt: "9 − 9 = ?", answer: 0, xp: 15 },
            { id: "ry1-cixma-l2-b3", type: "multiple_choice", prompt: "10-dan nə çıxsaq 3 qalar?", options: ["7", "6", "8", "5"], correctIndex: 0, xp: 15 },
            { id: "ry1-cixma-l2-b4", type: "numeric", prompt: "8 − 6 = ?", answer: 2, xp: 15 },
            { id: "ry1-cixma-l2-b5", type: "numeric", prompt: "10 − 3 = ?", answer: 7, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 4. Ədədlər 11-20 ═══════════════
    {
      id: "ry1-onluq",
      title: "Ədədlər 11-20",
      description: "11-dən 20-yə qədər ədədləri tanımaq və saymaq.",
      lessons: [
        {
          id: "ry1-onluq-l1",
          title: "11-dən 20-yə sayma",
          intro: "On birdən iyirmiyə qədər sayaq.",
          sections: [
            { heading: "Sayma", body: "11, 12, 13, 14, 15, 16, 17, 18, 19, 20. Bu ədədlər 'on' və bir rəqəmdən ibarətdir: on bir = 11, on beş = 15." },
          ],
          tasks: [
            { id: "ry1-onluq-l1-t1", type: "numeric", prompt: "11-dən sonra hansı ədəd gəlir?", answer: 12, xp: 10 },
            { id: "ry1-onluq-l1-t2", type: "numeric", prompt: "12-dən sonra hansı ədəd gəlir?", answer: 13, xp: 10 },
            { id: "ry1-onluq-l1-t3", type: "numeric", prompt: "14-dən sonra hansı ədəd gəlir?", answer: 15, xp: 10 },
            { id: "ry1-onluq-l1-t4", type: "numeric", prompt: "15-dən sonra hansı ədəd gəlir?", answer: 16, xp: 10 },
            { id: "ry1-onluq-l1-t5", type: "numeric", prompt: "19-dan sonra hansı ədəd gəlir?", answer: 20, xp: 10 },
            { id: "ry1-onluq-l1-t6", type: "multiple_choice", prompt: "'on bir' ədədi rəqəmlə necə yazılır?", options: ["11", "10", "12", "1"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t7", type: "multiple_choice", prompt: "'on beş' ədədi rəqəmlə necə yazılır?", options: ["15", "50", "14", "16"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t8", type: "multiple_choice", prompt: "'iyirmi' ədədi rəqəmlə necə yazılır?", options: ["20", "12", "2", "200"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t9", type: "numeric", prompt: "13-dən əvvəl gələn ədəd hansıdır?", answer: 12, xp: 10 },
            { id: "ry1-onluq-l1-t10", type: "numeric", prompt: "16-dan əvvəl gələn ədəd hansıdır?", answer: 15, xp: 10 },
            { id: "ry1-onluq-l1-t11", type: "numeric", prompt: "20-dən əvvəl gələn ədəd hansıdır?", answer: 19, xp: 10 },
            { id: "ry1-onluq-l1-t12", type: "multiple_choice", prompt: "13 və 17 ədədlərindən böyüyü hansıdır?", options: ["17", "13", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t13", type: "multiple_choice", prompt: "11 və 15 ədədlərindən kiçiyi hansıdır?", options: ["11", "15", "bərabər", "heç biri"], correctIndex: 0, xp: 10 },
            { id: "ry1-onluq-l1-t14", type: "numeric", prompt: "17-dən sonra hansı ədəd gəlir?", answer: 18, xp: 10 },
            { id: "ry1-onluq-l1-t15", type: "numeric", prompt: "10-dan sonra hansı ədəd gəlir?", answer: 11, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-onluq-l1-b1", type: "numeric", prompt: "14, 18, 12 ədədlərindən ən böyüyü hansıdır?", answer: 18, xp: 15 },
            { id: "ry1-onluq-l1-b2", type: "numeric", prompt: "16, 11, 19 ədədlərindən ən kiçiyi hansıdır?", answer: 11, xp: 15 },
            { id: "ry1-onluq-l1-b3", type: "multiple_choice", prompt: "15 ədədi neçə onluq və neçə təkdən ibarətdir?", options: ["1 onluq 5 tək", "5 onluq 1 tək", "15 tək", "2 onluq"], correctIndex: 0, xp: 15 },
            { id: "ry1-onluq-l1-b4", type: "numeric", prompt: "18-dən əvvəl gələn ədəd hansıdır?", answer: 17, xp: 15 },
            { id: "ry1-onluq-l1-b5", type: "numeric", prompt: "12 və 20 arasında 15-dən 1 böyük ədəd hansıdır?", answer: 16, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 5. 20 dairəsində toplama və çıxma ═══════════════
    {
      id: "ry1-yirmi",
      title: "20 dairəsində toplama və çıxma",
      description: "20-yə qədər sadə toplama və çıxma.",
      lessons: [
        {
          id: "ry1-yirmi-l1",
          title: "10-dan yuxarı toplama",
          intro: "10-a bir neçə əlavə edək.",
          sections: [
            { heading: "10 + tək", body: "10 + 3 = 13, 10 + 5 = 15. Onluğa təkləri əlavə edirik." },
          ],
          tasks: [
            { id: "ry1-yirmi-l1-t1", type: "numeric", prompt: "10 + 1 = ?", answer: 11, xp: 10 },
            { id: "ry1-yirmi-l1-t2", type: "numeric", prompt: "10 + 2 = ?", answer: 12, xp: 10 },
            { id: "ry1-yirmi-l1-t3", type: "numeric", prompt: "10 + 3 = ?", answer: 13, xp: 10 },
            { id: "ry1-yirmi-l1-t4", type: "numeric", prompt: "10 + 5 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l1-t5", type: "numeric", prompt: "10 + 7 = ?", answer: 17, xp: 10 },
            { id: "ry1-yirmi-l1-t6", type: "numeric", prompt: "10 + 9 = ?", answer: 19, xp: 10 },
            { id: "ry1-yirmi-l1-t7", type: "numeric", prompt: "11 + 2 = ?", answer: 13, xp: 10 },
            { id: "ry1-yirmi-l1-t8", type: "numeric", prompt: "12 + 3 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l1-t9", type: "numeric", prompt: "13 + 2 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l1-t10", type: "numeric", prompt: "14 + 3 = ?", answer: 17, xp: 10 },
            { id: "ry1-yirmi-l1-t11", type: "numeric", prompt: "15 + 4 = ?", answer: 19, xp: 10 },
            { id: "ry1-yirmi-l1-t12", type: "numeric", prompt: "16 + 2 = ?", answer: 18, xp: 10 },
            { id: "ry1-yirmi-l1-t13", type: "numeric", prompt: "18 + 2 = ?", answer: 20, xp: 10 },
            { id: "ry1-yirmi-l1-t14", type: "numeric", prompt: "10 + 10 = ?", answer: 20, xp: 10 },
            { id: "ry1-yirmi-l1-t15", type: "numeric", prompt: "17 + 2 = ?", answer: 19, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-yirmi-l1-b1", type: "numeric", prompt: "11 + 5 = ?", answer: 16, xp: 15 },
            { id: "ry1-yirmi-l1-b2", type: "numeric", prompt: "13 + 4 = ?", answer: 17, xp: 15 },
            { id: "ry1-yirmi-l1-b3", type: "numeric", prompt: "15 + 5 = ?", answer: 20, xp: 15 },
            { id: "ry1-yirmi-l1-b4", type: "numeric", prompt: "12 + 6 = ?", answer: 18, xp: 15 },
            { id: "ry1-yirmi-l1-b5", type: "numeric", prompt: "16 + 3 = ?", answer: 19, xp: 15 },
          ],
        },
        {
          id: "ry1-yirmi-l2",
          title: "20 dairəsində çıxma",
          intro: "20-yə qədər ədədlərdən çıxaq.",
          sections: [
            { heading: "Çıxma", body: "13 − 3 = 10, 15 − 5 = 10, 20 − 10 = 10. Əvvəlcə təkləri çıxırıq." },
          ],
          tasks: [
            { id: "ry1-yirmi-l2-t1", type: "numeric", prompt: "12 − 2 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t2", type: "numeric", prompt: "13 − 3 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t3", type: "numeric", prompt: "15 − 5 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t4", type: "numeric", prompt: "11 − 1 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t5", type: "numeric", prompt: "14 − 2 = ?", answer: 12, xp: 10 },
            { id: "ry1-yirmi-l2-t6", type: "numeric", prompt: "16 − 3 = ?", answer: 13, xp: 10 },
            { id: "ry1-yirmi-l2-t7", type: "numeric", prompt: "18 − 4 = ?", answer: 14, xp: 10 },
            { id: "ry1-yirmi-l2-t8", type: "numeric", prompt: "19 − 5 = ?", answer: 14, xp: 10 },
            { id: "ry1-yirmi-l2-t9", type: "numeric", prompt: "20 − 10 = ?", answer: 10, xp: 10 },
            { id: "ry1-yirmi-l2-t10", type: "numeric", prompt: "17 − 2 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l2-t11", type: "numeric", prompt: "20 − 5 = ?", answer: 15, xp: 10 },
            { id: "ry1-yirmi-l2-t12", type: "numeric", prompt: "15 − 3 = ?", answer: 12, xp: 10 },
            { id: "ry1-yirmi-l2-t13", type: "numeric", prompt: "13 − 1 = ?", answer: 12, xp: 10 },
            { id: "ry1-yirmi-l2-t14", type: "numeric", prompt: "20 − 1 = ?", answer: 19, xp: 10 },
            { id: "ry1-yirmi-l2-t15", type: "numeric", prompt: "16 − 6 = ?", answer: 10, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-yirmi-l2-b1", type: "numeric", prompt: "18 − 8 = ?", answer: 10, xp: 15 },
            { id: "ry1-yirmi-l2-b2", type: "numeric", prompt: "20 − 3 = ?", answer: 17, xp: 15 },
            { id: "ry1-yirmi-l2-b3", type: "numeric", prompt: "17 − 4 = ?", answer: 13, xp: 15 },
            { id: "ry1-yirmi-l2-b4", type: "numeric", prompt: "19 − 9 = ?", answer: 10, xp: 15 },
            { id: "ry1-yirmi-l2-b5", type: "numeric", prompt: "14 − 4 = ?", answer: 10, xp: 15 },
          ],
        },
      ],
    },
    // ═══════════════ 6. Müqayisə, fiqurlar və məsələlər ═══════════════
    {
      id: "ry1-fiqur",
      title: "Fiqurlar və sadə məsələlər",
      description: "Həndəsi fiqurları tanımaq və sadə mətn məsələlərini həll etmək.",
      lessons: [
        {
          id: "ry1-fiqur-l1",
          title: "Həndəsi fiqurlar",
          intro: "Dairə, kvadrat, üçbucaq, düzbucaqlını tanıyaq.",
          sections: [
            { heading: "Fiqurlar", body: "Dairə — dəyirmi (top kimi). Kvadrat — 4 bərabər tərəf. Üçbucaq — 3 tərəf. Düzbucaqlı — 4 tərəf (2-si uzun)." },
          ],
          tasks: [
            { id: "ry1-fiqur-l1-t1", type: "multiple_choice", prompt: "Üçbucağın neçə tərəfi var?", options: ["3", "4", "2", "5"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t2", type: "multiple_choice", prompt: "Kvadratın neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t3", type: "multiple_choice", prompt: "Dəyirmi (top kimi) fiqur necə adlanır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t4", type: "multiple_choice", prompt: "🔺 hansı fiqurdur?", options: ["üçbucaq", "kvadrat", "dairə", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t5", type: "multiple_choice", prompt: "⬛ hansı fiqurdur?", options: ["kvadrat", "dairə", "üçbucaq", "xətt"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t6", type: "multiple_choice", prompt: "🔵 hansı fiqurdur?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t7", type: "multiple_choice", prompt: "Dairənin neçə küncü var?", options: ["0 (küncü yoxdur)", "3", "4", "1"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t8", type: "multiple_choice", prompt: "Kvadratın neçə küncü var?", options: ["4", "3", "2", "0"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t9", type: "multiple_choice", prompt: "Üçbucağın neçə küncü var?", options: ["3", "4", "2", "0"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t10", type: "multiple_choice", prompt: "Top hansı fiqura oxşayır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t11", type: "multiple_choice", prompt: "Kitab hansı fiqura oxşayır?", options: ["düzbucaqlı", "dairə", "üçbucaq", "top"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t12", type: "multiple_choice", prompt: "Düzbucaqlının neçə tərəfi var?", options: ["4", "3", "5", "2"], correctIndex: 0, xp: 10 },
            { id: "ry1-fiqur-l1-t13", type: "numeric", prompt: "Kvadratın neçə tərəfi var? (rəqəmlə)", answer: 4, xp: 10 },
            { id: "ry1-fiqur-l1-t14", type: "numeric", prompt: "Üçbucağın neçə küncü var? (rəqəmlə)", answer: 3, xp: 10 },
            { id: "ry1-fiqur-l1-t15", type: "multiple_choice", prompt: "Hansı fiqurun bütün tərəfləri bərabərdir?", options: ["kvadrat", "düzbucaqlı", "dairə", "xətt"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-fiqur-l1-b1", type: "numeric", prompt: "Bir üçbucaq və bir kvadratın tərəflərinin cəmi neçədir? (3 + 4)", answer: 7, xp: 15 },
            { id: "ry1-fiqur-l1-b2", type: "multiple_choice", prompt: "Günəş hansı fiqura oxşayır?", options: ["dairə", "kvadrat", "üçbucaq", "düzbucaqlı"], correctIndex: 0, xp: 15 },
            { id: "ry1-fiqur-l1-b3", type: "numeric", prompt: "İki üçbucağın tərəflərinin cəmi neçədir? (3 + 3)", answer: 6, xp: 15 },
            { id: "ry1-fiqur-l1-b4", type: "multiple_choice", prompt: "Dam (ev üstü) çox vaxt hansı fiqura oxşayır?", options: ["üçbucaq", "dairə", "kvadrat", "düzbucaqlı"], correctIndex: 0, xp: 15 },
            { id: "ry1-fiqur-l1-b5", type: "numeric", prompt: "İki kvadratın tərəflərinin cəmi neçədir? (4 + 4)", answer: 8, xp: 15 },
          ],
        },
        {
          id: "ry1-fiqur-l2",
          title: "Sadə mətn məsələləri",
          intro: "Kiçik məsələləri toplama və çıxma ilə həll edək.",
          sections: [
            { heading: "Məsələ", body: "Diqqətlə oxu, sonra topla və ya çıx. Məs.: 'Aylının 3 alması var, 2 də aldı. Neçə alması oldu?' → 3 + 2 = 5." },
          ],
          tasks: [
            { id: "ry1-fiqur-l2-t1", type: "numeric", prompt: "Aylının 3 alması var, 2 də aldı. Neçə alması oldu?", answer: 5, xp: 10 },
            { id: "ry1-fiqur-l2-t2", type: "numeric", prompt: "Budaqda 5 quş var idi, 2-si uçdu. Neçə quş qaldı?", answer: 3, xp: 10 },
            { id: "ry1-fiqur-l2-t3", type: "numeric", prompt: "Nərminin 4 şarı var, 1-i partladı. Neçə şar qaldı?", answer: 3, xp: 10 },
            { id: "ry1-fiqur-l2-t4", type: "numeric", prompt: "Səbətdə 2 armud var, 3 də əlavə etdik. Neçə armud oldu?", answer: 5, xp: 10 },
            { id: "ry1-fiqur-l2-t5", type: "numeric", prompt: "Elçinin 6 karandaşı var, 2-sini dostuna verdi. Neçə qaldı?", answer: 4, xp: 10 },
            { id: "ry1-fiqur-l2-t6", type: "numeric", prompt: "Bağçada 4 gül var idi, 4 də açdı. Neçə gül oldu?", answer: 8, xp: 10 },
            { id: "ry1-fiqur-l2-t7", type: "numeric", prompt: "Rəfdə 7 kitab var idi, 3-nü götürdük. Neçə kitab qaldı?", answer: 4, xp: 10 },
            { id: "ry1-fiqur-l2-t8", type: "numeric", prompt: "Leylanın 5 konfeti var, 3 də aldı. Neçə konfeti oldu?", answer: 8, xp: 10 },
            { id: "ry1-fiqur-l2-t9", type: "numeric", prompt: "Hovuzda 6 balıq var idi, 2 də əlavə etdik. Neçə balıq oldu?", answer: 8, xp: 10 },
            { id: "ry1-fiqur-l2-t10", type: "numeric", prompt: "Sinifdə 10 uşaq var idi, 4-ü evə getdi. Neçə uşaq qaldı?", answer: 6, xp: 10 },
            { id: "ry1-fiqur-l2-t11", type: "numeric", prompt: "Anarın 2 maşını var, atası 2 də aldı. Neçə maşını oldu?", answer: 4, xp: 10 },
            { id: "ry1-fiqur-l2-t12", type: "numeric", prompt: "Ağacda 8 alma var idi, 5-i düşdü. Neçə alma qaldı?", answer: 3, xp: 10 },
            { id: "ry1-fiqur-l2-t13", type: "numeric", prompt: "Zərifənin 3 dəftəri var, 4 də aldı. Neçə dəftəri oldu?", answer: 7, xp: 10 },
            { id: "ry1-fiqur-l2-t14", type: "numeric", prompt: "Qutuda 9 top var idi, 3-nü çıxartdıq. Neçə top qaldı?", answer: 6, xp: 10 },
            { id: "ry1-fiqur-l2-t15", type: "numeric", prompt: "Kaminin 5 balonu var, 5 də aldı. Neçə balonu oldu?", answer: 10, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry1-fiqur-l2-b1", type: "numeric", prompt: "Bağda 10 armud var idi, 6-sını yığdıq. Neçə armud qaldı?", answer: 4, xp: 15 },
            { id: "ry1-fiqur-l2-b2", type: "numeric", prompt: "Tünelin 7 daşı var, 3 də əlavə etdi, sonra 2-sini götürdü. Neçə daş qaldı?", answer: 8, xp: 15 },
            { id: "ry1-fiqur-l2-b3", type: "numeric", prompt: "İki dostun hərəsində 5 stiker var. Cəmi neçə stiker var?", answer: 10, xp: 15 },
            { id: "ry1-fiqur-l2-b4", type: "numeric", prompt: "Nənənin 12 yumurtası var idi, 2-si sındı. Neçə yumurta qaldı?", answer: 10, xp: 15 },
            { id: "ry1-fiqur-l2-b5", type: "numeric", prompt: "Meşədə 8 dovşan var idi, 4 də gəldi. Neçə dovşan oldu?", answer: 12, xp: 15 },
          ],
        },
      ],
    },
  ],
};
