// Riyaziyyat — 5-ci sinif proqramı. Bölmələrin sırası kurikuluma uyğundur:
// 1) Natural ədədlər  2) Adi kəsrlər  3) Onluq kəsrlər  4) Faiz/nisbət/tənasüb
// 5) Həndəsə və ölçü vahidləri  6) Məlumatların təqdimatı və ehtimal.
// Hər dərs bir layihədir (project). Standart: 15 əsas + 5 bonus tapşırıq.
// Qeyd: 1-2-ci bölmələr tamdır; 3-6-cı bölmələr struktur + qaydalar + başlanğıc
// tapşırıqlarla verilib, mərhələli olaraq 15+5-ə tamamlanacaq.

import type { Subject } from "../types";

export const math: Subject = {
  slug: "riyaziyyat",
  name: "Riyaziyyat",
  grade: 5,
  icon: "🔢",
  color: "sky",
  units: [
    // ═══════════════ 1. Natural ədədlər ═══════════════
    {
      id: "ry-natural",
      title: "Natural ədədlər və onların üzərində əməllər",
      description:
        "Natural ədədlərin oxunuşu, yazılışı, müqayisəsi; dörd əməl, qalıqlı bölmə və əməllər sırası.",
      lessons: [
        {
          id: "ry-nat-l1",
          title: "Natural ədədlərin oxunması, yazılması və müqayisəsi",
          intro: "Çoxrəqəmli natural ədədləri oxumaq, yazmaq və müqayisə etmək.",
          visual: "place-value",
          sections: [
            { heading: "Natural ədədlər nədir?", body: "Saymaq üçün işlətdiyimiz 1, 2, 3, 4, ... ədədlərinə natural ədədlər deyilir. Sıfır (0) natural ədəd sayılmır, lakin ədədləri yazarkən ondan istifadə olunur." },
            { heading: "Mərtəbələr", body: "Ədədin hər rəqəmi bir mərtəbədə durur: təklik, onluq, yüzlük, minlik və s. Məsələn, 3 254-də 3 minlik, 2 yüzlük, 5 onluq, 4 təklikdir." },
            { heading: "Oxunuşu", body: "Çoxrəqəmli ədədlər sağdan üçlüklərə (siniflərə) ayrılır: 3 254 → 'üç min iki yüz əlli dörd'." },
            { heading: "Müqayisə", body: "Rəqəm sayı çox olan ədəd böyükdür. Rəqəm sayı eynidirsə, soldan başlayaraq rəqəmləri müqayisə edirik. İşarələr: '<' kiçik, '>' böyük, '=' bərabər." },
          ],
          tasks: [
            { id: "ry-nat-l1-t1", type: "multiple_choice", prompt: "3 254 ədədində 2 rəqəmi hansı mərtəbədədir?", options: ["təklik", "onluq", "yüzlük", "minlik"], correctIndex: 2, xp: 10 },
            { id: "ry-nat-l1-t2", type: "multiple_choice", prompt: "'Yeddi min beş yüz' ədədi rəqəmlə necə yazılır?", options: ["7 500", "750", "7 050", "70 500"], correctIndex: 0, xp: 10 },
            { id: "ry-nat-l1-t3", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 4 812 ___ 4 821", accepted: ["<"], xp: 10 },
            { id: "ry-nat-l1-t4", type: "numeric", prompt: "6 208 ədədində onluq mərtəbəsindəki rəqəm neçədir?", answer: 0, xp: 10 },
            { id: "ry-nat-l1-t5", type: "multiple_choice", prompt: "Aşağıdakı ədədlərdən hansı ən böyükdür?", options: ["9 090", "9 009", "9 900", "9 099"], correctIndex: 2, xp: 10 },
            { id: "ry-nat-l1-t6", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 12 000 ___ 9 999", accepted: [">"], xp: 10 },
            { id: "ry-nat-l1-t7", type: "multiple_choice", prompt: "5 073 ədədinin oxunuşu hansıdır?", options: ["beş yüz yetmiş üç", "beş min yetmiş üç", "beş min yeddi yüz üç", "əlli min yetmiş üç"], correctIndex: 1, xp: 10 },
            { id: "ry-nat-l1-t8", type: "numeric", prompt: "8 341 ədədində minlik mərtəbəsindəki rəqəm neçədir?", answer: 8, xp: 10 },
            { id: "ry-nat-l1-t9", type: "multiple_choice", prompt: "'On iki min üç yüz' ədədi rəqəmlə necə yazılır?", options: ["12 300", "1 230", "120 300", "12 030"], correctIndex: 0, xp: 10 },
            { id: "ry-nat-l1-t10", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 6 500 ___ 6 500", accepted: ["="], xp: 10 },
            { id: "ry-nat-l1-t11", type: "multiple_choice", prompt: "Aşağıdakı ədədlərdən hansı ən kiçikdir?", options: ["4 001", "4 100", "4 010", "4 011"], correctIndex: 0, xp: 10 },
            { id: "ry-nat-l1-t12", type: "numeric", prompt: "7 000 ədədində neçə rəqəm var?", answer: 4, xp: 10 },
            { id: "ry-nat-l1-t13", type: "multiple_choice", prompt: "Hansı ədəddə 2 rəqəmi yüzlük mərtəbəsindədir?", options: ["1 253", "3 021", "5 632", "8 924"], correctIndex: 0, xp: 10 },
            { id: "ry-nat-l1-t14", type: "fill_blank", prompt: "Natural ədədlər əşyaları ___ üçün işlədilir.", accepted: ["saymaq", "saymaq üçün", "saymağa"], xp: 10 },
            { id: "ry-nat-l1-t15", type: "numeric", prompt: "999 ədədindən sonra gələn natural ədəd neçədir?", answer: 1000, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-nat-l1-b1", type: "multiple_choice", prompt: "Ən böyük dördrəqəmli natural ədəd hansıdır?", options: ["9 999", "1 000", "9 000", "10 000"], correctIndex: 0, xp: 15 },
            { id: "ry-nat-l1-b2", type: "numeric", prompt: "Ən kiçik üçrəqəmli natural ədəd neçədir?", answer: 100, xp: 15 },
            { id: "ry-nat-l1-b3", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 45 678 ___ 45 687", accepted: ["<"], xp: 15 },
            { id: "ry-nat-l1-b4", type: "multiple_choice", prompt: "60 405 ədədinin oxunuşu hansıdır?", options: ["altı min dörd yüz beş", "altmış min dörd yüz beş", "altı yüz qırx beş", "altmış min qırx beş"], correctIndex: 1, xp: 15 },
            { id: "ry-nat-l1-b5", type: "numeric", prompt: "10 000 ədədində neçə rəqəm var?", answer: 5, xp: 15 },
          ],
        },
        {
          id: "ry-nat-l2",
          title: "Çoxrəqəmli ədədlər üzərində toplama, çıxma, vurma və bölmə",
          intro: "Çoxrəqəmli natural ədədləri dörd əməllə hesablamaq.",
          visual: "column-add",
          sections: [
            { heading: "Sütun üsulu", body: "Toplama və çıxmada rəqəmləri mərtəbəyə görə alt-alta yazırıq: təkliklər təkliklərin, onluqlar onluqların altında." },
            { heading: "Toplama", body: "Sağdan (təklikdən) başlayırıq. Bir mərtəbənin cəmi 10 və ya böyükdürsə, növbəti mərtəbəyə 1 keçir (əlavə)." },
            { heading: "Çıxma", body: "Yuxarıdakı rəqəm kiçikdirsə, qonşu mərtəbədən 1 'borc' alırıq." },
            { heading: "Vurma və bölmə", body: "Vurma təkrar toplamadır: 4 × 3 = 4 + 4 + 4. Bölmə isə bərabər paylaşdırmadır: 12 : 3 = 4." },
          ],
          tasks: [
            { id: "ry-nat-l2-t1", type: "numeric", prompt: "Hesabla: 3 456 + 2 130 = ?", answer: 5586, xp: 10 },
            { id: "ry-nat-l2-t2", type: "numeric", prompt: "Hesabla: 7 802 − 3 451 = ?", answer: 4351, xp: 10 },
            { id: "ry-nat-l2-t3", type: "numeric", prompt: "Hesabla: 124 × 3 = ?", answer: 372, xp: 10 },
            { id: "ry-nat-l2-t4", type: "numeric", prompt: "Hesabla: 936 : 4 = ?", answer: 234, xp: 10 },
            { id: "ry-nat-l2-t5", type: "numeric", prompt: "Hesabla: 1 250 + 3 750 = ?", answer: 5000, xp: 10 },
            { id: "ry-nat-l2-t6", type: "numeric", prompt: "Hesabla: 5 000 − 1 234 = ?", answer: 3766, xp: 10 },
            { id: "ry-nat-l2-t7", type: "numeric", prompt: "Hesabla: 45 × 12 = ?", answer: 540, xp: 10 },
            { id: "ry-nat-l2-t8", type: "numeric", prompt: "Hesabla: 728 : 7 = ?", answer: 104, xp: 10 },
            { id: "ry-nat-l2-t9", type: "multiple_choice", prompt: "4 × 250 neçəyə bərabərdir?", options: ["1 000", "900", "1 200", "254"], correctIndex: 0, xp: 10 },
            { id: "ry-nat-l2-t10", type: "numeric", prompt: "Hesabla: 6 543 + 1 457 = ?", answer: 8000, xp: 10 },
            { id: "ry-nat-l2-t11", type: "numeric", prompt: "Hesabla: 8 100 − 2 900 = ?", answer: 5200, xp: 10 },
            { id: "ry-nat-l2-t12", type: "numeric", prompt: "Hesabla: 132 × 5 = ?", answer: 660, xp: 10 },
            { id: "ry-nat-l2-t13", type: "numeric", prompt: "Hesabla: 1 000 : 8 = ?", answer: 125, xp: 10 },
            { id: "ry-nat-l2-t14", type: "multiple_choice", prompt: "Vurma hansı əməlin qısa yazılışıdır?", options: ["toplama", "çıxma", "bölmə", "müqayisə"], correctIndex: 0, xp: 10 },
            { id: "ry-nat-l2-t15", type: "numeric", prompt: "Bir mağazaya əvvəl 1 240 kq, sonra 860 kq un gətirildi. Cəmi neçə kq un gətirildi?", answer: 2100, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-nat-l2-b1", type: "numeric", prompt: "Hesabla: 12 × 12 = ?", answer: 144, xp: 15 },
            { id: "ry-nat-l2-b2", type: "numeric", prompt: "Hesabla: 9 999 + 1 = ?", answer: 10000, xp: 15 },
            { id: "ry-nat-l2-b3", type: "numeric", prompt: "Hesabla: 4 500 : 9 = ?", answer: 500, xp: 15 },
            { id: "ry-nat-l2-b4", type: "numeric", prompt: "Hesabla: 3 × 1 000 = ?", answer: 3000, xp: 15 },
            { id: "ry-nat-l2-b5", type: "numeric", prompt: "Bir avtobusda 54 sərnişin var. 6 belə avtobusda cəmi neçə sərnişin var?", answer: 324, xp: 15 },
          ],
        },
        {
          id: "ry-nat-l3",
          title: "Qalıqlı bölmə",
          intro: "Bölmə tam alınmayanda qalıq yaranır.",
          visual: "remainder",
          sections: [
            { heading: "Qalıq nədir?", body: "Bəzən bölünən bölənə tam bölünmür. Məsələn, 17 alma 5 uşağa paylananda hərəyə 3 alma düşür, 2 alma artıq qalır. Bu 2 — qalıqdır." },
            { heading: "Yazılış", body: "17 : 5 = 3 (qalıq 2). Burada 3 qismət, 2 qalıqdır. Qalıq həmişə böləndən kiçik olmalıdır." },
            { heading: "Yoxlama", body: "Bölən × qismət + qalıq = bölünən. Yəni 5 × 3 + 2 = 17. Bu düsturla cavabı yoxlaya bilərik." },
          ],
          tasks: [
            { id: "ry-nat-l3-t1", type: "numeric", prompt: "17 : 5 əməlində qalıq neçədir?", answer: 2, xp: 10 },
            { id: "ry-nat-l3-t2", type: "numeric", prompt: "17 : 5 əməlində qismət (tam hissə) neçədir?", answer: 3, xp: 10 },
            { id: "ry-nat-l3-t3", type: "numeric", prompt: "23 : 4 əməlində qalıq neçədir?", answer: 3, xp: 10 },
            { id: "ry-nat-l3-t4", type: "numeric", prompt: "30 : 7 əməlində qalıq neçədir?", answer: 2, xp: 10 },
            { id: "ry-nat-l3-t5", type: "numeric", prompt: "45 : 6 əməlində qismət neçədir?", answer: 7, xp: 10 },
            { id: "ry-nat-l3-t6", type: "multiple_choice", prompt: "Qalıq həmişə necə olmalıdır?", options: ["böləndən böyük", "bölənə bərabər", "böləndən kiçik", "həmişə sıfır"], correctIndex: 2, xp: 10 },
            { id: "ry-nat-l3-t7", type: "numeric", prompt: "19 : 3 əməlində qalıq neçədir?", answer: 1, xp: 10 },
            { id: "ry-nat-l3-t8", type: "numeric", prompt: "50 : 8 əməlində qalıq neçədir?", answer: 2, xp: 10 },
            { id: "ry-nat-l3-t9", type: "numeric", prompt: "50 : 8 əməlində qismət neçədir?", answer: 6, xp: 10 },
            { id: "ry-nat-l3-t10", type: "numeric", prompt: "100 : 9 əməlində qalıq neçədir?", answer: 1, xp: 10 },
            { id: "ry-nat-l3-t11", type: "fill_blank", prompt: "20 : 6 = 3 (qalıq ___). Boşluğu doldur.", accepted: ["2"], xp: 10 },
            { id: "ry-nat-l3-t12", type: "numeric", prompt: "7 uşağa 30 konfet bərabər paylandı. Paylandıqdan sonra neçə konfet artıq qaldı?", answer: 2, xp: 10 },
            { id: "ry-nat-l3-t13", type: "numeric", prompt: "41 : 5 əməlində qalıq neçədir?", answer: 1, xp: 10 },
            { id: "ry-nat-l3-t14", type: "multiple_choice", prompt: "24 : 6 əməlində qalıq neçədir?", options: ["0", "1", "2", "4"], correctIndex: 0, xp: 10 },
            { id: "ry-nat-l3-t15", type: "numeric", prompt: "Yoxlama düsturu ilə hesabla: 6 × 4 + 3 = ?", answer: 27, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-nat-l3-b1", type: "numeric", prompt: "99 : 10 əməlində qalıq neçədir?", answer: 9, xp: 15 },
            { id: "ry-nat-l3-b2", type: "numeric", prompt: "62 : 7 əməlində qismət neçədir?", answer: 8, xp: 15 },
            { id: "ry-nat-l3-b3", type: "numeric", prompt: "62 : 7 əməlində qalıq neçədir?", answer: 6, xp: 15 },
            { id: "ry-nat-l3-b4", type: "fill_blank", prompt: "Qalıqlı bölmədə: bölən × qismət + ___ = bölünən.", accepted: ["qalıq", "qaliq"], xp: 15 },
            { id: "ry-nat-l3-b5", type: "numeric", prompt: "48 nəfər 5 avtobusa bərabər minir, hərəyə 9 nəfər. Neçə nəfərə yer çatmır (qalıq)?", answer: 3, xp: 15 },
          ],
        },
        {
          id: "ry-nat-l4",
          title: "Əməllər sırası və mötərizəli ifadələr",
          intro: "Bir neçə əməl olanda hansını əvvəl edirik?",
          visual: "order-ops",
          sections: [
            { heading: "Sıra qaydası", body: "Əvvəl mötərizə içindəkiləri, sonra vurma və bölməni (soldan sağa), ən sonda toplama və çıxmanı yerinə yetiririk." },
            { heading: "Mötərizə", body: "Mötərizə əməllərin sırasını dəyişir. (2 + 3) × 4 əvvəl 5, sonra 20 verir; mötərizəsiz 2 + 3 × 4 = 14 olur." },
            { heading: "Soldan sağa", body: "Eyni səviyyəli əməllər (vurma-bölmə və ya toplama-çıxma) soldan sağa aparılır." },
          ],
          tasks: [
            { id: "ry-nat-l4-t1", type: "numeric", prompt: "Hesabla: 2 + 3 × 4 = ?", answer: 14, xp: 10 },
            { id: "ry-nat-l4-t2", type: "numeric", prompt: "Hesabla: (2 + 3) × 4 = ?", answer: 20, xp: 10 },
            { id: "ry-nat-l4-t3", type: "numeric", prompt: "Hesabla: 10 − 2 × 3 = ?", answer: 4, xp: 10 },
            { id: "ry-nat-l4-t4", type: "numeric", prompt: "Hesabla: (10 − 2) × 3 = ?", answer: 24, xp: 10 },
            { id: "ry-nat-l4-t5", type: "numeric", prompt: "Hesabla: 12 : 3 + 5 = ?", answer: 9, xp: 10 },
            { id: "ry-nat-l4-t6", type: "numeric", prompt: "Hesabla: 12 : (3 + 3) = ?", answer: 2, xp: 10 },
            { id: "ry-nat-l4-t7", type: "multiple_choice", prompt: "5 + 5 × 0 neçəyə bərabərdir?", options: ["0", "5", "10", "25"], correctIndex: 1, xp: 10 },
            { id: "ry-nat-l4-t8", type: "numeric", prompt: "Hesabla: 20 − (4 + 6) = ?", answer: 10, xp: 10 },
            { id: "ry-nat-l4-t9", type: "numeric", prompt: "Hesabla: 3 × 4 + 2 × 5 = ?", answer: 22, xp: 10 },
            { id: "ry-nat-l4-t10", type: "numeric", prompt: "Hesabla: 8 + 12 : 4 = ?", answer: 11, xp: 10 },
            { id: "ry-nat-l4-t11", type: "numeric", prompt: "Hesabla: (8 + 12) : 4 = ?", answer: 5, xp: 10 },
            { id: "ry-nat-l4-t12", type: "multiple_choice", prompt: "Aşağıdakı əməllərdən hansı birinci yerinə yetirilir?", options: ["toplama", "mötərizə içindəki", "çıxma", "heç biri"], correctIndex: 1, xp: 10 },
            { id: "ry-nat-l4-t13", type: "numeric", prompt: "Hesabla: 6 × (2 + 3) = ?", answer: 30, xp: 10 },
            { id: "ry-nat-l4-t14", type: "numeric", prompt: "Hesabla: 100 − 10 × 5 = ?", answer: 50, xp: 10 },
            { id: "ry-nat-l4-t15", type: "numeric", prompt: "Hesabla: 2 × 3 + 4 × 5 = ?", answer: 26, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-nat-l4-b1", type: "numeric", prompt: "Hesabla: (7 + 3) × (6 − 2) = ?", answer: 40, xp: 15 },
            { id: "ry-nat-l4-b2", type: "numeric", prompt: "Hesabla: 50 : 5 : 2 = ?", answer: 5, xp: 15 },
            { id: "ry-nat-l4-b3", type: "numeric", prompt: "Hesabla: 4 + 4 × 4 − 4 = ?", answer: 16, xp: 15 },
            { id: "ry-nat-l4-b4", type: "numeric", prompt: "Hesabla: 3 × (10 − 2 × 3) = ?", answer: 12, xp: 15 },
            { id: "ry-nat-l4-b5", type: "numeric", prompt: "Hesabla: (12 + 8) : 4 + 6 = ?", answer: 11, xp: 15 },
          ],
        },
      ],
    },

    // ═══════════════ 2. Kəsrlər (adi kəsrlər) ═══════════════
    {
      id: "ry-fractions",
      title: "Kəsrlər (adi kəsrlər)",
      description:
        "Kəsr anlayışı, düzgün və düzgün olmayan kəsrlər, qarışıq ədədlər və eyni məxrəcli kəsrlərin toplanması-çıxılması.",
      lessons: [
        {
          id: "ry-frac-l1",
          title: "Kəsrin anlayışı: surət, məxrəc və kəsr xətti",
          intro: "Bir bütövü bərabər hissələrə böləndə kəsr alınır.",
          visual: "fraction-basic",
          sections: [
            { heading: "Kəsr nədir?", body: "Bir bütövü bərabər hissələrə böləndə kəsr alınır. Məsələn, bir şokoladı 4 bərabər hissəyə bölmək olar və hər hissə bütövün 1/4-i olar." },
            { heading: "Surət və məxrəc", body: "Kəsr xəttinin altındakı ədəd — məxrəc — bütövün neçə bərabər hissəyə bölündüyünü göstərir. Üstdəki ədəd — surət — bizim neçə hissə götürdüyümüzü göstərir. 3/4-də 4 məxrəc, 3 surətdir." },
            { heading: "Kəsr xətti = bölmə", body: "Kəsr xətti həm də bölmə deməkdir: 3/4 eyni zamanda 3 : 4 deməkdir." },
          ],
          tasks: [
            { id: "ry-frac-l1-t1", type: "multiple_choice", prompt: "3/8 kəsrində məxrəc hansı ədəddir?", figure: { kind: "fractionBar", parts: 8, filled: 3 }, options: ["3", "8", "11", "5"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l1-t2", type: "multiple_choice", prompt: "Aşağıdakı kəsrlərdən hansında surət məxrəcdən böyükdür?", options: ["2/5", "7/4", "3/8", "1/6"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l1-t3", type: "numeric", prompt: "Bir düzbucaqlı 5 bərabər hissəyə bölünüb və onlardan 2-si rənglənib. Rənglənmiş hissəni göstərən kəsrin surəti neçədir?", figure: { kind: "fractionBar", parts: 5, filled: 2 }, answer: 2, xp: 10 },
            { id: "ry-frac-l1-t4", type: "fill_blank", prompt: "Kəsr xəttinin altında yazılan ədəd ___ adlanır.", accepted: ["məxrəc", "mexrec"], xp: 10 },
            { id: "ry-frac-l1-t5", type: "numeric", prompt: "Bir bütöv 7 bərabər hissəyə bölünüb və hər 7 hissə götürülüb. 7/7 kəsri neçə tam edir?", answer: 1, xp: 10 },
            { id: "ry-frac-l1-t6", type: "multiple_choice", prompt: "3/4 kəsri hansı bölmə əməlini bildirir?", figure: { kind: "fractionBar", parts: 4, filled: 3 }, options: ["4 : 3", "3 : 4", "3 + 4", "3 × 4"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l1-t7", type: "numeric", prompt: "5/6 kəsrində surət hansı ədəddir?", figure: { kind: "fractionBar", parts: 6, filled: 5 }, answer: 5, xp: 10 },
            { id: "ry-frac-l1-t8", type: "numeric", prompt: "Bir pizza 8 bərabər hissəyə bölünüb və 5 hissəsi yeyilib. Yeyilən hissəni göstərən kəsrin surəti neçədir?", figure: { kind: "fractionBar", parts: 8, filled: 5 }, answer: 5, xp: 10 },
            { id: "ry-frac-l1-t9", type: "fill_blank", prompt: "Kəsr xəttinin üstündə yazılan ədəd ___ adlanır.", accepted: ["surət", "suret"], xp: 10 },
            { id: "ry-frac-l1-t10", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün kəsrdir (surəti məxrəcindən kiçikdir)?", options: ["3/2", "5/5", "2/7", "9/4"], correctIndex: 2, xp: 10 },
            { id: "ry-frac-l1-t11", type: "numeric", prompt: "Bir düzbucaqlı 6 bərabər hissəyə bölünüb. Bu kəsrin məxrəci neçədir?", figure: { kind: "fractionBar", parts: 6, filled: 1 }, answer: 6, xp: 10 },
            { id: "ry-frac-l1-t12", type: "multiple_choice", prompt: "4/4 kəsri neçə tam edir?", options: ["0", "1", "4", "1/4"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l1-t13", type: "fill_blank", prompt: "6/10 kəsri 6 : 10 ___ əməlini bildirir.", accepted: ["bölmə", "bolme"], xp: 10 },
            { id: "ry-frac-l1-t14", type: "numeric", prompt: "Bir tortu 10 bərabər hissəyə böldük və 3 hissə götürdük. Götürülən hissəni göstərən kəsrin surəti neçədir?", figure: { kind: "fractionBar", parts: 10, filled: 3 }, answer: 3, xp: 10 },
            { id: "ry-frac-l1-t15", type: "multiple_choice", prompt: "Kəsrdə hansı ədəd bütövün neçə bərabər hissəyə bölündüyünü göstərir?", options: ["surət", "məxrəc", "kəsr xətti", "tam hissə"], correctIndex: 1, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-frac-l1-b1", type: "multiple_choice", prompt: "7/7, 3/3 və 9/9 kəsrlərinin hamısı neçəyə bərabərdir?", options: ["0", "1", "2", "10"], correctIndex: 1, xp: 15 },
            { id: "ry-frac-l1-b2", type: "numeric", prompt: "Bir zolaq 12 bərabər hissəyə bölünüb və 7-si rənglənib. Rənglənmiş hissəni göstərən kəsrin surəti neçədir?", figure: { kind: "fractionBar", parts: 12, filled: 7 }, answer: 7, xp: 15 },
            { id: "ry-frac-l1-b3", type: "fill_blank", prompt: "Surəti məxrəcinə bərabər olan kəsr həmişə ___ tama bərabərdir. (Rəqəmlə yaz)", accepted: ["1", "bir"], xp: 15 },
            { id: "ry-frac-l1-b4", type: "multiple_choice", prompt: "Aşağıdakı kəsrlərdən hansı bütövdən böyükdür?", options: ["3/8", "8/3", "1/2", "5/6"], correctIndex: 1, xp: 15 },
            { id: "ry-frac-l1-b5", type: "numeric", prompt: "Yarım saatı 1/2 kəsri ilə göstəririk. Bu kəsrin məxrəci neçədir?", answer: 2, xp: 15 },
          ],
        },
        {
          id: "ry-frac-l2",
          title: "Düzgün və düzgün olmayan kəsrlər",
          intro: "Surəti ilə məxrəcini müqayisə edərək kəsrin növünü tapaq.",
          visual: "proper-improper",
          sections: [
            { heading: "Düzgün kəsr", body: "Surəti məxrəcindən kiçik olan kəsrə düzgün kəsr deyilir. Belə kəsr həmişə 1-dən kiçikdir. Məsələn, 3/5, 2/7." },
            { heading: "Düzgün olmayan kəsr", body: "Surəti məxrəcinə bərabər və ya ondan böyük olan kəsrə düzgün olmayan kəsr deyilir. Belə kəsr 1-ə bərabər və ya 1-dən böyükdür. Məsələn, 7/4, 5/5." },
            { heading: "Necə ayırırıq?", body: "Sadəcə surətlə məxrəci müqayisə et: surət kiçikdirsə düzgün, böyük və ya bərabərdirsə düzgün olmayan kəsrdir." },
          ],
          tasks: [
            { id: "ry-frac-l2-t1", type: "multiple_choice", prompt: "3/5 kəsri hansı növ kəsrdir?", options: ["düzgün", "düzgün olmayan", "qarışıq", "tam"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l2-t2", type: "multiple_choice", prompt: "7/4 kəsri hansı növ kəsrdir?", options: ["düzgün", "düzgün olmayan", "qarışıq", "tam"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l2-t3", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün kəsrdir?", options: ["5/3", "2/7", "9/9", "8/5"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l2-t4", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün olmayan kəsrdir?", options: ["1/2", "3/8", "6/5", "2/9"], correctIndex: 2, xp: 10 },
            { id: "ry-frac-l2-t5", type: "fill_blank", prompt: "Surəti məxrəcindən kiçik olan kəsrə ___ kəsr deyilir.", accepted: ["düzgün", "duzgun"], xp: 10 },
            { id: "ry-frac-l2-t6", type: "multiple_choice", prompt: "9/9 kəsri hansı növ kəsrdir?", options: ["düzgün", "düzgün olmayan"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l2-t7", type: "multiple_choice", prompt: "Aşağıdakı kəsrlərdən hansı 1-dən böyükdür?", options: ["3/4", "5/4", "2/3", "1/2"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l2-t8", type: "multiple_choice", prompt: "Aşağıdakı kəsrlərdən hansı 1-dən kiçikdir?", options: ["7/5", "8/8", "3/7", "9/4"], correctIndex: 2, xp: 10 },
            { id: "ry-frac-l2-t9", type: "fill_blank", prompt: "Surəti məxrəcinə bərabər və ya ondan böyük olan kəsrə düzgün ___ kəsr deyilir.", accepted: ["olmayan"], xp: 10 },
            { id: "ry-frac-l2-t10", type: "multiple_choice", prompt: "11/12 kəsri hansı növ kəsrdir?", options: ["düzgün", "düzgün olmayan"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l2-t11", type: "multiple_choice", prompt: "12/11 kəsri hansı növ kəsrdir?", options: ["düzgün", "düzgün olmayan"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l2-t12", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün kəsrdir?", options: ["6/6", "4/9", "10/3", "5/5"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l2-t13", type: "multiple_choice", prompt: "8/3 düzgün olmayan kəsri hansı ədəddən böyükdür?", options: ["1", "3", "8", "heç birindən"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l2-t14", type: "multiple_choice", prompt: "Hansı qrupda yalnız düzgün kəsrlər var?", options: ["1/2, 3/4, 2/5", "5/2, 3/4, 1/2", "7/3, 8/5, 1/2", "9/9, 4/3, 1/2"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l2-t15", type: "numeric", prompt: "5/5 kəsri neçə tam edir?", answer: 1, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-frac-l2-b1", type: "multiple_choice", prompt: "Aşağıdakılardan hansı düzgün olmayan kəsrdir?", options: ["2/3", "3/2", "1/4", "4/5"], correctIndex: 1, xp: 15 },
            { id: "ry-frac-l2-b2", type: "fill_blank", prompt: "6/6 kəsri düzgün ___ kəsrdir.", accepted: ["olmayan"], xp: 15 },
            { id: "ry-frac-l2-b3", type: "numeric", prompt: "9/4 düzgün olmayan kəsrində surət neçədir?", answer: 9, xp: 15 },
            { id: "ry-frac-l2-b4", type: "multiple_choice", prompt: "Aşağıdakı kəsrlərdən hansı tam bir ədədə bərabərdir?", options: ["3/4", "4/4", "4/3", "3/8"], correctIndex: 1, xp: 15 },
            { id: "ry-frac-l2-b5", type: "multiple_choice", prompt: "100/99 kəsri hansı növ kəsrdir?", options: ["düzgün", "düzgün olmayan"], correctIndex: 1, xp: 15 },
          ],
        },
        {
          id: "ry-frac-l3",
          title: "Qarışıq ədədlər",
          intro: "Tam hissə ilə kəsr hissədən ibarət ədədləri tanıyaq.",
          visual: "mixed-number",
          sections: [
            { heading: "Qarışıq ədəd nədir?", body: "Bir tam hissə ilə bir düzgün kəsrdən ibarət ədədə qarışıq ədəd deyilir. Məsələn, 2 tam 1/3." },
            { heading: "Düzgün olmayan kəsrdən qarışıq ədədə", body: "Surəti məxrəcə bölürük: qismət tam hissə, qalıq isə yeni surət olur. 7/3 → 7 : 3 = 2 (qalıq 1) → 2 tam 1/3." },
            { heading: "Qarışıq ədəddən kəsrə", body: "Tam hissəni məxrəcə vurub surətə əlavə edirik. 2 tam 1/3 → 2 × 3 + 1 = 7 → 7/3." },
          ],
          tasks: [
            { id: "ry-frac-l3-t1", type: "numeric", prompt: "2 tam 1/3 qarışıq ədədinin tam hissəsi neçədir?", answer: 2, xp: 10 },
            { id: "ry-frac-l3-t2", type: "numeric", prompt: "3 tam 2/5 qarışıq ədədinin tam hissəsi neçədir?", answer: 3, xp: 10 },
            { id: "ry-frac-l3-t3", type: "multiple_choice", prompt: "7/3 kəsri qarışıq ədəd kimi necə yazılır?", options: ["2 tam 1/3", "1 tam 1/3", "3 tam 1/7", "2 tam 2/3"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l3-t4", type: "multiple_choice", prompt: "2 tam 1/2 qarışıq ədədi kəsr kimi necə yazılır?", options: ["5/2", "2/2", "3/2", "4/2"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l3-t5", type: "fill_blank", prompt: "Qarışıq ədəd ___ hissə və kəsr hissədən ibarətdir.", accepted: ["tam"], xp: 10 },
            { id: "ry-frac-l3-t6", type: "numeric", prompt: "5/2 kəsrində neçə tam var (tam hissəni yaz)?", answer: 2, xp: 10 },
            { id: "ry-frac-l3-t7", type: "multiple_choice", prompt: "9/4 kəsri qarışıq ədəd kimi necə yazılır?", options: ["2 tam 1/4", "1 tam 1/4", "2 tam 3/4", "4 tam 1/9"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l3-t8", type: "multiple_choice", prompt: "1 tam 3/4 qarışıq ədədi kəsr kimi necə yazılır?", options: ["7/4", "4/4", "3/4", "5/4"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l3-t9", type: "numeric", prompt: "11/5 kəsrinin tam hissəsi neçədir?", answer: 2, xp: 10 },
            { id: "ry-frac-l3-t10", type: "multiple_choice", prompt: "3 tam 1/2 qarışıq ədədi kəsr kimi necə yazılır?", options: ["7/2", "3/2", "6/2", "5/2"], correctIndex: 0, xp: 10 },
            { id: "ry-frac-l3-t11", type: "numeric", prompt: "8/3 kəsrinin tam hissəsi neçədir?", answer: 2, xp: 10 },
            { id: "ry-frac-l3-t12", type: "multiple_choice", prompt: "Aşağıdakılardan hansı qarışıq ədəddir?", options: ["3/4", "2 tam 1/3", "5/2", "7"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l3-t13", type: "fill_blank", prompt: "10/5 kəsri sadələşəndə tam ədəd ___ olur.", accepted: ["2", "iki"], xp: 10 },
            { id: "ry-frac-l3-t14", type: "numeric", prompt: "2 tam 3/4 qarışıq ədədinin tam hissəsi neçədir?", answer: 2, xp: 10 },
            { id: "ry-frac-l3-t15", type: "multiple_choice", prompt: "13/4 kəsri qarışıq ədəd kimi necə yazılır?", options: ["3 tam 1/4", "2 tam 1/4", "3 tam 3/4", "4 tam 1/3"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-frac-l3-b1", type: "multiple_choice", prompt: "17/5 kəsri qarışıq ədəd kimi necə yazılır?", options: ["3 tam 2/5", "2 tam 2/5", "3 tam 1/5", "5 tam 2/3"], correctIndex: 0, xp: 15 },
            { id: "ry-frac-l3-b2", type: "multiple_choice", prompt: "4 tam 1/3 qarışıq ədədi kəsr kimi necə yazılır?", options: ["13/3", "12/3", "4/3", "7/3"], correctIndex: 0, xp: 15 },
            { id: "ry-frac-l3-b3", type: "numeric", prompt: "20/4 kəsri tam ədəd kimi neçəyə bərabərdir?", answer: 5, xp: 15 },
            { id: "ry-frac-l3-b4", type: "numeric", prompt: "7/2 kəsrinin tam hissəsi neçədir?", answer: 3, xp: 15 },
            { id: "ry-frac-l3-b5", type: "multiple_choice", prompt: "2 tam 5/6 qarışıq ədədi kəsr kimi necə yazılır?", options: ["17/6", "12/6", "10/6", "7/6"], correctIndex: 0, xp: 15 },
          ],
        },
        {
          id: "ry-frac-l4",
          title: "Eyni məxrəcli kəsrlərin toplanması və çıxılması",
          intro: "Məxrəcləri eyni olan kəsrləri toplamaq və çıxmaq asandır.",
          visual: "fraction-add",
          sections: [
            { heading: "Toplama", body: "Surətləri toplayırıq, məxrəc dəyişmir. Məsələn, 2/7 + 3/7 = 5/7." },
            { heading: "Çıxma", body: "Surətləri çıxırıq, məxrəc olduğu kimi qalır. Məsələn, 6/9 − 4/9 = 2/9." },
            { heading: "Diqqət", body: "Məxrəc heç vaxt toplanmır və ya çıxılmır, çünki hissələrin ölçüsü dəyişmir." },
          ],
          tasks: [
            { id: "ry-frac-l4-t1", type: "numeric", prompt: "Hesabla: 3/10 + 4/10 kəsrinin surəti neçədir?", answer: 7, xp: 10 },
            { id: "ry-frac-l4-t2", type: "multiple_choice", prompt: "2/9 + 5/9 cəmi neçəyə bərabərdir?", figure: { kind: "compareBars", a: { parts: 9, filled: 2 }, b: { parts: 9, filled: 5 } }, options: ["7/18", "7/9", "3/9", "10/9"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l4-t3", type: "numeric", prompt: "Hesabla: 6/13 − 2/13 fərqinin surəti neçədir?", answer: 4, xp: 10 },
            { id: "ry-frac-l4-t4", type: "multiple_choice", prompt: "1/6 + 2/6 + 3/6 cəmi neçəyə bərabərdir?", options: ["6/18", "6/6", "1/2", "6/12"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l4-t5", type: "numeric", prompt: "Bir səbətdəki almaların 4/12-si qırmızı, 5/12-si yaşıldır. Qırmızı və yaşıl almalar birlikdə səbətin neçə on ikidə bir hissəsini təşkil edir? (Yalnız surəti yaz)", figure: { kind: "emoji", items: ["🍎", "🍎", "🍎", "🍎", "🍏", "🍏", "🍏", "🍏", "🍏", "⚪", "⚪", "⚪"] }, answer: 9, xp: 15 },
            { id: "ry-frac-l4-t6", type: "fill_blank", prompt: "Məxrəcləri eyni olan kəsrləri toplayarkən yalnız ___ toplanır.", accepted: ["surətlər", "suretler", "surət", "suret"], xp: 10 },
            { id: "ry-frac-l4-t7", type: "numeric", prompt: "Hesabla: 4/11 + 5/11 kəsrinin surəti neçədir?", answer: 9, xp: 10 },
            { id: "ry-frac-l4-t8", type: "numeric", prompt: "Hesabla: 8/15 − 3/15 fərqinin surəti neçədir?", answer: 5, xp: 10 },
            { id: "ry-frac-l4-t9", type: "multiple_choice", prompt: "3/8 + 3/8 cəmi neçəyə bərabərdir?", options: ["6/16", "6/8", "3/8", "9/8"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l4-t10", type: "numeric", prompt: "Hesabla: 7/20 + 8/20 kəsrinin surəti neçədir?", answer: 15, xp: 10 },
            { id: "ry-frac-l4-t11", type: "fill_blank", prompt: "Eyni məxrəcli kəsrləri toplayarkən məxrəc ___ .", accepted: ["dəyişmir", "deyismir"], xp: 10 },
            { id: "ry-frac-l4-t12", type: "numeric", prompt: "Hesabla: 9/10 − 4/10 fərqinin surəti neçədir?", answer: 5, xp: 10 },
            { id: "ry-frac-l4-t13", type: "multiple_choice", prompt: "1/5 + 1/5 + 1/5 cəmi neçəyə bərabərdir?", options: ["3/15", "3/5", "1/5", "3/10"], correctIndex: 1, xp: 10 },
            { id: "ry-frac-l4-t14", type: "numeric", prompt: "Bir kitabın 3/12-si bazar günü, 4/12-si bazar ertəsi oxunub. Cəmi neçə on ikidə bir hissə oxunub? (Yalnız surəti yaz)", answer: 7, xp: 10 },
            { id: "ry-frac-l4-t15", type: "multiple_choice", prompt: "10/13 − 10/13 neçəyə bərabərdir?", options: ["0", "20/13", "10/13", "10/26"], correctIndex: 0, xp: 15 },
          ],
          bonusTasks: [
            { id: "ry-frac-l4-b1", type: "numeric", prompt: "Hesabla: 2/9 + 3/9 + 4/9 kəsrinin surəti neçədir?", answer: 9, xp: 15 },
            { id: "ry-frac-l4-b2", type: "multiple_choice", prompt: "5/6 − 2/6 − 1/6 neçəyə bərabərdir?", options: ["2/6", "8/6", "2/18", "3/6"], correctIndex: 0, xp: 15 },
            { id: "ry-frac-l4-b3", type: "fill_blank", prompt: "Eyni məxrəcli kəsrləri çıxarkən yalnız ___ çıxılır.", accepted: ["surətlər", "suretler", "surət", "suret"], xp: 15 },
            { id: "ry-frac-l4-b4", type: "numeric", prompt: "Hesabla: 11/25 + 9/25 kəsrinin surəti neçədir?", answer: 20, xp: 15 },
            { id: "ry-frac-l4-b5", type: "numeric", prompt: "Bir bütöv 7/7-dir. 7/7 − 3/7 fərqinin surəti neçədir?", answer: 4, xp: 15 },
          ],
        },
      ],
    },

    // ═══════════════ 3. Onluq kəsrlər ═══════════════
    {
      id: "ry-decimals",
      title: "Onluq kəsrlər",
      description:
        "Onluq kəsrlərin yazılışı, oxunuşu, müqayisəsi, üzərində əməllər və yuvarlaqlaşdırma.",
      lessons: [
        {
          id: "ry-dec-l1",
          title: "Onluq kəsrlərin yazılışı və oxunuşu",
          intro: "Vergüllü ədədləri yazmaq və oxumaq.",
          sections: [
            { heading: "Onluq kəsr nədir?", body: "Vergüldən sonra hissəsi olan ədədə onluq kəsr deyilir. Məsələn, 0,5; 3,25; 12,7." },
            { heading: "Mərtəbələr", body: "Vergüldən sonra birinci rəqəm onda bir, ikinci rəqəm yüzdə bir mərtəbəsidir. 0,25 = 25 yüzdə bir." },
            { heading: "Oxunuşu", body: "Tam hissə 'tam' sözü ilə ayrılır: 3,4 → 'üç tam onda dörd'." },
          ],
          tasks: [
            { id: "ry-dec-l1-t1", type: "multiple_choice", prompt: "0,7 onluq kəsrinin oxunuşu hansıdır?", options: ["sıfır tam onda yeddi", "yeddi tam", "sıfır tam yüzdə yeddi", "yeddi onluq"], correctIndex: 0, xp: 10 },
            { id: "ry-dec-l1-t2", type: "fill_blank", prompt: "'Yarım' ədədi onluq kəsrlə 0,___ kimi yazılır.", accepted: ["5"], xp: 10 },
            { id: "ry-dec-l1-t3", type: "numeric", prompt: "3,25 ədədində vergüldən sonra neçə rəqəm var?", answer: 2, xp: 10 },
            { id: "ry-dec-l1-t4", type: "multiple_choice", prompt: "2,5 onluq kəsrinin tam hissəsi neçədir?", options: ["2", "5", "25", "0"], correctIndex: 0, xp: 10 },
          ],
        },
        {
          id: "ry-dec-l2",
          title: "Onluq kəsrlərin müqayisəsi",
          intro: "İki onluq kəsrdən hansının böyük olduğunu tapaq.",
          sections: [
            { heading: "Əvvəl tam hissə", body: "Əvvəl tam hissələri müqayisə edirik. Tam hissəsi böyük olan ədəd böyükdür: 2,1 > 1,9." },
            { heading: "Sonra vergüldən sonrası", body: "Tam hissələr eynidirsə, onda bir mərtəbəsindən başlayaraq rəqəmləri müqayisə edirik." },
            { heading: "Sağdakı sıfırlar", body: "Sağdan əlavə edilən sıfır dəyəri dəyişmir: 0,3 = 0,30." },
          ],
          tasks: [
            { id: "ry-dec-l2-t1", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 0,5 ___ 0,7", accepted: ["<"], xp: 10 },
            { id: "ry-dec-l2-t2", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 0,30 ___ 0,3", accepted: ["="], xp: 10 },
            { id: "ry-dec-l2-t3", type: "multiple_choice", prompt: "Hansı ədəd daha böyükdür: 1,2 yoxsa 1,15?", options: ["1,2", "1,15", "bərabərdir"], correctIndex: 0, xp: 10 },
            { id: "ry-dec-l2-t4", type: "fill_blank", prompt: "Uyğun işarəni yaz ('<', '>' və ya '='): 2,45 ___ 2,54", accepted: ["<"], xp: 10 },
          ],
        },
        {
          id: "ry-dec-l3",
          title: "Onluq kəsrlər üzərində toplama, çıxma, vurma və bölmə",
          intro: "Onluq kəsrləri hesablamaq.",
          sections: [
            { heading: "Toplama və çıxma", body: "Vergülləri düz alt-alta gətirib adi qayda ilə toplayıb-çıxırıq. Cavabda vergül eyni sırada qalır." },
            { heading: "Vurma", body: "Əvvəl vergülü nəzərə almadan vururuq, sonra hasilarda vergüldən sonrakı rəqəm sayını qoyuruq." },
            { heading: "Diqqət", body: "Sütun üsulunda vergüllər həmişə düz bir sırada olmalıdır." },
          ],
          tasks: [
            { id: "ry-dec-l3-t1", type: "numeric", prompt: "Hesabla: 0,5 + 0,3 = ?", answer: 0.8, xp: 10 },
            { id: "ry-dec-l3-t2", type: "numeric", prompt: "Hesabla: 1,2 + 2,3 = ?", answer: 3.5, xp: 10 },
            { id: "ry-dec-l3-t3", type: "numeric", prompt: "Hesabla: 5,5 − 2,5 = ?", answer: 3, xp: 10 },
            { id: "ry-dec-l3-t4", type: "numeric", prompt: "Hesabla: 0,2 × 3 = ?", answer: 0.6, xp: 10 },
          ],
        },
        {
          id: "ry-dec-l4",
          title: "Onluq kəsrlərin yuvarlaqlaşdırılması",
          intro: "Onluq kəsri ən yaxın tam və ya mərtəbəyə gətirmək.",
          sections: [
            { heading: "Yuvarlaqlaşdırma nədir?", body: "Ədədi ən yaxın tam və ya mərtəbəyə gətirməkdir. Bu, təxmini hesablamalarda işə yarayır." },
            { heading: "Qayda", body: "Atılan ilk rəqəm 5 və ya böyükdürsə, əvvəlki rəqəm 1 artır; 5-dən kiçikdirsə, dəyişmir." },
            { heading: "Nümunə", body: "3,7 → 4 (çünki 7 ≥ 5); 3,2 → 3 (çünki 2 < 5)." },
          ],
          tasks: [
            { id: "ry-dec-l4-t1", type: "multiple_choice", prompt: "3,7 ədədini tam ədədə qədər yuvarlaqlaşdır.", options: ["3", "4", "5", "7"], correctIndex: 1, xp: 10 },
            { id: "ry-dec-l4-t2", type: "multiple_choice", prompt: "2,3 ədədini tam ədədə qədər yuvarlaqlaşdır.", options: ["2", "3", "1", "23"], correctIndex: 0, xp: 10 },
            { id: "ry-dec-l4-t3", type: "numeric", prompt: "5,49 ədədini onda birə qədər yuvarlaqlaşdır (nəticəni yaz).", answer: 5.5, xp: 10 },
            { id: "ry-dec-l4-t4", type: "multiple_choice", prompt: "0,5 ədədini tam ədədə yuvarlaqlaşdırdıqda nə alınır?", options: ["0", "1", "0,5", "5"], correctIndex: 1, xp: 10 },
          ],
        },
      ],
    },

    // ═══════════════ 4. Faiz, nisbət və tənasüb ═══════════════
    {
      id: "ry-percent",
      title: "Faiz, nisbət və tənasüb",
      description:
        "Faiz anlayışı, ədədin faizinin tapılması, faizinə görə ədədin tapılması, nisbət və tənasübə ilkin giriş.",
      lessons: [
        {
          id: "ry-per-l1",
          title: "Faiz anlayışı və ədədin faizinin tapılması",
          intro: "Faiz nədir və ədədin faizini necə tapırıq?",
          sections: [
            { heading: "Faiz nədir?", body: "Faiz 'yüzdə' deməkdir. 1% bütövün yüz bərabər hissəsindən biridir. İşarəsi: %." },
            { heading: "Bəzi faizlər", body: "50% = yarısı, 25% = dörddə biri, 100% = bütövü." },
            { heading: "Ədədin faizi", body: "Ədədi 100-ə bölüb faizə vururuq. 200-ün 10%-i: 200 : 100 × 10 = 20." },
          ],
          tasks: [
            { id: "ry-per-l1-t1", type: "numeric", prompt: "200-ün 10%-i neçədir?", answer: 20, xp: 10 },
            { id: "ry-per-l1-t2", type: "numeric", prompt: "50-nin 50%-i neçədir?", answer: 25, xp: 10 },
            { id: "ry-per-l1-t3", type: "numeric", prompt: "80-in 25%-i neçədir?", answer: 20, xp: 10 },
            { id: "ry-per-l1-t4", type: "multiple_choice", prompt: "100% bir ədədin nə qədərini təşkil edir?", options: ["yarısını", "hamısını", "dörddə birini", "onda birini"], correctIndex: 1, xp: 10 },
          ],
        },
        {
          id: "ry-per-l2",
          title: "Faizinə görə ədədin tapılması",
          intro: "Ədədin faizi məlumdur — ədədin özünü tapaq.",
          sections: [
            { heading: "Tərs məsələ", body: "Bu dəfə ədədin faizi verilir, biz ədədin özünü tapırıq." },
            { heading: "Qayda", body: "Verilən hissəni faizə bölüb 100-ə vururuq. 10%-i 5 olan ədəd: 5 : 10 × 100 = 50." },
          ],
          tasks: [
            { id: "ry-per-l2-t1", type: "numeric", prompt: "Bir ədədin 10%-i 5-dir. Ədəd neçədir?", answer: 50, xp: 10 },
            { id: "ry-per-l2-t2", type: "numeric", prompt: "Bir ədədin 20%-i 10-dur. Ədəd neçədir?", answer: 50, xp: 10 },
            { id: "ry-per-l2-t3", type: "numeric", prompt: "Bir ədədin 50%-i 30-dur. Ədəd neçədir?", answer: 60, xp: 10 },
            { id: "ry-per-l2-t4", type: "numeric", prompt: "Bir ədədin 100%-i 45-dir. Ədəd neçədir?", answer: 45, xp: 10 },
          ],
        },
        {
          id: "ry-per-l3",
          title: "Nisbət və tənasüb anlayışına ilkin giriş",
          intro: "İki ədədi nisbətlə müqayisə etmək.",
          sections: [
            { heading: "Nisbət nədir?", body: "İki ədədin bölmə yolu ilə müqayisəsidir: a : b. Məsələn, sinifdə 2 oğlan, 4 qız varsa, nisbət 2 : 4-dür." },
            { heading: "Sadələşmə", body: "Nisbəti kəsr kimi sadələşdirmək olar: 2 : 4 = 1 : 2." },
            { heading: "Tənasüb", body: "İki bərabər nisbətə tənasüb deyilir: 1 : 2 = 2 : 4." },
          ],
          tasks: [
            { id: "ry-per-l3-t1", type: "multiple_choice", prompt: "2 : 4 nisbəti sadələşəndə nə olur?", options: ["1 : 2", "2 : 1", "1 : 4", "4 : 2"], correctIndex: 0, xp: 10 },
            { id: "ry-per-l3-t2", type: "multiple_choice", prompt: "10 : 5 nisbəti sadələşəndə nə olur?", options: ["2 : 1", "1 : 2", "5 : 1", "10 : 1"], correctIndex: 0, xp: 10 },
            { id: "ry-per-l3-t3", type: "fill_blank", prompt: "Tənasübü tamamla: 1 : 2 = 3 : ___", accepted: ["6"], xp: 10 },
            { id: "ry-per-l3-t4", type: "multiple_choice", prompt: "6 : 9 nisbəti sadələşəndə nə olur?", options: ["2 : 3", "3 : 2", "1 : 3", "6 : 3"], correctIndex: 0, xp: 10 },
          ],
        },
      ],
    },

    // ═══════════════ 5. Həndəsə və ölçü vahidləri ═══════════════
    {
      id: "ry-geometry",
      title: "Həndəsə elementləri və ölçü vahidləri",
      description:
        "Nöqtə, xətt, bucaq; üçbucaq və dördbucaqlılar; perimetr, sahə, həcm və ölçü vahidləri.",
      lessons: [
        {
          id: "ry-geo-l1",
          title: "Nöqtə, düz xətt, şüa, parça və bucaqlar",
          intro: "Həndəsənin əsas elementləri ilə tanış olaq.",
          sections: [
            { heading: "Əsas elementlər", body: "Nöqtə ölçüsüz işarədir. Düz xəttin sonu yoxdur. Parçanın iki ucu var. Şüanın bir ucu var, digər tərəfə sonsuz uzanır." },
            { heading: "Bucaq", body: "İki şüanın bir nöqtədən çıxması bucaq əmələ gətirir. Bucaq dərəcə (°) ilə ölçülür." },
            { heading: "Bucaq növləri", body: "İti bucaq 90°-dən kiçik, düz bucaq 90°, kor bucaq 90°-dən böyükdür." },
          ],
          tasks: [
            { id: "ry-geo-l1-t1", type: "multiple_choice", prompt: "İki ucu olan həndəsi elementə nə deyilir?", options: ["parça", "şüa", "düz xətt", "nöqtə"], correctIndex: 0, xp: 10 },
            { id: "ry-geo-l1-t2", type: "multiple_choice", prompt: "90°-lik bucaq necə adlanır?", options: ["iti", "düz", "kor", "dolğun"], correctIndex: 1, xp: 10 },
            { id: "ry-geo-l1-t3", type: "multiple_choice", prompt: "90°-dən kiçik bucaq necə adlanır?", options: ["iti", "düz", "kor", "tam"], correctIndex: 0, xp: 10 },
            { id: "ry-geo-l1-t4", type: "numeric", prompt: "Düz bucaq neçə dərəcədir?", answer: 90, xp: 10 },
          ],
        },
        {
          id: "ry-geo-l2",
          title: "Üçbucaqlar və onların növləri",
          intro: "Üçbucaqları tərəflərinə görə tanıyaq.",
          sections: [
            { heading: "Üçbucaq", body: "Üç tərəfi və üç təpəsi olan həndəsi fiqurdur." },
            { heading: "Tərəflərinə görə", body: "Bərabərtərəfli (üç tərəf bərabər), bərabəryanlı (iki tərəf bərabər), müxtəliftərəfli (tərəflər fərqli)." },
            { heading: "Bucaqların cəmi", body: "İstənilən üçbucağın daxili bucaqlarının cəmi 180°-dir." },
          ],
          tasks: [
            { id: "ry-geo-l2-t1", type: "multiple_choice", prompt: "Üç tərəfi də bərabər olan üçbucaq necə adlanır?", options: ["bərabərtərəfli", "bərabəryanlı", "müxtəliftərəfli", "düzbucaqlı"], correctIndex: 0, xp: 10 },
            { id: "ry-geo-l2-t2", type: "multiple_choice", prompt: "İki tərəfi bərabər olan üçbucaq necə adlanır?", options: ["bərabərtərəfli", "bərabəryanlı", "müxtəliftərəfli", "kvadrat"], correctIndex: 1, xp: 10 },
            { id: "ry-geo-l2-t3", type: "numeric", prompt: "Üçbucağın daxili bucaqlarının cəmi neçə dərəcədir?", answer: 180, xp: 10 },
            { id: "ry-geo-l2-t4", type: "numeric", prompt: "Üçbucağın neçə tərəfi var?", answer: 3, xp: 10 },
          ],
        },
        {
          id: "ry-geo-l3",
          title: "Dördbucaqlılar (düzbucaqlı, kvadrat)",
          intro: "Dörd tərəfli fiqurları tanıyaq.",
          sections: [
            { heading: "Dördbucaqlı", body: "Dörd tərəfi və dörd təpəsi olan fiqurdur." },
            { heading: "Düzbucaqlı", body: "Qarşı tərəfləri bərabər olan və bütün bucaqları 90° olan dördbucaqlıdır." },
            { heading: "Kvadrat", body: "Bütün tərəfləri bərabər olan düzbucaqlıdır." },
          ],
          tasks: [
            { id: "ry-geo-l3-t1", type: "multiple_choice", prompt: "Bütün tərəfləri bərabər olan dördbucaqlı necə adlanır?", options: ["kvadrat", "düzbucaqlı", "üçbucaq", "dairə"], correctIndex: 0, xp: 10 },
            { id: "ry-geo-l3-t2", type: "numeric", prompt: "Kvadratın neçə tərəfi var?", answer: 4, xp: 10 },
            { id: "ry-geo-l3-t3", type: "multiple_choice", prompt: "Düzbucaqlının bucaqları neçə dərəcədir?", options: ["90", "60", "180", "45"], correctIndex: 0, xp: 10 },
            { id: "ry-geo-l3-t4", type: "numeric", prompt: "Düzbucaqlının neçə bucağı var?", answer: 4, xp: 10 },
          ],
        },
        {
          id: "ry-geo-l4",
          title: "Perimetr və sahənin hesablanması",
          intro: "Fiqurun ətrafını və tutduğu yeri hesablamaq.",
          sections: [
            { heading: "Perimetr", body: "Fiqurun bütün tərəflərinin uzunluqları cəmidir. Düzbucaqlı üçün P = 2 × (a + b)." },
            { heading: "Sahə", body: "Fiqurun tutduğu yerdir. Düzbucaqlı üçün S = a × b, kvadrat üçün S = a × a." },
            { heading: "Vahidlər", body: "Perimetr sm, m ilə; sahə sm², m² ilə ölçülür." },
          ],
          tasks: [
            { id: "ry-geo-l4-t1", type: "numeric", prompt: "Tərəfləri 3 və 5 olan düzbucaqlının perimetrini tap.", answer: 16, xp: 10 },
            { id: "ry-geo-l4-t2", type: "numeric", prompt: "Tərəfləri 3 və 5 olan düzbucaqlının sahəsini tap.", answer: 15, xp: 10 },
            { id: "ry-geo-l4-t3", type: "numeric", prompt: "Tərəfi 4 olan kvadratın perimetrini tap.", answer: 16, xp: 10 },
            { id: "ry-geo-l4-t4", type: "numeric", prompt: "Tərəfi 4 olan kvadratın sahəsini tap.", answer: 16, xp: 10 },
          ],
        },
        {
          id: "ry-geo-l5",
          title: "Həcm anlayışı (paralelepiped və kubun həcmi)",
          intro: "Cismin tutduğu fəzanı hesablamaq.",
          sections: [
            { heading: "Həcm", body: "Cismin tutduğu fəzadır. Kubik vahidlərlə (sm³, m³) ölçülür." },
            { heading: "Paralelepiped", body: "Düzbucaqlı paralelepipedin həcmi: V = uzunluq × en × hündürlük (a × b × c)." },
            { heading: "Kub", body: "Kubun bütün tilləri bərabərdir, ona görə V = a × a × a." },
          ],
          tasks: [
            { id: "ry-geo-l5-t1", type: "numeric", prompt: "Ölçüləri 2, 3 və 4 olan düzbucaqlı paralelepipedin həcmini tap.", answer: 24, xp: 10 },
            { id: "ry-geo-l5-t2", type: "numeric", prompt: "Tili 3 olan kubun həcmini tap.", answer: 27, xp: 10 },
            { id: "ry-geo-l5-t3", type: "numeric", prompt: "Tili 2 olan kubun həcmini tap.", answer: 8, xp: 10 },
            { id: "ry-geo-l5-t4", type: "multiple_choice", prompt: "Həcm hansı vahidlə ölçülür?", options: ["sm³", "sm", "sm²", "dərəcə"], correctIndex: 0, xp: 10 },
          ],
        },
        {
          id: "ry-geo-l6",
          title: "Uzunluq, kütlə, zaman və sahə ölçü vahidləri",
          intro: "Gündəlik ölçü vahidlərini və çevrilmələri bilmək.",
          sections: [
            { heading: "Uzunluq", body: "1 m = 100 sm, 1 km = 1000 m." },
            { heading: "Kütlə", body: "1 kq = 1000 q, 1 ton = 1000 kq." },
            { heading: "Zaman", body: "1 saat = 60 dəqiqə, 1 dəqiqə = 60 saniyə, 1 gün = 24 saat." },
          ],
          tasks: [
            { id: "ry-geo-l6-t1", type: "numeric", prompt: "1 metr neçə santimetrdir?", answer: 100, xp: 10 },
            { id: "ry-geo-l6-t2", type: "numeric", prompt: "1 kiloqram neçə qramdır?", answer: 1000, xp: 10 },
            { id: "ry-geo-l6-t3", type: "numeric", prompt: "1 saat neçə dəqiqədir?", answer: 60, xp: 10 },
            { id: "ry-geo-l6-t4", type: "numeric", prompt: "1 gün neçə saatdır?", answer: 24, xp: 10 },
          ],
        },
      ],
    },

    // ═══════════════ 6. Məlumatların təqdimatı və ehtimal ═══════════════
    {
      id: "ry-data",
      title: "Məlumatların təqdim olunması və ehtimal",
      description:
        "Sütunlu və dairəvi diaqramlar, cədvəllərlə işləmə və sadə ehtimal hadisələri.",
      lessons: [
        {
          id: "ry-data-l1",
          title: "Diaqramlar (sütunlu və dairəvi diaqramlar)",
          intro: "Məlumatı diaqramla oxumaq.",
          sections: [
            { heading: "Diaqram", body: "Məlumatı şəkillə göstərmək üsuludur; kəmiyyətləri tez müqayisə etməyə imkan verir." },
            { heading: "Sütunlu diaqram", body: "Hər sütunun hündürlüyü kəmiyyəti göstərir. Uzun sütun böyük dəyər deməkdir." },
            { heading: "Dairəvi diaqram", body: "Bütövün hissələrini 'dilim' kimi göstərir; bütöv 100%-ə bərabərdir." },
          ],
          tasks: [
            { id: "ry-data-l1-t1", type: "multiple_choice", prompt: "Sütunlu diaqramda ən böyük dəyəri hansı sütun göstərir?", options: ["ən uzun", "ən qısa", "ortadakı", "birinci"], correctIndex: 0, xp: 10 },
            { id: "ry-data-l1-t2", type: "multiple_choice", prompt: "Bütövün hissələrini dilimlərlə göstərən diaqram hansıdır?", options: ["dairəvi", "sütunlu", "xətti", "cədvəl"], correctIndex: 0, xp: 10 },
            { id: "ry-data-l1-t3", type: "multiple_choice", prompt: "Diaqramlar əsasən nə üçün istifadə olunur?", options: ["məlumatı müqayisə etmək", "rəsm çəkmək", "kitab oxumaq", "saymaq"], correctIndex: 0, xp: 10 },
            { id: "ry-data-l1-t4", type: "numeric", prompt: "Bir dairəvi diaqram tam olaraq neçə faizi göstərir?", answer: 100, xp: 10 },
          ],
        },
        {
          id: "ry-data-l2",
          title: "Cədvəllərlə işləmə",
          intro: "Cədvəldəki məlumatı oxumaq və hesablamaq.",
          sections: [
            { heading: "Cədvəl", body: "Məlumatı sətir və sütunlarda nizamla göstərir." },
            { heading: "Oxumaq", body: "Lazımi məlumatı uyğun sətir və sütunun kəsişməsində tapırıq." },
            { heading: "İstifadə", body: "Cədvəldəki rəqəmlərlə cəm, fərq və müqayisə hesablamaq olar." },
          ],
          tasks: [
            { id: "ry-data-l2-t1", type: "multiple_choice", prompt: "Cədvəl məlumatı necə göstərir?", options: ["sətir və sütunlarda", "dairələrdə", "yalnız xətlərlə", "yalnız rənglərlə"], correctIndex: 0, xp: 10 },
            { id: "ry-data-l2-t2", type: "numeric", prompt: "3 gün ərzində satılan kitablar: 5, 8, 7. Cəmi neçə kitab satılıb?", answer: 20, xp: 10 },
            { id: "ry-data-l2-t3", type: "numeric", prompt: "Yuxarıdakı məlumata görə bir gündə ən çox neçə kitab satılıb?", answer: 8, xp: 10 },
            { id: "ry-data-l2-t4", type: "numeric", prompt: "Ən çox və ən az satılan günlər arasında neçə kitab fərq var?", answer: 3, xp: 10 },
          ],
        },
        {
          id: "ry-data-l3",
          title: "Sadə ehtimal hadisələri",
          intro: "Bir hadisənin baş vermə şansını qiymətləndirmək.",
          sections: [
            { heading: "Ehtimal", body: "Bir hadisənin baş vermə şansıdır. 'Mümkün deyil', 'az mümkün', 'mütləq' kimi qiymətləndirilir." },
            { heading: "Pul atmaq", body: "Pul atanda 'gerb' və ya 'yazı' — 2 mümkün nəticədən biri alınır." },
            { heading: "Zər atmaq", body: "Zər atanda 6 mümkün nəticə var (1-dən 6-ya qədər)." },
          ],
          tasks: [
            { id: "ry-data-l3-t1", type: "numeric", prompt: "Bir zər atılanda neçə mümkün nəticə var?", answer: 6, xp: 10 },
            { id: "ry-data-l3-t2", type: "numeric", prompt: "Pul atılanda neçə mümkün nəticə var?", answer: 2, xp: 10 },
            { id: "ry-data-l3-t3", type: "multiple_choice", prompt: "'Sabah günəş şərqdən çıxacaq' hadisəsi necə hadisədir?", options: ["mütləq", "mümkün deyil", "az mümkün", "qeyri-mümkün"], correctIndex: 0, xp: 10 },
            { id: "ry-data-l3-t4", type: "multiple_choice", prompt: "Adi zər atılanda 7 gəlməsi necə hadisədir?", options: ["mümkün deyil", "mütləq", "çox mümkün", "adi"], correctIndex: 0, xp: 10 },
          ],
        },
      ],
    },
  ],
};
